- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
> SqlServer: Generate literal for datetime type correctly

- src/EFCore.Design/Scaffolding/Internal/CSharpUtilities.cs
- src/EFCore.Design/Scaffolding/Internal/ICSharpUtilities.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpUtilitiesTest.cs
Scaffolding database enums involves generating fluent API calls which accept an array (the label list for the enum), this is currently unsupported.
> [Preview2] Generate array literals in CSharpUtilies

- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
#11288 - Query: Join/GroupJoin where key selectors are qsres or navigations fails during compilation
#10974 - Query: Include Collection group by reference throws exception
#11245 - Query: compilation error for queries with join where the inner key is navigation
#11022 - Query: GroupJoin with a complex join key fails during compilation
#9481 - EF Core joining on the wrong field when using GroupBy
- Added step to the QueryOptimizer that converts entity qsre comparison to key comparisons instead for order by join and group join,
- Improved logic of join/groupjoin inner key navigation rewrite to correctly handle case when navigation is the final operator (i.e. no scalar is projected at the end),
- Improved "requires materialization" logic to correctly mark qsre projected out of subquery that …
> Fix to issues around entity comparisons in query

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
As mentioned in #11324, [MigrationsModelDiffer unwraps enums to their underlying integral types](https://github.com/aspnet/EntityFrameworkCore/blob/13b4f7da77f6cad405f08d9b74d4d168ad382154/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L954). This causes migrations to be generated as `table.Column<int>(nullable: false)` instead of the actual type. The ModelSnapshot *does* contain the enum CLR type rather than int.
Strangely, this doesn't seem to affect the type of the column created in the database - running the migration with `Column<int>` does actually cause a PostgreSQL enum column to be created. I'm not sure exactly what's going on - I'm guessing that the model is consulted when running the migration, but I'm wondering if this won't interfere in other scenarios.
It …
> Don't unwrap enums in MigrationsModelDiffer

- src/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
> Allow to override a navigation property discovered by convention with a property on the principal side.

- src/EFCore.Relational/Migrations/Internal/Migrator.cs
Summary of the changes:
- Made "PopulateMigrations" method protected in Migrator.cs (this method is used in public virtual GenerateScript method, so it can be useful in descendants).
> Migrator.cs refactored - "PopulateMigrations" method made protected

- src/EFCore.Relational/Storage/Internal/FallbackRelationalTypeMappingSource.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore/Storage/TypeMappingInfo.cs
- src/EFCore/Storage/TypeMappingSource.cs
Also, stop providers from using Property directly when determining a type mapping so that providers build type mappings with the same information that is used to cache them.
Fixes #11358
> Stop using Property to cache type mappings

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Design/Internal/MigrationsOperations.cs
- src/EFCore.Design/Scaffolding/IReverseEngineerScaffolder.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
This can happen when using an older tool with a newer runtime.
Fixes #11075
> Design: Allow unspecified project language

- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/ServicePropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalServicePropertyBuilder.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Metadata/Internal/ServiceProperty.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Conventions/Internal/ConstructorBindingConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ServicePropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeBaseTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Make Ignore, conventions, properties and navigations treat service properties consistently.
Break up EntityTypeTest
Fixes #11351
> Add internal builder for service properties.

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/dotnet-ef/RootCommand.cs
- src/ef/Commands/MigrationsScriptCommand.cs
- src/ef/Commands/ProjectCommandBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
This passes the working directory of `dotnet ef` and the PMC commands to `ef.exe` so we can use it to resolve some relative paths (currently just `--output` on `ef migrations script`)
Fixes #10036
> Tools: Make the migration script path relative to the current directory

- test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
Increase timeout for async database creation tests
Issue:
The test mimics exception for first 5 attempts and passes on 6th attempt. We retry at interval of 1ms. Total duration before timeout is 1 minute.
In case of async test, if the thread is not scheduled to run at least 6 time in 1 min timeout period, we would not be able to reach 6th attempt and hence throw exception.
Resolves #11443
> Is it flaky or flakey?

- src/EFCore.Relational/Query/ExpressionVisitors/Internal/SubqueryProjectingSingleValueOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Sql naturally returns null for subqueries that contain no results.
Fix is to recognize the pattern and add COALESCE around it, and in case original term results in null return default value for that type instead.
> Fix to #10294 - Query: FirstOrDefault on empty collection returning a value type tries to return null instead of default

- samples/OracleProvider/src/OracleProvider/Metadata/OraclePropertyAnnotations.cs
- src/EFCore.Relational/Storage/ValueConversion/RelationalConverterMappingHints.cs
- src/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- src/EFCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
- src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationsAnnotationProvider.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/CoreTypeMapping.cs
- src/EFCore/Storage/ValueConversion/ConverterMappingHints.cs
- src/EFCore/Storage/ValueConversion/GuidToBytesConverter.cs
- src/EFCore/Storage/ValueConversion/GuidToStringConverter.cs
- src/EFCore/ValueGeneration/ValueGeneratorSelector.cs
Fixes #11010
Approach is:
* Throw by default if a converter is associated with a property that will use value generation
* However, a value generator to use can be specified:
* On the property
* On the type mapping
* On a converter
* A client-side generator is added to the Guid converters so that Guid key scenarios still work
> Handle value generation when value conversion is being used

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- src/EFCore/Query/Internal/ExpressionPrinter.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- Introduce rewrite for reference navigation (which was being done in nav expansion before)
- Disallow rewrite for owned entities (forces client eval for now) See #11485
- Streamline rewrite between Equals method & `==`
- Convert to false when 2 unrelated entityTypes are being compared
Resolves #11165
> Query: Improvements to EntityEqualityRewritingExpressionVisitor

- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/dotnet-ef/RootCommand.cs
Note, you'll still get errors when using EF Core 1.x on .NET Core 2. And there are still ways to get crashes with the PMC Tools. But hopefully this covers most cases.
Fixes #9984
> CLI Tools: Error when targeting netcoreapp1.x

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Migrations: Preserve MaxIdentifierLength in snapshot

- src/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerRetryingExecutionStrategy.cs
Properly ignore some tests on SQL Azure
> Ensure AUTO_CLOSE is OFF before creating memory-optimized tables

- src/EFCore.DocumentDb/EFCore.DocumentDb.csproj
- version.props
Stabilized builds failed because when IsFinalBuild=true, the version of the DocumentDb package did not align with its assembly versions.
@Eilon @ajcvickers - required for preview2
> Fix package version for DocumentDb when IsFinalBuild=true

- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
We fixed validation in DI and it found misconfigured service lifetime:
```
Cannot consume scoped service 'Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory' from singleton 'Microsoft.EntityFrameworkCore.Query.Sql.QuerySqlGeneratorDependencies'.
```
> Fix lifetime of IRelationalCommandBuilderFactory in test

- src/EFCore.Specification.Tests/ConvertToProviderTypesTestBase.cs
- src/EFCore.Specification.Tests/CustomConvertersTestBase.cs
While implementing some missing tests in Npgsql, `ConvertToProvider.Can_insert_and_read_with_max_length_set()`failed. After some investigation, it turns out that it's trying to insert the 9000-long `ByteArray9000` field into a database string column (converting with base64), but the database field is a `varchar(9000)` (BuiltInDataTypesFixtureBase sets MaxLength to LongStringLength). However, the base64 representation of the 9000 bytes ends up being more than 9000 characters, but the column is limited to 9000.
I'm guessing that on SQL Server the column's type is `varchar(max)`, so the limit doesn't actually get enforced. This PR doubles the character capacity of the column.
> Increase test column size to accommodate base64 data

- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/DbFunctionsOracleTest.cs
- src/EFCore.Specification.Tests/Query/DbFunctionsTestBase.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerFreeTextMethodCallTranslator.cs
- src/EFCore.SqlServer/SqlServerDbFunctionsExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs
Throw better exception when using non property as first arg.
Resolves #11481
> Query: Refine FreeText function for SqlServer

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Extensions/Internal/DbContextDependenciesExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/ExpressionVisitors/Internal/ModelExpressionApplyingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/Internal/IQueryModelGenerator.cs
- src/EFCore/Query/Internal/QueryCompiler.cs
- src/EFCore/Query/Internal/QueryModelGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- Validate that a query only uses a single EF IQueryProvider instance.
> Fix #11101 - The value can not be NULL. Parameter name: entityType

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
Only the first command will be used to determine batch dependencies. This will work fine unless there are other unique index or foreign key dependencies between the involved commands.
Fixes #11505
> Allow duplicate values for unique indexes.

- src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Also fixes related issues:
#10946 - ArgumentOutOfRangeException when ordering by a constant in collection include
#11525 - Query: order by anonymous object is silently ignored
Problem was that when a constant was part of the projection, we were never incorporating it into the SQL, but rather materialize it on the client. This is incorrect in case of subquery, since other queries could depend on that constant projection.
Example is include collection with order by a constant - as part of include rewrite we generate a subquery whose projection consists of all the orderings from the outer query, and the collection query is ordered by the elements in the projection. Since before constants were not translated into sql, the resulting query was incorrect, trying to order by element that didnt …
> Fix to #11459 - Query: incorrect data returned for queries projecting a single constant from a subquery

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- src/EFCore/Query/Internal/QueryOptimizer.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- Fix over aggressive subquery elimination in QueryOptimizer.
> Fix #11033 - Issue when using EFCore with Automapper's ProjectTo and Unions

- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- src/EFCore/ChangeTracking/NavigationEntry.cs
- test/EFCore.SqlServer.FunctionalTests/CompositeKeyEndToEndTest.cs
> Don't mark as modified the PK overlapping FK portion when using navigation entries.

- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
Part of #11599
This enables logging output of QueryModel & QueryExecution plan for further investigation
> Test: Enable logging around flaky test

- src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- Fixed issue, forced client-eval for equality of owned navs.
> Fix #11485 - Query: Entity equality rewrite on owned entities

- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Query: Async Collection Include produces invalid subquery with complex OrderBy
Issue: Current pipeline fails at lifting inner subquery in collection querymodel for async case. This causes client side join.
The OrderBy clause were dependent on inner subquery projection (through AnonymousObject). And while translating them we did not consider that select expression could be different.
Hence we added ordering to wrong select expression generating invalid SQL.
Resolves #10430
Resolves #11037
> 🔥 One liner bug fix - Challenge accepted 🔥 

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
Issue: Since Weak query fixture defines level2-4 as weak entities, dbset for Level4 needs to be retrived by constructing query from Level1 root. This query further composed with same expression as Level4_include caused query cache hit.
Since both the queries were using different SQL (table alias name difference), depending on the order of test run, it was causing SQL assertion failure.
Since this particular query is already being covered by other test, removing test for Weak types
Resolves #11599
> Query: Remove Level4_include for Weak Entities

- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Issue: Due to anonymous object we aliased projections. When wrapping the expression insider aggregate function, this generates invalid sql.
The same could happen with aggregate operation without group by too. Due to relinq optimizations, unable to write such a test.
Resolves #11636
Also added fixed issue with doing multiple select with first being on anonymous type.
> Query: Anonymous object group by causes invalid SQL

- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/DbContext.cs
- src/EFCore/DbSet`.cs
> Clarify documentation for setting state of single Entity

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/Metadata/Conventions/Internal/NavigationAttributeEntityTypeConvention.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Match the correct source property for a given type when diffing seed data
Fixes #11607
> Use the correct model builder for seed data in model snapshot

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateTimeMemberTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Fixes #11594.
* Implemented translation and test of `DateTimeOffset.Now` to `SYSDATETIMEOFFSET`
* Added unit test for `DateTimeOffset.UtcNow`
> SqlServer: Translate DateTimeOffset.Now

- src/EFCore.Relational/Query/Expressions/ColumnExpression.cs
- src/EFCore.Relational/Query/Expressions/JoinExpressionBase.cs
- src/EFCore.Relational/Query/Expressions/PredicateJoinExpressionBase.cs
- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Issue: We missed Having clause because it wasn't being copied while cloning SelectExpression
Fix:
We added processing of Having & GroupBy both in following places now to be consistent with other SelectExpression metadata
- Clone
- PushDownSubquery
- Clear
- JoinElimination for tablesplitting
- VisitChildren
Further, added NullConditionalExpression for translation of grouping key which can arise from GroupJoin-DefaultIfEmpty pattern. This improved some of the query translation
Resolves #11646
> Query: Fix for Having clause missing in Grouping Subquery

- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Internal/LazyLoader.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
Issue #11664
* If the navigation is not null/not empty, then no-op rather than throw. This matches the behavior in EF6 when attempting to lazy-load after a no-tracking query.
* Change the error to a warning-as-error so it can be forced to a no-op if needed.
> [For 2.1] Update no-tracking lazy-loading behavior

- src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that when we were building QM for correlated subquery we relied on query model cloning when trying to remap order by elements, that need to be applied to the correlated collection query.
Relinq cloning is currently broken (https://www.re-motion.org/jira/projects/RMLNQ/issues/RMLNQ-111) if the cloned query contains two copies of the same query source. This is the case if the order by or predicate of the main query contains a subquery itself.
Fix is to not rely on AdjustExpressionAfterCloning to remap complex orderings - now we get them directly from the cloned QM. Only simple orderings, that are guaranteed to be key accesses are remapped.
Also fixed issue in RelationalProjectionExpressionVisitor, where we would visit a projection (which could be complex), add appropriate SQL …
> Fix to #11622 - Query: Correlated subquery with complex ordering fails during compilation

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/Internal/QueryOptimizer.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue: When using let keyword in linq, ReLinq would create 1 SubQueryExpression being used in multiple places.
When we are flattening it out, it would mutate the SubQueryExpression so the other references are corrupted now.
This throws Must be reducible node exception since during translation the qsre in the tree is not in the scope of that subquery model
Resolves #11425
> Query: Clone inner SubQuery before flattening it out

- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Issue: Due to the shape of QM we incorrectly identified the query for Group By SQL translation.
Which is not the case hence we generate a SQL which produces incorrect result
Fix: During result operator processing, we more carefully identify if we are selecting from a grouping source.
Also relax criterea that group by aggregate should be only 1 level deep. This also allows us to translate group by aggregate when it is inside join
Resolves #11695
> [2.1 RC] Query: Fix for GroupBy with Where Aggregate produces incorrect SQL

- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore/Metadata/Internal/LazyLoaderParameterBindingFactory.cs
Fixes #11692
The issue was that the navigation property was defined on an abstract base class, and that entity type was not getting the NavigationAccessMode set.
> [2.1] Set field access mode for all entities in hierarchy when using lazy-loading

- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
Because it cannot be looked up, and it cannot have inheritance.
Fixes #11676
> [2.1] Use passed-in IEntityType when entity is weak.

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> [2.1] Query: Avoid applying entity equality rewrite to subquery coming from let

- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/WarningsSqlServerTest.cs
Problem was that we changed behavior of queries like:
customers.Select(c => (int?)c.Orders.Where(o => false).FirstOrDefault().Id)
In 2.0 this query would return collection of nulls, but in preview2 it would return collection of 0s. We made this change to address the following (very similar) scenario:
customers.Select(c => c.Orders.Where(o => false).Select(o => o.Id).FirstOrDefault())
which should have been returning 0s, but was returning nulls instead.
Fix is to add convert to nullable type whenever we perform member pushdown of a non-nullable property on a query containing FirstOrDefault/SingleOrDefault/LastOrDefault.
However, if the query doesn't require pushdown and *-OrDefault operator is applied on list of non-nullable scalars, rather than list of entities, we keep the query as is.
> Fix to #11690 - Handling of casts to nullable type differs between 2.1.0-preview2 and 2.0.0

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Issue: When we try to find name of the projection, we go through Convert/NullableExpression nodes. But when updating the alias we just wrap it inside a new AliasExpression. If the inner expression had AliasExpression giving it a name, then we would have multiple "AS" in SQL
Fix: When assigning new alias to projection, we run visitor and tries to replace old name to new name to avoid multiple aliases.
Resolves #11757
> Query: Improve alias-ing of projection in SelectExpression

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
> [2.1] Throw for defining query or view mapping on derived query types

- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
Throw a better exception if no relationships found.
Fixes #11855
> [2.1] Discover relationship to owned type even if configured at a later time.

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Issue: When eliminating joins, we updated projections and alongwith their tied member info mappings.
But in this case projection was empty so we did not update the mappings.
Fix is to update the mapping regardless of projection being there or not.
Resolves #11818
> [2.1] Query: Remap MemberInfo mapping while eleminating joins

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Issue: We save `Key` memberInfo to translation mapping in SelectExpression so we can bind `Key` later.
In this query, we also had anonymous projection in aggregate which projected out `Key` which would be essentially same projection but different `MemberInfo`
This causes us to have multiple `MemberInfo`s with same projection.
During `PushDownSubquery()`, we always lifted first `MemberInfo` matching current projection. This caused us to have stale entry in mapping.
In this particular scenario it got used and generated wrong query. (In other cases, we were corrupting mapping but never used it).
Fix:
Correct fix is to remove the stale mapping since the older memberInfo cannot be referenced further. So during the set method, we remove if there is existing mapping to same projection.
This has …
> [2.1] Query: Fix for GroupByAggregate with join on grouping key produces incorrect sql

- src/EFCore.Specification.Tests/Query/QueryFilterFuncletizationTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ModelExpressionApplyingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryFilterFuncletizationInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/QueryFilterFuncletizationSqliteTest.cs
- Visit generated subqueries/predicates to ensure nested filters get applied.
> Fix #11803 - QueryFilters: query filters are not applied recursively

- src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
When remapping member infos in a table splitting scenario we were not taking into the account that the element could be not a MemberInfo (it was a NullConditionalExpression because nav rewrite added null protection to it). However in case of accessing a property of an IGrouping, it's not necessary, because grouping can never be null.
Fix is to check for presence of GroupResultOperator when determining whether a given member access needs null compensation.
> [2.1] Fix to #11831 - Query: compilation error for queries with groupby anonymous object and table splitting

- src/EFCore.Relational/Query/Expressions/DiscriminatorPredicateExpression.cs
- src/EFCore/Query/Internal/ExpressionPrinter.cs
- src/EFCore/Query/Internal/IExpressionPrinter.cs
- src/EFCore/Query/Internal/IQueryModelPrinter.cs
- src/EFCore/Query/Internal/QueryModelExtensions.cs
- src/EFCore/Query/Internal/QueryModelPrinter.cs
Only affects PrintDebug mode (by default) - adding a number next to each unique qsre, to make debugging easier for scenarios with let and other cases where multiple qsres have the same names.
Also added option for Debug to print reduced forms of reducible nodes.
> Fix to #11670 - improve ExpressionPrinter debug mode to add unique IDs for query sources referenced by qsres

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/Model.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Fixes #11712
The idea is that if we already have a CLR type associated with the name given, then use that CLR type.
> Infer CLR type where possible when using OwnsOne

- src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Resolves #11905
Issue: GroupBy(g => new {}) converts to GroupBy(Constant) because of key not being correlated with range variable.
We translate GroupBy constant to server but in this case, the constant is of anon type which cannot be put in SQL tree hence translation pipeline failed.
Fix is to inject `1` as constant whenever we see GroupBy constant of a type which cannot be represented in SQL
> Query: Translate GroupBy new {} to GroupBy constant 1

- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Problem was that we were not correctly handling scenarios where multiple groupbys are present:
- if combined with Include, we would try to create orderings based on grouping keys for each group by. This is incorrect because all group keys apart from the innermost are out of scope of the inner query model (where we attempted to add them)
- if combined with aggregate we would try to translate into group-aggregate pattern and fail.
Fix is to only add ordering for the first grouping in case of include (includes are ignored for multi-groupby scenarios, so there is no risk of collection misalignment) and don't try to convert queries into group-aggregate pattern if multiple groupbys are present in the query.
> Fix to #11904 - 2.1 regression: "variable referenced from scope '', but it is not defined" exception in GroupBy query translation

- samples/OracleProvider/test/OracleProvider.FunctionalTests/TableSplittingOracleTest.cs
> Oracle: Skip testing for Can_use_with_redundant_relationships

- benchmarks/test/EFCore.Benchmarks.Sqlite.Dev/Query/NavigationsQuerySqliteTests.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Query/ExpressionVisitors/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteResultOperatorHandler.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Many operations involving the following types are problematic and should not be performed on the server:
- DateTime
- DateTimeOffset
- decimal
- TimeSpan
- ulong
Fixes #10534
> SQLite: Client-eval more expressions

- src/EFCore.Tools/EFCore.Tools.csproj
This was causing our build system to ignore the symbol.nupkg while publishing the artifacts.
@natemcmaster @pranavkm @bricelam
> Don't explicitly set IncludeSymbols to false

- src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Issue: We have custom logic to map the anonymous key in selector to translate key for SQL Group By case which was being applied for client group by causing error during client binding.
Fix for this makes sure that when we do such transformation we are dealing with ShapedQuery only.
Resolves #11973
> Query: Client GroupBy with anonymous type Key causes binding error

- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
Fixes #11972
The fix is to allow proxies (derived types) in the optimization check.
> Allow proxy weak types to be picked up by TryGetEntry

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
Since EF Core 2.1 supports Lazy loading scaffold should generate virtual navigation properties
- Added 'virtual' keyword to code generation string
> Add 'virtual' keyword to the navigation properties

- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue: In case of client order by in subquery, we could not lift SelectMany and generated 2 SelectExpression.
When binding from outer visitor we always assumed there would be 1 selectExpression inside. In this case, it fails.
To bind with inner SelectExpression, we need to find correct SelectExpression. That would be identified using its QSRE.
Since we are binding EF Property, the inner subquery's selector would be naked QSRE. so we use it as QS to get selectExpression.
To get inner selector, we store the QM on QMV for each lookup.
Resolves #11990
> Query: Improve binding when subquery has multiple SelectExpression

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
When scaffolding, a database column with an underlying store type but which itself has no mapping caused an NRE.
Fixes #12016
> Fix scaffolding unmapped type with underlying

- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
The warning produced by `EFCore.SqlServer` when not explicitly define precisions for decimals did suggest the usage of the wrong Fluent API method-name. This commit corrects the method name in the warning from ForHasColumnType() to HasColumnType(). 
Fixes #12041
> Corrects wrong method name in warningtext LogDefaultDecimalTypeColumn

- src/EFCore.Specification.Tests/TestModels/QueryFilterFuncletizationContext.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryFilterFuncletizationInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/QueryFilterFuncletizationSqliteTest.cs
> Query: Update tests in QueryFilters to avoid infinite recursion

- src/EFCore.Relational/Query/ExpressionVisitors/Internal/CompositeShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/EntityShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/ProjectionShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/Shaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/ValueBufferShaper.cs
- src/EFCore.Relational/Query/Internal/RelationalExpressionPrinter.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore/Query/Internal/ExpressionPrinter.cs
Shapers (especially projection shapers) contain useful information that gets compiled out of the query plan. For debugging purposes we stash the uncompiled expression on the Shaper as well so we can print the complete query plan.
We only do that if the query plans are getting logged to avoid unnecessary bloating of Shapers when that extra information doesn't get used.
> Fix to #9455 - Query/Logging: log contents of compiled code (e.g. materializers inside a shaper) as part of the query plan

- src/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/GearsOfWarFromSqlQueryTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalFixture.cs
- src/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryRelationalFixture.cs
- src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- src/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
- src/EFCore.Relational.Specification.Tests/TestUtilities/RelationalTestStore.cs
- src/EFCore.Relational.Specification.Tests/TestUtilities/TestFormattableString.cs
- src/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.QueryTypes.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.QueryTypes.cs
- test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
Make strict floating point comparison in BuiltInDataTypesTestBase optional
Fixes #11929
Fixes #11940
> Allow customizable SQL delimeters in tests

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Specification.Tests/Query/QueryTaggingTestBase.cs
- src/EFCore/EntityFrameworkQueryableExtensions.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs
- src/EFCore/Query/ResultOperators/Internal/TagExpressionNode.cs
- src/EFCore/Query/ResultOperators/Internal/TagResultOperator.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryTaggingInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryTaggingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/QueryTaggingSqliteTest.cs
- Adds WithTag query operator. From the doc comments: "Adds a tag to the collection of tags associated with an EF LINQ query. Tags are query annotations that can provide contextual tracing information at different points in the query pipeline." The first application of tags, included in this PR, is to cause a diagnostic header comment to be prefixed to generated SQL queries. E.g.
```sql
-- EFCore: (#Yanni)
SELECT TOP(1) [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
FROM [Customers] AS [c]
ORDER BY [c].[CustomerID]
```
- Also fixes a bug uncovered in the new parameterization parameter caching - NotParameterized parameters are removed from the set of parameters …
> Query: Fix #1664 - Tagged or named queries

- src/EFCore.Analyzers/RawSqlStringInjectionDiagnosticAnalyzer.cs
- src/EFCore.Analyzers/SqlInjectionDiagnosticAnalyzerBase.cs
- test/EFCore.Analyzers.Tests/RawSqlStringInjectionDiagnosticAnalyzerTest.cs
- Adds visited node set to prevent re-visiting.
- Also added max recursion depth fail safe in case there are more cases.
> Fix #12054 - Adds recursion guards to analyzer.

- src/EFCore/Query/Expressions/Internal/NullConditionalExpression.cs
Changed to:
instance?.Member
instance?.Method(argument)
EF.Property(?caller?, "Id")
?Caller | AccessOperation?
> Fix to #11793 - MQ: ExpressionPrinter incorrectly prints nested NullConditional expression on a method call

- src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
> [2.1.1] RevEng: Don't throw for type mappings that require an explicit store type

- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Resolves #11993
Issue: We visit element selector to save mappings for binding later. But in the case of constant key, we create a subquery to inject constant key. This made the mappings for element selector invalid since we cleared projection before pushing down.
Fix is to clear multi-projection after all processing is done.
> [2.1.1] Query: Fix for GroupBy Constant with element selector produces invalid SQL

- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
> Query: Avoid unnecessary type casting in AverageResultOperator

- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Issue: When ElementSelector is NewExpression/MemberInitExpression, it could easily bind through mapping and we don't need to preserve projection. In this case when projection is preserved and actual expression is complex, we ended up with multiple projections which we failed to lift during aggregate operation.
Fix: is to clear out projection for NewExpression/MemberInitExpression.
ElementSelector with single property requires aggregate expression over member only for server eval. So with complex aggregate it would do streaming group by.
If elementselector is made complex property then aggregate can be made simple and it still translates.
Resolves #12032
> Query: Clear out projection when GroupBy has element selector as anon type

- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/UdfDbFunctionOracleTest.cs
- src/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Creation of test data for UDF tests is currently duplicates in Sql Server and Oracle tests.  Moved to a shared base class so providers don't have to recreate test data.
> Create base test fixture which seeds test data for UDF tests.

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Issue:
Since the projection has same property repeated twice in the DTO, we would add alias from member name. We match projection based on unwrapped alias but we don't do that in ordering.
So we updated the projection but we did not update the ordering for new alias.
Fix:
Remember the removed projection and also use that while searching inside order by so we update ordering too and don't end up with incorrect column in order by list
Resolves #12180
> Query: Update OrderBy list properly when updating projection for alias-ing

- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore/Internal/EntityFinder.cs
Issue: If the ChangeTracking behaviour is set to NoTracking then calling Load on tracked entity won't track resuls of load query. Which results in load failing.
The fix is to issue AsTracking query so that results from load query are added to state manager and will be fixed up with tracked query
Currently calling Load on non tracked query does not work so this fix is safe in that regard.
Resolves #12209
> Always do tracking query for Load

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
Problem was that for queries that project constant bool which gets produced as a result of optimization (e.g. Contains on empty collection) we would not add explicit cast to bool, which resulted in value coming back as int.
Fix is to apply optimizations before we perform the check that determines whether the explicit cast is needed - this way the value is already collapsed into constant at this point and explicit cast is correctly applied.
> Fix to #12175 - OrderBy with contains and mapping fails duplicate Query source - expression association

- src/EFCore.Relational/Query/Expressions/ExplicitCastExpression.cs
- src/EFCore.Relational/Query/Expressions/LikeExpression.cs
- src/EFCore.Relational/Query/Expressions/NullCompensatedExpression.cs
- src/EFCore.Relational/Query/Expressions/NullableExpression.cs
- src/EFCore.Relational/Query/Expressions/StringCompareExpression.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Problem was that our expression comparison mechanism wasn't doing good job comparing extension nodes. Since the ExpressionEqualityComparer resides in Core it has no knowledge of custom expressions defined in Relational or providers. Those expressions should know how to compare themselves to one another, but in many cases they were using Equals method, rather than ExpressionEqualityComparer.Equals.
Fix is to use ExpressionEqualityComparer instead.
> Fix to #12249 - Ordering by a boolean column twice after an outer join results in invalid SQL

- src/EFCore.Relational/Query/ExpressionTranslators/Internal/StringCompareTranslator.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerCompositeMethodCallTranslator.cs
- src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringConcatMethodCallTranslator.cs
- src/EFCore/Query/Expressions/Internal/NullConditionalExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that when deciding whether new NullConditional expression was needed we were not correctly comparing the access expressions. Fix is to use ExpressionComparer instead to correctly identify equivalent expressions.
Moreover, when it comes to translation of SqlFragments (e.g. string compare) we are passing the expressions without stripping them from NCEs, and string compare was not accounting for presence of NCEs (or convert nodes). Fix is to improve the translator to correctly match expressions wrapped in NCE.
Also added translator for string.Compare(string, string) which we missed before.
> Fix to #12298 - Query: function call with argument that has null protection applied on can be unnecessarily complex leading to client eval

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that when looking for query source on which the include should be applied we were not short-circuiting on subqueries with aggregate result operators that returns a scalar value (count, sum, etc).
Fix is to jump out of the QuerySourceTracingExpressionVisitor when we encounter such a case.
> Fix to #12173 - Query: Include annotation is not ignored for group by aggregate causing client eval

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.Relational/RelationalIndexBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/ISqlServerIndexAnnotations.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexBuilderAnnotations.cs
- src/EFCore.SqlServer/Metadata/SqlServerIndexAnnotations.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/breakingchanges.netcore.json
- src/EFCore/Metadata/Builders/IndexBuilder`.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
This PR adds `ForSqlServerInclude` extension to `IndexBuilder` allowing defining columns to be included in a index on sql server.
To support expression parameter a generic version of `IndexBuilder` is introduced in main EF assembly, however to avoid breaking changes (as requested in https://github.com/aspnet/EntityFrameworkCore/issues/4846#issuecomment-395213518) this type is available only with new extension `ForSqlServerHasIndex` for the time being.
There is a breaking change in `EFCore.SqlServer` adding a property to interface -
`ISqlServerIndexAnnotations.Include`, which might be ok since it's maybe not really meant to be implemented by others? @ajcvickers 
I'm still investigating possible problems with migrations, so this is not yet ready.
Fixes #4846
> Add support for defining included column for indexes in SQL server

- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- LogStartedTracking statement expects context name first, then entity name, as seen here: https://github.com/aspnet/EntityFrameworkCore/blob/48e25cbd93324718c804aa604284528dce47ed99/src/EFCore/Properties/CoreStrings.resx#L370
> Fix incorrect order of properties passed to log message

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.Relational/breakingchanges.netcore.json
- src/EFCore/breakingchanges.netcore.json
Into interface Microsoft.EntityFrameworkCore.Storage.ISqlGenerationHelper were added two new methods:
- string GenerateParameterNamePlaceholder([NotNull] string name);
- void GenerateParameterNamePlaceholder([NotNull] StringBuilder builder, [NotNull] string name);
By default, RelationalSqlGenerationHelper (implementation of  ISqlGenerationHelper) saves old behavior: ParameterNamePlaceholder == ParameterName.
For generation of another placeholder name, need override GenerateParameterNamePlaceholder methods.
I tested these changes with my adapter for EFCore - seem they work as expected.
One problem - I not know how to test the changes in DefaultQuerySqlGenerator::VisitPropertyParameter. This method similar to VisitParameter. But my tests does not call the VisitPropertyParameter method.
> Implementation for issue #12152 [GenerateParameterNamePlaceholder]

- src/EFCore.Relational/Storage/RelationalDataReader.cs
New property RelationalDataReader::DbCommand allow to read OUTPUT-parameters of modification commands (INSERT, UPDATE).
It used from ConsumeResultSetWithPropagation method.
Need for resolution of problem #12169
---------
Additional information:
My ADO.NET provider (lcpi.data.oledb) does not return OUTPUT-parameters of modification commands (INSERT,UPDATE) through DataReader.
> Some help for resolution of problem #12169

- src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncIncludeSqlServerTest.cs
Issue:
The issue here was, when we get no select expression in RelationalProjectionEV, we returned expression as is. That made the expression to be visited through EntityQueryableEV.
ProjectionEV has special code (since it is projection side) to insert adapters from async to sync to match types. Because of above issue, we did not insert adapter and hit type mismatch.
Solution:
If there is no SelectExpression in RelationalProjectionEV then call base instead of returning expression.
Resolves #12374
> Query: Use ProjectionExpressionVisitor when no SelectExpression

- src/Shared/SharedTypeExtensions.cs
- test/EFCore.Tests/EFCore.Tests.csproj
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> [2.1.3] Handle properties with same name from multiple explicit interface implementations.

- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- src/EFCore.Specification.Tests/TestModels/UpdatesModel/Product.cs
- src/EFCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
- src/EFCore.Specification.Tests/UpdatesFixtureBase.cs
- src/EFCore.Specification.Tests/UpdatesTestBase.cs
Fixes #12214
Fix is to use structural equality all the time for concurrency checks. This matches more closely the way the check works on real database systems.
> [2.1.3] Use structural equality for concurrency check in in-memory database

- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Issue:
The issue here is, we had projection of kind `nav.Id == null ? null : new { nav.Property }`
When it is single property access, we can remove null check since SQL is null safe.
Same is not true for anonymous type since it has no SQL equivalent.
Anonyous type produces Expression[] in sql translation and we tried to print it out in SQL causing exception.
Fix:
Fix is to skip over NewExpression/MemberInitExpression so that if we encounter those, we don't go inside of them.
Resolves #12412
> [2.1] Query: Null checking with anonymous projection produces invalid SQL

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Issue:
Since the projection has same property repeated twice in the DTO, we would add alias from member name. We match projection based on unwrapped alias but we don't do that in ordering.
So we updated the projection but we did not update the ordering for new alias.
Fix:
Remember the removed projection and also use that while searching inside order by so we update ordering too and don't end up with incorrect column in order by list
Resolves #12180
This has been already approved in https://github.com/aspnet/EntityFrameworkCore/pull/12188
Will merge once CIs are happy.
> [2.1] Query: Update OrderBy list properly when updating projection for alias-ing

- src/EFCore.Tools/EFCore.Tools.csproj
- src/EFCore.Tools/EFCore.Tools.nuspec
- src/EFCore.Tools/EntityFrameworkCore.PowerShell2.psd1.in
- src/EFCore.Tools/EntityFrameworkCore.psd1.in
- test/EFCore.Tests/EFCore.Tests.csproj
- test/EFCore.Tests/ModelSourceTest.cs
Follow-up to https://github.com/aspnet/EntityFrameworkCore/pull/12484#issuecomment-400828972
Remove the hard-coded versions from .psd1 files and tests. Instead, this flows the version automatically into test runs and the .psd1 definitions.
> Automatically flow version into tests and powershell definitions

- src/EFCore.Relational/Extensions/RelationalTaskExtensions.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/AsyncQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Mission.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that in order to return 0 from empty Sum of nullable values, we convert them to non-nullable (to produce 0) and then convert back to nullable type. This works without issue for sync path, but in async simple casting like that doesn't work.
Fix is to call method that adds Task.ContinueWith() call that casts the result to the correct type in the async scenario.
> [2.1] Fix to #12314 - SumAsync throw Exception when used over float?

- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
There was two problems here:
- we were not lifting a select expression that had a GroupBy-Aggregate pattern, and another result operator was composed on top,
- we were not propagating RequiresStreamingGroupBy flag to a parent QM, when we lifted a client group by subquery, which could result in the client methods being wiped out if Count/LongCount was composed on top.
> [2.1] Fix to #12351 - Incorrect SQL generated for Count over Group By (EFCore 2.1)

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/TaskLiftingExpressionVisitor.cs
- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs
- src/EFCore/Query/Internal/IncludeCompiler.cs
- src/EFCore/Query/QueryCompilationContext.cs
Also fixes #12358 - The use of the ToListAsync method leads to missing data in version 2.1.0 of Microsoft.AspNetCore.All
Problem was that we were using multiple instances of cancellation token parameter when constructing a query plan. Fix is to unify it into one instance that is located on QueryCompilationContext instead.
> Fix to #12463 - Query: compilation error (bad cancellation token) for async query projecting collection navigation and include

- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerCompositeMethodCallTranslator.cs
- src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerFullTextSearchMethodCallTranslator.cs
- src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/SqlServerDbFunctionsExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs
```
- Added Contains function mapping to SqlServerDbFunctionsExtensions.cs
- Added translator logic for Contains to SqlServerFreeTextMethodCallTranslator, renamed to SqlServerFullTextSearchMethodCallTranslator.
- Updated query generator
- Added tests
```
Fixes #11486
> Implements #11486: Contains support for SQL server FTS.

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
> SqlServer Migrations: Quote schema identifier in TRANSFER statement

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that when we rewrite collection query during the include compilation we are supposed to prune the result operators that change the result type (e.g. GroupBy). However we missed Cast and OfType, which would lead to discrepancy between the selector and the QM result type.
Fix is to remove the missing operators from the collection query - we only need it to select all the elements of the included collection, we don't need to preserve the original type.
> Fix to #12582 - Includes With Cast Throws Exception

- src/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
Fixes #12227
This issues happens when the principal side of multiple relationships is using inheritance and the relationships share and FK property and principal key definition. In this case, the FK value may match instances that are not of the correct type for the given relationship. This would normally be an error and we started throwing for it in 2.1. But it is not an error if the principal is correct for some other relationship sharing the same FK property. So the fix here is to check all the FKs to see if any one can be used. If so, then no problem. If not, then still an error to catch the common case. No matches is also okay, since we don't know whether the principal is loaded or not.
Note that technically, GetPrincipal is broken and should be fixed with new API surface to get all …
> [2.1.3] Allow dependents that can match a principal through multiple relationships

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
Fixes #12557
This is a simple case that used to work for enums because they were always converted to their underlying type anyway. However, it falls out of the space where normal value converters would be expected to work, so to bring back the old behavior we check if the parameter type is already the underlying type for enum conversions and, if so, don't try to convert it.
> [2.1.3] Allow enum parameters to be passed as integers

- build/dependencies.props
- korebuild-lock.txt
Part of https://github.com/aspnet/Home/issues/3316
This pins package versions to the 2.1.2 baseline. Universe will not override variables in the 'Pinned' section. This helps ensure that EF does not upgrade its dependency versions for all future patches of 2.1.
> [2.1]: pin package versions to the 2.1.2 baseline

- src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
Problem was that affected tests were expecting exactly one message in the log, but now we are seeing messages about disposing the reader. Presumably due to a bug fix in sql client, which now correctly disposes the reader which it previously did not.
> fixing failing tests after recent package upgrade

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Recognize system defined type aliases
Resolves #12595
> SqlServer: Scaffold sysname data type columns

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that for correlated collection, the inner query model projects all orderings for this and all upstream orderbys. However, when we generate SelectExpression, duplicate projections are eliminated. Therefore if we naively construct correlated collection projection list, without taking duplicates into account, this can lead to inconsistencies between SelectExpression and query model.
Fix is to watch for duplicates when constructing the projections for correlated subquery QM and maintain the mapping between orderings and their corresponding projection element, so we know how to remap the orderings correctly - before we just assumed no duplicates and could simply remap them in sequence.
> Fix to #12709 - Query: ArgumentOutOfRangeException when doing multiple ordering on same property in collection include

- src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
I need support for things like `[t].[GeometryColumn].STX` in SQL as part of #1100. Can also be used for `CURRENT_TIMESTAMP`, etc.
I tried to write some unit tests, but the cost of unit testing `DefaultQuerySqlGenerator` is much higher than I'm willing to pay right now considering I have functional tests that use this already passing in my spatial branch.
Part of #9022
cc @pmiddleton
> Relational Query: Support niladic functions

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/CorrelatedSubqueryMetadata.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was that when we rewrite SelectMany, query sources get changed and need to be updated. We do that already for Include query annotations, but we were not doing it for query sources stored in CorrelatedSubqueryMetadata.
Fix is to update CorrelatedSubqueryMetadata query sources after we rewrite SelectMany, just like we do for Include annotations.
> Fix to #12575 - Query: compilation error for query with SelectMany optional navigation followed by a Select optional navigation

- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that correlated subquery did not perform structural comparison between outer and inner key values when needed (e.g. for byte[] keys). We already do this for Include queries.
> Fix to #12748 - Inner-query with byte[] FK produces wrong result with EFCore 2.1.x

- src/EFCore.Relational/RawSqlString.cs
Fixes an extra "see" in [the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.rawsqlstring.-ctor?view=efcore-2.1).
> Remove extra "see" in RawSqlString documentation

- src/EFCore.Relational/Query/Expressions/InExpression.cs
- src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- src/EFCore/Query/Internal/ExpressionEqualityComparer.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
Problem was that when performing Expression comparison using ExpressionEqualityComparer, the constituent sequences were compared using default comparer (via SequenceEquals method), which doesn't know how to properly handle some Expressions (e.g. ConstantExpression).
Fix is to add SequenceEquals method to out ExpressionEqualityComparer, that will perform the sequence comparison using its own logic.
> Fix to #12830 - Query: invalid sql for query projecting a sql function (e.g ROUND) and ordering by it twice

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
This allows providers to block caching SQL in second level cache
Resolves #12764
> [Query] Make SelectExpression.IsCacheable protected

- src/EFCore.Relational/Query/Expressions/IsNullExpression.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
We were using regular comparer, fix is to use ExpressionEqualityComparer instead.
> Fix to #12856 - Query: IsNullExpression doesn't use ExpressionEqualityComparer to compare its arguments which may lead to invalid sql

- version.props
Preparing for the next round of servicing.
Once this is merged, the release/2.1 branch is open for new 2.1.x fixes.
> Bump version to 2.1.3

- src/EFCore/Metadata/Conventions/ConventionSet.cs
- src/EFCore/Metadata/Conventions/Internal/CascadeDeleteConvention.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionNode.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionVisitor.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/IForeignKeyRequirednessChangedConvention.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Key.cs
- src/EFCore/Metadata/Internal/PropertiesSnapshot.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/RelationshipSnapshot.cs
- src/Shared/MemberInfoExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
This preserves the correct value for detached FKs and is part of a larger change
> Separate fk requiredness and add a convention type that runs when it changes

- src/EFCore.Specification.Tests/FieldMappingTestBase.cs
- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/ClrPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
Fixes #12490
Note that in #12490, the wrong backing field is found. This is not fixed here--issue #12523 covers that.
> Allow property accessor delegates to use fields that need casting

- benchmarks/src/EFCore.Benchmarks/JobExtensions.cs
- benchmarks/test/EFCore.Benchmarks.Sqlite.Version20/EFCore.Benchmarks.Sqlite.Version20.csproj
- benchmarks/test/EFCore.Benchmarks.Sqlite.Version20/Models/AdventureWorks/AdventureWorksContext.cs
- benchmarks/test/EFCore.Benchmarks.Sqlite.Version21/EFCore.Benchmarks.Sqlite.Version21.csproj
- benchmarks/test/EFCore.Benchmarks.Sqlite.Version22/EFCore.Benchmarks.Sqlite.Version22.csproj
BDN compiles .NET framework benchmarks with x64 platform which does not work for sqlite.dll
> Benchmarks: Compile for AnyCpu

- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithSensitiveDataLoggingFixture.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithoutSensitiveDataLoggingFixture.cs
Hopefully fixes #12859
(cherry picked from commit 4f65388bf68312e16fe07e62f79d8fad4e242f2a)
> Ensure each in-memory test fixture uses a different named database

- src/EFCore.Relational/Query/ExpressionTranslators/Internal/GetValueOrDefaultTranslator.cs
- src/EFCore.Relational/Query/ExpressionTranslators/RelationalCompositeMethodCallTranslator.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Adding translation on a relational level - translates to COALESCE
> Fix to #10153 - Query: add translator for Nullable<>.GetValueOrDefault()

- src/EFCore.Relational/Extensions/RelationalExpressionExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Issue: GroupJoin-DefaultIfEmpty aka left outer join introduced NullableExpression around the property which we fail to find hence we use wrong type mapping which expect int32 but we get back int16 from database
Resolves #13025
> Query: Improve logic to find underlying property for projection

- src/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- src/EFCore.Specification.Tests/CompositeKeyEndToEndTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore.Specification.Tests/TestUtilities/DatabaseFacadeExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.SqlServer.FunctionalTests/ComputedColumnTest.cs
- test/EFCore.SqlServer.FunctionalTests/DefaultValuesTest.cs
- test/EFCore.SqlServer.FunctionalTests/MemoryOptimizedTablesTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/SequentialGuidEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerConfigPatternsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDbFunctionMetadataTests.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerQueryTriggersTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
- test/EFCore.SqlServer.Tests/CommandConfigurationTests.cs
Tests using `SharedStoreFixture` already have resilient database creation
Fixes #13037
> Make database creation resilient in tests

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue:
We have certain optimizations running when comparing navigations with null or other navigations
- collection nav == collection nav converts to their parent equality
- collection nav == null converts to parent == null
- dependent to principal nav == null converts to parent.FK == null
For all above cases, we have to create parent expression. We used to create it through a method which assumed the navigation chain will always start from QSRE.
This all worked correctly upto 2.0 where we did not convert equalities after subquery.
In 2.1 we enabled equality rewrites involving subquery, which ultimately broke above assumption. The navigation chain can start from a subquery too.
Which means that for any of above optimization, we would through NRE (or equivalent).
Fix:
Instead of using …
> Query: Fix entity equality on navigation accessed on subquery

- src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
Adds time unit details to Get/SetCommandTimeout() extension methods:
- Adds `"(in seconds)"` to `GetCommandTimeout()`
- Adds `"(in seconds)"` to `SetCommandTimeout()` (`int` overload only)
Currently, a user sees this:
After a tweet, others seemed to agree a quick time unit addition here would save some headaches, so...here it is!
> Relational extensions: add time unit to XML docs

- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Issue: smalldatetime literal should be same as datetime literal. Conditions missed it hence we were printing literal for datetime2 which failed at parsing.
Resolves #13118
> Query: Generate correct SQL literal for smalldatetime

- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that when we were constructing collection subquery for the included entities we were using a MemberInfo to determine on which type the navigation is declared. This was incorrect when navigation from EF perspective is defined in a different place than the CLR classes would indicate. We should be using information contained on IPropertyBase instead.
> Fix to #11944 - Query: Include for derived types fails when navigation property is defined in an intermediate type

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue:
We have certain optimizations running when comparing navigations with null or other navigations
- collection nav == collection nav converts to their parent equality
- collection nav == null converts to parent == null
- dependent to principal nav == null converts to parent.FK == null
For all above cases, we have to create parent expression. We used to create it through a method which assumed the navigation chain will always start from QSRE.
This all worked correctly upto 2.0 where we did not convert equalities after subquery.
In 2.1 we enabled equality rewrites involving subquery, which ultimately broke above assumption. The navigation chain can start from a subquery too.
Which means that for any of above optimization, we would through NRE (or equivalent).
Fix:
Instead of using …
> [2.1.5] Query: Fix entity equality on navigation accessed on subquery

- src/EFCore.Relational/Query/ExpressionTranslators/Internal/GetValueOrDefaultTranslator.cs
- src/EFCore.Relational/Query/ExpressionTranslators/RelationalCompositeMethodCallTranslator.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/Shared/SharedTypeExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Adding translation on a relational level - translates to COALESCE
> [2.1.5] Fix to #10153 - Query: add translator for Nullable<>.GetValueOrDefault()

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/CorrelatedSubqueryMetadata.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was that when we rewrite SelectMany, query sources get changed and need to be updated. We do that already for Include query annotations, but we were not doing it for query sources stored in CorrelatedSubqueryMetadata.
Fix is to update CorrelatedSubqueryMetadata query sources after we rewrite SelectMany, just like we do for Include annotations.
> [2.1.5] Fix to #12575 - Query: compilation error for query with SelectMany optional navigation followed by a Select optional navigation

- src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
It is safe because @AndriySvyryd said so
Resolves #13157
> Query: Rewrite to key equality for owned navigation being compared to null

- src/EFCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
- src/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
> [Test] Update in-memory tests to use a different entity instance for concurrency checks

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
In the snapshot code HasData will now output as following
```
b.HasData(
new
{
Id = 42
},
new
{
Id = 43,
OptionalProperty = 4.3m
});
```
I also updated all the unit tests to the new format. 
Fixes #12367
> Format HasData in snapshot to multiple lines

- NuGet.config
- build/dependencies.props
- korebuild-lock.txt
- src/dotnet-ef/dotnet-ef.csproj
These targets are now part of Microsoft.NET.Sdk.
It should make VS slightly faster, and removes the need to generate the global.json file before you open a .sln.
> Remove usage of Microsoft.DotNet.GlobalTools.Sdk

- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
Fixes #13262
Since two test suites both switch the quirk on and off, but the quirk is global, it results in a race condition where one test is expecting it to be off, but it then gets switched off while that test is running. Fix is to remove these tests since they have little value going forward.
> Remove quirk tests due to global race condition

- src/EFCore.InMemory/Storage/Internal/InMemoryDatabaseCreator.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore/Infrastructure/DatabaseFacade.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/IDatabaseCreatorWithCanConnect.cs
- test/EFCore.InMemory.FunctionalTests/DatabaseInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
- test/EFCore.Tests/DatabaseFacadeTest.cs
> Adds CanConnect API for use by health checks

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMapping.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMappingSource.cs
- src/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- src/EFCore.Specification.Tests/TestModels/UpdatesModel/AFewBytes.cs
- src/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductWithBytes.cs
- src/EFCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
- src/EFCore.Specification.Tests/UpdatesFixtureBase.cs
- src/EFCore.Specification.Tests/UpdatesTestBase.cs
- src/EFCore/ChangeTracking/ArrayDeepComparer.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- src/EFCore/Extensions/MutablePropertyExtensions.cs
- src/EFCore/Extensions/PropertyExtensions.cs
- src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
- src/EFCore/Storage/CoreTypeMapping.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
Fixes #13254
This change introduces a new ValueComparer type that can be used when deep copies are needed. Neither the regular or the key comparer can be relied on to work this way, hence the need for a new one. There is no reliable way to know if such a comparer is needed, so it's up to the application/provider setting up the type mapping to provide one if needed.
> Deep copy byte arrays into the in-memory store

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Issue #12732
Note that this PR does not fix the issue, but does provide a better message for the failure.
> Better exception message when query encounters a missing type mapping

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Issue: When expanding values for InExpression from a parameter, we did not visit the InExpression recursively. This caused the inner InExpression to not have proper values hence trying to generate incorrect parameter type.
Fix: Visit the InExpression first and then convert it to value expanded form.
Resolves #12732
> Query: Visit Nested Contains recursively

- src/EFCore.Proxies/Proxies/Internal/IProxyLazyLoader.cs
- test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
Fixes #12772
Using `IgnoreDataMember` for this since it doesn't bring in any new dependencies and is honored by JSON.NET.
> Prevent ILazyLoader property in proxy from being serialized by JSON.NET

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
When providing values in exponential form it would append .0 where it was not needed.
6E-14 => 6E-14.0
Fixes #13089 
However wouldn't it be better to use the G17 format instead of R format? 
For example
Original | G17 | R   
---------|------|-----
6E-14    | 5.9999999999999997E-14 | 6E-14
0.84551240822557006 | 0.84551240822557006 | 0.84551240822557
> Update double literal to not append .0 when it is not needed

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
Avoids having to deal with SqlBytes outside of the data reader and parameters
> Use full provider type mapping for NTS types

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGeneratorDependencies.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Design/breakingchanges.netcore.json
- src/EFCore.Design/breakingchanges.netframework.json
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMapping.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMappingSource.cs
- src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs
- src/EFCore.Specification.Tests/TestModels/UpdatesModel/AFewBytes.cs
- src/EFCore.Specification.Tests/UpdatesTestBase.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerNTSTypeMappingSourcePlugin.cs
- src/EFCore.SqlServer.NTS/Storage/ValueConversion/Internal/GeometryValueConverter.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteNTSTypeMappingSourcePlugin.cs
- src/EFCore.Sqlite.NTS/Storage/ValueConversion/Internal/GeometryValueConverter.cs
- src/EFCore/ChangeTracking/GeometryValueComparer.cs
- src/EFCore/Storage/CoreTypeMapping.cs
- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
- test/EFCore.Sqlite.FunctionalTests/UpdatesSqliteFixture.cs
Part of #8741
Currently, as a first step, the scaffolding using WKT as a serialization format. This could be replaced with "pure" C# code calling nested constructors, etc. Also, SRID is not yet round-tripped.
Also, changed to a generic ValueConverter to take advantage of infrastructure and reduce custom overrides in the converter.
Still to do for #8741 - literals in other places
> Scaffold NTS literals for in model snapshot

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
I manually verified that absolute paths are handled in these paths and the issue is fixed.
For context, `Split-Path -IsAbsolute` doesn't work for network paths, and `Join-Path` doesn't handle absolute child paths.
Fixes #11781
> PMC Tools: Handle absolute paths better

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGeneratorDependencies.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGeneratorDependencies.cs
- src/EFCore.Design/breakingchanges.netcore.json
- src/EFCore.Design/breakingchanges.netframework.json
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs
Fixes #8741
Fixes #13297
Moves the dependency on the type mapper onto the CSharpHelper.
> Finishing up spatial literal generation for 2.2

- Directory.Build.props
- src/EFCore.Analyzers/EFCore.Analyzers.csproj
- src/EFCore.Tools/EFCore.Tools.csproj
- src/dotnet-ef/dotnet-ef.csproj
React to https://github.com/aspnet/BuildTools/pull/766 which will enable code signing to run as a part of build.ps1, including a dry-run for local developer builds.
> Fix the file path to signed package items and remove obsolete signing properties

- build/dependencies.props
- src/EFCore.Cosmos.Sql/Metadata/Conventions/Internal/StoreKeyConvention.cs
- src/EFCore.Cosmos.Sql/Query/Internal/ValueBufferFactoryFactory.cs
- src/EFCore.Cosmos.Sql/Storage/Internal/CosmosClient.cs
- src/EFCore.Cosmos.Sql/Update/Internal/DocumentCollectionUpdater.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/CosmosSqlEndToEndTest.cs
This is accomplished by storing the JObject returned from the store in a shadow property.
> Cosmos SQL: Preserve unmapped properties.

- build/dependencies.props
- korebuild-lock.txt
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- src/dotnet-ef/dotnet-ef.csproj
Per xunit guidance, class libraries which deliver xunit bits shouldn't also depend on the xunit or xunit.core metapackage. These packages contain project settings to make a test project runnable, but are not needed for class libraries which need to compile for xunit API's.
> https://xunit.github.io/releases/2.3:
> As a reminder: If you're extending xUnit.net and want to publish your extension as a NuGet package, you should import xunit.extensibility.core and/or xunit.extensibility.execution, not xunit or xunit.core. If you do this wrong, you might have problems generating your NuGet package via dotnet pack.
Incidentally, this resolves an issue with upcoming changes to KoreBuild which uses the `IsTestProject` property to skip code signing for test projects.
> Change Spec.Tests dependency on xunit.core to xunit.extensibility.execution

- src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Problem was that we were determining which owned navigations should be eagerly-loaded before we ran optimizations that handle OfType. This lead to trying to eagerly-load navigations available for base type, not the derived.
Fix is to run EagerLoadingExpressionVisitor after the initial OptimizeQueryModel pass.
> Fix to #13430 - OfType<T> throws InvalidOperationException when Derived entity has Owned entity type

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/CoreTypeMapping.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Mean that type mappings can support language independent code literals. Only the C#/VB/F# helper needs to be language specific, even for unknown types.
Fixes #13414
> Use expressions to represent type mapping code literals

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- test/EFCore.Tests/ModelBuilding/QueryTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Issue: We did not keep track of referencing FKs on QueryTypes. This causes issue when query type is discovered first making FK to TempId.
Since when PK is discovered on EntityType, we cannot find referencing FK to replace on QueryType.
Resolves #13382
> Metadata: Keep track of referencing FKs defined on QueryTypes

- samples/OracleProvider/test/OracleProvider.FunctionalTests/F1OracleFixture.cs
- src/EFCore.InMemory/Metadata/Conventions/Internal/InMemoryConventionSetBuilder.cs
- src/EFCore.Relational.Specification.Tests/F1RelationalFixture.cs
- src/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore.Specification.Tests/F1FixtureBase.cs
- src/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
- src/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
- src/EFCore/Infrastructure/ModelSource.cs
- src/EFCore/Metadata/Conventions/ConventionSet.cs
- src/EFCore/Metadata/Conventions/Internal/ValidatingConvention.cs
- src/EFCore/ModelBuilder.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
- test/EFCore.InMemory.FunctionalTests/F1InMemoryFixture.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
- test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerValueGenerationStrategyConventionTest.cs
- test/EFCore.Sqlite.FunctionalTests/F1SqliteFixture.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
Fixes #11738
Naming to be discussed.
This runs the model-based conventions, and model validation. Also moved setting or product version annotation to any use of the ModelBuilder and then removed from places in the tests that this would cause problems when the version changes.
> Added a ModelBuilder.FinalizeModel method to support building outside the context

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Expressions/CaseExpression.cs
- src/EFCore.Relational/Query/Expressions/CaseWhenClause.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Relational/Query/Sql/ISqlExpressionVisitor.cs
- src/EFCore.Relational/breakingchanges.netcore.json
- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteGeometryMemberTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
Fixes #13280
**Providers**, this adds a class for generating SQL CASE expressions.
> Spatial: Translate GeometryType and OgcGeometryType

- src/EFCore/ModelBuilder.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderAssemblyScanTest.cs
Summary of changes
```
- Added an extension method ApplyEntityTypeConfigurations for ModelBuilder that scans the assembly for IEntityTypeConfiguration instances.
- The API supports an optional filter for types within the assembly.
- It only supports IEntityTypeConfiguration.
```
Let me know what you think.
> Implemented assembly scanner for IEntityTypeConfiguration #13088

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Current filters
InsertData:
Columns -> IsKey/IsWrite (Exclude IsConcurrency)
UpdateData:
KeyColumns -> IsKey (Exclude IsConcurrency)
Columns -> IsWrite (Exclude IsConcurrency)
DeleteData:
KeyColumns -> IsKey (Exclude IsConcurrency)
Resolves #11969
UpdatedData excludes concurrency from values
Resolves #13276
DeleteData excludes concurrency from keys
Resolves #12687
Exclude non-write properties from Insert/UpdateData - Properties with ValueGeneratedOnAddOrUpdate
Resolves #13206
Exclude non-write properties from InsertData - Properties with value generator and CLR default
> Seed Data: Exclude concurrency token from Data Operations

- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Resolves #12508
Issue: While discovering FK, we try to find if a key is fully contained inside proposed FK and make decision based on that if we can use it.
But if the Key has overlap rather than containment, then our logic was still identifying it as no overlap making us to use a property with key for non-unique FK
Fix: If FK is non-unique and proposed match has any property with key defined on it then we don't match it
> ModelBuilding: Don't match FK properties which are part of Key for non-unique FK

- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Issue: When an owned type is converted to weak type, we detach/attach relationships. In the process we are losing the principal key configuration for non-ownership Fks
This caused explicitly configured relationship to use shadow AK when PK type was different than FK.
Fix: We were resetting PrincipalKey when dependentType is not same as FK.DependentType. Though for owned to weak conversion it is never same but the condition is only supposed to capture inversion. Hence expanded the check to match if dependentType is same as PrincipalEntityType
Resolves #12423
> ModelBuilding: Preserve Principal key configuration for FK on weak types

- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlGenerator.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/SimpleQueryCosmosSqlTest.Where.cs
Fixes: #13190 Cosmos.SQL: Incorrect datetime mapping
Cosmos DB SQL generator generates string value for DateTime and DateTimeOffset constants. Additionally it uses JSON serializer to generate numeric constants, so that it is culture independent.
```
- Detail 1
- Detail 2
```
> DateTime mapping in CosmosDb query

- samples/OracleProvider/src/OracleProvider/Query/Sql/Internal/OracleQuerySqlGenerator.cs
- src/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
> Query: Remove VisitSqlFunctionName redudant method

- src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Issue: When adding derived entity's relationship, we saw that owned navigations are not compatible and we removed them. The conditions incorrectly converted it to owned type not being in use. Hence owned types were removed (Since they were discovered using convention). Which in turn triggers relationship discovery and adds them again in derived type and goes into recursion.
Resolves #12628
> ModelBuilder: Only remove owned entity if it is not in use

- src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
- src/EFCore.SqlServer.NTS/Design/Internal/SqlServerNetTopologySuiteDesignTimeServices.cs
- src/EFCore.SqlServer.NTS/EFCore.SqlServer.NTS.csproj
- src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.SqlServer.NTS/build/netstandard2.0/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite.targets
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore.Sqlite.NTS/Design/Internal/SqliteNetTopologySuiteDesignTimeServices.cs
- src/EFCore.Sqlite.NTS/EFCore.Sqlite.NTS.csproj
- src/EFCore.Sqlite.NTS/build/netstandard2.0/Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite.targets
- src/EFCore/Design/DesignTimeServicesReferenceAttribute.cs
Verification: I manually bashed on this. I verified it works with multiple provider-specific services and non-provider-specific services.
Resolves #12083, resolves #13283
> Spatial RevEng: Automatically load NetTopologySuite services at design-time

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was that for navigations inside SelectMany we would always produce inner joins, however, when the navigation chain ends in DefaultIfEmpty, we can suspect that SelectMany operation is supposed to return at least one result per source element. For that purpose we need to produce LOJ.
Fix is to check if the navigation chain inside SelectMany ends in DefaultIfEmpty, and if so - generate LOJ calls instead.
> Fix to #13511 - SelectMany with DefaultIfEmpty() generates unexpected INNER JOIN

- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Problem was that the query had the same subquery present multiple times in the actual model and when we applied SubqueryMemberPushDownExpressionVisitor on one of those we would consequently mutate it in other place also, leading to invalid QM.
Previously we encountered this issue but only fixed it for pushdown via MemberExpression, missing cases that use EF.Property.
Fix is to clone the subquery before mutating it in the subquery member pushdown for EF.Property cases.
> Fix to #12738 - FirstOrDefault within Automapper causing Error

- src/dotnet-ef/dotnet-ef.csproj
This target dependency causes /t:Pack to re-build dotnet-ef.dll, even when `NoBuild=true` is specified. Removing this because the target dependency should be unnecessary.
> Avoid double writes of dotnet-ef.dll during build

- src/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
The issue is already fixed in 2.2, so just adding a test.
Fixes #13219
> Adding regression test for re-parenting bug

- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
We were losing convert nodes added by users and ended up getting results in wrong type
Resolves #13587
> Query: Don't remove ExplicitCast for aggregate operators

- README.md
Remove language info in EfCore documentation URL.
So that it is consistent with other URLs such as
- https://docs.microsoft.com/ef/core/providers/
> Remove language info in EfCore documentation url

- src/EFCore/ChangeTracking/ArrayStructuralComparer.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Tests/Storage/ValueComparerTest.cs
Fixes #13172
This change means we use structural comparisons for Equals now in regular DetectChanges. In the common case of DetectChanges, this short-circuits to quick same reference check, since the bytes are still not snapshotted. However, in case where the reference has changed, but the bytes are the same, we no longer get an erroneous Modified state, which as well as fixing this issue also means that we can avoid sending an update for data that hasn't changed.
> Fix erroneous diff in data seeding with binary values

- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- src/EFCore/Metadata/Internal/CollectionTypeFactory.cs
- test/EFCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
Problem was that when we were creating collection navigations we were using default ctors. This would cause (observable) HashSets to use element's Equals method when determining if the given entity is already part of the collection. This could lead to the same collection being added multiple times etc.
Fix is to special-case create collection delegates for well known concrete types like HashSet<T> and ObservableHashSet<T> and instantiate them using constructor that takes equality comparer argument. This way we can always ensure reference equality being perform on its elements.
For List<T> there is no such overload and for custom collection types we can't know which ctor to use so the behavior there stays the same.
> Fix to #12984 - Collection navigations should use reference equality by default

- src/EFCore/Metadata/IMutableEntityType.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/breakingchanges.netcore.json
- test/EFCore.Tests/Metadata/Internal/IndexedPropertyGetterFactoryTest.cs
Update EF metadata to allow properties to use a getter based on an indexer on the surrounding entity class rather than a member. (Note: setting is not in this PR - that will come later). This addresses part of issue #13610.
> Changing metadata to allow getting properties based on an indexer

- src/EFCore.Relational/Extensions/RelationalExpressionExtensions.cs
- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Relational/Storage/TypeMaterializationInfo.cs
- src/EFCore.SqlServer.NTS/Internal/SqlServerNetTopologySuiteExpressionExtensions.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerCurveMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryCollectionMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerLineStringMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerNetTopologySuiteMemberTranslatorPlugin.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerNetTopologySuiteMethodCallTranslatorPlugin.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerPointMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerPolygonMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerPolygonMethodTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
Fixes #13580 
**Providers**, type mappings can now be specified on SqlFunctionExpression to improve the handling of arguments and results.
> SqlServer Spatial: Improve type inference

- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> SqlServer Spatial: Use Parse for more SQL constants

- src/EFCore.Design/Design/OperationExecutor.cs
Manually verified the following scenarios:
Tool | Runtime | Result
--- | --- | ---
2.1.4 | 2.2.0 | Warning
2.2.0 | 2.2.0 | OK
2.2.0 | 2.2.1 | OK
Fixes #12869
> Tools: Don't warn for mismatched patch version

- src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/IndexedPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Internal/IndexedPropertySetterFactoryTest.cs
Update EF metadata to allow properties to use a setter based on an indexer on the surrounding entity class rather than a member. This addresses part of issue #13610.
(Also found a small update to the way the getter for indexers should work - this is a follow-on to PR #13656).
> Changing metadata to allow setting properties based on an indexer

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
```
- DefaultQuerySqlGenerator.GenerateOrdering() should be calling GeneratePseudoFromClause() when generating "SELECT 1"
```
> Append pseudo from clause to DefaultQuerySqlGenerator.GenerateOrdering

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Added a short circuit so the whole expression did not get evaluated. 
Fixes #13068
> Add short circuit for null coalesce expression

- src/EFCore/EntityFrameworkQueryableExtensions.cs
- test/EFCore.Tests/Extensions/QueryableExtensionsTest.cs
Needed this in a lot of cases already. The latest need was to fetch data for a GraphQL [CollectionBatchDataLoader](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/DataLoader/CollectionBatchDataLoader.cs).
> Add ToLookupAsync extension methods for IQueryable

- src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/IsNullExpressionBuildingVisitor.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/PredicateReductionExpressionOptimizer.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/RelationalNullsExpandingVisitor.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Problem was that we were not applying clr null semantics when comparing result of functions, i.e. if the function results in null and we compared it to another null value, we would treat them as non-equal. According to clr null semantics they should be treated as the same.
Fix is to expand IsNullExpression builder to handle functions with nullable arguments.
f(a, b) == null <=> a == null || b == null, unless function is COALESCE (in that case both arguments have to be null), so we can just test arguments not the entire function expression.
Also added small optimization in PredicateReductionExpressionOptimizer that removes redundant IS NULL terms.
> Fix to #13642 - Comparison of nullable result of functions

- src/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendCorrelatedCollectionExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendIncludeToExistingExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendOrderByIdentityExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendOrderByPropertyExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendSelectConstantExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendSelectIdentityExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendSelectPropertyExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendTakeExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/AppendThenByIdentityExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectCoalesceExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectIncludeExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectJoinWithSelfExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectOrderByPropertyExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectStringFunctionExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectThenByPropertyExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/InjectWhereExpressionMutator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/QueryTestGenerationExtensions.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/StringConcatWithSelfExpressionMutator.cs
This aims to increase our query test coverage - new component hooks into AssertQuery and alters existing tests before executing them.
We do it using Mutators - classes that modify the expression, if the expression meets given mutator's requirement.
Currently they are very simple (select property, order by, inject include, inject correlated collection, basic arithmetic operations) and will be extended in the future.
Due to non-deterministic nature of generated queries we are unable to verify SQL as well as reliably verify results - only catching compilation and runtime exceptions.
> [WIP] Adding test infra for procedural test generation

- src/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.JoinGroupJoin.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
There are 3 tests in SimpleQueryTestBase (and still finding more tests along the way) which relies on the assumption that clustered index will be sorted by default e.g in SQL Server.
Those tests fail for database engine which does not sort by default e.g DB2.
This commit modifies the affected tests to include explicit OrderBy for those query that have Skip / Take statement.
> Specify OrderBy for several tests that expect clustered index to be sorted by default

- samples/OracleProvider/src/OracleProvider/Scaffolding/Internal/OracleCodeGenerator.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Scaffolding/OracleCodeGeneratorTest.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Design/MethodCallCodeFragment.cs
- src/EFCore.Relational/Scaffolding/IProviderCodeGeneratorPlugin.cs
- src/EFCore.Relational/Scaffolding/IProviderConfigurationCodeGenerator.cs
- src/EFCore.Relational/Scaffolding/ProviderCodeGenerator.cs
- src/EFCore.Relational/Scaffolding/ProviderCodeGeneratorDependencies.cs
- src/EFCore.Relational/Scaffolding/ProviderCodeGeneratorPlugin.cs
- src/EFCore.Relational/breakingchanges.netcore.json
- src/EFCore.SqlServer.NTS/Design/Internal/SqlServerNetTopologySuiteDesignTimeServices.cs
- src/EFCore.SqlServer.NTS/Scaffolding/Internal/SqlServerNetTopologySuiteCodeGeneratorPlugin.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerCodeGenerator.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteCodeGenerator.cs
- src/EFCore.Sqlite.NTS/Design/Internal/SqliteNetTopologySuiteDesignTimeServices.cs
- src/EFCore.Sqlite.NTS/Scaffolding/Internal/SqliteNetTopologySuiteCodeGeneratorPlugin.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Relational.Tests/TestUtilities/TestProviderCodeGenerator.cs
- test/EFCore.SqlServer.Tests/Scaffolding/SqlServerCodeGeneratorTest.cs
- test/EFCore.Sqlite.Tests/Scaffolding/SqliteCodeGeneratorTest.cs
Manually verified that `UseNetTopologySuite()` is generated correctly.
Fixes #13764
cc @roji
> RevEng: Enable plugins to generate provider and DbContext options

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/City.cs
- src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs
- src/EFCore/Extensions/Internal/EFPropertyExtensions.cs
- src/EFCore/Metadata/IPropertyBase.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/IndexedPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/breakingchanges.netcore.json
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrPropertyGetterFactoryTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrPropertySetterFactoryTest.cs
- test/EFCore.Tests/Metadata/Internal/NavigationTest.cs
- test/EFCore.Tests/Metadata/Internal/PropertyTest.cs
Update query to allow references to indexed properties. This addresses part of issue #13610.
Note: at the moment this only addresses entity queries. I'm still working on `ValueBuffer` queries.
> Allow indexers to work in query

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Updating query to allow projection and order-by queries on indexed properties. Also changed the tests to use `AssertQuery()`. This addresses part of issue #13610.
(Still working on group-by and join etc).
> Updating query to allow projection and order-by queries on indexed properties

- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Updating query to allow group-by and joins on indexed properties. This addresses part of issue #13610.
> Updating query to allow group-by and joins on indexed properties.

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
* Conditional expression does no longer evaluate both sides.
Fixes #12521
Porting fix from master. Minimal risk.
> [2.2] Conditional expression does no longer evaluate both sides. (#13704)

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Issue: We were checking for QueryProvider being the same except for the path when we accessing DbSet property on DbContext which is converted to ConstantExpression of EntityQueryable
Fixed by #13862
Resolves #13775
> Regression Test for joining DbSet from different contexts

- src/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Making sure to use same query from cache
Resolves #13902
> Build fix: Avoid cache miss

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Needed for code literal generation of NodaTime types. Hopefully this can still go into 2.2?
(if merged into release/2.2, this automatically gets merged into master too, right?)
> Generate BigInteger literals in CSharpHelper

- Directory.Build.props
- azure-pipelines.yml
- build/dependencies.props
- build/repo.props
- build/templates/default-build.yml
- korebuild-lock.txt
- run.ps1
- run.sh
- src/EFCore.Analyzers/EFCore.Analyzers.csproj
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/EFCore.Tools/EFCore.Tools.csproj
- src/dotnet-ef/dotnet-ef.csproj
- tools/CleanMSSQLLocalDB.cmd
Changes:
* Update BuildTools and react to changes in code signing configuration and shim generation
* Update dependencies
* Add an Azure Pipelines build definition
* Update bootstrappers to support the --ci switch
This works around #12842 by using a different agent pool which has more CPU resources.
NB: this targets the release/2.1 branch, and will be merged forward into release/2.2 This will replace the files in https://github.com/aspnet/EntityFrameworkCore/tree/master/.vsts-pipelines/builds
> Update BuildTools and add an Azure Pipelines ci definition

- README.md
- azure-pipelines.yml
- build/repo.targets
- build/templates/default-build.yml
Changes:
* Add tags to builds based on whether or not "IsFinalBuild" is true. These can be used in the release pipeline to change build deployment triggers.
* Remove unused variables from the build template
* Switch the internal build queue to "dotnet-internal-temp".
* Add a README build badge
> Add build tags automatically and cleanup dead code from the build job template

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- src/EFCore/Metadata/Internal/ClrAccessorFactory.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/IndexedPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
- src/Shared/PropertyInfoExtensions.cs
- test/EFCore.Tests/Metadata/Internal/IndexedPropertyGetterFactoryTest.cs
- test/EFCore.Tests/Metadata/Internal/IndexedPropertySetterFactoryTest.cs
When an indexed property is created pass in the `PropertyInfo` associated with the indexer which will be used for this property. This has the desired effect of making indexed properties no longer shadow properties and allows the code to reference that `PropertyInfo` directly. This addresses part of #13610.
> Make Indexed Properties no longer Shadow Properties

- version.props
Updating the version.props file to match the plan of record on versioning, which is to start building our packages as 3.0.0-preview-$(buildnumber) instead of "preview1", "preview2", etc.
> Update branding to 3.0.0-preview

- azure-pipelines.yml
- build/dependencies.props
- korebuild-lock.txt
- src/ef/ef.csproj
- version.props
This implements the shared versioning spec for .NET Core 3.0. See https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Versioning.md for details.
For example, today's build would be `3.0.0-preview.18565.1`
Notably: this uses SemVer 2.0
> Use shortdate in package versions

- Directory.Build.targets
- build/dependencies.props
- test/EFCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
- test/EFCore.Tests/Utilities/TypeExtensionsTest.cs
Upgrade EFCore to build and test against the latest .NET Core 3.0 dependencies.
Changes:
* Update .NET Core to 3.0.0-preview-27117-01
* Update aspnet Extension to 3.0.0-preview.18569.3
* Added a compiler alias because both System.Interactive.Async and System.Runtime define `System.Generic.Collections.IAsyncEnumerable` in .NET Core 3.0.
* Disambiguate `System.Index` and `Microsoft.EntityFrameworkCore.Metadata.Internal.Index`.
> Upgrade .NET Core 3.0 dependencies

- Microsoft.Data.Sqlite.sln
- samples/StreamingSample/Program.cs
- samples/StreamingSample/StreamingSample.csproj
- samples/StreamingSample/input.txt
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
- src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteBlobTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Adds incremental blob I/O to Microsoft.Data.Sqlite. 
Already presented as PR https://github.com/aspnet/Microsoft.Data.Sqlite/pull/501.
Fixes #13824
> Microsoft.Data.Sqlite: Add incremental blob I/O

- src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
- src/EFCore.SqlServer/Metadata/ISqlServerIndexAnnotations.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- src/EFCore.SqlServer/Metadata/SqlServerIndexAnnotations.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/breakingchanges.netcore.json
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
Introduces new `ForSqlServerIsOnline` extension to index builder.
There is a breaking change in `EFCore.SqlServer` in form of new property 
`ISqlServerIndexAnnotations.IsOnline`.
Note that enabling/disabling online index creation does trigger a migration even though I believe it has no effect on the resulting index so it's essentially rebuilt for no reason. If this should be avoided I'd like to request a hint on how to achieve that.
Fixes #11499
> Allow specifying online option on MSSQL indexes

- Directory.Build.targets
- azure-pipelines.yml
- build/dependencies.props
- build/repo.props
- build/templates/default-build.yml
- korebuild-lock.txt
- src/dotnet-ef/dotnet-ef.csproj
- src/ef/ef.csproj
- version.props
This updates targets and property files to build a 2.2.1 version of EF Core.
cc @AndriySvyryd @bricelam @roji
> Prepare the release/2.2 branch for servicing updates

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
The issue was caused by trying to set `isRequired` to the default value when attaching the relationship, because the correct value wasn't recorded.
Fixes #14010
> [2.2.x] Set isRequired value when setting the isRequired configuration source.

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- Added check for constant and parameter expressions when no take or skip is present and filters the order by list
- Fixed up unit tests to omit ORDER BY (SELECT 1) when there is no skip/take.
- Fixed processedExperssion typo
Fixes #10410
> Omit Order By (Select 1) when no skip/take present

- build/dependencies.props
- build/repo.props
- korebuild-lock.txt
Changes 
* Includes updates to to fix bugs in code-signing tools
* Remove a reference to Internal.AspNetCore.Universe.Lineup, which isn't used in servicing branches anymore
> Update buildtools to 2.1.3-rtm-15847

- build/dependencies.props
Somehow, this got missed. Probably while resolving a 2.2 to 3.0 merge conflict.
> Fix NetTopologySuite.IO.SqlServerBytes Version

- src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ScaffoldingTypeMapperSqlServerTest.cs
Fixes #14160 Superceeds #14162
ScafoldingTypeMapper should have been passing `false` when looking for the default mapping, since, non-fixed length is the default. (Compare this to Unicode, where we pass `true` because Unicode is the default.)
Also included is a fix for test, which wasn't Asserting for fixed length, as found by Smit.
Also fixed the code in RelationalTypeMappingInfo that was for some reason using parsed-length to drive the fixed-length flag, although this was a secondary issue.
> Fix scaffolding type mapper FixedLength bug

- build/dependencies.props
> Update SQLitePCL.raw to version 1.1.12

- src/EFCore.Specification.Tests/Query/AsNoTrackingTestBase.cs
- src/EFCore.Specification.Tests/Query/AsTrackingTestBase.cs
- src/EFCore/EntityFrameworkQueryableExtensions.cs
Fixes #13385.
Note that it is not the same method with an optional parameter because those can't be used nicely when generating expressions.
> Add parameter to AsTracking

- src/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
Added additional property to specification test classes to make INSERTs work (SQL Compact does not allow INSERTs into a table with only an Identity column)
fixes #14184
> Make specification tests run with SQL Server Compact

- src/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
- src/EFCore.Specification.Tests/ProxyGraphUpdatesFixtureBase.cs
- src/EFCore.Specification.Tests/StoreGeneratedFixupTestBase.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
- src/EFCore/Metadata/Conventions/Internal/KeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/Internal/ValueGeneratorConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
* Find a candidate property using the normal convention or create a shadow int property if none found
* Configure the PK to be composed of the FK property(ies) and the found property
* The non-FK property is configured as ValueGeneratedOnAdd
HasKey and KeyAttribute work the same as on other entity types
Fixes #13295
> Add key discovery convention for owned collections

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
- Added |DataDirectory| checks in SqliteConnection connection string path
- Created unit test for checking |DataDirectory| support
Fixes #13840
> Support |DataDirectory| for SQLite provider

- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore.Specification.Tests/WithConstructorsTestBase.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- src/EFCore/Metadata/Internal/ClrPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
- test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilder.Other.cs
Fixes #13237
On both .NET Core and .NET Framework, the expression builder APIs do not allow assignment to IsInitOnly fields. However, on .NET Core, if this check is bypassed, then the compiler will happily compile the expression tree, which results in performant code for setting readonly fields. We should decide if we're comfortable doing this.
On .NET Framework, the compiler will not compile the expression tree, so if not running on Core, we drop down to calling FieldInfo.SetValue, which both boxes and is on the order of 1000 times slower, but has always worked and so should be safe to do.
> Allow writing to to readonly fields

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
Command removes itself from connection when disposing itself.
Fixes #13898
> Microsoft.Data.Sqlite: Fix memory leak after disposing SqliteCommand

- src/EFCore.SqlServer/ValueGeneration/Internal/ISqlServerValueGeneratorCache.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorCache.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
- test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
- test/EFCore.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs
Fixes #11451
Fix is to add database name and server name to the sequence state cache key.
> Fix SequenceHiLo to use the sequence from the correct database

- eng/Signing.props
- eng/Versions.props
(Manually running on the [internal CI](https://dev.azure.com/dnceng/internal/_build/results?buildId=68596))
> Remove workaround for dotnet/arcade#1634

- azure-pipelines.yml
- eng/Versions.props
Changes:
- Allow continuing without SpatiaLite on macOS
- Divide Versions.props into more granular groups to avoid merge conflicts
> Make CI more robust

- azure-pipelines.yml
- build/dependencies.props
- korebuild-lock.txt
- version.props
This backports a change made in 2.2 to build servicing builds as `2.1.8-servicing-123` instead of `2.1.8-rtm-123`
> [backport] Change prerelease label to 'servicing' for 2.1.x nightly builds

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
> [2.2.x] Reset the property isNullable configuration source when removing a key.

- src/EFCore/Metadata/Internal/Property.cs
> [2.2.x] Don't change FK requiredness when only some of the contained properties change nullability.

- src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs
Removes an unused constant from the `InMemoryDbContextOptionsExtensions` class.
> Remove unused constant from InMemoryDbContextOptionsExtensions

- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
Use a fixture in DbContextPoolingTest to ensure Northwind is initialized
Fixes #14434
> Use a retrying execution strategy when initializing Northwind

- src/EFCore/Query/Internal/ExpressionEqualityComparer.cs
- test/EFCore.Tests/Query/ExpressionEqualityComparerTest.cs
I couldn't get the build to work locally so I'm not sure that the test is correct but... here goes!
> Add support for ExpressionType.Index to ExpressionEqualityComparer (fixes #14509)

- azure-pipelines.yml
We already do this on macOS. When it fails, it will show up as a warning in the CI and the tests will be skipped.
> CI: Continue on errors while installing SpatiaLite on Ubuntu

- src/EFCore/ChangeTracking/CascadeTiming.cs
- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbContext.cs
- src/EFCore/DeleteBehavior.cs
- src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
- test/EFCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/ProxyGraphUpdatesInMemoryTest.cs
- test/EFCore.Specification.Tests/DatabindingTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/LoadTestBase.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedFixupTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs
- test/EFCore.Tests/DbContextTrackingTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Fixes #10114
Allows timing cascade delete (i.e. delete of dependent on principal deletion) and delete orphans (i.e. delete of dependent on severing its relationship to the principal) to be configured as:
* Immediate: Dependents changed to Deleted immediately, or at least at the next DetectChanges
* OnSaveChanges: Dependents are not changed to Deleted until SaveChanges is called
* Never: Cascades don't happen automatically. They can be triggered by a new method: `context.ChangeTracker.CascadeChanges()`
The default for both has been changed to `Immediate` which is a breaking change, but likely a better default because:
* Auditing in overridden SaveChanges will now report anything that will be deleted
* Data binding will reflect the changes immediately
However, deleting orphans can be more …
> Allow cascade delete timing to be configured

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/ChangeTracking/EntityEntryGraphNode`.cs
- src/EFCore/ChangeTracking/IEntityEntryGraphIterator.cs
- src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs
- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/IEntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/NavigationEntry.cs
- src/EFCore/DbContext.cs
- test/EFCore.InMemory.FunctionalTests/StoreGeneratedFixupInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/InheritanceFixtureBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedFixupTestBase.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
Issue #14616
Detected entities with generated key values that have already been set are marked as Modified instead of Added.
Also, some re-working of the EntityGraphAttacher to make the node generic on TState.
> Make DetectChanges honor store-generated key values when tracking new entities

- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
This mostly affects owned types, because on non-owned types the properties we would've used for the FK are likely to be part of the PK and thus wouldn't be used.
Fixes #13274
> Don't discover FK properties named the same as the principal properties

- eng/Versions.props
Per latest 3.0 release plan, we'll start including the preview number in the package branding.
> Update package branding to 3.0.0-preview3

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/CollectionEntry.cs
- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/ReferenceEntry.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/LazyLoader.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
Issue #13552
It will DetectChanges in the current entry and any tracked principals. This ensures that any cascading operations are detected. Dependents are not checked eagerly, but if a Member/Reference/Collection method is called to get related dependent entities, then local DetectChanges is run on the related dependents. These two things eliminated any breaks in our functional tests.
Also, Lazy-loading now does a local DetectChanges, which means FK changes will be picked up and honored by the loader.
> Introduce local DetectChanges

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
Issue #14523
I looked at making it easy to change the level back, but the ASP.NET delegate compiler expects the LogLevel to come in pre-baked--i.e. its parameterized on the level, which means we would have to regenerate the delegate to do this.
> Change log-level for query-executed to Debug

- src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
Problem was that we were only preventing null expansion in predicate, leaving projection and orderings intact.
Fix is to go through entire SelectExpression and prevent null expansion on all encountered comparisons.
Because this changes the result it is switched off by default.
> Fix to #13285 - UseRelationalNulls does not work with SELECT conditions

- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
Fixes #14226
Specifically, when using a store-generated key, propagation of a key value will cause dependents to be searched for, which can't be found since the dependents don't have keys.
> [2.2] Stop assuming dependent entity types have a key

- azure-pipelines.yml
> CI: Don't pipe to SQLCMD

- src/EFCore/EntityFrameworkServiceCollectionExtensions.cs
We were making sure these were registered in `AddDbContext` because EF used to need them to be registered, but now it's only optional depending on what you're doing. However, it seems that even in ASP.NET code this causes problems because people are using `AddDbContext` as a means to add these things to the service provider. This indicates poorly written tests/samples, but I think we can assume such will exist in the wild too, so adding these back in to avoid the break.
> Add back registration for logging and memory cache

- src/EFCore/Metadata/Internal/TypeBase.cs
- src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
- src/EFCore/Storage/ValueConversion/CastingConverter.cs
- src/EFCore/Storage/ValueConversion/EnumToNumberConverter.cs
Issue:
Calling `GetRuntimeProperties().FirstOrDefault()` throws `System.InvalidOperationException: Collection was modified; enumeration operation may not execute.` sometimes, see https://github.com/aspnet/AspNetCore-Internal/issues/1776
I cannot repro this locally and it should not ever happen for 3 reasons:
1. As far as I can tell the test in question doesn't perform any requests in parallel
2. Even if it did `GetRuntimeProperties()` is called during model construction and the results are stored, so the underlying dictionary shouldn't be modified after that point. The stack trace from failing tests is coming from the query pipeline.
3. Even if the underlying dictionary wasn't initialized somehow the memory barrier should prevent returning a dictionary before it has finished being …
> Fix another race condition in GetRuntimeProperties()

- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore/Storage/TypeMappingInfo.cs
* Moved parsing of the store type from RelationalTypeMappingInfo to RelationalTypeMappingSource, where it can be overridden.
* Moved considerable additional initialization logic from RTMI to RTS. RTMI no longer holds parsed facet fallbacks (e.g. `_parsedSize`) - the type mapping info is simply initialized with the right value.
* Collapsed together some constructors in RelationalTypeMappingInfo and TypeMappingInfo.
* Added option to parse Unicode from the store type for MySQL.
* Removed IsMax setting which wasn't used anywhere.
Part of #11896
Some additional comments:
* Do we really not need IsMax anymore, it wasn't being used anywhere? If we need it, I can add it back in a way that's SQL Server-specific rather than at the relational level.
* One thing that still doesn't seem possible, is …
> Refactored store type parsing in type mapping

- src/EFCore/Metadata/Internal/TypeBase.cs
* Switch to Interlocked.CompareExchange()
* Protect RuntimeFields as well
* Defensively lock after clearing caches to propagate changes
Continues #14742
> Improve concurrency around Runtime{Properties,Fields}

- Directory.Build.targets
- azure-pipelines.yml
- eng/Version.Details.xml
- eng/Versions.props
* Update to latest extensions build
* Workaround dotnet/sdk#2976
* Remove automatic triggers for internal/release/* branches
> Update dependencies and workaround dotnet/sdk#2976

- azure-pipelines.yml
- eng/Versions.props
We're getting consistent build timeouts. Changing to a unique feed instead. Each upstream partner will need to add this to restore sources.
> Change publish feed to workaround 'Waiting to obtain an exclusive lock on the feed.'

- src/EFCore/Metadata/Conventions/Internal/ValueGeneratorConvention.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Specification.Tests/Query/InheritanceFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ValueGeneratorConventionTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Issue #14617
Previously, they were generated on the client by default, with GUIDs used as the generated value. Now they are not generated by default (which is how they are usually used) but can be configured to the old behavior in the normal way.
> Stop making string and binary keys be generated by default

- src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs
- src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalFixture.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/LoginDetails.cs
- test/EFCore.Specification.Tests/UpdatesFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
Don't prefix columns on the same type when uniquifying
Fixes #14055
> Enable table name uniquification

- activate.ps1
- activate.sh
These put the local `dotnet` on the path so you can use it normally
PowerShell: . .\activate.ps1
macOS/Linux: source activate.sh
> Add activate scripts

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
@AndriySvyryd am not sure I fully understood the 2.1 backwards compatibility implemented (was not involved) so I'd appreciate a good review on this to make sure it's good... Note that it's only part of #12405, I intend to look at the StoreTypePostFix later part as part of #11896.
* Removed precision/scale 2.1 fallback behavior
* Made RelationalTypeMapping.Clone() abstract
Part of #12405
> Remove 2.1 provider fallback behavior

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilder.Other.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericUnqualifiedStringTest.cs
Issue #9171
Now if these methods are called with a single string, then that string represents the navigation property name. If there is no CLR property with the given name, then an exception is thrown.
The exception is when the entity type has no CLR type, in which case the old behavior is preserved so as not to break existing model snapshots. Entity types with no CLR type are only valid in model snapshots.
> Improve experience for HasOne/HasMany used with single string

- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
- src/Microsoft.Data.Sqlite.Core/Extensions/SqliteConnectionExtensions.cs
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- test/EFCore.InMemory.Tests/EFCore.InMemory.Tests.csproj
- test/EFCore.Proxies.Tests/EFCore.Proxies.Tests.csproj
- test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SpatialiteRequiredAttribute.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteDatabaseCleaner.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestStore.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteFactoryTest.cs
This also updates EFCore.Sqlite to use the new method.
There is a breaking change in SpatialiteLoader. The methods used to take a DbConnection (I guess 'cause we could) but now take a SqliteConnection.
You no longer need to call SqliteConnection.EnableExtensions() before using SpatialiteLoader since the new LoadExtension method will bypass the connection setting. This greatly improves usability and makes EnableExtensions only apply to the load_extension SQL function. Given this, EnableExtensions should probably have been a connection string keyword.
In fact, SpatialiteLoader isn't really needed anymore since calling UseNetTopologySuite now loads the extension for open external connections. Maybe we should make it internal. (See #14821)
LoadExtension has some unusual behavior when the …
> Microsoft.Data.Sqlite: Add LoadExtension() to SqliteConnection

- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Makes the `Where_subquery_correlated_client_eval` to use explicit order.
Fixes #14874.
> Fixed ordering in test

- src/EFCore.SqlServer/Query/Pipeline/SqlServerStringMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Pipeline/SqliteStringMethodTranslator.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
If the pattern is constant, we now escape it client-side and send a simple LIKE expression - no need for fancy concatenation and an additional LEFT(LEN()) check.
Fixes #14657
Replaces #14820
> Optimize translation of string.{Starts,Ends}With

- azure-pipelines.yml
- Suppresses the 'Welcome to .NET Core!' output that times out tests and causes locked file issues. When using dotnet we're not guarunteed to run in an environment where the dotnet.exe has had its first run experience already invoked. This would cause various functional tests to time out in AspNetCore and AspNetCore-Tooling and occasionally crash due to dotnet first run experience sentinels being locked.
aspnet/AspNetCore-Internal#1859
> Skip first run experience on azure pipelines.

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore/Internal/Reference.cs
- src/EFCore/Metadata/Builders/InvertibleRelationshipBuilderBase.cs
- src/EFCore/Metadata/Builders/RelationshipBuilderBase.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/Internal/IConventionBatch.cs
- src/EFCore/Metadata/Conventions/Internal/MetadataTracker.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupCompositeTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/ForeignKeyTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
FK requiredness would still be the same as before when running conventions or in the snapshot, so this isn't really a breaking change.
Generate `IsRequired()` in the snapshot to avoid a breaking change in the future
Fixes #14197
> Allow optional foreign keys on non-nullable properties

- Directory.Build.targets
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
~~Blocked on dotnet/sdk#2867~~
> Update .NET Core SDK

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerExtensions.cs
- src/EFCore/ChangeTracking/LocalView.cs
- test/EFCore.InMemory.FunctionalTests/DatabaseErrorLogStateTest.cs
- test/EFCore.Specification.Tests/Query/ChangeTrackingTestBase.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalShadowEntityEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Part of #8898
Fixes #14231
Investigation into DbSet.Local shows that:
* Iteration over tracked entities had a lot of LINQ code; fixed by un-LINQing
* Multiple composed iterators cause slow-down; fixed by giving LocalView it's only IStateManager method
* Filtering causes slow-down; fixed by splitting storage into multiple dictionaries. Makes lookup for entity instance slightly slower.
* Calculate Count lazily
This means that DbSet.Local iteration is now about 3x faster, although it depends a lot on what is being tracked. Getting an ObservableCollection and then iterating over that _once_ is slower than just iterating over the entries once. Iterating over the ObservableCollection multiple times is still faster than iterating over DbSet.Local multiple times. This seems like a reasonable …
> Improve perf for iterating over tracked entities

- src/EFCore/EntityFrameworkServiceCollectionExtensions.cs
- src/EFCore/Internal/ScopedLoggerFactory.cs
- test/EFCore.Tests/DbContextServicesTest.cs
Issue #14756
This will break some ASP.NET tests/samples when this change is consumed. (I tried to get ASP.NET tests to run locally with updated EF Core; no luck.)
> Stop calling `AddLogging` and `AddMemoryCache` from `AddDbContext`

- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Issue: When top level projection has convert node, we introduce explicit cast since we read exact type from DataReader.
Though we don't add cast when it is just nullability change or if the convert node is not on top level.
In this particular case, compiler generated expression tree contained, int to double to double? convert since int cannot be cast to double? directly. But when translating we did not introduce explicit cast for first level since _not top level_ and for second level it was nullability change only. Hence lack of explicit cast during projection caused error.
Fix: Remove any convert nodes to figure out if we need to apply explicit cast.
Resolves #14604
> [2.2.x] Query: Add explicitCast for projection more robustly

- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Query/ExpressionVisitors/Internal/CosmosEntityQueryableExpressionVisitor.cs
- src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
- test/EFCore.Cosmos.FunctionalTests/NestedDocumentsTest.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Remove unsupported Cosmos tests.
> Throw when tracking an owned entity as the owned type its base is mapped to.

- eng/Version.Details.xml
- eng/Versions.props
- previous update was incoherent and not caught until we reached aspnet/AspNetCore
- upgrades core-setup and Extensions dependencies but downgrades CoreFx to achieve coherency
> Manually update dependencies from CoreFx, core-setup and Extensions

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Fixes #13830
I'll go over the finer points of the design in a meeting to make sure we all agree with the behaviors before merging.
> Microsoft.Data.Sqlite: Delay statement execution until NextResult

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
It was previously a mixture of INTEGER and TEXT.
Resolves #13253, resolves #13841
cc @AlexanderTaeschner
Additional type-related improvements are tracked by #8824, #13831 & #13839
> SQLite: Change fallback type to BLOB

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
- src/EFCore/ChangeTracking/ValueComparer.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationSubqueryInjector.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionFindingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs
- src/EFCore/Query/ExpressionVisitors/ProjectionExpressionVisitor.cs
- src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
- src/EFCore/Query/Internal/ReLinqEvaluatableExpressionFilter.cs
Here are some fixes for reflection lookups to make them more robust - I may not have caught them all. Note that I didn't touch reflection on EF Core's types, or some wonky stuff happening in our tests (e.g. [SqlExceptionFactory.cs](https://github.com/aspnet/EntityFrameworkCore/blob/9afed5819d71ab1751741a591d81aa31d179c60b/test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlExceptionFactory.cs#L11).
Also simplified some lookups by using `GetRuntimeMethod()` rather than elaborate LINQ checks, it seems robust enough but let me know if there's some issue with that.
Fixes #14878
> More robust reflection lookups on non-EF types

- test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
> Enable ambient transaction tests on .NET Core

- src/EFCore.Cosmos/Extensions/CosmosDbContextOptionsExtensions.cs
- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/CosmosEndToEndTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.Tests/Configuration/CosmosDbContextOptionsExtensionsTests.cs
CosmosDb provider doesn't support a configuration option for a current region
Fix #15007
```
- Detail 1
- Detail 2
```
> CosmosDb provider support for a current region option

- src/EFCore/ChangeTracking/CollectionEntry.cs
- src/EFCore/ChangeTracking/CollectionEntry`.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalShadowEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/ReferenceEntry.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs
- src/EFCore/Metadata/Internal/IClrCollectionAccessor.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ChangeTracking/CollectionEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
Don't null out owned inverse when the owner and owned entity are deleted or detached.
Fixes #15033
> Add API to get an entry from an owned collection

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Scaffolding/IReverseEngineerScaffolder.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- src/EFCore.Relational/Scaffolding/DatabaseModelFactory.cs
- src/EFCore.Relational/Scaffolding/DatabaseModelFactoryOptions.cs
- src/EFCore.Relational/Scaffolding/IDatabaseModelFactory.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalDatabaseCleaner.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
Resolves #14602 
**Providers** in addition to updating your method signatures, be sure to inherit from DatabaseModelFactory.
> RevEng: Add DatabaseModelFactoryOptions

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
> Migrations: Use parameter objects in MigrationsSqlGenerator

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
- test/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
- test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
Fixes #8764
**Providers** you may need to tweak the way computed columns are implemented.
> Migrations: Throw not implemented in MigrationSqlGenerator for computed columns

- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/DbSetTest.cs
Makes the message specific to binding to `.Local`, rather than being about binding to a query.
Issue #8898
> Small change to data binding exception message

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/RelationalConnection.cs
- test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
On SQL Server if a connection was enlisted in a transaction, closed, then enlisted in a different transaction before the first one was completed results in a deadlock. We maintained the connection opened to allow the database to throw in this case, but this was unexpected behavior.
Now we close the database connection, but keep the reference to the original transaction to perform the above check explicitly.
This change also allowed to remove the semaphore as the opened count shouldn't be mutated on different threads anymore.
Fixes #14218
> Close connection even if ambient transaction hasn't completed

- eng/Version.Details.xml
- eng/Versions.props
- specific Extensions package doesn't matter much since packages from that repo will move together
- should reduce the builds of EntityFrameworkCore that AspNetCore can't take
In this first iteration, coherence with the newer Extensions _downgrades_ Microsoft.NetCore.App
- this repo was a bit ahead of the rest
> Chain coherence links up to aspnet/Extensions

- src/EFCore.Relational/Metadata/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
- src/EFCore.Relational/Query/Expressions/NullableExpression.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Relational/Query/Sql/ISqlExpressionVisitor.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/FuelTank.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs
A dependent is considered missing if any of its required properties is null or if all non-pk properties are optional and all of them are null.
Fixes #9005
> Make shared table dependents optional.

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Added test logic that checks if queries have top-level ordering, and if so throws exception if they are not asserting order OR using a client-side element sorter. Fixed all tests that were caught by the check.
In order to circumvent then check (in case of non-deterministic orderby) one can add a top level identity projection: .Select(c => c)
> Fix to #15114 - Query/Test: query test infra can obscure errors around ordering

- src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs
- src/EFCore.Relational/Metadata/Internal/RelationalPropertyExtensions.cs
- src/EFCore.SqlServer/Metadata/SqlServerKeyAnnotations.cs
- src/EFCore/Extensions/ConventionPropertyExtensions.cs
- src/EFCore/Extensions/MutablePropertyExtensions.cs
- src/EFCore/Extensions/PropertyExtensions.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/BackingFieldConvention.cs
- src/EFCore/Metadata/Conventions/Internal/ServicePropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/IndexedPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Metadata/Internal/PropertyIdentity.cs
- src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryFixtureBase.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/BackingFieldConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Throw an exception when calling `SetField` would change the shadowness of a property or the name of the identifying `MemberInfo`.
Rename `GetContainingPrimaryKey` to `FindContainingPrimaryKey`
Rename `PropertyIdentity.Property` to `MemberInfo`
Part of #214
> Always use a MemberInfo for navigations if there is one matching the name

- src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
- test/EFCore.Tests/Metadata/Internal/PropertyAccessorsFactoryTest.cs
… instead of member access.
Found a small situation when investigating Shared-Type Entities where I had missed using index access instead of member access. But it's really part of issue #13610 rather than Shared-Type Entities so sending it as a separate PR.
> Missed one situation for Indexed Properties where we need index access

- eng/Version.Details.xml
- eng/Versions.props
- Microsoft.Extensions.Caching.Memory - 3.0.0-preview4.19204.2
- Microsoft.Extensions.Configuration - 3.0.0-preview4.19204.2
- Microsoft.Extensions.Configuration.EnvironmentVariables - 3.0.0-preview4.19204.2
- Microsoft.Extensions.Configuration.Json - 3.0.0-preview4.19204.2
- Microsoft.Extensions.DependencyInjection - 3.0.0-preview4.19204.2
- Microsoft.Extensions.HostFactoryResolver.Sources - 3.0.0-preview4.19204.2
- Microsoft.Extensions.Logging - 3.0.0-preview4.19204.2
Dependency coherency updates
- Microsoft.CSharp - 4.6.0-preview4.19204.1
- Microsoft.DotNet.PlatformAbstractions - 3.0.0-preview4-27604-05
- Microsoft.Extensions.DependencyModel - 3.0.0-preview4-27604-05
- Microsoft.NETCore.App - 3.0.0-preview4-27604-05
- Microsoft.NETCore.Platforms - 3.0.0-preview4.19204.1
- …
> Update dependencies from https://github.com/aspnet/Extensions build 20190404.2

- test/EFCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/LoadInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/ProxyGraphUpdatesInMemoryTest.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/LoadSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/ProxyGraphUpdatesSqliteTest.cs
GraphsUpdate, ProxyGraphsUpdate & Load tests for InMemory and Sqlite
> Skipping more tests that were missed in previous chekin

- build/templates/default-build.yml
- aspnet/AspNetCore-Internal#2231
- use internal pools for all internal builds
- do not sign in builds for internal pull requests
nits:
- VSTS => Azure DevOps
- remove workaround for fixed issue
> Support internal pull requests

- .github/ISSUE_TEMPLATE.md
We had this in the SignalR repo to prevent folks from making public bugs with security issues.
> Add security section to issue template.

- azure-pipelines.yml
The PublishBuildArtifacts fails when artifacts/packages/ does not exist or is empty. This change will only publish packages if build.cmd succeeds (which means all tests, code signing, and compilation must pass)
Fix https://github.com/aspnet/AspNetCore-Internal/issues/2305
> Fix for false-positive publish failures when tests fail

- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
Necessary for PostgreSQL, which folds unquoted identifiers to lowercase...
> Add forgotten delimiter in raw SQL test

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
Summary of the change
- Fix the condition in `CSharpDbContextGenerator.GenerateSequence` to correctly append schema parameter to sequence creation code when sequence's schema is provided.
Fixes #15513
> fix condition in CSharpDbContextGenerator.GenerateSequence

- src/EFCore/Query/NavigationExpansion/NavigationExpansionHelpers.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
They are required for binding in projection
Blocking issue for #14455
> [Query] Always pass in Members when creating NewExpression

- src/EFCore.InMemory/Query/PipeLine/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/PipeLine/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/PipeLine/InMemoryShapedQueryExpression.cs
- src/EFCore.Relational/Query/PipeLine/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/PipeLine/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/PipeLine/RelationalShapedQueryExpression.cs
- src/EFCore.Relational/Query/PipeLine/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/PipeLine/ProjectionBindingExpression.cs
- src/EFCore/Query/PipeLine/QueryableMethodTranslatingExpressionVisitor.cs
Invariant: ProjectionBindingExpression can only appear in ShapedQueryExpression.ShaperExpression and it would always refer to ShapedQueryExpression.QueryExpression
> [Query] Remove QueryExpression from ProjectionBindingExpression

- src/EFCore.InMemory/Query/PipeLine/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/PipeLine/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/PipeLine/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/PipeLine/InMemoryShapedQueryExpression.cs
- src/EFCore.InMemory/Query/PipeLine/InMemoryShapedQueryExpressionVisitor.cs
- src/EFCore.Relational/Query/PipeLine/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/PipeLine/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/PipeLine/RelationalShapedQueryExpression.cs
- src/EFCore.Relational/Query/PipeLine/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore/Query/PipeLine/ProjectionBindingExpression.cs
- src/EFCore/Query/PipeLine/QueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/PipeLine/ShapedQueryExpression.cs
- src/EFCore/Query/PipeLine/ShapedQueryExpressionVisitor.cs
The LambdaExpression.Parameters were not being used anyway
> [Query] Make ShapedQueryExpression.ShaperExpression lambda body only

- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Fixes #14963 Changed default value of ColumnSize from DbNull to -1.
> [Microsoft.Data.Sqlite] ColumnSize of text fields is always DbNull.Value

- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/NonNullableConvention.cs
- src/EFCore/Metadata/Conventions/Internal/NonNullableNavigationConvention.cs
- src/EFCore/Metadata/Conventions/Internal/NonNullableReferencePropertyConvention.cs
- src/EFCore/Metadata/Conventions/Internal/RequiredNavigationAttributeConvention.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/NonNullableNavigationConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/NonNullableReferencePropertyConventionTest.cs
This introduces two new conventions - mirroring the existing RequiredPropertyAttributeConvention and RequiredNavigationAttributeConvention - which detect C# 8 non-nullable properties and treat them in the same way as `[Required]`. Some remarks:
* As things currently stand, the compiler synthesizes the NullableAttribute type used to indicate nullability into the assemblies it compiles. That means we need recognize it by name, use reflection to access its contents, and be prepared for multiple NullableAttribute types in different assemblies. I've done some caching around this to keep it efficient, things may get simplified by RTM-time.
* The non-nullable navigation convention emits the same two log messages as the [Required] one (NonNullableReferenceOnBothNavigations, …
> Support C# 8 nullable reference types

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
fixes #15104
Sample:
```
PM> Get-DbContext
AzureDbContext   
AzureOtherContext
PM> Get-DbContext -Context AzureDbContext
providerName                            databaseName dataSource             options
------------                            ------------ ----------             -------
Microsoft.EntityFrameworkCore.SqlServer AzureData    (localdb)\MSSQLLocalDB None   
```
> Modify Get-DbContext command to list DbContexts

- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
> Implement reverse engineering of views for SQLite

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- Switched up ForeignKeyAttribute and InversePropertyAttribute to use nameof() syntax
- Added InversePropertyAttribute into code generation unit test
Fixes #11744
> Added nameof syntax in scaffolding data annotations attributes

- src/EFCore/Query/PipeLine/NullCheckRemovingExpressionVisitor.cs
> Query: Make NullCheckRemovingExpressionVisitor thread safe

- eng/Versions.props
This upgrades the compiler to the version bundled in Arcade, which is 3.2.0-beta1-19253-08 right now. This allows this repo to consume a compiler that is newer than what is bundled in the .NET Core SDK. This is valuable during previews to get the latest C# 8 features and test them against EF's expression tree -> SQL code. 
This should workaround aspnet/AspNetCore-Internal#2476.
> Use Microsoft.NET.Compilers 

- src/EFCore.Relational/Query/PipeLine/NullSemanticsRewritingVisitor.cs
- src/EFCore.Relational/Query/PipeLine/SqlExpressionOptimizingVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitorsFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/CaseExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SqlBinaryExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SqlFunctionExpression.cs
- src/EFCore.SqlServer/Query/Pipeline/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerShapedQueryOptimizingExpressionVisitorsFactory.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerStringMethodTranslator.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpander.cs
- src/EFCore/Query/PipeLine/NegationOptimizingVisitor.cs
- src/EFCore/Query/Pipeline/FunctionPreprocessingVisitor.cs
- src/EFCore/Query/Pipeline/QueryCompilationContext2.cs
- src/EFCore/Query/Pipeline/QueryCompilationContextFactory2.cs
- src/EFCore/Query/Pipeline/QueryOptimizingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NullSemanticsQuerySqliteTest.cs
Currently we always apply "full" null semantics translation, meaning null values are completely removed from the tree. We could produce slightly simpler translation where it doesn't matter if we return NULL or FALSE (e.g. in predicates)
Also, currently when testing if a given subtree is null we do it in naive way, simply adding IsNull call around entire subtree. Instead we can test it's constituents, but to do it properly we need to persist nullability information.
> Implementing C# null semantics in the new pipeline

- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpansionExpression.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Problem was we were not handling a scenario with nested FirstOrDefault, e.g. customers.Select(c => orders.Select(orderDetails.FirstOrDefault()).FirstOrDefault().DetailName)
In this case we need to recursively pushdown the property until we don't encounter cardinality reducing operator.
Also resolves #15363 - Consecutive calls to FirstOrDefault() in a projection not translatable
This was already working but adding a test.
> Fix to #15720 - Query: Subquery Member pushdown

- src/EFCore.Design/Design/OperationException.cs
- src/EFCore/DbUpdateConcurrencyException.cs
- src/EFCore/DbUpdateException.cs
- src/EFCore/Storage/RetryLimitExceededException.cs
- test/EFCore.Design.Tests/ApiConsistencyTest.cs
- test/EFCore.Design.Tests/DesignExceptionTest.cs
- test/EFCore.Tests/ExceptionTest.cs
Fixes #12285
Related #15214
It turns out that the code causing #15214 to happen is not due to normal serialization, and hence it is likely not possible to fix this in EF code. (See comments on the issue.) However, the issue (or similar) would still exist if the exception was serialized, and the fix is to use best practices for exceptions, so doing that.
For reference, see https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions
> Use best-practices for Exception classes

- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/ShaperExpressionDedupingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/LikeExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SqlConstantExpression.cs
- src/EFCore/Query/Pipeline/ProjectionBindingExpression.cs
- src/EFCore/Query/Pipeline/ProjectionMember.cs
This phase is our form of projection before we call into client code
> [Query] Pull out variables upfront for ShaperExpression

- Directory.Build.targets
- eng/Version.Details.xml
- eng/Versions.props
This ensures the version of .NET Standard 2.1 we are using matches with the .NET Core runtime. This caused some problems in AspNetCore. Adding to this repo now as a defensive measure.
> Automate dependency updates to NETStandard 2.1 ref pack

- src/EFCore.Relational/Query/Pipeline/NullSemanticsRewritingVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was that when we compared scalar subquery to null, we would assume the subquery is never null so we would never return any results. Scalar subqueries can be null when using entities.Where(e => false).Select(e => e.Name).FirstOrDefault() pattern.
Fix is to always assume SubSelectExpression is nullable.
> Fix to #15778 - Query: null semantics visitor incorrectly classifies subquery returning single scalar value as non-nullable

- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
Also remove redundant code from Include in tracking query since all those task are already done by state manager
Couldn't enable GearsOfWar tests since they use TPH.
> Query: Add support for join on composite keys generated by Nav rewrite

- src/EFCore/Query/NavigationExpansion/LinqMethodHelpers.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpansionHelpers.cs
- src/EFCore/Query/Pipeline/QueryOptimizingExpressionVisitor.cs
Generating LeftJoin calls in nav expansion. In case source is Enumerable we apply AsQueryable. Removing second pass of GroupJoin flattening visitor, it also makes queries simpler: we do longer produce double TransparentIdentifiers when translating GroupJoin-SelectMany-DefaultIfEmpty, because we no longer project the inner groupings.
> Fix to #15634 - Query: Nav Expansion should generate flattened LeftJoin

- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/Pipeline/RelationalEntityQueryableExpressionVisitor2.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/FromSqlExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/ResultOperators/Internal/FromSqlExpressionNode.cs
- src/EFCore.SqlServer/Query/Pipeline/SearchConditionConvertingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncFromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/AsyncFromSqlQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
* Parameterization not implemented (see #15750)
* FromSqlRaw() and FromSqlInterpolated() are now defined over DbSet<>,
not IQueryable<>. FromSql() is still defined over IQueryable<> but
throws if not directly on a DbSet<>.
Closes #15704 
(rebased and pushed last minute before boarding a plane, it may be somewhat broken :))
> Basic FromSql() support in new pipeline

- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
- src/EFCore/Storage/Database.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Tests/QueryProviderTest.cs
- fixed bug where we would visit member expression twice in some cases during nav rewrite
- removed code that would swallow NotImplementedExceptions, which was making debugging more difficult
- enabled some tests for now fixed issue - 15041, tests that are still failing due to other issues have been properly re-assigned
> Minor query cleanup

- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
Problem was that we were not performing pushdown for subqueries with more than 1 table (e.g. joins). Fix is to add the necessary condition to logic that determines whether pushdown needs to be applied
> [TINY] Fix to #15834 - Query: translation error for queries with nested joins

- src/EFCore.Cosmos/Query/ExpressionVisitors/Internal/CosmosMemberAccessBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Pipeline/Translator.cs
- src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Extensions/Internal/EFPropertyExtensions.cs
- src/EFCore/Query/Expressions/Internal/NullConditionalExpression.cs
- src/EFCore/Query/Internal/ExpressionPrinter.cs
- src/EFCore/Query/NavigationExpansion/Visitors/IncludeApplyingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationPropertyBindingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/PendingIncludeFindingVisitor.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
Replace `IsEFProperty()` calls with new `TryGetEFPropertyArgument()`, which extracts the source and property name. Simplifies code repeated everywhere and is friendlier to nullability static analysis etc.
> Better access to EF.Property and indexer properties

- src/EFCore.InMemory/Query/Pipeline/InMemoryShapedQueryExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SqlConstantExpression.cs
Due to internal state, it causes corruption of generated Sql command
The fix is to pass factory and generate SqlGen when we are enumerating.
Also fixed logging when connection opening failed in query
> Query: Fix potential re-use of QuerySqlGen from multiple threads

- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
> Query: Client eval ListInit in sqltranslator

- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
> Query: Apply unique projection names in the subquery

- src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerDateDiffFunctionsTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- Added TimeSpan overloads to DateDiffHour, DateDiffMinute, DateDiffSecond, DateDiffMillisecond, DateDiffMicrosecond, DateDiffNanosecond
- Added unit tests to check overloads
Fixes #14685
> Add TimeSpan overloads to SqlServer DateDiff function

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Query/Pipeline/AsyncQueryingEnumerable.cs
- src/EFCore.Relational/Query/Pipeline/FromSqlNonComposedAsyncQueryingEnumerable.cs
- src/EFCore.Relational/Query/Pipeline/FromSqlNonComposedQueryingEnumerable.cs
- src/EFCore.Relational/Query/Pipeline/FromSqlParameterApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/ISqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/InExpressionValuesExpandingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/ParameterValueBasedSelectExpressionOptimizer.cs
- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Storage/RelationalCommand.cs
- src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncFromSqlSprocQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlSprocQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
Adds optimizer to optimize SelectExpression before printing based on ParameterValues
TODO: Add a factory through service to avoid multiple services here. This also serves point for us to determine second level caching
Lift FromSqlExpression when not composed over to avoid subquery which is necessary for stored procedures
Add additional enumerables which add remapping map to materialize non composed SelectExpression which can have out of order projections
Resolves#15750
> Query: Enable parameter & sproc support for FromSql

- src/EFCore.Relational/Extensions/RelationalIndexBuilderExtensions.cs
The issue here was that the SQL Server convention was not correctly setting the index filter. This resulted in differences between the actual and expected initial migrations.
Will add tests later, but wanted to get this into the build ASAP.
> Fix ASP.NET templates test break

- src/EFCore/Storage/ValueConversion/Internal/StringUriConverter.cs
- src/EFCore/Storage/ValueConversion/StringToUriConverter.cs
- src/EFCore/Storage/ValueConversion/UriToStringConverter.cs
- src/EFCore/Storage/ValueConversion/ValueConverterSelector.cs
- test/EFCore.Tests/Storage/StringToUriConverterTest.cs
- test/EFCore.Tests/Storage/ValueConverterSelectorTest.cs
- Added StringUriConverter and unit tests
- Added Uri selection to ValueConverterSelector
Fixes #15816
> Value converter for Uri

- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
This changes SqlTranslatingExpressionVisitor to return null rather than throwing InvalidCastExpression when something failed to translate to Sql
Part of #15866
> Query: Allow client projection to cause materialization

- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
In future we need to detect cases when it is used inside subquery to not throw but currently all such tests are disabled because it was doing client eval in previous pipeline
Part of #15559
Resolves #15866
> Query: Enable throwing behavior for Single/SingleOrDefault on top level

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpansionHelpers.cs
- src/EFCore/Query/NavigationExpansion/NavigationTreeNode.cs
- src/EFCore/Query/NavigationExpansion/Visitors/CollectionNavigationRewritingVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Navigation expansion should not try expand owned navigations. We still add them to navigation tree for tracking purposes but we don't inject LeftJoin calls when processing them.
Collection navigations are converted directly to NavigationExpansionExpressions whose root is the navigation itself to avoid rewrite to a subquery.
> Correcting navigation expansion handling of owned navigations

- src/EFCore/Query/NavigationExpansion/NavigationExpansionExpression.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpansionReducingVisitor.cs
- test/EFCore.Specification.Tests/FindTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Problem was that we were only storing generic method definition for cardinality reducing operators (First/Single) because nav rewrite changes source types a lot.
However, those operators are applied after pending selector, so they are guaranteed to be of the same type as originally. We only need to track the changes that happen e.g. during member pushdown, e.g.:
customers.FirstOrDefault<Customer>().Id is changed to customers.Select(c => c.Id).FirstOrDefault<int>()
> Fix to #15535 - Query: Navigation rewrite does not preserve the type of result

- src/EFCore.Relational/Query/Pipeline/ISqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionFactory.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore/Query/Pipeline/ParameterExtractingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/BuiltInDataTypesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/ConvertToProviderTypesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/ConvertToProviderTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
Enable BuiltInDataTypeTests
- Preserve convert nodes around parameters/constants in parameter extracting.
- While translating to Sql, remove implicit convert nodes. Implicit convert nodes appear only for binary expressions since equality operators are not defined for all types
- Apply explicit cast in SQL only when converted type is mapped.
- Convert int value to enum value before printing literal (how old pipeline did it)
Resolves #14159
Resolves #15330
Resolves #15948
Supersedes type inference changes in #15820
> Query: Remove implicit convert nodes in query to avoid unnecessary cast in generated SQL

- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
Resolves #15807
Resolves #15848 (Since client eval for projection is already added)
> Query: Allow property access on derived type by using type casting

- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/OrderingExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that when translating Skip/Take we were not performing pushdown when the select expression already had orderings defined
> [TINY] Fix to #15863 - Query: incorrect results due to invalid subquery pushdown logic

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
- src/EFCore/Extensions/MutableEntityTypeExtensions.cs
- src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
- src/EFCore/Metadata/IConventionEntityType.cs
- src/EFCore/Metadata/IMutableEntityType.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeBaseTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/PropertyAccessorsFactoryTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilder.Other.cs
- tools/Resources.tt
React to API review feedback
Add a way to obsolete event definitions
Part of #15662
> Consolidate AddProperty methods

- src/EFCore.Relational/Infrastructure/RelationalModelCustomizer.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalDbFunctionAttributeConvention.cs
- src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerDbFunctionAttributeConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs
- src/EFCore/Infrastructure/ModelCustomizer.cs
- src/EFCore/Metadata/Conventions/DbSetFindingConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- test/EFCore.Cosmos.Tests/TestUtilities/CosmosTestHelpers.cs
- test/EFCore.InMemory.FunctionalTests/TestUtilities/InMemoryTestHelpers.cs
- test/EFCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs
- test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
- test/EFCore.Relational.Tests/TestUtilities/RelationalTestHelpers.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDbFunctionMetadataTests.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestHelpers.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestHelpers.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs
- test/EFCore.Tests/ModelSourceTest.cs
> Move logic from ModelCustomizer to conventions.

- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
> Fix Debug build break

- src/EFCore.Relational/Storage/IRelationalDatabaseCreator.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalDatabaseCreator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
> Add IRelationalDatabaseCreator.HasTables and make the implementation public

- src/EFCore.Relational/Migrations/HistoryRepository.cs
- test/EFCore.Relational.Specification.Tests/MigrationsFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
I think this is one of the root causes of the ASP.NET failures in https://github.com/aspnet/AspNetCore/pull/10939#issuecomment-500473365
The issue is that now that we discover DbSets from a context as a convention, re-using the convention-laden ModelBuilder for creating the history table also brings in types from the context.
For now, the fix is to remove this convention, but we may want to consider other options for building the history table.
> Don't pull entity types from the context when building the Migrations history table

- test/EFCore.Specification.Tests/TestUtilities/TestStore.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
- test/EFCore.Tests/Storage/ExecutionStrategyTest.cs
This should prevent any distributed transactions.
> Synchronize transactions across test threads.

- src/EFCore.Relational/Query/Pipeline/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SelectExpressionTableAliasUniquifyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/ShaperExpressionDedupingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/ColumnExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/JoinExpressionBase.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/TableExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/TableExpressionBase.cs
- src/EFCore/Query/Pipeline/ProjectionMember.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
Added AddToProjection method which de-dupe columns and assign unique alias if subquery
Also added ability to assign alias based on member name in anonymous type projection
TableExpressionBase.Alias is either null or non-empty string to make processing it easier
> Query: Dry code for generating column alias

- eng/Versions.props
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/CosmosEndToEndTest.cs
- test/EFCore.Cosmos.FunctionalTests/NestedDocumentsTest.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
> Update Cosmos SDK

- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
When IsConfigured is called, it applies all services. This caused a DiagnosticListener to get instantiated on each DbContext instantiation, and since it wasn't disposed it caused a leak.
Fixes #15173
> Fix DiagnosticListener memory leak

- src/EFCore.Cosmos/Extensions/CosmosDatabaseFacadeExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategyFactory.cs
- src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
- src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.Cosmos.Tests/ValueGenerator/Internal/IdValueGeneratorTest.cs
> Make CosmosClient singleton and add a public way to access it.

- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> Microsoft.Data.Sqlite: Handle non-queries in SqliteDataReader

- src/EFCore.Relational/Query/Pipeline/SelectExpressionTableAliasUniquifyingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
We did not visit inner when we updated alias for select expression
> Query: Apply table aliasing recursively

- src/EFCore.Cosmos/Extensions/CosmosDatabaseFacadeExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosDbContextOptionsExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategyFactory.cs
- src/EFCore.InMemory/Extensions/InMemoryDatabaseFacadeExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
> Add IsCosmos extension method.

- src/EFCore/Query/Pipeline/QueryOptimizingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/ConcurrencyDetectorInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/CompiledQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ConcurrencyDetectorSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/ConcurrencyDetectorSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Fix bug in EnumerableVerifyingExpressionVisitor to allow ToArray
> Query: Attempt to enable few tests

- eng/Version.Details.xml
- eng/Versions.props
- test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs
- align Microsoft.NETCore.App.Ref version with other core-setup dependencies
> Add missing `CoherentParentDependency` attribute

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/MigrationBuilder.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.Relational/Migrations/Operations/AlterTableOperation.cs
- src/EFCore.Relational/Migrations/Operations/ColumnOperation.cs
- src/EFCore.Relational/Migrations/Operations/CreateTableOperation.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- Added HasComment extensions to table and column
- Added SQL server support for comments in extended properties
Fixes #15037
> Allow table/column comments to be specified in the model

- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs
- src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
- src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
- src/EFCore.SqlServer.NTS/Infrastructure/Internal/SqlServerNetTopologySuiteOptionsExtension.cs
- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerOptionsExtension.cs
- src/EFCore.Sqlite.Core/Infrastructure/Internal/SqliteOptionsExtension.cs
- src/EFCore.Sqlite.NTS/Infrastructure/Internal/SqliteNetTopologySuiteOptionsExtension.cs
- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Infrastructure/DbContextOptionsExtensionInfo.cs
- src/EFCore/Infrastructure/IDbContextOptionsExtension.cs
- src/EFCore/Infrastructure/Internal/DbContextOptionsExtensions.cs
- src/EFCore/Internal/ServiceProviderCache.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalOptionsExtension.cs
- test/EFCore.Tests/DbContextOptionsTest.cs
- test/EFCore.Tests/ServiceProviderCacheTest.cs
Also stop calling ApplyServices to find out if an extension is a database provider.
Fixes #16119 
Fixes #16045
Doing this refactoring because we keep having to add/change methods here, so putting them in a composed abstract base class to avoid breaking the interface each time.
> Break out metadata/info about an extension from the interface

- test/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTestClientCascade.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTestClientNoAction.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTestIdentity.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTestSequence.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdatesSqliteTest.cs
Because they have a lot of coverage for things outside of query.
The queries should be reverted back to full `Include` queries once they work--still annotated with the same issue number: #15318
> Re-enable most relational graph update tests

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Pipeline/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/Customer.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/OrderDetail.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Closes #15939
For Contains, I realized half-way through that the test (Contains_over_entityType_should_rewrite_to_identity_equality) depends on #15855, since the second query sends the ID selected in the first query. Am still submitting the implementation - the expression tree generated internally looks good. I can also hold off until #15855 is done.
Also, I tested the case `Orders.Contains(null)` and was surprised to see the null is parameterized. Is this intended?
Finally, unrelated to EE: I understand the need to split into two queries for Single, since the 1-element verification needs to happen client-side. However, for First, FOD, Last, LOD we can translate as a single query:
```sql
SELECT (
SELECT TOP(1) [o].[OrderID]
FROM [Orders] AS [o]
WHERE [o].[OrderID] = 10248)
IN (
SELECT …
```
> Entity equality: Contains and OrderBy

- src/EFCore.Relational/Query/Pipeline/InExpressionValuesExpandingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionOptimizingVisitor.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerStringMethodTranslator.cs
- src/EFCore/Query/Pipeline/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- removing redundant term in Contains translation with constant argument,
- fixing logic around IN sql gen,
- clean up logic around de morgan optimization,
- adding new optimization op(a, b) == true -> op(a, b),
- removing a number of tests that are no longer relevant due to query pipeline changes.
> Fixing some small bugs in sql generation

- src/EFCore.Cosmos/Extensions/CosmosEntityTypeBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosModelBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/CosmosModelCustomizer.cs
- src/EFCore.Cosmos/Infrastructure/CosmosModelValidator.cs
- src/EFCore.Cosmos/Metadata/Internal/CosmosAnnotationNames.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore/Metadata/Internal/Model.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
- test/EFCore.Cosmos.Tests/Metadata/CosmosBuilderExtensionsTest.cs
- test/EFCore.Cosmos.Tests/Metadata/CosmosMetadataExtensionsTest.cs
Fix Northwind tests
Part of #12086
> Cosmos: Add API to configure partition keys and use them in the update pipeline.

- benchmark/Shared.EFCore/Query/RawSqlQueryTests.cs
- benchmark/Shared.EFCore/Query/SimpleQueryTests.cs
Our current query pipeline makes some benchmarks fail. Unfortunately the ASP.NET perf lab currently ignores the entire benchmark suite if any benchmark fails, so disabled those benchmarks for now. This should allow us to start tracking some basic query scenarios.
Also modified benchmarks to access int rather decimal (the latter is limited on Sqlite).
We may want to add some more benchmarks - will look into this at some point (but if someone has ideas...).
FYI to manually run benchmarks on the console, just go into benchmark/EFCore.Sqlite.Benchmarks and do `dotnet run -c Release -f netcoreapp3.0 -- --inProcess`. You can add `--filter` to invoke a specific suite or method.
> Repair and disable failing benchmarks

- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
> Query: Remove translation of property on derived type after casting

- src/EFCore/Query/Pipeline/ReplacingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- enabling some tests for issues that were fixed previously,
- adding regression tests for some other issues that were also fixed previously,
- fix small bug where ReplacingExpressionVisitor would not properly simplify EF.Property expressions.
> More test cleanup

- src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetPlugin.cs
- src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
- src/EFCore.Proxies/ProxiesServiceCollectionExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Metadata/Conventions/Infrastructure/IConventionSetPlugin.cs
- src/EFCore/Metadata/Conventions/Infrastructure/IProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/RuntimeConventionSetBuilder.cs
- test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs
- test/EFCore.Tests/ModelSourceTest.cs
> Rename IConventionSetCustomizer to IConventionSetPlugin

- src/EFCore.Cosmos/Query/Pipeline/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Pipeline/CosmosShapedQueryCompilingExpressionVisitorFactory.cs
- src/EFCore.Cosmos/Query/Pipeline/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Pipeline/SelectExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryMaterializerFactory.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryShapedQueryExpressionVisitor.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/ChangeTracking/Internal/ArrayPropertyValues.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerDependencies.cs
- src/EFCore/Metadata/IEntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/PropertyParameterBinding.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosSqlTest.Where.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Tests/DbContextServicesTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityMaterializerSourceTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Part of #16133
Part of #16144
Resolves #16152
Part of #15662
> Teeny tiny bugs

- src/EFCore.SqlServer/Query/Pipeline/SearchConditionConvertingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Query: Convert SubSelectExpression to search condition as necessary

- src/EFCore.Relational/Query/Pipeline/IncludeCompilingExpressionVisitor.cs
- src/EFCore/Query/NavigationExpansion/IncludeExpression.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Improved the logic that converts string based include to lambdas:
- if navigation is not found on type itself, all of its derived types are tested,
- if multiple navigations with same name are found, each navigation becomes it's own path,
- at least one valid navigation needs to be found for each element of the "chain" specified in the Include method.
Also fixed a minor bug later in the include pipeline that was exposed by the fix.
> Fix to #15381 - QueryRewrite: string based include should include all navigations with the same name for scenarios with inheritance

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/ColumnExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Sqlite.Core/Query/Pipeline/SqliteQuerySqlGenerator.cs
- src/EFCore/Extensions/EntityTypeExtensions.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Query/Pipeline/ShapedQueryExpression.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
This is a first draft for set operation support (UNION/UNION ALL/INTERSECT/EXCEPT). @smitpatel I'm looking for feedback on the general direction before I go any further etc.
Some important notes on database-specific quirks/capabilities (which have informed the design) have been posted in https://github.com/aspnet/EntityFrameworkCore/issues/6812#issuecomment-502827316.
Set operations are currently represented as a special kind of SelectExpression, with an enum marker has been added (SetOperationType). Each such SelectExpression represents a single set operation with exactly two operands.
RelationalQueryableMethodTranslatingExpressionVisitor performs pushdown of set operations into a subquery on most LINQ operations, in one place. As part of this, I have refactored translation of queryable …
> Set operation support (except navigation/include)

- src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationsAnnotationProvider.cs
- test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
Initial fix for #16239
Required to unblock https://github.com/aspnet/AspNetCore/pull/11531#issuecomment-505289690
> Fix issue with SQLite migration snapshot needing a type mapping

- eng/Versions.props
- samples/EncryptionSample/EncryptionSample.csproj
- src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs
- src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- src/Microsoft.Data.Sqlite.Core/SqliteException.cs
- src/Microsoft.Data.Sqlite.Core/SqliteParameterReader.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Filed #16187 and #16202 to take more advantage of the new Span overloads.
Resolves #14824
> Update SQLitePCL.raw to 2.0.0

- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
In case a column value is NULL, SqliteDataReader.GetFieldType() now tries to return the field type based on the column affinity. 
SQLite does not provide the affinity via its API, therefore the corresponding C function sqlite3AffinityType was ported to C#. The affinity NUMERIC has no corresponding data type, so here the data type TEXT is returned (as suggested as default in #13831). 
A special case is a column where no type is specified, here the explicit rule was used, that such a column is of affinity BLOB (see [Determination Of Column Affinity](https://www.sqlite.org/datatype3.html#determination_of_column_affinity)).
The corresponding changes were also introduced for the SqliteDataReader.GetSchemaTable() DataType column.
Fixes #13831 and fixes #13839
> Microsoft.Data.Sqlite: Improve SqliteDataReader.GetFieldType() when NULL

- src/EFCore.Relational/Query/Pipeline/AsyncQueryingEnumerable.cs
- src/EFCore.Relational/Query/Pipeline/IncludeCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/QueryingEnumerable.cs
- src/EFCore.Relational/Query/Pipeline/RelationalCollectionShaperExpression.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/ShaperExpressionDedupingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Pipeline/ShapedQueryExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeAsyncTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeAsyncSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
> Query: Implement collection materialization in async

- src/EFCore.Cosmos/Query/Pipeline/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/Pipeline/QueryableMethodTranslatingExpressionVisitor.cs
Except for the subquery case
This visitor should only translate methods on Queryable so it should not do base eval for others.
All other methods should be passed through SqlTranslator (as they appear inside a lambda)
For subquery, we don't want to throw since we don't know if the subquery has client methods or not (projection case)
This is required for supporting collections/single non-scalar in projection.
> Query: Throw for unknown method encountered in QueryableMethodTranslator

- src/EFCore/Query/NavigationExpansion/Visitors/IncludeApplyingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/PendingIncludeFindingVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that when we search and apply include on the final projection we short circuit when we encounter member access. However, we should only do that if the member access is on top of navigation binding - in other cases, like client-side functions, we should peek inside and potentially apply includes on entities that are defined there.
> Fix to #16231 - Query: Include on client projection gets ignored

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Repro'd bug in 2.2.5 and confirmed it is gone in latest bits, added QueryBugTest.
Fixes #15684
@smitpatel @ajcvickers for these cases where there's only a new test, do you still want to sign off on PRs? It would give you visibility on work but otherwise may not be very useful.
> Verified bug #15684 is fixed

- src/EFCore.Relational/Query/Pipeline/NullSemanticsRewritingVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
problem was that when we were computing a nullability of sql function, if the function didn't have instance, we would inherit nullability from the expression that was visited previously.
Fix is to only use nullability of instance expression if that expression is not null.
> [TINY] Fix to #16245 - Null semantics applies incorrectly for SqlFunction

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Enable test for issue#16231

- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
Using interceptor?. pattern sent null back for Task which was being awaited.
Pattern, for async always make null check on interceptor before calling into.
For Sync methods if they are returning void or possible null then only use interceptor?.
Testing: Errors only happen when diagnosticSource enabled so that intercepter is null but we still go inside the block.
Not sure how to set it up that in tests. Submitting PR to unblock ASP.NET Core
> Intercepters: Don't return null for Async methods

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
DateTimeOffset and Contains()
Fixes #15208
> Add test verifying #15208

- src/EFCore/Query/Pipeline/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
This was quite silly...
Fixes #16335
> Fix conditional expression handling entity equality visitor

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- src/EFCore/Infrastructure/Uniquifier.cs
- src/EFCore/Metadata/IConstructorBindingFactory.cs
- src/EFCore/Metadata/IPropertyParameterBindingFactory.cs
- src/EFCore/Metadata/Internal/ConstructorBindingFactory.cs
- src/EFCore/Metadata/Internal/PropertyParameterBindingFactory.cs
> API review changes

- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
New variations of FromSqlRaw and FromSqlInterpolated specification tests take DbParameter without using a prefix in the name. E.g. "city" instead of "@city" and verify that the prefix is added automatically when the parameter name is added in-line in the SQL.
Also added SQL Server ~~and SQLite~~ overrides that assert the SQL.
Closes #14173
> Add tests for FromSql with DbParameter without name prefix

- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpansionReducingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/PendingIncludeFindingVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
This was split off from #16249 and now only contains include/nav features.
Continues #6812
Fixes #13196
Fixes #16065
Fixes #16165
> Set operations: include/nav support

- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Update/IUpdateAdapterFactory.cs
- src/EFCore/Update/Internal/UpdateAdapter.cs
- src/EFCore/Update/Internal/UpdateAdapterFactory.cs
- test/EFCore.InMemory.FunctionalTests/SeedingInMemoryTest.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.Specification.Tests/SeedingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SeedingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/SeedingSqliteTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> Use clean StateManager for seeding

- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
- src/EFCore/Metadata/Conventions/NonNullableReferencePropertyConvention.cs
See https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-metadata.md.
Makes #16370 pass.
> Update nullability convention to new nullability metadata

- src/EFCore.Relational/Query/Pipeline/InExpressionValuesExpandingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
Our InExpressionValuesExpanding visitor can turn an an IN expression to a constant (i.e. when the values list is empty), which is unsupported in orderings in SqlServer. Detect this and turn these expressions to a simple constant expression detectable by the SQL generator, which will generate (SELECT 1).
Fixes #15713
Some notes:
* These changes actually seem to be SqlServer-specific. Sqlite doesn't mind ordering by constants, and PostgreSQL is OK to order by bools (in fact, Npgsql can remove InExpressionValuesExpandingExpressionVisitor entirely and send an array parameter instead of expanding the array to a constant). However, the current architecture doesn't allow for this: RelationalShapedQueryCompilingExpressionVisitor isn't really extensible (lots of private etc.).
* Note #16375 about …
> Handle IN optimizer transformation of ordering to constant

- Directory.Build.targets
- eng/Version.Details.xml
- eng/Versions.props
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
- src/EFCore/Metadata/Conventions/NonNullableReferencePropertyConvention.cs
- bit surprised this isn't pulling in '3.2.0-beta4-19326-12' but that may come once dotnet/roslyn branches
- see also #16370 and #16385 discussions
If we decide to take this (with QB approval), I'll also add a subscription to auto-update the toolset.
> Explicitly reference Roslyn compiler version that's currently in the '.NET Core 3 Release' channel

- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Pipeline/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Pipeline/GroupByShaperExpression.cs
- src/EFCore/Query/Pipeline/ReplacingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/GroupByQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
This allows us to use those methods to translate aggregates after GroupBy
Resolves #15718
Query: Translate to SQL GROUP BY when aggregate operator is applied after GroupBy
Resolves #12826
Resolves #6658
Part of #15711
Resolves #15853
Resolves #12799
Resolves #12476
Resolves #11976
> Query: Add support for SQL GROUP BY

- benchmark/EFCore.SqlServer.Benchmarks/EFCore.SqlServer.Benchmarks.csproj
- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- benchmark/Shared.EFCore/Query/RawSqlQueryTests.cs
> Fix benchmarks for older EF Core versions

- src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbTransactionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.Relational/Storage/RelationalTransaction.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
> Use new ADO.NET async APIs

- src/EFCore.Cosmos/Query/Pipeline/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Pipeline/EntityProjectionExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/SelectExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Sqlite.Core/Query/Pipeline/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Support for Owned entities
Part of #15285
Also added SQL Assertion on Sqlite for LongCount
> Query: Move Property/Navigation binding to EntityProjection directly

- azure-pipelines.yml
- src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
- test/EFCore.Cosmos.FunctionalTests/NestedDocumentsTest.cs
- test/EFCore.Cosmos.FunctionalTests/Properties/TestAssemblyCondition.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.Cosmos.FunctionalTests/config.json
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.Specification.Tests/SharedStoreFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
- test/EFCore.Specification.Tests/TestUtilities/TestStore.cs
- test/EFCore.Specification.Tests/TestUtilities/Xunit/ConditionalFactTestCase.cs
- test/EFCore.Specification.Tests/TestUtilities/Xunit/ConditionalTheoryTestCase.cs
- test/EFCore.Specification.Tests/TestUtilities/Xunit/ITestCondition.cs
- test/EFCore.Specification.Tests/TestUtilities/Xunit/PlatformSkipConditionAttribute.cs
- test/EFCore.Specification.Tests/TestUtilities/Xunit/XunitTestCaseExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerCondition.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConfiguredConditionAttribute.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.SqlServer.Tests/Storage/Internal/SqlServerGeometryTypeMappingTests.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SpatialiteRequiredAttribute.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteVersionConditionAttribute.cs
Fix some deadlocks in Cosmos Test cleanup by converting sync invocations to async
> Run Cosmos tests for PRs

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
Fixes #15645
Fixes #13110 (was already working in 3.0, but added a test)
Fixes #15500 (was already working in 3.0, but added a test)
See also #16454
> Remove references to an entity when it is detached

- azure-pipelines.yml
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
Use a dummy token to skip the tests, as they fail if no token is set
> Use unique database names for Cosmos tests

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
- src/EFCore/Metadata/Internal/ModelExtensions.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
Fixes #16239
Fixes #12212
Also, make the SnapshotModelProcessor finalize the model.
I investigated whether it would be better to only store this sometimes, but that then still requires making some assumptions (basically using some conventions and/or the type mapper doing what it does in conventions) when loading the snapshot to ensure we find the right type for the provider being used. Storing it always is clean and simple, decouples from conventions when loading, and means we don't have to do special magic for facets that come from value converters.
> Store database type name in model snapshot

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs
- test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
> Allow store type name shape to be customized

- src/EFCore/Metadata/Conventions/ConstructorBindingConvention.cs
- test/EFCore.Tests/Metadata/Conventions/ConstructorBindingConventionTest.cs
> Don't set constructor binding by convention if already set

- src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Fixes (or verifies as fixed) several fix-up/owned types issues:
* Fixes #16161
* Fixes #15760
* Fixes #15600
* Fixes #15484
* Fixes #14675
> Better handling of different collection types in fix-up

- eng/Versions.props
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
Fixes #14595
~~@divega Looks like dotnet/corefx#36678 isn't in Microsoft.Data.SqlClient. Tests pass after reverting 10e553acc21f495e1bbdb384b90ac0a6e334f5ff~~ (resolved)
> SqlServer Spatial: Enable calling methods on parameterized values

- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Query/Pipeline/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Pipeline/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/Pipeline/QueryCompilationContext.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Entity equality introduces member access expressions on what may be a
parameter or a constant. Identify these cases and transform them into
a new parameter (for access of a parameter) or evaluate the constant.
Fixes #15855
Notes (additional comments inline):
* For now the logic is implemented in RelationalSqlTranslatingEV. In theory it should be moved to an earlier, independent visitor in the optimization phase, this way this can be used for non-relational. However, that would require distinguishing between ParameterExpressions that correspond to closures (which we're looking for) and all other lambda ParameterExpressions (which we don't care about). In other words, ParameterExtractingEV made our job difficult by replacing constant expressions with `TypeAttributes.NestedPrivate` to …
> Support member access on parameter and constant introduced in entity equality

- src/EFCore.Relational/Query/Pipeline/SqlExpressionFactory.cs
Providers can be expected to extend SqlExpressionFactory in order to facilitate creating custom SQL expressions. The ApplyTypeMapping in particular should be virtual to allow it to be overridden for those expressions. Other methods don't seem to require extensibility, but we can discuss.
Also did some C# 8 goodness.
> Make SqlExpressionFactory.ApplyTypeMapping virtual

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/DbContextTrackingTest.cs
Fixes #15819
We had previously decided in #1246 on a behavior for resolving this, but that behavior results in not tracking the graph passed to us. On reflection, that decision was likely wrong, so reverting it here to avoid discarding entities in the graph.
> Stop shredding graph when FK value and navigation property don't agree

- src/EFCore/Query/Pipeline/NullCheckRemovingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Make null check removal recursive

- test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
- test/EFCore.Specification.Tests/MusicStoreTestBase.cs
- test/EFCore.Specification.Tests/TestModels/AspNetIdentity/IdentityDbContext.cs
- test/EFCore.Specification.Tests/TestModels/AspNetIdentity/IdentityDbContext```.cs
- test/EFCore.Specification.Tests/TestModels/AspNetIdentity/IdentityUserContext.cs
- test/EFCore.Specification.Tests/TestModels/MusicStore/Album.cs
- test/EFCore.Specification.Tests/TestModels/MusicStore/Artist.cs
- test/EFCore.Specification.Tests/TestModels/MusicStore/Genre.cs
- test/EFCore.Specification.Tests/TestModels/MusicStore/Order.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
Covering all the queries MusicStore does, and also updating the tests to properly use store-generated values.
Also, added the ModelSnapshots generated by the project templates for 2.1, 2.2, and 3.0, for SQL Server and SQLite. They all diff correctly against the current code showing no differences in the generated schema.
Part of #15662 and #11838
Note that currently the ASP.NET 3.0 templates still contain migrations generated by 2.2. See https://github.com/aspnet/AspNetCore/issues/12168
> Add more MusicStore and Identity tests

- src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Query/Pipeline/SqlServerIsDateFunctionTranslator.cs
- src/EFCore.SqlServer/Query/Pipeline/SqlServerMethodCallTranslatorProvider.cs
- test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs
Implementation for #8488
As this function returns 0/1.
So I thought it would be better to make it Boolean.
https://docs.microsoft.com/en-us/sql/t-sql/functions/isdate-transact-sql?view=sql-server-2017
cc/ @divega @smitpatel
> EF.Functions: Translating ISDATE to SQL Server

- src/EFCore.Cosmos/Query/Pipeline/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
Resolves #16597
If we visit lambda then the parameter would be translated to server equivalent which cannot be used anymore to reconstruct the lambda expression so it threw weird exception.
LambdaExpression cannot be server represented hence return null
> Query: Translation of LambdaExpression is null

- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Verified that this is already fixed in 3.0. (Also verified that it did throw in 2.2, so this is a 3.0 fix.)
Issue #13573
> Add test for ambiguous self-reference case

- src/EFCore.Relational/Query/Pipeline/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/NavigationExpansion/NavigationTreeNode.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/LazyLoadProxyInMemoryTest.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
> Query: Add support for owned reference navigation

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- test/EFCore.Relational.Tests/TestUtilities/TestRelationalMigrationSqlGenerator.cs
> Consolidate terminate overloads in MigrationsSqlGenerator

- src/EFCore.Relational/Query/Pipeline/SqlExpressions/InExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SqlConstantExpression.cs
InExpression can hold an SqlConstantExpression with an array value, but with its elements' type mapping (i.e. string[] value but SqlServerStringMapping type mapping, which don't correspond). As a result SqlConstantExpression contained special logic for printing its values when the value is Enumerable, but this logic breaks for PostgreSQL where array constants are an actual thing.
Move array printing logic from SqlConstantExpression to InExpression to unblock native PostgreSQL arrays.
> Fix ExpressionPrinter logic for InExpression arrays

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
In new query pipeline, we preserve convert nodes around enum in expression tree and remove them on both sides when translating to server.
The typeMapping for enum column expects an enum value for constant or parameter
- With new pipeline, we will have parameter's value to be enum so we no long need any additional code for conversion
- For constants, there is no convert node around constant in actual tree so we are left with integral value to be printed with Enum type mapping. Hence we need to convert it to actual enum value first. Afterwards, provider can print enum literal or apply appropriate conversions
> Convert integral value to enum value when printing Sql literal

- src/EFCore.Relational/Diagnostics/CommandCorrelatedEventData.cs
- src/EFCore.Relational/Diagnostics/CommandErrorEventData.cs
- src/EFCore.Relational/Diagnostics/CommandEventData.cs
- src/EFCore.Relational/Diagnostics/CommandExecutedEventData.cs
- src/EFCore.Relational/Diagnostics/DbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/Internal/DbCommandInterceptorAggregator.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/RelationalCommand.cs
- test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
- test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
> API review: add interception for DbCommand creation

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Take 2 of 38c79bff4a64218da73c4d2e0e8b3a7eda0773b8
Fixes #16653
> Ignore convert nodes from nullable to non-nullable

- src/EFCore/Query/ExpressionPrinter.cs
> Expose basic IndentedStringBuilder API on ExpressionPrinter

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
In our current comment support (#15037), when creating a table only the table's comment is applied, and not the table's columns' comments.
> Apply column comments when creating tables

- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
- src/EFCore/Metadata/Conventions/NonNullableReferencePropertyConvention.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs
Fixes #16760
And that's the kind of stuff you produce when doing last-minute late-night hacking...
> Fix silly bugs in non-nullable reference handling

- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
Fixes #13546
Still fails on Cosmos, but due to failed left-join translation.
> Test to verify owned references in project load automatically

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
> Move RelationalStrings.NoElements exception message to core

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/IncludeCompilingExpressionVisitor.cs
- src/EFCore/ChangeTracking/CollectionEntry.cs
- src/EFCore/ChangeTracking/CollectionEntry`.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs
- src/EFCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalShadowEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Internal/ClrAccessorFactory.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/ClrPropertyMaterializationSetterFactory.cs
- src/EFCore/Metadata/Internal/ClrPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/IClrCollectionAccessor.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
- src/EFCore/Query/NavigationExpansion/Internal/IncludeHelpers.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Specification.Tests/FieldMappingTestBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedFixupTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/FieldMappingSqliteTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
Fixes #16287
Ended up being quite a can of worms--cleaned up some CLR accessor code that is no longer being used (it was there for old pipeline) and found several additional bugs in the same area.
> Use field/properties appropriately from query

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Seems like changing comments on a column doesn't actually work currently - the model differ doesn't check for it when deciding whether to generate an AlterColumnOperation.
> Make model differ recognize column comment change

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
* Removed comment-related migration generation APIs from relational, implementation is now only in SqlServerMigrationsSqlGenerator.
* Made extended property support more general so we can use them for other purposes if needed.
Fixes #16799
Fixes #16800
Note that I've included the comment statements (EXEC sp_addextendedproperty) in the same command as the DDL itself. Am not familiar enough with SqlServer to know if that's meaningful.
> Refactor comment support

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
> [preview8] Handle projected collections.

- src/EFCore.Sqlite.Core/Extensions/SqlitePropertyBuilderExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqlitePropertyExtensions.cs
- src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationsAnnotationProvider.cs
- src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuitePropertyBuilderExtensions.cs
- test/EFCore.Sqlite.Tests/Metadata/Builders/SqliteBuilderExtensionsTest.cs
- test/EFCore.Sqlite.Tests/Metadata/SqliteMetadataExtensionsTest.cs
Per https://github.com/aspnet/EntityFrameworkCore/pull/16824#pullrequestreview-268057495
> Tweak SpatialDimension -> GeometricDimension

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Query/Internal/QuerySqlGeneratorFactory.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/QuerySqlGeneratorDependencies.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGeneratorFactory.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerShapedQueryOptimizingExpressionVisitorsFactory.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGeneratorFactory.cs
- test/EFCore.Relational.Tests/Query/QuerySqlGeneratorDependenciesTest.cs
> SqlExpressionVisitorDependency -> QuerySqlGeneratorDependencies

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
> Some code cleanup in RelationalSqlTranslatingExpressionVisitor

- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/ExpressionEqualityComparer.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Also various modifications to support MemberMemberBinding better (RelationalProjectionBindingExpressionVisitor, ReplacingExpressionVisitor, ExpressionEqualityComparer)
Fixes #16789
There's probably some specific support for MemberMemberBinding missing from RelationalProjectionBindingExpressionVisitor but I think we can take care of that later.
Note that we still don't support MemberListBinding.
> Entity equality support for non-anonymous DTOs

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
- test/EFCore.Design.Tests/Scaffolding/Internal/ScaffoldingTypeMapperSqliteTest.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
Fixes #16111
The issue was that when finding a type mapping based on type name affinity we were not checking that it was compatible with the CLR type. This resulted in short-circuiting of the conversion selection and hence the wrong mapping.
> Fix SQLite affinity type mapping to correctly find conversions

- src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Navigation.cs
- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilder.Other.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Remove ambiguous navigations when the target type is ignored or a base type is set that has the navigation ignored.
Throw correct exception when the collection navigation type doesn't match the dependent entity type.
Fixes #16762
> Pull down relationship to the derived type when setting a navigation targeting the derived type.

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.SetOperations.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
Including different mapping types on the two sides, as long as the result is compatible.
Fixes #16725
> Allow set operations over other mapping types

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedFixupTestBase.cs
Fixes #15960
The issue here is that when the first graph of Added entities are replaces by the second graph, it causes the first graph to be detached, but this was only happening at the first level of the graph.
Other test changes are because we were relying on being able to detach a principal without it cascading, even though cascades are configured.
> Fix cascade detach to actually cascade

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Query: Add regression test for nav expansion inside interpolated string

- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
Resolves #16619
This avoids issue of adding includes when includes are not part of projection.
Fixed in new nav rewrite
> Query: Merge processing of eager loaded include with normal include

- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Resolves #16389
Fixed in new nav expansion
> Query: Re-enable tests for issue#16389

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Fixed in new nav expansion
Filed #16897 for further improvement in SQL
> Query: Enable tests for issue#16229

- azure-pipelines.yml
- test/ef.Tests/ef.Tests.csproj
> CI: Use an older version of SpatiaLite on macOS

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/QueryOptimizer.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs
Resolves #16620
Resolves #16392
Partially fix #15285
> Query: Add support for owned collections

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- src/EFCore/Query/Internal/QueryCompiler.cs
- src/EFCore/Storage/Database.cs
- src/EFCore/Storage/ValueConversion/ValueConverterSelector.cs
- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
Move the null check outside of the value convertor to avoid turning null into 0.
Take integer precision into account in the type mapping tests.
Fixes #13164
> Return the correct type mapping for enum properties.

- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/CustomerView.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
EE handled the extension version of {IQueryable,IEnumerable}.Contains,
but not instance methods such as List.Contains.
Fixes #15554, continues work from #16134.
There's a slight complication with the translation of `orders.Where(o => customers.Any(c => c.Orders.Contains(o)))` (test Where_contains_on_navigation).
As this wasn't handled by EE, nav expansion rewrote this to:
```sql
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
WHERE EXISTS (
SELECT 1
FROM [Customers] AS [c]
WHERE EXISTS (
SELECT 1
FROM [Orders] AS [o0]
WHERE (([c].[CustomerID] = [o0].[CustomerID]) AND [o0].[CustomerID] IS NOT NULL) AND ([o0].[OrderID] = [o].[OrderID])))
```
With this PR, the translation becomes:
```sql
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], …
```
> Entity equality support for non-extension Contains

- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Model.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
Fixes #15839
The issue was that both the immediate owner for `Rejection.FirstTest#FirstTest.Tester#SpecialistStaff` and `Attitude.FirstTest#FirstTest.Tester#SpecialistStaff` are the same resulting in the former being mistaken for the latter. The fix is to use the type rather than its name.
> Stop using similar-looking owned entity in deeply nested case

- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsAnnotationProviderTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Note, this introduces a **breaking change** from 3.0.0-preview7. Migrations with the following...
``` csharp
.Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
.Annotation("SqlServer:IdentitySeed", 2)
.Annotation("SqlServer:IdentityIncrement", 3)
```
...will need to be manually updated to this.
``` csharp
.Annotation("SqlServer:Identity", "2, 3")
```
Fixes #13352
> SqlServer Migrations: Consolidate IDENTITY annotations

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Owned FK whose navigation points to owned which is non-owned entity needs to be expanded out.
> Query: Expand owned FK navigation leading to non-owned entity

- src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
Fixes #16888
Note that `StructuralEqualityComparer.Equals` does not suffer from this problem.
> Handle binary keys of different lengths in update pipeline

- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
Close #15285
InMemory tracked by #16994
> Query: Wrap up support for owned/weak entities

- src/EFCore.Relational/Query/EntityProjectionExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
> Query: Update EntityProjection when filtering on derived type

- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
> Query: Disallow tracking queries for owned entites without their owners

- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
- src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
- Expose CosmosDB connection mode to the library consumer as a CosmosOptions propriety.
Fixes #16842
> Make ConnectionMode for CosmosDB editable by consumer

- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs
Remove module-level handling for [NullableContext] (as per https://github.com/dotnet/roslyn/pull/37610) and recognize [MaybeNull].
[See discussion here](https://github.com/aspnet/EntityFrameworkCore/issues/16440#issuecomment-518719554).
> More nullability work

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Query/AsyncQueryingEnumerable.cs
- src/EFCore/Internal/ConcurrencyDetector.cs
- src/EFCore/Internal/IConcurrencyDetector.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs
- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
This was causing deadlock issue in product because after concurrency exception the context is unusuable and in pooling scenario it caused forever wait in async queries
Resolves #10914
Resolves #12138
> Query: Remove serialization of async query code

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/QueryableMethodProvider.cs
- src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
Part of #16300, not exhaustive
Takes care of the big dispatching switches in QueryableMethodTranslatingEV, NavigationExpandingEV, EntityEqualityRewritingEV.
Some work should still be done to make QueryableMethodProvider itself more future-proof, and also to compare Enumerable operators by MethodInfo.
> Compare Queryable operators by MethodInfo

- .editorconfig
- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/InExpressionValuesExpandingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
And set appropriate .editorconfig option
> Unindent blocks within switch cases

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/Internal/NullCheckRemovingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Fixed in new nav expansion
Close #16088
> Query: Re-enable tests for Issue#16088

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
Fixes #16972
Continues work in #16957
> More fixes to entity equality nullability handling

- Directory.Build.targets
This addresses the missing types error in master. It turns out that the root cause was that a hack was removed when we converted to targeting netcoreapp5.0 that was still needed for netstandard2.1: https://github.com/aspnet/EntityFrameworkCore/commit/3ce0877474e3e5efcb0b1123b68ded52ec644532#r34638627.
This should fix master.
> Add targeting pack override back for NETStandard.Library

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/MigrationBuilder.cs
- src/EFCore.Relational/Migrations/Operations/AlterTableOperation.cs
- src/EFCore.Relational/Migrations/Operations/Builders/ColumnsBuilder.cs
- src/EFCore.Relational/Migrations/Operations/CreateTableOperation.cs
- src/EFCore.Relational/Migrations/Operations/TableOperation.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
Changed AlterTableOperation.OldTable from Annotatable to TableOperation,
and did various fixes throughout to support comment alteration on tables.
Some comment fixes and refactoring.
Fixes #16819
Fixes #16798 
* The extended property functions (e.g. sp_addextendedproperty) don't accept NULL for schema - it must always be passed. Am defaulting to the model default and after that to dbo, hopefully that's right.
* Trying to call sp_addextendedproperty or sp_dropextendedproperty twice results in an error (property is already defined), meaning that this comment implementation isn't idempotent. Does it need to be?
> Full OldTable on AlterTableOperation, further comment support

- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/IndentedStringBuilder.cs
- src/EFCore/Query/ExpressionPrinter.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/Internal/QueryMetadataExtractingExpressionVisitor.cs
- src/EFCore/Query/QueryCompilationContext.cs
- src/EFCore/Query/QueryOptimizer.cs
- src/EFCore/Query/QueryOptimizerDependencies.cs
- src/EFCore/Query/ReplacingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/FiltersInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/FiltersInheritanceInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/FiltersInheritanceTestBase.cs
- test/EFCore.Specification.Tests/Query/FiltersTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryFilterFuncletizationTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.QueryTypes.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FiltersInheritanceSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FiltersSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/QueryFilterFuncletizationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
When nav rewrite constructs new EntityQueryable it now looks into EntityType for any query filter annotations and applies them on top. Those predicates are parameterized and the parameters created are injected into the context as part of query execution expression.
Generated predicate expression is re-visited by nav expansion to recursively handle filters (expand potential navigation expansions that were introduced in them).
This adds some complexity to the way navigations are expanded - before the newly constructed join always was guaranteed to be an entity. Now it can be a complex structure with multiple navigations already expanded.
> Fix to #15264 - QueryRewrite: incorporate query filters into nav rewrite

- EFCore.sln.DotSettings
- src/EFCore.Relational/Storage/RelationalConnection.cs
- test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/TransactionSqliteTest.cs
> Don't throw when System.Transaction is not supported

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitorFactory.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitorDependencies.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
> Query: Throw when capturing unknown type constants in shaper

- src/EFCore.InMemory/Query/Internal/CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/IncludeCompilingExpressionVisitor.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.KeylessEntities.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Rather than requiring AsNoTracking in the query.
Resolves #17102
> Query: Don't track materialized keyless entity instances

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
> Don't run Select_nested_projection without MARS

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Pack of entity equality fixes

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
Fix for issue #14457. Contains breaking change in MigrationsSqlGenerator (changed signature of DefaultValue method).
> MigrationsSqlGenerator: DefaultValue formats default value properly

- src/EFCore.SqlServer/Extensions/SqlServerMigrationBuilderExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteMigrationBuilderExtensions.cs
- test/EFCore.SqlServer.Tests/SqlServerMigrationBuilderTest.cs
- test/EFCore.Sqlite.Tests/SqliteMigrationBuilderTest.cs
Migrations: Add IsSqlServer, etc. to MigrationBuilder
Fixes #8566
> IsSqlServer etc migrationBuilder extensions

- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
> Try match FK properties with the exact name as principal key if they are a proper subset of the dependent PK and don't contain the Id property.

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.FromSqlParameterApplyingExpressionVisitor.cs
- src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
It is ParameterExpression in normal query but ConstantExpression when using compiled query
Resolves #17071
> Query: Process when FromSql parameter is ConstantExpression

- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/EnumerableToQueryableMethodConvertingExpressionVisitor.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/ReplacingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
This puts some of the processing (evaluating the expression to the corresponding constant) inside translation pipeline.
- When applying EntityEquality, assumption here is that property is always going to be mapped on server side so we can generate constant.
- When translating newExpression. If the generated constant can be mapped, it would work. (like new Datetime()) else translation would null out.
Resolves #15712
Resolves #17048
Resolves #7983
> The magical query pipeline

- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryTaggingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Query: DRY joins inside SelectExpression

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
If Linq expression uses constants in GroupBy skip these constants in SQL GROUP BY to avoid "Each GROUP BY expression must contain at least one column that is not an outer reference" SQL exception.
Fixes #14152
> Query: Skip constants in GROUP BY

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
- Validate inner select expression after extracting join predicate that it does not contain reference to outer.
- Also apply same logic for generating collections in projection.
- Identify DefaultIfEmpty in collectionSelector of SelectMany accurately.
This fix up a lot of N+1 evaluation queries.
Resolves #17112
Resolves #16311
> Query: Convert lateral joins into predicate joins only when appropriate

- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Instead throw an exception
Part of #17019
> Avoid deadlock in tests

- src/EFCore/Query/Internal/GroupJoinFlatteningExpressionVisitor.cs
Issue: A nested visitor was stored in static field but if contained states which caused flattening to fail some times.
Also verified that such issue is not appearing anywhere else in query.
> Query: Fix flaky GroupJoinFlatteningExpressionVisitor

- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsAnnotationProviderTest.cs
> SqlServer: resolve included properties of index to column names (in migrations)

- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitorFactory.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindQuerySqliteFixture.cs
Further expands the brick wall  of success℠ 💥🧱 which keeps you from falling into the pit of failure.
Fixes #16431, fixes #11925
> Sqlite Query: Block aggregate functions and OrderBy on unsupported types

- src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- src/EFCore.Relational/Infrastructure/ModelSnapshot.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/CompositeValueFactory.cs
- src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/ValueGeneration/ValueGeneratorSelector.cs
- src/Shared/Check.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
Fixes #17145 but see also #17205
The fix here allows the state manager to work, which is required when the model snapshot has model data in it.
> Be more resilient when using the model from the model snapshot

- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
> Throw if defining query is used on keyed entity type

- EFCore.Sqlite.slnf
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
This only works with create table. Alter table commands do not preserve
comments.
Fixes #16820
```
- Detail 1
- Detail 2
```
> Generate Sqlite create table comments

- src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
Some cleanup in relationship builders
Resolves #16704
> [preview9] Add a test for #16704

- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Except for static readonly fields
const fields are always inlined as constant by compiler
Resolves #17172
> Query: Parameterize member access in expression tree

- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterDefiningQueryRewritingConvention.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.FromSqlParameterApplyingExpressionVisitor.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/QueryFilterDefiningQueryRewritingConvention.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/QueryTranslationPreprocessorDependencies.cs
- src/EFCore/Query/ReplacingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.KeylessEntities.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
- test/EFCore.Specification.Tests/Query/QueryFilterFuncletizationTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.KeylessEntities.cs
- test/EFCore.SqlServer.FunctionalTests/Query/CompiledQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.KeylessEntities.cs
- test/EFCore.Sqlite.FunctionalTests/Query/CompiledQueryInMemoryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs
During nav expansion, when visiting EntityQueryables we now peek into entity metadata looking for defining query and query filter. If they are found, nav expansion applies them and expands navigations in the resulting query (recursively).
Also, fix to #17111 - Cannot use DbSet in query filter
DbSet accesses are converted into EntityQueryables during model finialization. We need to do this early, because otherwise we would need a dbcontext to create a queryable, and that dbcontext could be disposed at the time nav expansion runs.
Since FromSql/FromSqlRaw/FromSqlInterpolated are constrained to DbSet<T> they need to be converted to FromSqlOnQueryable at the same time.
> [preview9] Fix to #16323 - Query: add support for keyless entity types with defining query

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Wrote a test locally to generate lots of garbage. This fixed a NullRef. Still couldn't repro #16234
> Don't call SqliteConnection.RemoveCommand() from command finalizer

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
> Query: Allow providers to create subquery translating visitor

- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> Disallow client evaluation of queryable methods in projection

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
When expanding defining query and/or query filters in nav rewrite we now replace instances of EntityQueryable of the entity for which defining query (or filter) is expanded into NavigationExpansionExpressions - this way we don't recursively try to visit and expand them.
> Fix to #17253 - Global Query Filter with reference to same entity

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/CaseExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/RowNumberExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/QueryNavigationsSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
This enables support for non-scalar single result on Sqlite.
Resolves #10001 for Sqlite
Resolves #17292
> Query: Add RowNumberExpression support to convert lateral joins to joins

- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/CaseExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/RowNumberExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryNavigationsInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/QueryNavigationsSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
When projection contains single result coming out of collection which is not a mappable scalar then we cause client eval and add outer apply to generate the result.
Also tracking for such elements is fixed in new pipeline
Resolves #10001
Resolves #11762
> Query: Generate single SQL for queries projecting out non scalar single result

- src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/ExceptExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/IntersectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SetOperationBase.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlConstantExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpressionBase.cs
- src/EFCore.Relational/Query/SqlExpressions/UnionExpression.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
Remove SetOperationType enum
Add support for Intersect/Except Distinct
Resolves #16709
> Query: Fix Set Operation design

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
> Query: Expand navigations in GroupBy case

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/CrossApplyExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/OuterApplyExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Since they don't represent lateral join truly
> Query: Rename Lateral joins to Cross/Outer Apply

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.ResultEnumerable.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.InMemoryProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
Don't send shapers to ServerQueryExpression
Laying ground work for collection projection
Part of #16963
> InMemory: Avoid N+1 queries for Include

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeDiagnosticsLogger.cs
- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
> Test for #9742

- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore/Query/CollectionShaperExpression.cs
- test/EFCore.InMemory.FunctionalTests/Query/AsyncGearsOfWarQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/AsyncSimpleQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/CompiledQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/FiltersInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/IncludeInMemoryFixture.cs
> InMemory: Add support for collection projection

- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
City is the same for each customer, so effectively the lateral subquery is doing Take(2) without ordering.
(are we still sending PRs to 3.0-preview9?)
> Fix non-deterministic CROSS APPLY tests

- src/EFCore.InMemory/Query/Internal/InMemoryLinqOperatorProvider.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/SingleResultShaperExpression.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryNavigationsInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
> InMemory: Support for non-scalar single result in projection

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
We now flow the last navigation only for pure traversal (via member, EF.Property) and not for Select and others. This corrects valid entity references which were misidentified as collection navigations.
Fixes #17229
> Entity equality: fix mis-identification as collection navigation

- src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
> Persist non-implied properties in owned collection types

- test/EFCore.InMemory.FunctionalTests/Query/SpatialQueryInMemoryTest.cs
Two remaining issues:
- NullReferenceException accessing properties. (e.g. `e?.StringProperty.Length`) @maumar is working on this
- ValueComparer.Snapshot() not called on query results. @smitpatel it thinking more about how to fix this.
Part of #16963
> InMemory Spatial: Enable passing tests

- EFCore.Runtime.slnf
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
Don't try to generate snapshots with alternate keys for owned types
Fixes #15698
Fixes #13628
Fixes #12414
> Remove previous primary key when overriden

- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs
Fixes #17375
Reverse engineering a database using a secure, named connection string will crash. This is a common scenario except that referencing the connection string via name is less common than reading it directly. Specifically:
* Developer sets up a connection string in user-secrets (common)
* Developer names that connection string in ASP.NET-style config (common)
* Developer references the connection string by name in EF Core (less common, but not uncommon)
* Scaffolding a `DbContext` (common) will now fail with an exception
Customers will not be able to reverse engineer a database when using a named, secure connection string.
A workaround is to read the connection string manually from config and pass it to EF. This isn't a bad workaround, but we expect this to be something that …
> [release/3.0] RevEng: Fix bad logic around connection strings

- EFCore.Sqlite.slnf
- src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
- test/EFCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs
- test/EFCore.Sqlite.Tests/Update/SqliteUpdateSqlGeneratorTest.cs
Enables using default constraints and triggers to generate keys on SQLite.
Fixes #11603
> SQLite SaveChanges: Enable non-rowid store-generated keys

- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/SpatialInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs
Update issues references and add area for #16963
Enable tests which are already working
> InMemory: Tests scrub

- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Fixes #15279
@smitpatel not sure there is much value but it does test conditional in aggregate and not on the key.
> Add test verifying GroupBy with conditional aggregate

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Fixed cases involving member pushdown. We now remove all converts from nullable to non-nullable (even ones explicitly added by users) so that nullability can propagate to the very top.
> Further improvements on null protection/propagation

- src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
- src/EFCore.Cosmos/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
> Don't validate partition keys on embedded entity types.

- benchmark/EFCore.Benchmarks/Query/QueryCompilationTests.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Profiling the scenario in #17455 showed that SelectExpression.VisitChildren was a major compilation perf hotspot (own time, not including child calls). This PR changes the logic to only allocate new data structures and copy if a Visit actually returned a different result.
This reduced the time for #17455 from 22 seconds to 15 on my machine. Memory allocated notably goes down from 61.86MB to 12.17MB.
Also added a compilation micro-benchmark which does three joins, here are the results. Note that #17455 includes 6 results and so the difference is considerably more significant.
```
BenchmarkDotNet=v0.11.3, OS=ubuntu 19.04
Intel Xeon W-2133 CPU 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100-preview8-013656
[Host] : .NET Core 3.0.0-rc1-19430-09 (CoreCLR 4.700.19.43003, …
```
> SelectExpression.VisitChildren optimizations

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
> Add regression test for issue#6061

- src/EFCore.Cosmos/Query/Internal/ContainsTranslator.cs
- src/EFCore.Relational/Query/Internal/ContainsTranslator.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Additional PR to clean up #17469
Also re-targeted to release/3.1
> Query: Support ICollection<T>.Contains

- azure-pipelines.yml
- test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
- test/EFCore.CrossStore.FunctionalTests/ConfigurationPatternsTest.cs
- test/EFCore.CrossStore.FunctionalTests/CrossStoreFixture.cs
- test/EFCore.CrossStore.FunctionalTests/DiscriminatorTest.cs
- test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj
- test/EFCore.CrossStore.FunctionalTests/EndToEndTest.cs
- test/EFCore.CrossStore.FunctionalTests/TestModels/CrossStoreContext.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalDatabaseCleaner.cs
- test/EFCore.Specification.Tests/TestUtilities/TestStore.cs
- test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/DbContextOptionsBuilderExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerDatabaseCleaner.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
Disable tests that delete databases on CI
Don't delete databases in CI script, instead clean Northwind
Change DbContextOptionsBuilderExtensions.ApplyConfiguration to always use an ExecutionStrategy
Fixes #16342
> Don't use Northwind in CrossStore tests

- src/EFCore.Cosmos/Extensions/CosmosEntityTypeBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosModelBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosModelExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
- src/EFCore.Cosmos/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/KeyAccessExpression.cs
- src/EFCore.Cosmos/Query/Internal/ObjectAccessExpression.cs
- src/EFCore.Cosmos/Query/Internal/ObjectArrayProjectionExpression.cs
- src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- src/EFCore.Cosmos/ValueGeneration/Internal/CosmosValueGeneratorSelector.cs
- src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
- test/EFCore.Cosmos.Tests/Metadata/CosmosBuilderExtensionsTest.cs
- test/EFCore.Cosmos.Tests/Metadata/CosmosMetadataExtensionsTest.cs
We missed some method renames when doing API review of the Cosmos provider. We are asking to do these renames now before we ship the first GA release of the Cosmos provider. (It was only in preview for 2.x.)
We could instead obsolete the existing methods so as not to break from the last preview, but that would mean introducing new methods in a GA release that are already marked as obsolete when they ship.
Current APIs are inconsistent with the pattern we use elsewhere; this change brings them into line. 
Customers coming from a previous preview could be broken by this, but the fix is easy, and Cosmos usage is low.
Found while doing exploratory testing/prep for 3.1.
N/A
No
Risk is close to zero from a GA perspective, but it could break a small number of customers moving from previews to …
> [3.0] Remove suffix from Cosmos Metadata extensions

- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Also remove convert to object when it is just to add convert to another type (double casting)
Covers both variation described in the issue
Resolves #17389
> Query: Fix bug in type inference of LikeExpression

- src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
An algorithmic issue in the 3.0 query code can cause execution time to grow quadratically with increasing number of includes and entity properties. This can make queries both compile and execute much slower in some scenarios.
Some queries with many `Include` calls could be so slow that they appear to hang.
We don't currently have perf testing for queries of this level of complexity. Perf testing is something we are already actively working on.
See below for local perf numbers before and after the change--in this case we're going from 175 seconds to 19 milliseconds.
Yes, regression in perf from 2.2.
We have spent some time deciding what to do now and going forward. For now, we have a low-risk fix that is not 100% architecturally correct, but which fixes the issue in a …
> [3.0] Perf: Skip visiting table inside ColumnExpression

- src/EFCore/Query/Internal/ExpressionEqualityComparer.cs
Because `ExpressionComparer` was a class each expression comparison did one additional allocation on the heap. This change removes it by changing the type to be a `struct`.
> Removed allocation introduced by ExpressionComparer

- src/EFCore.Relational/Storage/RelationalCommand.cs
Provide a simple solution to inject a custom `RelationalDataReader` into `RelationalCommand`, without having to override `ExecuteReader` and `ExecuteReaderAsync`.
- Refactor `RelationalDataReader` creation, out of `ExecuteReader` and `ExecuteReaderAsync`, into its own factory method.
Fixes #17712
> Custom RelationalDataReader injection into RelationalCommand

- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.KeylessEntities.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Problem was that when expanding collection navigations we convert them into subqueries with a correlation predicate being outerKey == innerKey. For relational, most of those queries would later be converted into joins, however for some complex cases e.g. with Skip/Take (and also on InMemory) the query would stay in the form of subquery with correlation predicate. Then, null semantics kicks in and converts the correlation predicate to a form that returns true when both keys are null. This is incorrect in the context of chaining navigations - if the parent entity is null then it should never return any children.
Fix is to add null check to the correlation predicate during nav rewrite, like so: outerKey != null && outerKey == innerKey
Additionally, when trying to convert those subqueries …
> Fix to #17531 - Query: incorrect results for queries with optional navigation followed by collection navigation with skip/take/distinct

- src/EFCore/Infrastructure/ModelSource.cs
- src/EFCore/Infrastructure/ModelSourceDependencies.cs
- test/EFCore.Tests/ModelSourceTest.cs
This reverts commit 4978c1af692ed62f9a188f22ece1cf44aeb0411d.
This is the alternative fix to https://github.com/aspnet/EntityFrameworkCore/pull/17835
> Revert "Use IMemoryCache for model caching."

- .editorconfig
- src/EFCore.Cosmos/Metadata/Conventions/CosmosDiscriminatorConvention.cs
- src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
- src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- src/EFCore/Infrastructure/ModelSource.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
Don't add discriminators for embedded entities 
Allow to update entities without discriminators
Don't try to add the default discriminator if a conflicting property already exists
Fixes #17764
Fixes #17302
Fixes #17814
Several basic scenarios involving discriminators will be unblocked now.
N/A, 3.0 will be the first RTM release for the Cosmos provider
Low
> Fix some Cosmos discriminator issues

- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
> Add regression test for issue#12761

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.JoinGroupJoin.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.KeylessEntities.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
- added `AssertEqual<T>` which now automatically use elementAsserters for a given test base.
- added `AssertCollection<TElement>` which can also use elementAsserters automatically.
- cleaned up elementAsserter lambdas in the current tests
> Improvements to asserters in query tests.

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
Use the full owner access expression instead of just the jObject variable to allow accessing values on the owner of the owner.
Fixes #17733
Owned entities nested more than one level down are unusable without this fix.
N/A, 3.0 will be the first RTM release for the Cosmos provider
Low
> Cosmos: Populate owned entities nested more than one level down

- src/EFCore/Query/Internal/EnumerableToQueryableMethodConvertingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Convert ToList().Count() to AsQueryable().Count()
When enumerable operators appears after ToList, we can convert them to queryable operators by removing ToList.
Also take care when ToList uses a different generic type than inner type.
Avoid adding AsQueryable if inner is already queryable of correct type.
Resolves #13744
A query which was throwing exception now evaluates correctly on server.
It never worked in past.
Low
> Convert ToList().Count() to AsQueryable().Count()

- src/EFCore/Query/ShapedQueryExpression.cs
- test/EFCore.Specification.Tests/Query/CompiledQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/CompiledQuerySqlServerTest.cs
Accurately assign type to ShapedQueryExpression
Earlier we assumed IQueryable<T> only. Now it sets based on actual cardinality
Resolves #13895
Customer may not be able to use EF.CompileQuery API when the expression tree does not terminate in queryable operator.
It never worked in past.
Low
> Accurately assign type to ShapedQueryExpression

- src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
Add the partition key to the store key
Throw when an error is detected during a store operation.
Fixes #17435
Fixes #17616
Fixes #17624
Without these fixes errors like modifying an immutable partition key, saving changes to or quering a non-existant container as well as other similar errors are silently ignored leading to confusion and potential data loss.
N/A, 3.0 will be the first RTM release for the Cosmos provider
Low
> Cosmos: Add the partition key to the store key

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Validate that properties sharing a column have the same nullability, not that the corresponding column would have the same nullability
Fixes #17820
Allows to share a column with a required property on the main entity type.
No
Low
> Fix shared column nullability validation

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/SharedTableEntryMap.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandComparerTest.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
- test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
Modifications to a shared row will derive their state only from the main entry (the entry that isn't a dependent of any other entry in the row). If the main entry isn't present the row is assumed to be modified.
The principal entry is now not required to be in the same state as the dependent when saving changes to a shared row.
Fixes #17422
Fixes #17935
Allows to add and delete just the dependent entities when using table splitting.
No, optional dependents in table splitting is a new feature in 3.0
Medium, can impact other update scenarios.
> Allow to add and delete dependents sharing a table

- src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Tests/Metadata/Conventions/BackingFieldConventionTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Don't throw when configuring a field for a shadow property.
Don't throw from BackingFieldConvention until the model is finalized.
Fixes #15307
Fixes #17691
Allows to use field-only properties and properties that have several matching fields
Yes
Low
> Fix validation for field configuration

- Directory.Build.props
- Directory.Build.targets
- global.json
- src/dotnet-ef/dotnet-ef.nuspec
Part of https://github.com/aspnet/AspNetCore-Internal/issues/3016
CC @ajcvickers @dougbu @JunTaoLuo
> Update to 5.0 SDK

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.JoinGroupJoin.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.KeylessEntities.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.SetOperations.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.JoinGroupJoin.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.KeylessEntities.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
converting AssertQuery(...) (i.e. queryable, non scalar result) to strongly typed versions
> Fix to #18002 - Query/Test: convert AssertQuery methods to strongly typed versions (part2)

- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategy.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
Use the SDK exception type when a store error occurs
Remove the exception messages introduced in https://github.com/aspnet/EntityFrameworkCore/pull/17903 as they didn't add much value
Part of #17925
With these changes store failures will be presented as `CosmosException` instead of `InvalidOperationException`, so they can be retried
N/A, 3.0 is the first RTM release for the Cosmos provider
Low
> [3.1] Cosmos: Use the execution strategy to retry transient failures

- src/EFCore.Analyzers/EFCore.Analyzers.nuspec
- src/EFCore.Tools/EFCore.Tools.nuspec
Add `icon` metadata to 2 manual `.nuspec`s that I missed previously
> Add missed icon metadata

- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
We were missing some overloads, this could be confusing when trying to write tests that needed those overloads.
Fixes #17975
> Fix to #17975 - Query/Test: add missing Assert overloads for aggregate operations

- src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
Problem was that we were only preventing null expansion in predicate, leaving projection and orderings intact.
Fix is to go through entire SelectExpression and prevent null expansion on all encountered comparisons.
Because this changes the result it is switched off by default.
> [2.1] Fix to #13285 - UseRelationalNulls does not work with SELECT conditions

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
resolves #14550
resolves #15164
resolves #15994
resolves #16722
added regression tests for #14671
added regression test for #17852
converted remaining tests in Gears of War into AssertQuery pattern (part of #12501)
> Miscellaneous query test fixes

- src/EFCore.Analyzers/EFCore.Analyzers.csproj
- src/EFCore.Analyzers/EFCore.Analyzers.nuspec
- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
In release/3.0, we needed placeholder files for NetStandard1.3 and NetCoreApp2.1 in these 2 nuspecs, but that's not the case in release/3.1 or master. Their existence caused nuget package validation to fail.
Manual cherry-pick of https://github.com/aspnet/EntityFrameworkCore/pull/18214, in case that one has to wait for preview2.
> Fixup nuspecs master

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
I knew we'd eventually find weird corner case bugs in this code.
Fixes #14027
> Migrations: Fix bug in complex column ordering code

- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- added regression tests for #12289
- added regression tests for #15279
- added regression tests for #15938
- added regression tests for #18267
- resolves #12522
- resolves #12805
- resolves #13231
- resolves #13594
- resolves #13754
- resolves #14851
- resolves #15103
- resolves #15669
- resolves #15853
> Adding tests for various group by scenarios

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
We we were not checking that argument to the Min/Max method was itself translated.
Resolves #18269
> Fix to #18269 - Query: NRE for query with groupby with Min/Max on entity

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Sql we generate is not perfect (ordering on the joined set is not preserved) but there is not much we can do in the general case. We could improve this for some cases (outer set it's unambiguously sorted or is entity which we can sort ourselves).
Probably not worth given the marginal benefit.
> [TINY] Enable sql verification for #16086 - Query: subquery with order by but without Skip/Take gets the orderby removed

- src/EFCore.Analyzers/EFCore.Analyzers.csproj
- src/EFCore.Analyzers/EFCore.Analyzers.nuspec
- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
In release/3.0, we needed placeholder files for `NetStandard1.3` and `NetCoreApp2.1` in these 2 nuspecs, but that's not the case in release/3.1 or master. Their existence caused nuget package validation to fail. 
@dougbu @Pilchie do you think it's worth taking this for 3.1-preview1? I lean towards waiting for preview2, since it doesn't block the build, and the effect on customers is minimal (an extra empty file in these 2 nupkg's).
> Remove unnecessary placeholders in .nuspec's

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Fixes #17744
@smitpatel the fix here is trivial/minimal to unblock the issue for 3.1: the EE visitor simply ignores (unwraps) entity reference node coming up from the NewArray's expressions.
A more complete fix would be to actually bubble this information up (probably all expressions must bubble up the same thing, or we start tracking information per element, like we do for anonymous objects). However, unless I'm mistaken, there's not actually much (anything?) that can be composed over this which EF Core can actually translate. For example, we don't support subscripting the array just created or anything similar, so there doesn't seem to be any value in this (right now).
Let me know if this sounds reasonable and if you'd like me to do something more on this.
> Handle NewArrayExpression in entity equality

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Resolves #18362
Also resolves #17239
> Pushdown SelectExpression with OrderBy/Skip/Take when creating a set operation

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Shadow Values factory expects a value buffer which also has slots for shadow navigations. But when populating we did not consider them. So we got a value buffer with values in wrong slots.
It happens only for ModelSnapshot (the shadow model phase) when seeding derived type when base type has a navigation.
It throws NRE if encounter null value for non-null field
or ICE if encounter different type then expected.
Resolves #17851
> Use Shadow property index when generating Shadow values buffer

- azure-pipelines.yml
- test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
Increase CI timeout
Fixes #18301
> Clean local Cosmos DB databases

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Since it will cause materialization and Find will return entity without the whole graph.
Resolves #18155
> Query: Add Includes when projecting non-mapped property

- src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
- src/EFCore/Query/QueryTranslationPreprocessor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Code follows the simplification ReLinq did for us.
Resolves #17791
> Query: Support InvocationExpression

- eng/Versions.props
> Update Microsoft.Azure.Cosmos to 3.3.1

- src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
- test/EFCore.Relational.Tests/Utilities/DbParameterCollectionExtensionsTest.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
Change formatting to print null/DbNull parameters are NULL instead of ''
> Fix to #17923 - FormatParameterValue results in @__prm='' for parameters whose value is NULL

- test/EFCore.CrossStore.FunctionalTests/ConfigurationPatternsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
Always use the ExecutionStrategy in SQL Server tests
> Don't leak connections in CrossStore tests

- src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
- test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/FunkyDataModel/FunkyDataData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.KeylessEntities.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
For StartsWith where pattern was a non-constant we used an optimization involving LIKE, however this could lead to incorrect results if the pattern contained a wildcard.
Fix is to remove the optimization. If needed, users can explicitly use LIKE to improve the performance.
Resolves #17948
> Fix to #17948 - Bracket [ not escape in string.StartsWith

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
Scenario: NewExpression of struct type which does not have any ctor arguments (so new DateTime()). New DateTime(2019, 12, 11) still has ctor so it works fine. Struct type could be user defined or system defined.
Root cause: When calling NewExpression.Update the way checking if arguments are changed is different in .NET Framework & Core. Since arguments are 0, it should not need to be updated. .NET Core identifies this correctly and does not cause regeneration avoiding the exception.
> Query: Skip updating NewExpression without ctor

- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
> Query: Translate GroupBy-Aggregate when using result selector

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.SetOperations.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
Fixes #18135
@smitpatel some minor comments:
* Technically we should also make [the outer EntityProjectionExpression itself](https://github.com/aspnet/EntityFrameworkCore/blob/3a87d7e12884f0706581a9d3b3547cb54b378851/src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs#L579) nullable when one of the inner ones is nullable, but we currently can't check if an EntityProjectionExpression is nullable or not - we could expose IsNullable for this purpose. This doesn't seem to matter in practice since EntityProjectionExpression's nullability is only consulted in BindProperty, but for set operations _propertyExpressionsCache is already populated correctly. Let me know if you want me to do this and expose IsNullable.
* In a perfect world, isNullableProjection should drill down into the …
> Correct nullability for set operations

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/ICSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
Summary of changes
- Add a new parameter to the WriteCode method of the ICSharpDbContextGenerator interface to pass the namespace of the models
- CSharpDbContextGenerator generates a using statement in the DbContext class if the models are in another namespace
- Add two test on CSharpDbContextGeneratorTest
Fixes #17839
> Scaffold-DbContext includes "using statement" with model´s namespace

- src/EFCore/Metadata/Internal/NavigationExtensions.cs
- src/EFCore/Query/ExpressionPrinter.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
- src/EFCore/Query/MaterializeCollectionNavigationExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.Specification.Tests/Query/FiltersTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeAsyncTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
- test/EFCore.Tests/Query/ExpressionPrinterTest.cs
Adding a new switch to ExpressionPrinter that creates simplified output for Print and verbose (i.e. what we had before this change) for PrintDebug.
Simplified output means:
- displaying Enumerable/Queryable methods (e.g. Where, Select, Join) as extension methods
- simplifying display of Navigation object
Also fixed minor display bugs in expression printer.
Also some changes in testing:
- added unit tests for ExpressionPrinter,
- DRY the "translation failed" tests,
- "translation failed" tests no longer verify expression in the exception message and instead just make sure that right exception is thrown.
Resolves #17236
> Fix to #17236 - Improve readability of expressions in client evaluation exception

- src/EFCore/Internal/EntityFinder.cs
- test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
Specifically for owned entities
Resolves #16186
Resolves #18366
> Build QueryRoot correctly for entity entries

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/FiltersTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
Fixes #18158
Added the entity equality scenario to an existing query filter in Northwind - not super pretty but works. I can do a QueryBugTest instead (extra db), let me know.
> Apply entity equality to query filters

- samples/Microsoft.Data.Sqlite/EncryptionSample/Program.cs
- samples/Microsoft.Data.Sqlite/InteropSample/Program.cs
The Password keyword was introduce in 3.0.0, but we forgot to update the sample.
> Microsoft.Data.Sqlite: Update encryption sample

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
> Don't throw when detaching owner entity with un-tracked owned

- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Throw better exception for incorrect ownership configuration.

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.RelationalCommandCache.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
Resolves #15892
I attempted to add to cosmos also but ran into #18033 
Currently this takes naïve approach that if SelectExpression was modified during parameter based EV then we cannot cache it. If we work on #16375 then that would be quite accurate logic without us having to pass back the information. I filed #18034 to track.
> Add RelationalCommandCaching based on parameter value nullability

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Map owned reference types to the same view as the owner by default.

- src/EFCore.Cosmos/Query/Internal/EqualsTranslator.cs
- src/EFCore.Relational/Query/Internal/EqualsTranslator.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
> Query: Only match object.Equals with 2 parameter when static method

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.RelationalCommandCache.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitorDependencies.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Add test to verify the command caching
Resolves #18493
@AndriySvyryd - Added a test. (and there were few existing already). Which verifies that same parameter nullability, cache size remains same.
> Query: Use MemoryCache for RelationalCommand caching

- src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ParameterNullabilityOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ParameterValueBasedSelectExpressionOptimizer.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.RelationalCommandCache.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/CompiledQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.KeylessEntities.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FiltersSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
This is part of #17543 - Queries really slow due to null checks
Problem was that at the time we performed null semantics and related optimizations we didn't know the value of parameters, so we always had to assume they can be nullable, which resulted in additional IS NULL checks being created.
However, later in the pipeline we know the parameter values and we can optimize out those checks for parameters whose values are not null.
> Optimize SQL based on parameter nullability

- test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs
See https://github.com/aspnet/AspNetCore/issues/14812.
No bug on our side, but good to increase coverage.
> Add some NRT tests for inheritance

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Closes #18379
* We lack support for MemberMemberBinding or MemberListBinding as decided in https://github.com/aspnet/EntityFrameworkCore/pull/16791. I think it would be good to at least handle these in top-most projection (not full support with flowing), @smitpatel let me know.
* Theoretically there's IndexExpression which doesn't seem to be actually produced by the C# compiler. The node breaks  elationalSqlTranslatingExpressionVisitor anyway, we can probably forget about it.
Haven't seen anything else but let me know if I've missed anything.
> Handle ListInitExpression in entity equality

- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
Fixes #17784
In 3.0 we made a [simple change](https://github.com/aspnet/EntityFrameworkCore/commit/7e65b82821ce2540d12d35c6449712f07c56a527#diff-7767de8ee880eb46efbfc9d2153dd33a) for #15645 that started clearing navigation properties when they referenced detached entities. In retrospect this was the wrong thing to do as people are relying on this to be able to detach all entities from the context.
The new fix restores the pre-3.0 detach behavior, and sends the reload of a deleted entity through a simulated to delete instead.
> Revert 3.0 fix for consistent reload and replace with fix that doesn't dramatically change detach behavior

- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Also added SQL assertion for unrelated test.
Closes #16308
> Add test for set operations over FromSql

- src/EFCore/Metadata/Internal/ConventionAnnotation.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/Index.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Key.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/TypeBase.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
> Reset relationship uniqueness when removing the navigation to dependent.

- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
Fixes #18330
Note that the connection.Open operation has passes `errorsExpected: true`, so that connection errors are logged as debug. We can do this for the `SELECT 1` command as well, but I think the main idea here is to squash "does not exist" errors specifically, which really aren't an error. Other types of errors (e.g. connectivity) still seem like they should log an error, since it's not a matter of the database not being created. But if someone thinks otherwise I can add `errorsExpected` to command failure logging.
> Add SELECT 1 check to Exists/CanConnect checks

- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
Fixes #18551
Manually verified.
cc @aspnet/build
> CLI Tool: Remove lib/ from package

- src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Fix nested owned types in 2.x snapshots.

- src/EFCore/Metadata/Internal/EntityType.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
> Don't clear discriminator values when discovering a new non-root base type.

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/SidecarValues.cs
- src/EFCore/ChangeTracking/Internal/Snapshot.cs
- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/TemporaryValuesFactoryFactory.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
Fixes #17997
The problem here was that the temporary values snapshot was copying current values rather than starting with empty values. This then meant that when the current value was set to null, the temp value took over, which was then incorrect. Related to this, when setting a current value to null, the temp value (if it exists) must also be set to null otherwise it will start being used.
> Fix temporary value snapshot

- src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ParameterNullabilityOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Problem was that during null semantics rewrite we create IS NULL calls on the operands of the comparison. If the operands themselves are complicated, we were simply comparing the entire complex expression to null. In some cases, we only need to look at constituents, e.g. a + b == null <=> a == null || b == null.
Also added other minor optimizations around null semantics:
- non_nullable_column IS NULL resolves to false,
- try to simplify expression after applying de Morgan transformations
Also fixed a bug exposed by these changes, where column nullability would be incorrect for scenarios with owned types.
> Fix to #16078 - Query/Null semantics: when checking if expression is null, just check it's constituents rather than entire expression

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
> Set Cascade OnDelete for ownerships without conventions to avoid false model diffs.

- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
Otherwise calling Close followed by Dispose generates an exception internally, bad for perf and for the debugging experience.
Fixes #18307
> Exit Dispose early if reader is already disposed

- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
> Warn when using a value converter on a collection/enumeration type without a comparer

- azure-pipelines.yml
__Problem__
The ${{ }} expressions evaluate at compile-time and `Build.BuildId` variable is not set at that point
And $[ ] can't be used in variable conditions
__Solution__
Move the `Build.BuildId` expression to a task condition so it can be evaluated at run-time
> Fix Cosmos tests on CI

- src/EFCore/DbSet.cs
Issue #18124
Helps avoid conflicts when also using IX-Async. No new tests since several existing tests now bind to these methods.
> Add explicit AsAsyncEnumerable and AsQueryable methods to DbSet

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Use the default value for non-nullable properties.
Fixes #18592
> Don't compare seed values for store generated properties.

- src/EFCore.Relational/Query/Internal/ContainsTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
> ContainsTranslator fix for arbitrary ICollection<T> implementations

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
And add some tests.
Fixes #18579
> Fix ValueGeneratedOnUpdate in scaffolding

- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Don't visit conditional true or false nodes as appropriate if test evalutes to constant.
Also don't visit right-hand side of null-coalescing expression if left-hand side evaluates to non-null.
Fixes #17942
Fixes #13859
> Fix conditional and null-coalescing handling in parameter extraction

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue: Earlier we expanded navigation in selector and include in separate phase. This causes issue because if the latter visitor expands a reference navigation then former visitor's collection expansions have incorrect references.
Fix: Fix is to make include expansion part of selector expansion as next phase. So by the time we apply include, the correlation predicate in collection hasn't been converted to actual reference. So when it gets converted, it takes correct reference.
Also apply pending selector inside lambda expression since it is a subquery. This caused issue when subquery has a projection which has navigation to expand, which we never visited.
Resolves #18127
Resolves #18090
Resolves #17852
Resolves #17756
> Query: Expand navigations in Selector/Include in one pass

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Necessary to unblock some code literal generation for Npgsql.
As this is a design-only low-risk tiny change, I'm hoping we can get this into 3.1.
/cc @bricelam @Pilchie @ajcvickers
> Support non-static members in C# generation

- src/EFCore/Query/Internal/EnumerableToQueryableMethodConvertingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
Our EnumerableToQueryable converter works on all the methods. But during nav expansion, we actually inject query sources.
If item is not a query source (like postgre arrays or collection property mapped as scalar via value conversion), then we convert it to enumerable again to be handled by provider.
Resolves #17374
> Query: Removing Queryable conversion for sources which are not queryable

- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NullCheckRemovingExpressionVisitor.cs
- src/EFCore/Query/NullConditionalExpression.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Tests/Query/ExpressionPrinterTest.cs
We flow nullability information through joins. And InMemory works with nullable values from database differently.
Hence we no longer need it. It creates unnecessary wrapper expression complicating things.
Looking for a quick review. It is required for #18670
> Query: Deprecate NullConditionalExpression

- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Test failures triggered in EFCore.PG (tests are not overridden). Not sure why this doesn't happen on our CI but it doesn't really matter much...
> Ignore line endings in test assertions

- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
AssertIncludeQuery currently ignores the provided element sorter.
I don't have all the context so I'm not sure I did the right thing here. It's fine to punt this after 3.1 if we want to, I have two affected test failures in Npgsql which I can skip.
> Apply element sorter in AssertIncludeQuery

- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
This are subtle and super annoying to track down... Too bad tests pass on SQL Server/Sqlite...
> Fix some non-determinism in tests

- src/EFCore.Relational/Metadata/Internal/DbFunction.cs
- test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
Update dbfunctions to use the AssemblyQualifiedName in their annotation name.  This will prevent nested, and cross assembly, class functions from having name collisions.  
Fixes #18425
> Use AssemblyQualifiedName to distinguish db functions.  Fix issue #18425

- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/Shared/ExpressionExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Unwrap convert nodes around entity before doing member lookup

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Resolves #18087
Navigation expansion prunes Cast to implemented interface or object
Navigation expansion puts cast to non-implemented interface
> Query: Process Cast to interface/object in Navigation expansion

- src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/MilitaryRank.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
One of the binary expression optimizations is op(a, b) == null -> a == null || b == null. This is valid for all binary operators except logical (AndAlso, OrElse). Before we used to also skip this optimization for bitwise (And, Or).
However, this optimization is valid for bitwise ops, so the fix is to enable it.
Resolves #18725
> [SMALL] Fix to #18725 - Optimize out null checks when translating Enum flags

- azure-pipelines.yml
`Build.BuildId` isn't guaranteed to provide consecutive numbers for consecutive runs, so instead use a separate counter for each build type.
> Use a more predictable input for Cosmos test accounts load balancing

- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Fix to #18709 - Query: expression printer should still print type argument for Cast and OfType
Fix to #18413 - Query: clean-up expression printer when we can do breaking changes
Resolves #18709
Resolves #18413
> ExpressionPrinter fixes/cleanup

- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Fixes #18759
@smitpatel if we really want to avoid QueryBugsTest we can simply remove the equality operator from Customer and the bug should repro in FiltersQueryBase.Entity_Equality. But this seems subtle enough that a query bug test makes sense (i.e. to avoid someone defining an operator again in the future). Let me know what you prefer.
> Exclude Object when checking for DbContext in query filters

- src/EFCore.Cosmos/Extensions/Internal/CosmosExpressionExtensions.cs
- src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
- src/EFCore.Relational/Extensions/Internal/RelationalExpressionExtensions.cs
- src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Query/Internal/AllAnyToContainsRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NegationOptimizingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Implement non-boolean bitwise complement

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was that on c# join predicate behaves differently when it's a regular property (null and null yield false), and where its anonymous type with just a single property (new { A = null } and new { A = null } yields true).
However, we lose that distinction during initial Join predicate translation.
Fix is to add a sentinel true == true condition, if the anonymous type only has one element. This condition can be later optimized out.
Resolves #18808
> Fix to #18808 - Query: incorrect results for query with Join where key selector is anonymous type with a single property

- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Also fixed a minor bug in expression printer, where we would print incorrect argument names for extension methods with 2+ arguments.
Resolves #16093
> Enable tests for #16093 - Query: Result mismatch likely due to null semantics

- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
Many tests are not producing expected SQL, tracked remaining ones with relevant issues.
Resolves #15994
> Fix to #15994 - Query: investigate suspicious SQL generated by query tests

- src/EFCore.Design/Design/Internal/NamespaceComparer.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- src/EFCore/Query/Internal/SubqueryMemberPushdownExpressionVisitor.cs
Fixes #18831. We should also use analyzers (#18870) to make sure it doesn't happen again.
*Mystery:*
Tried to add a test. But mysteriously, the following yields False, True:
```c#
Console.WriteLine("__someName_0".StartsWith("@"));
Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("th-TH");
Console.WriteLine("__someName_0".StartsWith("@"));
```
But the same inside a test returns false for both... There's some environmental thing going on, but don't think it's worth digging into it.
> Add missing Ordinal to {Starts,Ends}With

- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
Fixes #18355
We can consider logging the exceptions, although I'm not sure that would be the right thing to do - this method is purely about checking whether we can connect or not, and it could be said there's no actual "failing operation" warranting a log message. It would also likely cause lots of spurious log messages as automated health checks fail while networking is down etc.
Note that I don't think this is a breaking change, as applications are already expected to check for false.
> Catch exceptions in CanConnect and return false

- src/EFCore.Relational/Query/Internal/CaseWhenFlatteningExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- Added CaseWhenFlatteningExpressionVisitor postprocessor 
- Recursively collapse relevant CaseExpression
Fixes #12729
> Fixes #12729 Flatten Case expression

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Expand navigations together in OrderBy/ThenBy

- src/EFCore/ChangeTracking/GeometryValueComparer.cs
- test/EFCore.Relational.Tests/Storage/RelationalGeometryTypeMappingTest.cs
> Switch to using EqualsExact in geometry comparer

- src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/ScalarSubqueryExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
> Fix to #18522 - Query: SqlFunctionExpression instance should be SqlExpression rather than Expression

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Query/IRelationalParameterBasedQueryTranslationPostprocessorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
- src/EFCore.Relational/Query/Internal/RelationalParameterBasedQueryTranslationPostprocessor.cs
- src/EFCore.Relational/Query/Internal/RelationalParameterBasedQueryTranslationPostprocessorDependencies.cs
- src/EFCore.Relational/Query/Internal/RelationalParameterBasedQueryTranslationPostprocessorFactory.cs
- src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitorDependencies.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedQueryTranslationPostprocessor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedQueryTranslationPostprocessorFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
Using DI to create parameter value based postprocessor, which allows for provider-specific optimizations, including SearchConditionConvertingExpressionVisitor
Resolves #18492
Resolved #18940
> Fix to #18492 - Query: inject SearchConditionConvertingExpressionVisitor into ParameterValueBasedSelectExpressionOptimizer

- src/EFCore/Query/QueryCompilationContext.cs
- src/EFCore/Query/QueryCompilationContextDependencies.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- test/EFCore.Tests/Query/QueryCompilationContextDependenciesTest.cs
> Query: Don't expose ICurrentDbContext on QCCD

- src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
- src/EFCore.Cosmos/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/KeyAccessExpression.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- src/EFCore.Cosmos/ValueGeneration/Internal/CosmosValueGeneratorSelector.cs
> Cosmos: Rename Get/SetPropertyName to Get/SetJsonPropertyName

- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
Since visiting inner could return null
Resolves #18888
> Query: Don't use VisitAndConvert in projectionBindingExpressionVisitor

- test/EFCore.Specification.Tests/MusicStoreTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
> Query: Add regression tests

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
For #18926. 
It would really really really help [1] if this would be considered for merge 🙏 and before 3.1 ships 🤞. I don't see any breaking changes here, because in 3.0 this was non-existing and hence nobody could override, hence nothing is/was/will be broken.
[1]: It would help because copying `VisitSelect` and duplicating all the code is impractical because of some private methods usage and also makes no sense when simple plug in point can handle it.
> Re-introduction of GeneratePseudoFromClause for specific "empty" FROM clauses

- src/EFCore.SqlServer/Query/Internal/SqlServerByteArrayMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
> Support Contains on byte arrays

- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
Fixes #18724 (Hopefully)
Retrying if we get a null for up to one second and then assuming null is correct. We'll see how it goes...
> Mitigation for race condition in SpatialiteLoader.FindExtension()

- src/EFCore/Metadata/Internal/DebugView.cs
- src/EFCore/Metadata/Internal/DebugViewOptions.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/ForeignKeyExtensions.cs
- src/EFCore/Metadata/Internal/Index.cs
- src/EFCore/Metadata/Internal/IndexExtensions.cs
- src/EFCore/Metadata/Internal/Key.cs
- src/EFCore/Metadata/Internal/KeyExtensions.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/ModelExtensions.cs
- src/EFCore/Metadata/Internal/Navigation.cs
- src/EFCore/Metadata/Internal/NavigationExtensions.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/Metadata/Internal/ServiceProperty.cs
- src/EFCore/Query/MaterializeCollectionNavigationExpression.cs
- test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj
This is mostly for me when debugging issues, since I frequently manually remove annotations to make the model easier to read.
> Expose an annotation-free DebugView of the model

- src/EFCore/Query/ReplacingExpressionVisitor.cs
- src/Shared/MemberInfoExtensions.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
Issue: For compiler generated trees the MemberInfos always in sync. But for manually generated trees, if derived type parameter is used then the MemberInfo.ReflectedType is different. Which throws off ReplacingExpressionVisitor when comparing MemberInfo.
Fix: Use helper method IsSameAs which compare memberInfos which refer to same member access in given hierarchy
Resolves #19087
> Query: Match memberInfo in hierarchy for reducing MemberInitExpression

- eng/Version.Details.xml
- eng/Versions.props
- global.json
* Use Microsoft.NETCore.App.Internal for runtime version
For stable builds, core-setup is now publishing its artifacts to a suffixed directory (e.g. 3.0.1-servicing-19510-13) instead of 3.0.1. This ensures we don't have to overwrite outputs when we rebuild stable versions. Within that directory, it publishes the same set of files with the final file names as well as suffixed file names:
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-win-x64.msi
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-servicing-19510-13-win-x64.msi
Downstream repos should install the runtime using the full suffixed version.
> [release/3.1] Use Microsoft.NETCore.App.Internal for runtime version

- eng/Version.Details.xml
- eng/Versions.props
- global.json
* Use Microsoft.NETCore.App.Internal for runtime version
For stable builds, core-setup is now publishing its artifacts to a suffixed directory (e.g. 3.0.1-servicing-19510-13) instead of 3.0.1. This ensures we don't have to overwrite outputs when we rebuild stable versions. Within that directory, it publishes the same set of files with the final file names as well as suffixed file names:
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-win-x64.msi
- https://dotnetcli.blob.core.windows.net/dotnet/Runtime/3.0.1-servicing-19510-13/dotnet-apphost-pack-3.0.1-servicing-19510-13-win-x64.msi
Downstream repos should install the runtime using the full suffixed version.
> [release/3.0] Use Microsoft.NETCore.App.Internal for runtime version

- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
> Explicit order (#19216)

- test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
> Ordering fix (#19222)

- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> Ordering fix (#19220)

- src/EFCore.Cosmos/Metadata/Internal/CosmosPropertyExtensions.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Fixes #18948
Cosmos provider allows to save collections of owned entities as embedded documents in a JSON array property in the owner document without storing the key values explicitly. They are synthesized from the owner key and the ordinal in the collection. However we didn't synthesize the values when saving the entities, only when querying.
The fix is to synthesize the key values when saving the entities. And also consistently allow readonly properties to be set the current store values during SaveChanges to allow propagation of the new values.
The bug leads to the newly saved entities having a different identity and causes duplication in the owned collections if queried after saving a new entity using the same context.
Customer-reported
We did not have tests querying back the …
> [3.1.1] Set ordinal key values for embedded owned collection entities

- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
- src/EFCore/Internal/ServiceProviderCache.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
Fixes #19053
EF provides AddEntityFramework* methods to add EF-required services to a service collection, but this call is usually not needed when AddDbContext is called and is completely unnecessary if UseInternalProvider isn't called for the DbContext options.
This change adds a warning that is logged when this case is detected.
By calling AddEntityFramework* on the application service collection the customer can inadvertently make other frameworks use EF services like `IMemoryCache` which can lead to hard-to-diagnose issues at runtime.
Customer-reported
We had tests for this scenario, but didn't consider it to be common enough to warrant a warning.
Yes, in 3.0.0 EF started registering `IMemoryCache` with a hard limit.
Low, no behavior change
> [3.1.1] Warn on redundant AddEntityFramework* calls

- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
Since visiting inner could return null
Resolves #18888
> [3.1.1] Query: Don't use VisitAndConvert in projectionBindingExpressionVisitor

- src/EFCore.Relational/Query/SqlExpressions/InExpression.cs
Just to tighten things up, it's currently possible to construct in invalid InExpression via Update.
> Tiny: Add InExpression argument check

- src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
Fixes https://github.com/aspnet/EntityFrameworkCore/issues/3836
I was hoping to get a review of the auto-coalescing implementation before I fixed the broken tests (if there's a better way than creating a PR with knowingly broken tests let me know (or if I should have fixed the tests first)). This feature is a slight breaking change if anyone was dependent on return nullability, and it also breaks around 30 or so existing tests due to the difference in output SQL.
Based on comments from @smitpatel on the issue we should be able to handle 3 expressions (column/const/param) in the NullSemanticsVisitor and appropriately coalesce these so we can better emulate expected C# functionality
> #3836 - Coalescing string concatenation on nullable Expressions

- src/EFCore/Query/Internal/ExpressionEqualityComparer.cs
Resolves #18685
Resolves #10529
Resolves #17959
> Query: Clean up in ExpressionEqualityComparer

- src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
> Query: Cast result of IndexOf appropriately for SqlServer

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Minor code change to fix translation of `x.Foo as Bar`. 
There were 2 different exceptions here - either KeyNotFound when the **as** was inside an aggregate like **Sum**, or a ClientEvaluation when the **as** as inside a a **Where** clause. With tests covering both of these, the 3'rd test covers the exact repro that was reported in issue #5783
> #5783 - Casting with as causing exceptions

- .github/workflows/TestCosmos.yaml
Leaving the existing testing against a real Azure Cosmos instance for now, although we're happy with GA we could disable that and save some money.
> Add Github Actions Cosmos testing

- src/EFCore.Cosmos/Query/Internal/ContainsTranslator.cs
- src/EFCore.Relational/Query/Internal/ContainsTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
Based on how values are expanded into InExpression values cannot be anything other than SqlConstant/SqlParameter
Resolves #18970
Apply fix for #17342 for cosmos
Also enable Contains tests in Cosmos which were already working
> Query: Translate Contains only when it is a server-side list

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Squad.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
I am creating this PR with the implementation working for SQL Server, with all tests passing. Porting this to Sqlite will be simple, but I wanted to verify my implementation is acceptable.
Rationale here is that, given this is a provider-specific implementation of a unary expression, it becomes necessary to override SqlServer's ExpressionVisitor's `VisitUnary` method to catch `ArrayLength` expressions on `byte[]` columns, and then translate it as a `SqlFunctionExpression` which maps to an int.
Concerns - 
* Rationale is correct, yes? We want to capture and visit the unary expression before passing it to the base class because this is sql-specific
* May not need to check the CLR type of byte[], since, I think, binary columns are the only way to get an array (and therefore arraylength) type …
> Query Fix for #13487 Translate byte[].Length for SqlServer & Sqlite

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindSelectQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
Resolves #17388
In order to translate Reverse, we reverse the existing ordering. If there is no existing ordering then we throw translation failure.
> Query: Translate Queryable.Reverse()

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Fixes #12590
Fixes #18982
Regression test for #16546
> Prevent dependents from being deleted when principal is deleted

- src/EFCore/Internal/LazyLoader.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
Fixes #13138
(Note that it's harder to hit this in 3+ because field mapping is the default.)
> Avoid stack overflow when lazy loading

- src/EFCore.SqlServer/Query/Internal/SqlServerQueryStringFactory.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryStringFactory.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindWhereQuerySqliteTest.cs
Part of #6482
See also https://github.com/aspnet/EntityFrameworkCore/pull/19368#issuecomment-567692210 and https://github.com/aspnet/EntityFrameworkCore/pull/19368#issuecomment-568606361
> Use SQLite CLI parameter syntax for SQLite query string

- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/DbContextOptionsBuilder`.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Internal/ServiceProviderCache.cs
- test/EFCore.Specification.Tests/InterceptionTestBase.cs
- test/EFCore.Tests/DbContextServicesTest.cs
> Support replacement of services that allow multiple registrations
