dotnet/efcore

test/EntityFramework.Microbenchmarks.Core/PerfTestRunner.cs

Adding a results.csv file that all perf results are written to
This makes it easy to load up all results in Excel etc. for analysis

Adding CSV file for perf results

---

src/EntityFramework.Commands/Utilities/ForwardingProxy.cs
test/EntityFramework.Commands.FunctionalTests/EntityFramework.Commands.FunctionalTests.csproj
test/EntityFramework.Commands.FunctionalTests/ExecutorTest.cs
test/EntityFramework.Commands.FunctionalTests/Utilities/ForwardingProxyTest.cs
test/EntityFramework.Commands.FunctionalTests/project.json
test/EntityFramework.SqlServer.FunctionalTests/SqlServerTestStore.cs

I found these in an old branch...

Commands: Add more functional tests

---

src/EntityFramework.Core/DbContext.cs

Refactor to keep existing null checks and increase code reuse at the expense of readonly fields.
//cc @divega

Simple refactoring of DbContext constructors

---

src/EntityFramework.Commands/Program.cs

Adding the ability to specify subcommands in the print help command
Fix for #980

Fixing ef migration add help. 

---

src/EntityFramework.Relational/Migrations/Infrastructure/Migrator.cs
src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx
src/EntityFramework.Relational/Query/CommandBuilder.cs
src/EntityFramework.Relational/RelationalConnection.cs
src/EntityFramework.Relational/RelationalDatabase.cs
src/EntityFramework.Relational/RelationalDbContextOptions.cs
src/EntityFramework.Relational/RelationalOptionsExtension.cs
src/EntityFramework.Relational/SqlStatementExecutor.cs
src/EntityFramework.Relational/Update/ReaderModificationCommandBatch.cs
src/EntityFramework.SqlServer/Extensions/SqlServerDbContextOptions.cs
src/EntityFramework.SqlServer/SqlServerConnection.cs
src/EntityFramework.SqlServer/SqlServerDataStoreCreator.cs
src/EntityFramework.SqlServer/SqlServerSequenceValueGenerator.cs
src/EntityFramework.SqlServer/Update/SqlServerModificationCommandBatchFactory.cs
test/EntityFramework.Relational.Tests/RelationalDataStoreTest.cs
test/EntityFramework.Relational.Tests/TestHelperExtensions.cs
test/EntityFramework.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
test/EntityFramework.SqlServer.FunctionalTests/CommandConfigurationTests.cs
test/EntityFramework.SqlServer.FunctionalTests/EntityFramework.SqlServer.FunctionalTests.csproj
test/EntityFramework.SqlServer.Tests/CommandConfigurationTests.cs
test/EntityFramework.SqlServer.Tests/EntityFramework.SqlServer.Tests.csproj
test/EntityFramework.SqlServer.Tests/SqlServerDataStoreCreatorTest.cs
test/EntityFramework.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs

Enabling Command Timeout to be specified for Relational Datasources

---

src/EntityFramework.Core/Metadata/ModelBuilder.cs
test/EntityFramework.Core.Tests/Metadata/MetadataBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/NonGenericRelationshipBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/StringRelationshipBuilderTest.cs

See design meeting notes: https://github.com/aspnet/EntityFramework/wiki/Design-Meeting-Notes:-January-15,-2015

Remove ForeignKey API from convention model builder (Issue #782)

---

makefile.shade

Builds correctly with VS 2015 (CTP edition) & Sql Server 2012 (SP2)

[Tiny] Switch to MSBuild of VS 2015

---

test/EntityFramework.SqlServer.FunctionalTests/SqlServerTestStore.cs

Use DOTNET_APPBASE instead of K_APPBASE

---

build.cmd
makefile.shade
tools/EntityFramework.targets

- Change default packages path
- Change KRE to DOTNET
@davidfowl @divega

React to runtime renaming

---

src/EntityFramework.Commands/tools/EntityFramework.psm1

Added flag to migrations commands to specify startup project

---

src/EntityFramework.Core/Metadata/EntityType.cs
test/EntityFramework.Commands.Tests/Migrations/CSharpModelCodeGeneratorTest.cs
test/EntityFramework.Core.Tests/Metadata/BasicModelBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/EntityTypeTest.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationOperationFactoryTest.cs

Adding total order to address #1314 and fixing tests broken by this change.
@AndriySvyryd @bricelam @lajones

Added absolute order to EntityType Keys, Foreign Keys, Indexes, and Navigations

---

src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/EntityFramework.Core.csproj

Not commenting collection overloads of Add/Update/Attach/Remove just yet as the APIs are about to change

API docs for DbContext

---

src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/DbSet`.cs
src/EntityFramework.Core/Internal/InternalDbSet.cs
test/EntityFramework.Core.FunctionalTests/BuiltInDataTypesFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/GraphUpdatesTestBase.cs
test/EntityFramework.Core.FunctionalTests/OneToOneQueryFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/TestModels/ComplexNavigationsModel/ComplexNavigationsModelInitializer.cs
test/EntityFramework.Core.FunctionalTests/TestModels/ConcurrencyModel/ConcurrencyModelInitializer.cs
test/EntityFramework.Core.FunctionalTests/TestModels/Northwind/NorthwindData.cs
test/EntityFramework.Core.Tests/DbContextTest.cs
test/EntityFramework.Core.Tests/DbSetTest.cs
test/EntityFramework.Core.Tests/EntitySetFinderTest.cs
test/EntityFramework.CrossStore.FunctionalTests/EndToEndTest.cs
test/EntityFramework.CrossStore.FunctionalTests/TestModels/CrossStoreContext.cs
test/EntityFramework.InMemory.FunctionalTests/CompositeKeyEndToEndTest.cs
test/EntityFramework.InMemory.FunctionalTests/InMemoryConfigPatternsTest.cs
test/EntityFramework.InMemory.FunctionalTests/MusicStoreQueryTests.cs
test/EntityFramework.InMemory.Tests/InMemoryDataStoreCreatorTest.cs
test/EntityFramework.Microbenchmarks/ChangeTracker/DbSetOperationTests.cs
test/EntityFramework.Microbenchmarks/Models/Orders/OrdersSeedData.cs
test/EntityFramework.SqlServer.FunctionalTests/CompositeKeyEndToEndTest.cs
test/EntityFramework.SqlServer.FunctionalTests/QueryBugsTest.cs

Also add IEnumerable overload and change return type to void.

Use AddRange, RemoveRange, etc. for multiple entity overloads (Issue #1517)

---

src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/DbContextOptions.cs
src/EntityFramework.Core/DbContextOptions`.cs
src/EntityFramework.Core/DbSet`.cs
src/EntityFramework.Core/EntityServicesBuilder.cs
src/EntityFramework.Core/EntityState.cs

Skipping some of types that will be moved out in the near future

Adding doc comments to remaining public APIs in root namespace

---

src/EntityFramework.Core/Metadata/ForeignKey.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
src/EntityFramework.Core/Metadata/ModelBuilder.cs
src/EntityFramework.Core/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EntityFramework.Core/Metadata/ModelConventions/RelationshipDiscoveryConvention.cs
test/EntityFramework.Core.Tests/Metadata/ForeignKeyTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EntityFramework.SqlServer.FunctionalTests/SqlServerComplexNavigationsQueryTest.cs

Allow configuring FK nullability before the foreign key or the referenced key.

---

src/EntityFramework.Core/ChangeTracking/KeyValueEntityAttacher.cs
src/EntityFramework.Core/ChangeTracking/StateEntry.cs
src/EntityFramework.Core/DbContext.cs
test/EntityFramework.Core.FunctionalTests/ChangeTrackingTestBase.cs

This adds a code path to attach entities and update saved values to the current values

Issue #1385 Attach should not reject changes

---

src/EntityFramework.Core/Metadata/ForeignKey.cs
src/EntityFramework.Core/Metadata/IForeignKey.cs

Don't derive IForeignKey from IKey

---

src/EntityFramework.Core/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConvention.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EntityFramework.SqlServer.FunctionalTests/DefaultValuesTest.cs

Make FK convention not match the PK properties for self referencing relationships

---

src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/IQueryBuffer.cs
src/EntityFramework.Core/Query/QueryBuffer.cs
src/EntityFramework.InMemory/Query/InMemoryQueryModelVisitor.cs
src/EntityFramework.Relational/Query/AsyncQueryMethodProvider.cs
src/EntityFramework.Relational/Query/ExpressionTreeVisitors/IncludeExpressionTreeVisitor.cs
src/EntityFramework.Relational/Query/QueryMethodProvider.cs
src/EntityFramework.Relational/Query/RelationalQueryModelVisitor.cs
test/EntityFramework.Core.FunctionalTests/IncludeAsyncTestBase.cs
test/EntityFramework.Core.FunctionalTests/IncludeTestBase.cs

Flowing AsNoTracking information to include command

Issue #1402 NoTracking query with Include fixes up existing dependants

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
src/EntityFramework.Core/Utilities/BidirectionalAdjacencyListGraph.cs
src/EntityFramework.Core/Utilities/Multigraph.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
test/EntityFramework.Core.Tests/EntityFramework.Core.Tests.csproj
test/EntityFramework.Core.Tests/Utilities/MultigraphTest.cs
test/EntityFramework.Relational.Tests/EntityFramework.Relational.Tests.csproj
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTest.cs

This is part of the fix for #1453. It does not improve the error messages, but with cycle breaking a verbose cycle message may not be necessary
@bricelam @maumar

Add Multigraph with topological sort and cycle breaking

---

src/EntityFramework.Commands/Migrations/CSharpMigrationOperationGenerator.cs
src/EntityFramework.Relational/Migrations/Builders/TableBuilder.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
src/EntityFramework.Relational/Migrations/Operations/CreateTableOperation.cs
src/EntityFramework.Relational/Migrations/Sql/MigrationSqlGenerator.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationSqlGenerator.cs
test/EntityFramework.Relational.Tests/EntityFramework.Relational.Tests.csproj
test/EntityFramework.Relational.Tests/Migrations/Sql/MigrationSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Migrations/Sql/MigrationSqlGeneratorTestBase.cs
test/EntityFramework.SqlServer.Tests/EntityFramework.SqlServer.Tests.csproj
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

@anpete any feedback on the generated DDL (either format or syntax)?

Test MigrationSqlGenerator

---

src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx

Improve message for concurrency exception

---

src/EntityFramework.Relational/Migrations/History/IHistoryRepository.cs
src/EntityFramework.Relational/Migrations/Infrastructure/MigrationIdGenerator.cs
src/EntityFramework.Relational/Migrations/Migrator.cs
src/EntityFramework.Relational/Migrations/Sql/IMigrationSqlGenerator.cs
src/EntityFramework.Relational/Migrations/Sql/MigrationSqlGenerator.cs
src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx
src/EntityFramework.SqlServer/Migrations/SqlServerHistoryRepository.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationSqlGenerator.cs
test/EntityFramework.Relational.Tests/EntityFramework.Relational.Tests.csproj
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/MigrationIdGeneratorTest.cs
test/EntityFramework.SqlServer.Tests/EntityFramework.SqlServer.Tests.csproj
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs

Resolves #1280 & resolves #1281

Implement Script-Migration

---

src/EntityFramework.Commands/DatabaseTool.cs
src/EntityFramework.Commands/MigrationTool.cs
src/EntityFramework.Commands/Migrations/MigrationScaffolder.cs
src/EntityFramework.Commands/Utilities/CommandLogger.cs
src/EntityFramework.Commands/Utilities/LoggerProvider.cs
src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/Infrastructure/Database.cs
src/EntityFramework.Core/Infrastructure/LoggingModelValidator.cs
src/EntityFramework.Core/Query/AsyncLinqOperatorProvider.cs
src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/LinqOperatorProvider.cs
src/EntityFramework.Core/Query/QueryContextFactory.cs
src/EntityFramework.Core/Storage/DataStore.cs
src/EntityFramework.InMemory/InMemoryDatabase.cs
src/EntityFramework.Relational/RelationalConnection.cs
src/EntityFramework.Relational/RelationalLoggerExtensions.cs
src/EntityFramework.Relational/SqlStatementExecutor.cs
src/EntityFramework.Relational/Update/BatchExecutor.cs
src/EntityFramework.SqlServer.Design/ReverseEngineering/SqlServerEntityTypeCodeGenerator.cs
src/EntityFramework.SqlServer.Design/ReverseEngineering/SqlServerMetadataModelProvider.cs
src/EntityFramework.SqlServer.Design/Utilities/SqlServerLiteralUtilities.cs
src/Shared/LoggingExtensions.cs
test/EntityFramework.Core.FunctionalTests/DataStoreErrorLogStateTest.cs
test/EntityFramework.Core.FunctionalTests/TestFileLogger.cs
test/EntityFramework.Core.Tests/DbContextTest.cs
test/EntityFramework.Core.Tests/TestUtilities/ListLogger.cs
test/EntityFramework.Core.Tests/TestUtilities/ListLoggerFactory.cs
test/EntityFramework.InMemory.Tests/InMemoryDataStoreTest.cs
test/EntityFramework.Relational.FunctionalTests/TestSqlLoggerFactory.cs
test/EntityFramework.SqlServer.FunctionalTests/CommandConfigurationTests.cs

@bricelam 
Need to wait for logging to be pushed

Logging API changes

---

src/EntityFramework.Core/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EntityFramework.Core/Query/CompiledQueryCache.cs
src/EntityFramework.Core/project.json

Dependent on https://github.com/aspnet/Caching/pull/49/files

React to Caching package rename

---

src/EntityFramework.Core/ChangeTracking/Internal/EntityEntryMetadataServices.cs
src/EntityFramework.Core/ChangeTracking/Internal/IEntityEntryMetadataServices.cs
src/EntityFramework.Core/ChangeTracking/Internal/InternalEntityEntry.cs
src/EntityFramework.Core/ChangeTracking/Internal/InternalMixedEntityEntry.cs
src/EntityFramework.Core/ChangeTracking/Internal/InternalShadowEntityEntry.cs

Use generic ReadValue when reading shadow properties

---

test/EntityFramework.Core.FunctionalTests/EntityFramework.Core.FunctionalTests.csproj
test/EntityFramework.Core.FunctionalTests/NullSemanticsQueryFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/NullSemanticsQueryTestBase.cs
test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsContext.cs
test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsData.cs
test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsEntity1.cs
test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsEntity2.cs
test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsEntityBase.cs
test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsModelInitializer.cs
test/EntityFramework.Relational.FunctionalTests/EntityFramework.Relational.FunctionalTests.csproj
test/EntityFramework.Relational.FunctionalTests/NullSemanticsQueryRelationalFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/EntityFramework.SqlServer.FunctionalTests.csproj
test/EntityFramework.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs

Tests are disabled, since the functionality is not there yet.

Adding test infrastructure and tests for null semantics. 

---

src/EntityFramework.Commands/Program.cs

fixing up help

---

src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Query/Expressions/LongCountExpression.cs
src/EntityFramework.Relational/Query/RelationalResultOperatorHandler.cs
src/EntityFramework.Relational/Query/Sql/DefaultSqlQueryGenerator.cs
src/EntityFramework.Relational/Query/Sql/ISqlExpressionVisitor.cs
test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Adding sql gen for LongCount

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Metadata/Internal/InternalModelBuilder.cs
src/EntityFramework.Core/Metadata/ModelConventions/ConventionDispatcher.cs
src/EntityFramework.Core/Metadata/ModelConventions/ConventionSet.cs
src/EntityFramework.Core/Metadata/ModelConventions/IModelConvention.cs
src/EntityFramework.Core/ModelBuilder.cs
src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerValueGenerationStrategyConvention.cs
src/EntityFramework.SqlServer/Metadata/ReadOnlySqlServerPropertyExtensions.cs
src/EntityFramework.SqlServer/SqlServerModelBuilderFactory.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ConventionDispatcherTest.cs
test/EntityFramework.SqlServer.FunctionalTests/BatchingTest.cs
test/EntityFramework.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/CommandConfigurationTests.cs
test/EntityFramework.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/F1SqlServerFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/NullKeysSqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerFixture.cs
test/EntityFramework.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
test/EntityFramework.SqlServer.FunctionalTests/TransactionSqlServerFixture.cs
test/EntityFramework.SqlServer.Tests/Metadata/ModelConventions/SqlServerValueGenerationStrategyConventionTest.cs

Resolves #1811 
Add Model Conventions support
Set Sequence as default value generator for SqlServer by convention

Sequence as default value generator for SqlServer

---

src/EntityFramework.Core/Infrastructure/DbContextOptions.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx
src/EntityFramework.Relational/RelationalConnection.cs
src/EntityFramework.Relational/RelationalOptionsExtension.cs
src/EntityFramework.Relational/SqlStatementExecutor.cs
src/EntityFramework.Relational/project.json
src/EntityFramework.SqlServer/Extensions/SqlServerDbContextOptions.cs
test/EntityFramework.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs

Throw when System.Transactions.Transaction.Current is set

---

src/EntityFramework.SqlServer/Update/SqlServerModificationCommandBatch.cs
test/EntityFramework.SqlServer.FunctionalTests/BatchingTest.cs
test/EntityFramework.SqlServer.FunctionalTests/ConnectionSpecificationTest.cs
test/EntityFramework.SqlServer.FunctionalTests/DefaultValuesTest.cs
test/EntityFramework.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs

Split insert statements for SQL Server if the number of values read/written is different.

---

test/EntityFramework.SqlServer.FunctionalTests/QueryBugsTest.cs

Will investigate and fix, but disabling for now so that build passes

disabling tests that randomly fail

---

src/EntityFramework.Core/ChangeTracking/ChangeTracker.cs
src/EntityFramework.Core/ChangeTracking/Internal/IStateManager.cs
src/EntityFramework.Core/ChangeTracking/Internal/StateManager.cs
src/EntityFramework.Core/ChangeTracking/PropertyEntry.cs
src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/DbSet`.cs
src/EntityFramework.Core/Metadata/Builders/PropertyBuilder.cs
src/EntityFramework.Core/Metadata/Builders/PropertyBuilder`.cs
test/EntityFramework.Core.Tests/ChangeTracking/Internal/StateManagerTest.cs
test/EntityFramework.Core.Tests/DbContextTest.cs
test/EntityFramework.Relational.FunctionalTests/TransactionTestBase.cs

Add a way to accept all changes after multiple successful SaveChanges.

---

src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
test/EntityFramework.Core.Tests/Metadata/EntityTypeTest.cs

Additional test coverage and corrections/improvements to the exceptions for duplicate properties for issue #1890
@rowanmiller @anpete

EntityType AddProperty checking inherited property names

---

src/EntityFramework.Core/project.json
src/EntityFramework.InMemory/project.json
src/EntityFramework.Relational/project.json

This depends on aspnet/Caching#53

Target netcore451 (Resolves #1952)

---

src/EntityFramework.Core/ChangeTracking/Internal/KeyPropagator.cs
src/EntityFramework.Core/ChangeTracking/Internal/NavigationFixer.cs
src/EntityFramework.Core/Metadata/Builders/ReferenceNavigationBuilder.cs
src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Core/Metadata/ForeignKey.cs
src/EntityFramework.Core/Metadata/ForeignKeyExtensions.cs
src/EntityFramework.Core/Metadata/IForeignKey.cs
src/EntityFramework.Core/Metadata/INavigation.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
src/EntityFramework.Core/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EntityFramework.Core/Metadata/Navigation.cs
src/EntityFramework.Core/Metadata/NavigationExtensions.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/QueryBuffer.cs
src/EntityFramework.Core/Utilities/ModelNavigationsGraphAdapter.cs
src/EntityFramework.Relational/Query/ExpressionTreeVisitors/IncludeExpressionTreeVisitor.cs
test/EntityFramework.Core.Tests/Metadata/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/ForeignKeyTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/RelationshipDiscoveryConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/NavigationTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest.cs

And make PointsToPrincipal an extension method.

API review changes: make Navigations first class on ForeignKey

---

src/EntityFramework.Relational/Metadata/RelationalForeignKeyBuilder.cs
src/EntityFramework.Relational/Metadata/RelationalForeignKeyExtensions.cs
src/EntityFramework.Relational/Metadata/RelationalIndexBuilder.cs
src/EntityFramework.Relational/Metadata/RelationalIndexExtensions.cs
src/EntityFramework.Relational/Metadata/RelationalKeyBuilder.cs
src/EntityFramework.Relational/Metadata/RelationalKeyExtensions.cs
src/EntityFramework.Relational/Metadata/RelationalModelBuilder.cs
src/EntityFramework.Relational/Metadata/RelationalModelExtensions.cs
src/EntityFramework.Relational/Metadata/RelationalPropertyBuilder.cs
src/EntityFramework.Relational/Metadata/RelationalPropertyExtensions.cs
src/EntityFramework.Relational/Metadata/Sequence.cs
src/EntityFramework.Relational/RelationalTypeMapping.cs
src/EntityFramework.SqlServer/Metadata/ModelConventions/SqlServerValueGenerationStrategyConvention.cs
src/EntityFramework.SqlServer/Metadata/SqlServerEntityTypeExtensions.cs
src/EntityFramework.SqlServer/Metadata/SqlServerForeignKeyBuilder.cs
src/EntityFramework.SqlServer/Metadata/SqlServerForeignKeyExtensions.cs
src/EntityFramework.SqlServer/Metadata/SqlServerIndexBuilder.cs
src/EntityFramework.SqlServer/Metadata/SqlServerIndexExtensions.cs
src/EntityFramework.SqlServer/Metadata/SqlServerKeyBuilder.cs
src/EntityFramework.SqlServer/Metadata/SqlServerKeyExtensions.cs
src/EntityFramework.SqlServer/Metadata/SqlServerModelBuilder.cs
src/EntityFramework.SqlServer/Metadata/SqlServerModelExtensions.cs
src/EntityFramework.SqlServer/Metadata/SqlServerPropertyBuilder.cs
src/EntityFramework.SqlServer/Metadata/SqlServerPropertyExtensions.cs
src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs
src/EntityFramework.SqlServer/Update/SqlServerModificationCommandBatch.cs
test/EntityFramework.SqlServer.Tests/Metadata/ModelConventions/SqlServerValueGenerationStrategyConventionTest.cs
test/EntityFramework.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs

Resolves #1568 
Also changed few missed nameof

Add DefaultSequence to the model

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Core/Utilities/TypeNameHelper.cs
test/EntityFramework.Core.Tests/EntityFramework.Core.Tests.csproj
test/EntityFramework.Core.Tests/Metadata/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/PropertyTest.cs
test/EntityFramework.Core.Tests/ModelSourceTest.cs
test/EntityFramework.Core.Tests/Utilities/TypeNameHelperTest.cs

Pretty Print Generic EntityType Names

---

src/EntityFramework.SqlServer.Design/ReverseEngineering/Model/Table.cs
src/EntityFramework.SqlServer.Design/ReverseEngineering/Model/TableColumn.cs
src/EntityFramework.SqlServer/Migrations/SqlServerHistoryRepository.cs

Fix for issue 1929 - ignore the MigrationHistory table

Fix for issue 1929 - ignore the MigrationHistory table.

---

src/EntityFramework.Commands/Migrations/CSharpModelGenerator.cs
src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Property.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
test/EntityFramework.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs
test/EntityFramework.Core.FunctionalTests/MonsterFixupTestBase.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/KeyConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/PropertyTest.cs
test/EntityFramework.SqlServer.FunctionalTests/MonsterFixupSqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/QuerySqlServerTest.cs

fixes #1978 
Property which are part of PrimaryKey will be required by default

Make properties which are part of PrimaryKey as required

---

EntityFramework-aspnet.sln
makefile.shade
src/EntityFramework.Commands/MigrationTool.cs
src/EntityFramework.Commands/Migrations/MigrationScaffolder.cs
src/EntityFramework.Commands/Program.cs
src/EntityFramework.Commands/Properties/Strings.Designer.cs
src/EntityFramework.Commands/Properties/Strings.resx
src/EntityFramework.Commands/Utilities/CommandLogger.cs
src/EntityFramework.Commands/tools/EntityFramework.psm1
src/EntityFramework.Commands/tools/about_EntityFramework.help.txt
src/EntityFramework.Commands/tools/install.ps1
src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
src/EntityFramework.Relational/Migrations/Migrator.cs
src/EntityFramework.Relational/Migrations/Operations/DropColumnOperation.cs
src/EntityFramework.Relational/Migrations/Operations/DropTableOperation.cs
src/EntityFramework.Relational/Migrations/Operations/MigrationOperation.cs
src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx
src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs
test/EntityFramework.Core.Tests/EntityFramework.Core.Tests.csproj
test/EntityFramework.Sqlite.Tests/EntityFramework.Sqlite.Tests.xproj
tools/Resources.cs

Changes:
- Less unicorn--only for `ef` & `ef help`, not sub-commands
- Add documentation (resolves #578)
- Log more (resolves #975)
Still on my wishlist:
- Less stacktrace (#1044)

Commands: Improve the user experience

---

src/EntityFramework.Relational/Query/ExpressionTreeVisitors/RelationalEntityQueryableExpressionTreeVisitor.cs
src/EntityFramework.Relational/Query/RelationalQueryModelVisitor.cs
test/EntityFramework.Relational.FunctionalTests/AsyncFromSqlQueryTestBase.cs
test/EntityFramework.Relational.FunctionalTests/AsyncFromSqlSprocQueryTestBase.cs
test/EntityFramework.Relational.FunctionalTests/EntityFramework.Relational.FunctionalTests.csproj
test/EntityFramework.Relational.FunctionalTests/FromSqlQueryTestBase.cs
test/EntityFramework.Relational.FunctionalTests/FromSqlSprocQueryTestBase.cs
test/EntityFramework.Relational.FunctionalTests/NorthwindSprocQueryRelationalFixture.cs
test/EntityFramework.Relational.FunctionalTests/TestModels/NorthwindSproc/CustomerOrderHistory.cs
test/EntityFramework.Relational.FunctionalTests/TestModels/NorthwindSproc/MostExpensiveProduct.cs
test/EntityFramework.SqlServer.FunctionalTests/AsyncFromSqlSprocQuerySqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/EntityFramework.SqlServer.FunctionalTests.csproj
test/EntityFramework.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/FromSqlSprocQuerySqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/NorthwindSprocQuerySqlServerFixture.cs

Fix FromSql composable stored procedure tests and forced client evaluation

---

src/EntityFramework.Core/Metadata/Builders/EntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Builders/EntityTypeBuilder`.cs
src/EntityFramework.Core/ModelBuilder.cs
test/EntityFramework.Core.Tests/ApiConsistencyTest.cs

Enable Fluent_api_methods_should_not_return_void

---

src/EntityFramework.Commands/Migrations/CSharpMigrationGenerator.cs
src/EntityFramework.Commands/Migrations/CSharpModelGenerator.cs
src/EntityFramework.Commands/Migrations/MigrationScaffolder.cs
src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Migrations/Infrastructure/IMigrationModelFactory.cs
src/EntityFramework.Relational/Migrations/Infrastructure/MigrationAssembly.cs
src/EntityFramework.Relational/Migrations/Infrastructure/MigrationModelFactory.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelSnapshot.cs
src/EntityFramework.Relational/Migrations/Migration.cs
src/EntityFramework.Relational/Migrations/Migrator.cs
src/EntityFramework.Relational/RelationalEntityServicesBuilderExtensions.cs
test/EntityFramework.Commands.FunctionalTests/EntityFramework.Commands.FunctionalTests.csproj
test/EntityFramework.Commands.FunctionalTests/ExecutorTest.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/CodeCompilationTest.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/OperationCompilationTest.cs
test/EntityFramework.Commands.FunctionalTests/TestUtilities/BuildSource.cs
test/EntityFramework.SqlServer.FunctionalTests/SqlServerMigrationsTest.cs

Resolves #2128
Verification: Tests & manual bashing

Migrations: Change Migration.Target & ModelSnapshot.Model to methods

---

test/EntityFramework.Relational.FunctionalTests/MappingQueryFixtureBase.cs
test/EntityFramework.Sqlite.FunctionalTests/AsyncFromSqlQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/AsyncQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/BuiltInDataTypesSqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/ComplexNavigationsQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/EntityFramework.Sqlite.FunctionalTests.csproj
test/EntityFramework.Sqlite.FunctionalTests/FromSqlQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/GearsOfWarQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/GearsOfWarQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/InheritanceSqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/InheritanceSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/MappingQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/MappingQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/NorthwindQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/NullSemanticsQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/NullSemanticsQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/OneToOneQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/QuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/SqliteTestStore.cs
test/EntityFramework.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/packages.config

Exercise more of that SQLite provider :muscle:. Only adds code to testing.

Add more functional testing for SQLite

---

src/EntityFramework.Commands/Migrations/CSharpModelGenerator.cs
src/EntityFramework.Core/Metadata/CoreAnnotationNames.cs
src/EntityFramework.Core/Metadata/PropertyExtensions.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs

Blacklist core annotations from ModelSnapshot

---

src/EntityFramework.Core/Query/CompiledQueryCache.cs

@Tratcher @anpete 
There is no `GetOrSet` api anymore.

React to Caching api review changes

---

test/EntityFramework.Core.FunctionalTests/project.json
test/EntityFramework.Core.Tests/project.json
test/EntityFramework.InMemory.FunctionalTests/project.json
test/EntityFramework.Relational.FunctionalTests/project.json
test/EntityFramework.SqlServer.FunctionalTests/project.json
test/EntityFramework.Sqlite.FunctionalTests/project.json

Version Core and Relational functional tests

---

test/EntityFramework.Microbenchmarks.Core/TestConfig.cs

- may not completely unblock build but moves it much further along

React to aspnet/Configuration#194

---

src/EntityFramework.SqlServer/Migrations/SqlServerHistoryRepository.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs

Clean up SQL, fixes issue #2190

---

src/EntityFramework.Commands/Migrations/MigrationScaffolder.cs
src/EntityFramework.Core/project.json
src/EntityFramework.Relational/Migrations/Infrastructure/IMigrationAssembly.cs
src/EntityFramework.Relational/Migrations/Infrastructure/MigrationAssembly.cs
src/EntityFramework.Relational/Migrations/Migrator.cs
test/EntityFramework.Commands.Tests/EntityFramework.Commands.Tests.csproj
test/EntityFramework.Commands.Tests/Migrations/MigrationScaffolderTest.cs

Migrations: Reuse existing model snapshot

---

src/EntityFramework.Core/project.json
src/EntityFramework.InMemory/project.json
src/EntityFramework.Relational/project.json
src/EntityFramework.Sqlite/project.json

Depends on aspnet/Caching#69, aspnet/Logging#189 & aspnet/Microsoft.Data.Sqlite#87

dotnet all the things

---

src/EntityFramework.SqlServer/Query/Methods/MathRoundTranslator.cs
test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs
test/EntityFramework.Core.FunctionalTests/TestModels/Northwind/NorthwindData.cs
test/EntityFramework.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Also porting OrderDetail data from Northwind so that the results match our baselines.

[SMALL] Adding tests for the #2069 - Order by Guid.NewGuid() returns same order every time

---

src/EntityFramework.Relational/RelationalLoggerExtensions.cs
test/EntityFramework.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/QuerySqliteTest.cs

Parameter values should be logged using InvariantCulture

---

src/EntityFramework.Commands/ContextTool.cs
src/EntityFramework.Commands/Executor.cs
src/EntityFramework.Commands/MigrationTool.cs
src/EntityFramework.Commands/Migrations/MigrationScaffolder.cs
src/EntityFramework.Commands/Program.cs
src/EntityFramework.Commands/tools/EntityFramework.psm1
test/EntityFramework.Commands.FunctionalTests/TestUtilities/ExecutorWrapper.cs

Resolves #2219 & resolves #2024
Depends on aspnet/Hosting#284
Verification: Manual bashing

Commands: Use startup project to discover services

---

test/EntityFramework.Sqlite.FunctionalTests/EntityFramework.Sqlite.FunctionalTests.csproj
test/EntityFramework.Sqlite.FunctionalTests/IncludeOneToOneSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/SqliteTestStore.cs
test/EntityFramework.Sqlite.FunctionalTests/TransactionSqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/TransactionSqliteTest.cs

Depends on https://github.com/aspnet/Microsoft.Data.Sqlite/pull/84 for the transaction tests to work correctly.
TODO: DbConnection is not always disposed correctly--> test *.db files are left behind.

More SQLite testing

---

NuGet.Config
test/EntityFramework.Commands.FunctionalTests/ExecutorTest.cs

Fixing Commands functional tests on Windows 8.1

---

src/EntityFramework.Core/Metadata/Builders/EntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Builders/EntityTypeBuilder`.cs
test/EntityFramework.Core.Tests/ModelBuilderTest.cs

Add support for alternate keys

---

NuGet.Config
test/EntityFramework.Commands.FunctionalTests/project.json
test/EntityFramework.Commands.Tests/project.json
test/EntityFramework.Core.FunctionalTests/project.json
test/EntityFramework.Core.Tests/project.json
test/EntityFramework.CrossStore.FunctionalTests/project.json
test/EntityFramework.InMemory.FunctionalTests/project.json
test/EntityFramework.InMemory.Tests/project.json
test/EntityFramework.Microbenchmarks.Core/project.json
test/EntityFramework.Microbenchmarks.EF6/project.json
test/EntityFramework.Microbenchmarks/project.json
test/EntityFramework.Relational.Design.Tests/project.json
test/EntityFramework.Relational.Tests/project.json
test/EntityFramework.SqlServer.Design.Tests/project.json
test/EntityFramework.SqlServer.FunctionalTests/project.json
test/EntityFramework.SqlServer.Tests/project.json
test/EntityFramework.Sqlite.FunctionalTests/project.json
test/EntityFramework.Sqlite.Tests/project.json

Note, this uses the nightly builds of xUnit.net 2.1

Update xUnit.net packages

---

src/EntityFramework.Core/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EntityFramework.Core/Infrastructure/IModelSource.cs
src/EntityFramework.Core/Internal/DbContextServices.cs
src/EntityFramework.Core/Internal/ModelSource.cs
src/EntityFramework.Core/Storage/DataStoreServices.cs
src/EntityFramework.Core/Storage/IDataStoreServices.cs
src/EntityFramework.InMemory/InMemoryModelSource.cs
src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx
src/EntityFramework.Relational/RelationalDataStoreServices.cs
src/EntityFramework.Relational/RelationalEntityServicesBuilderExtensions.cs
src/EntityFramework.Relational/RelationalModelValidator.cs
src/EntityFramework.SqlServer/SqlServerModelSource.cs
src/EntityFramework.Sqlite/SqliteModelSource.cs
test/EntityFramework.Core.FunctionalTests/FixupTest.cs
test/EntityFramework.Core.FunctionalTests/ModelSourceTest.cs
test/EntityFramework.Core.FunctionalTests/TestModelSource.cs
test/EntityFramework.Core.Tests/DbContextTest.cs
test/EntityFramework.Core.Tests/Infrastructure/ModelValidatorTest.cs
test/EntityFramework.Core.Tests/ModelSourceTest.cs
test/EntityFramework.InMemory.FunctionalTests/TestInMemoryModelSource.cs
test/EntityFramework.Relational.Tests/EntityFramework.Relational.Tests.csproj
test/EntityFramework.Relational.Tests/RelationalModelValidatorTest.cs
test/EntityFramework.SqlServer.FunctionalTests/TestSqlServerModelSource.cs
test/EntityFramework.Sqlite.FunctionalTests/TestSqliteModelSource.cs

Add validation for distinct table names

---

src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
test/EntityFramework.Relational.FunctionalTests/AsyncFromSqlQueryTestBase.cs
test/EntityFramework.Relational.FunctionalTests/FromSqlQueryTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/FromSqlQuerySqliteTest.cs

Fix #2309 multiple FromSql call parameter name collision

---

src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/ExpressionVisitors/MemberAccessBindingExpressionVisitor.cs
src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Query/ExpressionVisitors/IncludeExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/QueryFlatteningExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/ResultTransformingExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/ShapedQueryFindingExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
src/EntityFramework.Relational/Query/Expressions/SelectExpression.cs
src/EntityFramework.Relational/Query/Expressions/TableExpressionBase.cs
src/EntityFramework.Relational/Query/RelationalQueryCompilationContext.cs
src/EntityFramework.Relational/Query/RelationalQueryModelVisitor.cs
src/EntityFramework.Relational/Query/RelationalResultOperatorHandler.cs
test/EntityFramework.Core.FunctionalTests/AsyncQueryTestBase.cs
test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
test/EntityFramework.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/IncludeSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/QuerySqliteTest.cs

Lift subqueries in MainFromClauses.

Query: Relational: First round of subquery lifting. 

---

src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
src/EntityFramework.Relational/Migrations/Operations/RenameSequenceOperation.cs
src/EntityFramework.Relational/Migrations/Operations/RenameTableOperation.cs
src/EntityFramework.SqlServer/Migrations/SqlServerModelDiffer.cs
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTest.cs
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTestBase.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

Still need to test...
* Renames with related constraints
* Matching
* Structural
* Conflicting

Test ModelDiffer

---

src/EntityFramework.Core/Internal/ModelValidator.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
test/EntityFramework.Core.Tests/Infrastructure/ModelValidatorTest.cs

Disable shadow state entity

---

src/EntityFramework.Commands/Program.cs

Reacting to aspnet/dnx#1116, which removes an named argument.
This should fix CI build.

Remove 'help' subcommand from command-line tool

---

src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDifferContext.cs
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTest.cs

Migrations: Test renames

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Internal/ModelSource.cs
src/EntityFramework.Core/Metadata/CoreAnnotationNames.cs
src/EntityFramework.Core/Properties/AssemblyInfo.cs
test/EntityFramework.Core.Tests/ModelSourceTest.cs

Include EF version in model

---

src/EntityFramework.Commands/Utilities/CSharpHelper.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDifferContext.cs
src/EntityFramework.Relational/Migrations/Sql/MigrationSqlGenerator.cs
src/EntityFramework.SqlServer/Migrations/SqlServerHistoryRepository.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationSqlGenerator.cs
test/EntityFramework.Commands.Tests/Utilities/CSharpHelperTest.cs
test/EntityFramework.Core.Tests/Utilities/TypeExtensionsTest.cs
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTest.cs
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTestBase.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

Migrations: Topologically sort DropTable operations

---

src/EntityFramework.Sqlite/EntityFramework.Sqlite.csproj
src/EntityFramework.Sqlite/SqliteDatabaseConnection.cs
src/EntityFramework.Sqlite/SqliteDbContextOptionsBuilder.cs
src/EntityFramework.Sqlite/SqliteDbContextOptionsBuilderExtensions.cs
src/EntityFramework.Sqlite/SqliteOptionsExtension.cs
test/EntityFramework.Sqlite.FunctionalTests/EntityFramework.Sqlite.FunctionalTests.csproj
test/EntityFramework.Sqlite.FunctionalTests/ForeignKeyTest.cs
test/EntityFramework.Sqlite.Tests/Extensions/SqliteDbContextOptionsBuilderExtensionsTest.cs

Always calls `PRAMGA foreign_keys = ON;` after opening a new connection.

[SQLite] Always use foreign keys

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/DatabaseGeneratedAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/EntityTypeAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/KeyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/MaxLengthAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/NotMappedEntityTypeAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/PropertyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/RequiredAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/StringLengthAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/TimestampAttributeConvention.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
src/EntityFramework.Relational/Metadata/Conventions/Internal/RelationalColumnAttributeConvention.cs
src/EntityFramework.Relational/Metadata/Conventions/Internal/RelationalTableAttributeConvention.cs
test/EntityFramework.Core.FunctionalTests/DataAnnotationFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/DataAnnotationTestBase.cs
test/EntityFramework.Core.Tests/EntityFramework.Core.Tests.csproj
test/EntityFramework.Core.Tests/Metadata/ModelConventions/EntityTypeAttributeConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/PropertyAttributeConventionTest.cs
test/EntityFramework.InMemory.FunctionalTests/DataAnnotationInMemoryTest.cs
test/EntityFramework.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs

part of #107 
Implements
NotMappedAttribute
MaxLengthAttribute
StringLengthAttribute
TimestampAttribute

More DataAnnotations

---

src/EntityFramework.Relational/Extensions/RelationalLoggerExtensions.cs

Made Logger extensions public

---

src/EntityFramework.Commands/tools/EntityFramework.psm1

Attempt to make PMC work with updated Reverse-Engineer command

---

src/EntityFramework.Commands/tools/EntityFramework.psm1

Improve Reverse-Engineer command tab expansion for installed packages

---

src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Metadata/RelationalEntityTypeExtensions.cs
src/EntityFramework.Relational/Metadata/RelationalModelExtensions.cs
src/EntityFramework.Relational/Metadata/RelationalPropertyExtensions.cs
src/EntityFramework.Relational/Migrations/Infrastructure/ModelDiffer.cs
test/EntityFramework.Relational.Tests/Migrations/Infrastructure/ModelDifferTest.cs

Migrations: Implement inheritance

---

src/EntityFramework.Core/Metadata/Builders/CollectionNavigationBuilder.cs
src/EntityFramework.Core/Metadata/Builders/EntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Builders/ReferenceCollectionBuilder.cs
src/EntityFramework.Core/Metadata/Builders/ReferenceNavigationBuilder.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Core/Metadata/EntityTypeExtensions.cs
src/EntityFramework.Core/Metadata/ForeignKey.cs
src/EntityFramework.Core/Metadata/ForeignKeyExtensions.cs
src/EntityFramework.Core/Metadata/IEntityType.cs
src/EntityFramework.Core/Metadata/Internal/EntityMaterializerSource.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalPropertyBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
src/EntityFramework.Core/Metadata/NavigationExtensions.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
src/EntityFramework.InMemory/InMemoryStore.cs
src/Shared/SharedTypeExtensions.cs
test/EntityFramework.Core.Tests/Metadata/EntityTypeExtensionsTest.cs
test/EntityFramework.Core.Tests/Metadata/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/ForeignKeyTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalModelBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/NavigationTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToOneTestBase.cs

Make InternalRelationshipBuilder.Required behave more consistently as to which properties it affects
Remove unused members from EntityType
Add inheritance helper members for ForeignKey

Make EntityType.FindKey account for inheritance

---

src/EntityFramework7.Core/Properties/Strings.Designer.cs
src/EntityFramework7.Core/Properties/Strings.resx
src/EntityFramework7.Core/ValueGeneration/HiLoValueGeneratorState.cs
src/EntityFramework7.Relational/Infrastructure/IUpdateSqlGenerator.cs
src/EntityFramework7.Relational/Infrastructure/UpdateSqlGenerator.cs
src/EntityFramework7.SqlServer/Metadata/SqlServerModelAnnotations.cs
src/EntityFramework7.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
src/EntityFramework7.SqlServer/Properties/Strings.Designer.cs
src/EntityFramework7.SqlServer/Properties/Strings.resx
src/EntityFramework7.SqlServer/ValueGeneration/SqlServerSequenceValueGenerator.cs
src/EntityFramework7.SqlServer/ValueGeneration/SqlServerSequenceValueGeneratorState.cs
src/EntityFramework7.SqlServer/ValueGeneration/SqlServerValueGeneratorCache.cs
src/EntityFramework7.Sqlite/SqliteUpdateSqlGenerator.cs
test/EntityFramework7.Relational.Tests/SqlGeneratorTestBase.cs
test/EntityFramework7.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
test/EntityFramework7.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs

Handle schema names in Sequences correctly

---

src/EntityFramework7.Core/project.json

This should unblock us on UWP.

Update Ix-Async package

---

test/EntityFramework7.Relational.Design.Tests/App.config
test/EntityFramework7.Relational.Design.Tests/EntityFramework7.Relational.Design.Tests.csproj
test/EntityFramework7.SqlServer.Design.FunctionalTests/App.config
test/EntityFramework7.SqlServer.Design.FunctionalTests/EntityFramework7.SqlServer.Design.FunctionalTests.csproj

Same solution as for the other cases of this--app.config with binding redirect.

Fix test projects that are still failing when running tests in VS

---

src/EntityFramework7.Commands/Migrations/CSharpModelGenerator.cs
src/EntityFramework7.Core/Metadata/EntityTypeExtensions.cs
test/EntityFramework7.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs

part of #2597 
Added to release to account for changes of #1704

Include BaseType info in model snapshot

---

src/EntityFramework7.Core/EntityFramework7.Core.csproj
src/EntityFramework7.Core/EntityFrameworkServiceCollectionExtensions.cs
src/EntityFramework7.InMemory/EntityFramework7.InMemory.csproj
src/EntityFramework7.InMemory/InMemoryEntityFrameworkServicesBuilderExtensions.cs
src/EntityFramework7.SqlServer/EntityFramework7.SqlServer.csproj
src/EntityFramework7.SqlServer/SqlServerEntityFrameworkServicesBuilderExtensions.cs
src/EntityFramework7.Sqlite/SqliteEntityFrameworkServicesBuilderExtensions.cs
test/EntityFramework7.Core.FunctionalTests/TestHelpers.cs
test/EntityFramework7.Core.FunctionalTests/TestUtilities/Extensions.cs
test/EntityFramework7.Core.Tests/EntityFramework7.Core.Tests.csproj
test/EntityFramework7.Core.Tests/EntityFrameworkServiceCollectionExtensionsTest.cs
test/EntityFramework7.InMemory.FunctionalTests/EntityFramework7.InMemory.FunctionalTests.csproj
test/EntityFramework7.InMemory.FunctionalTests/InMemoryTestHelpers.cs
test/EntityFramework7.InMemory.Tests/EntityFramework7.InMemory.Tests.csproj
test/EntityFramework7.InMemory.Tests/InMemoryEntityFrameworkServicesBuilderExtensionsTest.cs
test/EntityFramework7.InMemory.Tests/project.json
test/EntityFramework7.Relational.FunctionalTests/EntityFramework7.Relational.FunctionalTests.csproj
test/EntityFramework7.Relational.FunctionalTests/RelationalTestHelpers.cs
test/EntityFramework7.Relational.Tests/EntityFramework7.Relational.Tests.csproj
test/EntityFramework7.Relational.Tests/RelationalEntityFrameworkServicesBuilderExtensionsTest.cs
test/EntityFramework7.Relational.Tests/project.json
test/EntityFramework7.SqlServer.FunctionalTests/EntityFramework7.SqlServer.FunctionalTests.csproj
test/EntityFramework7.SqlServer.Tests/EntityFramework7.SqlServer.Tests.csproj
test/EntityFramework7.SqlServer.Tests/SqlServerEntityFrameworkServicesBuilderExtensionsTest.cs
test/EntityFramework7.SqlServer.Tests/SqlServerTestHelpers.cs
test/EntityFramework7.Sqlite.FunctionalTests/EntityFramework7.Sqlite.FunctionalTests.csproj
test/EntityFramework7.Sqlite.FunctionalTests/SqliteTestHelpers.cs
test/EntityFramework7.Sqlite.Tests/EntityFramework7.Sqlite.Tests.csproj
test/EntityFramework7.Sqlite.Tests/SqliteEntityFrameworkServicesBuilderExtensionsTest.cs
test/EntityFramework7.Sqlite.Tests/project.json

Make AddEntityFramework and AddProvider extensions idempotent
Update TestHelpers classes for DRY service collection registration tests
General DI and csproj/json updates
@bricelam @maumar @ajcvickers

Make AddEntityFramework and AddProvider extensions idempotent

---

src/EntityFramework.Commands/project.json
src/EntityFramework.Relational.Design/project.json

Also adds a missing dependency to it on Commands for the netcore50 framework.
Fixes #2661

Update Microsoft.CodeAnalysis.CSharp package

---

src/EntityFramework.Commands/Migrations/CSharpMigrationGenerator.cs
src/EntityFramework.Commands/Utilities/CSharpHelper.cs
test/EntityFramework.Commands.Tests/Utilities/CSharpHelperTest.cs

[small] Fix to CSharpHelper

---

src/EntityFramework.Sqlite/Metadata/SqliteAnnotationNames.cs
src/EntityFramework.Sqlite/Migrations/SqliteMigrationSqlGenerator.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs

[small] Include constraint name in SQLite create table PK

---

src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/NavigationAttributeConventionTest.cs

Configure relationship uniqueness while setting navigationToDependent

---

src/EntityFramework.Commands/Migrations/CSharpMigrationGenerator.cs
src/EntityFramework.Commands/Migrations/CSharpModelGenerator.cs
src/EntityFramework.Commands/Migrations/MigrationCodeGenerator.cs
src/EntityFramework.Relational/Migrations/Builders/CreateTableBuilder.cs
src/EntityFramework.Relational/Migrations/Builders/OperationBuilder.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationAnnotationProvider.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationSqlGenerator.cs
src/EntityFramework.Sqlite/Migrations/SqliteMigrationSqlGenerator.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/CodeCompilationTest.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

Migrations: Fix annotation issues

---

src/EntityFramework.Commands/Migrations/CSharpModelGenerator.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs

ModelSnapshot: Topologically Sort entityType by hierarchy

---

test/EntityFramework.Relational.FunctionalTests/EntityFramework.Relational.FunctionalTests.csproj
test/EntityFramework.SqlServer.FunctionalTests/EntityFramework.SqlServer.FunctionalTests.csproj

Two test files were missing from the csproj file

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Properties/EntityFramework.Core.rd.xml
src/EntityFramework.Core/project.json
src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Properties/EntityFramework.Relational.rd.xml
src/EntityFramework.Relational/project.json
src/EntityFramework.SqlServer/EntityFramework.SqlServer.csproj
src/EntityFramework.SqlServer/Properties/EntityFramework.SqlServer.rd.xml
src/EntityFramework.SqlServer/project.json
src/EntityFramework.Sqlite/EntityFramework.Sqlite.csproj
src/EntityFramework.Sqlite/Properties/EntityFramework.Sqlite.rd.xml
src/EntityFramework.Sqlite/project.json

These are suboptimal directives, and this doesn't completely solve the #623, but it's a step in the right direction.

Add runtime directives for .NET Native

---

src/EntityFramework.Relational/Migrations/Builders/MigrationBuilder.cs
src/EntityFramework.Relational/Migrations/Sql/MigrationSqlGenerator.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationSqlGenerator.cs
test/EntityFramework.Relational.FunctionalTests/MigrationsTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/EntityFramework.Sqlite.FunctionalTests/MigrationsSqliteTest.cs

SqlServer: Drop default constraints during add/alter column operations

---

makefile.shade
src/EntityFramework.Commands/build/netcore50/EntityFramework.Commands.props
src/EntityFramework.Commands/tools/EntityFramework.psm1

Also fixes #2784 (See TODO in EntityFramework.Commands.props)

NuGet Commands: Build using active configuration's platform

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/NavigationAttributeConventionTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/DataAnnotationsTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Add support for ForeignKeyAttribute

---

src/EntityFramework.Core/Metadata/Conventions/Internal/NavigationAttributeEntityTypeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/NavigationAttributeNavigationConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/PropertyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/RequiredNavigationAttributeConvention.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/NavigationAttributeConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/PropertyAttributeConventionTest.cs

AttributeConventions should run on private properties

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Metadata/Conventions/ConventionSet.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/ConventionDispatcher.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/IBaseTypeConvention.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Internal/RelationalModelValidator.cs
src/EntityFramework.Relational/Metadata/Conventions/Internal/DiscriminatorConvention.cs
src/EntityFramework.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs
src/EntityFramework.Relational/Metadata/RelationalEntityTypeAnnotations.cs
src/EntityFramework.Relational/Properties/Strings.Designer.cs
src/EntityFramework.Relational/Properties/Strings.resx
src/Shared/SharedTypeExtensions.cs
test/EntityFramework.Core.Tests/Infrastructure/ModelValidatorTest.cs
test/EntityFramework.Core.Tests/Metadata/EntityTypeExtensionsTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ConventionDispatcherTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/EntityTypeAttributeConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/PropertyAttributeConventionTest.cs
test/EntityFramework.Relational.FunctionalTests/InheritanceRelationalFixture.cs
test/EntityFramework.Relational.Tests/EntityFramework.Relational.Tests.csproj
test/EntityFramework.Relational.Tests/Metadata/Conventions/Internal/DiscriminatorConventionTest.cs
test/EntityFramework.Relational.Tests/Metadata/RelationalEntityTypeAttributeConventionTest.cs
test/EntityFramework.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
test/EntityFramework.Relational.Tests/Metadata/RelationalPropertyAttributeConventionTest.cs
test/EntityFramework.Relational.Tests/RelationalModelValidatorTest.cs

Add a convention for setting the default discriminator

---

test/EntityFramework.Commands.FunctionalTests/EntityFramework.Commands.FunctionalTests.csproj
test/EntityFramework.Relational.Design.Tests/EntityFramework.Relational.Design.Tests.csproj
test/EntityFramework.SqlServer.Design.FunctionalTests/EntityFramework.SqlServer.Design.FunctionalTests.csproj
test/EntityFramework.Sqlite.Design.FunctionalTests/EntityFramework.Sqlite.Design.FunctionalTests.csproj

Small cleanup

---

src/EntityFramework.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

SQL Server: Don't add IDENTITY to ALTER COLUMN statements

---

src/EntityFramework.Core/project.json

The smallest PR ever

---

src/EntityFramework.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EntityFramework.Relational.Design.Tests/EntityFramework.Relational.Design.Tests.csproj
test/EntityFramework.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

Migrations: Restart sequence when start value changes

---

README.md

cc: @rowanmiller 
Increase the visibility of the article.

Add link to roadmap in the project README

---

src/EntityFramework.Relational/Storage/RelationalDatabaseCreator.cs
src/EntityFramework.SqlServer/SqlServerDatabaseCreator.cs
src/EntityFramework.Sqlite/SqliteDatabaseCreator.cs

Pull Migrations use up into RelationalDatabaseCreator

---

src/EntityFramework.Core/DbSet`.cs
src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
test/EntityFramework.Core.Tests/DbSetTest.cs
test/EntityFramework.Core.Tests/EntityFramework.Core.Tests.csproj
test/EntityFramework.InMemory.Tests/EntityFramework.InMemory.Tests.csproj
test/EntityFramework.InMemory.Tests/InMemoryDatabaseCreatorTest.cs

Block databinding with IListSource

---

src/EntityFramework.Relational.Design/ReverseEngineering/DbContextCodeGeneratorHelper.cs
src/EntityFramework.Relational.Design/ReverseEngineering/RelationalMetadataModelProvider.cs
src/EntityFramework.SqlServer.Design/ReverseEngineering/SqlServerDbContextCodeGeneratorHelper.cs
src/EntityFramework.SqlServer.Design/ReverseEngineering/SqlServerDesignTimeMetadataProviderFactory.cs
src/EntityFramework.SqlServer.Design/ReverseEngineering/SqlServerMetadataModelProvider.cs
src/EntityFramework.Sqlite.Design/EntityFramework.Sqlite.Design.csproj
src/EntityFramework.Sqlite.Design/ReverseEngineering/SqliteDbContextCodeGeneratorHelper.cs

Use nameof for refactor-safe code.
Also fixup on more DI instance

[small] What's in a nameof?

---

makefile.shade

Update compile-tests target to run during compile

---

src/EntityFramework.Core/Internal/IndentedStringBuilder.cs
src/EntityFramework.Relational/Infrastructure/SqlBatchBuilder.cs
src/EntityFramework.Relational/Migrations/MigrationsSqlGenerator.cs
src/EntityFramework.Relational/Storage/Commands/RelationalCommandBuilder.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EntityFramework.SqlServer/Update/SqlServerUpdateSqlGenerator.cs
src/EntityFramework.Sqlite/Migrations/SqliteMigrationsSqlGenerator.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/EntityFramework.SqlServer.Tests/SqlServerSqlGeneratorTest.cs

Migrations: Don't batch commands by default

---

src/EntityFramework.Relational/Query/Expressions/SelectExpression.cs

Pretty much exactly what you suggested @anpete

Temp revert of change to SelectExpression for debug tooltips

---

src/EntityFramework.Relational/Metadata/IRelationalModelAnnotations.cs
src/EntityFramework.Relational/Metadata/RelationalAnnotationNames.cs
src/EntityFramework.Relational/Metadata/RelationalEntityTypeAnnotations.cs
src/EntityFramework.Relational/Metadata/RelationalModelAnnotations.cs
src/EntityFramework.Relational/Metadata/Sequence.cs
src/EntityFramework.Relational/RelationalModelBuilderExtensions.cs
src/EntityFramework.SqlServer/SqlServerModelBuilderExtensions.cs
src/EntityFramework.SqlServer/SqlServerPropertyBuilderExtensions.cs
test/EntityFramework.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
test/EntityFramework.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
test/EntityFramework.Relational.Tests/Metadata/SequenceTest.cs

Support for database schema on model builder

---

src/EntityFramework.SqlServer/project.json

Note, we're also working with the team to ensure it comes back. This commit is just to unblock the build.

Downgrade System.Data.SqlClient package to one that targets dnxcore50

---

test/EntityFramework.Relational.FunctionalTests/FromSqlQueryTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/FromSqlQuerySqliteTest.cs

Cleanup for the FromSql tests
@anpete @natemcmaster

Make FromSql query tests provider-agnostic #2941

---

src/EntityFramework.Relational/Migrations/HistoryRepository.cs
src/EntityFramework.Relational/Migrations/IMigrator.cs
src/EntityFramework.Relational/Migrations/Internal/Migrator.cs
src/EntityFramework.SqlServer/Migrations/SqlServerHistoryRepository.cs
src/EntityFramework.SqlServer/Update/SqlServerUpdateSqlGenerator.cs
test/EntityFramework.Relational.FunctionalTests/MigrationsTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
test/EntityFramework.SqlServer.Tests/SqlServerSqlGeneratorTest.cs
test/EntityFramework.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteHistoryRepositoryTest.cs

Migrations: Fine-tune formatting of generated SQL scripts

---

makefile.shade
src/EntityFramework.Commands/project.json

Note, this will be easier to review [without whitespace changes](https://github.com/aspnet/EntityFramework/pull/2988/files?w=1).

Use new packInclude property in project.json

---

src/EntityFramework.Commands/tools/EntityFramework.psm1

Fixes #2690
Verification: Manual bashing. :hammer:

Commands: Remove project items after Remove-Migration

---

src/EntityFramework.Commands/CommandException.cs
src/EntityFramework.Commands/ContextTool.cs
src/EntityFramework.Commands/DatabaseTool.cs
src/EntityFramework.Commands/EntityFramework.Commands.csproj
src/EntityFramework.Commands/Executor.cs
src/EntityFramework.Commands/Program.cs
src/EntityFramework.Commands/tools/EntityFramework.psm1
test/EntityFramework.Commands.Tests/ExecutorTest.cs

Resolves #1044
Depends on #3022

Commands: Print stack traces by default for unexpected exceptions

---

src/EntityFramework.Core/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
src/EntityFramework.Core/Query/Internal/QueryOptimizer.cs
src/EntityFramework.Relational/Query/Internal/RelationalResultOperatorHandler.cs
src/EntityFramework.Relational/Query/RelationalQueryModelVisitor.cs
test/EntityFramework.Core.FunctionalTests/InheritanceTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/InheritanceSqliteTest.cs

Fix #2220 - Corrected some handling of relational inheritance queries.

---

NuGet.Config
test/EntityFramework.Commands.FunctionalTests/project.json
test/EntityFramework.Commands.Tests/project.json
test/EntityFramework.Core.FunctionalTests/project.json
test/EntityFramework.Core.Tests/project.json
test/EntityFramework.CrossStore.FunctionalTests/project.json
test/EntityFramework.InMemory.FunctionalTests/project.json
test/EntityFramework.InMemory.Tests/project.json
test/EntityFramework.Microbenchmarks.Core/project.json
test/EntityFramework.Microbenchmarks.EF6/project.json
test/EntityFramework.Microbenchmarks/project.json
test/EntityFramework.Relational.Design.FunctionalTests/project.json
test/EntityFramework.Relational.Design.Tests/project.json
test/EntityFramework.Relational.Tests/project.json
test/EntityFramework.SqlServer.Design.FunctionalTests/project.json
test/EntityFramework.SqlServer.Design.Tests/project.json
test/EntityFramework.SqlServer.FunctionalTests/EntityFramework.SqlServer.FunctionalTests.csproj
test/EntityFramework.SqlServer.FunctionalTests/Properties/AssemblyInfo.cs
test/EntityFramework.SqlServer.FunctionalTests/project.json
test/EntityFramework.SqlServer.Tests/project.json
test/EntityFramework.Sqlite.Design.FunctionalTests/project.json
test/EntityFramework.Sqlite.Design.Tests/project.json
test/EntityFramework.Sqlite.FunctionalTests/project.json
test/EntityFramework.Sqlite.Tests/project.json

Depends on aspnet/aspnet.xunit#13

Stop using the xUnit.net nightly builds

---

src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/DbSet`.cs
src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/GraphBehavior.cs
src/EntityFramework.Core/Internal/InternalDbSet.cs
src/EntityFramework.Core/Metadata/DeleteBehavior.cs
src/EntityFramework.Core/Metadata/IForeignKey.cs
test/EntityFramework.Core.FunctionalTests/ChangeTrackingTestBase.cs
test/EntityFramework.Core.FunctionalTests/TestModels/MonsterContext`.cs
test/EntityFramework.Core.Tests/DbContextTest.cs
test/EntityFramework.Core.Tests/DbSetTest.cs

Use enum instead of bool for Add/Attach behavior

---

src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/KeyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/TimestampAttributeConvention.cs
src/EntityFramework.Core/Properties/Strings.Designer.cs
src/EntityFramework.Core/Properties/Strings.resx
test/EntityFramework.Core.Tests/Metadata/ModelConventions/NavigationAttributeConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/PropertyAttributeConventionTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/DataAnnotationsTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Errors and data annotations

---

test/EntityFramework.Relational.FunctionalTests/AsyncFromSqlQueryTestBase.cs
test/EntityFramework.Relational.FunctionalTests/FromSqlQueryTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs

Fix #2941 - Use quoted identifiers in (Async)FromSqlQuery tests.

---

src/EntityFramework.Sqlite/Migrations/SqliteMigrationsSqlGenerator.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs

Lift SQLite foreign key additions into create table statement

---

src/EntityFramework.Relational/Storage/SqlStatementExecutor.cs

Add missing cancellationToken

---

src/EntityFramework.Commands/Migrations/Design/MigrationsScaffolder.cs
src/EntityFramework.Relational/Migrations/IMigrationsAssembly.cs
src/EntityFramework.Relational/Migrations/Internal/MigrationsAssembly.cs
src/EntityFramework.Relational/Migrations/Internal/Migrator.cs
src/EntityFramework.Relational/Migrations/Migration.cs
src/EntityFramework.Relational/Migrations/MigrationBuilder.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/OperationCompilationTest.cs
test/EntityFramework.Commands.Tests/Migrations/Design/MigrationScaffolderTest.cs
test/EntityFramework.Relational.FunctionalTests/MigrationsFixtureBase.cs
test/EntityFramework.Relational.FunctionalTests/MigrationsTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EntityFramework.Sqlite.FunctionalTests/MigrationsSqliteTest.cs

Migrations: Expose active provider

---

src/EntityFramework.Commands/Design/DbContextOperations.cs

Fixes aspnet/dnx#2706
P.S. Fleshing out how we discover services and select an environment is part of #2357

DNX Commands: Use development environment

---

src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
test/EntityFramework.Relational.FunctionalTests/FromSqlQueryTestBase.cs
test/EntityFramework.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs

~~Fixing the issue and adding the missing Sqlite test cases~~
@anpete

Fix #3142 - Make FromSql compose on Projections

---

src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalPropertyBuilder.cs
test/EntityFramework.Core.FunctionalTests/DataAnnotationFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/DataAnnotationTestBase.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalPropertyBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ConventionDispatcherTest.cs
test/EntityFramework.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs

Set property CLR type and shadowness before calling conventions.

---

NuGetPackageVerifier.json
src/EntityFramework.Sqlite.Design/Properties/AssemblyInfo.cs
test/EntityFramework.Core.FunctionalTests/Properties/AssemblyInfo.cs
test/EntityFramework.Relational.Design.FunctionalTests/Properties/AssemblyInfo.cs
test/EntityFramework.Relational.FunctionalTests/Properties/AssemblyInfo.cs

Enabling NuGetPackageVerifier

---

src/EntityFramework.Core/Internal/ModelValidator.cs
test/EntityFramework.Core.Tests/Infrastructure/ModelValidatorTest.cs
test/EntityFramework.Core.Tests/ModelSourceTest.cs
test/EntityFramework.Relational.Tests/RelationalModelValidatorTest.cs

Add validation for null PK

---

src/EntityFramework.SqlServer/project.json

See #2977. Reverting c4fcbcee57a00e47469d56fc240e70379c3dd904.

Downgrade version of dnxcore SqlClient

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Query/EntityQueryModelVisitorFactory.cs
src/EntityFramework.Core/Query/QueryCompilationContext.cs
src/EntityFramework.Core/Storage/Database.cs
src/EntityFramework.InMemory/Query/InMemoryQueryModelVisitor.cs
src/EntityFramework.InMemory/Query/InMemoryQueryModelVisitorFactory.cs
src/EntityFramework.Relational/Query/RelationalQueryModelVisitorFactory.cs
src/EntityFramework.SqlServer/Query/SqlServerQueryModelVisitor.cs
src/EntityFramework.SqlServer/Query/SqlServerQueryModelVisitorFactory.cs

Query: More DRYing up of DI

---

src/EntityFramework.Commands/Commands/Program.cs
src/EntityFramework.Commands/Design/DatabaseOperations.cs
src/EntityFramework.Commands/Design/DbContextOperations.cs
src/EntityFramework.Commands/Design/MigrationsOperations.cs
src/EntityFramework.Commands/Design/OperationExecutor.cs
src/EntityFramework.Commands/Properties/Strings.Designer.cs
src/EntityFramework.Commands/Properties/Strings.resx
src/EntityFramework.Commands/tools/EntityFramework.psm1
test/EntityFramework.Commands.FunctionalTests/ExecutorTest.cs
test/EntityFramework.Commands.FunctionalTests/TestUtilities/OperationExecutorWrapper.cs

Other changes:
* Delay loading assemblies until needed
* Error better on assembly load failures
* Print stack traces (fixes #3135)

NuGet Commands: Use startup project for app base

---

src/EntityFramework.Relational.Design/ReverseEngineering/ReverseEngineeringGenerator.cs

@bricelam - this should fix the problem in #3227

[SMALL] Allow for whitespace from Scaffold-DbContext.

---

src/EntityFramework.Relational/Migrations/Internal/Migrator.cs
src/EntityFramework.Relational/Migrations/MigrationsSqlGenerator.cs
src/EntityFramework.Relational/Storage/ISqlGenerator.cs
src/EntityFramework.Relational/Storage/RelationalSqlGenerator.cs
src/EntityFramework.Relational/Update/IUpdateSqlGenerator.cs
src/EntityFramework.Relational/Update/UpdateSqlGenerator.cs
src/EntityFramework.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EntityFramework.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
src/EntityFramework.SqlServer/Storage/Internal/SqlServerSqlGenerator.cs
src/EntityFramework.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
src/EntityFramework.Sqlite/Migrations/SqliteMigrationsSqlGenerator.cs
src/EntityFramework.Sqlite/Update/Internal/SqliteUpdateSqlGenerator.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Storage/SqlGeneratorTestBase.cs
test/EntityFramework.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
test/EntityFramework.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/EntityFramework.SqlServer.Tests/Storage/SqlServerSqlGeneratorTest.cs
test/EntityFramework.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteHistoryRepositoryTest.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs

Remove IUpdateSqlGenerator from Migrations

---

src/EntityFramework.SqlServer/project.json

Let's try this again. DNX recently took a new version of coreclr.

Upgrade SqlClient on CoreClr

---

src/EntityFramework.Sqlite.Design/EntityFramework.Sqlite.Design.csproj
src/EntityFramework.Sqlite.Design/ReverseEngineering/Model/ColumnInfo.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/Model/DatabaseInfo.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/Model/ForeignKeyInfo.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/Model/IndexInfo.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/Model/TableInfo.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/SqliteDesignTimeMetadataProviderFactory.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/SqliteDmlParser.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/SqliteMetadataModelProvider.cs
src/EntityFramework.Sqlite.Design/ReverseEngineering/SqliteMetadataReader.cs

Refactors SQLite metadata fetching into its own component.
/cc: @lajones

Reveng: add SQLite metadata reader

---

src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Infrastructure/RelationalEntityFrameworkServicesBuilderExtensions.cs
src/EntityFramework.Relational/Infrastructure/RelationalSqlExecutor.cs
src/EntityFramework.Relational/Query/Sql/RawSqlQueryGenerator.cs
src/EntityFramework.Relational/Storage/ISqlCommandBuilder.cs
src/EntityFramework.Relational/Storage/Internal/SqlCommandBuilder.cs
src/EntityFramework.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGeneratorFactory.cs
src/EntityFramework.Sqlite/Query/Sql/SqliteQuerySqlGeneratorFactory.cs
src/EntityFramework.Sqlite/Storage/Internal/SqliteRelationalConnection.cs
test/EntityFramework.Relational.Tests/EntityFramework.Relational.Tests.csproj
test/EntityFramework.Relational.Tests/Storage/SqlCommandBuilderTest.cs
test/EntityFramework.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalTypeMapper.cs
test/EntityFramework.SqlServer.FunctionalTests/CommandConfigurationTest.cs
test/EntityFramework.Sqlite.FunctionalTests/CommandConfigurationTest.cs

Incremental change for #3110, Start to decouple command building from ISqlStatementExecutor, DRY up user command parameter processing.

Add SqlCommandBuilder to unify building RelationalCommands from raw SQL

---

src/EntityFramework.Core/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/KeyDiscoveryConvention.cs
src/EntityFramework.Relational.Design/ReverseEngineering/Configuration/ModelConfiguration.cs
test/EntityFramework.Core.FunctionalTests/GearsOfWarQueryFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/InheritanceRelationshipsQueryFixtureBase.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/KeyDiscoveryConventionTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ModelBuilderNonGenericStringTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/NonRelationshipTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Trigger KeyDiscoveryConventions when new property added

---

src/EntityFramework.Core/project.json
src/EntityFramework.Relational/project.json
src/EntityFramework.SqlServer/project.json
src/EntityFramework.Sqlite/project.json
test/EntityFramework.SqlServer.Design.FunctionalTests/project.json
test/EntityFramework.Sqlite.Design.FunctionalTests/project.json

Depends on...
* https://github.com/aspnet/Common/pull/47
* https://github.com/aspnet/Configuration/pull/305
* https://github.com/aspnet/DependencyInjection/pull/298
* https://github.com/aspnet/Options/pull/85
* https://github.com/aspnet/Logging/pull/258
* https://github.com/aspnet/Caching/pull/115
* https://github.com/aspnet/Microsoft.Data.Sqlite/pull/146

Downgrade to RTM packages for UWP

---

src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/EntityFrameworkServiceCollectionExtensions.cs
src/EntityFramework.Core/Internal/InternalDbSet.cs
src/EntityFramework.Core/Query/EntityQueryable`.cs
src/EntityFramework.Core/Query/ExpressionVisitors/NavigationRewritingExpressionVisitor.cs
src/EntityFramework.Core/Query/IEntityQueryProvider.cs
src/EntityFramework.Core/Query/Internal/EntityQueryProvider.cs
test/EntityFramework.Core.Tests/EntityFrameworkServiceCollectionExtensionsTest.cs

It adds nothing to the contract of IAsyncQueryProvider, so use this instead.

Remove IEntityQueryProvider

---

test/EntityFramework.SqlServer.Design.FunctionalTests/EntityFramework.SqlServer.Design.FunctionalTests.csproj

Fix problem with not copying expected files to output dir

---

src/EntityFramework.Commands/Commands/Program.cs

DNX Commands: Add --json option

---

src/EntityFramework.Core/Metadata/Conventions/Internal/KeyAttributeConvention.cs
test/EntityFramework.Core.FunctionalTests/TestModelSource.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/PropertyAttributeConventionTest.cs

Check for multiple KeyAttribute for base type only, Run ModelBuiltConventions for tests

---

src/EntityFramework.Commands/Design/DbContextOperations.cs
src/EntityFramework.Commands/Properties/CommandsStrings.Designer.cs
src/EntityFramework.Commands/Properties/CommandsStrings.resx
src/EntityFramework.Commands/tools/EntityFramework.psm1
src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Infrastructure/IDbContextFactory.cs

Add IDbContextFactory

---

test/EntityFramework.SqlServer.Design.FunctionalTests/EntityFramework.SqlServer.Design.FunctionalTests.csproj
test/EntityFramework.SqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/SqlServerReverseEngineerTestE2EContext.expected
test/EntityFramework.SqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/AttributesContext.expected
test/EntityFramework.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs

Fix e2e tests for SqlServer.Design

---

src/EntityFramework.Core/Properties/CoreStrings.resx

To correct word spell

---

src/EntityFramework.Commands/Commands/Program.cs
src/EntityFramework.Commands/Design/MigrationsOperations.cs
src/EntityFramework.Commands/Design/OperationExecutor.cs
src/EntityFramework.Commands/Migrations/Design/MigrationsScaffolder.cs
src/EntityFramework.Commands/Properties/CommandsStrings.Designer.cs
src/EntityFramework.Commands/Properties/CommandsStrings.resx
src/EntityFramework.Commands/tools/EntityFramework.psm1
src/EntityFramework.Relational/Migrations/IMigrationsAssembly.cs
src/EntityFramework.Relational/Migrations/Internal/MigrationsAssembly.cs
test/EntityFramework.Commands.FunctionalTests/Design/Internal/ForwardingProxyTest.cs
test/EntityFramework.Commands.FunctionalTests/Design/OperationExecutorTest.cs
test/EntityFramework.Commands.FunctionalTests/EntityFramework.Commands.FunctionalTests.csproj
test/EntityFramework.Commands.FunctionalTests/TestUtilities/OperationExecutorWrapper.cs

Resolves #3124
Also adds an `-OutputDir` parameter (resolves #3243)

Commands: Start new namespace if default contains migrations for another DbContext

---

src/EntityFramework.Relational.Design/ReverseEngineering/Internal/TableSelectionSet.cs
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/SqlServerMetadataReaderTest.cs
test/EntityFramework.Relational.Design.Tests/EntityFramework.Relational.Design.Tests.csproj
test/EntityFramework.Relational.Design.Tests/TableSelectionSetTests.cs

Also adding a default constructor for syntactic sugar.
cc @lajones

Fix minor bugs in TableSelectionSet

---

test/EntityFramework.MicrosoftSqlServer.FunctionalTests/FromSqlSprocQuerySqlServerTest.cs
test/EntityFramework.Relational.FunctionalTests/FromSqlSprocQueryTestBase.cs

Adding test cases to catch any regressions
@anpete

Add tests for resolved issue #2420, Multiple calls to FromSql with stored procedure

---

src/EntityFramework.Commands/Design/Internal/DesignTimeServicesBuilder.cs

Reverse mistaken changes made in #3423 
@lajones

[small] Quick fix for missing services error in Package Manager Console

---

src/EntityFramework.Core/ModelBuilder.cs

Very minor typo update to comment.

Small typo fix to comment on ModelBuilder.cs

---

test/EntityFramework.MicrosoftSqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
test/EntityFramework.Relational.FunctionalTests/FromSqlQueryTestBase.cs

Issue appears to be resolved in beta8, adding a test to prevent regression

Add test coverage for FromSql with null parameter value #3432

---

src/EntityFramework.Core/Metadata/EntityType.cs
src/EntityFramework.Relational/Metadata/Builders/DiscriminatorBuilder.cs
src/EntityFramework.Relational/Metadata/Builders/DiscriminatorBuilder`.cs
src/EntityFramework.Relational/Metadata/Internal/RelationalEntityTypeBuilderAnnotations.cs
src/EntityFramework.Relational/RelationalEntityTypeBuilderExtensions.cs
test/EntityFramework.Relational.Tests/Metadata/Conventions/Internal/DiscriminatorConventionTest.cs
test/EntityFramework.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs
test/EntityFramework.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs

Add more sugar API for discriminators

---

src/EntityFramework.Core/project.json

Upgrade version of Relinq

---

src/EntityFramework.Commands/Commands/Program.cs
src/EntityFramework.Commands/Design/DatabaseOperations.cs
src/EntityFramework.Commands/Design/DbContextOperations.cs
src/EntityFramework.Commands/Design/Internal/DesignTimeServicesBuilder.cs
src/EntityFramework.Commands/Design/Internal/StartupInvoker.cs
src/EntityFramework.Commands/Design/MigrationsOperations.cs
src/EntityFramework.Commands/Extensions/ServiceCollectionExtensions.cs
test/EntityFramework.Commands.FunctionalTests/TestUtilities/BuildReference.cs
test/EntityFramework.Commands.Tests/Design/Internal/StartupInvokerTest.cs
test/EntityFramework.Microbenchmarks.Core/BenchmarkTestCaseRunner.cs
test/EntityFramework.Relational.Design.FunctionalTests/Compilation/MetadataReferencesProvider.cs

Refactor dependency injection usage in entity framework

---

src/EntityFramework.Core/ChangeTracking/ChangeTracker.cs
src/EntityFramework.Core/ChangeTracking/EntityEntry.cs
src/EntityFramework.Core/ChangeTracking/EntityEntryGraphNode.cs
src/EntityFramework.Core/ChangeTracking/EntityEntry`.cs
src/EntityFramework.Core/ChangeTracking/EntityGraphNodeBase.cs
src/EntityFramework.Core/ChangeTracking/PropertyEntry.cs
src/EntityFramework.Core/ChangeTracking/PropertyEntry`.cs
src/EntityFramework.Core/ChangeTracking/QueryTrackingBehavior.cs

It would be good to get a detailed review of what I wrote for QueryTrackingBehavior
@ajcvickers can you take a quick look at what I wrote for the GraphNode classes and make sure it is technically correct.

Doc comments for ChangeTracking.*

---

src/EntityFramework.Commands/Design/Internal/HostingEnvironment.cs
src/EntityFramework.Commands/Extensions/ServiceCollectionExtensions.cs
src/EntityFramework.Core/DbSet`.cs
src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/ExpressionVisitors/ProjectionExpressionVisitor.cs
src/EntityFramework.Core/Query/QueryCompiler.cs
src/EntityFramework.Relational/Storage/RelationalConnection.cs

Update #if 
Change some reflection calls to use typeinfo.

[small] minor cleanups

---

src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/Internal/QueryBuffer.cs
src/EntityFramework.Core/Query/QueryCompilationContext.cs
src/EntityFramework.Core/Query/QueryContext.cs
src/EntityFramework.InMemory/Query/ExpressionVisitors/Internal/InMemoryEntityQueryableExpressionVisitor.cs
src/EntityFramework.InMemory/Query/Internal/InMemoryQueryContext.cs
src/EntityFramework.InMemory/Query/Internal/InMemoryQueryContextFactory.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
src/EntityFramework.Relational/Query/Internal/RelationalQueryContextFactory.cs
src/EntityFramework.Relational/Query/RelationalQueryContext.cs
test/EntityFramework.Core.FunctionalTests/AsNoTrackingTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
test/EntityFramework.Relational.Tests/Storage/RelationalCommandTest.cs

- Tracked queries, queries that use Include and queries that access shadow state.

Query: Performance: Only use QueryBuffer on queries that require it:

---

src/EntityFramework.Core/Extensions/EntityFrameworkQueryableExtensions.cs
src/EntityFramework.Core/Infrastructure/AccessorExtensions.cs
src/EntityFramework.Core/Infrastructure/Annotatable.cs
src/EntityFramework.Core/Infrastructure/Annotation.cs
src/EntityFramework.Core/Infrastructure/CoreLoggingEventId.cs
src/EntityFramework.Core/Infrastructure/CoreOptionsExtension.cs
src/EntityFramework.Core/Infrastructure/DatabaseFacade.cs
src/EntityFramework.Core/Infrastructure/DbContextAttribute.cs
src/EntityFramework.Core/Infrastructure/DbContextOptions.cs
src/EntityFramework.Core/Infrastructure/DbContextOptions`.cs
src/EntityFramework.Core/Infrastructure/EntityFrameworkServicesBuilder.cs
src/EntityFramework.Core/Infrastructure/IAccessor.cs
src/EntityFramework.Core/Infrastructure/IAnnotatable.cs
src/EntityFramework.Core/Infrastructure/IAnnotation.cs
src/EntityFramework.Core/Infrastructure/IDbContextFactory.cs
src/EntityFramework.Core/Infrastructure/IDbContextOptions.cs
src/EntityFramework.Core/Infrastructure/IDbContextOptionsBuilderInfrastructure.cs
src/EntityFramework.Core/Infrastructure/IDbContextOptionsExtension.cs
src/EntityFramework.Core/Infrastructure/IKeyValue.cs
src/EntityFramework.Core/Infrastructure/IModelSource.cs
src/EntityFramework.Core/Infrastructure/ModelSource.cs

The things that I think would be good to review in detail are:
* EntityFrameworkQueryableExtensions.Include/ThenInclude
* CoreLoggingEventId
* EntityFrameworkServicesBuilder

doc comments for Infrastructure.*

---

test/EntityFramework.Relational.FunctionalTests/QueryNoClientEvalTestBase.cs

Add some missing quotes around identifiers

---

src/EntityFramework.Core/ChangeTracking/Internal/CompositeKeyValueFactory.cs
src/EntityFramework.Core/ChangeTracking/Internal/KeyValueFactory.cs
src/EntityFramework.Core/ChangeTracking/Internal/SimpleKeyValueFactory.cs
src/EntityFramework.Core/Query/Internal/EntityTrackingInfo.cs
src/EntityFramework.Core/Query/Internal/IQueryBuffer.cs
src/EntityFramework.Core/Query/Internal/QueryBuffer.cs
src/EntityFramework.InMemory/Query/ExpressionVisitors/Internal/InMemoryEntityQueryableExpressionVisitor.cs
src/EntityFramework.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/Internal/QueryFlattener.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
src/EntityFramework.Relational/Query/Internal/AsyncQueryingEnumerable.cs
src/EntityFramework.Relational/Query/Internal/QueryingEnumerable.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs

Some other minor perf improvements to the query hot path.

Query: Perf: Adds a faster path for constructing primary key values.

---

src/EntityFramework.Core/Extensions/PropertyExtensions.cs
src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/Index.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalIndexBuilder.cs
src/EntityFramework.Core/Metadata/Internal/MetadataHelper.cs
src/EntityFramework.Core/Metadata/Internal/Property.cs
test/EntityFramework.Core.Tests/Metadata/Internal/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/IndexTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs

Allow indexes to use inherited properties

---

test/EntityFramework.Core.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Added test for #3503 so that we don't regress in future

Add test for foreign key property names for created shadow properties

---

src/EntityFramework.Commands/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EntityFramework.Commands/Migrations/Design/CSharpSnapshotGenerator.cs
src/EntityFramework.Commands/Migrations/Design/MigrationsCodeGenerator.cs
src/EntityFramework.Core/Extensions/MutableModelExtensions.cs
src/EntityFramework.Core/Infrastructure/Annotatable.cs
src/EntityFramework.Core/Infrastructure/IAnnotatable.cs
src/EntityFramework.Core/Metadata/IMutableAnnotatable.cs
src/EntityFramework.Core/Metadata/IMutableEntityType.cs
src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/InternalMetadataBuilder.cs
src/EntityFramework.Core/Metadata/Internal/Model.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
src/EntityFramework.Relational/Metadata/Sequence.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs
test/EntityFramework.Core.FunctionalTests/TestUtilities/Extensions.cs
test/EntityFramework.Core.FunctionalTests/TestUtilities/ForeignKeyComparer.cs
test/EntityFramework.Core.FunctionalTests/TestUtilities/IndexComparer.cs
test/EntityFramework.Core.FunctionalTests/TestUtilities/KeyComparer.cs
test/EntityFramework.Core.FunctionalTests/TestUtilities/NavigationComparer.cs
test/EntityFramework.Core.FunctionalTests/TestUtilities/PropertyComparer.cs
test/EntityFramework.Core.Tests/Infrastructure/AnnotatableTest.cs
test/EntityFramework.Core.Tests/Metadata/EntityTypeExtensionsTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalMetadataBuilderTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Metadata/InternalSqlServerMetadataBuilderExtensionsTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Metadata/ModelConventions/SqlServerValueGenerationStrategyConventionTest.cs
test/EntityFramework.Sqlite.Tests/Metadata/Internal/SqliteInternalMetadataBuilderExtensionsTest.cs

Add IMutableModel.AddEntityType(Type), GetOrAddEntityType(Type) and RemoveEntityType(Type) extension methods
Add IEntityType.ClrType setter
Change IAnnotatable.Annotations to GetAnnotations()

More IMutableModel API changes

---

src/EntityFramework.MicrosoftSqlServer/Extensions/SqlServerDbContextOptionsExtensions.cs
src/EntityFramework.MicrosoftSqlServer/Extensions/SqlServerEntityFrameworkServicesBuilderExtensions.cs
src/EntityFramework.Relational/RelationalDatabaseFacadeExtensions.cs

Doc comments for the APIs that are called in the ASP.NET 5 starter web
template (RC1)

[SMALL] doc comments for APIs used in ASP.NET 5 template

---

src/EntityFramework.Commands/Commands/Program.cs

@davidfowl said it's more idiomatic...

DNX Commands: Kabob-case all the things

---

test/EntityFramework.Commands.FunctionalTests/TestUtilities/BuildReference.cs
test/EntityFramework.Relational.Design.FunctionalTests/Compilation/MetadataReferencesProvider.cs

Issue: https://github.com/aspnet/Universe/issues/318
Depends on https://github.com/aspnet/dnx/pull/3126
/cc @davidfowl @pranavkm

Rename Microsoft.Dnx.Compilation.Abstractions to Microsoft.Extensions.Compilation.Abstractions 

---

src/EntityFramework.Commands/Migrations/Design/CSharpHelper.cs
src/EntityFramework.Commands/project.json
src/EntityFramework.Relational.Design/Internal/CSharpUtilities.cs
src/EntityFramework.Relational.Design/Internal/ReverseEngineeringConfiguration.cs
src/EntityFramework.Relational.Design/project.json
test/EntityFramework.Commands.FunctionalTests/project.json
test/EntityFramework.Relational.Design.FunctionalTests/project.json
tools/EntityFramework.props

Remove Roslyn dependency

---

src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
src/EntityFramework.InMemory/Properties/InMemoryStrings.Designer.cs
src/EntityFramework.InMemory/Properties/InMemoryStrings.resx
src/EntityFramework.MicrosoftSqlServer.Design/Properties/SqlServerDesignStrings.Designer.cs
src/EntityFramework.MicrosoftSqlServer.Design/Properties/SqlServerDesignStrings.resx
src/EntityFramework.MicrosoftSqlServer/Properties/SqlServerStrings.Designer.cs
src/EntityFramework.MicrosoftSqlServer/Properties/SqlServerStrings.resx
src/EntityFramework.Relational.Design/Properties/RelationalDesignStrings.Designer.cs
src/EntityFramework.Relational.Design/Properties/RelationalDesignStrings.resx
src/EntityFramework.Relational/Properties/RelationalStrings.Designer.cs
src/EntityFramework.Relational/Properties/RelationalStrings.resx
src/EntityFramework.Sqlite/Properties/SqliteStrings.Designer.cs

Discovered while reviewing messages for #2752

Remove unused exception and log strings from resource files

---

src/EntityFramework.Core/ChangeTracking/Internal/StateManager.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
test/EntityFramework.Core.Tests/ChangeTracking/ChangeTrackerTest.cs
test/EntityFramework.Core.Tests/ChangeTracking/Internal/StateManagerTest.cs

Resolves #743 
~~Re-introduced `ModelItemNotFoundException`~~

Throw when instance of unmapped derived type is used

---

src/EntityFramework.Relational/Update/Internal/CommandBatchPreparer.cs
test/EntityFramework.Relational.Tests/Update/CommandBatchPreparerTest.cs

resolves #3648 
We sort commands in same batch based on EntityState, which puts delete before add. But if the due to other operations, if add/delete on same entity ends up in different batches then add might be performed before delete. For foreign key which are unique this causes exception on database.
Solution is to add foreign key dependency between commands for unique foreign key if the same values are being re-used. So that delete always happen before add/update.
At present this error is not being seen because of #700 because all `0..1:0..1` relationships are stored as `0..1:*` in database.

Update topological sort to account for unique constraints on FK

---

src/EntityFramework.Core/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
test/EntityFramework.Core.Tests/Metadata/ModelConventions/PropertyMappingValidationConventionTest.cs

:bug: Don't use GetRuntimeProperty

---

src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
src/EntityFramework.Core/Query/Internal/ExpressionPrinter.cs
src/EntityFramework.Relational/Properties/RelationalStrings.Designer.cs
src/EntityFramework.Relational/Properties/RelationalStrings.resx
src/EntityFramework.Relational/Update/ModificationCommand.cs

Moving string literal error messages discovered in #2752 into appropriate resource files

Move error messages into resource files

---

src/EntityFramework.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EntityFramework.Commands.FunctionalTests/App.config
test/EntityFramework.Commands.FunctionalTests/EntityFramework.Commands.FunctionalTests.csproj
test/EntityFramework.Commands.FunctionalTests/TestUtilities/OperationExecutorWrapper.cs
test/EntityFramework.Commands.Tests/Migrations/Design/MigrationScaffolderTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
test/EntityFramework.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EntityFramework.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteHistoryRepositoryTest.cs
test/EntityFramework.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs

Migrations: Diff column types using the TypeMapper

---

README.md

Add links to docs in README.md

---

src/EntityFramework.Core/Properties/EntityFramework.Core.rd.xml

[uber-small] Fix missing metadata exception on UWP

---

src/EntityFramework.Commands/Scaffolding/Internal/Configuration/IndexConfiguration.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/CascadeDeleteConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/KeyConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
src/EntityFramework.Core/Metadata/IMutableIndex.cs
src/EntityFramework.Core/Metadata/Internal/ConfigurationSourceExtensions.cs
src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/ForeignKey.cs
src/EntityFramework.Core/Metadata/Internal/Index.cs
src/EntityFramework.Core/Metadata/Internal/InternalIndexBuilder.cs
src/EntityFramework.Core/Metadata/Internal/Key.cs
src/EntityFramework.Core/Metadata/Internal/Property.cs
test/EntityFramework.Core.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
test/EntityFramework.Core.Tests/Metadata/Internal/ConfigurationSourceExtensionsTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/ForeignKeyTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/IndexTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalIndexBuilderTest.cs

Move InternalIndexBuilder state to Index

---

src/EntityFramework.Commands/Scaffolding/Internal/Configuration/IndexConfiguration.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/CascadeDeleteConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/KeyConvention.cs
src/EntityFramework.Core/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
src/EntityFramework.Core/Metadata/IMutableIndex.cs
src/EntityFramework.Core/Metadata/Internal/ConfigurationSourceExtensions.cs
src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/ForeignKey.cs
src/EntityFramework.Core/Metadata/Internal/Index.cs
src/EntityFramework.Core/Metadata/Internal/InternalIndexBuilder.cs
src/EntityFramework.Core/Metadata/Internal/Key.cs
src/EntityFramework.Core/Metadata/Internal/Property.cs
test/EntityFramework.Core.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
test/EntityFramework.Core.Tests/Metadata/Internal/ConfigurationSourceExtensionsTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/ForeignKeyTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/IndexTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalIndexBuilderTest.cs

Move InternalRelationshipBuilder state to ForeignKey

---

src/EntityFramework.Sqlite/Storage/Internal/SqliteRelationalConnection.cs
test/EntityFramework.Sqlite.FunctionalTests/ComplexNavigationsQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/IncludeSqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/MappingQuerySqliteTest.cs
test/EntityFramework.Sqlite.FunctionalTests/QuerySqliteTest.cs

Explicitly disable FK enforcement for Sqlite

---

src/EntityFramework.Commands/Migrations/Design/CSharpSnapshotGenerator.cs
test/EntityFramework.Core.FunctionalTests/InheritanceFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/InheritanceRelationshipsQueryFixtureBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

#3282 got fixed by other changes.
Removed all work-arounds and added test

Add test for RequireValueGenerator handling

---

src/EntityFramework.Commands/Design/Internal/HostingEnvironment.cs

Fixes build
@rowanmiller @natemcmaster

React to hosting changes

---

src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToOneTestBase.cs

Create Shadow Property for FK

---

src/EntityFramework.Core/Metadata/Conventions/Internal/KeyConvention.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

:bug: Handle Identity in KeyConvention properly

---

src/EntityFramework.Commands/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EntityFramework.Commands/Migrations/Design/CSharpMigrationsGenerator.cs
src/EntityFramework.Relational/Migrations/MigrationsSqlGenerator.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/CodeCompilationTest.cs
test/EntityFramework.Commands.FunctionalTests/Migrations/OperationCompilationTest.cs
test/EntityFramework.Commands.Tests/EntityFramework.Commands.Tests.csproj
test/EntityFramework.Commands.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs

Migrations: Cleanup formatting of scaffolded code

---

src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
test/EntityFramework.Core.Tests/Metadata/ModelConventions/NavigationAttributeConventionTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ModelBuilderNonGenericStringTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Throw Exception if multiple navigations are pointing at same set of fk properties

---

src/EntityFramework.MicrosoftSqlServer/Storage/Internal/SqlServerConnection.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs
test/EntityFramework.MicrosoftSqlServer.Tests/SqlServerConnectionTest.cs

Compensate for slowness in creating a database on SQL Server.

Increase default command timeout on operations against SQL Server master

---

src/EntityFramework.Core/Query/QueryCompilationContext.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs

Need to consider Include annotations when determining if FromSql is composed
@anpete @maumar

Fix #3491 - FromSql query with complex Include not working

---

README.md
appveyor.yml
makefile.shade

Add appveyor.yml

---

src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Internal/RelationalDiagnosticSourceMessage.cs
src/EntityFramework.Relational/Internal/RelationalDiagnostics.cs
test/EntityFramework.Relational.Tests/Storage/RelationalCommandTest.cs

Use concrete type instead of anonymous type
Workaround for https://github.com/dotnet/corefx/issues/4672

Workaround anonymous type bug in diagnostics

---

test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/SqlServerDatabaseModelFactoryTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/CompiledQueryCacheKeyGeneratorTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/InheritanceSqlServerFixture.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/MappingQuerySqlServerFixture.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/OneToOneQuerySqlServerFixture.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs
test/EntityFramework.Relational.Design.FunctionalTests/ReverseEngineering/E2ETestBase.cs
test/EntityFramework.Relational.FunctionalTests/InheritanceRelationalFixture.cs
test/EntityFramework.Relational.FunctionalTests/TransactionTestBase.cs
test/EntityFramework.Sqlite.Design.FunctionalTests/SqliteDatabaseModelFactoryTest.cs
test/EntityFramework.Sqlite.FunctionalTests/AutoincrementTest.cs
test/EntityFramework.Sqlite.FunctionalTests/InheritanceSqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/OneToOneQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/SqliteForeignKeyTest.cs
test/EntityFramework.Sqlite.FunctionalTests/SqliteTestStore.cs

Make sure Scratch databases are deleted

---

src/EntityFramework.Core/Extensions/Internal/ExpressionExtensions.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/NonRelationshipTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Allow ignoring explicit interface implementation using casting

---

test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs

Wait for localdb database files to be deleted instead of deleting them

---

src/EntityFramework.Core/Metadata/Builders/CollectionNavigationBuilder.cs
src/EntityFramework.Core/Metadata/Builders/CollectionNavigationBuilder`.cs
src/EntityFramework.Core/Metadata/Builders/EntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Builders/ReferenceNavigationBuilder.cs
src/EntityFramework.Core/Metadata/Builders/ReferenceNavigationBuilder`.cs

Add a non-empty check for navigation name in relationship API

---

src/EntityFramework.MicrosoftSqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs

Use SCOPE_IDENTITY() for SqlServer inserts if only one row is being inserted

---

src/EntityFramework.Core/Metadata/Internal/InternalModelBuilder.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

:bug: Remove derived type from directlyDerivedTypes list when removing entity type

---

test/EntityFramework.Core.FunctionalTests/DatabaseErrorLogStateTest.cs
test/EntityFramework.Core.FunctionalTests/TestFileLogger.cs
test/EntityFramework.Core.Tests/DbContextTest.cs
test/EntityFramework.Core.Tests/TestUtilities/ListLoggerFactory.cs
test/EntityFramework.InMemory.FunctionalTests/NorthwindQueryInMemoryFixture.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/NorthwindSprocQuerySqlServerFixture.cs
test/EntityFramework.Relational.FunctionalTests/TestSqlLoggerFactory.cs
test/EntityFramework.Sqlite.FunctionalTests/NorthwindQuerySqliteFixture.cs

Reacting to https://github.com/aspnet/Logging/pull/308
Tested locally.

Reacting to removal of ILoggerFactory.MinimumLevel

---

src/EntityFramework.Commands/Properties/CommandsStrings.Designer.cs
src/EntityFramework.Commands/Properties/CommandsStrings.resx

[TINY] More command info when multiple contexts found

---

src/EntityFramework.Core/Internal/ModelValidator.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
test/EntityFramework.Core.Tests/Infrastructure/ModelValidatorTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/SqlServerTriggersTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/SqlServerModelValidatorTest.cs
test/EntityFramework.Relational.Tests/RelationalModelValidatorTest.cs
test/EntityFramework.Relational.Tests/Storage/RelationalTypeMapperTest.cs
test/EntityFramework.Sqlite.Tests/SqliteModelValidatorTest.cs
tools/Resources.cs

Enforce CLR inheritance in model using validation

---

src/EntityFramework.Core/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/DataAnnotationsTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Upgrade source for navigation being used by foreign key attribute

---

src/EntityFramework.MicrosoftSqlServer/EntityFramework.MicrosoftSqlServer.csproj
src/EntityFramework.MicrosoftSqlServer/Update/Internal/ISqlServerUpdateSqlGenerator.cs
src/EntityFramework.MicrosoftSqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
src/EntityFramework.MicrosoftSqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
src/EntityFramework.Relational/EntityFramework.Relational.csproj
src/EntityFramework.Relational/Update/AffectedCountModificationCommandBatch.cs
src/EntityFramework.Relational/Update/IUpdateSqlGenerator.cs
src/EntityFramework.Relational/Update/ReaderModificationCommandBatch.cs
src/EntityFramework.Relational/Update/ResultSetMapping.cs
src/EntityFramework.Relational/Update/UpdateSqlGenerator.cs
src/EntityFramework.Sqlite/Update/Internal/SqliteUpdateSqlGenerator.cs
test/EntityFramework.Core.FunctionalTests/NullKeysTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/InheritanceSqlServerTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
test/EntityFramework.Relational.Tests/Update/UpdateSqlGeneratorTest.cs
test/EntityFramework.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs
test/EntityFramework.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
test/EntityFramework.Sqlite.Tests/Update/SqliteUpdateSqlGeneratorTest.cs

Issue SET NOCOUNT ON on all operations
Fixes #2131

Don't validate affected rows for insert operations

---

src/EntityFramework.Core/Metadata/Builders/ReferenceReferenceBuilder.cs
src/EntityFramework.Core/Metadata/Builders/ReferenceReferenceBuilder`.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx

Add a better exception message when configuring the dependent/principal end of a relationship

---

src/EntityFramework.Sqlite/Storage/Internal/SqliteDatabaseCreator.cs
src/EntityFramework.Sqlite/Storage/Internal/SqliteRelationalConnection.cs
test/EntityFramework.Sqlite.FunctionalTests/EntityFramework.Sqlite.FunctionalTests.csproj
test/EntityFramework.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
test/EntityFramework.Sqlite.FunctionalTests/SqliteTestStore.cs

React to (and use) aspnet/Microsoft.Data.Sqlite#192

---

src/EntityFramework.Commands/Design/Internal/StartupInvoker.cs

Resolves #3802 
Verification: Manual (automation wasn't worth generating assemblies)

[2-liner] Commands: Look for Program then App if Startup not found

---

src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
test/EntityFramework.Core.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs

Dissalow defining FKs on properties that are part of an inherited key

---

src/EntityFramework.Core/Internal/Multigraph.cs
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
test/EntityFramework.Core.Tests/Utilities/MultigraphTest.cs
test/EntityFramework.Relational.Tests/Update/CommandBatchPreparerTest.cs

Update exception msg for circular dependency

---

src/EntityFramework.MicrosoftSqlServer/Migrations/Internal/SqlServerHistoryRepository.cs
src/EntityFramework.Relational/Migrations/HistoryRepository.cs
src/EntityFramework.Relational/Properties/RelationalStrings.Designer.cs
src/EntityFramework.Relational/Properties/RelationalStrings.resx
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs

Migrations: Allow multi-statement history table create scripts

---

src/EntityFramework.Relational/Storage/RelationalDatabaseCreator.cs

Make RelationalDatabaseCreator.CreateTables atomic

---

src/EntityFramework.Commands/Scaffolding/Internal/ScaffoldingUtilities.cs
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/SqlServerReverseEngineerTestE2EContext.expected
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/Test_Spaces_Keywords_Table.expected
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/Test_Spaces_Keywords_Table.expected

Fixes linux build errors.
cc @lajones

[reveng] Use x-plat consistent property ordering

---

test/EntityFramework.Microbenchmarks.EF6/EntityFramework.Microbenchmarks.EF6.csproj
test/EntityFramework.Microbenchmarks.EF6/Extensions.cs
test/EntityFramework.Microbenchmarks.EF6/Models/Orders/OrdersFixture.cs
test/EntityFramework.Microbenchmarks.EF6/Query/RawSqlQueryTests.cs
test/EntityFramework.Microbenchmarks/EntityFramework.Microbenchmarks.csproj
test/EntityFramework.Microbenchmarks/Models/Orders/OrdersFixture.cs
test/EntityFramework.Microbenchmarks/Query/RawSqlQueryTests.cs

Benchmarks for raw SQL queries

---

test/EntityFramework.MicrosoftSqlServer.Tests/SqlServerDatabaseCreatorTest.cs

React to changes in coreclr

---

test/EntityFramework.Microbenchmarks.EF6/ChangeTracker/FixupTests.cs
test/EntityFramework.Microbenchmarks/ChangeTracker/FixupTests.cs

[SMALL] AutoDetectChanges variations for FixupTests

---

src/EntityFramework.Commands/Design/Internal/DesignTimeServicesBuilder.cs
src/EntityFramework.Commands/Design/MigrationsOperations.cs
src/EntityFramework.Commands/Properties/CommandsStrings.Designer.cs
src/EntityFramework.Commands/Properties/CommandsStrings.resx
test/EntityFramework.Commands.FunctionalTests/Design/OperationExecutorTest.cs

Commands: Use override migrations assembly with target assembly

---

src/EntityFramework.Core/ChangeTracking/Internal/ChangeDetector.cs
src/EntityFramework.Core/ChangeTracking/Internal/KeyPropagator.cs
src/EntityFramework.Core/ChangeTracking/Internal/ValueGenerationManager.cs
src/EntityFramework.Core/EntityFramework.Core.csproj
src/EntityFramework.Core/Extensions/PropertyExtensions.cs
src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/IPropertyKeyMetadata.cs
src/EntityFramework.Core/Metadata/Internal/Property.cs
src/EntityFramework.Core/Metadata/Internal/PropertyExtensions.cs
src/EntityFramework.Relational/Storage/RelationalTypeMapper.cs
test/EntityFramework.Microbenchmarks/Query/SimpleQueryTests.cs

Properties keep track of which keys they belong to.

Improve perf of Add/Attach/Update by caching key metadata

---

src/EntityFramework.MicrosoftSqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
src/EntityFramework.Relational/Update/UpdateSqlGenerator.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/BatchingTest.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EntityFramework.MicrosoftSqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs

Add a strong order to the generated values returned from batches of inserts for Sql Server

---

test/EntityFramework.InMemory.FunctionalTests/QueryInMemoryTest.cs

[xplat] Ensure culture is set appropriately on failing in-memory test

---

test/EntityFramework.Core.FunctionalTests/AsNoTrackingTestBase.cs
test/EntityFramework.Core.FunctionalTests/ComplexNavigationsQueryTestBase.cs
test/EntityFramework.Core.FunctionalTests/GearsOfWarQueryTestBase.cs
test/EntityFramework.Core.FunctionalTests/IncludeAsyncTestBase.cs
test/EntityFramework.Core.FunctionalTests/QueryNavigationsTestBase.cs
test/EntityFramework.InMemory.FunctionalTests/MusicStoreQueryTests.cs
test/EntityFramework.Relational.FunctionalTests/NullSemanticsQueryTestBase.cs

Close #3594.
Skip tests that won't pass on Mono 4.0.x
cc @cesarbs

Skip tests that fail on Mono < 4.2

---

src/EntityFramework.Core/Metadata/Builders/ReferenceNavigationBuilder.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/OneToOneTestBase.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/TestModel.cs

Allow self referencing relationships without navigations

---

src/EntityFramework.Commands/Commands/Program.cs
src/EntityFramework.Commands/Design/Internal/ConsoleCommandLogger.cs
src/EntityFramework.Commands/Extensions/CommandLineUtilsExtensions.cs
src/EntityFramework.Commands/project.json

Unsource CommandLineUtils

---

src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/ResultOperatorHandler.cs
test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/QuerySqlServerTest.cs

Fixes exception thrown due to type mismatch between operator an expression sequence type
@anpete @maumar

Fix #1909 - Do not append Select when result operator performs projection

---

src/EntityFramework.Core/Metadata/Internal/EntityType.cs
src/EntityFramework.Core/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EntityFramework.Core/Metadata/Internal/InternalRelationshipBuilder.cs
test/EntityFramework.Core.Tests/Metadata/Internal/EntityTypeTest.cs
test/EntityFramework.Core.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/EntityFramework.Core.Tests/ModelBuilderTest/InheritanceTestBase.cs

Allow Fk to use inherited properties

---

test/EntityFramework.Core.FunctionalTests/ComplexNavigationsQueryTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs

also added some more complex groupjoin + selectmany + defaultifempty queries

adding more tests (currently disabled) for left outer join cases 

---

src/EntityFramework.Commands/tools/EntityFramework.psm1

- discovered while reading @julielerman MSDN Migrations article

[small] Fix Commands help typo

---

src/EntityFramework.MicrosoftSqlServer.Design/Metadata/SqlServerColumnModelAnnotations.cs
src/EntityFramework.MicrosoftSqlServer.Design/Metadata/SqlServerIndexModelAnnotations.cs
src/EntityFramework.MicrosoftSqlServer.Design/SqlServerDatabaseModelFactory.cs
src/EntityFramework.MicrosoftSqlServer.Design/SqlServerDesignTimeServices.cs
src/EntityFramework.MicrosoftSqlServer.Design/SqlServerScaffoldingModelFactory.cs
src/EntityFramework.MicrosoftSqlServer.Design/SqlServerTableSelectionSetExtensions.cs
src/EntityFramework.Relational.Design/Internal/CSharpUniqueNamer.cs
src/EntityFramework.Relational.Design/Internal/CSharpUtilities.cs
src/EntityFramework.Relational.Design/TableSelectionSet.cs
src/EntityFramework.Sqlite.Design/SqliteScaffoldingModelFactory.cs
src/EntityFramework.Sqlite.Design/SqliteTableSelectionSetExtensions.cs
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/App.config
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/SqlServerDatabaseModelFactoryTest.cs
test/EntityFramework.MicrosoftSqlServer.Design.Tests/SqlServerTableSelectionSetExtensionsTests.cs
test/EntityFramework.Relational.Design.FunctionalTests/App.config
test/EntityFramework.Relational.Design.FunctionalTests/Compilation/RoslynCompilationService.cs
test/EntityFramework.Relational.Design.FunctionalTests/ReverseEngineering/E2ETestBase.cs
test/EntityFramework.Relational.Design.FunctionalTests/ReverseEngineering/FileSet.cs
test/EntityFramework.Relational.Design.Tests/ApiConsistencyTest.cs
test/EntityFramework.Relational.Design.Tests/RelationalDatabaseModelFactoryTest.cs
test/EntityFramework.Relational.Design.Tests/ScaffoldingMetadataExtenstionsTest.cs
test/EntityFramework.Relational.Design.Tests/TestLogger.cs
test/EntityFramework.Sqlite.Design.FunctionalTests/App.config
test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
test/EntityFramework.Sqlite.Design.FunctionalTests/SqliteDatabaseModelFactoryTest.cs
test/EntityFramework.Sqlite.Design.FunctionalTests/SqliteScaffoldingModelFactoryTest.cs
test/EntityFramework.Sqlite.Design.FunctionalTests/TestLogger.cs
test/EntityFramework.Sqlite.Design.Tests/SqliteTableSelectionSetExtensionsTests.cs

Ran R# cleanup on all `*.Design.*` projects
cc @lajones

R# cleanup on design projects

---

src/EntityFramework.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs
test/EntityFramework.Core.FunctionalTests/InheritanceRelationshipsQueryFixtureBase.cs
test/EntityFramework.Core.FunctionalTests/InheritanceRelationshipsQueryTestBase.cs
test/EntityFramework.Core.FunctionalTests/TestModels/InheritanceRelationships/BaseInheritanceRelationshipEntity.cs
test/EntityFramework.Core.FunctionalTests/TestModels/InheritanceRelationships/DerivedInheritanceRelationshipEntity.cs
test/EntityFramework.Core.FunctionalTests/TestModels/InheritanceRelationships/InheritanceRelationshipsModelInitializer.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs

Support include on intra-hierarchical navigations

---

src/EntityFramework.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs
test/EntityFramework.Core.FunctionalTests/IncludeTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/IncludeSqlServerTest.cs

Fix #4260 - bug in interaction between rownumberpaging and include

---

src/EntityFramework.Relational/Query/Expressions/SelectExpression.cs
src/EntityFramework.Relational/Query/Internal/RelationalResultOperatorHandler.cs
test/EntityFramework.Core.FunctionalTests/QueryNavigationsTestBase.cs
test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/QuerySqlServerTest.cs

Partial fix for #153
- Resolves exception from invalid SQL and incorrect results for Contains subquery
- Does not address issues with Contains subquery with nav props.
@anpete @maumar

Convert ContainsResultOperator to InExpression in relational

---

src/EntityFramework.Core/DbContext.cs
src/EntityFramework.Core/EntityFramework.Core.xproj
src/EntityFramework.Core/Properties/CoreStrings.Designer.cs
src/EntityFramework.Core/Properties/CoreStrings.resx
test/EntityFramework.Core.Tests/DbContextTest.cs

Throw when DbContext.Set<T>() is called where T is not in the model

---

src/EntityFramework.Core/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs
src/EntityFramework.Relational/Query/RelationalQueryModelVisitor.cs
test/EntityFramework.Core.FunctionalTests/IncludeTestBase.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/IncludeSqlServerTest.cs

Fix for complex projections that include navigations

---

src/EntityFramework.MicrosoftSqlServer/Storage/Internal/SqlServerConnection.cs
src/EntityFramework.Relational/Query/RelationalQueryContext.cs

Make IsMultipleActiveResultSetsEnabled lazy.

Address use of SqlConnectionStringBuilder raised in discussion on #4133

---

src/EntityFramework.Core/Query/EntityQueryModelVisitor.cs
src/EntityFramework.Core/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs
src/EntityFramework.Core/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
src/EntityFramework.Core/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs
src/EntityFramework.Core/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs
src/EntityFramework.Core/Query/QueryCompilationContext.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
src/EntityFramework.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
test/EntityFramework.Core.FunctionalTests/TestModels/Northwind/NorthwindData.cs

Depends on #4320 
Fix #3604
cc @anpete

Fix .NET Native queries with shadow properties

---

test/EntityFramework.Sqlite.FunctionalTests/InheritanceRelationshipsQuerySqliteFixture.cs
test/EntityFramework.Sqlite.FunctionalTests/InheritanceRelationshipsQuerySqliteTest.cs

Fix #3365 - add more SQLite testing
cc @anpete -- all tests pass w/o any bugs on SQLite cuz Relational is so good :+1:

[test code only] Add InheritanceRelationshipsQuerySqliteTest

---

test/EntityFramework.InMemory.FunctionalTests/TestInMemoryModelSource.cs
test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/TestSqlServerModelSource.cs
test/EntityFramework.Sqlite.FunctionalTests/TestSqliteModelSource.cs

Fix build break from ModelCustomizer commit

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryNavigationsTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs

Fixes the data corruption issue described in #153. Still has room for some optimizations as described in the issue.
@anpete @maumar @divega

Fix #153 - Incorrect results from Contains with subquery

---

src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/CSharpSnapshotGenerator.cs
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs

:bug: Store delete behavior in model snapshot for unique FKs

---

src/Microsoft.EntityFrameworkCore.Sqlite/Properties/SqliteStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Sqlite/Properties/SqliteStrings.resx

[TINY] Link to SQLite limitation docs from exceptions

---

src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx

Updated based on wording suggested in issue #2227.
@divega @rowanmiller

Fix #2227 - Better exception message for no database provider configured

---

src/Microsoft.EntityFrameworkCore.Commands/build/netcore50/Microsoft.EntityFrameworkCore.Commands.props
src/Microsoft.EntityFrameworkCore.Commands/build/netcore50/Microsoft.EntityFrameworkCore.Commands.targets
src/Microsoft.EntityFrameworkCore.Commands/project.json
src/Microsoft.EntityFrameworkCore/build/netcore50/Microsoft.EntityFrameworkCore.targets

Fix UWP and commands support

---

src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/CommandLogger.cs
src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalLoggerExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/Internal/CoreLoggerExtensions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/SensitiveDataLogger.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/DatabaseErrorLogStateTest.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestFileLogger.cs
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/NorthwindQueryInMemoryFixture.cs
test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/NullLogger.cs
test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/TestLogger.cs
test/Microsoft.EntityFrameworkCore.Relational.FunctionalTests/TestSqlLoggerFactory.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/TestUtilities/FakeSensitiveDataLogger`.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/TestLogger.cs
test/Microsoft.EntityFrameworkCore.Tests/TestUtilities/ListLogger.cs

https://github.com/aspnet/Logging/issues/331
@anpete

React to Logging API changes

---

src/Microsoft.EntityFrameworkCore.Commands/project.json
src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore/project.json
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Commands.Tests/project.json
test/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.InMemory.Tests/project.json
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/project.json
test/Microsoft.EntityFrameworkCore.Microbenchmarks/project.json
test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.Relational.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Tests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/project.json
test/Microsoft.EntityFrameworkCore.Tests/project.json

Remove netcore50

---

src/Shared/PropertyInfoExtensions.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyDiscoveryConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/RelationshipDiscoveryConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs

Only discover properties with public getter & any setter

---

test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/InheritanceRelationshipsModelInitializer.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/NonEntityBase.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/ReferencedEntity.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs

Add additional property in function tests due to SQL CE limitation

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs

Store DefaultValue annotation of enum type as underlying type value

---

test/Microsoft.EntityFrameworkCore.Microbenchmarks/config.json

Adjust reporting name for EF Core benchmarks

[TINY] EF7 to EF Core in benchmarks

---

NuGetPackageVerifier.json
src/Microsoft.EntityFrameworkCore.Commands/Scaffolding/Internal/ReverseEngineeringGenerator.cs
src/Microsoft.EntityFrameworkCore.Commands/project.json
src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/SqliteTableSelectionSetExtensions.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore/project.json
src/dotnet-ef/project.json
test/Microsoft.EntityFrameworkCore.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Relational.FunctionalTests/project.json

Enabling xml doc generation

---

src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalLoggerExtensions.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Utilities/RelationalLoggerExtensionsTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs

Parameter logging now logs the value of byte arrays

---

src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/CSharpSnapshotGenerator.cs
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs

Resolves #4382 
This converts all the relational annotations (except sequence & `DatabaseName`) in model snapshot to fluent API.
Let me know if I missed any :smile:

Convert relational annotations to fluent api in model snapshot

---

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

SqlServer: Treat String literal as unicode by default

---

src/Microsoft.EntityFrameworkCore/Internal/ModelValidator.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/IMutableEntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKeyComparer.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyListComparer.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.FunctionalTests/Microsoft.EntityFrameworkCore.FunctionalTests.csproj
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestUtilities/ForeignKeyStrictComparer.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestUtilities/IndexComparer.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestUtilities/KeyComparer.cs
test/Microsoft.EntityFrameworkCore.Tests/Infrastructure/ModelValidatorTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/KeyConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs

Improve shadow key validation message
Fixes #3551

Allow multiple foreign keys to use the same set of properties

---

src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureBatchingTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs

Use MERGE for batch insert for Sql Server

---

src/Microsoft.EntityFrameworkCore.SqlServer.Design/SqlDataReaderExtension.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/SqlServerDatabaseModelFactory.cs

Fixes failing reveng tests on Mono.
cc @lajones

[small] Use GetValues for SqlServer reverse engineering on Mono

---

test/Microsoft.EntityFrameworkCore.FunctionalTests/IncludeTestBase.cs

Resolves https://github.com/aspnet/EntityFramework/commit/c12b548b94579e67ae8d57ec11f992e918cfea4e#commitcomment-16574796
@natemcmaster - Is there a way for me to check if this builds correctly in Linux? Would travis give answer?

Test: Make Exception message for anonymous type in include compile time

---

src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs
test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs

- AddCaching is split into 2 methods. Method useful for us AddMemoryCache
- AddLogging & AddMemoryCache methods are void functions now

Fix build break

---

test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/CodeCompilationTest.cs
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/OperationCompilationTest.cs

Skip these tests for now, tracked in #4841.

Skip failing Migration tests

---

src/dotnet-ef/OperationExecutor.cs

Set data directory to output path

---

src/Microsoft.EntityFrameworkCore.Relational/Storage/ParameterNameGenerator.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSqlGenerationHelper.cs
src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs
src/Microsoft.EntityFrameworkCore/Extensions/PropertyExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/IPropertyIndexMetadata.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Navigation.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyExtensions.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
src/Shared/SharedTypeExtensions.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/TestRelationalTypeMapper.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs

Improve perf of SqlServerTypeMapper.FindCustomMapping()
Improve perf of Property.FindContainingIndexes()
Restart parameter naming for each batch

Update pipeline hot path optimizations

---

src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/StartupInvoker.cs
test/Microsoft.EntityFrameworkCore.Commands.Tests/Design/Internal/StartupInvokerTest.cs

Commands: Set IHostingEnvironment.ContentRootPath

---

src/Microsoft.EntityFrameworkCore.Commands/Design/OperationExecutor.cs
test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Design/OperationExecutorTest.cs

Commands: Avoid serializing load exceptions across boundary

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/ConditionalRemovingExpressionVisitor.cs

[Tiny] Use hard cast in ConditionalRemovingExpressionVisitor for known expression type

---

src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/Microsoft.EntityFrameworkCore.Relational/Update/UpdateSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/OptimisticConcurrencyTestBase.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs

Avoid performing empty updates

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureBatchingTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureConnectionTest.cs

Reenable SQL Azure batching tests

---

src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs

Avoid adding redundant prefix for the shadow FK generated by convention

---

src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/DesignTimeServicesBuilder.cs
src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/StartupInvoker.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/SqlServerDesignTimeServices.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/SqliteDesignTimeServices.cs
src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs
test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/ReverseEngineering/E2ETestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/SqliteDatabaseModelFactoryTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/SqliteScaffoldingModelFactoryTest.cs
test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs

AddLogging and AddMemoryCache now support chaining again.

Use chaining for AddXxx methods now it is supported again.

---

src/Microsoft.EntityFrameworkCore.Relational/Extensions/ExpressionExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalParameterBuilder.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalTypeMapper.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/ISqlGenerationHelper.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalParameterBuilder.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSizedTypeMapping.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSqlGenerationHelper.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapper.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapperExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapping.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerMaxLengthMapping.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/GearsOfWarQueryTestBase.cs
test/Microsoft.EntityFrameworkCore.Relational.FunctionalTests/GearsOfWarQueryRelationalFixture.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalCommandBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/TestRelationalTypeMapper.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs

Infer literal/parameter's unicodeness from property

---

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/DiscriminatorConvention.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalEntityTypeBuilderAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx
src/Microsoft.EntityFrameworkCore/Internal/ModelValidator.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Infrastructure/ModelValidatorTest.cs

Validate all leaf types in hierarchies are instantiable
Validate all discriminator values are unique
Reset discriminator values when discriminator property changes
Fixes #4793
Fixes #4170
Fixes #4776

More TPH validation

---

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx
test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/SqliteModelValidatorTest.cs

Add more facet validation for shared columns

---

src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/ILinqOperatorProvider.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/LinqOperatorProvider.cs
src/Microsoft.EntityFrameworkCore/Query/ResultOperatorHandler.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/AsyncQueryTestBase.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs

Add In-Memory Support for Set Operations (e.g. Union, Intersect...)

---

test/Microsoft.EntityFrameworkCore.FunctionalTests/AsyncQueryTestBase.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/AsyncQuerySqlServerTest.cs

Fix one more of those pesky UTF-16 vs UTF-8 file encoding errors
Fix #4918 and fix #4915 
cc @Eilon (ask mode) @cesarbs

Fix file encoding on test

---

test/Microsoft.EntityFrameworkCore.FunctionalTests/Microsoft.EntityFrameworkCore.FunctionalTests.csproj
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestUtilities/Xunit/PlatformSkipConditionAttribute.cs
test/Microsoft.EntityFrameworkCore.FunctionalTests/TestUtilities/Xunit/TestPlatform.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureBatchingTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerConditionAttribute.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs

This will let us know if the scenario works while #4228 is being fixed
@natemcmaster

Make Sql Azure batching test only run on not Sql Azure

---

test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/ChangeTrackingInMemoryTest.cs

close #4457
Changes from corefx has arrived.

Test: Enable failing ChangeTrackingInMemoryTests

---

src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/HostingEnvironment.cs
src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/StartupInvoker.cs
src/Microsoft.EntityFrameworkCore.Commands/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore/project.json

Fix powershell commands.
Fix #4802 
Related pull requests for dependencies: 
https://github.com/aspnet/Common/pull/107
https://github.com/aspnet/Caching/pull/178
https://github.com/aspnet/Options/pull/137
https://github.com/aspnet/PlatformAbstractions/pull/32
https://github.com/aspnet/DependencyInjection/pull/399
https://github.com/aspnet/Logging/pull/403
https://github.com/aspnet/Microsoft.Data.Sqlite/pull/242

Cross-compile to netcore50

---

src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/StartupInvoker.cs
src/Microsoft.EntityFrameworkCore.Commands/tools/EntityFramework.psm1
src/Microsoft.EntityFrameworkCore.Commands/tools/OperationHandlers.cs
src/Microsoft.EntityFrameworkCore.Relational.Design/Internal/DesignTimeEnvironment.cs
src/Microsoft.EntityFrameworkCore.Relational.Design/Microsoft.EntityFrameworkCore.Relational.Design.csproj

Fix #5032 and #5036 
Depends on #5021 
cc @bricelam @divega

Fix powershell commands

---

src/dotnet-ef/MigrationsScriptCommand.cs

Minor tweaks to scripting migrations

---

src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/Properties/AssemblyInfo.cs

Populate Assembly Info for Specification.Tests

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs

Add test coverage for #3409 - ThenInclude on interface navigation

---

src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs
test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs

Allow AddDbContext to add context as transient or singleton

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs

Add test coverage for #3538 - projecting into subquery scalar comparison

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/LeftOuterJoinExpression.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/ISqlExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/QueryBuffer.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/ComplexNavigationsQuerySqliteTest.cs

Query: Minor code clean-ups

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs

Add test coverage for #3626 - group by on navigation properties

---

test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.csproj
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs

Add test class for misc. InMemory-specific tests with custom models
@maumar

Add test coverage for #3595 - GroupBy NullReferenceException InMemory

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Test coverage for a scenario that used to throw in beta/rc1
@maumar @divega

Add test for #3316 - Left outer join group by anonymous type

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Test case is now passing and generating expected SQL
@maumar

Enable test for #3208 - Query null semantics on .Equals with nullable params

---

test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkTestCaseDiscoverer.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkTestCaseRunner.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkVariationAttribute.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/Microsoft.EntityFrameworkCore.Microbenchmarks.Core.csproj
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/SkipForNonBenchmarkTestRuns.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/ChangeTracker/DbSetOperationTests.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/ChangeTracker/FixupTests.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/InitializationTests.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks/ChangeTracker/DbSetOperationTests.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks/ChangeTracker/FixupTests.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks/InitializationTests.cs

Increasing the work done in a number of the tests in order to get better numbers from our benchmark CI. See the individual commits for more specific details.

Various bechmark improvements

---

src/Microsoft.EntityFrameworkCore.Tools.Cli/CommonCommandOptions.cs
src/Microsoft.EntityFrameworkCore.Tools.Cli/CommonOptions.cs
src/Microsoft.EntityFrameworkCore.Tools.Cli/ExecuteCommand.cs
src/Microsoft.EntityFrameworkCore.Tools.Cli/Program.cs
src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json
src/Microsoft.EntityFrameworkCore.Tools/DispatchCommand.cs
src/Microsoft.EntityFrameworkCore.Tools/Properties/ToolsStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Tools/Properties/ToolsStrings.resx
src/Microsoft.EntityFrameworkCore.Tools/project.json

Fix https://github.com/aspnet/EntityFramework/issues/5182
cc @NTaylorMullen @Eilon

Add shared implementation of dispatching logic

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs

Add test for #4447 Where List Contains Navigation throws null ref.

---

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/InheritanceTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Query: Convert IS operator in predicate to comparison with discriminator

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs

Query: Fix 4826 - Parameterize evaluable method call expressions

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Add test for #4459 - InvalidCastException on subquery in let clause

---

EntityFramework.sln
makefile.shade
src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json
src/Microsoft.EntityFrameworkCore.Tools.Core/project.json
src/Microsoft.EntityFrameworkCore.Tools/project.json
src/Microsoft.EntityFrameworkCore/project.json

Additionally fixing some project.json warnings

Change tool package version to 1.0.0-preview1

---

src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityMaterializerSource.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityMaterializerSourceTest.cs

Throw better exception message if parameterless constructor is not found for entity type

---

src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs

redundant ?. and one potential null ref in IterateCompositePropertyExpression

[TINY] fixing resharper warnings 

---

src/Microsoft.EntityFrameworkCore/Extensions/Internal/CoreLoggerExtensions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/CoreLoggingEventId.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/IncludeSpecification.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs

Fix #5332 - Log warning when redundant includes detected.

---

src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsAddCommand.cs

tiny: fix success message for migration add

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalEntityTypeBuilderAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs

Ensure discriminator values are removed when the discriminator type is changed

---

src/Microsoft.EntityFrameworkCore.Tools.Core/Migrations/Design/CSharpSnapshotGenerator.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/project.json
test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs

This improves BuildModel_AdventureWorks time ~5x

Improve RelationshipDiscoveryConvention perf by keeping track of undiscovered properties

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs

Query: Add test for collection include with Skip/Take/FirstOrDefault

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs

[Small] Add tests for #4596 - One A to many B and one C to many B exception

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs

[Tiny] Add test for #4637 - Included entity following Skip and Take

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs

Failures introduced in ae7df9afa8008d46fdd1533c73949b2f4f489156 and 10bea84841fa845b7a500929e3f52a1e01381e47
@maumar

[Tiny] Fix IncludeSqlServerTest failuers on 2008RC2 - OFFSET not supported

---

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

SQL Server: Add missing condition to sys.default_constraints joins

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/ExpressionEqualityComparer.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Fix #4705 - NotImplementedException on GetHashCode for Invoke and Default

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/HistoryRepository.cs

Respect SqlGenerationHelper.StatementTerminator in default
HistoryRepository implementation

Fixes #5368

---

makefile.shade
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/HostingEnvironment.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/StartupInvoker.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/project.json
src/Microsoft.EntityFrameworkCore.Tools/project.json
src/Microsoft.EntityFrameworkCore/project.json

Add custom packing build step so tools can still be installed to UWP apps.

Remove cross compiling for netcore50 

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

Migrations: Don't reference new names before rename

---

src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs
test/Microsoft.EntityFrameworkCore.Tests/Extensions/QueryableExtensionsTest.cs

Possible fix for #5440 
cc @divega

Remove use of IX-Async ForEach

---

src/Microsoft.EntityFrameworkCore/Properties/Microsoft.EntityFrameworkCore.rd.xml

I was too aggressive in removing rdxml that it turns out we still need.
Fix #5517

Add runtime directive for System.Collections.ArrayList

---

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psd1
src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1

NuGet Commands: Remove Apply-Migration

---

src/Microsoft.EntityFrameworkCore.Tools.Core/Migrations/Design/CSharpHelper.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Migrations/Design/MigrationsCodeGenerator.cs
test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/CodeCompilationTest.cs

Add explicit cast to double literals in snapshots

---

src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/StartupInvoker.cs
src/Shared/SharedTypeExtensions.cs

Commands: Ignore non-loadable types

---

src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore/project.json

This builds locally but just want to make sure using the latest `System.Collections.Immutable` with a floating version is okay.
cc @pranavkm @natemcmaster.

React to update CoreCLR packages

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs
src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs

Fix #5545 - Prevent null compensation on Coalesce to avoid invalid cast

---

src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json
src/Microsoft.EntityFrameworkCore.Tools.Core/project.json
src/Microsoft.EntityFrameworkCore.Tools/project.json
src/Microsoft.EntityFrameworkCore/project.json

Description and tags for shipping packages

---

src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json

@pranavkm @rowanmiller @sebastienros

Remove duplicate packOptions in Tools.Cli project.json

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalForeignKeyAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalIndexAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalKeyAnnotations.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

Base default constraint names on column name instead of property name.

---

src/Microsoft.EntityFrameworkCore.Tools.Cli/ConsoleCommandLogger.cs
src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json
src/Microsoft.EntityFrameworkCore.Tools.Core/Microsoft.EntityFrameworkCore.Tools.Core.csproj
src/Microsoft.EntityFrameworkCore.Tools.Core/Utilities/Internal/JsonUtility.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/AspNetHostingPortableApp/Startup.cs
test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/Microsoft.EntityFrameworkCore.Tools.Core.Tests.csproj
test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/Utilities/JsonUtilityTest.cs

Remove dependency on Newtonsoft.Json from dotnet-ef

---

src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/TestPlatformHelper.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/SqlServerRequiredAttribute.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/project.json
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/EndToEndTests.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/EndToEndTests_NotSupported.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/project.json

Part of https://github.com/aspnet/PlatformAbstractions/issues/34

Replace some of PlatformAbstractions with RuntimeInformation

---

src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/StartupInvoker.cs
test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/Design/Internal/StartupInvokerTest.cs

Commands: Use implementations of IStartup if available

---

src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs

Issue #4454. After we create a database we wait for it to report as created because of the notorious issues with SQL Client/SQL Server and no process at end of pipe, etc. However, if the timeout takes a very long time, then the retry logic could make this a very, very long time. So now we give up if it seems like we have waited more than a minute and we are still getting failures.

Give up sooner if Exists is experiencing long timeouts

---

src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs

Allow decimal properties to be mapped to SQL Server Identity columns

---

src/Microsoft.EntityFrameworkCore.Relational/Update/UpdateSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/F1FixtureBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/ConcurrencyModel/Sponsor.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs

Issue 'IS NULL' instead of '= null' in condition expressions during update.

---

src/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder`.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/WarningsConfigurationBuilder.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj

Move WarningsConfigurationBuilder to Infrastructure

---

src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/QueryFlattener.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/ResultTransformingExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore/Extensions/Internal/MethodInfoExtensions.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj

Issue #5634
(Won't check this in until we have triaged that we want to do it.)

Make MethodInfoExtensions internal

---

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/PropertyEntryTest.cs

Rejecting changes when marking a property as not modified

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs

fixing failing tests on SQL 2008

---

tools/EntityFramework.targets

Fix csproj generation for sqlite3.dll

---

src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DbContextOperations.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/DbContextFactoryOptions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/IDbContextFactory.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj

Resolves #5615
Verification: Manually verified
cc @rowanmiller to review documentation

Commands: Flow app info into IDbContextFactory

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/TestPlatformHelper.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/Xunit/FrameworkSkipConditionAttribute.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkTestCaseRunner.cs
test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/project.json
test/Microsoft.EntityFrameworkCore.Tools.FunctionalTests/Design/OperationExecutorTest.cs

Use RuntimeEnvironment.Sources

---

src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DatabaseOperations.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DbContextOperations.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/StartupInvoker.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/MigrationsOperations.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Properties/ToolsCoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Properties/ToolsCoreStrings.resx
test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/Design/Internal/StartupInvokerTest.cs

Commands: Warn if an error occurs while calling Startup

---

tools/EntityFramework.targets

React to 93c8374085c100103bcfaf8c0313dd729920bc03
cc @bricelam

Fixup csproj lock file target to handle *.Sources packages

---

src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs

- Replace IX-Async Intersect with async/await impl.
cc @smitpatel

Query: Fix #5724: Intermittent failure caused by IX-Async Intersect op.

---

src/Microsoft.EntityFrameworkCore.Design/CommandLine/CommonCommandOptions.cs
src/Microsoft.EntityFrameworkCore.Design/CommandLine/ExecuteCommand.cs
src/Microsoft.EntityFrameworkCore.Design/Internal/CommonOptions.cs
src/Microsoft.EntityFrameworkCore.Design/Internal/OperationExecutor.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DatabaseOperations.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DbContextOperations.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/StartupInvoker.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/Design/MigrationsOperations.cs
src/Microsoft.EntityFrameworkCore.Tools.Core/project.json
src/Microsoft.EntityFrameworkCore.Tools/Design/OperationExecutor.cs
src/Microsoft.EntityFrameworkCore.Tools/DispatchCommand.cs
src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1
src/Microsoft.EntityFrameworkCore/Infrastructure/DbContextFactoryOptions.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/AspNetHostingPortableApp/Startup.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/AspNetHostingPortableApp/project.json.ignore
test/Microsoft.EntityFrameworkCore.Tools.FunctionalTests/TestUtilities/AppDomainOperationExecutor.cs

Fix #5726
cc @Eilon @phenning @bricelam

Use the startup project directory as the content root path

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

resolves & supersedes #5722 
@anpete @divega

Query: Convert Parameters of bool value to search condition in predicate

---

src/Microsoft.EntityFrameworkCore/ChangeTracking/ObservableHashSet.cs
src/Microsoft.EntityFrameworkCore/Extensions/Internal/MethodInfoExtensions.cs
src/Microsoft.EntityFrameworkCore/Infrastructure/ModelSource.cs
src/Microsoft.EntityFrameworkCore/Metadata/IMutableEntityType.cs

[SMALL] Fix bad xml doc comments

---

test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/project.json
test/Microsoft.EntityFrameworkCore.Microbenchmarks/project.json

Update microbenchmarks project.json to copy config to output

---

src/Microsoft.EntityFrameworkCore/project.json

cc @pranavkm @Eilon 
Parital fix for #5766

Upgrade re-linq to 2.1.1

---

test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs

Change test for product version

---

src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore/project.json

cc @natemcmaster \ @muratg \ @Eilon

Update to RTM versions

---

test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ObservableHashSetTest.cs

Issue #5711
Ran new test 10,000,000 times without error.

Fix ObservableHashSetTest

---

src/Microsoft.EntityFrameworkCore.Design/CommandLine/MigrationsScriptCommand.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/EndToEndTests.cs
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/AspNetHostingPortableApp/project.json.ignore
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/Utilities/MigrationScriptCommand.cs

Fix #5535 - script migrations ensures directory exists

---

src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteSqlGenerationHelper.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Storage/SqliteSqlGeneratorTest.cs

SQLite: Generate proper Guid literals

---

README.md

Close #5873 
Preview: https://github.com/natemcmaster/EntityFramework/blob/readme-patch-1/README.md
cc @rowanmiller

Add badges and links to packages to README.md

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationFixtureBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/DataAnnotationInMemoryFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/DataAnnotationSqliteFixture.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs

Issue #4931
Turns out we didn't have that many tests, but I ported all the relevant ones from DataAnnotationScenariosTest.

Port data annotation tests from EF6

---

src/Microsoft.EntityFrameworkCore/DbContext.cs
src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs

Identified hot spot during routine profiling.

Perf: Cache QueryProvider on DbContext

---

src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
test/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.InMemory.Tests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Tests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/project.json
test/Microsoft.EntityFrameworkCore.Tests/project.json
test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/project.json
test/Microsoft.EntityFrameworkCore.Tools.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Tools.Tests/project.json

cc @ajaybhargavb \ @natemcmaster

Updating to RTM builds of xunit and Moq

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs

Issue #5395 
Fix is to make L2O queries use InvariantCulture.

Make OrderBy tests run on machines with different culture settings

---

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/InheritanceRelationalFixture.cs

Remove SQL Server specific mapping from inheritance test base.

---

src/Microsoft.EntityFrameworkCore/EF.cs
src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs

Move EF.Property MethodInfo to common location

---

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1

Fix #5878
cc @rowanmiller @bricelam

[small] Block PMC commands on UWP class library startup projects

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs

Test for issue #6044

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Resolves #5220 
@roji - Let us know if there are more tests which are failing due to missing order by.

Query: Add OrderBy for definite results

---

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/NullSemanticsQueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs

Query: Test: Add test for ?? in where predicate translated to comparison

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs

Split relationships with the same ForeingKey attribute on both sides.

---

test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs

Test for #6067

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalMetadataItemBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyIdentity.cs

Properly handle explicit relationships in ForeignKeyAttributeConvention

---

src/Microsoft.EntityFrameworkCore/Internal/EntityFinder.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FindSqlServerTest.cs

Should make more efficient use of query cache on SQL Server.

Make Find queries parameterized

---

src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs

Fix warnings in InMemoryQueryModelVisitor

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs

Convert default values to property type when possible

---

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx
test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs

Log warning if key property has default value set

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs

Take the principal type into account when looking for existing relationship.

---

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapperExtensions.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/TestRelationalTypeMapper.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerTypeMapperTest.cs

Use value comparison for shared column default value validation

---

src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs

Populate AssemblyInfo for csprojs

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Fixes https://github.com/aspnet/EntityFramework/issues/6186

fixing failing test - adding orderby to the query so that results are deterministic

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Fixes https://github.com/aspnet/EntityFramework/issues/6186

fixing second test failing on sql 2008 - adding orderby to produce deterministic sql

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs

Test for #6212

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/IgnoredMembersValidationConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/NavigationAttributeEntityTypeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs

Throw when an inherited property or navigation is ignored

---

src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/BatchExecutor.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/BatchExecutorTest.cs

Call BeginTransactionAsync from BatchExecutor.ExecuteAsync

---

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TestSqlLoggerFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Extensions/DbCommandLogData.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalLoggerExtensions.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Utilities/RelationalLoggerExtensionsTest.cs

Logging: Log machine readable structured log entries

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Resolves #4748 
Apply search condition optimizations on join conditions

Query: Apply search condition optimizations on join conditions

---

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.resx
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

[TINY] SQL Server Migrations: Throw when RenameIndexOperation.Table unspecified

---

src/Microsoft.EntityFrameworkCore/Internal/EnumerableExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Index.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalIndexBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/ModelSnapshotTest.cs

Avoid adding indexes when covered by keys or other indexes
Fixes #5665

Add foreign key indexes using a convention

---

src/Tools.Console/Commands/DatabaseDropCommand.cs
src/Tools.Console/Reporter.cs
src/Tools.VisualStudio/tools/EntityFrameworkCore.PowerShell2.psd1
src/Tools.VisualStudio/tools/EntityFrameworkCore.PowerShell2.psm1
src/Tools.VisualStudio/tools/EntityFrameworkCore.psd1
src/Tools.VisualStudio/tools/EntityFrameworkCore.psm1
src/Tools.VisualStudio/tools/about_EntityFrameworkCore.help.txt

Close https://github.com/aspnet/EntityFramework/issues/2476
cc @bricelam

Add 'Drop-Database'

---

src/Tools.Console/Properties/AssemblyInfo.cs
src/Tools.DotNet/Properties/AssemblyInfo.cs
src/Tools.VisualStudio/Properties/AssemblyInfo.cs

Unblocks ASP.NET CI
cc @ajaybhargavb @pranavkm

Add missing assembly descriptions to tooling libraries

---

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

[TINY] SQL Server Migrations: Rebuild altered computed columns

---

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/MigrationsTestBase.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/Migrator.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/Microsoft.EntityFrameworkCore.Tools.Core.Tests.csproj

Resolve -From arguments in Script-Migration

---

makefile.shade
src/Tools.DotNet/project.nuspec
tools/CommandsPackager/CommandPackager.cs

Add package type attribute to .Tools.DotNet

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/PropertyValues.cs

Set current/original values directly from dictionary

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

This also changes the overall order from the following...
- Drop
- Alter/Create
- Rename
...to the following.
- Drop
- Rename
- Alter/Create
Fixes #6258, fixes #6340

Migrations: Refine the order of operations

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs
src/Microsoft.EntityFrameworkCore/Internal/Multigraph.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/AnnotatableExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/DebugView.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKey.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKeyExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Key.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/KeyExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Model.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ModelExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Navigation.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/NavigationExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyExtensions.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NavigationTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Utilities/MultigraphTest.cs

Issue #6304
Lazy-evaluated detailed representation including annotations as discussed, plus single line representation for standard ToString.

Expose way to get simple, human-readable, representation of the model for debugging

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKey.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs

Fix uncovered issues
This should revert the performance degradation from introducing indexes on foreign keys using conventions

Improve model building perf by recreating foreign keys less frequently

---

src/Microsoft.EntityFrameworkCore/Metadata/Builders/PropertyBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Builders/PropertyBuilder`.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs

Issue #5554
This is pure sugar for ValueGeneratedOnAddOrUpdate and IsConcurrencyToken.

Adds IsRowVersion fluent API

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry.cs

Issue #1203
A little bit more permissive than in EF6 where the we were constrained by the exceptions thrown by the original stack.

Implement EntityEntry.Reload

---

src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/MaterializerFactory.cs
src/Microsoft.EntityFrameworkCore.Relational.Design/RelationalScaffoldingModelFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Infrastructure/RelationalOptionsExtension.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/UntypedRelationalValueBufferFactoryFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Update/UpdateSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IdentityMap.cs
src/Microsoft.EntityFrameworkCore/Extensions/Internal/ExpressionExtensions.cs
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
src/Shared/SharedTypeExtensions.cs

Make appropriate use of ToList and ToArray

---

.gitignore
src/Microsoft.EntityFrameworkCore.Design.Core/Properties/DesignCoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.InMemory/Properties/InMemoryStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational.Design/Properties/RelationalDesignStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/AsyncQueryMethodProvider.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/GroupJoinInclude.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/QueryMethodProvider.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/SqlServerDesignStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/SqliteDesignStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Sqlite/Properties/SqliteStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Tools/Properties/ToolsStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Internal/CoreStrings.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyConvention.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
tools/Resources.tt

Curse that trailing whitespace character! (You may want to view the changes [ignoring whitespace changes](https://github.com/aspnet/EntityFramework/pull/6430/files?w=1))
Resolves #6420

Fix breaking API changes inadvertently introduced into the 1.0.1 branch

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/FieldMappingTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs
src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs
src/Microsoft.EntityFrameworkCore/Query/ResultOperators/Internal/IncludeResultOperator.cs
src/Microsoft.EntityFrameworkCore/Query/ResultOperators/Internal/StringIncludeExpressionNode.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/IncludeSqliteTest.cs

String based include

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/FieldMappingTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs

Add string-based Property API that does not require a type

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore/Extensions/MutableAnnotatableExtensions.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

Resolves #6102
This also includes a fair amount of cleanup to the code and generated SQL. #YakShaving

SQL Server Migrations: Rebuild indexes

---

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.resx
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs

Sql Server Migrations: Throw when altering IDENTITY

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/ExpressionEqualityComparer.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Query: Enables SQL translation of NullConditionalExpression.

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs

Current operator generation in queries is inflexible - the current logic selects an operator based only on the expression's NodeType. Cases where a different operator needs to be generated based on others factors (e.g. the expression's Type) are difficult to integrate.
A good example is string concatenation in PostgreSQL, which requires operator `|` rather than `+`. The current code hacks a special check for this directly into `DefaultQuerySqlGenerator`, defining a special ConcatOperator which can be overridden by providers. Another example is bitwise operators for boolean - PostgreSQL does not support `boolean & boolean`, so `ExpressionType.And` should be rendered as `&&` based on the expression's Type.

Make operator generation more flexible

---

src/Microsoft.EntityFrameworkCore.Design/project.json
src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore/project.json

cc @bricelam @pranavkm 
Fix the package versions ending up as 'alpha1-alpha1' on CI

Remove 'alpha1' from project.json versions

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/TestModels/SqlServerNorthwindContext.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs

Don't clean test databases created with a script.

---

src/Microsoft.EntityFrameworkCore.Design/Design/OperationExecutor.cs
src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Internal/ConfigurationFactory.cs
src/Microsoft.EntityFrameworkCore.InMemory/Query/ExpressionVisitors/Internal/InMemoryEntityQueryableExpressionVisitorFactory.cs
src/Microsoft.EntityFrameworkCore.InMemory/Storage/Internal/InMemoryDatabase.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationBuilder.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/Operations/Builders/AlterOperationBuilder.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/Operations/Builders/CreateTableBuilder.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/AsyncQueryMethodProvider.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/QueryFlattenerFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/RelationalNullsExpandingVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/QueryMethodProvider.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/QuerySqlGeneratorFactoryBase.cs
src/Microsoft.EntityFrameworkCore.Relational/RelationalModelBuilderExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational/RelationalPropertyBuilderExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalCommand.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitorFactory.cs
src/Microsoft.EntityFrameworkCore.Sqlite/Metadata/Internal/SqliteInternalMetadataBuilderExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/ExecutionStrategyExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/MutableEntityTypeExtensions.cs

Remove formatting workaround for multiline expression body methods

---

src/Microsoft.EntityFrameworkCore.Relational/Metadata/IRelationalComplexPropertyDefinitionAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalComplexPropertyDefinitionAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs
src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj
src/Microsoft.EntityFrameworkCore.Relational/RelationalMetadataExtensions.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerMetadataExtensions.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/ISqlServerComplexPropertyDefinitionAnnotations.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerComplexPropertyDefinitionAnnotations.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj
src/Microsoft.EntityFrameworkCore.Sqlite/Metadata/SqliteMetadataExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/ComplexPropertyDefinitionExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/MutablePropertyExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/PropertyBaseExtensions.cs
src/Microsoft.EntityFrameworkCore/Extensions/PropertyExtensions.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalComplexPropertyTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Microsoft.EntityFrameworkCore.Relational.Tests.csproj
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerComplexPropertyTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Microsoft.EntityFrameworkCore.SqlServer.Tests.csproj
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Metadata/SqliteComplexPropertyTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Microsoft.EntityFrameworkCore.Sqlite.Tests.csproj
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/ComplexPropertyTest.cs

Including defaults on property definitions and relational/SqlServer/Sqlite facets.
/cc @AndriySvyryd (But anyone can review)

Support for annotated facets on complex properties

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/QueryMethodProvider.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs

- Eliminated dynamic delegate creations during Include query execution.
Fix #6623

Query: Perf: Large perf improvement in Include.

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/IMutableComplexProperty.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ComplexTypeUsageExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs

Not full Migrations support--just enough to get creation of columns to work.

Initial support for creating complex type columns

---

src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/ArrayPropertyValues.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/Microsoft.EntityFrameworkCore/Extensions/Internal/ExpressionExtensions.cs
src/Microsoft.EntityFrameworkCore/project.json

Don't depend on System.Reflection.TypeExtensions

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

Migrations: Detect renamed properties

---

src/Microsoft.EntityFrameworkCore.Relational/Infrastructure/RelationalEventId.cs
src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/Migrator.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalLoggerExtensions.cs

Commands: Report SQL when verbose

---

src/Microsoft.EntityFrameworkCore.Sqlite/Metadata/Internal/SqliteFullAnnotationNames.cs
src/Microsoft.EntityFrameworkCore.Sqlite/Migrations/SqliteMigrationsSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs

SQLite: Prefix annotation names

---

src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/ModificationCommandComparer.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/ModificationCommandComparerTest.cs

Introduce a deterministic order based on key values to entities being saved

---

src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs

Better exception when Property called on navigation

---

src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
test/Microsoft.EntityFrameworkCore.Design.FunctionalTests/Migrations/CodeCompilationTest.cs

Generate using statements for namespaces of custom property types

---

src/Microsoft.EntityFrameworkCore.Design/Design/DbContextOperations.cs
src/Microsoft.EntityFrameworkCore.Design/Design/Internal/OperationLogger.cs
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/ReverseEngineering/E2ETestBase.cs
test/Microsoft.EntityFrameworkCore.Design.Tests/Design/Internal/OperationLoggerTest.cs
test/Microsoft.EntityFrameworkCore.Design.Tests/Microsoft.EntityFrameworkCore.Design.Tests.csproj

[SMALL] Commands: Dampen SQL log level

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/IForeignKeyUniquenessConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKey.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/TypeBase.cs
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/PropertyValuesInMemoryTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs

Remove FKs set by conventions when adding a key.

---

src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/ModelConfiguration.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeNameComparer.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKeyComparer.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Key.cs

And also some other metadata collections.
Issue #6295

Explicit ordering for Key.ReferencingForeignKeys

---

src/Microsoft.EntityFrameworkCore/DbContext.cs
src/Microsoft.EntityFrameworkCore/DbSet`.cs

Fix info about related entities in Attach/Update API docs

---

src/Microsoft.EntityFrameworkCore.Design/Design/Internal/ContextInfo.cs
src/Microsoft.EntityFrameworkCore.Design/Design/Internal/DatabaseOperations.cs
src/Microsoft.EntityFrameworkCore.Design/Design/Internal/DbContextOperations.cs
src/Microsoft.EntityFrameworkCore.Design/Design/Internal/IOperationReporter.cs
src/Microsoft.EntityFrameworkCore.Design/Design/Internal/MigrationInfo.cs
src/Microsoft.EntityFrameworkCore.Design/Design/Internal/MigrationsOperations.cs
src/Microsoft.EntityFrameworkCore.Design/Microsoft.EntityFrameworkCore.Design.csproj
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/ReverseEngineering/InMemoryOperationReporter.cs
test/Microsoft.EntityFrameworkCore.Design.Tests/ApiConsistencyTest.cs
test/Microsoft.EntityFrameworkCore.Design.Tests/TestUtilities/TestOperationReporter.cs

Additional verification: Tools tests pass

Design: Make more internal

---

src/Microsoft.EntityFrameworkCore.Design/Design/Internal/DatabaseOperations.cs
src/Microsoft.EntityFrameworkCore.Design/Design/OperationExecutor.cs

Dependent: aspnet/EntityFramework.Tools#11

Design: Rename to ScaffoldContext

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs

Create relationship on the derived type if the base doesn't have an inverse.

---

src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalCommand.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalCommand.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/TestRelationalCommandBuilderFactory.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs

Undo breaking change to IRelationalCommand

---

src/Microsoft.EntityFrameworkCore.Relational.Design/RelationalScaffoldingModelFactory.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerScaffoldingModelFactory.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteScaffoldingModelFactory.cs
test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/RelationalScaffoldingModelFactoryTest.cs

RevEng: Revert breaking change in RelationalScaffoldingModelFactory

---

src/Microsoft.EntityFrameworkCore.Relational.Design/Infrastructure/RelationalDesignEventId.cs
src/Microsoft.EntityFrameworkCore.Relational.Design/Internal/RelationalDesignLoggerExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational.Design/RelationalScaffoldingModelFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Infrastructure/RelationalEventId.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalConnection.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/Infrastructure/SqlServerDesignEventId.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerDatabaseModelFactory.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerScaffoldingModelFactory.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Infrastructure/SqliteDesignEventId.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteDatabaseModelFactory.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteScaffoldingModelFactory.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry.cs
src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry`.cs
src/Microsoft.EntityFrameworkCore/Extensions/PropertyBaseExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/NavigationExtensions.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyExtensions.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/BackingFieldConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/PropertyBaseTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs

Part of issue #6714
* Rename GetField to GetFieldName
* Rename navigationPropertyName to propertyName
* Update and consolidate names of design logger Ids
* Fix enum break in RelationalEventId
* Add CurrentTransaction back to IRelationalConnection (binary compat)

API review changes

---

appveyor.yml

AppVeyor: Only test against SQL Server 2014

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs

Doc comments which were missed in #6784

Add doc comments for ProjectStarAlias & related method in SelectExpression

---

src/Microsoft.EntityFrameworkCore/DbContext.cs
src/Microsoft.EntityFrameworkCore/DbSet`.cs

```
Rename dataabse into database
Fixes #6876
```
Fixes #6876

refactor: tiny typo dataabse into database

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

```
Modify sort to handle computed SQL add columns at last
Fixes #6853
```
Fixes #6853

fix(Migrations): better ordering when adding computed columns

---

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyIndexConvention.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs

Don't remove unique indexes covered by other unique indexes

---

src/Microsoft.EntityFrameworkCore.Relational/Infrastructure/RelationalServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalDatabaseProviderServices.cs
src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalDatabaseProviderServices.cs

Allow providers to replace and extend SqlTranslatingExpressionVisitor

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs

refactor(Migrations): split computed column into separate operations

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/AnnotationComparer.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/Internal/SqlServerIndexConvention.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj
src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/ConventionSet.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/IIndexAnnotationSetConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/IPropertyAnnotationSetConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Index.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs
src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
test/Microsoft.EntityFrameworkCore.Relational.Tests/Microsoft.EntityFrameworkCore.Relational.Tests.csproj
test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/ModelBuilderTest/RelationalTestModelBuilderExtensions.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Microsoft.EntityFrameworkCore.SqlServer.Tests.csproj
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/ModelBuilderTest/SqlServerModelBuilderGenericTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/ModelBuilderTest/SqlServerTestModelBuilderExtensions.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Microsoft.EntityFrameworkCore.Sqlite.Tests.csproj
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ManyToOneTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs

Set the filter for nullable unique indexes using a convention

---

src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore/Properties/AssemblyInfo.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs

Fix failing tests by updating assembly versions.
cc @JunTaoLuo

rel/1.0.2: Update assembly versions

---

src/Microsoft.EntityFrameworkCore.Design/project.json
src/Microsoft.EntityFrameworkCore.InMemory/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational.Design/project.json
src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.Relational/project.json
src/Microsoft.EntityFrameworkCore.Specification.Tests/project.json
src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.SqlServer.Design/project.json
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.SqlServer/project.json
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/project.json
src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite/project.json
src/Microsoft.EntityFrameworkCore/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore/project.json
test/Microsoft.EntityFrameworkCore.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/project.json
test/Microsoft.EntityFrameworkCore.Relational.Tests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/project.json
test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs
test/Microsoft.EntityFrameworkCore.Tests/project.json

Thanks for fixing the test @natemcmaster. The dependencies have been updated, and the version number has been bumped up to 1.0.2. Verified to build locally. 
cc @pranavkm

Updating dependencies for 1.0.2

---

src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKey.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs

Add more details to the exception message.
Fixes #6792

Move the derived foreign key properties validation to a common method.

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/Internal/ContainsTranslator.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/Internal/EndsWithTranslator.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/Internal/StartsWithTranslator.cs

Issue #6926
Add back obsolete parameterless constructors and make logging conditional.
/cc @divega

Fix breaking changes affecting SapientGuardian MySQL provider

---

src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs

Mark shadow properties created by string-based HasForeignKey as Explicit

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/EqualityPredicateInExpressionOptimizer.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/InExpression.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs

since Sql supports In with following expressions
- ParameterExpression
- ConstantExpression
- ColumnExpression
- AliasExpression
@anpete @maumar @divega

Make InExpression accept broader type of argument

---

src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalDatabaseProviderServices.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/UpdatesFixtureBase.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Infrastructure/SqlServerEventId.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Infrastructure/SqlServerModelValidator.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.resx
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerDatabaseProviderServices.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerLoggerExtensions.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/UpdatesInMemoryFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NorthwindQuerySqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NorthwindSprocQuerySqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/PropertyValuesSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerServiceCollectionExtensionsTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/UpdatesSqliteFixture.cs

Log a warning if a decimal property does not have an explicit type mapping.

---

src/Microsoft.EntityFrameworkCore.Relational.Design/Metadata/Internal/ScaffoldingFullAnnotationNames.cs
src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalFullAnnotationNames.cs
src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalEntityTypeAttributeConventionTest.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalPropertyAttributeConventionTest.cs

Make RelationalFullAnnotationNames  public

---

src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs

Allow to specify the shadow FK before configuring the primary key on the principal type.

---

src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Internal/DbContextWriter.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SqlServerReverseEngineerTestE2EContext.expected
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/AttributesContext.expected
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/FilteredIndexContext.expected
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/PrimaryKeyWithSequenceContext.expected
test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/SequenceContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/FkToAltKey/FkToAltKeyContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/ManyToMany/ManyToManyFluentApiContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/NoPrincipalPk/NoPrincipalPkFluentApiContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/OneToMany/OneToManyFluentApiContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/OneToOne/OneToOneFluentApiContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SelfRef/SelfRefFluentApiContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/FkToAltKey/FkToAltKeyContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/ManyToMany/ManyToManyAttributesContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/NoPrincipalPk/NoPrincipalPkAttributesContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/OneToMany/OneToManyAttributesContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/OneToOne/OneToOneAttributesContext.expected
test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/SelfRef/SelfRefAttributesContext.expected

fix #6686 
Diff for expected files shows generated code.

RevEng: Make OptionsBuilder Configuration conditional

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/ExistsExpression.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitor.cs

Query: Remove Mutation of SelectExpression from ExistExpression

---

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs

Query: Improve detection of composible FromSql queries

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/CompiledQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/F1FixtureBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/InheritanceRelationshipsQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeAsyncSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs

Resolves #6248 
Re-enabled some of the query tests which were already fixed.

Test: Re-enable some query tests

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyAttributeConvention.cs

Remove temporary keys created by KeyAttributeConvention

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/Internal/SqlServerValueGenerationStrategyConvention.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/DataAnnotationInMemoryTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs

This will go in 1.1.1
Part of #7010

Make DatabaseGeneratedOption.Identity attribute just set ValueGenerated to OnAdd on SQL Server

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs

Avoid infinite recursion in InversePropertyAttributeConvention

---

src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs

Throw when AddDbContext called with configuration and only parameterless constructor

---

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
test/Microsoft.EntityFrameworkCore.SqlServer.Tests/ModelBuilderTest/SqlServerModelBuilderGenericTest.cs

Run key conventions on base type set and for keys removed when an FK is detached

---

src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Additional case was when context instances are captured in method call expressions (via Set)

Query: Fixes another case of query cache keys leaking context instances (#6737)

---

src/Microsoft.EntityFrameworkCore.Design/Design/Internal/DbContextOperations.cs
test/Microsoft.EntityFrameworkCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
test/Microsoft.EntityFrameworkCore.Design.Tests/Microsoft.EntityFrameworkCore.Design.Tests.csproj

Design: Get DbContext from application services if possible

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Query: Translate Average to server

---

src/Microsoft.EntityFrameworkCore/Storage/IDatabaseProvider.cs

Fixes aspnet/EntityFramework.Docs#143

[TINY] Adjust IDatabaseProvider.IsConfigured() comment

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/BufferedEntityShaper`.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore/Query/EntityLoadInfo.cs
src/Microsoft.EntityFrameworkCore/Query/Internal/QueryBuffer.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs

[1.1.1] Query: Materialize shadow properties in derived types properly

---

src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs
test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ForeignKeyIndexConventionTest.cs
test/Microsoft.EntityFrameworkCore.Tests/Microsoft.EntityFrameworkCore.Tests.csproj

of the ForeignKey when the associated index's uniqueness changes.
Fixes #7254

Changed ForeignKeyIndexConvention to update the IsUnique property

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/Xunit/ConditionalTheoryDiscoverer.cs

Compile currently fails due to changes in xunit sdk. This fixes the code to use the new APIs.
cc @javiercn build buddy

React to changes in Xunit sdk

---

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/CompositePredicateExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/EqualityPredicateInExpressionOptimizer.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs
src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

This PR isolates one of the optimizations I made in #7543 into a smaller commit. It will shave two files off of that PR. This PR partially address #5230.

Optimize discriminator predicates into IN expressions in more cases

---

src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
src/Microsoft.EntityFrameworkCore/Properties/AssemblyInfo.cs
test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs

Forgot to update the assembly versions as part of the patch updates.

Update assembly versions to 1.1.1

---

test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs

Skip flaky tests

---

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs

fixed via resolution of #7451
close #7312

Test: Add test for issue #7312

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathTranslator.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Summary of the changes:
- Added Math.Sign -> Sql Server SIGN to SqlServerMathTranslator
- Added Where_math_sign to QueryTestBase
- Added Where_math_sign to QuerySqlServerTest
Fixes bug #7601

Added Math.Sign -> SQL Server SIGN translator

---

src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerDatabaseModelFactory.cs

(for example created by Database Tuning Advisor - DTA)
fixes #7665

Ignore hypothetical indexes

---

src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs
src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx

Update exception message to not suggest a CLR type can be mapped if the store type is changed.

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs
src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

[Tiny] Query: Add verification test for issue #7666

---

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs

Query: Add a hook to override single projection or predicate

---

src/Microsoft.EntityFrameworkCore.Sqlite.Core/Infrastructure/SqliteEventId.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Internal/SqliteModelValidator.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Migrations/Internal/SqliteMigrationsSqlGenerator.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Properties/SqliteStrings.resx
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Storage/Internal/SqliteLoggerExtensions.cs
src/Microsoft.EntityFrameworkCore.Sqlite.Core/Storage/Internal/SqliteSqlGenerationHelper.cs
test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
test/Microsoft.EntityFrameworkCore.Sqlite.Tests/SqliteModelValidatorTest.cs

Also updates Migrations to ignore EnsureSchema and DropSchema operations (fixes #6679)

SQLite: Warn when model has schema or sequence

---

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Operations/CreateIndexOperation.cs
src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/Internal/SqlServerMigrationsSqlGenerator.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs

SQL Server Migrations: Don't rebuild indexes which will be created

---

src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs
test/EFCore.Design.Tests/Design/Internal/ForwardingProxyTest.cs
test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.SqlServer.Design.FunctionalTests/EFCore.SqlServer.Design.FunctionalTests.csproj
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SqlServerReverseEngineerTestE2EContext.expected
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/AttributesContext.expected
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/EFCore.Sqlite.Design.FunctionalTests/EFCore.Sqlite.Design.FunctionalTests.csproj
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs

Generate binding redirects for tests that need it

---

build/repo.props
test/EFCore.Benchmarks.EF6/EFCore.Benchmarks.EF6.csproj
test/EFCore.Benchmarks/EFCore.Benchmarks.csproj

Make EF.Benchmarks a class library, not a test project

---

src/dotnet-ef/Project.cs
src/dotnet-ef/Resources/EntityFrameworkCore.targets
src/dotnet-ef/RootCommand.cs

Fixes #7889
Verification: Manual testing

[1.0.4] CLI Tools: Use project's runtime framework version

---

src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs
src/EFCore.Specification.Tests/QueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Fix was done in #6998
resolves #7922

Test: Add tests for nullable int/guid contains translation to server

---

.github/ISSUE_TEMPLATE.md

This was driving me crazy.
I'm not sure how you'd add tests for this, so...

Fix typo in issue template: repoduce -> reproduce

---

test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs

@AndriySvyryd  - I tried nested class approach. It did not run them in parallel.
This PR has approach to use one file but separate class for each logical group.

Test: Split SqlServerDatabaseCreator tests

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs
src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs

Fixes #7698
This is already fixed in 2.0

[1.1.2] Fix stack overflow on InversePropertyAttribute cycle.

---

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TransactionTestBase.cs
src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/BatchExecutor.cs
test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/BatchExecutorTest.cs

[1.1.2] Maintain connection state in BatchExecutor

---

build/common.props
src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
src/EFCore.Specification.Tests/LoadTestBase.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Infrastructure/CoreModelValidator.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder.cs
src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs
src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/Internal/DerivedTypeDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
src/EFCore/Metadata/Conventions/Internal/KeyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
test/EFCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
test/EFCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs
test/EFCore.Tests/ModelBuilderTest/OwnedTypesTestBase.cs

InversePropertyAttribute is not supported.

Add conventions support for owned entity types.

---

src/EFCore.Relational/Query/Internal/RelationalExpressionPrinter.cs
src/EFCore/Extensions/Internal/ExpressionExtensions.cs
src/EFCore/Query/ExpressionVisitors/EntityQueryableExpressionVisitor.cs
src/EFCore/Query/Internal/ExpressionPrinter.cs
src/EFCore/Query/Internal/QueryOptimizer.cs
src/EFCore/Query/QueryCompilationContext.cs

Follow up PR for #8061 
@anpete

Query: DRY IsEntityQueryable

---

src/EFCore.Specification.Tests/FieldMappingTestBase.cs
src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerExecutionStrategy.cs
src/EFCore/Query/EntityQueryModelVisitor.cs
src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs
src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs
src/EFCore/Query/Internal/ExpressionPrinter.cs
src/EFCore/Query/Internal/IncludeCompiler.cs
test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/WarningsSqlServerTest.cs

Leverage nav rewrite for initial creation of collection include queries.

Query: Include: Use nav rewrite to generate skeleton collection include queries.

---

src/EFCore.Relational/Query/Internal/RelationalExpressionPrinter.cs
src/EFCore/Query/Internal/ExpressionPrinter.cs
src/EFCore/Query/Internal/QueryModelPrinter.cs
test/EFCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs

- improved formatting around SQL, MethodCallExpression and result operators (in query model),
- improved display of type names in several places,
- improved display of parameters,
- consolidated DefaultCollectionPrinter and DefaultConstantPrinter,
- removed unused TrackedQuery property
- added support for IndexExpression

Various improvements to ExpressionPrinter

---

src/EFCore.Specification.Tests/QueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Scenario is now working, adding regression test.

[TINY] adding test for issue #5171

---

.gitignore
src/EFCore.Relational/Query/Expressions/SelectExpression.cs
src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
src/EFCore.Specification.Tests/IncludeTestBase.cs
src/EFCore/Query/EntityQueryModelVisitor.cs
src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs
src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTree.cs
src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs
src/EFCore/Query/Internal/IncludeCompiler.cs
test/EFCore.InMemory.FunctionalTests/ComplexNavigationsQueryInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/ComplexNavigationsQueryInMemoryTest.cs
test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
test/EFCore.Sqlite.FunctionalTests/QuerySqliteTest.cs

Handle any Include path having at most one collection include anywhere in the path.

Query: Include compiler: First part of recursive compiler

---

src/Microsoft.EntityFrameworkCore.Specification.Tests/DatabindingTestBase.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DatabindingSqlServerTest.cs
test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs

Disable flaky tests on CI

---

src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
src/EFCore.Specification.Tests/TestUtilities/Xunit/OsSkipConditionAttribute.cs
src/EFCore.Specification.Tests/TestUtilities/Xunit/WindowsVersions.cs
test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj
test/EFCore.Benchmarks.EFCore/Properties/AssemblyInfo.cs
test/EFCore.CrossStore.FunctionalTests/ConfigurationPatternsTest.cs
test/EFCore.CrossStore.FunctionalTests/EndToEndTest.cs
test/EFCore.SqlServer.Design.FunctionalTests/Properties/TestAssemblyConditions.cs
test/EFCore.SqlServer.FunctionalTests/Properties/TestAssemblyConditions.cs

Disable Sql Server tests on windows 7 & windows server 2008

---

build/repo.props
src/EFCore.Specification.Tests/TestUtilities/Xunit/OsSkipConditionAttribute.cs
test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj
test/EFCore.Benchmarks.EFCore/Properties/AssemblyInfo.cs

To unblock CI.
Filing issue for investigation.

Disbale benchmarks on netcoreapp2.0

---

build/repo.props
test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj

@divega 
Also added Build Configuration in ef ci server to build this.
Still needs to do updates to actually display results on perf site.

Enable benchmark testing on netcoreapp2.0

---

test/EFCore.SqlServer.FunctionalTests/QueryBugsTest.cs

The scenario is working in the current bits.

[TINY] enabling/fixing test for issue #7573

---

src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs
src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTree.cs
src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs
src/EFCore/Query/Internal/IncludeCompiler.cs
src/EFCore/Query/Internal/QueryBuffer.cs
test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs

Enables Includes for GroupJoin QSREs.

Query: Include compiler - enable includes on GJ QSREs.

---

src/EFCore/Query/Internal/ExpressionPrinter.cs

Before we relied on NullConditionalExpression.ToString(), however this way we would not highlight dangling qsres that were inside the NCE. Also DRYing up printing of arguments.

improvement to ExpressionPrinter for null conditional expression

---

src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs

Like in EF6 (LOL) http://entityframework.codeplex.com/SourceControl/changeset/edcc73132f64af0308e3fcf7b46ccd16202b4481
fixes #8146

Be explicit about NULL or NOT NULL

---

build/dependencies.props

See aspnet/Microsoft.Data.Sqlite#358

React to aspnet/Microsoft.Data.Sqlite#358

---

EFCore.sln.DotSettings
src/EFCore.Specification.Tests/QueryTestBase.cs
src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathTranslator.cs
test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Query: Handle type convert for Round operator

---

test/EFCore.InMemory.FunctionalTests/WarningsTest.cs

- React to https://github.com/aspnet/EntityFramework/pull/8261

Update WarningsTest for "Query: Include: Log ignored Include warnings properly in new compiler."

---

src/EFCore.SqlServer/EFCore.SqlServer.csproj
test/EFCore.Benchmarks/EFCore.Benchmarks.csproj
test/EFCore.Benchmarks/Models/AdventureWorks/TestHelpers/AdventureWorksDatabaseRequiredAttribute.cs
test/EFCore.Benchmarks/SqlServerBenchmarkResultProcessor.cs
test/EFCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs

Add switch to use native code for localdb

Upgrade to System.Data.SqlClient package 4.4.0-*

---

src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/Internal/DbContextOperations.cs
src/EFCore.Design/Design/Internal/MigrationsOperations.cs
src/EFCore.Design/Design/Internal/StartupInvoker.cs
src/EFCore.Design/Design/OperationExecutor.cs
src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/dotnet-ef/Exe.cs
src/dotnet-ef/RootCommand.cs
src/ef/AppDomainOperationExecutor.cs
src/ef/Commands/ProjectCommandBase.cs
src/ef/OperationExecutorBase.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx
src/ef/ReflectionOperationExecutor.cs
test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
test/EFCore.Design.Tests/Design/Internal/StartupInvokerTest.cs
test/ef.Tests/AppDomainOperationExecutorTest.cs
test/ef.Tests/SimpleProjectTest.cs

[2.0.0-preview1] Tools: Use project directory as working directory

---

src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.csproj
src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.nuspec
src/dotnet-ef/dotnet-ef.csproj

I have no idea how much of this will even work since it's blocked on NuGet/Home#4396. I've filed #8280 to follow up with testing after that gets fixed.

[2.0.0-preview1] Update dotnet-ef to netcoreapp2.0

---

src/EFCore.SqlServer/EFCore.SqlServer.csproj
test/EFCore.Benchmarks/EFCore.Benchmarks.csproj
test/EFCore.Benchmarks/Models/AdventureWorks/TestHelpers/AdventureWorksDatabaseRequiredAttribute.cs
test/EFCore.Benchmarks/SqlServerBenchmarkResultProcessor.cs
test/EFCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs

This reverts commit 8e0c0b2c88fc8e81d0525bc8b520e6355c9567e7.
Diagnostics broken due to this unless switch to native added.

Revert "Upgrade to System.Data.SqlClient package 4.4.0-*"

---

build/dependencies.props
src/EFCore.SqlServer/EFCore.SqlServer.csproj
test/EFCore.Benchmarks/EFCore.Benchmarks.csproj

Add switch to use native code for localdb
Port #8291 to 2.0.0-preview1
@ajcvickers @Eilon @muratg for approval.

[2.0.0-preview1] Upgrade to System.Data.SqlClient package 4.4.0-*

---

build/dependencies.props

Related: https://github.com/aspnet/BuildTools/pull/244

Update SqlitePCLRaw version

---

src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
src/EFCore/Metadata/Conventions/ConventionSet.cs
src/EFCore/Storage/ExecutionStrategy.cs

Resolves https://github.com/aspnet/EntityFramework/issues/7177 & https://github.com/aspnet/EntityFramework/issues/6828

Update errors in docs

---

src/EFCore.Relational.Design.Specification.Tests/EFCore.Relational.Design.Specification.Tests.csproj
src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs
src/EFCore.Relational.Design.Specification.Tests/TestUtilities/BuildReference.cs
src/EFCore.Relational.Design.Specification.Tests/TestUtilities/BuildSource.cs
src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Specification.Tests/DatabindingTestBase.cs
src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
src/EFCore.Specification.Tests/TestModels/ConcurrencyModel/Team.cs
src/EFCore.Specification.Tests/TestUtilities/Xunit/FrameworkSkipConditionAttribute.cs
src/EFCore/DbSet`.cs
test/EFCore.SqlServer.Design.FunctionalTests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/EFCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
test/EFCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
test/EFCore.Tests/TestUtilities/MockAssembly.cs
test/ef.Tests/AppDomainOperationExecutorTest.cs

Tests: Clean up cross-targeting

---

src/EFCore.Specification.Tests/InheritanceFixtureBase.cs

Fix race in test database creation.

Fix race in test database creation.

---

src/EFCore.Specification.Tests/AsyncQueryTestBase.cs

See #8393  will follow up with Ix-Async

Disable flaky tests

---

src/EFCore.Relational/Query/RelationalQueryContextFactory.cs

Make RelationalQueryContextFactory public.

---

.travis.yml
appveyor.yml

https://github.com/aspnet/Universe/issues/508 for EF

Build rel branches on travis & appveyor

---

src/EFCore.Relational/Query/ExpressionTranslators/Internal/StringCompareTranslator.cs
src/EFCore.Specification.Tests/QueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs

Query: Translate String.CompareTo

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

PMC Tools: Fix bug in output prefix parsing

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

PMC Tools: Allow opening projects from a file share

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

PMC Tools: Disallow Docker startup projects

---

src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsOwnedQuerySqlServerTest.cs

Update project star table correctly while eliminating join

---

EFCore.sln
build/dependencies.props
src/EFCore.ApplicationInsights/DiagnosticEventForwarder.cs
src/EFCore.ApplicationInsights/EFCore.ApplicationInsights.csproj
src/EFCore.Relational/Diagnostics/CommandData.cs
src/EFCore.Relational/Diagnostics/ConnectionData.cs
src/EFCore/Query/Internal/LinqOperatorProvider.cs
test/EFCore.ApplicationInsights.Tests/ApiConsistencyTest.cs
test/EFCore.ApplicationInsights.Tests/DiagnosticEventForwarderTest.cs
test/EFCore.ApplicationInsights.Tests/EFCore.ApplicationInsights.Tests.csproj
test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs

- Sets up the product/test projects and enables simple AI dependency forwarding of EF generated ADO events including EF correlation ids.
TBD:
- DbContext correlation? NB: ASP.NET AI integration already correlates everything at the Request level.
- Forward other events? NB. ASP.NET AI integration already forwards all logging events as AI Events and all errors as AI Errors, so it is unclear what we should do here.

Diagnostics: Initial commit of new EF.AppInsights package.

---

test/EFCore.ApplicationInsights.Tests/DiagnosticEventForwarderTest.cs

Make app insight test conditional which uses SqlServer

---

build/dependencies.props

Since it is 3rd party dependency and any updates need to be approved.

Pin version of Microsoft.AppInsights

---

src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs

Fixes #8547
Verification: Manually tested

Design: Work around dynamic binding differences

---

src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
src/EFCore.Sqlite.Core/Internal/SqliteModelValidator.cs
src/EFCore/Infrastructure/CoreModelValidator.cs
src/EFCore/Infrastructure/ModelValidator.cs

- Remove ShowError (It's not suitable for logging interception anymore)
- Make all methods "Validate..."

API review changes to ModelValidator

---

src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs
test/EFCore.Design.Tests/Design/Internal/AppServiceProviderFactoryTest.cs

Design: Default ASPNETCORE_ENVIRONMENT to Development

---

src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
src/EFCore.Relational/Query/RelationalQueryCompilationContextDependencies.cs
src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/EFCore.Relational/RelationalIndexBuilderExtensions.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/DbContext.cs
src/EFCore/Infrastructure/CoreModelValidator.cs
src/EFCore/Infrastructure/CoreOptionsExtension.cs
src/EFCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/Infrastructure/IResettableService.cs
src/EFCore/Metadata/IEntityType.cs
src/EFCore/Metadata/IMutableEntityType.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Query/ExpressionVisitors/Internal/FilterApplyingExpressionVisitor.cs
src/EFCore/Query/Internal/INodeTypeProviderFactory.cs
src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs
src/EFCore/breakingchanges.netcore.json
src/EFCore/breakingchanges.netframework.json
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.SqlServer.FunctionalTests/Utilities/TestSqlServerConnection.cs
test/EFCore.Tests/DbContextTest.cs
test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs

- Rename IResettableService.State to ResetState
- Make AddEntityFramework obsolete as an error
- Make INodeTypeProviderFactory/MethodInfoBasedNodeTypeRegistryFactory internal
- Rename filterExpression parameter to sql
- Make GenerateIsNotNull protected
- Rename to IEntityType.Filter to QueryFilter

Miscellaneous API review changes

---

src/EFCore.Design/Migrations/Design/CSharpHelper.cs
src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EFCore.Design/breakingchanges.netcore.json
src/EFCore.Design/breakingchanges.netframework.json
src/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsSqlGenerator.cs
src/EFCore/Internal/IndentedStringBuilder.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpHelperTest.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs

Migrations: Finalize CUD APIs

---

src/ef/CommandException.cs
src/ef/Commands/ProjectCommandBase.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx

Tools: Error better when Design not found

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/dotnet-ef/Properties/Resources.Designer.cs
src/dotnet-ef/Properties/Resources.resx
src/dotnet-ef/RootCommand.cs

Tools: Block .NET Standard startup projects

---

src/EFCore.Specification.Tests/TestUtilities/Xunit/ConditionalFactAttribute.cs
src/EFCore.Specification.Tests/TestUtilities/Xunit/ConditionalTheoryAttribute.cs
test/EFCore.InMemory.FunctionalTests/GearsOfWarQueryInMemoryFixture.cs
test/EFCore.SqlServer.Design.FunctionalTests/Properties/TestAssemblyConditions.cs
test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Properties/TestAssemblyConditions.cs
test/EFCore.Sqlite.FunctionalTests/GearsOfWarQuerySqliteFixture.cs

Fixup namespace changes to test projects

---

src/dotnet-ef/Project.cs

CLI Tools: Fix --configuration and --framework

---

test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs

Skip flaky test in SqlServerDatabaseCreatorExistsTest
#8615

Increase command timeout for F1SqlServerFixture

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs

Fixes #8575 
cc @laskoviymishka

Design: Fix index filter in model snapshot

---

src/EFCore.Relational/Query/ResultOperators/Internal/FromSqlExpressionNode.cs
src/EFCore.Relational/RawSqlString.cs
src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
src/EFCore.Relational/RelationalQueryableExtensions.cs

API review: rename SqlFormat to RawSqlString

---

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs

SQL Server Migrations: Only SET IDENTITY_INSERT when IDENTITY

---

src/dotnet-ef/Exe.cs
src/dotnet-ef/Project.cs

CLI Tools: Suppress MSBuild output (unless --verbose)

---

src/ef/Program.cs

ef.exe: Always use UTF-8 when redirected

---

src/EFCore.Specification.Tests/ThrowingMonsterStateManager.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Diagnostics/CoreEventId.cs
src/EFCore/Diagnostics/EntityTypesEventData.cs
src/EFCore/Diagnostics/EventDefinitionBase.cs
src/EFCore/Diagnostics/WarningsConfiguration.cs
src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
src/EFCore/Extensions/ModelExtensions.cs
src/EFCore/Internal/DiagnosticsLogger.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Metadata/Internal/TypeBase.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs

Log a warning when a DIET instance is shared.

---

src/EFCore/Extensions/ExecutionStrategyExtensions.cs
src/EFCore/Storage/ExecutionStrategy.cs

Add null checks to ExecutionStrategyExtensions

---

src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs
src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/Internal/DbContextOperations.cs
src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
src/EFCore.Design/Design/Internal/MigrationsOperations.cs
src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
src/EFCore.Design/Properties/DesignStrings.Designer.cs
src/EFCore.Design/Properties/DesignStrings.resx
src/EFCore.Relational/Diagnostics/MigrationAssemblyEventData.cs
src/EFCore.Relational/Diagnostics/RelationalEventId.cs
src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs
src/EFCore.Relational/Migrations/Internal/Migrator.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
test/EFCore.Design.Tests/TestUtilities/TestAppServiceProviderFactory.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs

Design: Log all the things

---

src/EFCore.Relational/Diagnostics/RelationalEventId.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs

Warn for non-nullable store-generated bool properties

---

src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Storage/Internal/NamedConnectionStringResolver.cs
test/EFCore.Relational.Tests/Storage/NamedConnectionStringResolverTest.cs

Throw if named connection cannot be found in configuration

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

PMC Tools: Don't terminate on logged errors

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerScaffoldingHelper.cs
src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteScaffoldingHelper.cs

RevEng: Move the . & ;

---

src/EFCore/Metadata/Internal/InternalIndexBuilder.cs
src/EFCore/Metadata/Internal/InternalKeyBuilder.cs
src/EFCore/Metadata/Internal/InternalMetadataBuilder.cs
src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs

Preserve ForeignKey annotations when rebuilding

---

src/ef/WrappedException.cs
test/ef.Tests/AppDomainOperationExecutorTest.cs
test/ef.Tests/SimpleProjectTest.cs

Tests: Reference Microsoft.Extensions.Primitives when compiling code with Roslyn

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
src/EFCore.Relational/Metadata/IMutableSequence.cs
src/EFCore.Relational/Metadata/ISequence.cs
src/EFCore.Relational/Metadata/Internal/Sequence.cs
src/EFCore.Relational/Metadata/RelationalModelAnnotations.cs
src/EFCore.Relational/Metadata/SequenceBuilder.cs
src/EFCore.Relational/RelationalModelBuilderExtensions.cs
src/EFCore.Relational/breakingchanges.netcore.json
test/EFCore.Relational.Tests/Metadata/SequenceTest.cs
test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs

Renamed RelationalSequenceBuilder to SequenceBuilder
Added IMutableSequence
Moved Sequence to .Internal namespace
Fixes #8733

Clean up Sequence Metadata API

---

src/EFCore/Internal/TypeExtensions.cs
src/EFCore/Metadata/Conventions/Internal/BackingFieldConvention.cs
src/EFCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
src/EFCore/Metadata/Internal/Property.cs
src/Shared/SharedTypeExtensions.cs
test/EFCore.Tests/Metadata/Conventions/Internal/BackingFieldConventionTest.cs

Filter out hidden fields in BackingFieldConvention

---

src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
src/EFCore.Design/Properties/DesignStrings.Designer.cs
src/EFCore.Design/Properties/DesignStrings.resx
src/EFCore.SqlServer/Properties/AssemblyInfo.cs
src/EFCore.Sqlite.Core/Properties/AssemblyInfo.cs
src/EFCore/Design/DesignTimeProviderServicesAttribute.cs
test/EFCore.Relational.Tests/Design/DesignTimeProviderServicesTest.cs

Cleanup DesignTimeServicesAttribute

---

src/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
src/EFCore/Query/EntityQueryModelVisitor.cs
test/EFCore.SqlServer.FunctionalTests/FiltersSqlServerTest.cs

- Adds a missing box operation.

[Preview2] - Fix #8630 - HasQueryFilter supporting any other type than string?

---

.travis.yml
README.md

This reverts commit d81a67f4129a14d67e4ea0ad4a6c09c18fc5aede.
Testing out current status to look into repro.

Re-enable travis CI

---

src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs

Migrations: Disable obsolete warnings in designer files

---

src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/OperationExecutor.cs
src/EFCore.Design/Scaffolding/Internal/CSharpScaffoldingGenerator.cs
src/EFCore.Design/Scaffolding/Internal/IModelScaffolder.cs
src/EFCore.Design/Scaffolding/Internal/IScaffoldingCodeGenerator.cs
src/EFCore.Design/Scaffolding/Internal/ModelScaffolder.cs
src/EFCore.Design/Scaffolding/Internal/ScaffoldingCodeGenerator.cs
test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs

RevEng: Remove unnecessary async

---

.travis.yml

[Testing] Enable OS X on travis CI

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
src/EFCore.Relational/Scaffolding/IScaffoldingProviderCodeGenerator.cs
src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerScaffoldingCodeGenerator.cs
src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteScaffoldingCodeGenerator.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs

RevEng: Add language to code generating APIs

---

src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Diagnostics/DesignEventId.cs
src/EFCore.Design/Internal/DesignLoggerExtensions.cs
src/EFCore.Design/Properties/DesignStrings.Designer.cs
src/EFCore.Design/Properties/DesignStrings.resx
src/EFCore.Design/Scaffolding/Internal/IModelScaffolder.cs
src/EFCore.Design/Scaffolding/Internal/IScaffoldingModelFactory.cs
src/EFCore.Design/Scaffolding/Internal/ModelScaffolder.cs
src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
src/EFCore.Relational.Specification.Tests/RelationalDatabaseCleaner.cs
src/EFCore.Relational/Diagnostics/RelationalEventId.cs
src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Scaffolding/IDatabaseModelFactory.cs
src/EFCore.Relational/Scaffolding/Internal/TableSelectionSet.cs
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
test/EFCore.SqlServer.Design.FunctionalTests/SqlServerDatabaseModelFactoryTest.cs
test/EFCore.SqlServer.Design.FunctionalTests/SqlServerDatabaseModelFixture.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
test/EFCore.Sqlite.Design.FunctionalTests/SqliteDatabaseModelFactoryTest.cs
test/EFCore.Sqlite.Design.FunctionalTests/SqliteScaffoldingModelFactoryTest.cs

RevEng: Make TableSelectionSet Internal

---

src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs
src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs
src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
src/EFCore.Relational/Storage/IRelationalConnection.cs
src/EFCore.Relational/Storage/Internal/RelationalCommand.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Relational/Update/Internal/BatchExecutor.cs
src/EFCore.Relational/breakingchanges.netcore.json
src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
src/EFCore/Diagnostics/EventDefinition.cs
src/EFCore/Diagnostics/EventDefinitionBase.cs
test/EFCore.Relational.Tests/RelationalConnectionTest.cs
test/EFCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.Relational.Tests/Update/BatchExecutorTest.cs
test/EFCore.SqlServer.FunctionalTests/Utilities/TestSqlServerConnection.cs
test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs

Log connection error at debug level for Exists path

---

src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx

What the customer suggested seems slightly shorter and easier to understand. It also brings back "for navigation" before the actual navigation and I removed the word "target" which didn't help IMO.

Simplified ignored include message. Fixes #7162.

---

src/EFCore.Relational/Query/ExpressionTranslators/Internal/EnumHasFlagTranslator.cs
src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
src/EFCore.Relational/Storage/RelationalTypeMapping`.cs

Query: Generate Enum constants differently

---

src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Diagnostics/CoreEventId.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/ForeignKey.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
test/EFCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/EFCore.Tests/Metadata/Internal/ModelTest.cs

Remove DIET references

---

test/EFCore.Benchmarks.EFCore/Query/QueryCompilationTests.cs

Something changed in caching which broke an assumption in our fake memory cache.

Fix #8810 - Fix error in fake memory cache impl.

---

src/EFCore/ChangeTracking/EntityEntry.cs
test/EFCore.Tests/ChangeTracking/EntityEntryTest.cs

Add tests and update docs for IsKeySet

---

build/dependencies.props
test/EFCore.Sqlite.Design.FunctionalTests/EFCore.Sqlite.Design.FunctionalTests.csproj
test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj

React to https://github.com/aspnet/Microsoft.Data.Sqlite/pull/374

Downgrade to SQLitePCLRaw 1.1.3

---

src/EFCore.Design/Design/OperationExecutor.cs
src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/ef/Commands/DbContextScaffoldCommand.cs
src/ef/Commands/MigrationsRemoveCommand.cs
src/ef/IOperationExecutor.cs
src/ef/OperationExecutorBase.cs

CLI Tools: Structure JSON of `migrations remove` and `dbcontext scaffold`

---

src/EFCore.Design/Metadata/Internal/ScaffoldingEntityTypeAnnotations.cs
src/EFCore.Design/Metadata/Internal/ScaffoldingModelAnnotations.cs
src/EFCore.Design/Metadata/Internal/ScaffoldingPropertyAnnotations.cs
src/EFCore.Relational/Metadata/RelationalAnnotations.cs
src/EFCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs
src/EFCore.Relational/Metadata/RelationalForeignKeyAnnotations.cs
src/EFCore.Relational/Metadata/RelationalIndexAnnotations.cs
src/EFCore.Relational/Metadata/RelationalKeyAnnotations.cs
src/EFCore.Relational/Metadata/RelationalModelAnnotations.cs
src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs
src/EFCore.SqlServer/Metadata/SqlServerEntityTypeAnnotations.cs
src/EFCore.SqlServer/Metadata/SqlServerIndexAnnotations.cs
src/EFCore.SqlServer/Metadata/SqlServerKeyAnnotations.cs
src/EFCore.SqlServer/Metadata/SqlServerModelAnnotations.cs
src/EFCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs

Remove RelationalAnnotations.GetAnnotation

---

src/EFCore.Relational/Storage/IRelationalTypeMapper.cs
src/EFCore.Relational/Storage/Internal/RelationalCommand.cs
src/EFCore.Relational/Storage/Internal/RelationalParameterBuilder.cs
src/EFCore.Relational/Storage/RelationalTypeMapper.cs
src/EFCore.Relational/Storage/StringTypeMapping.cs
src/EFCore.Specification.Tests/Query/QueryTestBase.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs
test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/CompiledQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.ResultOperators.cs
test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.Select.cs
test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.Where.cs
test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.cs

Always use varchar(max) or nvarchar(max) for SQL Server string command parameters

---

src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs
test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs

Add a workaround for SQL Client bug involving parameters of type date and time

---

src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Internal/PropertyExtensions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs

Validate keys are not configured as AddOrUpdate/Computed

---

src/dotnet-ef/Project.cs
src/dotnet-ef/ProjectOptions.cs
src/dotnet-ef/Properties/Resources.Designer.cs
src/dotnet-ef/Properties/Resources.resx
src/dotnet-ef/RootCommand.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx

Resolves #8479
Verification: Manually tested

CLI Tools: Add --runtime

---

.travis.yml
appveyor.yml
test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs

Increase the range of assertion in Concurrency_test()

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SqlServerReverseEngineerTestE2EContext.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/AttributesContext.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/FilteredIndexContext.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/NonNullBoolWithDefaultContext.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/PrimaryKeyWithSequenceContext.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/SequenceContext.cs
test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/SystemVersionedContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/FkToAltKey/FkToAltKeyContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/ManyToMany/ManyToManyFluentApiContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/NoPrincipalPk/NoPrincipalPkFluentApiContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/OneToMany/OneToManyFluentApiContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/OneToOne/OneToOneFluentApiContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SelfRef/SelfRefFluentApiContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/FkToAltKey/FkToAltKeyContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/ManyToMany/ManyToManyAttributesContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/NoPrincipalPk/NoPrincipalPkAttributesContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/OneToMany/OneToManyAttributesContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/OneToOne/OneToOneAttributesContext.cs
test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/SelfRef/SelfRefAttributesContext.cs

Indent warning in reveng properly

---

src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/Internal/DbContextOperations.cs
src/EFCore.Relational.Design.Specification.Tests/ReverseEngineering/E2ETestBase.cs
src/EFCore.Relational.Specification.Tests/TestSqlLoggerFactory.cs
test/EFCore.Tests/DbContextTest.cs

Remove obsolete warnings about obsolete logger APIs

---

src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs

This is a test for issue #8401, which is fixed already in the 2.0 code. The expected behavior is that the entity is in the list of those returned from the database (because it is still in the database) but is not re-fixed up to other entities.

Add test for not doing query fixup to Deleted entities

---

src/EFCore.Design/Properties/DesignStrings.Designer.cs
src/EFCore.Design/Properties/DesignStrings.resx

Design: Update "no default constructor" message

---

src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore/Internal/TypeExtensions.cs
test/EFCore.Tests/Utilities/TypeExtensionsTest.cs

Design: Handle generic types in namespace search

---

src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
src/EFCore.Specification.Tests/Query/FiltersInheritanceTestBase.cs
src/EFCore.Specification.Tests/Query/InheritanceFixtureBase.cs
src/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
src/EFCore.Specification.Tests/TestModels/Inheritance/InheritanceContext.cs
src/EFCore.Specification.Tests/TestModels/Inheritance/InheritanceModelInitializer.cs
test/EFCore.InMemory.FunctionalTests/Query/FiltersInheritanceInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/FiltersInheritanceSqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/FiltersInheritanceSqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/InheritanceSqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/InheritanceSqliteTest.cs

Since InheritanceTests modify the data causing flaky errors
Also add InheritanceTests for Sqlite
@anpete @AndriySvyryd

Test: Use different database for FiltersInheritanceTests

---

src/EFCore.Specification.Tests/Query/FiltersInheritanceTestBase.cs
src/EFCore/Internal/EntityFinder.cs

Make GetDatabaseValues call IgnoreQueryFilters()

---

src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

Create a relationship with just the inverse if an ambiguity was resolved

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs

Migrations: Store annotations present on Alternate Keys in ModelSnapshot

---

src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx

Change the exception message for underconfigured 1-to-1 relationship.

---

src/EFCore.Relational/DbFunctionAttribute.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Internal/MethodInfoExtensions.cs
src/EFCore.Relational/Metadata/Builders/DbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Conventions/Internal/RelationalDbFunctionConvention.cs
src/EFCore.Relational/Metadata/IDbFunction.cs
src/EFCore.Relational/Metadata/IMutableDbFunction.cs
src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore.Relational/Metadata/Internal/InternalDbFunctionBuilder.cs
src/EFCore.Relational/Metadata/RelationalModelAnnotations.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/RelationalModelBuilderExtensions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

I did a final sweep of DbFunctions post API review changes.

DbFunctions: Some final polishing of the code.
