dotnet/efcore

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerExtensions.cs
- src/EFCore/Update/UpdateEntryExtensions.cs
Issue #19109
* Moved to StateManager
* Implemented as ToDebugString on InternalEntityEntry
* Used for ToString on InternalEntityEntry
* Also for ToString on external EntityEntry
* Also added DebugView on InternalEntityEntry to access long form for single entry
> Update state manager debug view based on design meeting feedback

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
> Modified ALTER DATABASE statement to support complex names.

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
Per https://github.com/aspnet/EntityFrameworkCore/pull/19324#pullrequestreview-332291360
> Extract and DRY

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> Scaffold empty C# array literals correctly

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
- test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs
- test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
- test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
> Fix propagation of fixed length facet

- src/EFCore.Relational/Migrations/MigrationBuilder.cs
- src/EFCore/DeleteBehavior.cs
- src/EFCore/Infrastructure/ModelCustomizer.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
Fixes #19386
Fixes #19304
Fixes #18824
> Fix small typos in docs/strings

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
> Don't set FK properties to null when detaching principal

- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- src/EFCore/Extensions/Internal/EFPropertyExtensions.cs
- src/EFCore/Extensions/Internal/TypeExtensions.cs
- src/EFCore/Extensions/ModelExtensions.cs
- src/EFCore/Infrastructure/ExpressionExtensions.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
- src/EFCore/Metadata/Internal/TypeBase.cs
- src/EFCore/Query/EntityMaterializerSource.cs
- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/Internal/SubqueryMemberPushdownExpressionVisitor.cs
- src/EFCore/Query/QueryTranslationPreprocessor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/City.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.Tests/Metadata/Internal/PropertyAccessorsFactoryTest.cs
Part of #13610
Resolves #15799
> Query: Add indexed property support

- src/EFCore/Extensions/ConventionNavigationExtensions.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Conventions/ConventionSet.cs
- src/EFCore/Metadata/Conventions/ISkipNavigationForeignKeyChangedConvention.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ConventionScope.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.DelayedConventionScope.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
- src/EFCore/Metadata/IConventionEntityType.cs
- src/EFCore/Metadata/IConventionSkipNavigation.cs
- src/EFCore/Metadata/IMutableEntityType.cs
- src/EFCore/Metadata/IMutableSkipNavigation.cs
- src/EFCore/Metadata/ISkipNavigation.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/SkipNavigation.cs
- src/EFCore/Metadata/MemberIdentity.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
- test/EFCore.Tests/Metadata/Internal/SkipNavigationTest.cs
> Make skip navigation foreign key nullable and mutable

- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
Also dropped dynamic from entity sorters.
Resolves #19527
> Fix to #19527 - Query/Test: convert entity asserters from Action<dynamic, dynamic> to Action<object, object>

- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
> SQLite Spatial: Find SpatiaLite in framework-dependent deployments

- test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
Discovered during implementing on Npgsql
Follow-up to #19039
Apparently the guy who did the original PR didn't have cross-database firmly in mind...
> Minor fixes to migration tests

- eng/Versions.props
Release notes: https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.0-preview1.md
> Update to Microsoft.Data.SqlClient 2.0.0-preview1

- eng/Versions.props
Release notes: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md
> Update to Microsoft.Azure.Cosmos 3.6.0

- azure-pipelines.yml
> Fix Cosmos CI tests

- src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Add IEnumerable overloads of HasData to OwnedNavigationBuilders

- src/EFCore/DbContext.cs
- src/EFCore/DbSet.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Internal/DbSetSource.cs
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/IDbSetCache.cs
- src/EFCore/Internal/IDbSetSource.cs
- src/EFCore/Internal/InternalDbSet.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/DbSetSourceTest.cs
- test/EFCore.Tests/DbSetTest.cs
> Add DbSet support for shared type entity types

- src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
> Query: Remove applying default type mapping

- src/EFCore.Design/Design/ICSharpHelper.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Scaffolding/IProviderConfigurationCodeGenerator.cs
> RevEng: Minor refactorings

- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
Not sure if this is how we like to do it, let me know.
/cc @maumar
> Fix non-deterministic ordering in test

- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs
Only picks up commit for weak/owned entity. Rest of them are already in master.
Will push to master on local build pass. PR is for CLA approval.
> Merge release/3.1 to master

- test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
- Added related stubs to Sqlite and SqlServer spatial tests
Part of #19957
> Added test stubs Normalized in SpatialQueryTestBase

- src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs
- src/EFCore/Metadata/IConventionEntityType.cs
- test/EFCore.Tests/Metadata/Conventions/EntityTypeAttributeConventionTest.cs
> Metadata: Don't override KeylessAttribute with KeyAttribute

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalValueGenerationConvention.cs
- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/StoreObjectType.cs
- src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
> Allow to map an entity type to both a table and a view.

- src/EFCore.SqlServer/Metadata/Conventions/SqlServerEnumConvention.cs
> Reuse StringBuilder

- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
This is causing intermittent seg fault on Linux in Microsoft.Data.Sqlite.Tests
> Revert Improve SqliteDataRecord class efficiency

- Directory.Build.props
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/EFCore.Cosmos/EFCore.Cosmos.csproj
- src/EFCore/EFCore.csproj
- test/Directory.Build.props
- test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
> Update dependencies to 3.1.2, clean up build scripts

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Metadata/ITable.cs
- src/EFCore.Relational/Metadata/ITableIndex.cs
- src/EFCore.Relational/Metadata/IUniqueConstraint.cs
- src/EFCore.Relational/Metadata/Internal/Column.cs
- src/EFCore.Relational/Metadata/Internal/ForeignKeyConstraint.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/Table.cs
- src/EFCore.Relational/Metadata/Internal/TableIndex.cs
- src/EFCore.Relational/Metadata/Internal/TableIndexComparer.cs
- src/EFCore.Relational/Metadata/Internal/TableIndexExtensions.cs
- src/EFCore.Relational/Metadata/Internal/UniqueConstraint.cs
- src/EFCore.Relational/Metadata/Internal/UniqueConstraintComparer.cs
- src/EFCore.Relational/Metadata/Internal/UniqueConstraintExtensions.cs
- src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
- src/EFCore/Metadata/Internal/IndexComparer.cs
- src/EFCore/Metadata/Internal/KeyComparer.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
> Add TableIndex and UniqueConstraint to the relational model.

- benchmark/EF.Benchmarks.Shared/EFCoreBenchmarkRunner.cs
- benchmark/EF.Benchmarks.Shared/ParamsSummaryColumn.cs
- eng/Versions.props
> Bump BenchmarkDotNet version to 0.12.0

- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> Update SQL baseline for free-text query

- .github/ISSUE_TEMPLATE/bug_report_efcore.md
- .github/ISSUE_TEMPLATE/bug_report_sqlite.md
- .github/ISSUE_TEMPLATE/feature_request.md
And remove type-bug :trollface:
> Add customer-reported to issue templates

- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- test/EFCore.Design.Tests/Design/Internal/AppServiceProviderFactoryTest.cs
- test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
- test/EFCore.Design.Tests/TestUtilities/TestAppServiceProviderFactory.cs
> Design: Use exact IDesignTimeDbContextFactory method

- azure-pipelines.yml
Arcade takes care of these now.
> Build: Don't publish packages to AzDO twice

- src/EFCore.Design/Design/Internal/MigrationsOperations.cs
- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/ef/Commands/DatabaseUpdateCommand.Configure.cs
- src/ef/Commands/DatabaseUpdateCommand.cs
- src/ef/IOperationExecutor.cs
- src/ef/OperationExecutorBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
> Tools: Add --connection (string) to "database update"

- src/EFCore/Extensions/EntityTypeExtensions.cs
- test/EFCore.InMemory.FunctionalTests/Query/IncompleteMappingInheritanceInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/IncompleteMappingInheritanceInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalFixture.cs
- test/EFCore.Specification.Tests/Query/InheritanceFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceSqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/IncompleteMappingInheritanceSqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/IncompleteMappingInheritanceSqliteTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
> Mark discriminator mapping as complete by default

- src/EFCore/Query/EntityShaperExpression.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
> Query: Create Discriminator Condition on EntityShaper and use it in shaper

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitorDependencies.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
> Query: Bring back detailed errors logging

- src/EFCore.Relational/EFCore.Relational.csproj
- src/EFCore/EFCore.csproj
Because it is causing some issues with my IDE. :-P
> Allow switching off use of EF Analyzer in EF projects

- .editorconfig
- src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> Query: Correct translation of SqlServer ToString

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGeneratorDependencies.cs
- src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
- src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
- src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/IRelationalTypeMappingSource.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs
- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/SharedTableEntryMap.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerNetTopologySuiteTypeMappingSourcePlugin.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Updates/ProductTableView.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Updates/ProductTableWithView.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Updates/ProductViewTable.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
- test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs
- test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs
- test/EFCore.Tests/ApiConsistencyTestBase.cs
Throw if no model or types are provided
Part of #15671
> Add column types to migrations data operations

- eng/Versions.props
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
Microsoft.Azure.Cosmos changes: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md
Microsoft.Data.SqlClient changes: https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.0-preview2.md
> Update Cosmos and SqlClient

- azure-pipelines.yml
- test/EFCore.CrossStore.FunctionalTests/ConfigurationPatternsTest.cs
- test/EFCore.CrossStore.FunctionalTests/EndToEndTest.cs
> Start LocalDB early to make tests more reliable

- src/EFCore.Sqlite.Core/Query/Internal/SqliteStringMethodTranslator.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindQueryFiltersQuerySqliteTest.cs
For non-constant patterns
Fixes #20715
> Fix StartsWith on Sqlite

- src/EFCore.Relational/Migrations/Internal/MigrationsIdGenerator.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsIdGeneratorTest.cs
Add assert position at the start of the line in the RegEx.
https://github.com/dotnet/efcore/issues/20706
> Correct RegEx

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Query: Add regression test for #20731

- src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
- src/EFCore.Relational/Query/Internal/ByteArraySequenceEqualTranslator.cs
- src/EFCore.Relational/Query/Internal/CaseWhenFlatteningExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/CollectionMaterializationContext.cs
- src/EFCore.Relational/Query/Internal/ComparisonTranslator.cs
- src/EFCore.Relational/Query/Internal/ContainsTranslator.cs
- src/EFCore.Relational/Query/Internal/EnumHasFlagTranslator.cs
- src/EFCore.Relational/Query/Internal/EqualsTranslator.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
- src/EFCore.Relational/Query/Internal/GetValueOrDefaultTranslator.cs
- src/EFCore.Relational/Query/Internal/LikeTranslator.cs
- src/EFCore.Relational/Query/Internal/NullableMemberTranslator.cs
- src/EFCore.Relational/Query/Internal/QuerySqlGeneratorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalQueryContextFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalQueryTranslationPostprocessorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalQueryTranslationPreprocessorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalQueryableMethodTranslatingExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalShapedQueryCompilingExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Internal/RelationalSqlTranslatingExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Internal/ResultContext.cs
- src/EFCore.Relational/Query/Internal/ResultCoordinator.cs
- src/EFCore.Relational/Query/Internal/SelectExpressionProjectionApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/StringMethodTranslator.cs
- src/EFCore.Relational/Query/Internal/TableAliasUniquifyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/TableValuedFunctionQueryRootExpression.cs
- src/EFCore.Relational/Query/Internal/TableValuedFunctionToQueryRootConvertingExpressionVisitor.cs
- Add docs for public internal APIs
> Query: Add XML docs for relational

- eng/Version.Details.xml
- eng/Versions.props
- global.json
```sh
darc update-dependencies --channel ".NET 5 Preview 3"
```
> Update to .NET 5 Preview 3

- eng/helix.proj
> Helix: Update to .NET 5 Preview 3

- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
> Add exceptions to documentation

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
> Fix wrong "Comitted transaction" log message

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- Merges internal -> public
- Removes internal feeds from nuget.config
- Updates branding
> Update branding to 3.1.5

- test/Directory.Build.props
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalQueryAsserter.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
Wanted to get this out of the way before I change include testing infra.
> Tests: Cleanup

- src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs
> Add SqlServer transient error 10936

- .github/ISSUE_TEMPLATE/config.yml
Same as for ASP.NET (but with efcore swapped for aspnet).
> Add links to other repos to new issue flow

- src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
- src/EFCore/Infrastructure/DatabaseFacade.cs
- src/EFCore/Infrastructure/ProductInfo.cs
- src/EFCore/Metadata/Conventions/RequiredNavigationAttributeConvention.cs
- src/EFCore/Metadata/MemberIdentity.cs
- test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
Fixes #20900
Fixes #20843
Fixes #20837
Fixes #19462
Fixes #18910
> Small updates

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
> Correct ordering of check constraint creation

- src/EFCore.Relational/Metadata/IPrimaryKeyConstraint.cs
- src/EFCore.Relational/Metadata/ITable.cs
- src/EFCore.Relational/Metadata/IUniqueConstraint.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/Table.cs
- src/EFCore.Relational/Metadata/Internal/UniqueConstraint.cs
- src/EFCore.Relational/Metadata/UniqueConstraintExtensions.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
> Add IPrimaryKeyConstraint and remove UniqueConstraint.IsPrimaryKey

- Directory.Build.props
This reverts commit ee14d4c7cd7bdbc1990399fe2bdd10afe6d9c11a.
> Revert "Temporarily switch back TFMs from net5.0 to netcoreapp5.0 (#21100)"

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
> Provide hook for SQL composability checks

- src/EFCore.Relational/Diagnostics/DbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbTransactionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs
- src/EFCore.Relational/Diagnostics/Internal/DbCommandInterceptorAggregator.cs
- src/EFCore.Relational/Diagnostics/Internal/DbConnectionInterceptorAggregator.cs
- src/EFCore.Relational/Diagnostics/Internal/DbTransactionInterceptorAggregator.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
- test/EFCore.Relational.Specification.Tests/ConnectionInterceptionTestBase.cs
- test/EFCore.Relational.Specification.Tests/TransactionInterceptionTestBase.cs
> Return ValueTask in loggers and interceptors

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- src/EFCore.Relational/EFCore.Relational.csproj
- src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj
- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
(Also added a subscription to dotnet/runtime to update weekly.)
> Restart dependency flow

- src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindMiscellaneousQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryTaggingQuerySqlServerTest.cs
- Added tests for filtered include but only Where filter works for now.
Part of #20892
> Add support for split query for non-composed collections

- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
> Discover IDbContextFactory at design-time

- src/EFCore/ValueGeneration/ValueGenerator`.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
> Call the NextAsync instead of Next

- src/EFCore.Relational/Query/Internal/SplitIncludeRewritingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindStringIncludeQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerMarsEnabledTestStoreFactory.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindStringIncludeQuerySqliteTest.cs
> Query: Implement filtered include for AsSplitQuery operator

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
Fixes https://github.com/dotnet/efcore/issues/20361
> Clearly indicate that userSuppliedSearchTerm variable represents parameter for the query (Fixes #20361)

- azure-pipelines.yml
System is just slow in scheduling and running the job.
> Increase timeout for helix build

- src/EFCore/Infrastructure/IndentedStringBuilder.cs
- test/EFCore.Tests/Utilities/IndentedStringBuilderTest.cs
Part of #20409 
Update XML docs on `IndentedStringBuilder`. Plus added some more tests.
> Addresses 20409. XML docs on IndentedStringBuilder.

- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/Extensions/NavigationExtensions.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
> Correctly set IsLoaded for navigations on derived types

- src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- src/EFCore/Update/UpdateEntryExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
> Cosmos: correctly convert the id value to string

- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> Fix test ordering issue

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/ExpressionExtensions.cs
- src/EFCore.Relational/Query/ISqlExpressionFactory.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMemberTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteGeometryMemberTranslator.cs
- src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
> Query: API review changes

- src/EFCore.Cosmos/Query/Internal/SqlParameterExpression.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/ProjectionExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlParameterExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
- src/EFCore/DbFunctions.cs
- src/EFCore/EF.cs
- test/EFCore.Tests/DbFunctionsTest.cs
> Document some internal constructors

- src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
- src/EFCore/Query/Internal/CompiledQueryCache.cs
Fixes #21245
Thank god for continuous benchmarking...
> Correctly remove locks in query caches

- src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> Sqlite: Throw on blocked translation of aggregate

- test/EFCore.InMemory.FunctionalTests/Query/FiltersInheritanceQueryInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/FiltersInheritanceQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/IncompleteMappingInheritanceQueryInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/IncompleteMappingInheritanceQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceQueryInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/FiltersInheritanceQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FiltersInheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FiltersInheritanceQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/InheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/InheritanceQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTInheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTInheritanceQuerySqliteTest.cs
> Test: Add test base for TPT in InheritanceQueryTestBase

- src/EFCore.Relational/Query/SqlExpressions/CaseExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/InExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
> Query: Update documentation for different ctors of SqlExpression

- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationshipsQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTRelationshipsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/InheritanceRelationshipsQuerySqliteTest.cs
> Query: Add split query tests in TPT relationship tests

- test/EFCore.Relational.Specification.Tests/Query/TPTFiltersInheritanceQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTFiltersInheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTFiltersInheritanceQuerySqliteTest.cs
> Query: Add TPT variant for FilterInheritanceQueryTests

- eng/helix.proj
- global.json
> Update to .NET 5 Preview 6 SDK

- .github/dependabot.yml
> Auto-merge Dependabot PRs

- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
updating baselines missed in previous checkin
> fixing failing tests

- src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/Metadata/Conventions/ManyToManyAssociationEntityTypeConventionTest.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Fixes #21565 
Change the default association entity type name.
> Fix for issue 21565. Update default Join Entity name.

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
> Update branding to 3.1.7

- src/EFCore/Query/QueryableMethods.cs
> Bring back QueryableMethods

- test/EFCore.InMemory.FunctionalTests/SerializationInMemoryTest.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
- test/EFCore.Specification.Tests/SerializationTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SerializationSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/SerializationSqliteTest.cs
Fixes #21538
Also add regression test for serialization of proxies
Fixes #19403
> Move JSON serialization tests out of query tests

- src/EFCore/DbContext.cs
- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
- src/EFCore/Extensions/ModelExtensions.cs
- src/EFCore/Extensions/MutableModelExtensions.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
- src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
- src/EFCore/Metadata/IConventionModel.cs
- src/EFCore/Metadata/IModel.cs
- src/EFCore/Metadata/IMutableModel.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/Metadata/Internal/ModelTest.cs
- Make FindEntityType(Type) return null for shared type entity type
- Add IModel.IsShared(Type) API
- Flow IEntityType info in places when availble rather than doing Type based loopup
Part of #9914
> Merge to master !Old skool!

- src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
- src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Add API to allow configuration of the association entity type.

- src/EFCore/Metadata/Internal/EntityType.cs
Part of https://github.com/dotnet/efcore/issues/21674
> Reduce allocations in EntityType by short-circuiting

- src/EFCore.SqlServer/Diagnostics/Internal/SqlServerLoggingDefinitions.cs
- src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
- src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- test/EFCore.Specification.Tests/ServiceProviderFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
> Add a warning for decimal keys for SqlServer

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
> Query: Use correct column mappings for TVF/FromSql

- src/EFCore.Proxies/Proxies/Internal/IProxyFactory.cs
- src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
- src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
- src/EFCore.Proxies/ProxiesExtensions.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbSet.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Shared/PropertyInfoExtensions.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityOne.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityThree.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/SharedTypes.cs
- test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingSqlServerTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/ManyToManyTrackingSqliteTest.cs
> Support shared-type entity types in change tracking

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
> Correctly generate null literals in arrays

- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
- src/EFCore/Metadata/Builders/IConventionNavigationBuilder.cs
- src/EFCore/Metadata/Builders/IConventionSkipNavigationBuilder.cs
- src/EFCore/Metadata/Builders/NavigationBuilder.cs
- src/EFCore/Metadata/Conventions/NavigationEagerLoadingConvention.cs
- src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs
- src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalNavigationBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
> Rename IsEagerLoaded to AutoInclude

- eng/helix.proj
- global.json
- src/EFCore/ModelBuilder.cs
> Update to .NET 5.0 SDK Preview 7

- src/EFCore.Relational/Extensions/RelationalIndexBuilderExtensions.cs
> [preview8] Avoid StackOverflowException in IndexBuilder.HasName()

- src/EFCore.Relational/Extensions/RelationalIndexBuilderExtensions.cs
Local build passed, this is CLA check.
> Merge release/5.0-preview8 to main

- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
- src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/TypeMaterializationInfo.cs
- src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs
- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerSharedTableConvention.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerKeyExtensions.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
> Validate shared views

- src/EFCore.Relational/Query/RelationalParameterBasedSqlProcessor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Make ParameterBasedSqlProcessor thread safe

- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/Engine.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/TableSplittingSqliteTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
> Don't write to computed column when table splitting

- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
Simplified some things. Fixed a few issues. Removed some mostly dead code. (We'll never generate migrations for it and users are unlikely to ever manually write migrations for it.)
Part of #329
> [release/5.0-preview8] SQLite Migrations: Test table rebuilds

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Originally raised by @imba-tjd in https://github.com/dotnet/efcore/discussions/21791
> Fix Sqlite CommandType in XML docs

- src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Query/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
Feedback of #21784
Part of #21509
And the bot won the race earlier.
> Query: Change alias of the column for TPT Discriminator

- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
> Remove duplicate registration in AddEntityFrameworkDesignTimeServices

- src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs
- test/EFCore.Design.Tests/Design/Internal/AppServiceProviderFactoryTest.cs
Fixes #19903
(Note, all this code can go away after #8695)
> Tools: Default DOTNET_ENVIRONMENT to Development

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
Change Conflicting Relationship Navigation error message.
fixes #21416
> Update error message CoreStrings.ConflictingRelationshipNavigation

- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- src/EFCore/Metadata/Builders/PropertyBuilder.cs
- src/EFCore/Metadata/Builders/PropertyBuilder`.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
- test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
Fixes #21061
Fixes #21140
Fixes #15159
> Fully support base type mapping names with precision/scale/size specified separately

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindChangeTrackingQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindInMemoryContext.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindKeylessEntitiesQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindQueryInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/WithConstructorsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs
> Query: Support ToQuerySql

- src/EFCore.Relational/Migrations/MigrationBuilder.cs
> Migrations: Don't warn for existing calls to CreateCheckConstraint

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore/DbContext.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/ISaveChangesInterceptor.cs
- src/EFCore/Diagnostics/Internal/SaveChangesInterceptorAggregator.cs
- src/EFCore/Diagnostics/SaveChangesInterceptor.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- test/EFCore.InMemory.FunctionalTests/InterceptionInMemoryTest.cs
- test/EFCore.Specification.Tests/SaveChangesInterceptionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SaveChangesInterceptionSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/SaveChangesInterceptionSqliteTestBase.cs
> Add SaveChanges interceptor

- src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
For #16708
What we ultimately do will depend on further discussions after 5.0.
> Document internal classes are internal for 5.0

- src/EFCore.Relational/Migrations/MigrationCommand.cs
- src/EFCore.Relational/Storage/RelationalCommandParameterObject.cs
- test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs
> Make CommandLogger available on MigrationCommand

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
> Un-expose some methods on CSharpSnapshotGenerator

- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/ISaveChangesInterceptor.cs
- src/EFCore/Diagnostics/Internal/SaveChangesInterceptorAggregator.cs
- src/EFCore/Diagnostics/SaveChangesInterceptor.cs
- test/EFCore.Specification.Tests/SaveChangesInterceptionTestBase.cs
> Remove non-generic ValueTask from interceptors

- README.md
Read-me points to the stale 2019 weekly update issue.  This PR changes the link to the 2020 weekly update issue.
> Update weekly status updates link in readme.

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/OwnedQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Revert to 3.1 behavior
Part of #21781
> Query: Allow FromSql on owner by generating join

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
Resolves #18836
Resolves #11711
> Query: Translate GroupBy-Aggregate with condition

- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> Remove all ambiguous InverseAttribute skip navigations

- src/EFCore.Relational/Metadata/Internal/ColumnMappingBaseComparer.cs
- src/EFCore.Relational/Metadata/Internal/ColumnNameComparer.cs
- src/EFCore.Relational/Metadata/Internal/Table.cs
- src/EFCore.Relational/Metadata/Internal/TableBase.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore/Extensions/ConventionPropertyExtensions.cs
- src/EFCore/Extensions/MutablePropertyExtensions.cs
- src/EFCore/Extensions/PropertyExtensions.cs
- src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
- src/EFCore/Metadata/Conventions/TypeMappingConvention.cs
- src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
- src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs
- test/EFCore.Specification.Tests/TestUtilities/AnnotationComparer.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
- test/EFCore.Sqlite.Tests/Infrastructure/SqliteModelValidatorTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
Sort columns and column mappings for PK first
Fixes #21772
> Remove TypeMapping annotation

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryTestExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
Resolves #14003
Resolves #14155
Resolves #14489
Resolves #17421
> Add regression tests

- src/EFCore.Design/Design/ICSharpHelper.cs
- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
> RevEng: Generate lambda with good identifiers

- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/TypeIdentity.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
- Also fix issue in property mapping convention to exclude "shadow" properties on property bag which are no longer "shadow"
Resolves #21892
> Metadata: Add overloads for configuring shared type as owned type

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbContext.cs
- src/EFCore/Infrastructure/EntityFrameworkEventSource.cs
- src/EFCore/Query/Internal/CompiledQueryCache.cs
- src/EFCore/Storage/ExecutionStrategy.cs
Implemented as discussed in design
> Implement perf counters

- src/EFCore.Relational/Metadata/ITableBase.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/TableBase.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
> Add ITableBase.IsOptional

- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Relational/Migrations/Internal/Migrator.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerationOptions.cs
- src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteSqlGenerationHelper.cs
- src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/ef/Commands/MigrationsScriptCommand.Configure.cs
- src/ef/Commands/MigrationsScriptCommand.cs
- src/ef/IOperationExecutor.cs
- src/ef/OperationExecutorBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
- test/EFCore.Relational.Specification.Tests/MigrationsInfrastructureTestBase.cs
- test/EFCore.Relational.Tests/Storage/SqlGenerationHelperTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsInfrastructureSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/MigrationsInfrastructureSqliteTest.cs
> Migrations: Generate transaction statements in SQL script

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Throw if same name is specified for a different shared type owned entity type

- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
> Don't uniquify non-existing FKs

- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/TableBase.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
> Make ITableBase methods throw for entity types not mapped to the table

- src/EFCore/Internal/DbContextFactorySource.cs
> Use CreateFactory instead of CreateInstance in DbContextFactory

- eng/Version.Details.xml
- relates to recent strict coherency updates
> [release/3.1] Correct SHAs for a few dependencies

- test/EFCore.Tests/DbContextTrackingTest.cs
> React to code review comments after the bot got too eager

- Directory.Build.props
- eng/Versions.props
- eng/helix.proj
- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/SerializationTestBase.cs
- also target correct 5.0 TFM (`net5.0`)
> Update branding to 6.0.0 Alpha1

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- test/EFCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs
- test/EFCore.SqlServer.Tests/SqlServerDatabaseFacadeTest.cs
> Avoid initializing the model during DatabaseFacade.IsRelational()

- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
The exception message for actual instance has changed from emulator version.
> Fix Cosmos build break.

- test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
> Fix flakey SQLite test

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
> PMC Tools: Work around dotnet/project-system#5895

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsWeakQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
Resolves #21333
Owned ones were already added earlier.
> Add tests for split query and weak entities

- src/EFCore.Cosmos/Query/Internal/CosmosValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Relational/Metadata/ITableBase.cs
- src/EFCore.Relational/Metadata/Internal/ColumnNameComparer.cs
- src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs
- src/EFCore.Sqlite.Core/Diagnostics/Internal/UnexpectedConnectionTypeEventData.cs
- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- src/EFCore/Metadata/Internal/PropertyNameComparer.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Query/Internal/SubqueryMemberPushdownExpressionVisitor.cs
- src/Shared/Check.cs
- test/EFCore.Tests/ApiConsistencyTestBase.cs
> Be consistent about which NotNull attribute to use

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Don't use nulls for shadow properties in non-anonymous seed data

- src/EFCore.SqlServer/EFCore.SqlServer.csproj
Release Notes: https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.1.md
Part of #22198
> [release/5.0] Update to Microsoft.Data.SqlClient 2.0.1

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
> Update exception message for LogMultipleCollectionIncludeWarning

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
> Add regression test for issue#13860

- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Let's see if we still have discrepancies
Resolves #16057
> Re-enable tests for issue#16057

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> Add regression test for issue#14471

- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
> Stop repeatedly detecting changed properties on Deleted entities

- src/EFCore.Relational/Query/RelationalEvaluatableExpressionFilter.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerEvaluatableExpressionFilter.cs
- src/EFCore/Query/EvaluatableExpressionFilter.cs
- test/EFCore.Relational.Specification.Tests/Query/RelationalNorthwindDbFunctionsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindDbFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
Fixes #22317
/cc @maumar who's looking at adding test coverage for collations
> Make DbFunctions non-evaluatable

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Proxies.Tests/ProxyTests.cs
> Update exception messages

- test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryFixtureBase.cs
Adding sorting to the verification code for owned collections in the InheritanceRelationships query test infra.
> Fix to #22293 - AssertIncludeCollection ordering of elements issue

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#15215

- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
> Relax restriction on derived FKs using value-generation properties from composite keys.

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
> Exception message review (Cont.)

- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorCache.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
> Propagate identity seed and increment to sharing columns

- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
> Snapshot using comparer even when property is store-generated

- src/EFCore.Relational/Storage/RelationalCommand.cs
- test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
> Stop generating CommandError if CommandExecuted has already happened

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
- test/EFCore.Tests/EFTest.cs
> Grammar/style pass for CoreStrings

- src/EFCore.Cosmos/EFCore.Cosmos.csproj
Note, the tests build fine without a direct reference to it, so apps should too.
Part of #22231
> Remove Microsoft.Azure.Cosmos.Direct from nupkg

- src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> Handle stale skip FKs in ForeignKeyPropertyDiscoveryConvention

- eng/helix.proj
- global.json
- src/EFCore.Tools/EFCore.Tools.csproj
- src/ef/ef.csproj
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
- test/EFCore.Design.Tests/DesignExceptionTest.cs
- test/EFCore.Tests/ExceptionTest.cs
> Update to .NET SDK 5.0 RC1

- eng/helix.proj
- global.json
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Tools/EFCore.Tools.csproj
- src/ef/ef.csproj
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
- test/EFCore.Design.Tests/DesignExceptionTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Tests/ExceptionTest.cs
> Merge 5.0-rc2 to main

- src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs
> Add some docs on CommandTimeout

- src/EFCore/Infrastructure/Internal/CoreSingletonOptions.cs
- test/EFCore.Analyzers.Tests/InternalUsageDiagnosticAnalyzerTest.cs
Introduced by https://github.com/dotnet/efcore/pull/22596
> Fix analyzer test after internal type was moved

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Merge rc2 to main

- azure-pipelines.yml
- eng/Publishing.props
With Default Channel - https://dnceng.visualstudio.com/internal/_build/results?buildId=826459&view=results
Without Default Channel - https://dnceng.visualstudio.com/internal/_build/results?buildId=826457&view=results
> V3 publishing 

- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.Tests/Query/ExpressionPrinterTest.cs
> Don't print trailing comma for enumerable constants

- eng/Versions.props
- global.json
Will update the SDK version tomorrow
> Update branding to 3.1.10

- eng/helix.proj
- global.json
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
@ajcvickers @Pilchie This will eventually need to go into `release/5.0`
> [release/5.0] Update to .NET SDK 5.0 RC2

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
> Scaffold table and column description as XML comments.

- src/EFCore.Cosmos/EFCore.Cosmos.csproj
Looks like #22231 went away...
> Update to Microsoft.Azure.Cosmos 3.15.0-preview

- eng/helix.proj
You will see the change if you know where to look
> Make Helix PreCommand more restrictive

- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/DbFunction.cs
- src/EFCore.Relational/Metadata/Internal/DbFunctionParameter.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Relational.Tests/RelationalOptionsExtensionTest.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
- test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalForeignKeyBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/ModelTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
> Add more tests for exceptions

- test/EFCore.Tests/QueryProviderTest.cs
> Remove test for unsupported scenario

- test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
> is operator working for InMemory

- eng/Versions.props
- global.json
> Update branding to 3.1.11

- src/EFCore.Sqlite.Core/Query/Internal/SqliteCharMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
> Sqlite: Translate char.ToLower and ToUpper

- src/EFCore.Sqlite.Core/Extensions/SqliteDbFunctionsExtensions.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteGlobMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteHexMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSubstrMethodTranslator.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
> Sqlite: Add glob, hex & substr functions

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
> Fix collation scaffolding

- test/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> [SMALL] Fix to #23349 - Test: Implement entity sorters/asserts for Spatial test base

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/EntityShaperExpression.cs
- src/EFCore/Query/Internal/EntityMaterializerSource.cs
- src/EFCore/Query/QueryContext.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.InMemory.FunctionalTests/PropertyValuesInMemoryTest.cs
- test/EFCore.InMemory.Tests/InMemoryTransactionManagerTest.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.Tests/ChangeTracking/EntityEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
- test/EFCore.Tests/DatabaseFacadeTest.cs
- test/EFCore.Tests/DbContextOptionsTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/DbSetTest.cs
- test/EFCore.Tests/Infrastructure/EntityFrameworkServicesBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityMaterializerSourceTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
- test/EFCore.Tests/Storage/ValueComparerTest.cs
> Added testing for various negative cases

- docs/DailyBuilds.md
> Remove EF Core 5.0 daily build feed

- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
> Fix SqliteDataRecord.GetStream on attached databases

- src/EFCore/ChangeTracking/Internal/StateManager.cs
> Fix missing event source logging

- azure-pipelines.yml
- eng/helix.proj
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Resolves #19974
Resolves #20128
> Test SqlServer test on Ubuntu in helix

- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.Relational/Metadata/Internal/RelationalPropertyExtensions.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
#23473 
- Change annotation code generation for `IsFixedLength()`
> Scaffold IsFixedLength() instead of IsFixedLength(true)

- test/EFCore.Cosmos.FunctionalTests/F1CosmosFixture.cs
- test/EFCore.Cosmos.FunctionalTests/OptimisticConcurrencyCosmosTest.cs
> Re-enable Cosmos concurreny tests

- src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerIsNumericFunctionTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
Fix: https://github.com/dotnet/efcore/issues/23114
> Add EF.Functions.IsNumeric

- eng/helix.proj
https://github.com/dotnet/efcore/issues/23776
> Disable SqlServer functional tests on helix ubuntu docker

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Relational/Migrations/MigrationBuilder.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
> Fixes to database collation migrations

- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> Microsoft.Data.Sqlite: Handle eponymous virtual tables in GetSchemaTable()

- test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
> Fix non-deterministic test

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
> Fix relational overrides validation for non-inheritance case

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/post-build/publish-using-darc.ps1
- merge from internal/internal/release/5.0
- rebrand to v5.0.3
> [release/5.0] Rebrand to v5.0.3

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/SetupNugetSources.ps1
- eng/common/SetupNugetSources.sh
- global.json
> Update branding to 3.1.12

- global.json
> [release/5.0] Update to 1.0.2 SDK

- src/EFCore/Infrastructure/DatabaseFacade.cs
Fixed incorrect comment on `DatabaseFacade.RollbackTransactionAsync`.
> Fix incorrect xml doc comment on RollbackTransactionAsync

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- global.json
> Update branding to 3.1.13

- NuGet.config
- eng/Versions.props
- global.json
- merge in 5.0.3 changes
- update branding to 5.0.4
- update to 5.0.3 SDK
- also update downlevel runtimes
> Update branding to 5.0.4

- src/EFCore/Query/QueryableMethods.cs
- src/Shared/EnumerableMethods.cs
> Query: Use stronger reflection in Queryable/Enumerable methods

- test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
> Reference Web SDK in OData test project since we need MVC references

- src/EFCore/DbUpdateException.cs
- test/EFCore.Tests/ExceptionTest.cs
> Added DbUpdateException constructors that accept list of EntityEntry for Entries property

- NuGet.config
- remove remaining way user NuGet.config can infect builds
> [main] Clear disabled package sources

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
- src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
- src/EFCore/Extensions/EntityTypeExtensions.cs
- src/EFCore/Extensions/ModelExtensions.cs
- src/EFCore/Extensions/MutableEntityTypeExtensions.cs
- src/EFCore/Extensions/NavigationExtensions.cs
- src/EFCore/Extensions/PropertyBaseExtensions.cs
- src/EFCore/Extensions/PropertyExtensions.cs
- test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
- test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
Add missing relational extensions
> Unbreak API used by Scaffolding

- src/EFCore.Relational/Update/ColumnModification.cs
Introduced in 0f61aaccba94dde54ae6694c89c4dfd48b37290d
> Remove bad DebugAssert causing a stack overflow

- global.json
- dotnet/aspnetcore-internal#3783
- nothing else to do here😀
> [release/5.0] Update SDK and runtime versions

- NuGet.config
- remove remaining way user NuGet.config can infect builds
> [release/5.0] Clear disabled package sources

- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs
- src/EFCore.SqlServer/Properties/AssemblyInfo.cs
- src/EFCore.Sqlite.Core/Design/Internal/SqliteDesignTimeServices.cs
- src/EFCore.Sqlite.Core/Properties/AssemblyInfo.cs
- test/EFCore.Relational.Specification.Tests/DesignTimeTestBase.cs
- test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- test/EFCore.SqlServer.FunctionalTests/DesignTimeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
- test/EFCore.Sqlite.FunctionalTests/DesignTimeSqliteTest.cs
> Add missing design-time services

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindGroupByQueryInMemoryTest.cs
> InMemory: Preserve type to bool when applying predicate on a grouping

- src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
Ran into this in EFCore.PG, where I needed to null out some settings.
> Tiny nullability corrections

- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Update explicit throw for navigation ignored warning

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
So that referential integrity remains consistent after we start treating SelectExpression as immutable
> Query: Update table references for SelectExpression.Update method

- src/Shared/Check.cs
Add line breaks where necessary to maintain the consistency
> Minor formatting

- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryDatabase.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore/DbContext.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Metadata/IDesignTimeModel.cs
- src/EFCore/Metadata/Internal/DesignTimeModel.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
- test/EFCore.Proxies.Tests/ChangeDetectionProxyTests.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsInfrastructureTestBase.cs
- test/EFCore.Specification.Tests/FieldMappingTestBase.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/ModelSourceTest.cs
Documentation tracked by https://github.com/dotnet/EntityFramework.Docs/issues/3030
> Replace DbContext.DesignTimeModel with IDesignTimeModel service

- src/EFCore/Storage/ValueConversion/NumberToBytesConverter.cs
- test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
> Handle zero-length arrays in NumberToBytesConverter

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
> Set changed navigation property to loaded

- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTypeAliasTest.cs
> Stop appending facets to SQL Server type aliases

- azure-pipelines.yml
- eng/Versions.props
> Update branding to 3.1.15

- src/EFCore/ChangeTracking/ValueComparer.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
> Check offset when comparing DateTimeOffset

- azure-pipelines.yml
> Updating CI to set locale for ubuntu18.04.

- global.json
There are no internal commits to merge
> [release/5.0] Update SDK

- build/dependencies.props
- korebuild-lock.txt
- src/EFCore.Specification.Tests/TestUtilities/Xunit/SkippedTestCase.cs
- move to latest KoreBuild / .NET SDK
- align versions with aspnetcore updates
> [release/2.1] Bump some versions

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
> Don't consider key set if property is not set and is FK and PK is not generated

- .github/CONTRIBUTING.md
For my first(of hopefully many) pull request, I'm just adding a missing word to fix the sentence.
> Add a missing word

- test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs
> Add regression test for #22223

- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationshipsQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
> Add regression test for #19584

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
- src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
- src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
> Using duplicate words in a comments

- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqlitePropertyExtensions.cs
> Merge conditional ?: expression into conditional access

- src/EFCore/DbContextOptionsBuilder`.cs
> Fix typo in xmldocs

- .github/CONTRIBUTING.md
Please check if the PR fulfills these requirements
- Added a link to a video where Entity Framework Core team members guide you through the process of contributing and provide advise and good practices.
Review the guidelines for [contributing](CONTRIBUTING.md) for more details.
> Updated "How To Contribute" doc to include video from EF Core team

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Design/Internal/MigrationsOperations.cs
- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
- src/EFCore.Design/Scaffolding/ModelCodeGenerationOptions.cs
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Project.cs
- src/dotnet-ef/Resources/EntityFrameworkCore.targets
- src/dotnet-ef/RootCommand.cs
- src/ef/AppDomainOperationExecutor.cs
- src/ef/Commands/ProjectCommandBase.cs
- src/ef/OperationExecutorBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
- src/ef/ReflectionOperationExecutor.cs
- test/EFCore.Design.Tests/Design/Internal/DatabaseOperationsTest.cs
- test/EFCore.Design.Tests/Design/Internal/MigrationsOperationsTest.cs
- test/EFCore.Design.Tests/TestUtilities/TestDatabaseOperations.cs
- test/EFCore.Design.Tests/TestUtilities/TestMigrationsOperations.cs
Manually verified that `--nullable` is passed from both PMC and dotnet-ef.
Part of #15520, part of #18950
> Flow project's nullable setting into design-time code

- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
> Bump SQLitePCLRaw to 2.0.5-pre20210521085756

- src/EFCore.Relational/Metadata/Internal/DbFunction.cs
- test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
> Make DbFunction.HasSchema(null) always override the attribute

- src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Tests/Migrations/MigrationCommandExecutorTest.cs
> Allow to run migrations inside of a user transaction

- src/EFCore.SqlServer/EFCore.SqlServer.csproj
Release notes: https://github.com/dotnet/SqlClient/tree/main/release-notes/3.0
GA release date: Estimated for May 2021
> Bump Microsoft.Data.SqlClient to 3.0.0-preview3.21140.5

- Directory.Build.targets
- eng/Version.Details.xml
- eng/Versions.props
- eng/helix.proj
- global.json
- src/EFCore/EFCore.csproj
Having this seems to cripple the experience of running and debugging tests in Visual Studio.
> Stop flowing Microsoft.NETCore.App

- .github/dependabot.yml
- src/EFCore.SqlServer/EFCore.SqlServer.csproj
> Revert to Microsoft.Data.SqlClient 2.x

- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Follow-up to #25086
Thanks to @Tommigun1980 for flagging in https://github.com/dotnet/efcore/commit/2c7670fc40bbfb95040e754ab0a9c86215ffc2a4#r52177633
> Test fixup

- eng/Versions.props
- dotnet/aspnetcore-internal#3870
> Update branding to 6.0.0-rc1

- src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
> Fix the return type of OwnedNavigationBuilder.HasIndex

- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs
- src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
- src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
- src/EFCore.SqlServer.NTS/Infrastructure/Internal/SqlServerNetTopologySuiteOptionsExtension.cs
- src/EFCore.Sqlite.NTS/Infrastructure/Internal/SqliteNetTopologySuiteOptionsExtension.cs
- src/EFCore/DbContextOptions.cs
- src/EFCore/DbContextOptions`.cs
- src/EFCore/Diagnostics/WarningsConfiguration.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Infrastructure/DbContextOptionsExtensionInfo.cs
- src/EFCore/Internal/ServiceProviderCache.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
- test/EFCore.Relational.Tests/RelationalConnectionTest.cs
- test/EFCore.Specification.Tests/LoggingTestBase.cs
- test/EFCore.Tests/DbContextOptionsTest.cs
- test/EFCore.Tests/ServiceProviderCacheTest.cs
> Store options in ServiceProviderCache

- src/EFCore.InMemory/Design/Internal/InMemoryCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.InMemory/Design/Internal/InMemoryDesignTimeServices.cs
- src/EFCore.Relational/Design/EntityFrameworkRelationalDesignServicesBuilder.cs
- src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies.cs
- src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs
- src/EFCore.Sqlite.Core/Design/Internal/SqliteCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.Sqlite.Core/Design/Internal/SqliteDesignTimeServices.cs
- src/EFCore/Design/EntityFrameworkDesignServicesBuilder.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGeneratorDependencies.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGeneratorParameters.cs
- src/EFCore/Design/Internal/ICSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Diagnostics/UpdateEntryEventData.cs
- test/EFCore.Cosmos.FunctionalTests/CosmosApiConsistencyTest.cs
- test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
Make UpdateEntryEventData derive from DbContextEventData
Part of #24743
> Make CSharpRuntimeAnnotationCodeGenerator and friends internal

- src/EFCore.Relational/Diagnostics/Internal/RelationalCommandDiagnosticsLogger.cs
- src/EFCore.Relational/Diagnostics/Internal/RelationalConnectionDiagnosticsLogger.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
> Make DefaultLoggingCacheTime private

- src/EFCore/Infrastructure/AnnotatableBase.cs
> Make the annotations SortedDictionary use ordinal ordering

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Storage/IRelationalTypeMappingSource.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Metadata/IModel.cs
- src/EFCore/Metadata/IPropertyTypeConfiguration.cs
- src/EFCore/Metadata/IReadOnlyProperty.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/ModelConfiguration.cs
- src/EFCore/Metadata/Internal/PropertyConfiguration.cs
- src/EFCore/Metadata/RuntimeModel.cs
- src/EFCore/Metadata/RuntimePropertyTypeConfiguration.cs
- src/EFCore/Storage/ITypeMappingSource.cs
- src/EFCore/Storage/TypeMappingInfo.cs
- src/EFCore/Storage/TypeMappingSource.cs
- src/EFCore/Storage/TypeMappingSourceBase.cs
- src/Shared/SharedTypeExtensions.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs
- test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
> Allow TypeMappingSource to use the pre-convention configuration

- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/DatabaseProvider.cs
- src/EFCore/Storage/IDatabaseProvider.cs
- test/EFCore.InMemory.FunctionalTests/LoggingInMemoryTest.cs
- test/EFCore.Specification.Tests/LoggingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/LoggingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/LoggingSqliteTest.cs
- test/EFCore.Tests/DbContextLoggerTests.cs
> Log provider version in addition to EF Core version

- src/EFCore.Cosmos/Query/Internal/CosmosDateTimeMemberTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindWhereQuerySqliteTest.cs
Part of the cosmos method translations
> Add translation for DateTime.UtcNow

- eng/Versions.props
TODOs:
- TFM update - this can come once 6.0 work calms down & we have a 7.0 SDK available
CC @mmitche 
Will merge this after main gets forked for RC1
> Update branding to 7.0.0-alpha1

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
And simplify the SQL a bit.
Fixes #25567
> Correct FromSqlRaw docs

- test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
> Query: Add regression test for Contains on skip collection navigation

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToMany.cs
> Undelete an entity when it has been orphaned and then reparented

- src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Closes #25624
Merged #25626 for RC1
Fixes #25624
> Disable nullability in migrations (RC1)

- src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Disable nullability in migrations

- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
> Query: Add regression test for #21036

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Query: Add regression test for #18658

- src/EFCore.Cosmos/ChangeTracking/Internal/NullableListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/SingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
> Fix Cosmos update exception wrapping

- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
> Query: Re-enable fixed test

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
> Fix nullability in compiled model

- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
> Query: Add regression test for #12329

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Add MigrationsModelDiffer tests for propagating facets

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
to improve nav expansion debugging
> [SMALL] Fully printing include tree structure

- src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
> Configure self-referencing navigations when disambiguated by ForeignKey attributes

- src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
> Change Cosmos FromSqlRaw to be over DbSet

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Enable test for Projecting_column_with_value_converter_of_ulong_byte_array

- test/EFCore.InMemory.FunctionalTests/GraphUpdates/ProxyGraphUpdatesInMemoryTest.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/ProxyGraphUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdates/ProxyGraphUpdatesSqliteTest.cs
> Add regression test for cycle detection using lazy-loading proxies

- azure-pipelines.yml
The yaml changes made in #25808 cause the internal build to fail. Fixing it
```
- Detail 1
- Detail 2
```
> Fix pipeline yaml

- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerRetryingExecutionStrategy.cs
> Update SQL Server transient error list

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
> Query: Add regression test for #23658

- src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
> Convert Int32 identity seed value

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Update/UpdateEntryExtensions.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
> Reset unknown original value when current value is set

- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/IColumn.cs
> Fix doc typo

- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RawSqlServerTest.cs
> Readd test for obsolete ToQuery

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/ICosmosClientWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/FindCosmosTest.cs
> Cosmos: return null instead of throwing from Find

- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Add test for scaffolding multiple indexes on the same column

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StoreGeneratedValuesFactoryFactory.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/IRuntimeEntityType.cs
- src/EFCore/Metadata/RuntimeEntityType.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
> Store store-generated FK values in the store-generated snapshot

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
> Support no termination in SQL Server CREATE TABLE migration operation

- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.Specification.Tests/ValueConvertersEndToEndTestBase.cs
> Add convert node to snapshot expression when needed

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Query: Convert enum value to integer when printing constant as needed

- src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
> Fixup to index filter validation

- azure-pipelines-richnav.yml
- azure-pipelines.yml
> Switch to R&D pools on main

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Make compiled model classes public and supporting classes internal

- src/EFCore/Metadata/Internal/PropertyConfiguration.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
> Apply pre-convention value converters on nullable types

- src/EFCore.SqlServer/Query/Internal/SqlServerMathTranslator.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
> Query: Convert result of Round appropriately for MathF functions

- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
> Query: Add regression test for #24657

- test/EFCore.InMemory.FunctionalTests/Query/NorthwindMiscellaneousQueryInMemoryTest.cs
> Query: Enable test for #24291

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SpatialQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryRelationalFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Resolves #17540
Resolves #22692
> Query: Re-enable few tests

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
> Better exception message when switching from owned to non-owned configuration

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
> Query: Add regression test for #19726

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
> Query: Extract join predicate from Having for group by aggregate queries

- azure-pipelines.yml
Blocked by https://github.com/dotnet/core-eng/issues/14346
> Remove OSX from helix build (temporarily)

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
> Fix adding value-converted rowversion column

- src/dotnet-ef/RootCommand.cs
> Tools: Pass absolute project paths to ef.exe

- global.json
- forgot this when handling merge
> Update to 5.0.7 SDK and 3.1.19 runtimes

- global.json
- forgot this when handling merge
> Update to 3.1.119 SDK and 2.1.30 runtime

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
The issue has already been fixed.
Resolves #25315
> [6.0-rc2] Add regression test for #25315 - Unable to translate collection subquery in projection

- test/EFCore.Specification.Tests/ManyToManyFieldsLoadTestBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyFieldsModel/ManyToManyData.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
- test/EFCore.SqlServer.FunctionalTests/ManyToManyFieldsLoadSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalManyToManyQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalManyToManyQuerySqlServerTest.cs
> Query: Fix temporal table tests

- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
We already have regression tests for most of the scenarios mentioned in the issue report. Adding the one scenario that was missing.
Resolves #15279
> [6.0-rc2] Adding regression test for #15279

- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> Add regression test for HasMany on keyless entity

- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> ModelBuilding: Add regression test for #18149

- eng/Versions.props
- dotnet/aspnetcore-internal#3946
> Update branding to 6.0.1

- src/EFCore.InMemory/Design/Internal/InMemoryDesignTimeServices.cs
- src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
- src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
- src/EFCore.InMemory/Infrastructure/InMemoryDbContextOptionsBuilder.cs
- src/EFCore.InMemory/Infrastructure/Internal/InMemoryModelValidator.cs
- src/EFCore.InMemory/Query/Internal/CollectionResultShaperExpression.cs
- src/EFCore.InMemory/Query/Internal/EntityProjectionExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.Helper.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitorFactory.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryExpressionVisitorFactory.cs
- src/EFCore.InMemory/Query/Internal/InMemoryTableExpression.cs
- src/EFCore.InMemory/Query/Internal/SingleResultShaperExpression.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryDatabase.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryDatabaseCreator.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTableFactory.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
- src/EFCore.InMemory/ValueGeneration/Internal/InMemoryIntegerValueGenerator.cs
- src/EFCore.InMemory/ValueGeneration/Internal/InMemoryValueGeneratorSelector.cs
> Evolve null-checking approach in EFCore.InMemory

- src/EFCore.Proxies/ProxiesExtensions.cs
- src/EFCore.Proxies/ProxiesServiceCollectionExtensions.cs
- src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteDbContextOptionsBuilderExtensions.cs
- src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryCollectionMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryCollectionMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerLineStringMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerLineStringMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerMultiLineStringMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerPointMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerPolygonMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerPolygonMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerNetTopologySuiteTypeMappingSourcePlugin.cs
- src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuiteDbContextOptionsBuilderExtensions.cs
- src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteGeometryCollectionMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteGeometryCollectionMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteGeometryMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteGeometryMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteLineStringMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteLineStringMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteMultiLineStringMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqlitePointMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqlitePolygonMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqlitePolygonMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteNetTopologySuiteTypeMappingSourcePlugin.cs
> Evolve null-checking approach in extensions

- src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
> Query: More VB CompareString normalization

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Applied @AndriySvyryd's suggestion from https://github.com/dotnet/efcore/issues/25815#issuecomment-922612451.
Closes #25815
> Make concurrent test use different connections

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
As this is being considered for servicing, I went with the least invasive/risky option, and introduced read/write locking. Using a ConcurrentDictionary is definitely possible, but would require other changes - specifically in how pruning is implemented. We can clean this up and improve for 7.0. I couldn't repro this in some quick testing efforts (tricky concurrency issue), if we think it's really worth it I can spend more time on it.
Fixes #26612
Locking is missing when looking up a pool group in a Dictionary in SQLite's pooling implementation.
If code happens to look up a pool group at the same time as a modification of the pool group dictionary is happening (e.g. opening a connection with a new connection string), an exception may be thrown (or in …
> [6.0.1] Use read-write lock to protect concurrent pool accesses

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
> Revert SQLite concurrent pool access change

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
Hi there
This PR closes #26283
> Cache Eventargs in SQLiteConnection

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
> Cache ParamCount together with a statement for SQLite

- azure-pipelines.yml
Testing out on main.
Do we need to update the same in previous release branches?
> Update to Mac 11 image

- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsCollectionsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsSharedTypeQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindGroupByQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsSharedTypeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
> No skipped complex navigation tests

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Dealing with this is tracked by #26763
> Skip flaky SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841

- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
```
- Detail 1
- Detail 2
Fixes #26742
```
> test and fix for Issue #26742

- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
- src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
- src/EFCore/Query/ExpressionPrinter.cs
After https://github.com/dotnet/efcore/pull/26806
> Tiny cleanup

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Storage/DoubleTypeMapping.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/dotnet-ef/Exe.cs
> Static analysis: use char instead of string literals

- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> Don't discover navigations to Dictionary<> and non-owned STETs

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerTemporalConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
> Static analysis: use null propagation

- azure-pipelines.yml
> [release/3.1] Update to Mac OS 11 image

- azure-pipelines.yml
> [release/5.0] Update to Mac OS 11 image

- azure-pipelines.yml
> [release/6.0] Update to Mac OS 11 image

- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Relational/Storage/RelationalTransaction.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
> Static analysis: using declarations and await using

- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
> Add regression tests for Count after GroupBy

- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- src/EFCore/Storage/ExecutionStrategy.cs
- src/Shared/ExpressionExtensions.cs
> Static analysis: revert tail recursion unrolling

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpressionBase.cs
> Static analysis: protect against mutating fields in hash calculations

- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/NonRetryingExecutionStrategy.cs
Fix spelling in LoggingDefinitions.LogSaveChangesCanceled.
Add a sugar constructor to NonRetryingExecutionStrategy.
> Fix spelling in LoggingDefinitions.LogSaveChangesCanceled.

- src/ef/ReflectionOperationExecutor.cs
> Tools: Use App.config on .NET Core

- eng/helix.proj
- src/EFCore.SqlServer/EFCore.SqlServer.csproj
> Update to SqlClient 4.0

- eng/Versions.props
Update to `preview1` in advance of the snap tomorrow.
> Update branding to preview1

- azure-pipelines.yml
- follow-up on bb7c910644aa
- unclear how CI validation worked in #27239
> [main] Fix build break

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/EntityEntryGraphNode`.cs
> Correct TrackGraph nullability

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindKeylessEntitiesQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindMiscellaneousQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindAsNoTrackingQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAsNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindWhereQuerySqliteTest.cs
Converting Northwind query tests to query infra.
Fixes #27229
> Fix to #27229 - Test: Convert query tests to conditional theory

- build/templates/default-build.yml
- version of VisualStudio is out of support
> [release/2.1] Stop building w/ VS2017 in CI

- azure-pipelines.yml
- version of VisualStudio is out of support
> [release/3.1] Stop building w/ VS2017 in CI

- azure-pipelines.yml
- version of VisualStudio is out of support
> [release/5.0] Stop building w/ VS2017 in CI

- src/EFCore.Design/Scaffolding/TemplatedModelGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/TextTemplatingModelGeneratorTest.cs
> Scaffolding: Use "CodeTemplates" directory

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
- src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Part of #3170
Also fix some API review issues
Seeding will be done in a separate PR as it requires update pipeline support
> Add TPC support for migrations

- eng/Version.Details.xml
- eng/Versions.props
- src/EFCore/EFCore.csproj
Fixes https://github.com/dotnet/efcore/issues/27715.
```
- Detail 1
- Detail 2
```
> Remove needless package references in EFCore.

- test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
Resolves a Component Governance bug
> [release/6.0] Update Grpc.AspNetCore dependency

- src/EFCore.Relational/Storage/RelationalDataReader.cs
- test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
> Reset read count on RelationalDataReader

- eng/Versions.props
- test/EFCore.Analyzers.Tests/UninitializedDbSetDiagnosticSuppressorTest.cs
And "skip" suppressor tests which depend on it.
See #27895
> Downgrade Microsoft.CodeAnalysis.CSharp

- src/EFCore/Diagnostics/IInterceptorAggregator.cs
> [Typo] Cleanup trailing end tag in documentation

- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- src/EFCore.SqlServer/EFCore.SqlServer.csproj
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Dependabot struggles with prerelease versions...
> Bump Microsoft.Data.SqlClient and SQLitePCLRaw

- docs/getting-and-building-the-code.md
> Update test instructions and remove 2.2

- test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
Conflicting PR made SQL baselines outdated.
> Update SQL baselines

- src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
- src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
This is non-breaking change. Next PR will submit potentially breaking changes in RelationalCommandCache area
> Query: Minor refactoring in shaper

- eng/Versions.props
- part of dotnet/aspnetcore-internal#4071
> Update branding to 7.0.0-preview6

- src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteEvaluatableExpressionFilterPlugin.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteMethodCallTranslatorPlugin.cs
> Explicitly exclude MSSQL NTS EF.Functions from parameter extraction

- eng/Versions.props
- part of dotnet/aspnetcore-internal#4089
> Update branding to 7.0.0-preview7

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/DetectChangesEventArgs.cs
- src/EFCore/ChangeTracking/DetectedChangesEventArgs.cs
- src/EFCore/ChangeTracking/EntityStateChangingEventArgs.cs
- src/EFCore/ChangeTracking/EntityTrackingEventArgs.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/IChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
- Tracking
- StateChanging
- DetectingChanges
- DetectedChanges
Part of #626
Fixes #27093
Fixes #16256
> New ChangeTracker events

- src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
> Query: Allow materializing owned entities with no required properties

- test/EFCore.Design.Tests/Design/DbContextActivatorTest.cs
- test/EFCore.Design.Tests/Design/DesignTimeFlagTest.cs
- test/EFCore.Design.Tests/Design/OperationExecutorTest.cs
> Fix race condition testing global state

- eng/Version.Details.xml
- eng/Versions.props
- src/EFCore.Tools/EFCore.Tools.csproj
> Use Arcade's token replacement task

- src/EFCore/ChangeTracking/Internal/IInternalEntityEntrySubscriber.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
> Re-subscribe to notifying collection when the collection instance is changed

- src/EFCore/Infrastructure/ModelSource.cs
- src/EFCore/Metadata/Builders/ConventionsBuilder.cs
- src/EFCore/ModelConfigurationBuilder.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- test/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelSourceTest.cs
> Add pre-convention configuration for conventions

- src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
- test/EFCore.Specification.Tests/ApiConsistencyTestBase.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
> Improve convention API consistency test

- global.json
- test/EFCore.Trimming.Tests/EFCore.Trimming.Tests.csproj
- ❌ I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- ❌ I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- ❌ The code builds and tests pass locally (also verified by our automated build checks)
- ❌ Commit messages follow this format:
```
- Detail 1
- Detail 2
```
- ❌ Tests for the changes have been added (for bug fixes / features)
- ❌ Code follows the same patterns and style as existing code in this repo
> Bump .NET SDK from 7.0.100-preview.6.22352.1 to 7.0.100-preview.7.22377.5

- src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/IStoreStoredProcedure.cs
- src/EFCore.Relational/Metadata/Internal/StoreStoredProcedure.cs
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
> Cosmos: Fail in model validation for owned types that are mapped to a different container.

- src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategy.cs
Fix https://github.com/dotnet/efcore/issues/28629
I cannot find error code 449 in HttpStatusCode enum, so skip it now.
> Cosmos: retry on error codes 408 and 410

- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Circumventing #28667 in different way
> Don't implement ITableBasedExpression in FromSqlExpression

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
> Validate that an entity type with sproc mapping is mapped to a table

- src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
> Validate that GetContainingPropertyName() is null iff IsDocumentRoot()

- src/EFCore/ModelBuilder.cs
/cc @ajcvickers in case the aka.ms link itself needs to be updated
Closes https://github.com/dotnet/efcore/issues/28771
> Fix typo in aka.ms links

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/DeleteExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/UpdateExpression.cs
- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
> Add support for TagWith on ExecuteDelete/Update

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore/EF.cs
- src/EFCore/Infrastructure/MethodInfoExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/EvaluatableExpressionFilter.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
> ExecuteUpdate: Implement support for DEFAULT

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
> ExecuteUpdate: Correctly identify when we need to cause a subquery join

- azure-pipelines-richnav.yml
- azure-pipelines.yml
> Move to -Svc pool provider in release branches (7.0 RC1)

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/BuildSource.cs
> Stop scaffolding DbSet initializers

- benchmark/Directory.Build.props
> Update BenchmarkDotNet version

- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
> Don't match explicit implementations for InversePropertyAttribute

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore/EF.cs
- src/EFCore/Infrastructure/MethodInfoExtensions.cs
- src/EFCore/Query/EvaluatableExpressionFilter.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Current implementation has issues and we're too late in the game to address them with confidence.
See #28660 and #28921
> Remove EF.Default since we are punting for 7.0

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/EntityBasic.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
- tools/ReplaceQueryBaseline.py
> Fix for including collection entity which contains JSON

- azure-pipelines.yml
Avoid waiting for a machine for Maestro publishing.
> Publish assets immediately

- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
- test/EFCore.Specification.Tests/SharedStoreFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Address.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Country.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPCTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPTTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
> Convert to provider values when comparing shared columns

- azure-pipelines.yml
- eng/helix.proj
> Move to ubuntu22.04

- src/EFCore/Infrastructure/MethodInfoExtensions.cs
> Cleanup in EF.Property

- azure-pipelines.yml
- eng/helix.proj
> [release/7.0] Move to Ubuntu 22.04 - missed parts

- azure-pipelines.yml
> [release/6.0] Move to Ubuntu 22.04

- azure-pipelines.yml
> [release/3.1] Move to Ubuntu 22.04

- azure-pipelines.yml
- eng/common/templates/job/execute-sdl.yml
- eng/common/templates/job/onelocbuild.yml
- eng/common/templates/jobs/jobs.yml
- eng/common/templates/post-build/channels/generic-internal-channel.yml
- eng/common/templates/post-build/channels/generic-public-channel.yml
- eng/common/templates/post-build/darc-gather-drop.yml
- eng/common/templates/post-build/post-build.yml
- eng/common/templates/post-build/promote-build.yml
- eng/common/templates/post-build/setup-maestro-vars.yml
- includes a fake Arcade update matching recent release/3.x changes
> [release/3.1] Switch to consolidated Windows build images

- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Sqlite has a peculiar way of adding months, which is by design - we need to compensate in test.
Resolves #25851
> [MQ] Add test changes to AddMonths test for Sqlite

- azure-pipelines-richnav.yml
- azure-pipelines.yml
- correct a leak in previous merges from release/7.0
> [main] Switch to consolidated Windows build images and non-Svc pools

- test/EFCore.InMemory.FunctionalTests/DataBindingInMemoryTest.cs
- test/EFCore.Specification.Tests/DataBindingTestBase.cs
- test/EFCore.Specification.Tests/F1FixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/DataBindingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
- test/EFCore.Sqlite.FunctionalTests/DataBindingSqliteTest.cs
And rename Databinding->DataBinding
> Remove SQL Server-specific test config from relational

- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
> Fix to #29289 - don't print JSON_QUERY calls when we extract the entire aggregate

- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
> [release/6.0] Update to SQLitePCLRaw 2.1.2

- eng/Versions.props
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
> [release/3.1] Update to SQLitePCLRaw 2.1.2

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> Check for SQL Server VIEW DEFINITION rights fails, if databasename contains special chars

- azure-pipelines.yml
- eng/helix.proj
- also align helix.proj (default) Helix queues w/ CI choices
> [release/6.0] Use simpler Docker tags

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
> Implement EnsureDeleted for SQLite in-memory database

- azure-pipelines-richnav.yml
- Enabling debugging to understand why richnav pipeline is failing.
> Enable system debugging for RichNav task.

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/ValueGeneration/Internal/InMemoryValueGeneratorSelector.cs
- src/Shared/EnumerableMethods.cs
- test/EFCore.InMemory.FunctionalTests/StoreGeneratedInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/ValueConvertersEndToEndInMemoryTest.cs
Fixes #29636.
Also fixes #29603.
Sorry. I know I shouldn't have fixed this.
> Fix in-memory issues with value comparers

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToMany.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseOneToMany.cs
> Null FK value when detaching Added principal by Remove

- azure-pipelines-richnav.yml
- First one resulted in a bad syntax. Not quite sure if there's a better way to run the [efcore-richnav pipeline](https://dev.azure.com/dnceng-public/public/_build?definitionId=18&_a=summary). Please let me know if you know a better way other than checking into main 😄
> Second attempt at enabling debugging in richnav build.

- src/EFCore.Abstractions/DeleteBehavior.cs
- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/DbContextOptionsBuilder`.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
Fixes #29747
Fixes #29261
Fixes #29125
Fixes #26552
Fixes #24972
Fixes #18938
> Clean up and document local DetectChanges behavior, plus other API doc fixes

- azure-pipelines-richnav.yml
- @ajcvickers / @bricelam do you know who I could chat with to get permissions for the pipelines? I'm failing to understand how to set debugging in the YAML file :(
> Undo all my debugging attempts.

- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore/Infrastructure/ModelRuntimeInitializer.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
And add some migration test coverage.
Closes #29758
> Allow SQLServer Sequence/HiLo on non-key properties

- src/EFCore/Diagnostics/MaterializationInterceptionData.cs
- src/EFCore/Query/Internal/EntityMaterializerSource.cs
- test/EFCore.Specification.Tests/MaterializationInterceptionTestBase.cs
> Flow query tracking behavior to materialization interceptor

- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
> Switch to interpreted delegates for one-off invocations

- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
I know this is a super tiny nit, but I noticed it today and figured it would be a quick edit. If this isn't appropriate for the repo, feel free to close.
> Fix grammar in XML doc for ToQueryString

- src/EFCore/Infrastructure/DatabaseFacade.cs
> Correct [Obsolete] message for AutoTransactionBehavior

- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Leftover from #29965, fixes the build.
> Fix test string assertion

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
> Move taking of lock earlier to avoid race in PruneCallback

- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- test/EFCore.Design.Tests/Design/DbContextActivatorTest.cs
- test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
> Provide more information when exception thrown discovering/creating design-time DbContexts

- src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
> Clarify how the --table and --schema parameters work when scaffolding

- src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
- src/EFCore/Metadata/Builders/PropertyBuilder.cs
- src/EFCore/Metadata/Builders/PropertyBuilder`.cs
- src/EFCore/Metadata/Builders/TypeMappingConfigurationBuilder.cs
- src/EFCore/Metadata/Builders/TypeMappingConfigurationBuilder`.cs
- src/EFCore/Metadata/IReadOnlyProperty.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/PropertyConfiguration.cs
> Document that HasMaxLength(-1) means no maximum length

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Use default schema for TPC tables

- eng/Versions.props
- to be merged after we create branches for Preview2
> Rebrand for 8.0.0-preview3

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.tt
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
> Add back setter for scaffolded collection navigations

- src/EFCore.SqlServer/Query/Internal/SqlServerConvertTranslator.cs
> Evaluate SqlServerConvertTranslator.SupportedMethods once

- global.json
Reverts dotnet/efcore#30359
Related to this: https://github.com/dotnet/aspnetcore/pull/46919
> Revert "Update SDK to 8.0.100-preview.3.23127.4"

- eng/common/templates/job/source-index-stage1.yml
- global.json
Reverts dotnet/efcore#30368 & Pre-empts the next arcade update
> Update SDK & sourceindexpackageversion

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
> Fix for Cosmos embedded line ending

- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Temporary fix for in-memory test failures

- src/EFCore.InMemory/Storage/Internal/IInMemoryTable.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryStoreCache.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTableFactory.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/KeyPropagatorTest.cs
> Stop using model references as identifiers in the in-memory database

- src/ef/Commands/MigrationsBundleCommand.cs
> Create directory chain if doesn't exist for ef migrations bundle

- eng/Versions.props
Can be merged after we have preview3 branches
> Update branding to preview4

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs
> Scaffolding: Fix handling of ConnectionString annotation

- azure-pipelines.yml
Work around an issue in provisioning in 2204 that is still be worked out.
> [release/7.0] Build on 2004 rather than 2204

- eng/Versions.props
> Update branding to preview5

- global.json
This is a routine weekly SDK update.
> Update SDK to 8.0.100-preview.5.23228.7

- test/EFCore.VisualBasic.FunctionalTests/EFCore.VisualBasic.FunctionalTests.vbproj
> Disable VB tests

- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
An arbitrary decision about an arbitrary number
> Address design meeting feedback

- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Add tests to ensure sentinels for flags enums are code-genned correctly

- global.json
- test/EFCore.Design.Tests/DesignExceptionTest.cs
- test/EFCore.Tests/ExceptionTest.cs
SDK update whilst on build ops (for Monday).
> SDK update

- eng/Version.Details.xml
- eng/Versions.props
- src/EFCore/EFCore.csproj
> Remove implicitly dependent reference

- eng/Versions.props
> Update branding to preview7

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
> No longer scaffold nullable booleans when column has a default value

- test/EFCore.VisualBasic.FunctionalTests/EFCore.VisualBasic.FunctionalTests.vbproj
- test/EFCore.VisualBasic.FunctionalTests/NorthwindQueryVisualBasicTest.vb
- test/EFCore.VisualBasic.FunctionalTests/NorthwindVBQuerySqlServerFixture.vb
> VB Tests: Use a copy of Northwind

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Fix FK duplicate detection bug

- global.json
routine build-ops; update SDK to 23354.1
> update SDK to nightly

- README.md
- src/EFCore/README.md
Fix #31088
```
- Detail 1
- Detail 2
```
> Documentation: Use `using` declarations in README files

- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
occured -> occurred
```
- Detail 1
- Detail 2
```
> Fix typo in RelationalStrings.resx

- src/EFCore/Query/Internal/EntityMaterializerSource.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityAllTypes.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
Part of #30677
Builds on https://github.com/dotnet/efcore/pull/31272
> Added using existing collection for primitive collections not inside a JSON doc

- src/EFCore.Cosmos/Query/Internal/CosmosMathTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerMathTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> Query: Translate DEGREES and RADIANS

- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Re-enable BigModel_with_JSON_columns

- src/EFCore/README.md
- Remove "MySQL" duplication from README.md
> Removed "MySQL" duplication from README.md

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Migrations: Use comparer to diff default values

- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMathTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
- test/EFCore.NativeAotTests/EFCore.NativeAotTests.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
- test/EFCore.TrimmingTests/EFCore.TrimmingTests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Resolves #18843
~~Blocked waiting for ericsink/cb#17~~
> SQLite: Translate more Math members

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Migrations: Synthesize HasColumnName in snapshot when DefaultColumnName uses CLR type

- src/EFCore.Design/Extensions/MethodCallCodeFragmentExtensions.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
- test/EFCore.Design.Tests/Extensions/MethodCallCodeFragmentExtensionsTest.cs
> Scaffolding: Add usings for UseProvider call

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Don't exclude from migrations derived tables for TPT and TPC

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
> Microsoft.Data.Sqlite: Use aggregate_context instead of user_state in CreateAggregate

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> Microsoft.Data.Sqlite: Only try sqlite3_win32_set_directory on Windows and be more resilient

- src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerOptionsExtension.cs
- src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
- src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs
- src/EFCore/Infrastructure/IDbContextOptionsExtension.cs
- src/EFCore/Storage/ExecutionStrategy.cs
- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerConfigPatternsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerConnection.cs
Detect Azure SQL based on connection string.
Detect more transient errors.
Fixes #27826
> Increase the retry delay for throttling errors on Azure SQL.

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Metadata/ITypeBase.cs
- src/EFCore/Metadata/Internal/ClrPropertySetterFactory.cs
- src/EFCore/Metadata/Internal/ComplexPropertyExtensions.cs
- src/EFCore/Metadata/Internal/PropertyBase.cs
- src/EFCore/Metadata/Internal/TypeBase.cs
- src/EFCore/Metadata/RuntimeTypeBase.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.InMemory.FunctionalTests/ComplexTypesTrackingInMemoryTest.cs
- test/EFCore.Specification.Tests/ComplexTypesTrackingTestBase.cs
Also make change tracking resilient to nulls when reading, and fix writing to structs when using properties.
> Validate complex properties are not null when saving

- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
- src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
> Cosmos: Add a way to configure Application Preferred Regions

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
> Cosmos: use Point-Read when the key is a Guid.

- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> Map complex type properties to nullable columns when the complex type is declared on a derived type in TPH.

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Migrations: Fix ComplexPropertyBuilder.IsRequired call in snapshot

- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore/ChangeTracking/ListComparer.cs
- src/EFCore/ChangeTracking/NullableValueTypeListComparer.cs
- src/EFCore/ChangeTracking/ObjectListComparer.cs
- src/EFCore/Storage/TypeMappingSource.cs
- src/EFCore/Storage/TypeMappingSourceBase.cs
- test/EFCore.SqlServer.FunctionalTests/JsonTypesCustomMappingSqlServerTest.cs
- test/EFCore.Tests/CollectionComparerTest.cs
> Better handling of nullable element comparers

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/StructuralTypeProjectionExpression.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexTypeQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexTypeQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexTypeQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexTypeQuerySqliteTest.cs
> Adjust some exception messages

- src/EFCore/EF.cs
- src/EFCore/Infrastructure/ExpressionExtensions.cs
> Allow generating EF.Property over struct

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerRuntimeModelConvention.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
> SqlServer: Rename IsSortedInTempDb to SortInTempDb

- src/EFCore/Metadata/Conventions/ComplexTypeAttributeConvention.cs
- src/EFCore/Metadata/Conventions/TypeAttributeConventionBase.cs
- test/EFCore.Tests/ModelBuilding/ComplexTypeTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> Discover ComplexTypeAttribute on nested complex types

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Store sentinel values as provider values in the compiled model

- src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
- test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
Fixes https://github.com/dotnet/efcore/issues/31740
> Don't throw for collection skip navigation without a setter

- src/EFCore.Proxies/Proxies/Internal/ProxyBindingInterceptor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Metadata/DefaultValueBinding.cs
- src/EFCore/Metadata/Internal/ConstructorBindingFactory.cs
- src/EFCore/Query/Internal/EntityMaterializerSource.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/LazyLoadProxyInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexTypeQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/ComplexTypesTrackingTestBase.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexTypeQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexTypeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/ComplexTypeModel/ComplexTypeData.cs
- test/EFCore.Specification.Tests/TestModels/ComplexTypeModel/Model.cs
- test/EFCore.SqlServer.FunctionalTests/ComplexTypesTrackingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexTypeQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/LazyLoadProxySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexTypeQuerySqliteTest.cs
Fixes https://github.com/dotnet/efcore/issues/31634
> Tests for proxies with complex types

- test/EFCore.Relational.Specification.Tests/Query/OptionalDependentQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/OptionalDependentQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentData.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentEntityAllOptional.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentEntitySomeRequired.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentJsonAllOptional.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentJsonSomeRequired.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentNestedJsonAllOptional.cs
- test/EFCore.Relational.Specification.Tests/TestModels/OptionalDependent/OptionalDependentNestedJsonSomeRequired.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OptionalDependentQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OptionalDependentQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OptionalDependentQuerySqliteTest.cs
For now only JSON entities. Can also add other scenarios (regular entities, complex types etc) in the future.
> [TEST ONLY] Adding query test suite for optional dependent. 

- src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
- src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerConfigPatternsTest.cs
> Rename UseAzureSql to UseAzureSqlDefaults

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
Fixes #31751
Using a large compiled model results in stack overflow on Mac due to excessive locals in the generated code. This change runs the compiled model initialization in a new thread with a bigger stack. This is a fix for 8 only--for 9 we will, factor the generated code differently.
Stack overflow using the compiled model on a Mac.
Customer reported on RC1 and C.I. failure on Mac after adding a test with a big compiled model.
Yes. The compiled model is bigger in EF8, which means that 6/7 models that worked will now throw.
Updated tests, plus tests pass on Mac on the C.I. Also, reporting customer verified fix on his Mac.
Low. Also quirked.
> [release/8.0] Mitigation for stack overflow with compiled model on Mac

- test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
Regression test for https://github.com/npgsql/efcore.pg/issues/2957
> Add primitive collection regression test

- src/EFCore/Storage/Json/JsonCollectionReaderWriter.cs
- src/EFCore/Storage/Json/JsonValueReaderWriter.cs
- test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- test/EFCore.Specification.Tests/JsonTypesTestBase.cs
> Correctly parse JSON from string

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.ClientMethods.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyNoTrackingSplitQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ManyToManySplitQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ManyToManySplitQuerySqliteTest.cs
> Handle shadow navigations when loading with split queries

- src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FunkyDataQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindQueryFiltersQuerySqliteTest.cs
> Add method postfix when rewriting parameters for StartsWith/EndsWith/Contains

- test/EFCore.Relational.Specification.Tests/Query/AdHocQuerySplittingQueryTestBase.cs
See https://github.com/dotnet/efcore/issues/22921#issuecomment-1848976810
> Stop re-using the same connection when running test queries in parallel

- src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
- test/EFCore.Relational.Specification.Tests/Query/AdHocJsonQueryTestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.NonRelationship.cs
- test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.OwnedTypes.cs
- test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.TestModel.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
> Check value converter configuration source when setting element type

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGeneratorDependencies.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.ModelSnapshot.cs
- test/EFCore.SqlServer.HierarchyId.Tests/TestModels/Migrations/AnonymousArraySeedContext.cs
- test/EFCore.SqlServer.HierarchyId.Tests/TestModels/Migrations/TypedArraySeedContext.cs
> Generate the correct type in snapshot when a property has a value converter

- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
See dotnet/EntityFramework.Docs#4608
> Test for navigation naming from composite FK names

- src/EFCore.Cosmos/Metadata/Conventions/CosmosKeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
- test/EFCore.Cosmos.FunctionalTests/JsonTypesCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/JsonTypesInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/JsonTypesRelationalTestBase.cs
- test/EFCore.Specification.Tests/JsonTypesTestBase.cs
- test/EFCore.Specification.Tests/NonSharedModelTestBase.cs
- test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/JsonTypesCustomMappingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/JsonTypesSqlServerTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/JsonTypesSqliteTest.cs
Derive `JsonTypesTestBase` from `NonSharedModelTestBase`
Part of #28866
> Break up KeyDiscoveryConvention

- docs/getting-and-building-the-code.md
> Add a note about testing on non en-US

- All.sln.DotSettings
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
> [release/6.0] Test only/disable broken test

- src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
> Correct SQL Server Take(0) compensating logic

- src/EFCore.Abstractions/DeleteBehavior.cs
> Fix typos on DeleteBehavior.cs

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Metadata/Internal/RelationalAdHocMapper.cs
- src/EFCore/Metadata/Internal/AdHocMapper.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Fixes #32680
Two follow on items after this is merged:
- Port to 8
- Make AdHocMapper public
> Don't discover DbFunctions when building ad-hoc model

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqliteTest.cs
> Fix SelectExpression cloning when client projections are present

- src/EFCore.Design/EFCore.Design.csproj
- src/EFCore.Design/Scaffolding/Internal/TextTemplatingModelGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/TextTemplatingEngineHostTest.cs
> Update Mono.TextTemplating to new preview package

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Storage/IRawSqlCommandBuilder.cs
- src/EFCore.Relational/Storage/Internal/RawSqlCommandBuilder.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindQueryCosmosFixture.cs
- test/EFCore.Cosmos.FunctionalTests/Query/QueryLoggingCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindQueryInMemoryFixture.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindQueryRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Relational.Tests/Extensions/RelationalDatabaseFacadeExtensionsTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFiltersCustomizer.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestUtilities/ITestModelCustomizer.cs
- test/EFCore.Specification.Tests/TestUtilities/NoopModelCustomizer.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SqlExecutorSqlServerTest.cs
- test/EFCore.SqlServer.Tests/ValueGeneration/SqlServerSequenceValueGeneratorTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindQuerySqliteFixture.cs
- test/EFCore.VisualBasic.FunctionalTests/NorthwindVBQuerySqlServerFixture.vb
> Use configured default type mappings in ExecuteSql

- src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
- test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerOnDeleteConventionTest.cs
> Don't assume that FK of skip navigation is non-null

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
> Support resetting SQL Server IDENTITY

- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
This reverts commit [9e69b85b90e0d490fa46dbf25ffac0c3f7747455](https://github.com/dotnet/efcore/commit/9e69b85b90e0d490fa46dbf25ffac0c3f7747455) from #32770 due to test failures.
See issue #32944
> Revert "Microsoft.Data.Sqlite.Core issue with multiple Blob colums (#32770)"

- src/dotnet-ef/Project.cs
I've accidentally copied the negation as well, leading to double negation
Fixes https://github.com/dotnet/efcore/pull/32860#issuecomment-1913805087
> Fix copy paste typo

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
> Fix failing test related to SQL Server identity reseeding

- src/EFCore.SqlServer/EFCore.SqlServer.csproj
> [release/7.0] Update SqlClient dependency

- src/EFCore.SqlServer/EFCore.SqlServer.csproj
> [release/8.0] Update SqlClient dependency

- src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs
- test/EFCore.VisualBasic.FunctionalTests/NorthwindQueryVisualBasicTest.vb
> Sanitize parameter names for VB

- eng/Versions.props
Bumps the `PreReleaseVersionIteration` to 3 on main
> Bump PreReleaseVersionIteration

- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/AdHocJsonQuerySqliteTest.cs
Coming out of the EFCore.PG 9.0.0-preview.2 sync.
> Minor test cleanup

- azure-pipelines-public.yml
> Split public pipeline definition

- azure-pipelines-public.yml
> [release/8.0] Split public pipeline definition

- azure-pipelines-public.yml
> [release/7.0] Split public pipeline definition

- azure-pipelines-public.yml
> [release/6.0] Split public pipeline definition

- azure-pipelines-public.yml
> Remove non-public logic from public pipeline

- .config/tsaoptions.json
> Update tsaoptions.json for EF/Data notifications to new alias

- src/ef/Commands/DbContextScaffoldCommand.Configure.cs
See #26687.
This reverts commit 5bceb5ed4f14e9481bc76917084f24d66cc45038.
> Revert "Scaffolding Change -d option to -m, since -d no longer works (#32606)"

- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Design/Scaffolding/CompiledModelCodeGenerationOptions.cs
- src/EFCore.Design/Scaffolding/Internal/CompiledModelScaffolder.cs
- src/EFCore.Tasks/EFCore.Tasks.csproj
- src/EFCore.Tasks/EFCore.Tasks.nuspec
- src/EFCore.Tasks/Properties/Resources.Designer.cs
- src/EFCore.Tasks/Properties/Resources.resx
- src/EFCore.Tasks/Tasks/Internal/OperationTaskBase.cs
- src/EFCore.Tasks/Tasks/OptimizeContext.cs
- src/EFCore.Tasks/buildTransitive/Microsoft.EntityFrameworkCore.Tasks.targets
- src/dotnet-ef/Exe.cs
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/ef/Commands/DbContextOptimizeCommand.Configure.cs
- src/ef/Commands/DbContextOptimizeCommand.cs
- src/ef/IOperationExecutor.cs
- src/ef/OperationExecutorBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
- test/dotnet-ef.Tests/ExeTest.cs
Add `.g` suffix to the generated files
And other PR comments from https://github.com/dotnet/efcore/pull/33049
> Refactor OperationTaskBase to derive from ToolTask

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.RelationshipsSnapshot.cs
- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/DbContextOptionsBuilder`.cs
> chore: remove repetitive words

- Directory.Build.props
- src/dotnet-ef/Project.cs
Fixes failures encountered in https://github.com/dotnet/installer/pull/19313
> Various fixes for issues in efcore-in-VMR build

- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
To match rest of the code around.
> Improve formatting

- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore/Internal/DbContextServices.cs
- test/EFCore.Relational.Specification.Tests/F1RelationalFixture.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
> Correctly initialize design-time relational model for externally built models

- azure-pipelines.yml
This can be reverted once https://github.com/dotnet/dnceng/issues/2333 is fixed
> Publish binaries for BinSkim

- test/EFCore.Sqlite.FunctionalTests/Properties/TestAssemblyConditions.cs
> Skip Sqlite functional tests on MacOs

- test/EFCore.Specification.Tests/Query/IQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/ListLoggerFactory.cs
> Output test logging for query tests only on error

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Fixes #33780
```
- Detail 1
- Detail 2
```
> Pass sequence annotations (#33780)

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
From the design discussion around #33815.
> Improve error message

- azure-pipelines.yml
Avoid darc double publish.
```
- Detail 1
- Detail 2
```
> Set publishAssetsImmediately on post-build

- src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/PrimitiveCollectionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
> Add missing check for predicate in primitive collection simplifications

- src/EFCore.Cosmos/Query/Internal/CosmosQuerySqlGenerator.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosTypeMapping.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
- test/EFCore.Cosmos.Tests/Storage/Internal/CosmosTypeMappingSourceTest.cs
- Look for plug-in mappings first
- Fixes #34041
- Fail for types that Cosmos does not know about
- Fixes #34022
> Changes and tests for Cosmos type mapping

- src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Storage/IRawSqlCommandBuilder.cs
- src/EFCore.Relational/Storage/Internal/RawSqlCommandBuilder.cs
- test/EFCore.Cosmos.FunctionalTests/Query/FromSqlQueryCosmosTest.cs
- test/EFCore.CrossStore.FunctionalTests/QueryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
* Fix nullability annotations on FromSqlRaw/ExecuteSqlRaw parameters ([#34064](https://github.com/dotnet/efcore/issues/34064))
* Introduce FormattableString-based (safe) FromSql in Cosmos ([#29177](https://github.com/dotnet/efcore/issues/29177))
Closes #34064
Closes #29177
> FromSql work

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.PagingQueryingEnumerable.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/GroupBySingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/GroupBySplitQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
~**Note: based on top of #34103, review last commit only**~
Just some syntax cleanup when using the critical section detector.
> Use using for critical section management everywhere

- azure-pipelines-public.yml
- azure-pipelines.yml
- Eliminate variable groups that are non-functional
- Eliminate internal runtime download arguments which aren't correct here either.
> [release/6.0] Clean up YAML

- test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
> Explicitly mark EFCore.Relational.Specification.Tests as shipping

- azure-pipelines-public.yml
- azure-pipelines.yml
- eng/helix.proj
- test/EFCore.Specification.Tests/Scaffolding/CompiledModelTestBase.cs
> Update Helix pools

- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.InMemory.FunctionalTests/EndToEndTest.cs
- test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.OwnedTypes.cs
- test/EFCore.Specification.Tests/ModelBuilding/ModelBuilderTest.TestModel.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
> Throw (suppressible) for common concrete collection types mapped as entity types

- src/EFCore/Infrastructure/EntityFrameworkEventSource.cs
- src/EFCore/Infrastructure/EntityFrameworkMetricsData.cs
- src/EFCore/Infrastructure/Internal/EntityFrameworkMetrics.cs
- test/EFCore.Tests/Infrastructure/EntityFrameworkMetricsTest.cs
> Better reporting for query cache hits and misses for OTEL.

- src/EFCore.Cosmos/Metadata/Conventions/CosmosJsonIdConvention.cs
- src/EFCore.Cosmos/Metadata/Internal/JsonIdDefinitionFactory.cs
> Don't implement IModelFinalizingConvention on CosmosJsonIdConvention

- src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessorFactory.cs
> remove SqlServerQueryTranslationPostprocessorFactory _typeMappingSource

- eng/Versions.props
- github-merge-flow.jsonc
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsInfrastructureTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
Update inter branch automatic PRs
> Update branding to 10.0.0-alpha1

- src/EFCore.Relational/Metadata/Internal/StoredProcedureComparer.cs
> Rename some locals

- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
> Remove duplicated docs

- src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
This is just some minor code cleanup.
> Remove unused variable

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServer160Test.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
Always nice to cut & slash code :)
Closes #34696
/cc @ranma42
> Make SqlNullabilityProcessor into a real ExpressionVisitor

- azure-pipelines.yml
> Update azure-pipelines.yml to fix BinSkim

- azure-pipelines.yml
modified based on suggestion from 1ES support team
```
- Detail 1
- Detail 2
```
> (Attempt #2) Update azure-pipelines.yml for binskim

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindGroupByQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryTaggingQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
> Fix tags for final GroupBy queries

- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.Json.cs
- test/EFCore.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
> Throw when a nested entity type is mapped to a different JSON column.

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
Fixes #32826
This was split from https://github.com/dotnet/efcore/pull/34870 as this issue wasn't customer-reported.
> Don't remove quoted 'GO' lines

- Directory.Build.props
> reenable stable package warning

- .github/CODEOWNERS
- github-merge-flow.jsonc
> Enable flow to release/8.0-staging and release/9.0-staging

- test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
> [TINY/CLEANUP] enabling test for scenario that was fixed earlier

- build/dependencies.props
- build/templates/default-build.yml
In official builds, this version should match the repo version
> Update .Sources package reference

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/Expressions/PagingExpression.cs
> Clean up Cosmos PagingExpression namespace

- src/EFCore.Relational/Migrations/MigrationCommandListBuilder.cs
- src/EFCore.Relational/Storage/IRelationalCommandBuilder.cs
- src/EFCore.Relational/Storage/RelationalCommandBuilder.cs
- src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
- test/EFCore.SqlServer.Tests/Storage/Internal/SqlServerDatabaseCreatorTest.cs
> Uniquify all variables used in SQL Server migration scripts

- src/EFCore/ChangeTracking/LocalView.cs
- test/EFCore.Specification.Tests/DataBindingTestBase.cs
> Don't attempt to remove a detached entry from the local view

- src/EFCore.Relational/Migrations/Internal/Migrator.cs
- test/EFCore.Specification.Tests/DataBindingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsInfrastructureSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryJsonTypeSqlServerFixture.cs
> Don't throw PendingModelChangesWarning when applying a specific migration

- src/EFCore.Relational/Query/SqlExpressions/SqlConstantExpression.cs
Forgoing a test since this fix is for an obsolete constructor that will go away soon anyway.
Fixes #35355
/cc @ranma42
> Fix SqlConstantExpression obsolete constructor

- run.ps1
- run.sh
We've migrated the korebuild bits to a new storage account
> [release/2.3] Fetch korebuild from new URL

- src/dotnet-ef/ProjectOptions.cs
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
Document it as obsolete instead
> Revert dotnet ef --msbuildprojectextensionspath breaking change 

- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
> Update Microsoft.Data.Sqlite.Core TFMs

- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
We'll postpone any further discussion about this until 11: #35599
> Update Microsoft.Data.Sqlite.Core TFMs again

- azure-pipelines.yml
Unblock preview3 builds as these tests are currently failing on CI
> [release/10.0-preview3] Disable Cosmos tests

- src/EFCore/Query/QueryRootProcessor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/PrimitiveCollectionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQueryOldSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServer160Test.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerJsonTypeTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/PrimitiveCollectionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/PrimitiveCollectionsQuerySqliteTest.cs
> Fix casted collections of enums as primitive collections.

- azure-pipelines.yml
Temporarily disabling tests to unblock the build.
> [release/10.0-preview4] Disable cosmos tests on CI

- src/dotnet-ef/Project.cs
Addresses https://github.com/dotnet/efcore/commit/fbce1d55bbacae5995decf545db9ae2eb3603dcc#r156164353
```
- Detail 1
- Detail 2
```
> Remove get ef project metadata

- azure-pipelines.yml
Reverts dotnet/efcore#36034 - it causes an invalid yml file error
> Revert "Try BinSkim extract feature azure-pipelines.yml"

- azure-pipelines.yml
> BinSkim extract - try 2 - Update azure-pipelines.yml

- src/EFCore.Cosmos/EFCore.Cosmos.csproj
- src/EFCore.Cosmos/Extensions/CosmosDbFunctionsExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosIndexBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosIndexExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosPropertyBuilderExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Metadata/Internal/CosmosAnnotationNames.cs
- src/EFCore.Cosmos/Metadata/Internal/CosmosVectorType.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ParameterInliner.cs
- src/EFCore.Cosmos/Query/Internal/Expressions/SqlFunctionExpression.cs
- src/EFCore.Cosmos/Query/Internal/Translators/CosmosFullTextSearchTranslator.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosVectorTypeMapping.cs
- src/EFCore/ValueGeneration/SequentialGuidValueGenerator.cs
- src/Shared/EFDiagnostics.cs
- test/EFCore.Cosmos.FunctionalTests/AddHocFullTextSearchCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/AddHocVectorSearchCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/FullTextSearchCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/HybridSearchCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.FunctionalTests/VectorSearchCosmosTest.cs
- test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
4b16eca7e7bf6fefe1e26e6a9bb984ce68a87dbd reverted more than intended
> Revert 4b16eca7e7bf6fefe1e26e6a9bb984ce68a87dbd

- global.json
See https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#paths for more information on the `paths` property
> Add paths to global.json

- Directory.Packages.props
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryCollectionMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteGeometryCollectionMethodTranslator.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryFilterFuncletizationInMemoryTest.cs
And update GeometryCollection Item translator accordingly
Fixes #36111
> Update to NetTopologySuite 2.6.0

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
- test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
Thanks for pointing this out @Charlieface!
Follow-up for 246b2d268367aa6fcb37535937fc944279ad82e6
> Additional set operation parentheses fix

- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.CreateSelect.cs
- test/EFCore.Relational.Specification.Tests/Query/AdHocJsonQueryRelationalTestBase.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel/DbContextModelBuilder.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/DbContextModelBuilder.cs
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel/DbContextModelBuilder.cs
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/Baselines/BigModel_with_JSON_columns/DbContextModelBuilder.cs
> Implement entity splitting with JSON owned entities (on main table)

- src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
> Fix reading/writing DateTimeOffset when no time zone is available.

- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
> Correct nullability annotation for ElementAtOrDefaultAsync

- src/EFCore/Metadata/RuntimeProperty.cs
> Fix race condition in RuntimeProperty.Sentinel

- src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
> [release/10.0][TESTS-ONLY] Improve parameter splitting

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- src/Microsoft.Data.Sqlite.Core/Utilities/IsBusyHelper.cs
> Fix "IsBusy" problem when calling NextResult and disposing data record.

- azure-pipelines.yml
> [release/8.0] Disable Guardian Dotnet Analyzers

- test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerJsonTypeTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AdHocJsonQuerySqlServerTestBase.cs
See https://github.com/dotnet/efcore/issues/36626#issuecomment-3299297784 for an explanation of what's happening.
Test-only change, /cc @artl93.
> [rc2] Adapt SQL Server legacy enum test to new JSON type

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
> Correct nullable annotations on raw SQL APIs

- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
- src/EFCore/Metadata/Conventions/NonNullableReferencePropertyConvention.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs
Just some trivial cleanup and additional coverage that came out of investigating #35669.
> Some NRT testing tweaks
