dotnet/efcore

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs

Fixes #13666
Investigated this in more detail. Two `Object` (this is a custom `Object` class, not the normal `System.Object` type) entities are created. The first one is directly associated with a Container. The second one has no Container reference or FK set. However, because the FK is also part of the PK, and the PK uses generated values, it means that the FK gets a value set.
We do this to handle dependents encountered before principals when attaching the graph. But the intention here is that the dummy key value generated will be replaced once the principal is attached. If this doesn't happen, then SaveChanges will throw due to the FK constraint violation. This change provides clarity by failing in SaveChanges so we avoid ever sending the dummy value to the database.

Throw if identifying foreign key is still unknown when saving changes

---

test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs

Fixes #14039
Issue was fixed as part of 3.0/3.1 changes.

Regression test for TPH model with lazy loading

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs

Prevent temporary value being left over when FK is later set to null

---

src/EFCore/Extensions/PropertyExtensions.cs
src/EFCore/Metadata/Internal/PropertyExtensions.cs
test/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs

Since these are used by the update pipeline.
Fixes #18859

Always store original values for index properties

---

src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
src/EFCore/Metadata/Internal/PropertyBase.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Metadata/Conventions/BackingFieldConventionTest.cs

- Don't discover backing field for indexer property by convention
- Throw if trying to set a backing field for indexer property
Resolves #19448

Metadata: Disallow backing field on indexer property

---

src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
src/Shared/EnumerableMethods.cs
src/Shared/ExpressionExtensions.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

- Skip/Take does not force applying pending selector and changing shape.
- Throw translation failure message for Querayble methods which we don't translate (hence we don't process in navigation expansion). Earlier we threw query failed message. Now Navigation Expansion does not throw QueryFailed error message from any place.
- Unwrap type conversion for validating member access during include expansion so that we don't generate include when derived type's member is accessed.
Resolves #18140
Resolves #18374
Resolves #18672
Resolves #18734
Resolves #19138
Resolves #19207

Query: Improvements to Navigation Expansion

---

src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
src/EFCore/Metadata/Internal/PropertyBase.cs
src/Shared/SharedTypeExtensions.cs
test/EFCore.Specification.Tests/FieldMappingTestBase.cs
test/EFCore.Sqlite.FunctionalTests/FieldMappingSqliteTest.cs

Relax backing field convention for collection properties

---

test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs

Resolves #12603
Fixed in #19377

Query: Add regression test for #12603

---

src/EFCore.Cosmos/Query/Internal/ISqlExpressionFactory.cs
src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
src/EFCore.Cosmos/Query/Internal/SqlBinaryExpression.cs
src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
src/EFCore.Relational/Query/ISqlExpressionFactory.cs
src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
src/EFCore.Relational/Query/QuerySqlGenerator.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressions/SqlBinaryExpression.cs

Query: Make translation of Coalesce SqlFunction

---

src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMemberTranslator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs

Query: Assign datetime typemapping to DateTimeOffset.Date

---

src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs

Resolves #13610
```C#
modelBuilder.Entity<City>().IndexedProperty<string>("Nation");
```

Metadata: Add Fluent API to configure Indexed properties

---

src/EFCore.Relational/Query/SqlExpressions/RowNumberExpression.cs

Query: Make partitions optional in RowNumberExpression

---

src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/EntityProjectionExpression.cs
src/EFCore.Cosmos/Query/Internal/KeyAccessExpression.cs
src/EFCore.Cosmos/Query/Internal/ObjectAccessExpression.cs
src/EFCore.Cosmos/Query/Internal/OrderingExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/CaseWhenFlatteningExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/SelectExpressionProjectionApplyingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/TableAliasUniquifyingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionVisitor.cs
src/EFCore/Query/IncludeExpression.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Query/ShapedQueryExpression.cs

Resolves #19192
Changes
- Only server side query expression are in place updated using private setters, public methods
- Moved to Update method pattern in certain cases
- TableExpressionBase still has internal set which will be fixed in #17337
- ShapedQueryExpression.VisitChildren throws now. Since ShapedQuery contains query expression (server side) and shaper expression (client side), it is unlikely that a visitor needs to visit both components. Hence we force visitor to decide which component to visit. This improves perf as we wouldn't go into client side shaper when updating something in sql tree

Query: Remove public setters from custom expression properties

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
test/EFCore.Tests/ChangeTracking/TrackGraphTestBase.cs

Detach entity with same identity when attaching an equivalent entity as Unchanged

---

src/dotnet-ef/dotnet-ef.csproj

This should unblock https://github.com/dotnet/aspnetcore/pull/17947

Update dotnet-ef to roll forward across major .NET Core versions

---

src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

Resolves #19511
Issue: When we unwound the first level, we did not visit it recursively.

Query: Unwind nested invocation expressions

---

src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Metadata/IConventionModel.cs
src/EFCore/Metadata/IMutableModel.cs
src/EFCore/Metadata/ITypeBase.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Metadata/Internal/TypeBase.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/EFCore.Tests/Metadata/Internal/ModelTest.cs

Metadata: Add metadata support for shared entity type

---

src/EFCore.Relational/Query/QuerySqlGenerator.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

Cleanup: Extra line 🔥

---

src/EFCore.Relational/Query/FromSqlParameterApplyingExpressionVisitor.cs
src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs
src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
src/EFCore.Relational/Query/SqlExpressions/InExpression.cs
src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedQueryTranslationPostprocessor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindJoinQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs

- moving NullSemantics visitor after 2nd level cache - we need to know the parameter values to properly handle IN expressions wrt null semantics,
- NullSemantics visitor needs to go before SqlExpressionOptimizer and SearchCondition, so those two are also moved after 2nd level cache,
- moving optimizations that depend on knowing the nullability to NullSemantics visitor - optimizer now only contains optimizations that also work in 3-value logic, or when we know nulls can't happen,
- merging InExpressionValuesExpandingExpressionVisitor int NullSemantics visitor, so that we don't apply the rewrite for UseRelationalNulls,
- preventing NulSemantics from performing double visitation when computing non-nullable columns.
Resolves #11464
Resolves #15722
Resolves #18338
Resolves #18597
Resolves …

Additional refactoring of Null Semantics

---

src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
test/EFCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs

add `IsRelational` extension for `DatabaseFacade`
Fixes #6983 
Tests for the changes have been added (for features)

add IsRelational extension for DatabaseFacade

---

src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs

Addresses part of #16143
This PR introduces translation for `string.StartsWith`, `string.EndsWith`, and `string.Contains` in cosmos queries. They are converted to the built-in cosmos functions `STARTSWITH`, `ENDSWITH`, and `CONTAINS` respectively.
Not sure if this contribution is wanted, but I had added this extension to my code as I was playing around with efcore cosmos and figured I would offer to contribute it back. If it is wanted, I will add tests and make changes as requested.

Cosmos: translate string Contains, StartsWith, and EndsWith

---

src/EFCore.Relational/Scaffolding/Metadata/DatabasePrimaryKey.cs
src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs

That only surface in preview versions of VS.
I've fixed this by using GetFieldValue instead of GetValueOrDefault when reading the relevant database values. I've taken a look (e.g. [here](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-foreign-keys-transact-sql)) and to my understanding, the affected columns (table/index/key/constraint name, delete referential action) can never be null in the database. In at least some of the cases, our own code would anyway throw immediately afterwards if null was ever returned (@bricelam can you please confirm this looks OK?).
Fixes #19496

Fix scaffolding NRT issues

---

src/EFCore/Metadata/Builders/ReferenceNavigationBuilder`.cs

`WithOne` on `ReferenceNavigationBuilder` had a comment that said "one-to-many", but it should be "one-to-one". Not much more to say I guess. Let me know if you have any questions.

Fix incorrect summary comment on ReferenceNavigationBuilder.WithOne

---

src/EFCore.Proxies/Properties/ProxiesStrings.Designer.cs
src/EFCore.Proxies/Properties/ProxiesStrings.resx
src/EFCore.Proxies/Proxies/Internal/IProxyFactory.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangedInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangingInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetPlugin.cs
src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
src/EFCore.Proxies/Proxies/Internal/ProxyChangeTrackingConvention.cs
src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
src/EFCore.Proxies/ProxiesExtensions.cs
src/EFCore.Proxies/ProxiesServiceCollectionExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
test/EFCore.Proxies.Tests/ChangeDetectionProxyTests.cs
test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
test/EFCore.Proxies.Tests/ProxyTests.cs
test/EFCore.Proxies.Tests/TestUtilities/TestContext.cs

Addresses #10949 
This was getting a bit bigger than I originally anticipated so making a draft pull request for any early feedback.
Note that the tests are currently all in `LazyLoadingProxyTests` and as part of this PR I have split them out into 3 files (change detection, lazy loading, proxy) since they don't all fall under "Lazy-Loading" anymore. All the tests still exist in their current form. Hopefully that's not an issue.
Things that still need to be done:
Some questions copied from #10949, which still stand:
1. If the entity already implements one of the notify interfaces, should we just not proxy that interface and leave it up to the consumer to raise those events? Edit: alternatively we could just continue to proxy and potentially raise 2 events if the consumer is already raising …

Proxy Change Detection

---

src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

- if one of the conditions in CaseWhen test evaluates to false we can remove it,
- if one of the conditions in CaseWhen test evaluates to true, we can remove all blocks (including else block) that appears after,
- if we only have one CaseWhen block in the end, and test evaluates to true, we can simply return the result,
- if only Else block is left, return it's result,
- if nothing is left, return NULL.
Resolves #19295

Fix to #19295 - Query: optimize CASE blocks

---

src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs

After seeing @smitpatel's [awesome explanation](https://github.com/aspnet/EntityFrameworkCore/issues/18874#issuecomment-553138737) of navigation expansion, I had the crazy idea of... integrating the comments into XML doc comments. In some cases I corrected grammar but can change back or whatever.
It would be great if we started to have a bit more doc comments, especially on complicated areas - I think they could help contributors/provider writers immensely.

Integrate navigation expansion explanations by @smitpatel into source comments

---

src/EFCore/DbContextOptionsBuilder.cs

- Specifically calls out `AddDbContextPool` as also auto-adding services for `UseLoggerFactory` and `UseInternalServiceProvider`.
Fixes #19611

Update comments on setup methods

---

test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

Issue has already been fixed earlier, likely by null semantics improvements.
Resolves #19020

[TINY] Enabling tests for #19020 - Parameter based optimization tries to group by constant

---

src/EFCore/ChangeTracking/EntityEntry.cs

OriginalValues does not always return the original values which might not be clear to everyone and should be mentioned.

Update EntityEntry.cs OriginalValues docs

---

test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

The issue has been fixed earlier.
Resolves #15641

[TINY] Adding tests for #15641 - GroupBy FK_Id.HasValue on Sql Server generates invalid sql

---

test/EFCore.Relational.Specification.Tests/TwoDatabasesTestBase.cs
test/EFCore.Specification.Tests/MusicStoreTestBase.cs

The tests in TwoDatabasesTest extract a connection string from a DbContext after its connection has been opened. This usually means that the password is scrubbed out when `Persist Security Info=false` (the default), so the connection string is copied without it. The EF Core tests use LocalDB and Sqlite where there's no security info in the connection string.
Also made tests virtual.

Fixes to TwoDatabasesTest

---

src/EFCore.Proxies/Proxies/Internal/PropertyChangedInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangingInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
src/EFCore.Proxies/ProxiesExtensions.cs
src/EFCore/Internal/ReferenceEqualityComparer.cs
test/EFCore.InMemory.FunctionalTests/ProxyGraphUpdatesInMemoryTest.cs
test/EFCore.Specification.Tests/ProxyGraphUpdatesFixtureBase.cs
test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
test/EFCore.SqlServer.FunctionalTests/ProxyGraphUpdatesSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/ProxyGraphUpdatesSqliteTest.cs

Issue #10949
Found and fixed a couple of bugs:
* Proxies were reading directly from the property. This can cause recursive loops in some cases. Fixed by using EF's compiled delegates for writing to the field directly.
* Comparisons were being done by the default for the property/navigation. Instead force use of configured value comparer for regular properties or reference equality for navigations.
Also added overloads to `CreateProxy` to make it easier to do creation of proxy graphs inline.

Graph update tests for change tracking proxies

---

src/EFCore.Cosmos/Storage/Internal/CosmosTypeMapping.cs
src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTypeMapping.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTypeMappingSource.cs
src/EFCore/ChangeTracking/ValueComparer.cs
src/EFCore/ChangeTracking/ValueComparer`.cs
src/EFCore/Extensions/ConventionPropertyExtensions.cs
src/EFCore/Extensions/MutablePropertyExtensions.cs
src/EFCore/Extensions/PropertyExtensions.cs
src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
src/EFCore/Metadata/Internal/Property.cs
src/EFCore/Storage/CoreTypeMapping.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Tests/Storage/ValueComparerTest.cs

See PR discussion: https://github.com/dotnet/efcore/pull/19644#pullrequestreview-345575790

Obsolete structural comparers and make key comparers do deep snapshot for arrays

---

src/EFCore/Query/Internal/LanguageNormalizingExpressionVisitor.cs
src/EFCore/Query/QueryTranslationPreprocessor.cs

Fixes #19592
Note that this currently contains no tests, since that would require us to at least reference Microsoft.VisualBasic.dll, which I can do (or even more extreme, create a VB project).

LanguageNormalizingExpressionVisitor for VB.NET string comparisons

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs

Visit sibling includes when encountering an owned collection

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs

Fix is to detect bool columns with value converters (upon initial translation) and apply comparison with constant true (with the same mapping). Also, we need to recognize this pattern during SqlExpression optimization, so that it' doesn't get simplified from 'a == true' to 'a'
Resolves #18147

Fix to #18147 - Where bool column needs to convert to equality when value converter is applied

---

src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindAggregateOperatorsQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs

- Added throw to TranslateLastOrDefault to give a friendly exception
Not great at exception message text at the best of times. I went with:
When performing a Last() operation, you must include an OrderBy clause.
I'm open to suggestions on better text!
Fixes #18211

Fix to #18211 - Throw better exception for Last without order by

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs

Allows `DEFAULT` with single or double parenthesis to remove unnecessary `HasDefaultValueSql`
- It appears that schemas generated with older version of SSMS tools or DDL commands have produced defaults in the format
e.g. `DEFAULT (0)`
- Modern tools always generate `DEFAULT ((0))`
- It seems inexpensive to test for legacy schema `DEFAULT (0)`

Fixes #19720 single parenthesis defaults

---

src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs

For collection scalar property preserve Count member as is.
Resolves #19715
@roji - Can you verify with this fix it correctly translates in npgsql?

Query: Convert List.Count to Queryable.Count() only for queryables

---

src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs

If all components are NewExpression are default then just make it wholy default so that it can match to GroupBy-Aggregate shape
Resolves #19705

Query: Snapshot selector shape correctly for better match

---

src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalCollectionShaperExpression.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/KeysWithConvertersCosmosTest.cs
test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs

Query: Identifiers should compare using KeyValueComparer

---

src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs

Making RelationalCommandCache printable and printing it's SelectExpression.
Example query plan output:
```
queryContext => new QueryingEnumerable<int>(
(RelationalQueryContext)queryContext,
RelationalCommandCache.SelectExpression(
(Projection Mapping:
EmptyProjectionMember -> 0
SELECT ((COUNT((*))))
FROM (Customers AS c)
WHERE ((c.CustomerID) == (N'ALFKI')))),
null,
ReaderColumn[] { ReaderColumn<int>, },
Func<QueryContext, DbDataReader, ResultContext, int[], ResultCoordinator, int>,
TestModels.Northwind.NorthwindRelationalContext,
DiagnosticsLogger<Query>)
.Single()
```
Fixes #19023

Fix to #19023 - Query: Log query plan

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/ChangeTracking/ValueComparer.cs
src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Query/ReplacingExpressionVisitor.cs

ReplacingExpressionVisitor held original and replacement expressions in a dictionary. Unfortunately that means hash code calculation occurs exponentially, as each TryGetValue on the dictionary must traverse the entire tree.
Replaced with two lists and a simple Equals check, which is much faster.
Fixes #19737

ReplacingEV uses two arrays instead of dictionary

---

test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs

Fixes issue #16701 . The tests work for SQL Server but in other providers the table names need square brackets (which are then re-interpreted as the provider's escape character).

Fix for issue 16701. Brackets around tables names supports non-SQL Server providers

---

src/EFCore.Relational/Storage/Internal/RawSqlCommandBuilder.cs
test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/SqlExecutorSqlServerTest.cs

Use sql generation helper to generate parameter name to write in sql command.
Resolves #19493

Generate parameter name properly for ExecuteSqlInterpolated

---

src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindCompiledQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #19322
Also block evaluation of DbContext inside Parameter extractor. It would throw exception rather than using first time context value every time (which would be incorrect results) till true funcletizer is implemented in #19209

Query: Convert Set to entity queryables in explicitly compiled query

---

test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.Specification.Tests/Query/QueryTestBase.cs
test/EFCore.Specification.Tests/TestUtilities/ExpectedQueryRewritingVisitor.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
test/EFCore.Specification.Tests/TestUtilities/QueryTestExtensions.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

Added visitor that injects Maybe methods for all non-scalar member accesses.
Also refactored Maybe methods to be more composible and so that when used manually, they don't require type arguments to be specified.

Fix to #19900 - Query/Test: add automatic null propagation for AssertQuery baselines (part1)

---

src/EFCore.SqlServer/Diagnostics/ConflictingValueGenerationStrategiesEventData.cs
src/EFCore.SqlServer/Diagnostics/Internal/SqlServerLoggingDefinitions.cs
src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerStoreGenerationConvention.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationConflictTest.cs
test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs

Instead of throwing as it used to do. This fixes #16814.
By default the warning is still set up to throw, but now you could turn that off if you're sure you know what you're doing. Tests for that latter part will be forthcoming, but I wanted to get feedback that I'm going the right direction, plus agree on the message etc.

SqlServerValueGenerationStrategy which conflicts now causes warning

---

src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Fixes #18904
Using navigations in OrderBy & ThenBy creates invalid tree which fails during translation.
Query fails to translate to server throwing exception
We did not have test coverage for specific scenario where OrderBy & ThenBy both are expanding new navigations. Add regression test.
Regression from 2.1 release
Low. Affects only processing of OrderBy/ThenBy in query. Basic case of which are covered by many tests.
Also, fix is on by default, but quirk switch is present to revert back to old behavior.

[release/3.1] Query: Expand navigations together in OrderBy/ThenBy

---

src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMemberTranslator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs

Resolves #19052
When DateTimeOffset.Date is translated, we kept resulting type mapping as datetimeoffset so during comparison with other date, the parameter is created using wrong store type.
Due to parameter type being wrong, it can have offset sometimes giving incorrect results of the query.
We did not have test coverage for specific scenario where DateTimeOffset.Date's type mapping mattered. This has been added.
Possibly. We have verified the exact behavior in 2.x because a lot has changed in how we translate this, but it's likely this was broken in 2.x at least for some cases.
Low. Affects only translation of `DateTimeOffset.Date` which was incorrect before this fix.
Also, fix is on by default, but quirk switch is present to revert back to old behavior.

[release/3.1] Query: Assign datetime typemapping to DateTimeOffset.Date

---

src/EFCore.Relational/Query/SqlExpressionFactory.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs

Partial fix for #18299
Issue: The way we construct SelectExpression for owned entity type involves adding inner joins to owner when table splitting so that only owned entity for given owner is in result. Considering the fact that any owned entity translation would originate from a query root which would be non-owned, the join condition is unnecessary when it is same as outer query root which initiated this owned entity.
Fix: When we are generating join condition for linking FK if the FK is ownership for entity type and principal type is root entity type then the join condition would be redundant hence we skip adding it.
Notes:
- The joins would be unnecessary even for derived type if the owned navigation is on base type or the given entity type but integrating that information involves …

[release/3.1] Query: Simplify SQL generated for optional owned/weak entities when table splitting

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/ChangeTracking/ValueComparer.cs
src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Query/ReplacingExpressionVisitor.cs

ReplacingExpressionVisitor held original and replacement expressions in a dictionary. Unfortunately that means hash code calculation occurs exponentially, as each TryGetValue on the dictionary must traverse the entire tree.
Replaced with two lists and a simple Equals check, which is much faster.
Fixes #19737
(cherry picked from commit 7c9fc8acfa4fc36131ba07bc6c52b83b3fae439f)

[Release/3.1] ReplacingEV uses two arrays instead of dictionary (#19858)

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs

Fixes #19159
When querying owned entity types that have owned collections as well as owned references the owned references are not included in the results.
Query returns incomplete results. There's no workaround.
We did not have test coverage for this specific scenario. This PR includes new coverage.
No.
Low. Affects only processing of owned references sibling to owned collections.
Also, fix is on by default, but quirk switch is present to revert back to old behavior.

[release/3.1] Cosmos: Visit sibling includes when encountering an owned collections

---

src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs

Loading SpatiaLite can fail in framework-dependent deployments. This prevents EF SQLite applications from using spatial types.
Application crashes when attempting to use SpatiaLite.
We need better testing in this area. It's hard to do with automated testing of dotnet publish, but we are looking at what we can do in CTI tests.
No.
Very low; we just check for the library in one more place before abandoning the search.
----
Fixes #15691

[release/3.1] SQLite Spatial: Find SpatiaLite in framework-dependent deployments

---

src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Design.Tests/TestUtilities/DatabaseColumnRef.cs
test/EFCore.Design.Tests/TestUtilities/DatabaseTableRef.cs
test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs

Fixes #18633
In 3.0, we started reverse engineering entity types for tables without a primary key. If the keyless table contained a foreign key, a bi-directional relationship was created for it; however navigation properties to a keyless entity type aren't allowed at runtime.
The code generated by `dotnet ef dbcontext scaffold` throws at runtime and needs to be updated manually before it will work.
Automated tests were added covering the various scenarios reported.
No.
Low. Navigation properties to the keyless entity type are no longer created. An AppContext switch was added to enable reverting to the previous behavior.

[release/3.1] RevEng: Don't create navigations to keyless entity types

---

src/EFCore.Abstractions/BackingFieldAttribute.cs
src/EFCore/Metadata/Conventions/BackingFieldAttributeConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs

Fixes #6266. Adding a `BackingField` attribute which does the same as the `HasField()` fluent API.

Adding a BackingField attribute

---

azure-pipelines.yml
eng/Version.Details.xml
eng/helix.proj
global.json
test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs

- Adds coverage for testing using
- WindowsServer 2016-Datacenter with localdb
- macOS 10.14
- Ubuntu 18.04-LTS
- Currently tests are run separately based on OS type win/non-win due to #19964
- Uses anonymous auth from public build and access token from internal build
- Automatically adds all test projects from test folder
- All telemetry is enabled for reporting
- EnableAzurePipelinesReporter
- FailOnTestFailure
- EnableXUnitReporter
- FailOnMissionControlTestFailure
- Validated internal builds also uses helix for testing using HelixAccessToken
- Checking FullTextSearch on SqlServer has been put in try-catch (Helix run threw exception of localdb not found)
Resolves #19857

Add EF Core CI testing using Helix queues

---

Directory.Build.targets
eng/Versions.props

The dotnet-ef global tool was built incorrectly:
* dotnet-ef 3.1.2 depends on runtime 3.1.2
* This fails on any machine with just 3.1 on it. This includes when the web tools try to load dotnet-ef from within VS.
* It should depend on 3.1.0
This will break common VS scenarios as well as people who install the latest tool on the command line.
CTI validation using VS following the patch release, and also customer-reported on the command line.
We have done manual validation on the new PR and will validate again once it is in the build.
Going forward we need to make sure that we can reproduce this in the CTI validation _before_ the new packages are pushed to NuGet.
Also, since we knew about this before and thought it was fixed we will investigate what happened in the process that allowed this. …

[release/3.1] Fix dotnet-ef RuntimeFrameworkVersion

---

test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs

- Added regression test to verify concatenating int and strings together doesn't fail with "Null TypeMapping in Sql Tree"
- I rolled the code back to the 3.1 release branch and verified the tests failed on that branch.
Fixes #18132

#18132 Added regression tests for concatenating int and strings together

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs

During translation, when we decide whether we can apply JOIN or APPLY we visit inner SelectExpression looking for references to tables in the outer SelectExpression.
Problem was that we were using Contains method, which would not match cases where the outer table was in the form of JoinExpressionBase.
Fix is to use ContainsTableReference method which matches different types of tables.
Resolves #19825

Fix to #19825 - Query: incorrectly generating JOIN rather than APPLY for subqueries with outside references to a joined table

---

src/EFCore.Abstractions/KeylessAttribute.cs
src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/KeylessEntityTypeAttributeConvention.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
test/EFCore.Tests/Metadata/Conventions/EntityTypeAttributeConventionTest.cs
test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs

Resolves #19246
Also related #19964
- Add KeylessAttribute in Abstractions packge
- Add convention to detect KeylessAttribute and configure the entityType to be keyless
- Scaffolding when using data annotations
- Generate KeylessAttribute over entity class
- Skip HasNoKey from fluent API configuration
Tests:
- Add tests for OwnedAttribute
- Add tests for KeylessAttribute
- Add test for scaffolding to verify behavior with data annotations

Introduce KeylessAttribute

---

test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsQueryRelationalFixtureBase.cs
test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalQueryAsserter.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/QueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
test/EFCore.Specification.Tests/TestUtilities/ExpectedQueryRewritingVisitor.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs

- converting EF.Property to member access,
- adding complex EF.Property rewrite, e.g. EF.Property(entity, "CustomerId") -> entity.Customer.Id
- adding null safety to non-nullable member access in Join/GroupJoin key selectors,
- adding null safety to non-nullable member access in binary,
- adding null safety to non-nullable member access wrapped in cast to nullable,
- adding null safety to member access returning bool,
- adding null safety for string related methods: StartsWith, EndsWith, Contains,
- adding expected query rewrite for methods returning a single element.
Resolves #19900

Fix to #19900 - Query/Test: add automatic null propagation for AssertQuery baselines (part2)

---

src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
test/EFCore.Sqlite.Tests/Storage/SqliteRelationalConnectionTest.cs

SQLite: Make optionsBuilder.CommandTimeout() also set connection.DefaultTimeout

---

src/EFCore.Sqlite.Core/Diagnostics/Internal/SqliteLoggingDefinitions.cs
src/EFCore.Sqlite.Core/Diagnostics/Internal/UnexpectedConnectionTypeEventData.cs
src/EFCore.Sqlite.Core/Diagnostics/SqliteEventId.cs
src/EFCore.Sqlite.Core/Internal/SqliteLoggerExtensions.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
test/EFCore.Sqlite.Tests/SqliteEventIdTest.cs

SQLite: Fix modulo on floating-point values

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs

[Perf] RevEng: Get EngineEdition & CompatibilityLevel once per connection

---

src/EFCore.Relational/Query/ISqlExpressionFactory.cs
src/EFCore.SqlServer/Query/Internal/SqlServerTimeSpanMemberTranslator.cs

Obsolete ISqlExpressionFactory methods as well.
Closes #19731

Further function nullability propagation work

---

src/EFCore/Query/ReplacingExpressionVisitor.cs
src/Shared/MemberInfoExtensions.cs
test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs

Issue: For compiler generated trees the MemberInfos always in sync. But for manually generated trees, if derived type parameter is used then the MemberInfo.ReflectedType is different. Which throws off ReplacingExpressionVisitor when comparing MemberInfo.
Fix: Use helper method IsSameAs which compare memberInfos which refer to same member access in given hierarchy
Resolves #19087
In dynamic query generation if hierarchies are involved then it could throw translation failure error. It is hard to figure out the root cause for such cases.
**How found**
Multiple customer reported.
We have added test to cover this scenario.
Yes, from 2.x
**Risk**
Low.

[release/3.1] Query: Match memberInfo in hierarchy for reducing MemberInitExpression

---

src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
src/EFCore/Query/EvaluatableExpressionFilter.cs
src/EFCore/Query/EvaluatableExpressionFilterBase.cs
src/EFCore/Query/EvaluatableExpressionFilterDependencies.cs
src/EFCore/Query/IEvaluatableExpressionFilterPlugin.cs

Plugin support for EvaluatableExpressionFilter

---

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs

- Update methods GetBytes and GetChars to use internally GetStream.
Fixes #13987

Improve SqliteDataRecord class Efficiency

---

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs

This reverts commits 2fdcc8d560c9619153857f1d31556bbd2f1228c0 and b416e9d28babc5f65af8c0d38b75500f671891e3.
(Added a few missing `using` statements in the tests.)
Fixes #13987

Microsoft.Data.Sqlite: Bring back the SqliteBlob optimizations

---

src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs

Changes:
- Honor AUTOINCREMENT (fixes #11961)
- Handle foreign keys without foreign column references (fixes #19920)

SQLite RevEng: Fix some issues

---

src/EFCore/Query/ExpressionPrinter.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs

- Removed parenthesis around IPrintableExpression since it was making printing of query roots bad.
- Individual expression should decide if it wants to add parenthesis around it.
- Reduce the expression tree before printing in Navigation expansion for more human readable form.
Required for #20146

Query: Print better expression trees

---

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs

Microsoft.Data.Sqlite: Lazy all the things!

---

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs

Microsoft.Data.Sqlite: Default CommandText to an empty string

---

src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/InExpression.cs
src/EFCore/Query/Internal/AllAnyContainsRewritingExpressionVisitor.cs
src/EFCore/Query/QueryTranslationPreprocessor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.Specification.Tests/Query/QueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/LocustLeader.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs

We used to translate this into `NULL IN subquery` pattern, but this doesn't work because it doesn't match if the subquery also contains null.
Fix is to convert this into subquery.Any(e => e == NULL), which translates to EXISTS with predicate and we can correctly apply null semantics.
Also it allows us to translate contains on entities with composite keys.
Also made several small fixes:
- marked EXISTS and IN expressions as never nullable for purpose of null semantics,
- optimized EXISITS (subquery) with predicate that resolves to false, directly into false, since empty subquery never exisits,
- improves expression printer output for IN expression in the subquery scenario.

Fix to #19499 - Query: null semantics not applied on subquery.Contains(null)

---

src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalModelBuilder.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Proxies.Tests/ProxyTests.cs

Fixes #15958. Do not allow the user to register dynamically-generated proxy types in the ModelBuilder.

Fix for 15958. Do not allow the user to register proxy types.

---

src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs

Store null index filters

---

src/EFCore.Design/Design/Internal/CSharpHelper.cs
test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs

For NodaTime code literal generation (https://github.com/npgsql/efcore.pg/issues/854)

Support ExpressionType.Add in CSharpHelper

---

src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs

Tiny fix that was missed when fixing #18555

[TINY] Use sql function IsNullable property to determine its nullability, rather than always assume it's nullable

---

src/EFCore.Relational/Query/RelationalEvaluatableExpressionFilter.cs
src/EFCore/Query/EvaluatableExpressionFilterBase.cs
src/EFCore/Query/IEvaluatableExpressionFilter.cs
src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs

Resolves #20162
- Never evaluate DbFunction
- If it is inside lambda then we will have whole method call
- If it is outside of lambda then it will be evaluated by compiler alread

Query: Improve parameterization of queryable functions

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Extensions/MutableEntityTypeExtensions.cs
src/EFCore/Metadata/Builders/DiscriminatorBuilder.cs
src/EFCore/Metadata/Builders/DiscriminatorBuilder`.cs
src/EFCore/Metadata/Builders/IConventionDiscriminatorBuilder.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.InMemory.FunctionalTests/Query/CompleteMappingInheritanceInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/Query/CompleteMappingInheritanceInMemoryTest.cs
test/EFCore.Specification.Tests/Query/InheritanceFixtureBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/CompleteMappingInheritanceSqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/CompleteMappingInheritanceSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/CompleteMappingInheritanceSqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/CompleteMappingInheritanceSqliteTest.cs
test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs

- Add fluent API IsComplete over DiscriminatorBuilder
- In query if mapping is complete
- Don't generate predicate when creating Select for an entityType
- Don't apply predicate when doing OfType of derived type when the discriminator is not needed
Current default: Mapping is incomplete unless user uses fluent API to mark it as complete.
Resolves #18106

Introduce complete discriminator mapping

---

src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Metadata/Internal/TableMappingComparer.cs
src/EFCore.Relational/Metadata/Internal/ViewMappingComparer.cs
src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs

Refactor RelationalModelValidator
Part of #15660

Validate more SqlServer-specific configuration on shared database objects

---

src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore/Query/ShapedQueryExpression.cs
test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs

Minor cleanup for queryable function support

---

azure-pipelines.yml
test/EFCore.CrossStore.FunctionalTests/ConfigurationPatternsTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.InMemory.FunctionalTests/Query/CompleteMappingInheritanceInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
test/EFCore.Tests/Query/ExpressionPrinterTest.cs

Use single build to run helix tests across different OS.
Resolves #19964

Ignore line ending differences in tests

---

test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/CompleteMappingInheritanceSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs

Resolved by #19377
Issue fixed since cast to base type is removed by nav expansion as it is redundant
Resolves #20046

Add regression test for issue#20046

---

src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/NavigationBuilder.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

Partial fix for #6674
Created new Navigation() calls directly on EntityBuilder. Added tests for OneToMany, ManyToOne, ManyToMany, OneToOne and principal side of the Owned Type.
- The additions to `WithOwner()` to allow configuring a navigation on the dependent side of an Owned Type.
- Removing the old way of doing it (see #20195).

Partial fix for 6674. 

---

src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs

Most of the rest of the fix for #6674. (Rest is clean up)
This adds the last part - being able to configure the dependent side navigation of an Owned-type relationship.

Add ability to configure the navigation on dependent side of Owned-types

---

src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs

Query: Remove client eval code for EF.Functions methods

---

src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
src/EFCore/DbFunctionsExtensions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
test/EFCore.Tests/DbFunctionsTest.cs

InMemory translates it using an provider specific method now
Resolves #20293

Query: Remove client implementation for EF.Functions.Like

---

test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerCondition.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
test/EFCore.SqlServer.FunctionalTests/config.json

- Remove TeamCity CI condition
- Remove SupportsOffset as our lowest supported SqlServer version supports offset
- Remove env variable for FreeText and detect by connecting to server

Clean up in SqlServer functional tests config

---

src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs

Disallow setting custom translation for DbFunction mapped to TVFs

---

src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs

To support non-literal value for the argument
Fixes #13315

Add [NotParameterized] to FreeText's argument

---

src/EFCore/Metadata/Builders/IConventionNavigationBuilder.cs
src/EFCore/Metadata/Builders/NavigationBuilder.cs
src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs
src/EFCore/Metadata/Internal/InternalPropertyBaseBuilder`.cs
src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
test/EFCore.Specification.Tests/FieldMappingTestBase.cs
test/EFCore.Tests/Metadata/Internal/InternalNavigationBuilderTest.cs

Fixes #20281. `NavigationBuilder` now has a `HasField()` method on it allowing the user to specify the backing field explicitly.
(Note: avoiding duplication meant pushing this code down onto `InternalPropertyBaseBuilder` and updating some other classes to call it at the same time.)

Fix for 20281. Adding HasField() method and updating tests.

---

src/EFCore/Query/ExpressionPrinter.cs

Adding proper handling for SwitchExpresions.
Resolves #20322

Fix to #20322 - Print Switch in expression tree

---

src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryCompilationContext.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryCompilationContextFactory.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryContext.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryContextFactory.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryMetadataExtractingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryTranslationPreprocessor.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryTranslationPreprocessorFactory.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitorFactory.cs
src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs

Adding `.WithPartitionKey()`  `IQueryable` extension method.
Needed when using resource tokens for secure authentication when permissions are grated based on partition keys. #20221

Adding .WithPartitionKey()

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.InMemoryProjectionBindingRemovingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.cs
src/EFCore/Infrastructure/ExpressionExtensions.cs
src/EFCore/Metadata/PropertyParameterBinding.cs
src/EFCore/Query/EntityMaterializerSource.cs
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/IEntityMaterializerSource.cs
src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs

This method is to read a particular index from valueBuffer for a property.
It was in EntityMaterializerSource as an instance method in order for provider to influence how values are read from valueBuffer.
In new query pipeline, providers are supposed to convert valueBuffer read to their database object read. Further, even if they want to create a ValueBuffer for read, the valueBuffer should have values after all custom processing.
Hence there is no particular need to make this overridable behavior. Making it extension method simplify quite a lot of things.
(note: functionality to use this was available anyway since the method it invoke was also publicly exposed as static.

Query: Make CreateReadValueExpression an extension method

---

src/EFCore.InMemory/Storage/Internal/IInMemoryTable.cs
src/EFCore.InMemory/Storage/Internal/IInMemoryTableFactory.cs
src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTableFactory.cs
test/EFCore.InMemory.FunctionalTests/IntegerValueGeneratorTest.cs

Fixes #19854
Because in-memory isn't "TPH" and so derived types have their own "table" but the value generator is stored on the "table" that the property is defined in.

Force use of common value generator for all derived types

---

src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs

Query: Cleanup in optional dependent SQL feature

---

src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/RelationalOwnedQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs

- Also add at least one additional property in each owned type. If there no columns other than shared PK then it is required dependent.
- Add a property in owned type which would be sharing column for hierarchy. Currently disabled due to #20334
Resolves #20343
Resolves #20336
Finishes left over test work from #20345

Test: Update Sql assertion in OwnedQuerySqlServerTest

---

src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/RelationalOwnedQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs

Fix involves:
- Adding additional materialization conditions for relational layer when table splitting is used. See #20332 for conditions
- Create EntityProjection using the same table when both types are sharing the table.
- Fix a bug in shaper when null entityType is returned from materialization condition, don't call StartTracking.
- Assign nullability to PK column correctly for optional dependents so we don't project it twice.
- Disabled Sql assertion in OwnedQuerySqlServerTest. Will enable after model update as described in #20336, #20343
Resolves #18299
Resolves #20338
Resolves #20332

Query: Do not generate server side joins for optional dependents

---

src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/RelationalOwnedQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs

When joining 2 tables in relational, we lift the table from inner select expression and copy over projections. If one of this projection is same as any outer projection then we reuse the same projection. That means the associated indexes in inner shaper will go to different indexes rather than in linear fashion.
Fix is to remember which index each projection went and use that rather than applying an offset.
Resolves #19616

Query: Map projection properly when joining 2 tables

---

src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.RelationalProjectionBindingRemovingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitorDependencies.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/FromSqlSprocQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs

Query: Improve detection of non-composed FromSql

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs

When joining 2 tables in relational, we lift the table from inner select expression and copy over projections. If one of this projection is same as any outer projection then we reuse the same projection. That means the associated indexes in inner shaper will go to different indexes rather than in linear fashion.
Fix is to remember which index each projection went and use that rather than applying an offset.
Resolves #19616
Inside Select, if subquery Select contains a constant/parameter, which is in parent Select or other subquery's Select then we project it only once in SQL causing projection indexes mismatch.
Problematic queries throws exception.
Added regression test for scenario in which projection indexes would become non-linear.
Yes. From 2.2 to 3.0 …

[release/3.1] Query: Map projection properly when joining 2 tables

---

src/Microsoft.Data.Sqlite.Core/Properties/Microsoft.Data.Sqlite.rd.xml
src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs
src/Microsoft.Data.Sqlite.Core/Utilities/BundleInitializer.cs

Fixes #19754
The native SQLite interop library we depend on (SQLitePCL.raw) made a breaking change to stop setting the temp and data directories on UWP. Our guidance was for users to manually set these in their application. If users don't set these and specify a relative database file in their connection string, they'll get a SQLite error:
> unable to open database file
Several customers are encountering the error without understanding why or how to fix it.
By reintroducing code to set these directories automatically for the user, it will lower the barrier to get started using Microsoft.Data.Sqlite and EF Core on UWP.
Manually verified that this works on UWP using both the version of SQLite that we include and winsqlite3.dll. Also verified that it works on …

[release/3.1] Microsoft.Data.Sqlite: Set temp and data directory on UWP

---

src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/TestUtilities/ExpectedFilteredInclude.cs
test/EFCore.Specification.Tests/TestUtilities/IncludeQueryResultAsserter.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs

Allows for additional operations to be specified inside Include/ThenInclude expression when the navigation is a collection:
- Where,
- OrderBy(Descending)/ThenBy(Descending),
- Skip,
- Take.
Those additional operations are treated like any other within the query, so translation restrictions apply.
Collections included using new filter operations are considered to be loaded.
Only one filter is allowed per navigation. In cases where same navigation is included multiple times (e.g. Include(A).ThenInclude(A_B).Include(A).ThenInclude(A_C)) filter should only be applied once.
Alternatively the same exact filter should be applied to all.

Fix to #1833 - Support filtered Include

---

src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
src/EFCore.SqlServer/Query/Internal/SqlServerDataLengthFunctionTranslator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs

Add `DATALENGTH` function to SqlServer
Fixes #19988
Please review,

Add DATALENGTH function to SqlServer

---

src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
src/EFCore.Relational/Internal/RelationalDatabaseFacadeDependencies.cs

Part of #15393
This is some sort of "optimization" which no other provider would need.

Suppress internal warnings for DatabaseFacadeDependencies

---

build/templates/default-build.yml

- dotnet/aspnetcore-internal#3540
- nit: Consistently use `in` / `notin` with `Build.Reason`
- YAML was inconsistent and this aligns w/ the Arcade code

[release/2.1] Update hosted and BYOC agents used in our builds

---

test/EFCore.SqlServer.FunctionalTests/CommandConfigurationTest.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerCondition.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
test/EFCore.SqlServer.FunctionalTests/config.json

fixes #20318
I have attempted to cater for current implicit assumptions - but it is opaque to me what SQL Server edtions tests are actually run against.
Tested with SQL 2016 Developer Edition and LocalDb version 14

Detect SqlServer features automagically rather than using env vars

---

src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/Internal/MigrationsOperations.cs
src/EFCore.Design/Design/OperationExecutor.cs
src/EFCore.Design/Migrations/Design/IMigrationsScaffolder.cs
src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/dotnet-ef/Properties/Resources.Designer.cs
src/dotnet-ef/Properties/Resources.resx
src/ef/Commands/DbContextScaffoldCommand.Configure.cs
src/ef/Commands/DbContextScaffoldCommand.cs
src/ef/Commands/MigrationsAddCommand.Configure.cs
src/ef/Commands/MigrationsAddCommand.cs
src/ef/IOperationExecutor.cs
src/ef/OperationExecutorBase.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx
test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs

Fixes #9723 
Add the ability to override the namespaces of
- the migration in Add-Migration
- the entity classes generated by Scaffold-DbContext
- and separately the DbContext class generated by Scaffold-DbContext
Updates to dotnet-ef, ef and Powershell all included.

Fix for 9723. Allow namespaces to be specified.

---

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs

Fix for #15256 - bad SQL was generated for DefaultValue with line breaks.

Fix for 15256 - bad generated SQL for DefaultValue with line breaks.

---

src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs

Fix two issues building and testing on Linux introduced by #20304 (bad generated SQL for DefaultValue with line breaks /cc @lajones)
* Test literals were using machine line endings
* Replacement mechanism for new lines in literals did not handle a single `\n`
Fixes #20439
Fixes #20438

Fix Linux build breaks

---

src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs

Throw if cannot set IsUnique because the NavProp has the opposite multiplicity.
Fixes #20303.

Fix for 20303. 

---

src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/IndexBuilder.cs
src/EFCore/Metadata/Builders/KeyBuilder.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
src/EFCore/Metadata/Builders/PropertyBuilder.cs
src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
src/EFCore/Metadata/Builders/RelationshipBuilderBase.cs
src/EFCore/ModelBuilder.cs
test/EFCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
test/EFCore.Tests/Metadata/Conventions/DiscriminatorConventionTest.cs
test/EFCore.Tests/Metadata/Conventions/PropertyMappingValidationConventionTest.cs
test/EFCore.Tests/Metadata/Internal/InternalNavigationBuilderTest.cs
test/EFCore.Tests/Metadata/Internal/InternalPropertyBuilderTest.cs
test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs

Fixes #18561 
Update the usage of `IInfrastructure<T>` on Fluent API classes to use the public `IConventionXyzBuilder` interfaces instead of the `InternalXyzBuilder` ones.
Note: breaking change.

Fix 18561. Update IInfrastructure on Fluent API to use public interfaces

---

test/EFCore.InMemory.FunctionalTests/Query/ManyToManyQueryInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/Query/ManyToManyQueryInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/Query/ManyToManyQueryRelationalFixture.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/CompositeToLeafFullySpecified.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityBranch.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityCompositeKey.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityLeaf.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityOne.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityRoot.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityThree.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityTwo.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/OneToBranchFullySpecified.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/OneToThreeFullySpecifiedWithPayload.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/OneToTwoFullySpecified.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/SharedTyped.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ThreeToCompositeFullySpecified.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/TwoSelfFullySpecified.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/TwoToThreeFullySpecified.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyQuerySqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyQuerySqliteTest.cs

Entities:
One, Two, Three - regular
CompositeKey - entity with composite key
Root, Branch, Leaf - inheritance
Navigations (all many to many have corresponding navigation on the other side that is not listed here):
One
- TwoFullySpecified
- ThreeFullySpecifiedWithPayload
- TwoSharedEntity
- ThreeSharedEntity
- SelfSharedEntityWithPayload
- BranchFullySpecified
Two
- ThreeFullySpecified
- SelfFullySpecified
- CompositeSharedEntity
Three
- CompositeFullySpecified
- RootSharedEntity
Composite
- RootSharedEntity
- LeafSharedEntity
For now shared entity scenarios are not supported in metadata API so we added linking entities temporarily. Those should be removed once the support is in.

Adding model for Many to Many scenarios

---

src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs

Resolves #20498
Manually tested in debugger. Cannot write a test since LINQ Where requires bool and does not accept bool?

Query: Avoid potential null to bool cast

---

src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs

Fixes #19670 
Update `ForeignKeyAttributeConvention` to also run when a new navigation is added.

Fix for 19670. ForeignKeyAttributeConvention run when new Navigation is added.

---

src/EFCore.Relational/Extensions/RelationalKeyBuilderExtensions.cs
src/EFCore.SqlServer/Extensions/SqlServerKeyBuilderExtensions.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/KeyBuilder`.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
test/EFCore.Tests/Metadata/MetadataBuilderTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs

Fixes #15380. Adds a generic version of `KeyBuilder`.

Fix for 15380. Generic KeyBuilder.

---

src/EFCore.Abstractions/BackingFieldAttribute.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/NavigationBackingFieldAttributeConvention.cs
test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs

Fixes #20471 
Update so the `BackingFieldAttribute` also works for navigation properties.

BackingFieldAttribute also works for Navigations.

---

src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs

Issue: When evaluating MemberInitExpression/ListInitExpression, we skipped visiting inner NewExpression if other components were not evaluatable.
We did this since if we cannot evaluate NewExpression otherwise due to structure of expression which does not take ParmeterExpression in place of NewExpression.
But existing logic skipped visiting NewExpression altogether, leaving behind closure variable inside NewExpression.
Fix: Visit NewExpression so that it's components are marked for parameterization and explicitly disallow evaluating NewExpression
Resolves #20502

Query: Parameterize components of NewExpression when possible

---

src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerTestModelBuilderExtensions.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs

After doing #20516 for `KeyBuilder` I noticed that we had some similar work to do to use the (already existing) generic `IndexBuilder` - so this is that work.

Use the generic IndexBuilder.

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs

During translation, when we decide whether we can apply JOIN or APPLY we visit inner SelectExpression looking for references to tables in the outer SelectExpression.
Problem was that we were using Contains method, which would not match cases where the outer table was in the form of JoinExpressionBase.
Fix is to use ContainsTableReference method which matches different types of tables.
Invalid sql generated for relatively complicated but common query pattern. No easy workaround.
**How found**
We have added test to cover this scenario.
No.
**Risk**
Low. Fix is very isolated. Logic used to fix the issue is already being used in other places without problems. Quirk added.

[3.1] Fix to #19825 - Query: incorrectly generating JOIN rather than APPLY for subqueries with outside references to a joined table

---

src/EFCore.Relational/Query/Internal/CaseWhenFlatteningExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs

- Added CaseWhenFlatteningExpressionVisitor postprocessor
- Recursively collapse relevant CaseExpression
Invalid sql generated for query with multi level conditional expression. Some scenarios can work around the problem by rewriting the queries, but when the case statements are generated (e.g. in some OData scenarios) we don't have a good workaround.
**How found**
We have added test to cover this scenario.
No.
**Risk**
Low. Fix is very isolated and the logic the fix employs is straightforward. Quirk added to further mitigate the risk.

[3.1] Fix to #12729 - Flatten Case expression

---

src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs

Resolves #19990
When inferring type mapping, use inferred type mapping's clr type to determine resulting sqlExpression's type.

Query: Assign types for SqlExpression correctly

---

src/EFCore/Infrastructure/ExpressionExtensions.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

Extends fix for #15080 to navigation expansion too where we check for outerKey != null before correlation predicate.

Query: Check for all PK value for collection navigation expansion

---

src/EFCore.Cosmos/Query/Internal/SqlUnaryExpression.cs
src/EFCore.Design/Design/Internal/CSharpHelper.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore.Relational/Migrations/MigrationCommandListBuilder.cs
src/EFCore.Relational/Query/SqlExpressions/SqlUnaryExpression.cs
src/EFCore.Relational/Storage/IRelationalCommandBuilder.cs
src/EFCore.Relational/Storage/RelationalCommandBuilder.cs
src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
src/EFCore/Infrastructure/IndentedStringBuilder.cs
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/ExpressionPrinter.cs
src/EFCore/Query/ProjectionBindingExpression.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs

Fixes #20383
Looked at making it pubternal or internal again, but it seems to be fundamental to the C# code generators in the design assembly. Considered moving it to design, but that would result in duplicate internal code other places. So just documented and cleaned up the surface--in particular, it only handles strings so that any possible locale-specific string conversions are forced to happen outside.

Cleanup and add documentation for IndentedStringBuilder

---

src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs

Do not output the SQL Server decimal warning if the user has specified a value converter.
Fixes #20406

Fix for 20406. Do not output unnecessary decimal warning

---

test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs

This test was very slow against in-memory. Reduced the amount of data used without, hopefully, impacting the intent of the test. Results in 10 seconds faster total test run time on my machine.

Tweak slow-running test.

---

src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Throw a better exception if only 1 navigation is specified on a many-to-many relationship.
Fixes #20508

Fix for 20508 - Throw if only 1 navigation on many-to-many

---

eng/Version.Details.xml
eng/Versions.props

Reacting to dotnet/arcade#5195
Darc can downgrade dependencies that we don't want it to, when the parent we list as a CPD doesn't also depend on those things. Pinning these dependencies while the above issue is resolved.
CC @mmitche

Pin 2 CoreFx dependencies

---

src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs

Problem was that when we were rewriting methods from Enumerable to Queryable we didn't correctly handle conversion from IOrderedEnumerable to IOrderedQueryable.
When that conversion happens inside lambda, the lambda expression needs to be rebuild since the types (unlike Enumerable to Queryable) are not compatible.
Resolves #20578

Fix to #20578 - Query: filtered include fails when orderby is the last operation inside the Include

---

src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs

Fixes #20557
EF generates aliases in the SQL query based on the projection properties. However "value" is a keyword in CosmosDB, so projections with a "Value" property result in invalid SQL.
This is especially impactful when used with OData, as it generates this type of queries frequently and there's no workaround for the user.
Reported by customer.
Added a test using this pattern.
No.
Low. Fix only affects the alias used in the SQL.

[release/3.1] Cosmos: Avoid using "value" as an alias

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/ContainsTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

Query: Remove object convert for Contains

---

src/EFCore/Diagnostics/CoreLoggerExtensions.cs
src/EFCore/Diagnostics/ForeignKeyCandidateEventData.cs
src/EFCore/Diagnostics/IncompatibleMatchingForeignKeyEventData.cs
src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Infrastructure/CoreEventIdTest.cs
test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs

Fixes #15759  Update the error message/logging to include the entity types involved in order to make it clearer.

Fix for 15759. Update an error message for FK properties mismatch

---

test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
test/EFCore.Specification.Tests/ConvertToProviderTypesTestBase.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs

Testing introduced in #20470
When syncing, EFCore.PG fails the new Object_to_string_conversion because PostgreSQL strips trailing zeros from the TimeSpan representation, so we get back `10:09:08.007` instead of `10:09:08.0070000` which is what .NET does.
As recently discussed, we shouldn't expect parameterless ToString to yield precisely the same representation in the database as in .NET. The other types tested in this test seem fine, except maybe for decimal which could also suffer from a similar issue (but doesn't for PG).

Remove testing for ToString behavior on TimeSpan

---

src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/TestUtilities/QueryTestExtensions.cs

Query: Fix Max/Min after DefaultIfEmpty

---

src/EFCore.InMemory/Query/Internal/AnonymousObject.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore/Infrastructure/ExpressionExtensions.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs

- Make it implementation detail of InMemory provider which still needs it to match outer/inner keys of a join executed on server side
Resolves #20565

Query: Remove AnonymousObject

---

src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/ColumnExpression.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeQuerySqliteTest.cs

We skipped doing it during left join which was incorrect.
We need to apply it for every join and account for it could be null for LeftJoin/OuterApply.
- Make columnExpression.Type nullble if it is nullable.
- Add some fancy code in TestSqlLoggerFactory to write directly into file updating baselines (I ran into updating 234 baselines).
- Off by default
- Can set indent if it is higher than usual
- Only works when number of lines do not change

Query: Add identifier appropriately when generating joins

---

src/EFCore/Diagnostics/CoreEventId.cs
src/EFCore/Diagnostics/CoreLoggerExtensions.cs
src/EFCore/Diagnostics/Internal/InvalidIncludePathEventData.cs
src/EFCore/Diagnostics/LoggingDefinitions.cs
src/EFCore/Infrastructure/CoreOptionsExtension.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Fix is to use logging infrastructure for the "invalid include path" error. Log event is configured to throw by default but can be overriden in the dbcontextoptions. Event id is CoreEventId.InvalidIncludePathError
Resolves #20609

Fix to #20609 - Includes() with string throws not finding navigation path exception when type T is derived

---

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs
test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs

Sqlite: Empty string init and coalescing for various properties

---

src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

Calling ModelBuilder.Entity() followed by .Owned() could cause NRE.
Fixes #20446

Calling ModelBuilder.Entity() followed by .Owned() could cause NRE

---

src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs

- Store the document that Cosmos returns after Create and Replace operations onto the __jObject shadow property, ensuring it always exists after a database operation (previously it would only exist after queries)
- Use instead of ignore the value of the __jObject shadow property on entity adds, allowing untracked properties to be populated on new entities before they're added.
Resolves #17778

Cosmos: Populate __jObject on SaveChanges

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
src/EFCore/Extensions/ConventionPropertyExtensions.cs
src/EFCore/Extensions/MutablePropertyExtensions.cs
src/EFCore/Extensions/PropertyExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
src/EFCore/Metadata/Internal/Property.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs

Part of #20409
Type mappings need to be able to provide different comparers for key and non-key property. However, when a key comparer is being set on a specific property, then a key comparer can be set for key properties and a regular comparer can be set for non-key properties. We don't need to support setting both on the same property.
Also remove the fallback parameter, per API review.

Obsolete key comparers on properties

---

src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalModelBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalOwnedNavigationBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Metadata/Internal/Sequence.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Update/ColumnModification.cs
src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/EFCore.Relational/Update/ModificationCommand.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
test/EFCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs

Add complex mapping support to the update pipeline

---

src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

SQLServer: Support fill factor for index

---

README.md

The link to release planning process is pointing to https://docs.microsoft.com/ef/core/what-is-new/#release-planning-process instead of https://docs.microsoft.com/en-us/ef/core/what-is-new/release-planning.

Update link to release planning process

---

src/EFCore/ValueGeneration/SequentialGuidValueGenerator.cs

Following investigation in #20528 and #19124.
/cc @peroyhav

Correct documentation for SequentialGuidValueGenerator

---

src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTransaction.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Relational/Update/Internal/BatchExecutor.cs
src/EFCore/Infrastructure/DatabaseFacade.cs
src/EFCore/Storage/ExecutionStrategyExtensions.cs
src/EFCore/Storage/IDbContextTransaction.cs
src/EFCore/Storage/IDbContextTransactionManager.cs
test/EFCore.InMemory.Tests/InMemoryTransactionManagerTest.cs
test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
test/EFCore.Relational.Tests/RelationalConnectionTest.cs
test/EFCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs
test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
test/EFCore.Tests/DatabaseFacadeTest.cs
test/EFCore.Tests/TestUtilities/TestInMemoryTransactionManager.cs

Expose async transaction commit/rollback APIs

---

src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/IColumn.cs
src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Migrations/Operations/Builders/ColumnsBuilder.cs
src/EFCore.Relational/Migrations/Operations/ColumnOperation.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Scaffolding/Metadata/DatabaseColumn.cs
src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs

Closes #6682
| Database   | Stored name | Virtual name                  | Default                                  | Docs |
|------------|-------------|-------------------------------|------------------------------------------|------|
| SQL Server | PERSISTED   | &lt;empty&gt;                 | &lt;empty&gt; (virtual)                  | https://docs.microsoft.com/en-us/sql/relational-databases/tables/ |specify-computed-columns-in-a-table?view=sql-server-ver15
| Sqlite     | STORED      | VIRTUAL                       | VIRTUAL                                  | https://www.sqlite.org/gencol.html |
| PostgreSQL | STORED      | VIRTUAL (not yet implemented) | None, STORED must currently be specified | https://www.postgresql.org/docs/12/ddl-generated-columns.html |
| MySQL      | STORED …

Add option for specifying stored/virtual on computed columns

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs

Ignore hypothetical indexes (now with test!)

---

src/EFCore.Design/Design/Internal/CSharpHelper.cs
test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs

Fixes #20662 
Generating the verbatim string literal syntax in the migration `HasData()` and snapshot `BuildModel()` code where the input data had line breaks in it caused problems because the code generators would add an additional indent at the newline and hence unintentionally add spaces to the string literal.
Now we generate "\r" and "\n" in non-verbatim strings instead.

Fix for 20662. Linebreaks in HasData() in migration

---

src/EFCore.Relational/Extensions/RelationalDbFunctionsExtensions.cs
src/EFCore.Relational/Query/Internal/CollateTranslator.cs
src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/QuerySqlGenerator.cs
src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/CollateExpression.cs
src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/RelationalNorthwindDbFunctionsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindDbFunctionsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs

New EF.Functions.Collate

---

src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Relational/Update/Internal/BatchExecutor.cs
src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTransaction.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTransactionFactory.cs
src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteTransaction.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteTransactionFactory.cs
src/EFCore/Infrastructure/DatabaseFacade.cs
src/EFCore/Storage/IDbContextTransaction.cs
src/EFCore/Storage/IDbContextTransactionManager.cs
test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
test/EFCore.Relational.Tests/RelationalConnectionTest.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
test/EFCore.Tests/DatabaseFacadeTest.cs

* Add APIs for supporting transaction savepoints.
* Support is implemented at the EF level only, no System.Data support yet (this should come soon).
* Use savepoints in the update pipeline when a user-managed transaction is used, to roll back to before SaveChanges in case of exception.
Some notes:
* See SaveChanges_uses_explicit_transaction_with_failure_behavior for how savepoints help with SaveChanges failures.
* Another good example is Database_concurrency_token_value_is_discarded_for_non_conflicting_entities, which isn't needed anymore because the entire SaveChanges is rolled back if any conflict occurs. I wonder if we should still have a test for this - this may require an escape hatch flag that allows running without savepoints even if the provider supports them (but I'm not sure …

Add savepoint support

---

src/EFCore.SqlServer/Storage/Internal/SqlServerTransaction.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTransactionFactory.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteTransaction.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteTransactionFactory.cs

All tests pass locally, @smitpatel can you approve?

Add missing XML docs

---

src/EFCore.Design/Design/DbContextActivator.cs
src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/Internal/MigrationsOperations.cs
src/EFCore.Design/Design/OperationExecutor.cs
src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/dotnet-ef/RootCommand.cs
src/ef/AppDomainOperationExecutor.cs
src/ef/CommandLineUtils/CommandLineApplication.cs
src/ef/Commands/CommandBase.cs
src/ef/Commands/DatabaseDropCommand.cs
src/ef/Commands/DatabaseUpdateCommand.cs
src/ef/Commands/DbContextInfoCommand.cs
src/ef/Commands/DbContextListCommand.cs
src/ef/Commands/DbContextScaffoldCommand.cs
src/ef/Commands/DbContextScriptCommand.cs
src/ef/Commands/HelpCommandBase.cs
src/ef/Commands/MigrationsAddCommand.cs
src/ef/Commands/MigrationsListCommand.cs
src/ef/Commands/MigrationsRemoveCommand.cs
src/ef/Commands/MigrationsScriptCommand.cs
src/ef/Commands/ProjectCommandBase.cs
src/ef/Commands/RootCommand.cs
src/ef/IOperationExecutor.cs
src/ef/OperationExecutorBase.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx
src/ef/ReflectionOperationExecutor.cs

Fixes #8332 
This updates the dotnet-ef, ef and PowerTools to pass in the arguments

Fix for 8332. Pass in arguments to IDesignTimeDbContextFactory 

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
src/EFCore/Query/QueryCompilationContext.cs
src/EFCore/Query/QueryContext.cs
src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
tools/Resources.tt

- Uses an adhoc statemanager in the background which is different from statemanager in the context
Resolves #19877

Query: Introduce identity resolution in no tracking query

---

src/EFCore.Relational/Metadata/Conventions/AddConcurrencyTokenPropertiesConvention.cs
src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs
test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs

Fixes #18063 . Previously if the user was table-splitting and one or more entity types did not map to a concurrency column, we used to throw warning the user to configure the property. Now we simply add it ourselves in shadow state.

Fix for 18063. Add missing concurrency token properties for table splitting

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/EqualsTranslator.cs
src/EFCore.Relational/Query/Internal/EqualsTranslator.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/ConvertToProviderTypesTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs

Query: Remove convert node around object.Equals with value types

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

There's a bug where if you pass no remaining arguments to the Powershell commands you get the error:
```
You cannot call a method on a null-valued expression.
```
This fixes that.

Only add the RemainingArguments if they are defined.

---

test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs

It passes with latest emulator
Resolves #20453

Query: Enable skipped test for #20453

---

src/EFCore.Design/Design/Internal/DatabaseOperations.cs
src/EFCore.Design/Design/Internal/DbContextOperations.cs
src/EFCore.Design/Design/Internal/MigrationsOperations.cs
test/EFCore.Design.Tests/Design/Internal/DatabaseOperationsTest.cs
test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
test/EFCore.Design.Tests/Design/Internal/MigrationsOperationsTest.cs
test/EFCore.Design.Tests/TestUtilities/TestDatabaseOperations.cs
test/EFCore.Design.Tests/TestUtilities/TestMigrationsOperations.cs

Fixes #20741 
Allow older versions of tools to pass null args. This should fix @ajcvickers [comment](https://github.com/dotnet/efcore/issues/20741#issuecomment-620077080). There may still be underlying issues with `MigrationsModelDiffer`.

Fix for 20741. Allow older versions of tools to pass null args.

---

src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore/Properties/CoreStrings.Designer.cs
tools/Resources.tt

Update `Resources.tt` to output `[Obsolete]` for string resources, not just for event definitions. Also some .Designer.cs files were not up to date.
Note: Obsolete originally added due to comment [here](https://github.com/dotnet/efcore/pull/20726#discussion_r414114742).

Output [Obsolete] for string resources.

---

src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
src/EFCore.Design/Scaffolding/Metadata/Internal/DatabaseColumnExtensions.cs
src/EFCore.Design/Scaffolding/Metadata/Internal/DatabaseForeignKeyExtensions.cs
src/EFCore.Design/Scaffolding/Metadata/Internal/DatabaseTableExtensions.cs
src/EFCore.Design/Scaffolding/ScaffoldedFile.cs
src/EFCore.Design/Scaffolding/ScaffoldedModel.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseColumn.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseForeignKey.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseIndex.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabasePrimaryKey.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseSequence.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseTable.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseUniqueConstraint.cs
src/EFCore.Relational/Scaffolding/Metadata/DatabaseView.cs
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpUniqueNamerTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CandidateNamingServiceTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs

API Review: revert scaffolding nullability breaking changes

---

src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressions/SqlBinaryExpression.cs
src/EFCore.Relational/Query/SqlExpressions/SqlUnaryExpression.cs
test/EFCore.Specification.Tests/Query/NorthwindCompiledQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindCompiledQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/CompiledQueryInMemoryTest.cs

Query: MakeUnary/Binary should return null if invalid operator type

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs

Query: Translate NegateChecked to SQL

---

src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
src/EFCore.Relational/Metadata/Conventions/SequenceUniquificationConvention.cs
src/EFCore.Relational/Metadata/Internal/Sequence.cs
test/EFCore.Relational.Tests/Metadata/Conventions/SequenceUniquificationConventionTest.cs

Fixes #19608 
Truncate and uniquify Sequence Names within each schema.

Fix for 19608. Truncate/Uniquify Sequence Names.

---

test/EFCore.Relational.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs

For consistency with MigrationsSqlGenerator

Rename MigrationSqlGeneratorTest -> MigrationsSqlGeneratorTest

---

src/EFCore.Relational/Query/ISqlExpressionFactory.cs
src/EFCore.Relational/Query/NullabilityBasedSqlProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/QuerySqlGenerator.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs

- Table sources which takes alias should have alias as first argument.
- Single API to create select expression for all custom query roots-> custom table sources
- QuerySqlGenerator.Generate* methods are void and appends to command builder directly.

Query: Consistency issues

---

src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
src/EFCore.Relational/Query/RelationalParameterBasedQueryTranslationPostprocessor.cs
src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedQueryTranslationPostprocessor.cs
test/EFCore.SqlServer.FunctionalTests/Query/AsyncFromSqlQuerySqlServerTest.cs

Resolves #20204
For table sources, there is no concept of nullability
- `Process(TableExpressionBase)` which works as dispatcher.
- `Process(SelectExpression)` as a special case to avoid casting.
- No additional methods for individual table sources.
For SQL expressions,
- `Process(SqlExpression, out bool nullable)` which defaults allowOptimizedExpansion to false.
- `Process(SqlExpression, allowOptimizedExpansion, out bool nullable)` which works as dispatcher.
- Individual Process* methods to change bahavior of any particular SqlExpression.
Notes:
- Each individual SQLExpression processes it's children with appropriately set allowOptimizedExpansion flag. It collects nullable flag for all children and return nullable for itself through out parameter.
- NonNullableColumns are being used only …

Query: Improve extensibility of null semantics processor

---

benchmark/EF.Benchmarks.Shared/Models/Orders/OrderLine.cs
benchmark/EF.Benchmarks.Shared/Models/Orders/Product.cs
benchmark/EF6.SqlServer.Benchmarks/Query/QueryCompilationTests.cs
benchmark/EFCore.Benchmarks/Query/QueryCompilationTests.cs

Because Sqlite doesn't support operations on decimals (e.g. ordering)
Fixes #20822

Replace decimal with double in benchmarks

---

test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs

Pretty trivial since it's just DROP/CREATE, but coverage seems important especially since we now generate check constraints automatically for enums (#15411).

Add test coverage for altering check constraints

---

eng/Versions.props
src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs

Generated column support for Sqlite

---

eng/Versions.props
src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs

We ignore now when paramters are not initialized in case a EXPLAIN query is used.
Fixes #16647

Sqlite: Support uninitialized EXPLAIN queries

---

src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
src/EFCore.Relational/Extensions/RelationalDbFunctionsExtensions.cs
src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
src/EFCore/ChangeTracking/ChangeTracker.cs
src/EFCore/DbContextOptionsBuilder.cs
src/EFCore/DbContextOptionsBuilder`.cs
src/EFCore/DbLoggerCategory.cs
src/EFCore/Diagnostics/WarningsConfiguration.cs
src/EFCore/EF.cs
src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/Update/IUpdateAdapter.cs

Clean up <code> in XML docs

---

src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs

Query: Cosmos: Generate enum literal/parameter correctly

---

src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindMiscellaneousQueryInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeAsyncQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.Specification.Tests/Query/QueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Adding state to ExpressionTranslatingExpressionVisitor that stores the information about why translation failed. The information is bubbled up and added to the "translation failed" exception.
Currently only doing this for string.Equals and non-mapped member properties

Fix to #20612 - Throw helpful translation exception for String.Equals(String, StringComparison)

---

test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/QueryTestBase.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

Remove AssertIncludeQuery which is based on queryable
Introduce AssertInclude method over element which can be used anywhere element asserter can be passed just like collection asserter
Resolves #15368

Tests : A better infrastructure for asserting includes in the query

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs

Refer to branch name :trollface:

Switch expression in SqlNullabilityProcessor + cleanup

---

src/EFCore.Relational/Diagnostics/DbTransactionInterceptor.cs
src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs
src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
src/EFCore.Relational/Storage/IRelationalTransactionManager.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
test/EFCore.Relational.Tests/RelationalConnectionTest.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs

Add overload that takes a GUID to use for the transaction ID.
Fixes: #20828 
Please review

Use existing transaction identifier in RelationalConnection.UseTransaction 

---

test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

Issue has been fixed in earlier commit.
Resolves #13906

[TINY] Regression test for #13906 - String.CompareTo emits unicode literal against varchar column

---

test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

[TINY] Add regression test for #20992 - Select with coalesce operator on field non unicode string should not append N

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
src/EFCore/Query/QueryContext.cs
src/EFCore/Query/QueryContextDependencies.cs
test/EFCore.Tests/ApiConsistencyTestBase.cs

Resolves #21016
All scoped services used while executing the query comes from QueryContext.
All scoped services on QueryCompilationContext should only be used while compiling the query and should not be made part of QueryExecutorLambda.
Singleton services comes from QueryCompilationContext and added to the QueryExecutorLambda directly during compilation.

Use scoped query logger from QueryContext

---

src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
test/EFCore.InMemory.FunctionalTests/GlobalDatabaseTest.cs

Differentiate between owned types correctly when using in-memory database with string matching

---

src/EFCore/Diagnostics/CoreEventId.cs
src/EFCore/Diagnostics/CoreLoggerExtensions.cs
src/EFCore/Diagnostics/LoggingDefinitions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs

Warning is issued for required navigations for which required side has query filter and the optional side doesn't.
When both sides define query filters we assume they are correct, i.e. we don't peek inside the filters to make sure they are consistent.
Fixes #19801

[SMALL] Fix to #19801 - Query: add validation to warn about required navigations pointing to entity with query filter

---

src/EFCore.Design/Design/DbContextActivator.cs
test/EFCore.Design.Tests/Design/DbContextActivatorTest.cs

CTI testing resulted in this exception from tooling:
```
Method not found: 'Microsoft.EntityFrameworkCore.DbContext Microsoft.EntityFrameworkCore.Design.DbContextActivator.CreateInstance(System.Type, System.Reflection.Assembly, Microsoft.EntityFrameworkCore.Design.IOperationReportHandler)'.
```

Fix preview 5 break in DbContextActivator

---

src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Metadata/Conventions/IndexAttributeConventionTest.cs

See [this comment](https://github.com/dotnet/efcore/pull/21012#discussion_r432024488) and the ones above it. I put in the  messages for named and unnamed indexes for Relational, but I forgot there were 2 messages in Core that needed the same treatment. This fixes that.

More on 4050. Named and unnamed versions of Core index errors.

---

src/EFCore.Relational/Query/ISqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMemberTranslator.cs
src/EFCore.SqlServer.NTS/Query/Internal/SqlServerPointMemberTranslator.cs

Resolves #20409
- Updated obsolete message for old methods
- Renamed newly added methods

API review: Rename ISqlExpressionFactory.Function to NiladicFunction

---

src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs

Fixes #21072
Rename GetName/GetDefaultName methods to GetDatabaseName/GetDefaultDatabaseName in index extension methods.

Fix for 21072. Rename GetName etc methods to GetDatabaseName etc

---

eng/Versions.props
test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/Northwind/Customer.cs

Fixes #20548
Added tests that serialize graphs with both the BCL Json support and Newtonsoft.Json.
Findings:
* BCL Json
* Preserving references working fine; needed to increase max-depth for heavily nested graph, but exception message was clear
* Lack of an Ignore option may be missed because output is harder to understand when it contains many internal references. Will follow up on this.
* Newtonsoft.JSON
* Found it easy to get out-of-memory errors even when ignoring cycles
* ~~Got stack overflow errors when attempting to serialize cycles instead of ignoring them~~
* ~~I'm probably not configuring things correctly here, but this isn't high priority~~
* Net Topology Suite types are not JSON-serialization-friendly; will follow up on this

Test JSON serialization of EF object graphs

---

src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/EFCore.Relational/Update/Internal/IKeyValueIndexFactory.cs
src/EFCore.Relational/Update/Internal/KeyValueIndexFactory.cs
src/EFCore.Relational/Update/ModificationCommand.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/ValueGenerationConvention.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs

Fixes #20932
The first time a CLR type is used as an owned collection it is not weak. Value generation is set correctly.
The second time, it becomes weak, and value generation is set correction for both usages.
The first time, it is already weak, but the FK is marked as IsOwnersShip after value generation has been set.
The fix to run the value generation convention again when FK ownership changes.

Mark owned collections composite key properties to use generated values even after the first two usages

---

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
test/EFCore.Cosmos.FunctionalTests/OverzealousInitializationCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/OverzealousInitializationInMemoryTest.cs
test/EFCore.Specification.Tests/OverzealousInitializationTestBase.cs
test/EFCore.SqlServer.FunctionalTests/OverzealousInitializationSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/OverzealousInitializationSqliteTest.cs

Fixes #18007
Previously it was possible for the existing instance to be replaced when a query brings back a new instance, but only for the first time the new instance is returned. This change prevents the new instance from being used in all cases, which is the agreed behavior here, and also now matches what EF6 does consistently.

Consistent fixup from query when reference navigation explicitly set

---

test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs

Fixes #20432
Issue was already fixed in 5.0. Adding tests.

Tests for array literals in migrations data

---

Directory.Build.props

Outside tooling hasn't yet adapted to the new net5.0 TFM, e.g. Rider (https://youtrack.jetbrains.com/issue/RIDER-45160). Since netcoreapp5.0 works fine, we can temporarily switch back to it.

Temporarily switch back TFMs from net5.0 to netcoreapp5.0

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Relational/Metadata/Internal/ColumnListComparer.cs
src/EFCore.Relational/Metadata/Internal/ColumnMappingBaseComparer.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Metadata/Internal/TableMappingBaseComparer.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/EFCore.Relational/Update/Internal/SharedTableEntryMap.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Extensions/MutableEntityTypeExtensions.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalFixture.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs

Sort table mappings consistently
Remove discriminator-related facets completely when using TPT
Simplify SharedTableEntryMap
Part of #2266

Add support for seed data for entity types using table sharing where the principal is using TPT

---

eng/Versions.props
rulesets/Documentation.ruleset
rulesets/EFCore.ruleset
src/Directory.Build.props
src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
src/EFCore/Diagnostics/InterceptionResult`.cs
src/EFCore/Diagnostics/WarningsConfiguration.cs
src/EFCore/EF.cs
src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs

Just racking up the consistency points on a fine Monday morning.
Closes #21094

Starting using DocumentationAnalyzers

---

src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
src/EFCore.Relational/Update/ModificationCommand.cs
src/EFCore/Metadata/Internal/PropertyExtensions.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs

Fixes #21041.
All concurrency properties should be able to store "store-generated values". Note: in this context "store-generated values" just means "can be injected from the update pipeline".
Also updated `TableSharingConcurrencyTokenConvention` to create shadow concurrency property for all concurrency properties in the hierarchy, even non-store-generated ones.

Fix for 21041. Make all concurrency properties capable of storing "store-generated values"

---

src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

* Translate to LIKE instead of CHARINDEX for constant patterns
* Change empty string compensation from equality to LIKE
*EDIT:* This can't currently be fixed, and not just because of the compensation - the main translation - `LEFT(LEN))` - also doesn't work for whitespace-only patterns (see https://github.com/dotnet/efcore~/pull/21097#issuecomment-637031454). Nothing to do about this for now.
~StartsWith/EndsWith still isn't fixed with regards to empty string compensation, so a whitespace-only pattern returns all rows. I can't change it to use LIKE, since the compensation happens in preprocessing. Our options:~
~1. Keep things the same, so we have false positives when the pattern is whitespace-only (all rows returned)~
~2. Remove the compensation, so we'll have a false negative for empty …

Fix SQL Server Contains whitespace issues

---

Directory.Build.props
eng/helix.proj

Outside tooling hasn't yet adapted to the new net5.0 TFM, e.g. Rider (https://youtrack.jetbrains.com/issue/RIDER-45160). Since netcoreapp5.0 works fine, we can temporarily switch back to it.
Will not accidentally merge before it's green this time around...

Temporarily switch back TFMs from net5.0 to netcoreapp5.0, take 2

---

src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/IConventionEntityType.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/Index.cs

See comments in PR #21115 (for issue #21089). Missed some `[NotNull]` statements. Plus minor docs change.

Further fix for 21089. Some missed NotNulls.

---

src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs

Added model validation rule.
Fixes #18565

[SMALL] Fix to #18565 - Throw when a query filter is configured on an owned type

---

src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
src/EFCore/Query/Internal/CompiledQueryCache.cs
src/EFCore/Query/Internal/ICompiledQueryCache.cs

Closes #18516
tl;dr While results aren't very conclusive, this PR replaces spinning with an equivalent lock-based approach.
* The objective here is to remove the spinning loop that occurs when another thread is already compiling our query, and to generally simplify synchronization.
* I checked replacing the spinning loop with two things:
* LOCKING: A proper lock; this keeps the behavior where multiple threads don't compile the same query, but rather the first one compiles and the others wait for it (just not via spinning).
* NOSYNC: No synchronization, so multiple threads that happen to execute an un-compiled query compile in parallel.
* I used two benchmarking scenarios (the MemoryCache is compacted/reset at the beginning of each invocation):
* Simply spin up 16 threads which execute the …

Rewrite cache synchronization to lock instead of spin

---

src/EFCore.Relational/Diagnostics/DbCommandInterceptor.cs
src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs
src/EFCore.Relational/Diagnostics/DbTransactionInterceptor.cs
src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
src/EFCore.Relational/Diagnostics/IDbConnectionInterceptor.cs
src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs
src/EFCore.Relational/Diagnostics/Internal/DbCommandInterceptorAggregator.cs
src/EFCore.Relational/Diagnostics/Internal/DbConnectionInterceptorAggregator.cs
src/EFCore.Relational/Diagnostics/Internal/DbTransactionInterceptorAggregator.cs
src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
test/EFCore.Relational.Specification.Tests/ConnectionInterceptionTestBase.cs
test/EFCore.Relational.Specification.Tests/TransactionInterceptionTestBase.cs

Closes #21109
(cherry picked from commit 9f316e5b6150b4abdbd75697823eec27cef64523)

Return ValueTask in loggers and interceptors (merge to preview6)

---

src/EFCore.SqlServer/Query/Internal/SqlServerConvertTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs

[TINY] Fix to #19606 - Query: add support for convert to/from bool value using Convert.To* methods

---

src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerIndexExtensions.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsInfrastructureSqlServerTest.cs

Add extra defensive checks
Part of #2266

Validate that derived types in TPT aren't sharing table as dependants

---

src/EFCore/Storage/ValueConversion/IPAddressToStringConverter.cs
test/EFCore.Tests/Storage/ValueConverterSelectorTest.cs

Set hint size for IPAddress string representation to 45

---

src/EFCore/Query/ExpressionEqualityComparer.cs

Closes #17757
Note: the assumes that the same ParameterExpression instance cannot appear in the parameter list of nested lambdas, which I'm pretty sure is correct, but would be good to confirm with the experts.

Reduce allocations in ExpressionEqualityComparer

---

eng/helix.proj

Helix: Start LocalDB early to make tests more reliable

---

src/EFCore/ChangeTracking/ChangeTracker.cs
src/EFCore/ChangeTracking/Internal/IStateManager.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
test/EFCore.Tests/TestUtilities/FakeStateManager.cs

Fixes #15577
This is an alternative to mass-detach for situations where creating a new context instance is difficult.
The context configuration is not reset, since it seems likely that setting like lazy-loading and registered events are more useful left as they would be--just as is the case when doing mass-detach.

Implement ChangeTracker.Clear() to stop tracking all entities

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs

Correctly processing values expression for the relational nulls code path
Fixes #21164

[SMALL] Fix to #21164 - Error translating Contains expression when UseRelationalNulls(true)

---

src/EFCore.Relational/Query/QuerySqlGenerator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs

Move fake ORDER BY clause to SQL Server provider

---

src/EFCore.Relational/Query/QuerySqlGenerator.cs
test/EFCore.Relational.Tests/Query/Internal/QuerySqlGeneratorTest.cs

And rewrite without regex
Fixes #18412

Ignore comments in SQL composability check

---

src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs

- Move ReaderColumns to RelationalCommandCache

Query: Introduce FromSqlQueryingEnumerable for non composed FromSql

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindJoinQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindJoinQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs

Resolves #19247
Resolves #17763
Lays ground work for #20291
Required for #20892

Query: Perform join operations when one of the source has client eval

---

src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalIndexTest.cs
test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs
test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
test/EFCore.Tests/Metadata/Conventions/IndexAttributeConventionTest.cs

Fixes #21133 .
IndexAttribute properties did not have the right TypeMappings. Also create indexes before ModelFinalizing to allow fluent api overrides.

Fix for 21133. IndexAttribute properties did not have the right TypeMappings

---

src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs

Make NotMapped take precedence over other attributes that reference properties

---

test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeNoTrackingQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeNoTrackingQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqliteTest.cs

Add tests for split include and no tracking

---

src/EFCore/Metadata/ParameterBinding.cs

Use the correct parameter name in the null guard exception.
Fixes #21233

Fix parameter name

---

.github/dependabot.yml
benchmark/Directory.Build.props
benchmark/EFCore.Benchmarks/EFCore.Benchmarks.csproj
benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
eng/Versions.props
src/Directory.Build.props
src/EFCore.Abstractions/EFCore.Abstractions.csproj
src/EFCore.Analyzers/EFCore.Analyzers.csproj
src/EFCore.Cosmos/EFCore.Cosmos.csproj
src/EFCore.Design/EFCore.Design.csproj
src/EFCore.InMemory/EFCore.InMemory.csproj
src/EFCore.Proxies/EFCore.Proxies.csproj
src/EFCore.Relational/EFCore.Relational.csproj
src/EFCore.SqlServer.NTS/EFCore.SqlServer.NTS.csproj
src/EFCore.SqlServer/EFCore.SqlServer.csproj
src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj
src/EFCore.Sqlite.NTS/EFCore.Sqlite.NTS.csproj
src/EFCore.Sqlite/EFCore.Sqlite.csproj
src/EFCore/EFCore.csproj
src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
test/EFCore.Analyzers.Tests/EFCore.Analyzers.Test.csproj
test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
test/ef.Tests/ef.Tests.csproj

The NuGet/MSBuild support is pretty primitive and requires us to inline versions.
This is enough to start getting PRs from Dependabot. We can iterate on the configuration as we go.
Once merged, you can view the logs and manually trigger checks using [this page](https://github.com/dotnet/efcore/network/updates).
I've tested this on my fork.

Enable GitHub Dependabot

---

src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindJoinQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindJoinQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs

Extension of #19247 for collection shaper in client eval
This is not required for preview6. But the work depends on other split include work so creating PR against the feature branch, it will auto-cascade to master once those commits reach master.

Query: Process client eval in join when collection shaper

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs

Disable NRTs in scaffolding

---

src/EFCore/Infrastructure/ConcurrencyDetectorCriticalSectionDisposer.cs
src/EFCore/Infrastructure/IConcurrencyDetector.cs
src/EFCore/Internal/ConcurrencyDetector.cs
test/EFCore.Tests/Infrastructure/EntityFrameworkServicesBuilderTest.cs

Eliminate boxing when entering critical sections

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore/Extensions/Internal/ExpressionExtensions.cs
src/Shared/ExpressionExtensions.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

Fix inference issues around convert to object

---

src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/IDbContextFactory.cs
src/EFCore/Internal/DbContextFactory.cs
test/EFCore.Tests/DbContextFactoryTest.cs

Fixes #18575
Mostly this is copied from @JeremyLikness's sample, with tests added. It evolved a bit as I was testing. Most significantly, we now register an IDbContextFactory interface, for which we provide a default implementation. This allows the factory to be replaced by one specific for the application, which can be more performant because it doesn't use ActivatorUtilities. Overloads have been added for this.
I believe we can also add overloads to allow the factory to resolve from a context pool, but I will file a new issue for this.

Add AddDbContextFactory to allow registering a factory for creating contexts

---

src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/Internal/DbContextFactory.cs
src/EFCore/Internal/DbContextFactorySource.cs
src/EFCore/Internal/IDbContextFactorySource.cs
test/EFCore.Tests/DbContextFactoryTest.cs

Improvement to #18575
This change checks if the DbContext has the usual constructor taking just options:
```C#
MyContext(DbContextOptions<MyContext> options)
```
If it does, then we create a delegate (once in a singleton service) and use that to create context instances. This avoids using ActivatorServices and falling out of constructor injection (other than the delegate) for the common case.

Avoid using ActivatorServices for common DbContext constructor

---

src/EFCore.Cosmos/Extensions/CosmosDbContextOptionsExtensions.cs
src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
test/EFCore.Cosmos.FunctionalTests/ConnectionSpecificationTest.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestEnvironment.cs

Add an overload to UseCosmos that takes a connection string.
Fixes #20712
For now, I have some problems with testing it. Could you please suggest if I'm on the right way? I'll continue to work on tests.

Add an overload to UseCosmos that takes a connection string

---

src/EFCore/ChangeTracking/NavigationEntry.cs
test/EFCore.Tests/ChangeTracking/CollectionEntryTest.cs
test/EFCore.Tests/ChangeTracking/ReferenceEntryTest.cs

Restore original value when setting IsModified false on navigation

---

src/EFCore/ChangeTracking/NavigationEntry.cs
test/EFCore.Tests/ChangeTracking/MemberEntryTest.cs
test/EFCore.Tests/ChangeTracking/ReferenceEntryTest.cs

Fixes #16513
I investigated this some more and I now understand why this was labeled a bug. Collection navigations already have this behavior--that is, Deleted or Added related entities indicate that the navigation property is modified. So this change brings reference navigations inline, which I think is a bug. Nevertheless, I think it makes sense to document this as a breaking change.

Return true for IsModified on navigations pointing to Added or Deleted entities

---

src/EFCore.Cosmos/Internal/CosmosModelValidator.cs
src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
src/EFCore.Cosmos/Properties/CosmosStrings.resx
src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs
test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
test/EFCore.Cosmos.Tests/ModelBuilding/CosmosTestModelBuilderExtensions.cs
test/EFCore.Cosmos.Tests/ValueGenerator/Internal/IdValueGeneratorTest.cs

- Rename the 'id' property created by convention to '__id' to avoid it clashing with an entity property.
- Make sure that the property created by the convention is removed if any other property is mapped to 'id' (the new property should get a value generator).
- Remove the value generator from the property mapped to 'id' if it's part of the PK
- Validate all properties have distinct database names
Fixes #17751

Cosmos: Make the 'id' property more flexible 

---

src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs

Query: DRY SelectExpression.AddJoin

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
test/EFCore.Specification.Tests/Query/NorthwindNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Adding COALESCE around SUM sql function expression
Fixes #12657

Fix to #12657 - Query: logic protecting SUM from returning null doesn't work for complex scenarios

---

src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
src/EFCore.Cosmos/Properties/CosmosStrings.resx
src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
src/EFCore/Storage/IDatabaseCreator.cs
test/EFCore.Cosmos.FunctionalTests/ConnectionSpecificationTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbContextOptionsBuilderExtensions.cs
test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs

Use default connection mode by default
Fixes #19342
Fixes #19492
Fixes #18479

Expose more CosmosClient options

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/dotnet-ef/RootCommand.cs
src/ef/CommandLineUtils/CommandLineApplication.cs
src/ef/Commands/ProjectCommandBase.cs
src/ef/OperationExecutorBase.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx

Fixes #8332 
Re-enable errors if unexpected arguments are detected. Use `--` for command line to indicate arguments to be passed to the application. And `-Args` in Powershell for the same thing.

Further fix for 8332: Use -- for command line and -Args for Powershell

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs

Resolves #17326
This enables filtered include with skip to be translated for Sqlite

Query: Convert "APPLY" to "JOIN" with skip via RowNumber

---

src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs

Resolves #21296
Issue: `TaskAwaiter(new Task[] { PopulateSplitCollectionInclude(), PopulateSplitCollectionInclude() })` rather than creating task array and passing to method it also started executing them causing threading issue.
Fix: `TaskAwaiter(new Func<Task>[] { () => PopulateSplitCollectionInclude(), () => PopulateSplitCollectionInclude() })` creates the actual task only when we are ready to await them.

Query: Remove race condition in split query

---

src/EFCore/ChangeTracking/LocalView.cs
test/EFCore.Specification.Tests/DatabindingTestBase.cs

Start tracking entire graph when new entity added to LocalView

---

.github/dependabot.yml
src/EFCore.Cosmos/EFCore.Cosmos.csproj
src/EFCore.Cosmos/Extensions/CosmosDatabaseFacadeExtensions.cs
src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategy.cs
src/EFCore.Cosmos/Storage/Internal/HttpException.cs
src/EFCore.Cosmos/Storage/Internal/JsonCosmosSerializer.cs
src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs

Fixes #18753
Pending: Array parameters aren't working correctly and Newtonsoft.Json shouldn't be used in the provider anymore https://github.com/dotnet/efcore/issues/14570

Upgrade to Cosmos SDK V4

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs

This change makes Collection projection path for single query to use AddJoin method which does conversion.
Now filtered include with Skip/Take works on Sqlite for single query scenario also.
Resolves #20608

Query: Convert Apply to Join for collection projection

---

src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs

Very small part of #10508 
Elsewhere in the code we keep the order of the parameter definitions in the XML comments the same as the order of the parameters. This is some very small updates to fix that for the `CollectionCollectionBuilder` classes.

Correcting order of param definitions

---

src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs

Fixes #7283
See also https://github.com/dotnet/efcore/issues/21327

Avoid 10 second timeout when doing existence checks with SqlClient

---

test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs

[SMALL] Adding regression tests for #12826 - Query: Incorrect syntax near the keyword 'AS` for group by aggregate

---

test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/TestUtilities/ExpectedFilteredInclude.cs
test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs

ExpectedFilteredInclude now detects whether filter contains ordering. Based on that information we either perform default ordering or leave the exisiting order as is.

[SMALL] Add capability to verify order in ordered filtered include queries

---

src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindStringIncludeQueryTestBase.cs

Query: Clean up query validation for various negative cases

---

src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalCollectionShaperExpression.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSplitCollectionShaperExpression.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/EFCore/Extensions/NavigationExtensions.cs
src/EFCore/Infrastructure/NavigationBaseExtensions.cs
src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/CollectionShaperExpression.cs
src/EFCore/Query/IncludeExpression.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
src/EFCore/Query/MaterializeCollectionNavigationExpression.cs
src/EFCore/Query/QueryContext.cs
test/EFCore.Relational.Specification.Tests/Query/ManyToManyQueryRelationalTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyQuerySqliteTest.cs

Query: Expand/Include skip navigations in query
Part of #19003
- Expand skip navigations over
- A 1<=>1 Join 1<=>1 B
- A 1<=>* Join *<=>1 B
- A 1<=>* Join 1<=>* B
- Change EntityReference to remember existing expansions based on FK & direction rather than INavigation since skipNavigation may not have intermediate navigations which should get de-dupe if navigation to join entity is expanded
- Include skip navigations
- While searching for string based include
- While adding eager loaded navigations
- Cosmos - SkipNavigations are not embedded so processing them is same as non-embedded navigations
- Change MaterializeCollectionNavigationExpression/IncludeTreeNode to accept INavigationBase to accomodate skip navigations
- Downstream changes to flow INavigationBase to …

I need a crystal ball

---

src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs

Use object syntax for aliased projections

---

src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Migrations/Design/CSharpSnapshotGeneratorDependencies.cs
src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
src/EFCore.Design/Migrations/Design/MigrationsCodeGeneratorDependencies.cs
src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
src/EFCore.Relational/Design/AnnotationCodeGeneratorDependencies.cs
src/EFCore.Relational/Design/AttributeCodeFragment.cs
src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
src/EFCore/ChangeTracking/ChangeTracker.cs
src/EFCore/ChangeTracking/CollectionEntry.cs
src/EFCore/ChangeTracking/EntityEntry.cs
src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
src/EFCore/ChangeTracking/ReferenceEntry.cs
src/EFCore/Metadata/Conventions/ChangeTrackingStrategyConvention.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
src/EFCore/Update/Internal/UpdateAdapter.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs

* IAnnotationCodeGenerator now exposes an API to generate all fluent API calls, not one-by-one as before. This allows generating multiple annotations as a single fluent API call. 
* Use this in SQL Server to properly generate a fluent API for identity (increment/seed) and HiLo.
* The AnnotationCodeGenerator base class exposes the same one-by-one API as before, so this is totally backwards compatible (unless the interface is implemented directly).
* Use IAnnotationCodeGenerator when generating the model snapshot, to have proper fluent API calls instead of raw annotations. This also DRYs lots of logic between CSharpSnapshotGenerator and CSharpDbContextGenerator.
* IAnnotationCodeGenerator centralizes ignoring annotations that shouldn't be generated in code (also DRY between …

Refactor annotation code generation

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/EFCore/Extensions/Internal/ExpressionExtensions.cs
src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
test/EFCore.Specification.Tests/FieldMappingTestBase.cs
test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
test/EFCore.Specification.Tests/TestModels/Northwind/Employee.cs
test/EFCore.Specification.Tests/TestModels/Northwind/Order.cs
test/EFCore.Specification.Tests/TestModels/Northwind/OrderDetail.cs
test/EFCore.Specification.Tests/TestModels/Northwind/Product.cs
test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs

Fixes #15182
This allows a null backing field to be used for a non-nullable property while at the same time checking the backing field for null in order to determine if a property value has been set.

Use nullable backing field to check for default value

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs

Fixup to #21329
Note that since there's no ModelBuilder API for setting the version (and there probably shouldn't be), this is the one place where the snapshot generator accesses the (internal) annotation directly, at least for now.

Generate ProductVersion in model snapshot again

---

src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs

Resolves #21338
Also Clean up execution strategy in QueryingEnumerables
Resolves #21211

Query: Fix ordering for filtered include in single query scenario

---

test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs

Query: Update SQL assertions

---

test/EFCore.Relational.Specification.Tests/Query/OwnedQueryRelationalTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs

Query: Add tests for Owned collections and AsSplitQuery

---

src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs

Store the entity types mapped to views in the snapshot
Fixes #2725

Allow to exclude a table from migrations

---

src/EFCore.Abstractions/DbFunctionAttribute.cs
src/EFCore.Relational/Metadata/Builders/DbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Builders/IConventionDbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Conventions/RelationalDbFunctionAttributeConvention.cs
src/EFCore.Relational/Metadata/IConventionDbFunction.cs
src/EFCore.Relational/Metadata/IDbFunction.cs
src/EFCore.Relational/Metadata/IMutableDbFunction.cs
src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore.Relational/Metadata/Internal/InternalDbFunctionBuilder.cs
src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerDbFunctionConvention.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs

Resolves #17268
- Introduces new API `IsBuiltIn` on DbFunctionBuilder which marks the function as built-in and we translate it accordingly.
- Add `DbFunctionAttribute.IsBuiltIn` and convention to set the flag appropriately.

Query: Make it easy to map built-in functions

---

src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
test/EFCore.Cosmos.Tests/Infrastructure/CosmosModelValidatorTest.cs

Cosmos: Allow PK with just the partition key and using id as the partition key

---

src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs
src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalQueryMetadataExtractingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalCompiledQueryCacheKeyGenerator.cs
src/EFCore.Relational/Query/RelationalQueryCompilationContext.cs
src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
src/EFCore.Relational/Query/RelationalQueryTranslationPreprocessor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Relational/QuerySplittingBehavior.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

- Add enum QuerySplittingBehavior
- Add RelationalDbContextOptionsBuilder.UseQuerySplittingBehavior
- Add AsSingleQuery
Resolves #21355

Query: Introduce context level configuration for split query

---

src/EFCore.Relational/Diagnostics/RelationalEventId.cs
src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryCompilationContext.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerDbContextOptionsBuilderExtensions.cs
test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestStore.cs

Query: Generate a warning for multiple collection Includes

---

src/EFCore/DbContext.cs
src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/Internal/DbContextLease.cs
src/EFCore/Internal/DbContextPool.cs
src/EFCore/Internal/IDbContextPool`.cs
src/EFCore/Internal/IDbContextPoolable.cs
src/EFCore/Internal/IScopedDbContextLease.cs
src/EFCore/Internal/PooledDbContextFactory.cs
src/EFCore/Internal/ScopedDbContextLease.cs
test/EFCore.Specification.Tests/SharedStoreFixtureBase.cs
test/EFCore.Specification.Tests/TestUtilities/PoolableDbContext.cs
test/EFCore.Specification.Tests/TestUtilities/ServiceCollectionExtensions.cs
test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
test/EFCore.Tests/DbContextFactoryTest.cs

Fixes #21247
Refactors the context pooling code to create a cleaner responsibility of services.
Has the same restrictions as regular pooling since the context instances are reused.

Allow DbContextFactory to use a pool

---

src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Query: Dispose inner data readers for split query

---

src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs

Query: Bind projection member in client eval

---

src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerQueryCompilationContext.cs
src/EFCore.SqlServer/Query/Internal/SqlServerQueryCompilationContextFactory.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerConnection.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Query: Auto-buffer data readers in SqlServer when split query & MARS off

---

src/EFCore.Relational/Query/QuerySqlGenerator.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs

This pull request resolves Issue #13919: Translation error using negative.
If a LINQ query references an entity property and uses a negated expression, negation only applies to the first term in the expression.
Example: 
`db.Entities.Where(e => e.Num1 == -(e.Num2 + 100))`
Expected translation: 
`SELECT ... FROM Entities e WHERE e.Num1 = -(e.Num2 + 100)`
Actual translation: 
`SELECT ... FROM Entities e WHERE e.Num1 = -e.Num2 + 100`
---
- On translation, add opening and closing parentheses around expression if expression type is `ExpressionType.Negate`
- Add unit test for SQL Server and SQLite providers
---
- Are these tests placed in the right place? I couldn't find a set of unit tests for unary expressions.

Fix Issue 13919: Translation error using negative

---

src/EFCore/DbContext.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.Tests/DbContextTest.cs

Public method FromExpression on DbContext to tie up our query provider with the expression
Resolves #9810

Query: Self-bootstrapping functions returning IQueryable

---

src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs

Query: Allow ToList on non queryables

---

src/EFCore.Relational/Metadata/Internal/StoreFunction.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs

Query: Use function mapping when querying for DbSet

---

build.cmd
restore.cmd
test.cmd

Case Sensitive: eng/common/build.ps1 is with lower case 'b' and not upper case

Case Sensitive: eng/common/build.ps1 is with lower case 'b' and not upper case

---

src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
src/EFCore/Metadata/Builders/IConventionForeignKeyBuilder.cs
src/EFCore/Metadata/Builders/IConventionNavigationBuilder.cs
src/EFCore/Metadata/Builders/IConventionSkipNavigationBuilder.cs
src/EFCore/Metadata/Builders/NavigationBuilder.cs
src/EFCore/Metadata/Conventions/NavigationEagerLoadingConvention.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs
src/EFCore/Metadata/Internal/InternalPropertyBaseBuilder`.cs
src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
src/EFCore/Metadata/Internal/SkipNavigation.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
src/EFCore/Query/QueryCompilationContext.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/EFCore.Tests/Metadata/Internal/InternalNavigationBuilderTest.cs
test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs

IsEagerLoaded API on NavigationBuilder to mark a navigation as eagar loaded
IgnoreEagerLoadedNavigations API on query to ignore model based config
Resolves #21540

Model level eager loading configuration

---

test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalFixture.cs
test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs

Query: Add TPT variant for GearsOfWarQueryTests

---

test/EFCore.Relational.Specification.Tests/Query/TPTManyToManyNoTrackingQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/TPTManyToManyQueryRelationalFixture.cs
test/EFCore.Relational.Specification.Tests/Query/TPTManyToManyQueryRelationalTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyQuerySqliteFixture.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs

This also cover some split queries
Part of #21510

Query: Add TPT variation for ManyToMany tests

---

src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/EFCore.Relational/Migrations/Operations/AddCheckConstraintOperation.cs
src/EFCore.Relational/Migrations/Operations/AddColumnOperation.cs
src/EFCore.Relational/Migrations/Operations/AlterColumnOperation.cs
src/EFCore.Relational/Migrations/Operations/AlterDatabaseOperation.cs
src/EFCore.Relational/Migrations/Operations/AlterSequenceOperation.cs
src/EFCore.Relational/Migrations/Operations/AlterTableOperation.cs
src/EFCore.Relational/Migrations/Operations/Builders/CreateTableBuilder.cs
src/EFCore.Relational/Migrations/Operations/ColumnOperation.cs
src/EFCore.Relational/Migrations/Operations/CreateIndexOperation.cs
src/EFCore.Relational/Migrations/Operations/CreateTableOperation.cs
src/EFCore.Relational/Migrations/Operations/DatabaseOperation.cs
src/EFCore.Relational/Migrations/Operations/SequenceOperation.cs
src/EFCore.Relational/Migrations/Operations/TableOperation.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs

I found a few things I didn't like while working on table rebuilds...

Clean up Migrations

---

test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindCompiledQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs

Makes `AssertSql()` assert that no SQL was generated (used to no-op)

Test: Assert all the SQL

---

test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #14028
Resolves #18346

[SMALL] Adding some regression tests for issues that have been fixed previously

---

src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/EFCore.Relational/Update/Internal/IKeyValueIndexFactory.cs
src/EFCore.Relational/Update/Internal/KeyValueIndex.cs
src/EFCore/ChangeTracking/Internal/IdentityMap.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToManyAk.cs

Don't use entry sharing for entities with the same AK values
Only remove the entry with duplicate key value from the identity map if it's still there
Fixes #20870

Include key values in the update topological sort

---

eng/Version.Details.xml

It is not critically important that these match in exact version to those that are being shipped to NuGet.
They are primarily for verification. During previews, the subscription edge will remain, but once we get to 5.0.0
the edge can be changed to only update on demand.
This ensures that efcore does not end up on the critical path for the build.
EFCore's build is fairly long (though it is currently running tests).

Recategorize the runtime dependencies

---

src/EFCore.Design/Design/DbContextActivator.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Migrations/Operations/Builders/CreateTableBuilder.cs

Part of #20409 
Rename parameter to `args`.
Make `CreateTableBuilder` use `PropertyInfo` instead of `MemberInfo`.

API Review Updates

---

test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs

Add regression tests for issue#10012

---

src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs
test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs

Remove hacky mappings for SQL types that only work on .NET Framework

---

src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs

The overload of UsingEntity() which configures the association entity type was returning the wrong side of the association.

UsingEntity was returning the wrong side of the association.

---

src/EFCore.Relational/Query/Internal/CollectionJoinApplyingExpressionVisitor.cs
src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryTranslationPostprocessor.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryTranslationPostprocessorFactory.cs
test/EFCore.InMemory.FunctionalTests/Query/ManyToManyQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/ManyToManyNoTrackingQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindIncludeQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSplitIncludeQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindStringIncludeQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyQuerySqliteTest.cs

Adding logic that checks for APPLY and throws meaningful exception
Fixes #19178

Fix to #19178 - Invalid SQL with CROSS APPLY generated on SQLite

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs

Fix to #20180 - Query: Apply null semantics processing to QueryableFunctionExpression

---

src/ef/Commands/ProjectCommandBase.cs
src/ef/ef.csproj

Fixes #19760
@ajcvickers Should we `Servicing-consider` this?
For EF Core 2.x projects, we use `AppDomainSetup.ConfigurationFile` to specify which *.config file to use at design time.
In EF Core 3.0, we removed support for .NET Framework and simplified some design-time hooks since we no longer needed to support our AppDomain strategy for invoking user code.
In EF Core 3.1, we re-added support for .NET Framework but not our AppDomain strategy. Instead, we use a Reflection strategy to invoke user code. There is no API for specifying the *.config file without creating a new AppDomain. (see https://github.com/dotnet/runtime/issues/931)
APIs used to read the connection string from the *.config file (like `ConfigurationManager`) stopped working at design-time after upgrading to EF Core 3.1. For …

[release/3.1] Tools: Fix up App.config path on .NET Framework

---

azure-pipelines.yml

After https://github.com/dotnet/efcore/pull/21605 now it is crossing an hour mark and fails to complete.

Increase timeout for windows build

---

test/EFCore.Specification.Tests/Query/ManyToManyQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs

Fix non-deterministic test issue in ManyToManyQueryTestBase

---

eng/Versions.props

Issue #20316
We brought this issue originally in March, at which time we decided to hold off on updating the dependency to gather more data that this is a safe update to make. The 1.1.3 patch has now been out a couple of months and is proving stable. We talked to the SqlClient folks again and they agreed that it is now time to make this change.
SqlClient fixed a deadlock issue in their 3.1.1 patch. EF Core customers are hitting this, so we want to update our dependency to that version version.
Several customers have hit the deadlock issue. They can fix the issue themselves by updating their SqlClient package, but this can be hard to discover as is often the case with deadlock issues.
SqlClient have tested and released the patch. We have run all EF Core …

[3.1] Updating Microsoft.Data.SqlClient to 1.1.3

---

src/EFCore/DbContext.cs
src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
src/EFCore/Extensions/ModelExtensions.cs
src/EFCore/Extensions/MutableModelExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Internal/EntityFinder.cs
src/EFCore/Internal/InternalDbSet.cs
src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
src/EFCore/Metadata/IConventionModel.cs
src/EFCore/Metadata/IModel.cs
src/EFCore/Metadata/IMutableModel.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.Tests/DbContextTest.cs
test/EFCore.Tests/Metadata/Internal/ModelTest.cs

- Make FindEntityType(Type) return null for shared type entity type
- Add IModel.IsShared(Type) API
- Flow IEntityType info in places when availble rather than doing Type based loopup
Part of #9914

Use FindEntityType(Type) as appropriate

---

src/EFCore.Design/Design/Internal/CSharpHelper.cs
src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
src/EFCore.Relational/Extensions/RelationalPropertyBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs

Note, we can't get their actual SQL without parsing the entire CREATE TABLE statement, so we just generate HasComputedColumnSql without any arguments to at least make them usable.
Fixes #21557

SQLite RevEng: Include computed columns

---

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
test/EFCore.InMemory.FunctionalTests/ManyToManyTrackingInMemoryTest.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/SharedTypes.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/ManyToManyTrackingSqliteTest.cs

Part of #19003
Mostly tests, but also fixes to navigation fixup to/from join entities

Additional testing for many-to-many change tracking

---

test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs

Resolves #21527
Root cause: When generating outer identifier for OrderDetails include, it missed OrderId and had only CustomerID which made all outer result pairs of (customer, order) to be same as long as same customerID which was not true.
The code has been fixed in one of the earlier changes so now we correctly identify results

Add a regression test for #21527

---

src/EFCore/Diagnostics/CoreEventId.cs
src/EFCore/Diagnostics/CoreLoggerExtensions.cs
src/EFCore/Diagnostics/LoggingDefinitions.cs
src/EFCore/Infrastructure/CoreOptionsExtension.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
src/EFCore/Metadata/Conventions/RequiredNavigationAttributeConvention.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs

Log an error for Required on principal to dependent

---

src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs

Set max batch size for SQL Server

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs

Don't ask how! :cry:

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

This PR fixes an issue where seeded values that contain a property that is set to `ValueGeneratedOnAdd` get reseeded in every new migration, even though none of the values changed.
Fixes https://github.com/dotnet/efcore/issues/21661

Fix issue where property with `ValueGeneratedOnAdd` is reseeded in every migration

---

src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs

Metadata: Throw error for shared type in inheritance

---

src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindKeylessEntitiesQueryRelationalTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs

Disabling the scenario when we try to add collection join to keyless entity parent, since we don't have identifying columns to properly bucket the results.
Fixes #21607

[SMALL] Fix to #21607 - Incorrect results returned when joining a key-less view to an entity

---

src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
test/EFCore.Relational.Tests/Design/AnnotationCodeGeneratorTest.cs

Fixes #21470
Note: this excludes from scaffolding only, we still always include this in the snapshot.

Stop scaffolding IsTableExcludedFromMigrations

---

src/EFCore.Cosmos/Query/Internal/EqualsTranslator.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/EqualsTranslator.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore/Internal/EntityFinder.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs

And associated changes to support translation.
Resolves #19407

Query: Key comparison should use object.Equals internally in query

---

src/EFCore/Extensions/ConventionModelExtensions.cs
src/EFCore/Extensions/MutableModelExtensions.cs
src/EFCore/Metadata/Internal/Model.cs
test/EFCore.Tests/ApiConsistencyTest.cs

Return void from AddShared and AddOwned

---

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/IConventionSkipNavigation.cs
src/EFCore/Metadata/IMutableSkipNavigation.cs
src/EFCore/Metadata/ISkipNavigation.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalModelBuilder.cs
src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
src/EFCore/Metadata/Internal/SkipNavigation.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
test/EFCore.Tests/Metadata/Conventions/ManyToManyAssociationEntityTypeConventionTest.cs
test/EFCore.Tests/Metadata/Conventions/RelationshipDiscoveryConventionTest.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
test/EFCore.Tests/Metadata/Internal/SkipNavigationTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs

Henceforth Associations are Joins

---

src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/EFCore.Relational/Storage/Internal/TypeMappedPropertyRelationalParameter.cs
src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs
src/EFCore.Relational/Storage/RelationalTypeMapping.cs
src/EFCore.Relational/Storage/TypeMaterializationInfo.cs
src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
src/EFCore.Relational/Update/ColumnModification.cs
src/EFCore.Relational/Update/ModificationCommand.cs
src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
src/EFCore.Relational/Update/UpdateSqlGenerator.cs
test/EFCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs
test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
test/EFCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs

Configure command parameters as nullable for optional dependents in table splitting

---

azure-pipelines.yml
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs

Changes:
- Synthesize DEFAULT value when column altered to NOT NULL (fixes #19882)
- SQL Server: Rebuild indexes when column collation is altered (fixes #21547)

Migrations: Fix some bugs

---

src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Query: Rewrite entity equality for dependents sharing table

---

src/EFCore.Relational/Query/EntityProjectionExpression.cs
src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTRelationshipsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs

Query: Change TPT to use string discriminator column

---

src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Query: Allow entity equality to work on client converted entity

---

src/EFCore.Abstractions/DbFunctionAttribute.cs
src/EFCore.Relational/Metadata/Builders/DbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Builders/DbFunctionBuilderBase.cs
src/EFCore.Relational/Metadata/Builders/DbFunctionParameterBuilder.cs
src/EFCore.Relational/Metadata/Builders/IConventionDbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Conventions/RelationalDbFunctionAttributeConvention.cs
src/EFCore.Relational/Metadata/IConventionDbFunction.cs
src/EFCore.Relational/Metadata/IDbFunction.cs
src/EFCore.Relational/Metadata/IDbFunctionParameter.cs
src/EFCore.Relational/Metadata/IMutableDbFunction.cs
src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore.Relational/Metadata/Internal/DbFunctionParameter.cs
src/EFCore.Relational/Metadata/Internal/InternalDbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Internal/InternalDbFunctionParameterBuilder.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs

Added fluent API for function to specify it's nullability and function parameter to specify whether it propagates null. Also added property to DbFunction attribute to allow specify nullability there.
Fixes #19609

Fix to #19609 - Query: allow user functions to be annotated with nullability propagation information

---

src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
src/EFCore/Extensions/MutableEntityTypeExtensions.cs
src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/ForeignKey.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
src/EFCore/Metadata/Internal/InternalModelBuilder.cs
src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
src/EFCore/Metadata/Internal/Model.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Tests/Metadata/Conventions/ManyToManyAssociationEntityTypeConventionTest.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Remove implicit join entity type in a convention
Configure PK for join entity type in a convention
Consolidate `HasNoSkipNavigation` usage
Fixes #21567

Use default property names for join entity type

---

src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
src/EFCore.Relational/Storage/Internal/TypeMappedRelationalParameter.cs
src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Conventions/ManyToManyAssociationEntityTypeConvention.cs
src/EFCore/Metadata/ITypeBase.cs
src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
src/EFCore/Metadata/Internal/PropertyBase.cs
src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
src/EFCore/Metadata/Internal/TypeBase.cs
src/Shared/SharedTypeExtensions.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
test/EFCore.Tests/ApiConsistencyTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Allow indexer properties to be used without first initializing them
Fixes #21718
Fixes #21720

Make property bag entity types use an indexer prop rather than a shadow prop

---

NuGet.config
build/sources.props

As part of [moving to Azure Artifacts from MyGet](https://github.com/dotnet/arcade/blob/master/Documentation/MigrationPlan/MyGetFeeds.md), point all MyGet feed sources to new Azure Artifacts feed.
@dougbu FYI, from email.

Use Azure Artifacts instead of MyGet

---

src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Tests/Metadata/Conventions/RelationshipDiscoveryConventionTest.cs

Discover self-referencing many-to-many relationships

---

src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Metadata/Internal/ClrCollectionAccessor.cs
test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
test/EFCore.Specification.Tests/TestModels/UpdatesModel/Category.cs
test/EFCore.Specification.Tests/TestModels/UpdatesModel/Product.cs
test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductBase.cs
test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductCategory.cs
test/EFCore.Specification.Tests/TestModels/UpdatesModel/ProductWithBytes.cs
test/EFCore.Specification.Tests/UpdatesFixtureBase.cs
test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs

Use the correct shared foreign key for navigation fixup

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs

Make discriminator read-only by default

---

src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Query: Fix bug in FromSqlExpression.Equals

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.InMemory/Extensions/InMemoryEntityTypeBuilderExtensions.cs
src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
src/EFCore.Relational/Metadata/Builders/TableBuilder`.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs

Obsolete `CoreAnnotationNames.DefiningQuery`
Part of #20409

Add a nested lambda to ToTable

---

src/EFCore.InMemory/Extensions/InMemoryEntityTypeBuilderExtensions.cs
src/EFCore.InMemory/Extensions/InMemoryEntityTypeExtensions.cs
src/EFCore.InMemory/Internal/InMemoryModelValidator.cs
src/EFCore.InMemory/Metadata/Conventions/DefiningQueryRewritingConvention.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
src/EFCore.Relational/Metadata/SqlQueryExtensions.cs
src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Extensions/MutableEntityTypeExtensions.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Conventions/QueryFilterRewritingConvention.cs
test/EFCore.InMemory.FunctionalTests/Query/InheritanceQueryInMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindInMemoryContext.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/WithConstructorsInMemoryTest.cs
test/EFCore.InMemory.Tests/Infrastructure/InMemoryModelValidatorTest.cs
test/EFCore.Relational.Specification.Tests/Query/InheritanceQueryRelationalFixture.cs
test/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/WithConstructorsSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/WithConstructorsSqliteTest.cs

Rename InMemoryEntityTypeBuilderExtensions.ToQuery to ToInMemoryQuery
Rename ToQuerySql to ToSqlQuery
Part of #20409

Rename defining query APIs

---

src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/SkipNavigation.cs

Add IConventionEntityTypeBuilder.HasSkipNavigation that takes an inverse

---

src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityOne.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityThree.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ImplicitManyToManyA.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ImplicitManyToManyB.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/SharedTypes.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

- Add DefaultPropertyBagType in shared type by convention
- Throw exception message for nonconfigured navigation pointing to shared type
- Skip Shared type navigation when searching for FKAttribute on property

Metadata: Fix few Shared Type entity type bugs

---

src/EFCore/DbContext.cs
src/EFCore/Diagnostics/CoreLoggerExtensions.cs
src/EFCore/SaveChangesEventArgs.cs
src/EFCore/SaveChangesFailedEventArgs.cs
src/EFCore/SavedChangesEventArgs.cs
src/EFCore/SavingChangesEventArgs.cs
test/EFCore.InMemory.FunctionalTests/InterceptionInMemoryTest.cs
test/EFCore.Specification.Tests/SaveChangesInterceptionTestBase.cs
test/EFCore.Tests/DbContextTest.cs

Fixes #15910
I realized that the interceptor, while powerful, is hard to attach to without changing the context configuration. Therefore, this PR adds simple .NET events that can easily be attached to from outside the code that defines the context.
Also, fix to call the SaveChanges failed interceptor when the failure is an optimistic concurrency exception.

Add SaveChanges events

---

src/EFCore/Infrastructure/ModelValidator.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

We were not checking collection navigations which are initialized inline and without setter.
This worked fine for most part as
- One sided collection were always added by convention
- When there were multiple pairs and convention failed, opposite side had reference navigation which would end up throwing
- Many to Many brings a twist that there is no reference on other side so in case we fail to add many to many skip navigations by convention, we would not throw.

ModelValidator: Throw for unmapped initialized collection navigation

---

test/EFCore.SqlServer.FunctionalTests/SaveChangesInterceptionSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs

Run two SaveChanges interception suites against different databases

---

src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Relational/Storage/RelationalTransaction.cs
src/EFCore.Relational/Update/Internal/BatchExecutor.cs
src/EFCore/Infrastructure/DatabaseFacade.cs
src/EFCore/Storage/IDbContextTransaction.cs
src/EFCore/Storage/IDbContextTransactionManager.cs
test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs
test/EFCore.Tests/DatabaseFacadeTest.cs

Aligning with the System.Data savepoints API: https://github.com/dotnet/runtime/issues/33397#issuecomment-662004505
Part of #20409 (May 20)

Rename AreSavepointsSupported to SupportsSavepoints

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Migrations/Operations/AddCheckConstraintOperation.cs
src/EFCore.Relational/Migrations/Operations/AddForeignKeyOperation.cs
src/EFCore.Relational/Migrations/Operations/AddPrimaryKeyOperation.cs
src/EFCore.Relational/Migrations/Operations/AddUniqueConstraintOperation.cs
src/EFCore.Relational/Migrations/Operations/CreateIndexOperation.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs

Rename MigrationOperation.For methods to CreateFrom

---

src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs

Resolves #21816
Also added regression tests for other property attributes

RevEng: Scaffold MaxLength attribute when using data annotations

---

test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs

Fix FreeText tests

---

src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/QuerySqlGenerator.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Query/SqlExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/DistinctSqlExpression.cs
src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs

Query: Translate Distinct operator over group element before aggregate

---

src/EFCore.Relational/Query/SqlExpressions/SqlFragmentExpression.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs

Query: Identify Count(*) in different SelectExpression differently

---

src/EFCore.Relational/Query/SqlExpressions/CaseExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs

Query: Fix bug in CaseExpression.VisitChildren

---

src/EFCore.Design/Design/Internal/MigrationsOperations.cs
src/EFCore.Design/Design/OperationExecutor.cs
src/EFCore.Relational/Migrations/IMigrationsSqlGenerator.cs
src/EFCore.Relational/Migrations/IMigrator.cs
src/EFCore.Relational/Migrations/Internal/Migrator.cs
src/EFCore.Relational/Migrations/MigrationsSqlGenerationOptions.cs
src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
test/EFCore.Relational.Specification.Tests/MigrationsInfrastructureTestBase.cs
test/EFCore.Relational.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs

Also adds the ability for providers to detected whether a script is being generated and whether its idempotent. (resolves #14746)
Fixes #12911

SqlServer Migrations: Add EXEC calls to idempotent script

---

src/EFCore/Metadata/Internal/ConstructorBindingFactory.cs
test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
test/EFCore.Specification.Tests/WithConstructorsTestBase.cs

EFCore now skips constructors generated with c#9 that contain parameters with no names.  
The nameless constructor parameters were throwing null reference exceptions when
EFCore was trying to modify the strings to the various conventions for matching
properties like pascal-case, camel-case, m_, etc.

Fix issue https://github.com/dotnet/efcore/issues/21844

---

src/EFCore/Internal/InternalDbSet.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Tests/DbSetTest.cs

Resolves #19979
Also verify return type of DbSet with CLR type of EntityType
Resolves #21937

Add end to end test for shared type entity type

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
src/EFCore.Relational/Metadata/Builders/TableBuilder`.cs
src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs

API Review fallout

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Storage/ParameterNameGenerator.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs

Make required dependent columns in shared table non-nullable.

---

src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/IForeignKeyAddedConvention.cs
src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/ManyToManyJoinEntityTypeConvention.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingSqlServerTestBase.cs
test/EFCore.Tests/Metadata/Conventions/ManyToManyJoinEntityTypeConventionTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Make join entity type name deterministic
Use skip navigation name for the implicit FK name
Fixes #21858
Fixes #21870
Fixes #21915

Configure OnDelete for join entity types on SQL Server

---

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs

Adds `BeginTransaction(bool deferred)` to `SqliteConnection`.
Fixes #20786

Microsoft.Data.Sqlite: Add deferred transactions

---

src/EFCore/Extensions/EntityTypeExtensions.cs

Metadata: Add CLR type for shared type entity type in debug view

---

src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
src/EFCore/ChangeTracking/EntityEntryGraphNode`.cs
src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs
src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxySqlServerTest.cs

This fixes a case where attaching one side of a many-to-many would require DetectChanges for enties on the other side to be tracked.

Fix to check skip navigations in when attaching a graph

---

src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
src/EFCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/NavigationBuilder`.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
test/EFCore.Tests/ApiConsistencyTest.cs
test/EFCore.Tests/ApiConsistencyTestBase.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs

Add API consistency test to ensure generic Fluent API classes hide inherited non-generic methods
Fixes #22012
Fixes #21942

Add NavigationBuilder<TSource, TTarget>

---

src/EFCore/ChangeTracking/CollectionEntry.cs
src/EFCore/ChangeTracking/EntityEntry.cs
src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
src/EFCore/ChangeTracking/NavigationEntry.cs
src/EFCore/ChangeTracking/ReferenceEntry.cs
src/EFCore/Internal/EntityFinder.cs
src/EFCore/Internal/IEntityFinder.cs
src/EFCore/Internal/IEntityFinder`.cs
src/EFCore/Metadata/Internal/PropertyBase.cs
src/EFCore/Update/UpdateEntryExtensions.cs
src/Shared/SharedTypeExtensions.cs
test/EFCore.Tests/ChangeTracking/SkipCollectionEntryTest.cs
test/EFCore.Tests/ChangeTracking/SkipMemberEntryTest.cs
test/EFCore.Tests/ChangeTracking/SkipNavigationEntryTest.cs

Part of #19003
New version of this that reads/manipulates the join table for IsModified.
Also:
* Fixed an issue with `HasDefaultValue` where we were comparing 0 to null for indexer properties
* When _attaching_ a many-to-many graph, existing join entities are created as Unchanged.

MemberEntry support for skip navigations

---

src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Metadata/Internal/TableBase.cs
src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs

- Also remove additional conditions in SelectExpression
Resolves #21807
Resolves #12100

Query: Materialize Required dependents always

---

src/EFCore/ChangeTracking/CollectionEntry.cs
src/EFCore/ChangeTracking/EntityEntry.cs
src/EFCore/ChangeTracking/NavigationEntry.cs
src/EFCore/ChangeTracking/ReferenceEntry.cs
src/EFCore/Extensions/Internal/ExpressionExtensions.cs
src/EFCore/Internal/EntityFinder.cs
src/EFCore/Internal/EntityFinderCollectionLoaderAdapter.cs
src/EFCore/Internal/ICollectionLoader.cs
src/EFCore/Internal/ICollectionLoader`.cs
src/EFCore/Internal/IEntityFinder.cs
src/EFCore/Internal/IEntityFinder`.cs
src/EFCore/Internal/ManyToManyLoader.cs
src/EFCore/Internal/ManyToManyLoaderFactory.cs
src/EFCore/Metadata/Internal/SkipNavigation.cs
test/EFCore.InMemory.FunctionalTests/ManyToManyLoadInMemoryTest.cs
test/EFCore.Specification.Tests/LoadTestBase.cs
test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/ManyToManyLoadProxySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/ManyToManyLoadSqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/ManyToManyLoadSqliteTestBase.cs

Explicit and lazy loading for many-to-many collections

---

src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Metadata/Conventions/EntityTypeHierarchyMappingConvention.cs
src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
src/EFCore/Diagnostics/CoreEventId.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs

Determine column names for TPT in the model instead of a convention.

---

src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs
src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/ScaffoldingTypeMapperSqliteTest.cs
test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs

* Removed `StoreTypeNameBaseUsesPrecision`
* Removed large GetMapping overload that was added in 5.0 but is never called
* Fixed issue when reverse engineering where different casing for type name was being ignored
Part of #20409

Type mapping fixes from API reviews

---

src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
src/EFCore.Relational/Infrastructure/RelationalPropertyExtensions.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalKeyExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

Target FKs to the derived table in TPT if possible

---

src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalSkipNavigationBuilder.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Remove referenced key when removing the FK from skip navigation

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore/Infrastructure/TypeExtensions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAsyncSimpleQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs

Blocks collections in the projection which are of type
- IQueryable<T>
- IOrderedQueryable<T>
- IOrderedEnumerable<T>
- DbSet<T>
Resolves #16314

Query: Disallow return types of queryables in projection

---

src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
src/EFCore/Metadata/Internal/TypeIdentity.cs
src/EFCore/Metadata/MemberIdentity.cs
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs

Implement IEquatable on TypeIdentity and MemberIdentity
Fixes #21838

Fix an OwnsOne overload not passing through the type.

---

src/EFCore.Relational/Metadata/StoreObjectIdentifier.cs
src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
src/EFCore.Relational/Query/RelationalCompiledQueryCacheKeyGenerator.cs
src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
src/EFCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs
src/EFCore/Query/CompiledQueryCacheKeyGenerator.cs
src/EFCore/Storage/ValueBuffer.cs
src/EFCore/ValueGeneration/ValueGeneratorCache.cs

No boxing for structs

---

src/EFCore.Relational/Update/ColumnModification.cs
src/EFCore.Relational/Update/ModificationCommand.cs
src/EFCore/ChangeTracking/Internal/OriginalValues.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
src/EFCore/Metadata/Builders/OwnedNavigationBuilder`.cs
test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryFixtureBase.cs

Use public types in OwnedNavigationBuilder constructor
Fixes #21465

Propagate original values for shared columns to added dependents in table splitting

---

src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalModelBuilder.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs

Properly remove incompatible entity types with the same name.

---

benchmark/EFCore.Benchmarks/EFCore.Benchmarks.csproj
eng/Versions.props
src/EFCore.Analyzers/AnalyzerReleases.Shipped.md
src/EFCore.Analyzers/EFCore.Analyzers.csproj
src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
test/EFCore.Analyzers.Tests/EFCore.Analyzers.Test.csproj
test/EFCore.Analyzers.Tests/InternalUsageDiagnosticAnalyzerTest.cs
test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
test/ef.Tests/ef.Tests.csproj

* Rewrite most of the analyzer using Operations, for much better perf and VB.NET support.
* Support some extra language scenarios which weren't being detected.
Fixes #19648
Fixes #20206

Redo pubternalyzer with Roslyn Operations

---

src/EFCore/ChangeTracking/Internal/StateManager.cs
test/EFCore.Tests/DbContextTrackingTest.cs

Use local DetectChanges when cascade-deleting

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs

Manually verified
- Works for Relational
- No-op for InMemory
- Throws translation failure for Cosmos
Resolves #22034

InMemory: No-op for AsSplitQuery operator

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs

Manually verified
- Works for Relational
- No-op for InMemory
- Throws translation failure for Cosmos
Resolves #22034
Cherry-pick because branching did not take my PR changes.

InMemory: No-op for AsSplitQuery operator (#22098)

---

src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs

We currently don't calculate nullability for generic properties, since that's a complex task (https://github.com/dotnet/runtime/issues/29723 is supposed to add this capability to the reflection API at some point). This interferes with the ability to use Dictionary for property bag, since it's a generic type and its indexer is incorrectly identified as non-nullable (the actual nullability of the generic type argument isn't taken into account).
The general inability to handle generic properties hasn't proved problematic - it's been this way since EF Core 3.0 and we've received no user complaints. This is a specific fix to recognize the indexer on Dictionary and not identify it as non-nullable. If this is OK to merge, I'll document the general limitation in our doc page on nullability, and …

Don't identify dictionary indexer as NRT

---

eng/Version.Details.xml

- aligns with dotnet/core-setup#9066 and dotnet/extensions#3417
- unpin System.IO.Pipelines and System.Runtime.CompilerServices.Unsafe Versions
- see dotnet/aspnetcore#24937
- move System.IO.Pipelines version to latest

[release/3.1] Add dependencies for CPD strict in aspnetcore

---

src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

**Query: New set of conditions to materialize optional dependents**
Let A be the set of properties which are not sharing column with any principal.
B be the subset of A where property is required.
C be subset of A where property is optional. (hence A = B + C)
The necessary condition for materialization without anything else be C1 - all required properties (excluding PK) must have a value (with or without sharing).
- If A is empty, then C1 will be sufficient condition as it will be required dependent.
- If B is non-empty, then C1 will cover those properties and be sufficient condition.
- If B is empty and then C is non-empty, then materialize if there is at least 1 non-null value in C along with C1 being true.
- Otherwise null.
If there are no required properties other than PK (essentially …

Schrödinger's Cat

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

This enables queries like `Get-Migration | where applied`. Other places were working by coincidence using special properties that PowerShell adds to collection objects.

PMC Tools: Work around PowerShell/PowerShell#3424

---

src/EFCore.Relational/Metadata/Conventions/EntityTypeHierarchyMappingConvention.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs
src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/EFCore.Relational/Update/ModificationCommand.cs
src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Extensions/ForeignKeyExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/ValueGenerationConvention.cs
src/EFCore/Metadata/Internal/ForeignKeyExtensions.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
test/EFCore.Tests/Metadata/Conventions/ValueGeneratorConventionTest.cs
test/EFCore.Tests/Metadata/Internal/ForeignKeyTest.cs

Only added if there isn't an equivalent FK already in the model
The new FKs are used to sort the TPT update commands instead of the ad-hoc solution
Fix recursive issues exposed by the new FKs
Fixes #21943

Add FK constraints between TPT tables

---

src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Design.Tests/TestUtilities/DatabaseColumnRef.cs
test/EFCore.Design.Tests/TestUtilities/DatabaseTableRef.cs
test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs

RevEng: Use pluralizer with database names too

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs

SqlServer RevEng: Handle included index columns

---

src/EFCore.Abstractions/ChangeTracking/Internal/SortableBindingList.cs
src/EFCore.Abstractions/ChangeTracking/ObservableCollectionListSource.cs
src/EFCore.Abstractions/DbFunctionAttribute.cs
src/EFCore.Abstractions/IndexAttribute.cs
src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
src/EFCore.Proxies/Proxies/Internal/LazyLoadingInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangedInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangingInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetPlugin.cs
src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
src/EFCore.Proxies/Proxies/Internal/ProxyChangeTrackingConvention.cs
src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
src/EFCore.Proxies/ProxiesExtensions.cs
src/Shared/Check.cs

Code cleanup for miscellaneous packages

---

src/EFCore/Extensions/PropertyExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
src/EFCore/Metadata/IConventionProperty.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
test/EFCore.Tests/ChangeTracking/SkipCollectionEntryTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Unify base FK property name logic
Unify implicit property logic
Fixes #22128

Re-run fk discovery convention when skip navigation changes

---

src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
test/EFCore.Specification.Tests/SerializationTestBase.cs
test/EFCore.Specification.Tests/WithConstructorsTestBase.cs
test/EFCore.Tests/Storage/PhysicalAddressToBytesConverterTest.cs
test/EFCore.Tests/Storage/PhysicalAddressToStringConverterTest.cs

Be consistent about ifdefs for .NET 5

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs

Query: InMemory: Preserve value buffer indexes when adding navigation to weak type
Resolves #20729
The issue here was, when adding navigation to weak type, we generate GJ-DIE-SM pattern in which we push current projection to outer element. During the process we updated value buffer indexes for entity projections, some of them were being nested entity projection for weak types. This indexes differed from what it was earlier when the earlier navigation was expanded and put into the tree. Giving us incorrect expression to translate in projection.
Fix is to maintain original indexes and add a dummy one if needed.
For EntityProjections, each slot would represent reading 1 property value so we can just put the same value in same slot.
For non-entity projections, each slot can have complex …

Don't move my cheese!

---

src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs

Don't use PropertyInfo from unmapped base type

---

src/EFCore.Relational/Storage/DoubleTypeMapping.cs
src/EFCore.Relational/Storage/FloatTypeMapping.cs
src/EFCore/ChangeTracking/ArrayStructuralComparer.cs
src/EFCore/ChangeTracking/DoubleValueComparer.cs
src/EFCore/ChangeTracking/FloatValueComparer.cs
test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs

Handle NaN in value comparers for double/float

---

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs

SqlServer Migrations: Don't generate unnecessary ALTER TABLE

---

src/EFCore.Analyzers/EFCore.Analyzers.csproj
src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs

Remove VB support from analyzer

---

test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs

Resolves #17020
It is already fixed in some earlier commit

Query: Enable test for complex case of null removal

---

src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs

Note, --output-dir is still used (elsewhere) to determine the directory on the first migration.
Fixes #13342

Migrations: Don't let --output-dir override the existing snapshot dir

---

src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
test/EFCore.Relational.Tests/DbSetAsTableNameTest.cs
test/EFCore.SqlServer.Tests/DbSetAsTableNameSqlServerTest.cs
test/EFCore.Sqlite.Tests/DbSetAsTableNameSqliteTest.cs

Stop using DbSet property name for table name of shared type entity types

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs

Allow FK properties to remain temporary when state changes from Added

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Storage/RelationalDatabase.cs
src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Metadata/Builders/PropertyBuilder.cs
src/EFCore/Metadata/Builders/PropertyBuilder`.cs
src/EFCore/Metadata/Internal/PropertyExtensions.cs
src/EFCore/Metadata/ValueGenerated.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs

Add ValueGenerated.OnUpdateSometimes for shared columns

---

src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
src/EFCore.Relational/Storage/ReaderColumn.cs
src/EFCore.Relational/Storage/ReaderColumn`.cs
src/EFCore.Relational/Storage/RelationalCommand.cs
src/EFCore.Relational/Storage/RelationalCommandParameterObject.cs
test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
test/EFCore.Relational.Tests/Query/Internal/BufferedDataReaderTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #20364
Adds code for error handling when create buffered data reader.
Code needs to handle unexpected nulls and incorrect type of data encountered

Throw detailed exception message in buffered data reader

---

src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationAnnotationProviderTest.cs

Turns out SqlServer:Identity is also not first class. It is computed based on ValueGenerationStrategy and ValueGenerated flag.
Aligned Sqlite to do the same to compute AutoIncrement only when applicable
Resolves #10228

Sqlite: Make AUTOINCREMENT accurate

---

test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs

Query: Enable regression test for InMemory and byte array equality

---

src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs

Query: Get mapped projection from associated query expression
Since projection binding can come from parent query expression too
Resolves #12239

Assumptions are correct till they are not

---

test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Regression test already existed.
Added another variation for #22256
Close #12518

Fix issue#12518

---

src/EFCore/ChangeTracking/Internal/StateManager.cs

Perf: Cache change detector in state manager CascadeDelete
Resolves #22215

Caching is important :snail:

---

azure-pipelines.yml

This fixes the build as it no longer means we rely on VS in official builds. This is currently problematic because efcore uses the p8 SDK, which requires a 16.8 p2, which is not available yet in hosted pools.

Disable validation stages that are run in nightly+staging

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore/Query/ReplacingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs

Resolves #13303
Normal scenario worked already. Weak entities needed some additional handling

Query: Handle multiple lets with weak entities

---

src/EFCore/Query/Internal/NullCheckRemovingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

Query: Add optimization to conditional being equated to equality

---

src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs

SqlServer Migrations: Persist ValueGenerationStrategy.None in snapshot

---

src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
src/EFCore/ChangeTracking/Internal/IValueGenerationManager.cs
src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs

Resolves #22263
Also improves perf for Add

Perf: Cache candidate properties for propagation and generation

---

test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeNoTrackingQueryTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindSplitIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs

Resolves #13669
Resolves #13680
Resolves #13787
Resolves #14901
Resolves #14902
Resolves #15864
Resolves #16104

Add regression tests

---

src/EFCore/ChangeTracking/ChangeTracker.cs
src/EFCore/ChangeTracking/CollectionEntry.cs
src/EFCore/ChangeTracking/EntityEntry.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/ChangeTracking/ReferenceEntry.cs
src/EFCore/Metadata/Conventions/ChangeTrackingStrategyConvention.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Update/Internal/UpdateAdapter.cs

Perf: Cache SkipDetectChanges on model as a field

---

src/EFCore.Proxies/Proxies/Internal/PropertyChangeInterceptorBase.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangedInterceptor.cs
src/EFCore.Proxies/Proxies/Internal/PropertyChangingInterceptor.cs
src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
src/EFCore/Extensions/Internal/ExpressionExtensions.cs
src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
src/EFCore/Metadata/Internal/PropertyBase.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ProxyableSharedType.cs

Support overriding virtual indexer property in proxies

---

test/EFCore.Design.Tests/DesignExceptionTest.cs
test/EFCore.Tests/ExceptionTest.cs

Re-enable exception serialization tests

---

src/EFCore/Extensions/ConventionModelExtensions.cs
src/EFCore/Extensions/ModelExtensions.cs
src/EFCore/Extensions/MutableModelExtensions.cs
src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/InheritanceDiscoveryConventionBase.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/Model.cs

Minor model building perf improvements

---

src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
src/EFCore/ChangeTracking/ChangeTracker.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Internal/InternalDbSet.cs
test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs

Fixes #22255
This must have happened when we switched back from ValueTask to Task. We missed this because we had no coverage for async dispose with context pooling. Added this coverage and scanned code for other occurrences.

Fix return values from ResetAsync

---

src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/InheritanceDiscoveryConventionBase.cs
src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
src/EFCore/Metadata/Internal/InternalModelBuilder.cs
src/EFCore/Metadata/Internal/Model.cs
test/EFCore.Tests/Metadata/Conventions/DerivedTypeDiscoveryConventionTest.cs
test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs

Merge BaseTypeDiscoveryConvention with DerivedTypeDiscoveryConvention.
Make sure that base type is reset when it becomes owned.
Remove entries from the ambiguous inverses as soon as the navigation or declaring type is ignored.

Cache derived types used in DerivedTypeDiscoveryConvention.

---

src/EFCore.Tools/tools/EntityFrameworkCore.psm1

More users seem to be hitting this lately. Making the exception more obvious so we don't spend so much time investigating.
Part of #16386
/cc @Pilchie

PMC Tools: Throw a better exception when ActiveConfiguration returns null

---

src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
src/EFCore.Relational/Update/ColumnModification.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs

Add fluent overloads to specify column types for Insert/Update/Delete operations
Fixes #21886
Fixes #22302

Add the column type to the migration when deleting a data using a removed column

---

src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindGroupByQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindKeylessEntitiesQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs

Added validation step for AddCollectionJoin which checks that if subquery contains Distinct or GroupBy, the projection contains all identifying columns needed to correctly bucket the results during materialization.
Also making sure that identifying columns can be correctly propagated during pushdown and joining - if they are not we mark them as such (by removing identifying columns altogether), so that we can throw exception when these columns are actually needed.
Fixes #15873
Fixes #20184

Fix to #15873 - Query: Identifying columns in the case of distinct

---

src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs

Populate DbUpdateException.Entries for non-concurrency exceptions

---

src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
src/EFCore.Cosmos/Properties/CosmosStrings.resx
src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs

Print expression when throwing null type mapping in SQL tree

---

test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs

Test for #18339

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
src/Shared/Multigraph.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

Correctly break double cycles in FK constraints

---

src/EFCore/Metadata/Internal/InternalModelBuilder.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingSqlServerTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/ManyToManyLoadSqliteTestBase.cs
test/EFCore.Sqlite.FunctionalTests/ManyToManyTrackingSqliteTest.cs
test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Make sure non-shared-type entity types aren't discovered while a shared-type entity type is being added

---

test/EFCore.InMemory.FunctionalTests/IntegerGeneratorEndToEndInMemoryTest.cs

I ran the test repeatedly:
* In the IDE for ~30 mins using run-until-fails
* 30 times in a full test run on the command line
and saw no failures.
Fixes #17672

Re-enable Can_use_sequence_end_to_end_from_multiple_contexts_concurrently_async for in-memory

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs

Don't check for temporary values on non-key properties when deleting an entity

---

src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
src/EFCore/ChangeTracking/ValueComparer.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/Internal/StaticDiscriminatorComparer.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs

Allow discriminator properties to have value converter and comparer

---

src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs

Stop attempting to do local DetectChanges when not snapshot change-tracking

---

src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
src/EFCore/Metadata/Internal/CollectionTypeFactory.cs
test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityBranch.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityCompositeKey.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityLeaf.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityOne.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityRoot.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityThree.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityTwo.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
test/EFCore.Tests/Metadata/Internal/CollectionTypeFactoryTest.cs

Automatically create notification collections when change-tracking proxies are being used

---

src/EFCore/Infrastructure/Annotatable.cs
src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/ForeignKey.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
test/EFCore.Tests/Infrastructure/AnnotatableTest.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.BaseType.cs
test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs

Improve exception messages (cont...)

---

test/EFCore.Specification.Tests/SharedStoreFixtureBase.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsInfrastructureSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs

Before this commit, it was impossible to create a concrete implementation of SharedStoreFixtureBase that requires a `TestStoreFactory` which is initialized asynchronously (the purpose of `IAsyncLifetime`).
After this commit, it becomes possible because the `TestStoreFactory` and the `StoreName` properties are not accessed in the constructor anymore:
```csharp
public class MySharedStoreFixture<TContext> : SharedStoreFixtureBase<TContext> where TContext : DbContext
{
private string? _storeName;
private ITestStoreFactory? _testStoreFactory;
protected override string StoreName => _storeName ?? throw new InvalidOperationException($"The {nameof(StoreName)} property is only available after {nameof(InitializeAsync)} has executed.");
protected override ITestStoreFactory TestStoreFactory => …
```

Create and initialize the TestStore inside InitializeAsync

---

DailyBuilds.md
README.md
docs/DailyBuilds.md

Update daily builds guidance

---

src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
src/EFCore.Tools/tools/EntityFrameworkCore.psm1
src/EFCore.Tools/tools/about_EntityFrameworkCore.help.txt
src/dotnet-ef/Properties/Resources.Designer.cs
src/dotnet-ef/Properties/Resources.resx
src/ef/Commands/DbContextScriptCommand.Configure.cs
src/ef/Properties/Resources.Designer.cs
src/ef/Properties/Resources.resx

Tools: Review resource strings

---

docs/DailyBuilds.md

Tweaks to daily build guidance after feedback

---

src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs
src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs

Part of #7201
/cc @Pilchie FYI

Microsoft.Data.Sqlite: Review resources

---

src/EFCore/Query/Internal/InvocationExpressionRemovingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Where.cs
test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs

Resolves #19511
Port of #19514
In 2.x query pipeline when we used Remotion.Linq library to normalize expression tree into query model, it also inlined all invocation expressions. In 3.1 we added code in our pipeline to do inilining but it was not applying it recursively.
Customers using nested invocations to build expression tree get an exception with translation error.
**How found**
Customers reported that they are facing issue with invocation expressions even after the fix we added in 3.1.
Regression test added to verify that we cover recursive case.
Yes, from EF Core 2.x to 3.1 as 2.x pipeline normalized this through external library.
**Risk**
Very low. Visiting recursively should be no-op if not the case of …

[release/3.1] Query: Unwind nested invocation expressions

---

src/EFCore.Relational/Extensions/RelationalModelExtensions.cs
src/EFCore.Relational/Metadata/SqlQueryExtensions.cs
src/EFCore.Relational/Metadata/StoreFunctionExtensions.cs
src/EFCore.Relational/Metadata/TableExtensions.cs
src/EFCore.Relational/Metadata/ViewExtensions.cs
src/EFCore/Metadata/Internal/Model.cs

Improve RelationalModel DebugView
Fixes #22309

Add RelationalModel debug property to Model

---

src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs
src/EFCore.Design/Design/Internal/DbContextOperations.cs
src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
src/EFCore.Design/Properties/DesignStrings.Designer.cs
src/EFCore.Design/Properties/DesignStrings.resx

Design: Review resources

---

src/EFCore.Relational/Storage/Internal/RawRelationalParameter.cs
test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs

Clone DbParameter when adding to command if ICloneable

---

src/EFCore/Extensions/ConventionEntityTypeExtensions.cs
src/EFCore/Extensions/ConventionModelExtensions.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Extensions/ModelExtensions.cs
src/EFCore/Extensions/MutableEntityTypeExtensions.cs
src/EFCore/Extensions/MutableModelExtensions.cs
src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/Model.cs

Fixes #22503
Some issues fixed late in 5.0.0-rc2 caused a significant perf regression on the code path used frequently by applications. To mitigate this the implementation of how `ChangeTrackingStrategy` is stored in the model was changed.
Customers would experience perf degradation if the affected code path is used extensively.
**How found**
Automated perf testing.
Already covered.
Yes
**Risk**
Low. There is no functional impact.

[5.0.0-rc2] Change ChangeTrackingStrategy from annotation to field

---

src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Part of #22530
Skip navigations were introduced in 5.0.0, but `ForeignKeyAttribute` support wasn't implemented.
Customers using `ForeignKeyAttribute` on skip navigation would see no effect without this fix. Now an exception will be thrown allowing us to add support later without it being a breaking change.
**How found**
New tests included in PR.
No.
**Risk**
Low. Corner case in a new feature.

[5.0.0-rc2] Throw for ForeignKeyAttribute on skip navigation

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs

Fixes #22564
This is a regression from 3.1 found by a customer using RC1. We scaffold the appropriate method call to set the column type, but then also explicitly add the underlying annotation.
This will impact a large majority of migrations generated by customers. While it does not cause a functional break, we would like to avoid thousands of customers getting this redundant code in their apps.
**How found**
Found in customer repro
New tests included in PR. This is also an area where we recognize that we need more testing; this is planned for MQ.
Yes. Regression from 3.1
**Risk**
Low. Just remove redundant annotation.

[5.0-rc2] RevEng: Remove ColumnType annotation from scaffolded code

---

src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
src/EFCore/Metadata/Internal/PropertyExtensions.cs
test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs

Fixes #22573
This is a regression from preview 8 on a very common case for a major new feature. We added FK constraints to the TPT model in RC1, but this broke value generation for the PK property of any TPT mapping.
Very common scenario on a major new feature.
Customer reported moving from preview 8 to RC1.
We were lacking test coverage for change tracking in TPT models. This PR adds a TPT variation to our main change tracking tests (1622 tests). This revealed one additional bug which we will triage separately. 
New feature in 5.0, but regression from preview 8.
Low. Issue is well understood and fix is small.

Generate values for PK properties that are also self-referencing FK properties

---

src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
test/EFCore.Relational.Specification.Tests/DataAnnotationRelationalTestBase.cs
test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs

Fixes #22576
This is a bug in a new feature. In scenarios with more than 2 levels of TPT with an owned type defined on a derived type some methods will return `null` that we haven't accounted for.
It's hard to estimate how many customers will be impacted, but given the location in the code path it's likely to affect other TPT scenarios apart from the one described above.
We were lacking test coverage for complex TPT models. This PR adds a test for the affected scenario. 
No, new feature in 5.0.
Low. Code changes just add `null` checks.

[5.0.0-rc2] Add null checks to account for owned types in TPT

---

docs/DailyBuilds.md

Also changed the guidance around clearing package sources.

Updates to daily build guidance for EF Core 5.0/EF Core 6.0

---

src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteStringTypeMapping.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
test/EFCore.SqlServer.Tests/Storage/SqlServerStringTypeMappingTest.cs
test/EFCore.Sqlite.Tests/Storage/SqliteStringTypeMappingTest.cs

Fixes #22553
We added some code in 5.0 to escape newlines in generated migrations. Unfortunately, this code was a little naive and missed some important cases. Several customers have hit this using RC1.
This will impact many customers, as indicated by the multiple reports we already have against RC1.
We were lacking test coverage for the escaping. Better test coverage is included in this PR.
Yes, from 3.1.
cc @Pilchie

[release/5.0-rc2] Make newline escaping logic more robust

---

src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #22568
It is possible to have bad configuration of auto included navigations in the model which causes a cycle.
Customers with bad configuration when running a query with affected types runs into stackoverflow indicating no information about the error.
**How found**
It is a negative case scenario. We did not have coverage for it. We have added coverage for supported scenario with cycle and error validation for incorrect case.
No, it is new feature introduced in 5.0
**Risk**
Low. It should only affect when auto includes are used. Further any error can be mitigated by ignoring auto include at query level.

[5.0-rc2] Throw exception for cycles in auto included navigations

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/EFCore.Relational.Specification.Tests/DataAnnotationRelationalTestBase.cs

Fixes #22577
Usually a value is only propagated to a foreign key and the foreign key value is not store-generated, however in TPT the property might get a store-generated value before the real value is propagated to it.
The issue mostly affects a new feature - TPT when the principal key is store generated. There is a workaround where the entities to be saved are split and the dependent values cleared manually, but this isn't practical in most applications.
We were lacking test coverage for complex TPT models. This PR adds a test for the affected scenario. 
No, new feature in 5.0.
Low. The fix mostly affects a new feature - TPT and the values that are now discarded were already being discarded before, but on completion of SaveChanges instead of during execution

[5.0-rc2] Also clear the store generated values when setting a normal value

---

src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs

Resolves #22632
In EF Core 3.1, for provider specific annotations we generated HasAnnotation in model snapshot, which we improved to generate specific fluent API calls. For particular API call `UseIdentityColumn` we set other annotations whose values are default values in the method parameter but when generating the code, we did not account for those default values correctly generating same API with arguments.
This change in API causes a diff when adding new migration which can cause conflict. Further changing this after 5.0 would cause diff in other direction in future release.
**How found**
We did not have proper coverage for round-tripping the API. Added tests for this API for all variations. …

5.0 Migrations: Correctly generate UseIdentityColumn(s) API in snapshot

---

src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs

Fixes #22569
In EF Core 3.1, it was possible to specify a SQL Server column type using square brackets. For example, "[money]" instead of "money". EF Core didn't understand this, so we treated it as an unknown decimal type, and passed it through to SQL Server as-is.
In EF Core 5.0, we added support for precision and scale specified independently of the type. We don't do this when we know the type is `money` because doing so is not valid. However, since we don't recognize "[money]" it gets precision and scale added.
The fix is to recognize SQL Server types with square brackets. Note that only type names without spaces can have square brackets.
I don't believe many customers are using square brackets like this. However, I could be wrong about this since …

[5.0 RC2] Handle square brackets around explicitly specified SQL Server type names

---

src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Fixes #22521
Usually the shared-type join entity type is created by convention, but when the configuration source is upgraded to `Explicit` the declared foreign keys that are created by convention are misidentified as unnecessary and removed.
The issue only affects a new 5.0 feature - many-to-many when the join entity type created by convention is configured explicitly without configuring the associated foreign keys. The workaround is to configure the relationship fully, which requires 3-5 more lines of code.
This PR adds a test for the affected scenario. 
No, new feature in 5.0.
Low. The fix only affects a new 5.0 feature and the issue is fixed by not removing a part of the configuration, which is generally safe.

[5.0-rc2] Don't remove skip foreign key when join entity type is configured explicitly.

---

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/GeneratedKeysLeft.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/GeneratedKeysRight.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs

Fixes #22647
If the entity on either end of a many-to-many relationship is Added, then any join entity instance must be new since it references a new entity via a required relationship. This change improves the many-to-many experience by detecting this case.
This is an improvement to the experience for the new many-to-many feature. Doing this now instead of in the future avoids a breaking change after 5.0. Therefore, doing this now will help customers have a seamless update to 6.0.
**How found**
Added additional test coverage around this case.
No; new feature.
**Risk**
Low; small change in behavior.

[5.0-rc2] Mark join entities as Added when either side is Added

---

test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindAggregateOperatorsQueryInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindAsyncSimpleQueryInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindMiscellaneousQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindAsyncSimpleQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs

Resolves #12274
Resolves #11835
Resolves #12597
Resolves #12379
Resolves #12717
Resolves #17775
Resolves #18962

Adding tests for previously fixed issues

---

src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
src/EFCore.Relational/Migrations/HistoryRepository.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
test/EFCore.Relational.Tests/Metadata/Conventions/TableSharingConcurrencyTokenConventionTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalMetadataBuilderExtensionsTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalPropertyAttributeConventionTest.cs
test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs

Fixes #22608
In 5.0 complex mapping support was introduced allowing to map an entity type to multiple tables, views, functions and queries. This subtly changed the meaning of `GetColumnName` return type from a table column name to a base column name to be used for any mapping.
`GetColumnName` is used commonly for batch column name processing and the value returned for properties in owned types is different now compared to 3.1
This PR adds a test for the affected scenario. 
Yes.
Low. The modified method isn't used internally after this change, so there is no danger of other features being affected.

[5.0-rc2] Undo GetColumnName behavior change

---

test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs

The `QuestTask` hierarchy is designed to only be mapped as TPH because the leaves act as principals for the same FK property:
```C#
modelBuilder.Entity<QuizTask>()
.HasMany(qt => qt.Choices)
.WithOne()
.HasForeignKey(tc => tc.QuestTaskId);
modelBuilder.Entity<HiddenAreaTask>()
.HasMany(hat => hat.Choices)
.WithOne()
.HasForeignKey(tc => tc.QuestTaskId);
```
Fixes #22582

Fix the model in GraphUpdatesSqlServerTest.TptIdentity

---

Directory.Build.targets

- see dotnet/arcade#5866 discussion

Include commit SHA in `[AssemblyInformationalVersion]` value

---

src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
src/EFCore/ChangeTracking/ChangeTracker.cs
src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
src/EFCore/DbContextOptionsBuilder`.cs
src/EFCore/DbSet.cs
src/EFCore/Diagnostics/InterceptionResult.cs
src/EFCore/Diagnostics/InterceptionResult`.cs
src/EFCore/Diagnostics/WarningsConfigurationBuilder.cs
src/EFCore/EF.cs
src/EFCore/Infrastructure/DatabaseFacade.cs
src/EFCore/Infrastructure/IModelCustomizer.cs

* Document connection obtained from DatabaseFacade.GetDbConnection() should normally not be disposed Fixes #11415
* Add XML docs referencing how to determine the default CommandTimeout Fixes #17503
* Clarify behavior for EnsureExists with an empty database Fixes #17563
* A hyperlink to the DbContext.Database.Migrate() method would be useful Fixes #17571
* Default values for maxRetryCount, maxRetryDelay, and errorNumbersToAdd Fixes #17574
* Document that modifying entity states while iterating over entries can result in "Collection was modified" exception Fixes #18389
* Update API doc links to correctly reference external dependencies Fixes #18580
* Make it clearer how to access EF.Functions Fixes #21424
* Improve API docs for TrackGraph Fixes #22529

Update API docs

---

.github/ISSUE_TEMPLATE/ask_a_question.md
.github/ISSUE_TEMPLATE/bug_report_efcore.md
.github/ISSUE_TEMPLATE/bug_report_sqlite.md
.github/ISSUE_TEMPLATE/config.yml
src/EFCore/EF.cs

Originally intended to just remove discussions, but this changed into add a template for asking a question, which itself changed into updating the templates.
Notes:
* Not sure if I'm dong this right
* Should the template text be in a comment?
* Should the template text be a template instead of instructions?
* Should we include real, runnable EF code as a starting point in the template?
Other suggestions?

Update issue templates to remove discussions

---

src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
test/EFCore.Tests/Metadata/Internal/InternalSkipNavigationBuilderTest.cs

Fixes #22809
When an ambiguous many-to-many navigation is discovered the code was trying to remove the wrong navigation resulting in an exception.
This is happening by convention, before any user configuration is applied, so there is no straightforward workaround.
Customer report on daily build.
This PR adds tests for the affected scenario. 
No.
Low. The change only affects a new 5.0 feature many-to-many.

[5.0] Remove the correct conflicting skip navigation.

---

src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Fixes #22844
When using the new 5.0 feature many-to-many a join entity type will be used to establish the relationship. The schema it uses currently defaults to `null`, but in most scenarios it should be the same as the related entity types.
Since this affects a new feature fixing it after release would be a breaking change.
Customer report.
This PR adds tests for the affected scenario. 
No
Low. The change only affects many-to-many.

[5.0] Use the schema of related ends for the join entity type by default

---

docs/DailyBuilds.md

Update daily builds to call out the GA daily build

---

eng/Publishing.props

Fixes https://github.com/dotnet/core-eng/issues/11032 which was discovered by post build signing.  Arcade was auto-generating some symbols.nupkgs in this repo, but this repo wasn't expecting them and didn't include them in the asset manifest.  The result was that post build signing validation would discover some symbols.nupkgs that it wasn't told to sign and validation would fail.

Disable auto-generating symbols.nupkgs

---

src/EFCore.Relational/Storage/RelationalConnection.cs
test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs

Add template methods around DbConnection inside RelationalConnection

---

src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
test/EFCore.Specification.Tests/TestModels/TransportationModel/CompositeVehicle.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs

Fixes #22873
When a hierarchy with more than 2 levels is mapped using TPT and the root table has other types sharing it the relational model didn't include all the derived types in the mapping.
Queries and updates fail for the affected models. There is no reasonable workaround.
Customer report on daily build.
This PR adds tests for the affected scenario. 
No.
Low. The change only affects a new 5.0 feature TPT.

[release/5.0] Ensure grandchildren and below are mapped to the root table when using table sharing.

---

src/EFCore/ChangeTracking/EntityEntry.cs
src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs
src/EFCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
test/EFCore.InMemory.FunctionalTests/ManyToManyTrackingInMemoryTest.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxySqlServerTest.cs
test/EFCore.Tests/ChangeTracking/SkipCollectionEntryTest.cs

Fixes #22882
Skip navigations (i.e. many-to-many navigations; new for 5.0) are not being returned as members, navigations, or collections from an an API used to access them. In addition, scrubbing the code found three other issues with the same pattern, plus a few that need more investigation. This PR contains fixes and tests for the four clear issues. I have filed #22883 to follow up on the others.
* Navigations for a major new feature are not being returned from an API that should return them.
* Attaching a graph asynchronously may miss navigations.
* Skip navigations are missed as notification properties.
* Exception will say a property is not found, when actually it is a navigation.
**How found**
Customer reported on RC2 daily build.
**Test …

[5.0] Fix places where skip navigations are missed

---

src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpNamerTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CandidateNamingServiceTest.cs

Accept empty and emoji column names when reverse engineering

---

src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs

Part of #22883
Skip navigations (i.e. many-to-many navigations; new for 5.0) could contain entities when used in seed data. However they will be ignored.
With this change EF will throw an exception explaining the supported way to add seed data. Making this change after 5.0 would be a bigger breaking change as more users could be affected.
**How found**
Code examination.
This PR adds tests for the affected case.
No.
**Risk**
Low. The change only affects skip navigations, which are new in 5.0.

[5.0] Add validation for seed data with skip navigations

---

test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

Resolves #10295
Resolves #12453
Resolves #13216
Resolves #13550
Resolves #13712
Resolves #13977
Resolves #15302
Resolves #17735

Additional regression tests for issues that have been fixed previously

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

What is life if full of care
If we have no time to stand and stare
Sqlite for some reason does not allow aliases - "True"/"False"
Resolves #22915

Query: Use aliases when doing pushdown

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs

Floor the sequence values to long Min and Max

---

src/EFCore/Infrastructure/EntityFrameworkEventSource.cs

The backing fields for the counters are `long`, so there was potential torn read on 32-bit platforms.
`Volatile.Read` ensures that the value is read in a atomic way, so no torn reads can occur.

Fixed potential torn reads in EventCounters

---

src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs

Closes #20228
Rebases #22273 against main

Implement savepoint API for Microsoft.Data.Sqlite

---

eng/helix.proj
global.json
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs

- use the latest SDK and contained runtimes when building this repo

Upgrade to a 6.0 SDK

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs

Fixes #21146
When using `ValueGeneratedOnAdd` on a property that is seeded it causes redundant `UpdateData` calls in every subsequent migration to be generated
This is porting a 5.0 fix for https://github.com/dotnet/efcore/issues/21661 (https://github.com/dotnet/efcore/commit/a8f0f4c4dfc94975bd318a6b5a5d3a627df1d5ba) to 3.1.x
This issue makes generating subsequent migrations very tedious as the redundant entries need to be found and removed manually, which is error-prone.
Multiple customer reports on 3.1.6.
This PR adds a test for the affected scenario. 
Yes, from 3.0.3
Low. The affected code path is only used for data seeding and the fix was validated in 5.0.

[release/3.1] Fix issue where property with value generated on add is reseeded in every migration

---

Directory.Build.targets

- see dotnet/arcade#5866 discussion

[release/3.1] Include commit SHA in `[AssemblyInformationalVersion]` value

---

src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs

This works around a mono bug preventing using Xamarin, see https://github.com/dotnet/efcore/issues/22665#issuecomment-707734584 for details.
Fixes #22665
A mono bug currently prevents EF Core 5.0 from being used on Xamarin Android (and possibly other mono-based platforms). This PR replaces the API call causing issues on mono with a workaround that does not.
EF Core 5.0 is currently unusable with Xamarin Android.
**How found**
Reported by a user: #22665
We unfortunately do not have test coverage for Xamarin yet (#8792). We do have testing around this code area which confirms the fix doesn't introduce other regressions in general.
Yes, from 3.1.x
**Risk**
Low, the change is a very local replacement of a single API call …

Work around mono bug affecting Xamarin Android

---

src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs

Original PR merged to main: #22982
Fixes #22665
(cherry picked from commit fbc11f26134e6c283cb785c80a88447863e14ea8)
A mono bug currently prevents EF Core 5.0 from being used on Xamarin Android (and possibly other mono-based platforms). This PR replaces the API call causing issues on mono with a workaround that does not.
EF Core 5.0 is currently unusable with Xamarin Android.
**How found**
Reported by a user: #22665
We unfortunately do not have test coverage for Xamarin yet (#8792). We do have testing around this code area which confirms the fix doesn't introduce other regressions in general.
Yes, from 3.1.x
**Risk**
Low, the change is a very local replacement of a single API call with another code pattern that does the …

Work around mono bug affecting Xamarin Android (#22982)

---

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs

Fixes #22611
In 5.0 we started generating EXEC calls in idempotent migration SQL scripts to work around quirks in the SQL Server parser. Unfortunately, this code didn't integrate well with another change we made to generate CONCAT calls for string literals containing new lines. The resulting SQL--`EXEC(CONCAT(...))`--is invalid.
This will only affect users generating idempotent migration scripts containing seed data. One customer has reported it so far.
Customer reported on RC2.
We have tests comparing the generated SQL against a baseline. However, we don't have any tests that execute the SQL scripts due to the complexity of executing scripts containing utility statements like GO that aren't supported by SqlClient and only work in tools like SSMS, SDT, and SQLCMD. We previously failed to …

[release/5.0] SqlServer Migrations: Don't generate EXEC(CONCAT())

---

src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs

Avoid lambda capture of cancellation token in ExecuteAsync

Avoid lambda capture of cancellation token

---

All.sln.DotSettings
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs

Add regression test for count after client eval

---

src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs

Simplified `string.IsNullOrWhiteSpace` translation for SqlServer to
```
@value IS NULL OR @value = N''
```
instead of 
```
@value IS NULL OR LTRIM(RTRIM(@value)) = N''
```
Fixes #22916
Please review

Simplify string.IsNullOrWhiteSpace translation for SqlServer

---

src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs

Extends SqlServerStringMethodTranslator (without changes in [StringMethodTranslator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/Internal/StringMethodTranslator.cs#L56)) to simplify `string.IsNullOrEmpty` translation
```
@value IS NULL OR @value LIKE N''
```
instead of
```
@value IS NULL OR @value = N''
```
Fixes #23037
Please review

Simplify string.IsNullOrEmpty translation for SqlServer

---

global.json

With 3.1.8 runtime installed and 5.0-rc2 SDK installed,
- Command line build with dotnet build works
- Opening in VS without activation script or startvs script works.

Use 5.0 SDK

---

src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
src/EFCore.Cosmos/Properties/CosmosStrings.resx
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.ReadItemQueryingEnumerable.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

Exception message review

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs

See https://github.com/dotnet/efcore/issues/22150
In 5.0 we started to reverse-engineer "included columns" for indexes. However, we have a bug where if the column names are different from the mapped property names, then the result is incorrect and fails at runtime. Fixing this bug requires significant work and is not something we can do in a patch. Therefore, we want to pull this feature.
We've had several people run into this on the previews/RCs, and the reports keep coming. On reflection, we think it's likely that many customers will have column names that don't match, and so will hit this. The workaround is to edit the generated code to fix it. But this is manual and could involve editing hundreds of lines of code. This would then need to be done …

[release/5.0] SqlServer RevEng: Stop scaffolding included index columns

---

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs

Fixes #23045
In EF Core 5.0, we fixed issue #21364 which sometimes omitted the ALTER COLUMN statement when it was not needed. Unfortunately, migrations generated using versions of EF Core prior to version 3.1.0 don't contain enough information to always know whether or not the column type was actually changed. This results in the ALTER COLUMN statement being erroneously omitted.
Anyone with migrations generated prior to EF Core 3.1 who try to apply them using EF Core 5.0 may run into this issue. Their column type will not be changed as expected which can lead to subsequent issues (as reported in the original issue).
**How found**
Customer reported
We have tests that cover migrations generated using EF Core 3.1 but they didn't cover …

[release/5.0] SqlServer Migrations: Don't omit ALTER COLUMN when old type is unknown

---

src/EFCore.Abstractions/UnicodeAttribute.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/UnicodeAttributeConvention.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs

https://github.com/dotnet/efcore/issues/19794 Support Unicode attribute

Support Unicode Attribute

---

src/EFCore.SqlServer/EFCore.SqlServer.csproj

It looks like @dependabot doesn't update from a stable version to a prerelease version. I don't see a way to configure it.
Release notes: https://github.com/dotnet/SqlClient/tree/master/release-notes/2.1

Update to Microsoft.Data.SqlClient 2.1.0-preview2

---

.github/dependabot.yml
All.sln
EFCore.Relational.slnf
EFCore.Runtime.slnf
EFCore.slnf
test/EFCore.OData.FunctionalTests/EFCore.OData.FunctionalTests.csproj
test/EFCore.OData.FunctionalTests/Extensions/HttpContentExtensions.cs
test/EFCore.OData.FunctionalTests/Properties/TestAssemblyConditions.cs
test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsControllers.cs
test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataContext.cs
test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTestFixture.cs
test/EFCore.OData.FunctionalTests/Query/ComplexNavigationsODataQueryTests.cs
test/EFCore.OData.FunctionalTests/Query/GearsOfWarControllers.cs
test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataContext.cs
test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTestFixture.cs
test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTests.cs
test/EFCore.OData.FunctionalTests/Query/IODataQueryTestFixture.cs
test/EFCore.OData.FunctionalTests/Query/NorthwindControllers.cs
test/EFCore.OData.FunctionalTests/Query/NorthwindODataContext.cs
test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTestFixture.cs
test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTests.cs
test/EFCore.OData.FunctionalTests/Query/ODataQueryTestBase.cs
test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
test/EFCore.OData.FunctionalTests/TestAssembly.cs
test/EFCore.OData.FunctionalTests/TestControllers.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerNorthwindTestStoreFactory.cs

Adding infrastructure and rudimentary tests using OData. Ported Northwind, ComplexNavigations and GearsOfWar models. Only setup for sqlserver currently.
Resolves #21402

Fix to #21402 - Test using OData

---

src/EFCore/Infrastructure/Annotatable.cs
src/EFCore/Infrastructure/IAnnotatable.cs
src/EFCore/Metadata/IConventionAnnotatable.cs
src/EFCore/Metadata/IConventionEntityType.cs
src/EFCore/Metadata/IEntityType.cs
src/EFCore/Metadata/IMutableAnnotatable.cs
src/EFCore/Metadata/IMutableEntityType.cs
src/EFCore/Metadata/ITypeBase.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/TypeBase.cs
src/Shared/NonCapturingLazyInitializer.cs
test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs

Annotates Annotatable (haha), EntityType and related types.
No particular difficulties encountered, this was quite straightforward. A couple notes:
* I've annotated mutating methods (e.g. EntityType.SetPrimaryKey) to return nullable, because they return the results of conventions which could return null. Is this correct?
* I know we don't like TODO comments, but in some places I've left special TODO-NULLABLE for stuff to check/improve (this was the pattern used in the runtime repo).

First nullability work on metadata

---

src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexMethodTranslator.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexTranslator.cs
src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs

Translate Regex.IsMatch on SQLite

---

All.sln.DotSettings
src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
src/EFCore.Relational/Storage/RelationalTransaction.cs
src/EFCore.Relational/Storage/RelationalTransactionFactory.cs
src/EFCore.Relational/Storage/RelationalTransactionFactoryDependencies.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTransaction.cs
src/EFCore.SqlServer/Storage/Internal/SqlServerTransactionFactory.cs
src/EFCore/Storage/IDbContextTransaction.cs
test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
test/EFCore.Relational.Tests/Storage/RelationalTransactionExtensionsTest.cs
test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs
test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs

And move savepoint management generation logic to ISqlGenerationHelper.
Fixes #23021
Note: some version of this can in theory be backported to fix 5.0, but it's complicated and probably not worth the risk.

Delimit savepoint names as identifiers

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore.SqlServer/Query/Internal/SkipTakeCollapsingExpressionVisitor.cs
src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs

SqlServer: Generate False predicate when skip/take both are 0

---

src/EFCore.Cosmos/Query/Internal/CosmosMemberTranslatorProvider.cs
src/EFCore.Cosmos/Query/Internal/IMemberTranslator.cs
src/EFCore.Cosmos/Query/Internal/IMemberTranslatorProvider.cs

Static methods
First code change from codespaces

Cosmos: Instance can be null for member translation

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs

Also remove implicit convert for float to double since there is no explicit convert in Cosmos
Resolves #16919

Cosmos: Add support for char literals

---

test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Re-enable previously failing test

---

src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerMethodCallTranslatorProvider.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs

SqlServer: date constant in DateAdd method is always datetime

---

test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

Re-enable in-memory test for optional navigation access

---

src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

Query: Add support for set operations between 2 collection navs

---

src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs
src/EFCore.InMemory/Infrastructure/Internal/IInMemorySingletonOptions.cs
src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs
src/EFCore.InMemory/Infrastructure/Internal/InMemorySingletonOptions.cs
src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
src/EFCore.InMemory/Properties/InMemoryStrings.resx
src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
src/EFCore.InMemory/Storage/Internal/InMemoryTableFactory.cs
test/EFCore.InMemory.FunctionalTests/InMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/NullabilityCheckInMemoryTest.cs
test/EFCore.InMemory.Tests/ModelBuilding/InMemoryModelBuilderGenericTest.cs
test/EFCore.Tests/DbContextServicesTest.cs

Add nullability check to In-Memory Database

---

NuGet.config
eng/Versions.props
global.json

- rebrand
- move to GA .NET SDK
- remove feeds that are not needed after 5.0.0 is GA

[release/5.0] Move to 5.0.1 versions

---

src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs

Original PR merged for 5.0: #18873
This backports the fix for #18831 to 3.1.
A missing StringComparison.Ordinal causes a string comparison to be culture-sensitive, and incorrectly omits the @ placeholder character for parameter names when using the Thai culture.
EF Core 3.1 is largely unusable when using the Thai culture, without a specific non-trivial workaround (replace the ISqlGenerationHelper service).
**How found**
Reported three times: #18831, #23032, https://github.com/npgsql/efcore.pg/issues/1508
#22625 added the new code analysis support coming with Roslyn for 5.0, including checks for StringComparison. Using the overload without StringComparison now generates a compilation error.
Not within 3.1.x.
**Risk** …

3.1.11: Add missing Ordinal to parameter StartsWith comparison

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs

When optimizing false == x -> !x we were not running optimization for the Not that we just created, like we do for x == false
Fixes #23121

[TINY] Fix to #23121 - Query: improve optimization of "false==(expr)"

---

src/EFCore.SqlServer/Metadata/Conventions/SqlServerIndexConvention.cs
src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs

Fixes #23092
The fix does the following:
- Don't discover FK properties for an identifying FK created by convention
- Silently ignore inherited properties in TPT in `SqlServerIndexConvention` instead of throwing an exception
Currently when there's property with name in form of *Foo*Id on base type named *Foo* in a TPT hierarchy an exception is thrown when a convention is applied. The workaround is non-obvious and might not work when there are multiple types with this pattern.
**How found**
Reported by user on RC2
This PR includes tests for the affected scenario.
No, this only affects TPT - a new feature in 5.0
**Risk**
Low. The fix only affects models using TPT.

[5.0.1] Fix issues with property called FooId on base type Foo in TPT

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderGenericTestBase.cs
test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs

Fixes #23137
The fix does the following:
- Generate the correct overload for excluding tables for owned types.
- Don't generate `DropForeignKey` or data operations for excluded tables.
- Don't set excluded from migrations to `false` if it was not specified.
When an owned entity type is excluded from migrations we generate an incorrect API call in the model snapshot that needs to be fixed manually. And when the next migration is created a `DropForeignKey` operation is generated for the foreign key to owner even though no operations should be created for tables excluded from migrations. This operation needs to be removed manually.
If both the owner and owned types are mapped to the same table and only the owner is excluded the generated snapshot throws an …

[5.0.1] Generate the correct overload for excluding tables for owned types.

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
test/EFCore.InMemory.FunctionalTests/GraphUpdates/GraphUpdatesInMemoryTest.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToOne.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToOneAk.cs
test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs

Fixes #23180
When propagating store-generated value from the principal entry to the dependent we set the FK store-generated value to `null` if there was any, due to #22603. When accepting the values on the dependent entry we overwrite the propagated value with the "store-generated" `null`.
EF expects that the properties that currently have the default value to be store-generated. Therefore it is reasonable to only accept the store-generated value if it's different from the default.
Inserting a non-TPT dependent and two principals or a TPT-dependent and a principal when the principals have store-generated primary keys will result in a navigation to principal being set to `null`. 
It is possible to manually set the navigation after calling `SaveChanges` …

[5.0.1] Only accept non-default store-generated values

---

src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs

Fixes #23274
EF doesn't use the default schema for view mappings.
The schema needs to be specified in all `ToView` calls.
**How found**
Reported by user on 5.0.0
This PR includes tests for the affected scenario.
Yes, this used to work in 3.1
**Risk**
Low. The behavior is being reverted to what it was in 3.1

[5.0.1] Use default schema for view mappings

---

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs

Original PR merged for 5.0: #21190
**Note for Tactics**
This issue was previously approved for 3.1.11. However, our ever astute MVP @ErikEJ pointed out that since 3.1 targets .NET Standard 2.0, we will potentially be generating 
```C#
#nullable disable
```
in projects where that **won't compile**.
Therefore, we could either not do this at all, or instead generate something like:
```C#
// Code scaffolded by EF Core assumes nullable reference types (NRTs) are disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable
```
---
This backports the fix for #23016 to 3.1.
This adds `#nullable disable` at the top of all C# files generated by EF Core's scaffolding.
EF Core scaffolding is currently unaware of …

3.1.11: Disable NRTs in scaffolding

---

All.sln.DotSettings
src/EFCore/DbContext.cs
test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs

Fixes #23108
We added three new .NET events on DbContext in 5.0. These events are not cleared when the DbContext is disposed, which can lead to memory leaks.
Potential memory leak. (We had a similar bug in the early days of EF6 that resulted in several hard-to-find customer memory leaks.)
**How found**
Internal code review.
We were missing coverage for this. Added in this PR.
No; these events are new in 5.0.
**Risk**
Very low. Set the event handlers to null when the context is disposed (and hence it is invalid to use it anymore and any operation on it will call ObjectDisposedException. Also quirked.

[5.0.1] Clear events when DbContext is disposed or returned to the pool

---

test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/CogTag.cs
test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsWeakQuerySqliteTest.cs

Resolves #21836
Resolves #22978
Resolves #23205

Add regression tests to several bugs that were fixed previously

---

src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/Shared/Multigraph.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs

Fixes #23289
EF Core 5.0 adds validation that detects identifying relationship cycles to prevent infinite recursion. However the algorithm used returned false positive for multiple paths.
Users who have identifying relationships with multiple paths in their model are unable to use them.
**How found**
User-reported for 5.0.0
Added in this PR.
Yes, the affected scenario worked correctly in 3.1
**Risk**
Low. The topological sort implementation has been in use since 1.0 and is thoroughly tested.

[5.0.1] Use topological sort to detect identifying relationship cycles.

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
test/EFCore.Relational.Specification.Tests/Query/OwnedQueryRelationalTestBase.cs
test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs

Resolves #23130
Some additional tests changed because it ended up causing client eval in the middle due to another level of OwnsMany
Whenever an entity has composite PK and an owned collection, we fail to generate correct correlation predicate to join with table containing owned entities. The incorrect predicate fails during translation throwing an exception.
Customers cannot use owned collection when owner has composite PK. This can also arise indirect when owned collection entity also contains another owned collection where convention will put composite PK.
**How found**
Reported by user on RC2
This PR adds coverage for Owned collection targeting owner with composite PK
Yes, the scenario worked in 3.1
**Risk**
Low …

[5.0.1] Query: Generate predicate correctly when expanding owned collections

---

All.sln.DotSettings
src/EFCore.SqlServer/Diagnostics/Internal/SqlServerLoggingDefinitions.cs
src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
src/EFCore.SqlServer/Storage/Internal/SqlServerTransaction.cs
src/EFCore/Diagnostics/WarningsConfiguration.cs
test/EFCore.SqlServer.FunctionalTests/MigrationsInfrastructureSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs

Fixes #23269
**Additional context for Tactics**
This is a tricky one, because it is a regression in 5.0 resulting in an exception, the root cause of which is new feature added in 5.0. We don't want to break this new feature in 5.0.1 for people who are using it successfully in 5.0.0. Therefore, we are:
- Reverting the behavior here to that of 3.1, but only in the specific case that is broken. (This kind of pivot isn't ideal, but this is a tricky case.)
- Rather than doing this silently, we also generate a warning in the logs when we do this.
EF Core 5.0 adds transaction savepoint support, and automatically uses savepoints to make SaveChanges better when an external transaction is used. Unfortunately savepoints do not work in SQL Server when the Multiple Active Result Set …

[5.0.1] Disable savepoints on SQL Server when MARS is enabled

---

src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #23211
Resolves #23276 
Adding quirk in a separate commit
Same root cause results in two bugs:
1. When an entity type has _two or more owned reference types_ which are mapped to _different tables_, then including the collection on such an entity type with a split query throws. Split queries are a new feature in 5.0.
2. When an entity type has an _owned reference type_ mapped to a _different table_ then including the collection in a split query with a _single result_ generates wrong results which can lead to data corruption.
Either exception of data corruption when using new split query feature with owned reference types.
**How found**
We found this while adding MQ test coverage for owned types. It has not been customer reported yet, but we …

[5.0.1] Query: Correctly compute ordering to be copied from outer in collection join

---

src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs

Resolves #23268
Regression when scaffolding from database: if a unique constraint does not have a name, then the reverse engineering tool throws an exception.
Regression such that customers who were previously able to reverse engineer a database may now not be able to do so. There is no workaround other than changing your database to name constraints.
We do not have good data on how many people have unnamed constraints, but given this was filed early after release it seems reasonable to assume there will be more.
**How found**
Customer reported on 5.0. This was a case where we didn't realize it was valid to have a constraint like this without it being named. We previously didn't reverse engineer the name, so we never ran into this until 5.0.
**Test …

[5.0.1] RevEng: Call correct overload of HasIndex when scaffolding constraints without name

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs

Resolves #23285
This is a query regression with the in-memory database when an entity type both _references an owned entity_ and is _in a hierarchy_.
Unable to make any queries using models which contains both a hierarchy and acts as a owner for some owned entity. Note that this is only for the in-memory database, which means it is unlikely to impact production code. However, it is very likely to impact tests for production code since it is a common scenario which is likely to be tested by many using the in-memory database.
**How found**
Added test for affected scenario. Also MQ work is greatly increasing our coverage of owned types.
Yes, this worked in 3.1.
**Risk**
Low. This aligns the …

[5.0.1] InMemory: Copy correct value buffer data when doing LeftJoin

---

src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #23282
Resolves #23104
Issue: When buffering is enabled, first time when we read particular property slot, we create expression to read into buffer and out of the buffer. We mistakenly bypassed changing expression to read from value buffer when same property slot was being read again, causing cast errors.
Any type mapping having custom read expression from data reader throws an exception while retrying strategy is enabled. This was reported for SQL Server spatial types, but we know that Oracle uses the same pattern for some of its type mappings, so this is likely to be broken for Oracle too once they have an updated provider.
When retrying strategy is enabled (which is recommended for all SQL Azure applications), querying for spatial types or …

[5.0.1] Query: Properly generate expression to read from BufferedDataReader

---

src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs

Resolves #23265
Everyone wants their own set of conditions for pushdown. ¯\\_(ツ)_/¯
When applying GroupBy over result of another GroupBy-aggregate, we missed doing a push-down of the subquery causing incorrect results. This is a regression from 3.1 in a reasonably common query pattern.
Incorrect results which can cause data corruption in customer apps.
**How found**
Added test for affected scenario.
Yes, this worked in 3.1.
**Risk**
Low.  This brings back same set of condition which were in place for push-down in 3.1

[5.0.1] Query: Pushdown into subquery when applying group by over a group by

---

src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs

Sometimes reclaiming memory is not the best thing to do. You never know what you will need in future.
Resolves #23266
In 5.0, we cleared the projection mapping when adding single projection to SelectExpression. However, this is still needed if there are further subqueries to be translated in the projection. We don't need to clear here since this will be done by the projection translation.
Regression for any query which is evaluating on client for final projection (common) and also doing FirstOrDefault (or friends) on a non-primitive type will fail with exception.
**How found**
Added test for affected scenario and existing scenario also working since clearing is happening later automatically. …

[5.0.1] Query: Don't clear projection mapping when adding single projection

---

src/EFCore.Relational/Metadata/Internal/InternalDbFunctionBuilder.cs
test/EFCore.Relational.Tests/Metadata/DbFunctionMetadataTests.cs

[TINY] Fix to #23370 - Function and parameter names flipped for DbFunctionInvalidParameterName

---

src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs

Resolves #23309
Regression when client evaluation in the final projection (common) encounters a conditional expression where one part can be null in the database. In this case we end up with mismatched types between the true/false part of the conditional, resulting in an exception.
Regression when a ternary is used in projection when client eval happens, which is a common case.
**How found**
Added test for affected scenario.
Yes, from 3.1.
**Risk**
Low. Convert node would only fail when null is encountered when non-null expected which is error.

[5.0.1] Query: Match types in conditional during client evaluation

---

src/EFCore/ChangeTracking/Internal/InternalEntityEntryFactory.cs
src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/Extensions/EntityTypeExtensions.cs
src/EFCore/Infrastructure/ModelValidator.cs
src/EFCore/Metadata/Conventions/DerivedTypeDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
src/EFCore/Metadata/Conventions/NotMappedMemberAttributeConvention.cs
src/EFCore/Metadata/Conventions/OwnedEntityTypeAttributeConvention.cs
src/EFCore/Metadata/Conventions/PropertyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
src/EFCore/Metadata/IEntityType.cs
src/EFCore/Metadata/ITypeBase.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
src/EFCore/Metadata/Internal/InternalModelBuilder.cs
src/EFCore/Metadata/Internal/Model.cs
src/EFCore/Metadata/Internal/Property.cs
src/EFCore/Metadata/Internal/TypeBase.cs
src/EFCore/Metadata/Internal/TypeBaseExtensions.cs
src/EFCore/Query/Internal/EntityMaterializerSource.cs

@AndriySvyryd we can also move other extension methods to be properties on the interfaces if we want (especially internal ones).

Change some metadata extension methods into DIM properties and annotate for nullability

---

test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ManyToManyQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTManyToManyQuerySqliteTest.cs

This is likely fixed by adopting to newer sqlite version underneath
Resolves #21541

Enabled tests marked with sqlite bug

---

src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx

Mainly error in projection binding expression visitor, when we have an unknown extension expression which is hit when client evaluating, (non-client eval we wouldn't reach this code).
Translation failure seems most appropriate error.
Returning NoTranslationExpression will actually provide lesser value in what failed exactly.
Cosmos has a lot of places where it used but those are supposed to invariants and shouldn't exist after Cosmos Query pipeline is updated.
Resolves #22508

Remove QueryFailed

---

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs

Fixes #23250
In Microsoft.Data.Sqlite 5.0 we updated the connection to throw when the database is encrypted, but not key (aka password) was provided in the connection string.
While this improved the experience for users who forgot to supply a key, it broke others who were supplying the key immediately after opening the connection.
The fix in this PR reverts to the 3.1 behavior.
Without this fix, anyone supplying a key after opening the connection would need to update their app to supply it in the connection string instead.
```csharp
// Change this...
connection.Open();
connection.Execute("PRAGMA key = 'password'");
// ...to this
connection.ConnectionString = "" + new SqliteConnectionStringBuilder(connection.ConnectionString)
{
Password = "password"
}; …
```

[5.0.1] Microsoft.Data.Sqlite: Don't force decryption when password unset

---

src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs

Fixes #23390
We took some fixes in EF Core 5.0 to enable using additional dimensions (Z and M) in spatial data on SQLite. However, we missed some updates in Migrations resulting in the columns getting created incorrectly in the database.
This only affects users wanting to start using Z and M in EF Core 5.0. The columns are created in a way that can read and write the data, but more advanced queries and database validation of the data won't work.
**How found**
Customer reported
We have coverage of reading and writing these values to the database, but no coverage asserting the DML we use to create the columns. This PR adds that coverage.
No, Z and M did not work at all in SQLite prior to EF Core 5.0.
**Risk**
Low

[5.0.1] Sqlite Migrations: Handle Z and M in spatial columns

---

Directory.Build.props

'Cause sometimes you're in the flow and just wanna code.

Allow missing headers and doc comments in developer builds

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
src/EFCore/Query/EntityShaperExpression.cs
src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Also improved In-Memory set operation implementation
Resolves #19253

Query: Assign nullability to entity shaper correctly for set operations

---

src/EFCore.Cosmos/Query/Internal/CosmosQueryTranslationPostprocessor.cs
src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs

Resolves #21142 
Resolves #16752

Cosmos: Apply projection in post processor

---

src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs

Fixes #23386
EF Core 5.0 added support for database and column collations, but the scaffolding logic was faulty.
When reverse engineering an existing database, column collations are mistakenly scaffolded as comments, and database collations aren't scaffolded at all.
**How found**
User-reported for 5.0.0
Added in this PR. In addition, we have identified scaffolding as an area where we are lacking sufficient test coverage and are beginning to address this.
No, collations are new in 5.0.
**Risk**
Very low, minimal code changes, and only in the scaffolding code (no impact on runtime).

[5.0.1] Fix collation scaffolding

---

src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs

Resolves #23336
Hash code computation in SqlFunctionExpression does not check for null for niladic functions (non-parameter functions). Niladic functions are frequent in Spatial types.
Queries involving collection projection, spatial function and FirstOrDefault will throw null ref.
**How found**
Test added for affected scenario.
Yes, the buggy code existed on 3.1 too but it was not being hit in some query scenario. Other changes in query exposed this bug and made working queries from 3.1 to fail in 5.0
**Risk**
Low.

[5.0.1] Query: Add null check in hash computation in SqlFunctionExpression

---

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs

Since all the columns are considered included columns
Resolves #23378
All the columns in the columnstore index in SqlServer appears as included columns for the index. When we started identifying included columns as separate and started skipping them over, the columnstore indexes were left without any columns in the index causing error when generating model out of it.
Customer will see an exception when scaffolding a database which has a columnstore index without any details why it failed. It has only been reported by a single customer so far, but we believe more people will hit this given that it also reproduces when scaffolding from the WideWorldImporters sample database, which is commonly used in SQL Server samples.
**How found**
Customer reported on …

[5.0.1] RevEng: Ignore column store index

---

src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #23410
in EF Core 5.0, we added support for indexer properties. As a part of translating indexer properties, we intercepted them and tried to identify them in model. If not found, we would terminate translation. In earlier versions, this would actually go into further translation treating indexer access as just a normal method call. There are custom extensions/plugins out there that utilize this (it reported on the MySQL provider, PostgreSQL is also impacted) and provide support for JSON mapping to database as in JSON dictionary, tokens are accessed using indexer.
Customers which were using indexer by custom mapping or through 3rd party libraries will start having errors in using indexers in their queries without any work-around. This was …

[5.0.1] Query: Don't terminate translation if indexer method does not bind to indexer property

---

src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

Fixes #23377
Fixes #23354
Some unsupported models cause `StackOverflowException` instead of a more useful exception.
Using the same property for a self-referencing many-to-many or using the same entity type as the join entity type produces a  `StackOverflowException`.
**How found**
Multiple customers reported on 5.0.
Added tests for affected scenarios
No, many-to-many is a new feature in 5.0
**Risk**
Low. This only affects many-to-many.

[5.0.1] Avoid stack overflow in negative many-to-many cases

---

src/EFCore.Relational/Migrations/HistoryRepository.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs

Resolves #23312
When generating the script to create migration history table, we use a model builder to generate the model. This model builder is decoupled from the application DbContext so that it won't include application entity types in the model. However, this decoupling is broken in 5.0 because we still discover methods on DbContext annotated with DbFunctionAttribute. If the DbFunction is targeting table valued function (TVF), then we add that as an entity type to the model. This causes an incorrect model to be built for the history table.
Customers who have TVF declared using DbFunction attribute on their DbContext will get error when applying first migration or generating migration script from first migration. We create the migration history …

[5.0.1] Migrations: Skip DbFunctionAttributeConvention when creating model for history repository

---

src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToOne.cs
test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToOneAk.cs
test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs

Disable owned entity reparenting if it leads to key modification
Fix default SQL Server value generation strategy for shared columns
Query: Detect parent identifier correctly when parent has owned navs
Fixes #16454

Create GraphUpdatesTests for owned entities

---

src/EFCore.Design/Properties/DesignStrings.Designer.cs
src/EFCore.Design/Properties/DesignStrings.resx
src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs

So model builder does not throw error.
Resolves #23405

RevEng: Warn for FK with same required facets exists and skip it

---

src/EFCore.Cosmos/Extensions/CosmosDatabaseFacadeExtensions.cs
src/EFCore.Cosmos/Extensions/CosmosServiceCollectionExtensions.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryContext.cs
src/EFCore.Cosmos/Query/Internal/CosmosQueryContextFactory.cs
src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
src/EFCore.Cosmos/Storage/Internal/ICosmosClientWrapper.cs
src/EFCore.Cosmos/Storage/Internal/ISingletonCosmosClientWrapper.cs
src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs

Interfaces for CosmosClientWrapper and SingletonCosmosClientWrapper

---

src/EFCore.Cosmos/Diagnostics/CosmosEventId.cs
src/EFCore.Cosmos/Diagnostics/CosmosQueryEventData.cs
src/EFCore.Cosmos/Diagnostics/CosmosReadItemEventData.cs
src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggerExtensions.cs
src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggingDefinitions.cs
src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
src/EFCore.Cosmos/Properties/CosmosStrings.Designer.tt
src/EFCore.Cosmos/Properties/CosmosStrings.resx
src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
test/EFCore.Cosmos.FunctionalTests/Query/QueryLoggingCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/QueryLoggingCosmosTestBase.cs
test/EFCore.Cosmos.FunctionalTests/Query/QueryLoggingCosmosTestSensitive.cs
test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestSqlLoggerFactory.cs
test/EFCore.Cosmos.Tests/CosmosEventIdTest.cs

Use loggging infrastructure on Cosmos

---

azure-pipelines.yml

Enables post build signing. This repo will discontinue signing in-build and instead the entire product will sign all at once in the staging pipelines.

Enable post-build-signing

---

test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs

Query: Add regression test for #21003

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs

LambdaExpression can never be translated. The only time when returning null has effect in translation is projection where we would visit the base to client eval.
But lambda cannot be client evaluated either so right thing to do is just throw exception so that user know which lambda is throwing error.
Resolves #18179

Query: Throw error for translating Lambda right away

---

src/EFCore.Abstractions/EntityConfigurationAttribute.cs
src/EFCore/Metadata/Conventions/EntityConfigurationEntityTypeAttributeConvention.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
test/EFCore.Tests/Metadata/Conventions/EntityConfigurationAttributeConventionTest.cs

Fixes #23163 
I am not sure how I have to handle the case when in the attribute a wrong Configuration type is given

EntityTypeConfiguration annotation #23163

---

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
test/EFCore.Sqlite.Tests/Storage/SqliteRelationalConnectionTest.cs
test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs

Microsoft.Data.Sqlite: Add Default Timeout connection string keyword

---

src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs

Microsoft.Data.Sqlite: Enable GetFieldValue<Stream>() and TextReader

---

src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationsSqlGeneratorTest.cs

Fixes #23621
When rebuilding table on SQLite (required for [certain schema changes](https://docs.microsoft.com/ef/core/providers/sqlite/limitations#migrations-limitations); this is a new feature in 5.0) we create an INSERT..FROM statement to copy data from the old table to the new one. However, we missed quoting the table name.
Because the name isn't quoted, some tables can't be rebuilt. For example, this includes tables containing spaces in the name or ones matching a SQLite keyword (like GROUP).
Customer reported on 5.0.0
We have tests asserting against baseline SQL, but failed to carefully review the SQL for quotes. The baselines have been updated to catch regressions.
No. Table rebuilds are new in EF Core 5.0; the operation would have failed previously.
Very low. We quote table and …

[5.0.2] SQLite Migrations: Quote table names in FROM clause during rebuilds

---

src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs

Fixes #23516
When creating the properties to use for the foreign key the conventions could use them to configure the current foreign key before the explicit configuration is applied. However this removes the foreign key currently being configured from the model resulting in an extra foreign key created to compensate this.
This only manifests itself when using a property not already present on an entity type. This situation is common when configuring the join entity type for the new 5.0 feature - many-to-many. There's no straightforward workaround for this.
**How found**
No, this existed in 3.1.x, but it's more likely to be hit in 5.0 when using …

[5.0.2] Delay conventions when creating the properties to use for the foreign key

---

src/EFCore/Metadata/Conventions/CascadeDeleteConvention.cs
test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs

Fixes #23555
If the OnDelete behavior is configured explicitly `CascadeDeleteConvention` could stop other conventions that react to the requiredness changing from running.
Calling `IsRequired` after `OnDelete` will produce a foreign key with nullable properties. The workaround is to flip the order of the calls. However, customers may miss that their model is building incorrectly, and hence get unexpected results which will be hard to track to this issue.
**How found**
Yes
**Risk**
Low. There's only one convention that would be affected by this.

[5.0.2] Don't stop ForeignKeyRequirednessChanged conventions prematurely

---

src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs

Fixes #23479
The columns for required properties on required sharing dependents were assumed to be required, but this is incorrect when the owner is a derived type in TPH. All properties of derived types in TPH must be nullable (not required) since instances of other types do not have values for that column.
The migrations created for such a model would need to be fixed manually each time they are generated.
**How found**
No, required sharing dependents are new in 5.0
**Risk**
Low. Only affects required sharing dependents

[5.0.2] Calculate correct nullability for required sharing dependents on derived types in TPH

---

src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
test/EFCore.Cosmos.Tests/ModelBuilding/CosmosTestModelBuilderExtensions.cs
test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
test/EFCore.Tests/ModelBuilding/TestModel.cs

Fixes #23476
The PK on the join entity type is usually created by a convention from the FKs to the related types. However composite FKs might be sharing a property resulting in an exception if it's specified twice for the PK.
The users will get an exception when configuring many-to-many relationship in the case above and the workaround is awkward since the conventions run before user configuration.
**How found**
No, this only affects many-to-many, which is new in 5.0
**Risk**
Low. Only affects a new feature in 5.0

[5.0.2] Avoid duplicate properties when discovering the PK on the join entity type

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs

Fixes #23639
Fixes #23641
When diffing foreign keys we compare make sure that the principal columns haven't changed, but for excluded principal tables we didn't have this information since they were never diffed.
Users witch excluded principal tables in the model will always get redundant changes when adding a migration, even if the model hasn't changes
**How found**
Customer reported on 5.0.1
No, this only affects excluded tables, which is new in 5.0
**Risk**
Low. Only affects a new feature in 5.0

[5.0.2] Diff FKs to excluded tables correctly

---

src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
test/EFCore.InMemory.FunctionalTests/F1InMemoryFixture.cs
test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
test/EFCore.InMemory.FunctionalTests/OptimisticConcurrencyInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/F1RelationalFixture.cs
test/EFCore.Relational.Specification.Tests/PropertyEntryTestBase.cs
test/EFCore.Specification.Tests/DatabindingTestBase.cs
test/EFCore.Specification.Tests/F1FixtureBase.cs
test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
test/EFCore.Specification.Tests/SerializationTestBase.cs
test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/F1SqliteFixture.cs

Fixes #23527
Also fixes #12436 (MQ issue to add more testing for ulong concurrency tokens)
The fix is to ensure the current value is converted to the model type before comparing.
This is a regression from 3.1 where using a concurrency token with a value converter throws in the in-memory database. This is becoming more common since its much nicer to deal with a `ulong` in your code than it is to deal with an `byte[8]`.
This is regression from 3.1 such that customers using this pattern for testing see their tests fail.
**How found**
We were lacking test coverage for this pattern, as indicated by #12436, which was in my list to do for MQ, but is now done as part of this PR.
Yes, from 3.1. …

[5.0.2] Handle concurrency tokens with conversions in the in-memory database

---

src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
src/EFCore/Internal/ManyToManyLoader.cs
src/EFCore/Query/IncludeExpression.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.Expressions.cs
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs

Fixes #23475
This is a targeted patch fix which special cases many-to-many loading. I will file an issue for a more general solution using an appropriate general update to query. See #22022.
This is a bug in many-to-many relationships, a major new feature in EF Core 5.0. When loading a collection navigation property, the inverse navigation property is marked as loaded. This is not correct, since only entities related to the source entity are loaded. This means that attempting to load the inverse is a no-op because it is already marked as loaded, and hence data is missing in the context.
Related entities are not loaded from the database when they should be, leading to possible data corruption in an application that assumes this is working correctly. This …

[5.0.2] Stop marking the inverse navigation as loaded when loading a many-to-many navigation

---

src/EFCore.SqlServer/Query/Internal/SqlServerByteArrayMethodTranslator.cs
src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteByteArrayMethodTranslator.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/MonsterFixupTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs

SqlServer: Translate ArrayAccess/First over byte[]

---

src/EFCore.Abstractions/PrecisionAttribute.cs
src/EFCore.Abstractions/Properties/AbstractionsStrings.Designer.cs
src/EFCore.Abstractions/Properties/AbstractionsStrings.resx
src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
src/EFCore/Metadata/Builders/IConventionPropertyBuilder.cs
src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
src/EFCore/Metadata/Conventions/PrecisionAttributeConvention.cs
src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
test/EFCore.Tests/Infrastructure/AnnotationTest.cs
test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs

Fix https://github.com/dotnet/efcore/issues/17914

Support Precision Attribute

---

test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs

Fix to #21049 - Test: Consider adding Include tests with smaller datasets

---

test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs

Re-enable flaky CI tests on SqlServer on Ubuntu

---

test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalFixture.cs
test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/ComplexNavigationsModel/ComplexNavigationsData.cs
test/EFCore.Specification.Tests/TestUtilities/ExpectedQueryRewritingVisitor.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

Building the mapping when we generate the expected data, so we also have access to navigations and entities for shadow navigations in the future.
Discriminators are added at the test class level since we use same expected data setup for TPH and TPT.
Fixes #19994

Fix to #19994 - Query/Test: figure out how to represent shadow properties in expected result queries

---

test/EFCore.OData.FunctionalTests/Query/NorthwindODataContext.cs
test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTestFixture.cs
test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTests.cs
test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs

Adding custom routing for OrderDetailsController
Fixes #23063

Fix to #23063 - Query/OData: add test support for models requiring non-standard routing (e.g. "Order Details" table in Northwind)

---

src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
src/Microsoft.Data.Sqlite.Core/Utilities/AllowNullAttribute.cs
src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj

I mean, even *I* still want to use this on .NET Framework (in a VS extension) and Unity...

Microsoft.Data.Sqlite: Target .NET Standard 2.0 again

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs

When comparing something to bool constant, which is later negated we now flip the constant true -> false and false -> true, rather than flipping the operation from == to !=
Fixes #23472

Fix to #23472 - !boolean in query should convert to boolean == false rather than boolean != true where possible

---

eng/helix.proj

Sometimes you just need more time
SqlServer functional tests in ubuntu are timing out intermittently by hitting half an hour mark.

Try to fix build failures in SqlServer ubuntu run

---

src/EFCore.Relational/Metadata/Builders/DbFunctionBuilder.cs
src/EFCore.Relational/Metadata/Builders/IConventionDbFunctionBuilder.cs
src/EFCore.Relational/Metadata/IConventionDbFunction.cs
src/EFCore.Relational/Metadata/IDbFunction.cs
src/EFCore.Relational/Metadata/IMutableDbFunction.cs
src/EFCore.Relational/Metadata/Internal/DbFunction.cs
src/EFCore.Relational/Metadata/Internal/InternalDbFunctionBuilder.cs
test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerFixture.cs

Makes it easier to access the args via indexer rather than doing link over it, e.g. args[2], rather than args.Skip(2).First()
Fixes #23565

Fix to #23565 - Consider changing function mapping HasTranslation args from IReadOnlyCollection to IReadOnlyList

---

test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyContext.cs
test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingGeneratedKeysSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/ManyToManyTrackingProxyGeneratedKeysSqlServerTest.cs

This is a precursor to fixes for #23659, #23787. This test has no product changes, it just refactors the many-to-many tests so that they can be run with generated key values, as well as running with explicit keys values like they currently do. Generated keys result in more work being done in fixup by navigations, which is where both of these issues live.
Once this is merged I will send out separate PRs to fix the two bugs.

[5.0.3/Tests only] Updates many-to-many change tracking tests to work with generated key values

---

src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Migrations/Operations/AddForeignKeyOperation.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs

`MigrationsSqlGenerator` expects `PrincipalColumns` to be `null`, not a `null` element.

Fix unexpected null in principal columns of foreign key

---

src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs

Handle composite keys in SqliteDataReader.GetStream()

---

src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs

Previously, the default mode (usually Serialized) was used. Since ADO.NET connections are generally not thread safe, this caused unnecessary lock checking in SQLite.
~~Note, this will break compatibility with versions compiled with SQLITE_THREADSAFE=0. However, we plan to add a connection pool in this release which, I suspect, will also break compatibility with those versions anyway.~~ (Updated)
Resolves #22330

Microsoft.Data.Sqlite: Use multi-thread mode

---

benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
src/EFCore.Sqlite/EFCore.Sqlite.csproj
src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs

Part of aspnet/Microsoft.Data.Sqlite#443
Could also be used by #19599
cc @ericsink

Microsoft.Data.Sqlite: Support GetSchema("ReservedWords")

---

benchmark/Directory.Build.props
benchmark/EFCore.Benchmarks/EFCoreBenchmarkRunner.cs

Without the new BDN version the current benchmarks fail (on net5.0).
It's also removing all the extraneous configuration that is not necessary anymore.

Fix benchmarks

---

src/EFCore.Relational/Query/ISqlExpressionFactory.cs
src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
src/EFCore.Relational/Query/SqlExpressionFactory.cs

Since #23381, UDFs which have a null schema cause a SqlFunctionExpression with BuiltIn=true to be created. This causes incorrect SQL generation.
(SqlServer isn't affected because of SqlServerDbFunctionConvention, which sets the schema of all non-builtin UDFs with a null schema to dbo)

Allow schema-less UDFs to not be built-in

---

benchmark/EFCore.Benchmarks/EFCoreBenchmarkRunner.cs

Add MemoryDiagnoser and OpsPerSecond back to benchmark config

---

test/EFCore.Relational.Specification.Tests/TPTTableSplittingTestBase.cs
test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
test/EFCore.Specification.Tests/ComplianceTestBase.cs
test/EFCore.Specification.Tests/NonSharedModelTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
test/EFCore.Specification.Tests/TestUtilities/TestStore.cs
test/EFCore.Specification.Tests/TestUtilities/TestStoreIndex.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs

Refactor QueryBugsTest to use a non-provider specific way to configure the contexts

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

When comparing composite key entities we were comparing the constituent keys and combining them with AndAlso. For not equal comparison we were still comparing the keys using !=, but we didn't flip the combining operator to OrElse.
Fixes #23779

[5.0.3] Fix to #23779 - TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey

---

src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs

When comparing composite key entities we were comparing the constituent keys and combining them with AndAlso. For not equal comparison we were still comparing the keys using !=, but we didn't flip the combining operator to OrElse.
Fixes #23779

Fix to #23779 - TryRewriteEntityEquality and NotEqual comparison of CompositePrimaryKey

---

src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs

Resolves #20404
When using enum value in a Cosmos query, the query throws rather than giving results back.
Customers are unable to run queries which need to use enum values. There is no work-around.
**How found**
Reported my multiple customers on 3.1. We made a similar patch fix for relational providers, and based on feedback we are now bringing this for Cosmos as well.
Added test specifically for queries similar to customer queries. Also enabled existing tests which were using enums but were failing earlier.
Not that we know of.
**Risk**
Low. We are backporting existing fix which went in 5.0 release and has no reported issues with it so far.

[3.1.x] Query: Cosmos: Generate enum literal/parameter correctly

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs

Fixes #23456, replaces #23847
When generating the model snapshot for migrations, provider extension method calls generated for certain annotations are ambiguous across providers. This change replaces these ambiguous calls will direct reading of the associated metadata attribute, which was what we generated before 5.0, and is what we still generate for unknown annotations.
When both SQL Server and Npgsql are used, fluent API calls are mismatched, leading to incorrect migration logic. Specifically, the same migration code is scaffolded again and again because the previous code doesn't work correctly. (Note that most cases cause compiler warnings. However, for some attributes there are different numbers of parameters on the extension methods, which causes …

[5.0.3] Don't generate Fluent API in model snapshot for certain annotations

---

src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/DbContext.cs
src/EFCore/Infrastructure/EntityFrameworkEventSource.cs
src/EFCore/Storage/ExecutionStrategy.cs
test/EFCore.Tests/EventSourceTest.cs
test/EFCore.Tests/Storage/ExecutionStrategyTest.cs

Fixes #23630
Three event counters don't get updated when the async API is used (as opposed to the sync one). An additional event counter is incorrectly updated, and so show wrong results.
Our newly-introduced event counters show incorrect data which does not take into account async calls.
**How found**
Customer reported an issue on 5.0.0 with one counter, the rest discovered via due diligence.
Test coverage added after investigation and discussion of the best way to do it. We settled on using reflection to access the counters and then configuring the tests to not run in parallel. These tests are both for detecting regressions, and so that going forward we can test new event counters to avoid mistakes like this in the future. …

[5.0.3] Fix event counter issues and add test patterns for event source testing

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs

Resolves #23759
Relational providers have `AsSingleQuery` operator to evaluate query in single SQL scenario. The queryable method only exist for relational providers but when using InMemory provider for testing (multiple providers in same app scenario), the method throws translation error since InMemory provider doesn't understand the method. In 5.0, we added code to skip `AsSplitQuery` this is similar method on the flipside.
Customers who are using `AsSingleQuery` in their production code and using InMemory provider for testing will see test failures.
**How found**
Customer reported on 5.0.1.
Manually verified. No test projects contains relational and inmemory provider together.
No, AsSingleQuery is operator introduced …

[5.0.3] InMemory: Skip over AsSingleQuery method

---

src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs

Fixes #23794
When generating migrations, if a database collation is configured and non was previously configured, a mangled migration is generated which does not compile.
Any user trying to explicitly set a collation on an existing database will fail and would have to manually edit generated migration source code.
**How found**
Customer reported on 5.0.2.
We have added test coverage in this PR.
No, collation support was only introduced in 5.0.
**Risk**
Low. Only affects the faulty code path, which is part of design-time migration generation (no runtime impact).

[5.0.3] Fixes to database collation migrations

---

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs

Fixes #23659
If we encounter an un-mapped entity during graph discovery of Attach, etc., then that entity is put aside for delayed fixup when it later becomes tracked. In this delayed fixup we were not populating skip navigations. The fix is to do this, just like happens in non-delayed fixup.
Many-to-many navigations that use store-generated keys are not populated correctly when a join entity is tracked. This makes it appear to the application as if the two objects are not related.
**How found**
This only happens when using store-generated keys, for which we were missing some many-to-many coverage. A previous PR added that coverage, and this PR contains a new test for this specific case.
No; …

[5.0.3] Set skip navigations in delayed fixup

---

src/EFCore.Relational/Migrations/MigrationBuilder.cs
test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs

Fixes #23503
**Note for Tactics**
This was rejected for 5.0.2 due to concerns that it might not impact many customers. We now have multiple customer reports (4+) so we're brining it back for 5.0.3.
`MigrationBuilder.InsertData` was not passing through the column types parameter to the underlying method.
Creating a migration that adds data to a table that is not mapped in the model will fail. The workaround would be to use internal API.
**How found**
No, this overload of `InsertData` is new in 5.0
**Risk**
Low. Only affects new API that is seldomly used.

[5.0.3] Flow through the column types in MigrationBuilder.InsertData

---

src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs

Fixes #23668
`ModificationCommand.EntityState` is used in many places throughout `CommandBatchPreparer` and in most cases it is the same as `IUpdateEntry.EntityState` for the corresponding entry, however when adding an optional dependent to an existing row `ModificationCommand.EntityState` is `Modified` while `IUpdateEntry.EntityState` is `Added`
Adding an optional dependent that is referencing a newly added principal entity or deleting both of them can result in a SQL error as the operations aren't ordered correctly. A workaround would be to call `SaveChanges` immediately after the first operation that should be performed, but this isn't feasible in some scenarios.
**How found**
Customer reported on 5.0.1.
We have added more test …

[5.0.3] Use IUpdateEntry.EntityState instead of ModificationCommand.EntityState for entities using table splitting.

---

src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs

Fixes #23672
`GetColumnNames(StoreObjectIdentifier)` returns `null` for properties that are not mapped to the specifier store object. However `GetDefaultName()` didn't account for this.
User models that use table splitting and have FKs to other table will result in an unhelpful `ArgumentNullException`. A workaround would be to specify the key and index store names explicitly, but this would be unfeasible for large models as the exception doesn't provide information on which are the offending ones.
**How found**
Customer reported on 5.0.1.
Yes
**Risk**
Low. This just adds two `null` checks.

[5.0.3] Add column name null checks in default FK and PK name calculation

---

src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs

We have optimization for EXISTS, that returns false when the subquery has a predicate which filters out all the rows. In such case we return constant false. However, ExistExpression also stores information about it being negated or not (i.e. EXISTS vs NOT EXISTS).
If the Exists expression is negated and the predicate filters out all the rows we should return true instead.
Fixes #23617

[5.0.3] Fix to #23617 - IQueryable.All evaluate to false with predicate _ => true

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs

Resolves #23593
Using enums as key selector for joins throws exception. Same could happen for any other type which uses `object.Equals` for value comparison.
In 5.0 EF Core started applying value converter to server side for InMemory database. Some of the scenario where value comparer is default (but not == operator) are broken which were working. There is no work-around.
**How found**
Customer reported issue on 5.0.0
Added test coverage for using enums as key in joins in different construct of key selectors.
Yes, this query worked correctly in 3.1 since InMemory didn't handle value converters/comparers
**Risk**
Very low, It adds additional pattern matching for expression of shape `object.Equals` existing working …

[5.0.3] InMemory: Decompose join condition which uses equals for comparison

---

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs

Fixes #23787
If skip navigations are detected to have values on a newly tracked entities, then these values need to be added to the relationship snapshot so that DetectChanges does not re-detect them. This is not happening for one path with store-generated keys.
In most cases this has no impact, as DetectChanges catches up when it first runs. However, if changes are made to the graph before this happens, and if the entities have store-generated keys, then this can result in a change not being detected and hense an incorrect update to the database.
**How found**
This only happens when using store-generated keys, for which we were missing some many-to-many coverage. A previous PR added that coverage, and this PR …

[5.0.3] Set relationship snapshot correctly for skip navigations

---

test/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs

Issue is by design, will clean up procedural test generation at some point in the future

[TINY] Removing references to #12591 from the procedural test generation

---

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs

Fixes #23792
Migrations compared seed data based on the column information, meaning that data was matched as long as the values were mapped to the same columns and in the case of table sharing in some cases this caused data to be mismatched between different entity types. And if one of the types has a read-only property (an alternate key) this results in the row being deleted and inserted again unnecessarily.
A migration for a model that matches the above condition will always contain operations even if the model hasn't changed. There is no workaround other than removing the read-only properties or manually fixing the migrations.
**How found**
Customer reported on 5.0.1.
Yes. …

[5.0.3] Correctly distinguish between seeds for different owned types

---

src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
src/EFCore.Relational/Update/ModificationCommand.cs
src/EFCore/ChangeTracking/ValueComparer`.cs
src/EFCore/Internal/InternalDbSet.cs
src/EFCore/Metadata/INavigation.cs
src/EFCore/Metadata/INavigationBase.cs
src/EFCore/Metadata/ISkipNavigation.cs
src/EFCore/Metadata/Internal/EntityType.cs
src/EFCore/Metadata/Internal/Index.cs
src/EFCore/Metadata/Internal/Key.cs
src/EFCore/Metadata/Internal/Navigation.cs
src/EFCore/Metadata/Internal/PropertyBase.cs
src/EFCore/Metadata/Internal/SkipNavigation.cs
src/EFCore/Metadata/ServiceParameterBinding.cs
src/EFCore/Query/Internal/CompiledQueryBase.cs
src/EFCore/Storage/CoreTypeMapping.cs
src/EFCore/Storage/ValueConversion/ValueConverter`.cs
src/Shared/NonCapturingLazyInitializer.cs

* Fixed several cases where our initialization was capturing (so spurious memory allocations). Added C# 9 static everywhere to reduce the risk of this happening again.
* Fixed one case where a nullable value was being lazily generated, defeating the initialization mechanism (because NonCapturingLazyInitializer compares to null to see if a value has been generated). This meant every invocation would re-generate again and again. Discovered during NRT annotations - doing this won't compile any more after that's done.

Fix capturing uses of NonCapturingLazyInitializer

---

src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs
src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs

We do optimization which combines comparisons based on the same property into IN and NOT IN. Problem is that if the comparisons contain nulls, we add those into the list of IN values, generating queries like  a IN (1, 2, NULL). In normal circumstances, during null semantics processing we extract these nulls and produce correct IS NULL / IS NOT NULL calls, however when useRelationalNulls is enabled, we don't run null semantics visitor and therefore don't "fix" the IN expressions.
Fix is to only apply the initial optimization for c# null semantics.
Fixes #23761

Fix to #23761 - UseRelationalNulls causes subquery to include NOT IN (NULL, x)

---

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
src/EFCore.Relational/Migrations/MigrationBuilder.cs
src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
src/EFCore/ChangeTracking/Internal/NavigationFixer.cs

Remove quirks from main

---

src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs

Don't leave unknown FK values when principal is known but has not-set, non-generated, value

---

src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.resx
src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs

Sometimes you just got to do a "good first issue" on a Saturday morning.
This should be useful with TPH mapping.
Closes #8023

Support for SQL Server sparse columns

---

test/EFCore.AspNet.Specification.Tests/AspNetIdentityCustomTypesDefaultTestBase.cs

Checks that skip navigations can be layered over the existing model; see #23951.

Add many-to-many mapping for Identity Users/Roles relationship

---

src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs

Correctly reflect that SnapshotModelProcessor now depends on IModelRuntimeInitializer instead of IConventionSetBuilder
This is blocking preview-1 branching

[small] Fix migration dependencies

---

src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
src/EFCore.Relational/Query/Internal/StringMethodTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs

This PR fixes #23859 by adding support for three and four string argument versions of [String.Concat](https://docs.microsoft.com/en-us/dotnet/api/system.string.concat?view=net-5.0).

Add support for three and four string argument versions of System.String.Concat

---

src/EFCore/ChangeTracking/Internal/StateManager.cs
src/EFCore/DbContext.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Preserve synchronization context in SaveChangesAsync

---

src/EFCore.Relational/Query/SqlExpressions/SqlUnaryExpression.cs

Small fix in SqlUnaryExpression::Print
Fixes #23985

Fix mistake in SqlUnaryExpression::Print

---

src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs

Resolves #23926
Issue:
- For TPH hierarchy, we generate conditional value read expression for derived property using ConditionalExpression
- To check the right derived type we use value comparer on discriminator column in ConditionalExpression.Test
- For enum discriminator the value comparer uses `object.Equals` methods which requires converting all args to object using UnaryExpression. (This could happen for non-enums too in some cases)
- When reading right side of properties in left join we convert all of those read access to nullable which causes operand of unary to be nullable type. The base visitor does not allow this type change
Hence we need to override the method and allow for conversion to happen since we expect it.
Doing left join with entity hierarchy on right …

[release/5.0] InMemory: Allow UnaryExpression.Operand to be converted to nullable for LeftJoin

---

src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs

Fixes #23889
AddPooledDbContextFactory (new in 5.0) has a parameter to set the pool size. This value was not being passed down to lower-level config and hence the default pool size is always used.
The pool size cannot be changed when using the 'AddDbContext' for a factory and pooling.
**How found**
The test factoring did not test the defaults or overridden values for pool size; this has been added.
No; new feature in 5.0.
**Risk**
Very low.

Correctly set pool size when using AddPooledDbContextFactory

---

eng/helix.proj

Re-enable SqlServer on helix

---

src/EFCore.SqlServer/Storage/Internal/SqlServerSqlVariantTypeMapping.cs
test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Regarding issue #12482 
Currently when batch inserting values into a sql_variant column each DbParameter will resolve its own SqlDbType. This results in invalid sql and will therefore throw an exception
This pull request passes DbType.Object for any parameter targeting a variant column so that each DbParameter will map into the SqlDbType sql_variant instead, making the batch insert possible.
This is my first time working with this repository so please let me know if something is missing or if more tests are required

#12482 Fix batch inserts using with different types on a sql_variant column

---

src/EFCore/DbContext.cs
src/EFCore/Internal/DbContextLease.cs

This avoids recalculating the services which need to be reset every time a pooled DbContext is disposed.
This gets us from 74,621 RPS -> 77,231 (3.4% improvement)

Cache ResettableServices for DbContext pooling

---

src/EFCore.Relational/Query/QuerySqlGenerator.cs
src/EFCore/Infrastructure/IndentedStringBuilder.cs

Remove redundant string allocation in IndentedStringBuilder.DoIndent. Stringbuilder already has a Append(char, repeat) implementation.
Change a couple of string concats to stringbuilder append for consistency with other parts of the code. Performance difference seems to be neglectable

Minor stringbuilder cleanup in QuerySqlGenerator

---

src/EFCore/DbSet.cs
src/EFCore/Internal/InternalDbSet.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs

Fixes #24041
Some compat notes:
* `await foreach` works fine, even if LangVersion is set to 7.0. Am not sure if this is because the SDK is new - if so, then new SDKs are required to build anything depending on EF Core 6.0 anyway (since we target net5.0).
* ToListAsync and friends work fine because they're over IQueryable

Remove IAsyncEnumerable from DbSet

---

src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
tools/Resources.tt

On a local 30k iteration Fortunes run, allocations were reduced from 2.5M instances (153.21MB) to 2.23M instances (146.99MB) (10% reduction in instances, 4% in bytes).
Interestingly, no discernible effect on RPS throughput at the perf lab. The GC must be doing its job quite well.

Stop capturing in logging

---

src/EFCore/Storage/ExecutionStrategy.cs

Using recursive generics with nested type parameters will make AOT compilers impossible to complete compilation, because all methods and types need to be resolved at compile-time, but compiler has no way to know how many levels of recursion need to be expanded. 
In this PR, I made the type of `operation` and `verifySucceeded` in `ExecuteImplement` and `ExecuteImplementAsync` be same to avoid recursive generics call with `TResult = ExecutionResult<TResult>`. It's a better way to fix the issue than previously attempt #20494 and won't affect maintainability and introduce any public API changes.
Fixes #20393

Fix infinite recursive generics

---

src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs

Add translator for string.ToLower()
Issue #16143
Please review.

Cosmos: Add translator for ToLower method which map to LOWER built-in function

---

src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs

Add translator for string.ToUpper()
Issue #16143
Related to ToLower PR: #24203
Please review.

Cosmos: Add translator for ToUpper method which map to UPPER built-in function

---

src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

Fixes #23271 
New test `Query_reusing_parameter_with_inner_query_doesnt_declare_duplicate_parameter` added to verify solution.
Other tests modified since constants are now kept for lambdas and not reused from earlier top-level expressions.
All tests pass locally.

Keep parameter names for inlined queries

---

src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs

Add translator for TrimStart/TrimEnd/Trim methods which map to LTRIM/RTRIM/TRIM built-in functions
Issue #16143
Please review.

Cosmos: Add translator for TrimStart/TrimEnd/Trim

---

src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Relational/Update/Internal/BatchExecutor.cs
src/EFCore/Storage/ExecutionStrategy.cs
src/EFCore/Storage/ITransactionEnlistmentManager.cs

Accessing `Transaction.Current` (in HandleAmbientTransactions) is a heavy operation - profiling shows it to take around 0.3% of the total running time.
Npgsql has connection string parameter to disable this check at the ADO level. Allowing providers to override HandleAmbientTransactions would allow EFCore.PG to skip this if the parameter is set.
HandleAmbientTransactions isn't a great name for a publicly-exposed method, but I don't really have anything better...

Allow providers to override ambient transaction access

---

src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
test/EFCore.OData.FunctionalTests/Query/ODataQueryTestFixtureInitializer.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs

Problem was that during query optimization, TryOptimizeMemberAccessOverConditional could change the type of the expression (from non nullable to nullable), which then would throw when trying to re-construct the expression tree upstream.
Fix is to change the type to the original as part of TryOptimizeMemberAccessOverConditional.
Fixes #23877

Fix to #23877 - Odata $filter and $orderby not working with Select to new DTO for one to one relationship

---

src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs

Added InvalidOperationException to xml docs for MaxAsync method
Fixes #24242

Documented InvalidOperationException to MaxAsync method

---

src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs

Add translator for `string.Substring()`
Issue #16143
Please review.

Cosmos: Add translator for Substring method which map to SUBSTRING built-in functions

---

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs

Fix default constraint logic in SQL Server migrations

---

src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
src/EFCore.Relational/Storage/IRelationalCommand.cs
src/EFCore.Relational/Storage/IRelationalConnection.cs
src/EFCore.Relational/Storage/RelationalCommand.cs
src/EFCore.Relational/Storage/RelationalConnection.cs
src/EFCore.Relational/Storage/RelationalConnectionDependencies.cs
src/EFCore.Relational/Storage/RelationalDataReader.cs
test/EFCore.Relational.Tests/RelationalEventIdTest.cs
test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs
test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs
test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs

Reduces query allocations by around 10% (both instance numbers and total bytes).
This causes the following to be recycled:
* All the stopwatches
* RelationalCommand
* RelationalDataReader
* DbConnection
... plus various other tidbits.
* DbCommand (and dependencies) is notably excluded since I plan to implement that at the ADO layer (cache inside NpgsqlConnection).
* I can also do RelationalTransaction in a later PR.
@AndriySvyryd @smitpatel would be good to get your eyes on this, some touchy changes.
See #24206

Recycling relational and ADO.NET objects in query pipeline

---

src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs

Removes a lot of unnecessary allocations and conversions from utf8
Fixes #16202
Here are some rough numbers from the Mixed Update Pipeline EF Core benchmark:
|        |     Mean |     Error |   StdDev |  Op/s |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|------- |---------:|----------:|---------:|------:|-----------:|----------:|----------:|----------:|
| Before | 660.5 ms | 151.77 ms |  8.32 ms | 1.514 | 28000.0000 | 8000.0000 | 1000.0000 | 135.14 MB |
| After  | 628.8 ms | 167.3 ms  |  9.17 ms | 1.590 | 25000.0000 | 7000.0000 | 1000.0000 | 132.73 MB |

Microsoft.Data.Sqlite: Use Span overload of sqlite3_prepare

---

NuGet.config

- remove remaining way user NuGet.config can infect builds

[release/3.1] Clear disabled package sources

---

src/EFCore/Query/QueryableMethods.cs
src/Shared/EnumerableMethods.cs

Resolves #24002
As per https://github.com/dotnet/runtime/issues/28776, there are new queryable/enumerable method overloads of existing methods are being added. We use reflection to get some of the methods which EF Core translates and uses in generating result. Those new overloads could cause error in finding correct method.
Customers won't be able to use EF Core 3.1 on net6 platform.
**How found**
Indicated on API proposal by customers.
Whole query pipeline uses both classes so any error in reflection will cause all query tests to fail due to type initialization error.
No. This is to make code forward-compatible for platform.
**Risk**
Very low. All tests verify that current code for reflection is correct. Comparison …

[release/3.1] Query: Use stronger reflection in Queryable/Enumerable methods (#24090)

---

src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
src/EFCore.Relational/Properties/RelationalStrings.resx
src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindGroupByQueryInMemoryTest.cs
test/EFCore.InMemory.FunctionalTests/Query/NorthwindMiscellaneousQueryInMemoryTest.cs
test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindGroupByQueryRelationalTestBase.cs
test/EFCore.Relational.Specification.Tests/Query/NorthwindSelectQueryRelationalTestBase.cs
test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs

As fix to #15873 we started blocking some scenarios that used to work (by accident) - when we have a subquery using Distinct or GroupBy that doesn't happen to have any duplicates.
Fix is to enable those scenarios (and others) by modifying identifier columns in case of distinct and group by, if the original identifiers are not already present. In case of distinct, the entire projection becomes unique identifier, as distinct guarantees it to be unique.
In case of groupby, the grouping key becomes the identifier - since we only support grouping key or group aggregate in the projection, we are also guaranteed to have 1 row per unique grouping key.
Also fix to #24288 - Query: add collection join tries to convert correlated collection from APPLY to JOIN for subqueries with Distinct and GroupBy, …

Fix to #22049 - Query: consider updating select expression identifiers when projecting a subset of column and adding distinct

---

src/EFCore/Query/QueryableMethods.cs
src/Shared/EnumerableMethods.cs

Resolves #24002
As per https://github.com/dotnet/runtime/issues/28776, there are new queryable/enumerable method overloads of existing methods are being added. We use reflection to get some of the methods which EF Core translates and uses in generating result. Those new overloads could cause error in finding correct method.
Customers won't be able to use EF Core 5.0 on net6 platform.
**How found**
Indicated on API proposal by customers.
Whole query pipeline uses both classes so any error in reflection will cause all query tests to fail due to type initialization error.
No. This is to make code forward-compatible for platform.
**Risk**
Very low. All tests verify that current code for reflection is correct. Comparison …

[release/5.0] Query: Use stronger reflection in Queryable/Enumerable methods

---

src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs

Port of 6.0 fix https://github.com/dotnet/efcore/pull/23875 to 5.0 release.
Fixes #23730
An exception is thrown when no key value is set for a non-generated key of an owned type. Normally this is a negative case since non-generated key values must be explicitly set. However, this can works when the non-generated value is part of a composite key for which other parts of the key are generated. In this case, the non-generated part can have the same default value for multiple inserts without violating the primary key constraint.
This is a regression for the case described above. There is no reasonable workaround.
(We already fixed this for EF Core 6.0, but decided not to patch since it seemed to be a regression only in a negative case. Since then other …

[5.0.x] Don't leave unknown FK values when principal is known but has not-set, non-generated, value

---

src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs

Fixes #24221
An exception is thrown when comparing key values of different types for deleted entities. This code was added in 5.0.0 to delete the entities in the correct order relative to inserted entities.
Deleting entities with different key types always throws an exception, and this is a fairly common scenario.
A workaround would be to delete entities one by one, but this isn't possible in all scenarios.
**How found**
Test coverage for this case has been added in this PR.
Yes, from EF Core 3.1.
**Risk**
Low. This code has good test coverage aside from the above scenario. Also quirked.

[release/5.0] Don't compare values from different keys for deleted entities

---

src/EFCore/Diagnostics/CoreEventId.cs
src/EFCore/Diagnostics/CoreLoggerExtensions.cs
src/EFCore/Diagnostics/LoggingDefinitions.cs
src/EFCore/Properties/CoreStrings.Designer.cs
src/EFCore/Properties/CoreStrings.resx
src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs

Resolves #23674
When walking up the include tree to add more navigations, includes are walk back paths are dropped. 
Customers who wrote query by walking back include tree will not get results included. Earlier this was incorrect results from relationship fixup. Now it won't give results to user what they would expect. The scenario is negative case and should be blocked but currently silently ignored without informing user of possible error.
**How found**
Test coverage for this case has been added in this PR.
No.
**Risk**
Low. This code has good test coverage for all possible variations. It also adds only a warning message.

[release/5.0] Warn for walking back up the Include tree

---

src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs

Add Ordinal and Name Caching to SqliteDataRecord
This speeds up repeated ordinal and Name access, while having probable negligible effect on existing queries to GetName(int) or GetOrdinal(string). 
Fixes #24140
This is my first PR, please guide me if there is anything I must do to improve the submission 👍

Add Caching to SqliteDataRecord for Ordinal and Name 

---

src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs

Added InvalidOperationException to xml docs for:
- ~LastOrDefaultAsync~
- ~AverageAsync~
- MinAsync
Fixes #24307

Documented InvalidOperationException for QueryableExtensions methods

---

test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs

Explicit order in case the database returns the records in different order (i.e. Firebird returns different order).

Explicit order in case the database returns the records in different order.

---

src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
src/EFCore/Metadata/MemberIdentity.cs

Following discussion in https://github.com/dotnet/efcore/pull/23381#discussion_r597171187

Obsolete MemberIdentity.IsNone()
