- test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> Update SQL baselines

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
Part of #17337
This commit doesn't make any functional change. Just moved code around for better organization and made certain private functions local static functions
> Query: Re-organize SelectExpression

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSelectQuerySqliteTest.cs
- Don't apply Include on entities with Include already applied
- Update table references when pushing down select into left for set operation
- Update identifiers after applying set operation if the projection removed exiting identifiers
- Update SQL references in pending collection during push down
Fix for the repro in #17337
Resolves #18738
Resolves #19763
Resolves #19947
Resolves #20813
Resolves #21026
Resolves #22222
Resolves #23676
Resolves #23720
Resolves #24216
> Query: Update column references in pending collections

- src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Metadata/ContextParameterBinding.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/SlimModelConvention.cs
- src/EFCore/Metadata/DependencyInjectionMethodParameterBinding.cs
- src/EFCore/Metadata/DependencyInjectionParameterBinding.cs
- src/EFCore/Metadata/EntityTypeParameterBinding.cs
- src/EFCore/Metadata/Internal/ContextParameterBindingFactory.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/EntityTypeParameterBindingFactory.cs
- src/EFCore/Metadata/LazyLoaderParameterBindingFactory.cs
- src/EFCore/Metadata/ObjectArrayParameterBinding.cs
- src/EFCore/Metadata/ParameterBinding.cs
- src/EFCore/Metadata/PropertyParameterBinding.cs
- src/EFCore/Metadata/ServiceParameterBinding.cs
- src/EFCore/Metadata/ServiceParameterBindingFactory.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Conventions/ServicePropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
Fixes #23968
Service properties are most commonly private. We were missing test coverage for public service properties in a type hierarchy, which was hiding this bug where we detect the property reflected from the base type as a duplicate. Fix is to match duplicates by name.
> Don't detect public service properties in hierarchy as duplicates

- src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
> Microsoft.Data.Sqlite: Add Span overloads to SqliteBlob

- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindStringIncludeQueryTestBase.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
Fixes #24264
The mechanism for changing parameter order does not work for log messages since we pass the string directly to the ASP.NET Log method.
> Fix order of arguments passed to log messages

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/ValueConversion/Internal/StringEnumConverter.cs
- test/EFCore.Tests/Storage/EnumToStringConverterTest.cs
- test/EFCore.Tests/Storage/StringToEnumConverterTest.cs
> Throw when attempting to convert an invalid enum value from the database

- src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs
- src/EFCore.InMemory/Infrastructure/InMemoryDbContextOptionsBuilder.cs
- test/EFCore.InMemory.FunctionalTests/NullabilityCheckInMemoryTest.cs
- test/EFCore.InMemory.Tests/ModelBuilding/InMemoryModelBuilderGenericTest.cs
> Move EnableNullabilityCheck from DbContextOptionsBuilder to InMemoryDbContextOptionsBuilde

- src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- test/EFCore.AspNet.InMemory.FunctionalTests/GrpcInMemoryTest.cs
- test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
- test/EFCore.AspNet.Specification.Tests/GrpcTestBase.cs
- test/EFCore.AspNet.Specification.Tests/ProtoTest.proto
- test/EFCore.AspNet.SqlServer.FunctionalTests/GrpcSqlServerTest.cs
- test/EFCore.AspNet.Sqlite.FunctionalTests/GrpcSqliteTest.cs
- test/EFCore.Tests/Metadata/Conventions/BackingFieldConventionTest.cs
Fixes #23703
At some point we started eagerly throwing when attempting to build a setter delegate. This should be lazy because we don't always need a setter.
Fixes #23901
Detects "propertyName_" as a backing field.
> Tweaks for by-convention mapping of gRPC model

- src/EFCore/DbContext.cs
> Add name parameter to Set overload docs

- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
> Log Cosmos database access at Info level

- test/EFCore.Cosmos.FunctionalTests/OptimisticConcurrencyCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/OptimisticConcurrencyInMemoryTest.cs
- test/EFCore.Specification.Tests/OptimisticConcurrencyTestBase.cs
> Fix Many to Many with optimistic concurrency tests

- src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
An optional dependent considered present
If all non-nullable non-PK properties have a non-null value, or
If all non-nullable non-PK properties are shared with principal then at least one nullable non shared property has a non-null value
If there are no non-shared properties then it is always present and act like a required dependent
Resolves #23564
> Query: Implement optional dependent conditions

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/IForeignKey.cs
- src/EFCore/Metadata/Internal/ForeignKeyExtensions.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
Fixes #23883
This is only relevant for overlapping composite foreign keys, where nulling all FK values can also sever other relationships. Since a composite FK is null if any part is null, we avoid nulling the properties that are also shared with another foreign key.
> Only null non-overlapping FK properties on delete/fixup, if possible

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/INavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerDependencies.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/EntityTwo.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/JoinOneToTwoExtra.cs
- test/EFCore.SqlServer.FunctionalTests/ManyToManyLoadSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/F1SqliteFixture.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Fixes #23339
This stops the change tracker creating a join entity instance for the same join entity that is later discovered in the graph.
> Delay synthesis of join entities until entire graph is attached

- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore/Diagnostics/EntityTypeEventData.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/ChangedChangingMonsterContext.cs
- test/EFCore.Specification.Tests/TestModels/ChangedOnlyMonsterContext.cs
- test/EFCore.Specification.Tests/TestModels/MonsterModel.cs
- test/EFCore.Specification.Tests/TestModels/SnapshotMonsterContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Resolves #23229
Resolves #23198
Resolves #21488
> Warn for optional dependents sharing table without identifying column

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/TestModels/ChangedChangingMonsterContext.cs
- test/EFCore.Specification.Tests/TestModels/ChangedOnlyMonsterContext.cs
- test/EFCore.Specification.Tests/TestModels/MonsterModel.cs
- test/EFCore.Specification.Tests/TestModels/SnapshotMonsterContext.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/FuelTank.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/OperatorDetails.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
> Update exception messages for optional dependents

- src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
- test/EFCore.Relational.Tests/Utilities/DbParameterCollectionExtensionsTest.cs
Note that this will capture any IList, which may be a bit wide (Npgsql supports arrays and generic lists).
> Support arrays in parameters value logging

- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
I love the smell of hacky parsers in the morning...
Don't replace comma with newline in the test parameter logging if they're inside single quotes or curlies.
> Make TestSqlLoggerFactory recognize quoting/curlies

- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Fixes: https://github.com/dotnet/efcore/issues/24590
> Unskip `Double_dispose_does_not_enter_pool_twice` Test

- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingSourceTest.cs
> Allow type mapping source plugins to override built-in mappings

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
> Fix index creation with legacy filter

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateData.cs
- src/EFCore/ChangeTracking/PropertyEntry.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateDataTest.cs
- test/EFCore.Tests/ChangeTracking/TemporaryValuesTest.cs
This allows values explicitly set by the application as temporary to be stored in and obtained from the entity instance.
Fixes #23191
Fixes #24245
> Allow property values to be explicitly flagged as temporary

- src/EFCore/Infrastructure/AnnotatableBase.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Tests/Infrastructure/AnnotatableTest.cs
> Copy instead of reusing the same reference in AnnotatableBase.AddAnnotations

- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
> Tiny: Disable failing Cosmos tests

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
So that we can reference them using column and generate valid SQL
Resolves #19027
Resolves #23432
> Query: Push down into subquery when group by has unallowed terms

- src/EFCore.Relational/Query/Internal/SelectExpressionProjectionApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Also add a visitor to verify that all table references are proper
Update alias unique-fier to skip already visited expression
Fixes #24473
Fixes #24460
> Relational: Make table reference graph mapping consistent

- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
Follow-up to #24606, done because of https://github.com/aspnet/AspNetCore-ManualTests/issues/565
> Improve test coverage fo DateTimeOffset comparer

- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
> Add a test for #23059

- test/EFCore.InMemory.FunctionalTests/Query/OwnedEntityQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OwnedEntityQuerySqliteTest.cs
We can move tests out of QueryBugsTest at some point
Resolves #20277
> Create a provider agnostic test base to put custom models

- src/EFCore/Internal/DbContextFactorySource.cs
- test/EFCore.Tests/DbContextFactoryTest.cs
Fixes #24124
Please check if the PR fulfills these requirements
- Detail 1
- Detail 2
Review the guidelines for [contributing](CONTRIBUTING.md) for more details.
> Handle parameterless constructor in DbContextFactorySource

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
select projecting queryable followed by SelectMany, Join, GroupJoin. Also SelectMany, Join, GroupJoin projecting queryable on top level.
> [SMALL] Adding more tests for #23302 - Query: IQueryable in subquery sometimes triggers validation which prevents IQueryables in the final projection

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
> Using Debug.Fail

- src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> Case insensitive SqliteDataReader. Fixes dotnet/efcore#24011

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
The TableValuedFunctionExpression does not take the IsBuiltIn option into account. This results in brackets being added to build in database functions.
Fixes #24569
> Fix to #24569 - TableValuedFunctionExpression does not take the IsBuiltIn option into account (DbFunctions)

- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
Issue has already been fixed by earlier query pipeline refactoring, adding regression tests
> [SMALL] Adding tests for #24726 - Bug with Take()

- src/EFCore/Infrastructure/AnnotatableBase.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Tests/Infrastructure/AnnotatableTest.cs
Cherry-picking the commit into preview 4.
Fixes #24658
An exception is thrown when generating migration SQL when a property is modified which has both a comment and a default value.
The EF Core Power Tools are broken for reverse engineering/scaffolding.
**How found**
Reported by @ErikEJ, author of the Power Tools, while testing.
The fix was already in preview 5 with test coverage; this PR brings the fix and tests to preview 4.
Yes, from preview 2.
**Risk**
Low. This is a feature bug fix that we are bringing forward.
> Preview 4: Copy instead of reusing the same reference in AnnotatableBase.AddAnnotations

- src/EFCore.Relational/Query/Internal/SingleQueryResultCoordinator.cs
- src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SplitQueryResultCoordinator.cs
- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- src/EFCore/DbContext.cs
- src/EFCore/Query/QueryContext.cs
Reading from virtual properties in a cycle/sequentially is very slow because the compiler can't cache the returned value from the property (because there might be side effects). This pr helps to alleviate this problem for some of the properties (the worst offender is `QueryContext.Context`, which is called every time a new `MaterializationContext` is created, but changing this is not trivial). Below is the benchmark results of reading from fields and properties in a cycle of 10.
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 5 2400G with Radeon Vega Graphics, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=6.0.100-preview.3.21202.5
[Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, CoreFX 6.0.21.20104), X64 RyuJIT
DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.20104, …
```
> Caching access to virtual properties

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryTaggingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Avoid pushdown on top level during split query

- src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteStringMethodTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> Add translations for string.Substring with one arg

- global.json
- test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataQueryTests.cs
- test/EFCore.OData.FunctionalTests/Query/NorthwindODataQueryTests.cs
> Update to .NET SDK 6.0 Preview 3

- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
Uses T-SQL for all raw queries in `FromSqlQueryTestBase` and ensures they are funneled through `NormalizeDelimitersInRawString()`, so provider specific delimiters are applied.
> Consolidate SQL syntax

- Directory.Build.targets
- eng/Version.Details.xml
- eng/Versions.props
- eng/helix.proj
- global.json
> Start flowing Microsoft.NETCore.App

- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
> Move connection probing to CosmosTestStore

- src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
> Cosmos: Filter out the partition key property when it is the same as id

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/ICSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/ICSharpEntityTypeGenerator.cs
- src/EFCore.Design/Scaffolding/ModelCodeGenerationOptions.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
- test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
Was a bit trickier than it looked... Would be good to get a close review.
Closes #15520
> Scaffold with nullable reference types

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
We have a general decision to remove code samples from XML docs, and to link to conceptual docs instead. But as there are no conceptual docs yet for ExecuteSql (https://github.com/dotnet/EntityFramework.Docs/issues/665), this just fixes the code sample for now.
Fixes #24934
> Fix code samples for ExecuteSql methods

- src/EFCore.Relational/Storage/RelationalConnection.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
> Reset CommandTimeout in context pooling

- eng/Version.Details.xml
- eng/Versions.props
- src/EFCore/EFCore.csproj
System.ComponentModel.Annotations is no longer produced by dotnet/runtime (https://github.com/dotnet/runtime/pull/51891)
> Coherency fix

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
We can also go the other way, i.e. change the metadata APIs to work with byte. This would be more consistent with the internal SQL Server representation (tinyint), but would be a small breaking change.
Fixes #25006
> Scaffold SQL Server index fill factor annotation as int

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
Properly fallback to model-level defaults
Fixes #24840
> Allow long identity seed

- src/EFCore/Storage/ExecutionStrategy.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
- test/EFCore.Tests/ChangeTracking/Internal/ObservableBackedBindingListTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/SortableBindingListTest.cs
Use the new [`Random.Shared`](https://github.com/dotnet/runtime/blob/3c1f5b380e6704f9d14de02a4a22adaec5095cd1/src/libraries/System.Private.CoreLib/src/System/Random.cs#L50-L51) property to remove the need to allocate a new instance when targeting `net6.0`.
> Use Random.Shared

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
("really slow" on SDK style .csproj)
fixes #24933
> Stop using AddFromFile with many files

- src/EFCore.SqlServer/Query/Internal/SqlServerMathTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMathTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> Add Translation for MathF (#18842)

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/TableValuedDbFunctionConvention.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Metadata/Conventions/Internal/TableValuedDbFunctionConventionTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Preserve `null` mappings in the model snapshot.
Add non-generic `ToSqlQuery` overload.
Output Fluent API for `ToSqlQuery` in the model snapshot.
Fix `SetFunctionName` setting incorrect annotation.
Fixes #23408
> Don't remove default table mapping for TVF return entity types.

- src/EFCore/Storage/ExecutionStrategy.cs
- test/EFCore.Tests/Storage/ExecutionStrategyTest.cs
Do not throw an exception on the first execution of an execution strategy if a transaction is pending when `MaxRetryCount` is zero.
This follows the suggested implementation in https://github.com/dotnet/efcore/issues/24922#issuecomment-843490061.
I've added a unit test for the async and sync execution paths using the example code in #24922 as the starting point.
> Allow execution strategy bypass

- src/EFCore/DbContext.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
> Fix caching of resettable services for pooled uninitialized context

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- test/EFCore.SqlServer.Tests/CommandConfigurationTests.cs
Add support for `InfiniteTimeSpan` In `Context.Database.SetCommandTimeout()`.
resolves #25068 Comment [858547728](https://github.com/dotnet/efcore/issues/25068#issuecomment-858547728)
> Add support for `InfiniteTimeSpan` in `SetCommandTimeout`.

- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/ICosmosDbContextOptionsBuilderInfrastructure.cs
- src/EFCore.InMemory/Infrastructure/IInMemoryDbContextOptionsBuilderInfrastructure.cs
- src/EFCore.InMemory/Infrastructure/InMemoryDbContextOptionsBuilder.cs
This is the moral equivalent of IRelationalDbContextOptionsBuilderInfrastructure which lets extension methods access the core options builder.
Fixes #23669
> Add IInMemoryDbContextOptionsBuilderInfrastructure

- src/EFCore.Relational/Storage/DateOnlyTypeMapping.cs
- src/EFCore.Relational/Storage/TimeOnlyTypeMapping.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateOnlyMemberTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMemberTranslatorProvider.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateOnlyTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTimeOnlyTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
- test/EFCore.OData.FunctionalTests/Query/GearsOfWarODataContext.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Mission.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
Closes #24506
Note: this doesn't add translations for TimeOnly, since none exist for TimeSpan at the moment (and some Sqlite magic needs to be done). Both can be done together as part of #18844.
> Implement DateOnly/TimeOnly support for Sqlite 

- src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
- src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/MathTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
Added Math for Cosmos:
ABS, CEILING, FLOOR, POWER, EXP, LOG10, LOG, SQRT, ACOS, ASIN, ATAN, ATN2, COS, SIN, TAN, SIGN, TRUNC, ROUND
Issue: #16143
Need your help with translation methods with converting.
Example:
```
.Where(od => Math.Tan(od.Discount) > 0)
```
here `od.Discount` is `float`. `Math.Tan` requires `double`. So, the following expression will be generated:
```
Tan(Convert([Microsoft.EntityFrameworkCore.Query.EntityShaperExpression].Discount, Double))
```
In this case the `TryRemoveImplicitConvert` will be called and return `null`
https://github.com/Marusyk/efcore/blob/e23cdc0128851a8760bbcd57696f4001ae3b3a60/src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs#L685
Could you please suggest how to improve that?
> Add Math translators for Cosmos DB provider

- src/EFCore/DbSet.cs
Resolves #25122
The calls on Finder/DbContext have correct nullability
> Correct nullability of DbSet.Find

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
* Fixes missing code generation output for custom data annotation attributes.
* Adds regression tests.
The two regression tests currently skip the assembly build process, because the two custom data annotation attributes do not exist in the generated assembly. If necessary, the `Microsoft.EntityFrameworkCore.Design.Tests` assembly could be added as a reference or additional source code files (containing the attributes) could be added to the build process.
Should be considered as a 5.0 backport.
(Feel free to directly change/edit this PR, if less time consuming than writing a review.)
Fixes #25127
> Fix missing code generation output for custom data annotation attributes

- src/EFCore.Design/Properties/TypeForwards.cs
- src/EFCore.Relational/Diagnostics/Internal/RelationalCommandDiagnosticsLogger.cs
- src/EFCore.Relational/Diagnostics/Internal/RelationalConnectionDiagnosticsLogger.cs
- src/EFCore.Relational/Infrastructure/RelationalModelRuntimeInitializer.cs
- src/EFCore.Relational/Properties/TypeForwards.cs
- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/DbContextOptionsBuilder`.cs
- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Infrastructure/IndentedStringBuilder.cs
- src/EFCore/Infrastructure/ModelRuntimeInitializer.cs
- src/EFCore/ModelConfigurationBuilder.cs
- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
> Incorporate API Review feedback

- eng/Version.Details.xml
- eng/Versions.props
- global.json
> [release/6.0-preview6] Unpin Microsoft.Extensions.Logging

- test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorDisabledRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorEnabledRelationalTestBase.cs
For databases with case sensitive object names, the object name casing in `FromSqlRaw()` calls should be the expected default one, which is Pascal casing.
> Fix table casing to be the expected default (Pascal casing)

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Fixes #25133
Part of a larger fix from 6.0: 6b4ee136cea6a9cb360eed10024511f62b1fac0b
When an entity type is used as a TVF return type the (lack of) table mapping is not preserved in the model snapshot.
This causes a migration to be generated even without any model changes. And the generated migration produces an error when applied.
Anyone using TVFs (a new feature in 5.0) is affected by this unless they do want to map the entity type to a table.
**How found**
Test coverage for this case has been added in this PR.
No.
**Risk**
Low. The change only affect design-time tooling that generate source code. No quirk as it's unfeasible to turn it on when using the tools.
> [release/5.0] Preserve the null table mapping in migration snapshot when an entity type is used as a TVF return type.

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
Fixes #25156
Port of https://github.com/dotnet/efcore/pull/25128
When scaffolding code from a database provider-specific data annotation attributes are not generated.
Users need to add the provider-specific data annotation attributes manually, this could be unfeasible for large schemas. In particular this affects the data annotations added in 5.0 to the Pomelo MySQL provider
**How found**
Test coverage for this case has been added in this PR.
No.
**Risk**
Low. The change only affect design-time tooling that generate source code. No quirk as it's unfeasible to turn it on when using the tools.
> [release/5.0] Fix missing code generation output for custom data annotation attributes

- src/EFCore.SqlServer/Extensions/SqlServerDbSetExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerTemporalConvention.cs
- src/EFCore.SqlServer/Query/SqlExpressions/TemporalTableExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalPointInTimeQueryRewriter.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- added some comments,
- moved temporal query methods from queryable extensions to dbset extensions
- added convention logic for case when initially non-temporal implicit many to many gets converted to temporal
> minor cleanup for temporal table feature

- src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
- src/EFCore.Relational/Query/RelationalCollectionShaperExpression.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Internal/TypeFullNameComparer.cs
- src/EFCore/Metadata/Conventions/ConventionSet.cs
- src/EFCore/Metadata/Conventions/IForeignKeyNullNavigationSetConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ConventionScope.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.DelayedConventionScope.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs
- src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
- src/EFCore/ModelBuilder.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
- test/EFCore.Tests/Metadata/Conventions/KeyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ServicePropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
Rerun KeyDiscoveryConvention when a property is ignored
Remove the associated FK when a skip navigation is removed
Add IForeignKeyNullNavigationSetConvention
Sort IEntityTypeConfiguration applied from assembly
Fixes #18388
Fixes #24521
> Rerun relationship discovery if an ambiguity has been resolved on the inverse

- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
- test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
Adds extension methods to enable simpler adding and configuration of contexts for a specific EF Core provider, e.g.:
``` csharp
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddSqlite<ApplicationDbContext>(connectionString);
```
Contributes to #25192
Todo:
> Add IServiceCollection.Use[DbProviderName]<DbContext> extension methods

- Directory.Build.props
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/EFCore.Abstractions/ChangeTracking/Internal/ObservableBackedBindingList.cs
- src/EFCore/Metadata/Builders/IndexBuilder.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalIndexTest.cs
- test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
Fixes https://github.com/dotnet/efcore/issues/25148
> [preview7] Unpin Microsoft.Extensions.Caching.Memory and Microsoft.Extensions.Logging

- eng/Version.Details.xml
Unpinned dependencies in https://github.com/dotnet/efcore/pull/25324#issuecomment-886525732 need an update to the latest runtime.
> [release/6.0-preview7] Update dependencies from latest p7 runtime

- src/EFCore.Cosmos/ChangeTracking/Internal/ListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableEqualityComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableSingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableStringDictionaryComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/SingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosInversePropertyAttributeConvention.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosRelationshipDiscoveryConvention.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosTypeMappingSource.cs
- src/EFCore/Storage/CoreTypeMapping.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
> Cosmos: Add basic support for collections and dictionaries of primitive types

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
* Made DropColumnOperation inherit from ColumnOperation. This was needed to distinguish between dropping computed and non-computed, but it makes sense to expose all column facets in case they matter somehow when dropping the column.
* SQL Server and PostgreSQL don't allowing referencing a computed column from another computed column, Sqlite and MySQL do. In any case, we won't parse the computed SQL to understand dependencies.
Fixes #25237
> Drop computed columns before non-computed

- src/EFCore.Relational/Metadata/RuntimeRelationalPropertyOverrides.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore/DbContext.cs
- src/EFCore/IDbContextFactory.cs
- src/EFCore/Infrastructure/DatabaseFacade.cs
- src/EFCore/Infrastructure/PooledDbContextFactory.cs
- src/EFCore/Internal/DbContextLease.cs
- src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
- src/EFCore/Internal/IDbContextPoolable.cs
- src/EFCore/Internal/ScopedDbContextLease.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.Tests/DbContextTest.cs
Fixes #19193
~Fixes #17086~
Notes:
* We now no longer reset context events, as per #19193
* However, I left the code that resets options like QueryTrackingBehavior since that still seems useful, and makes this less of a break
* Added events to DbContext. These are easy and decoupled, but sync only.
* A derived DbContext can override the On... event methods. This allows async hooks.
* DbContextFactory now has a CreateDbContextAsync method such that a context can be rented from the pool and the hook applied in an async context.
> Implements events/callbacks for leasing and returning a context to the pool

- src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
- src/EFCore/Metadata/Builders/CollectionCollectionBuilder`.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
- src/EFCore/Metadata/Conventions/ManyToManyJoinEntityTypeConvention.cs
- src/EFCore/Metadata/Internal/Model.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
> Add more overloads of UsingEntity()

- src/EFCore/ChangeTracking/ChangeTracker.cs
> Grammar corrections

- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.Relational.Tests/Design/AnnotationCodeGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
* Database-level collation is scaffolded to the Fluent API call, instead of to a raw annotation.
* Don't scaffold database collation when it is identical to the server collation (i.e. is the default).
Fixes #25418
Fixes #25419
Note that we have a test the the database collation isn't scaffolded when it's the default, but no coverage for when it's different, since our DatabaseModelFactoryTest tests don't create new databases. I've manually verified this works.
> Fixes around scaffolding collations

- src/EFCore.Cosmos/Diagnostics/CosmosEventId.cs
- src/EFCore.Cosmos/Diagnostics/CosmosItemCommandExecutedEventData.cs
- src/EFCore.Cosmos/Diagnostics/CosmosQueryExecutedEventData.cs
- src/EFCore.Cosmos/Diagnostics/CosmosReadItemEventData.cs
- src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggerExtensions.cs
- src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggingDefinitions.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestSqlLoggerFactory.cs
> Cosmos: Add diagnostic events with statistics

- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/ValueGeneration/ValueGeneratorSelector.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
Allows to use value converters for identity and sequence columns, within the limitations already established (must be a non-floating point numerical type on the provider side).
Implements https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1118 for SQL Server.
I added an explicit `.UnwrapNullableType()` call, so that a `decimal?` would behave the same way as an `int?` (both are not really supported for identity columns by SQL Server, but they should at least be handled in the same way before SQL Server finally returns an error, and should not lead to different behavior in EF Core).
It would probably be cleaner to check for non-nullable types only in general instead.
Related to #11597 and https://github.com/npgsql/efcore.pg/issues/1439
I don't see any issues with this …
> Enable value conversion support for identity/sequence properties

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/Builders/TemporalTableBuilder.cs
- src/EFCore.SqlServer/Metadata/Builders/TemporalTableBuilder`.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerTemporalConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerNavigationExpansionExtensibilityHelper.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Query/INavigationExpansionExtensibilityHelper.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/NavigationExpansionExtensibilityHelper.cs
- src/EFCore/Query/NavigationExpansionExtensibilityHelperDependencies.cs
- src/EFCore/Query/QueryTranslationPreprocessor.cs
- src/EFCore/Query/QueryTranslationPreprocessorDependencies.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- converted QueryRootCreator into general purpose helper service,
- renamed WithHistoryTable to UseHistoryTable,
- removed Temporal from entity type extensions,
- added dependency objects to temporal convention.
> Addressing API Review feedback for temporal tables feature:

- src/EFCore.Cosmos/Infrastructure/CosmosDbContextOptionsBuilder.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
- src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
- test/EFCore.Cosmos.Tests/Extensions/CosmosDbContextOptionsExtensionsTests.cs
> Cosmos: Make it possible to configure a HttpClientFactory

- src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
> Allow ForeignKeyAttribute to be used on skip navigations.

- src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosKeyDiscoveryConvention.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosManyToManyJoinEntityTypeConvention.cs
- src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/ManyToManyJoinEntityTypeConvention.cs
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
> Set partition key on join entity type by convention.

- src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
Fixes the conflict between https://github.com/dotnet/efcore/pull/25444 and https://github.com/dotnet/efcore/pull/25443
> Don't fallback to default foreign key properties for many-to-many if no attribute was specified.

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
> Tune mappings between ReferentialAction and DeleteBehavior

- src/EFCore.SqlServer/Diagnostics/Internal/SqlServerLoggingDefinitions.cs
- src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
- src/EFCore.SqlServer/Extensions/Internal/SqlServerLoggerExtensions.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Skip and warn of duplicated SQL Server foreign keys

- src/EFCore.SqlServer/Extensions/SqlServerDbSetExtensions.cs
Adding note to temporal methods that database stores time in UTC so local time may lead to unexpected results. Also indicating that in DateTime argument names for those methods.
> [TINY] Temporal Tables API feedback

- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
- test/EFCore.Tests/DbContextFactoryTest.cs
Fixes #25164
Results from design investigation:
* AddDbContext registers DbContextOptions as scoped by default. This cannot be consumed from the default singleton factory. Changing the lifetime of DbContextOptions is a breaking change. This prevents us from adding the factory automatically, since it will not work correctly in the default/normal case.
* AddDbContextFactory can automatically add a scoped DbContext registration. This will depend on the singleton options added with the factory, which will work. This is the change we will make.
* Applications that explicitly register a DbContext as well as using AddDbContextFactory will not be impacted, since we always TryAdd in our methods.
* Applications that are already calling AddDbContextFactory first, and then also AddDbContext, would …
> Register a scoped DbContext automatically when using AddDbContextFactory

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
> Support making computed columns non-computed

- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Diagnostics/UniquifiedPropertyEventData.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
> Warn when uniquifying an FK column name

- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionPool.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionPoolGroup.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
- src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
- src/Microsoft.Data.Sqlite.Core/Utilities/MemberNotNullAttribute.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/SpatialSqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteDatabaseCleaner.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestStore.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionFactoryTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Resolves #13837, fixes #25101, fixes #25078
TechEmpower Fortunes benchmark results on aspnet-citrine-win:
&nbsp;            | 5.0   | 6.0
----------------- | ----- | ------
**Requests/sec**      | 3,473 | 25,510
**Mean latency (ms)** | 73.56 | 10.04
**CPU Usage (%)**     | 93    | 99
/cc @sebastienros
> Microsoft.Data.Sqlite: Pool connections

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.SqlServer.NTS/Scaffolding/Internal/SqlServerNetTopologySuiteCodeGeneratorPlugin.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerCodeGenerator.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteCodeGenerator.cs
- src/EFCore.Sqlite.NTS/Scaffolding/Internal/SqliteNetTopologySuiteCodeGeneratorPlugin.cs
- src/EFCore/Design/AttributeCodeFragment.cs
- src/EFCore/Design/ICSharpHelper.cs
- src/EFCore/Design/MethodCallCodeFragment.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/Shared/SharedTypeExtensions.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Relational.Tests/TestUtilities/TestProviderCodeGenerator.cs
- test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Scaffolding/SqlServerCodeGeneratorTest.cs
- test/EFCore.Sqlite.Tests/Scaffolding/SqliteCodeGeneratorTest.cs
- test/EFCore.Tests/Design/MethodCallCodeFragmentTest.cs
@bricelam this is a draft for getting your general OK before going further... #25046 (custom namespaces in scaffolding) is fully implemented, while #23848 (type-qualified Fluent APIs in the model snapshot) is a bit more tricky/ugly.
Closes #25046
Closes #23848
Closes #25434
> Fixes around namespaces and Fluent API calls

- src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
- src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
INDEX_OF, LEFT, RIGHT, REPLACE, case insensitive STRINGEQUALS
> Adding translations for cosmos string methods

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
Fixes #25508, unresolves #16202
> Microsoft.Data.Sqlite: Revert to using string overload of sqlite3_prepare

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
> [SMALL] Enabling some Distinct tests on Cosmos

- src/EFCore/Metadata/Builders/PropertiesConfigurationBuilder.cs
- src/EFCore/Metadata/Builders/PropertiesConfigurationBuilder`.cs
- src/EFCore/Metadata/Builders/PropertyBuilder.cs
- src/EFCore/Metadata/Builders/PropertyBuilder`.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
> Simplify HasConversion API by allowing provider type and converter type to be used interchangeably

- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbContextOptionsBuilderExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
This can make it easier to run the Cosmos tests (instead of messing around with installing the self-signed certificate etc.)
> Disable SSL certificate validation in Cosmos tests

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
> SQLite: Revert multi-threading change

- src/EFCore.Cosmos/Extensions/CosmosQueryableExtensions.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosDiscriminatorConvention.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Query/Internal/CosmosQueryTranslationPostprocessor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/FromSqlExpression.cs
- src/EFCore.Cosmos/Query/Internal/FromSqlQueryRootExpression.cs
- src/EFCore.Cosmos/Query/Internal/ISqlExpressionFactory.cs
- src/EFCore.Cosmos/Query/Internal/QuerySqlGenerator.cs
- src/EFCore.Cosmos/Query/Internal/QuerySqlGeneratorFactory.cs
- src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
- src/EFCore.Cosmos/Query/Internal/SqlExpressionFactory.cs
- src/EFCore.Cosmos/Query/Internal/SqlExpressionVisitor.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Cosmos.FunctionalTests/EFCore.Cosmos.FunctionalTests.csproj
- test/EFCore.Cosmos.FunctionalTests/Query/FromSqlQueryCosmosTest.cs
Notes:
* Did not implement FromSqlInterpolated for now as we're not sure we want to. Current naming is FromSqlRaw (as opposed to FromSql).
* Cosmos has no DbParameter - parameters are added via [QueryDefinition.WithParameter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.querydefinition.withparameter?view=azure-dotnet) where the name/value are given directly. The main use of accepting DbParameter in relational is to allow configuring parameter facets (size, precision, scale), but as these concepts don't exist in Cosmos we simply don't support it. So Cosmos FromSql supports only direct values.
* The current implementation always integrates the raw SQL as a subquery, even when it isn't composed over. This is because we currently always send `SELECT c FROM root c` for …
> Cosmos FromSql

- src/EFCore/DbContext.cs
- src/EFCore/DbSet.cs
- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
> Make the non-thread-safety of DbContext more visible

- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/ValueGeneration/ValueGeneratorSelector.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteValueGenerationScenariosTest.cs
Fixes #11970
Also, add back in the provider-agnostic check for converters with value generators, but make it less restrictive.
> Support mapping identity columns to enum properties

- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
Fixes #14307
This means that tooling (such as the database middleware) can still find the context, while the application can resolve using the interface.
> Register concrete DbContext type in D.I. even when registration for interface is also made

- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Don't remember which bug I was testing when I wrote this.
> Query: Add a test for group by constant composed

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Design/Internal/ICSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Metadata/RuntimeModel.cs
- src/EFCore/Metadata/RuntimeScalarTypeConfiguration.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Add scalar type configuration support to compiled models.

- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
If there are no related data loaders then we don't need to run the shaper again to generate result from resultValues
Resolves #25400
> Query: Run shaper only when needed in SplitQueryingEnumerable

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> RevEng: SqlServer: Escape table name passed from user correctly

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore.Relational/Infrastructure/RelationalModelRuntimeInitializer.cs
- src/EFCore/Infrastructure/ModelRuntimeInitializer.cs
- src/EFCore/Metadata/Conventions/IModelFinalizedConvention.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.SqlServer.Tests/SqlServerOptionsExtensionTest.cs
> Make compiled model and runtime initialization thread-safe

- src/EFCore.SqlServer/Design/Internal/SqlServerCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerRuntimeModelConvention.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Removing unnecessary temporal annotations on runtime entity types, also avoiding adding EnsureSchemaOperation if the schema that is to be created has already been added in the migration batch.
> Fix to #25013 - Outstanding work for temporal tables

- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
> Query: Remove unnecessary convert to IEnumerable for OData

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore.Relational/Extensions/RelationalPropertiesConfigurationBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalTypeMappingConfigurationBuilderExtensions.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Design/Internal/ICSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Metadata/Builders/PropertiesConfigurationBuilder.cs
- src/EFCore/Metadata/Builders/TypeMappingConfigurationBuilder.cs
- src/EFCore/Metadata/Builders/TypeMappingConfigurationBuilder`.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Metadata/IModel.cs
- src/EFCore/Metadata/ITypeMappingConfiguration.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/ModelConfiguration.cs
- src/EFCore/Metadata/Internal/PropertyConfiguration.cs
- src/EFCore/Metadata/RuntimeModel.cs
- src/EFCore/Metadata/RuntimeTypeMappingConfiguration.cs
- src/EFCore/ModelConfigurationBuilder.cs
- src/EFCore/Storage/TypeMappingSource.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ValueConvertersEndToEndSqlServerTest.cs
> Rename Scalars to DefaultTypeMapping

- src/EFCore/ChangeTracking/EntityEntry`.cs
- src/EFCore/ChangeTracking/ReferenceEntry`.cs
Unfortunately, the situation here is complicated, since ReferenceEntry APIs sometimes returns nullable for TProperty, sometimes not:
* ReferenceEntry.CurrentValue can return nulls if the reference navigation property was nullable.
* ReferenceEntry.TargetEntry returns a nullable EntityEntry, so the TProperty it wraps is never null. Query also return `IQueryable<TProperty>` where TProperty should never be null.
I don't think there's a perfect solution, here are some options with what they mean for the return values of ReferenceEntry.TargetEntry and CurrentValue:
|                                                                                                  | TargetEntry for nullable property  | TargetEntry for non-nullable property  | CurrentValue for nullable property  | CurrentValue …
> Correct nullability annotation for ReferenceEntry

- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Handle context types in the global namespace
Fixes #25058
Fixes #25059
> Change the default subfolder/subnamespace for compiled models to CompiledModels

- src/EFCore.Tools/tools/EntityFrameworkCore.PS2.psm1
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/ef/Commands/MigrationsBundleCommand.Configure.cs
- src/ef/Commands/MigrationsBundleCommand.cs
> Migrations Bundles: Address API Review feedback

- src/EFCore.Relational/Scaffolding/ProviderCodeGenerator.cs
> [release/6.0-rc1] Revert ProviderCodeGenerator.RelationalDependencies change

- test/EFCore.Cosmos.FunctionalTests/Query/FromSqlQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
> Fix some test determinism issue

- src/EFCore/ChangeTracking/EntityEntry`.cs
- src/EFCore/ChangeTracking/ReferenceEntry`.cs
Merging to RC1 for public API changes (nullability)
Merged to 6.0 via #25591 
Fixes #24659
> Correct nullability annotation for ReferenceEntry, RC1

- src/EFCore.Cosmos/Query/Internal/FromSqlQueryRootExpression.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
- src/EFCore.Relational/Query/Internal/TableValuedFunctionQueryRootExpression.cs
- src/EFCore.SqlServer/Query/Internal/TemporalAllQueryRootExpression.cs
- src/EFCore.SqlServer/Query/Internal/TemporalAsOfQueryRootExpression.cs
- src/EFCore.SqlServer/Query/Internal/TemporalBetweenQueryRootExpression.cs
- src/EFCore.SqlServer/Query/Internal/TemporalContainedInQueryRootExpression.cs
- src/EFCore.SqlServer/Query/Internal/TemporalFromToQueryRootExpression.cs
- src/EFCore/Metadata/Conventions/QueryFilterRewritingConvention.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/QueryRootExpression.cs
- test/EFCore.InMemory.FunctionalTests/Query/SharedTypeQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/SharedTypeQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/SharedTypeQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SharedTypeQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SharedTypeQuerySqliteTest.cs
- test/EFCore.Tests/Metadata/Conventions/QueryFilterRewritingConventionTest.cs
> Query: Allow using STET overload for Set in query filter/defining query

- src/EFCore.Cosmos/ChangeTracking/Internal/ListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableSingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableStringDictionaryComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/SingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore/ChangeTracking/ArrayStructuralComparer.cs
- src/EFCore/ChangeTracking/GeometryValueComparer.cs
- src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/ValueComparerExtensions.cs
- src/EFCore/ChangeTracking/ValueComparer.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Tests/Storage/ValueComparerTest.cs
Some of this came up during annotating EFCore.PG.
The main thing is that generic Snapshot shouldn't accept/return `T?`, but rather T (just like GetHashCode).
> Tweaks to ValueComparer nullability

- src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Disable nullability in migrations

- src/EFCore.Cosmos/ChangeTracking/Internal/ListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableListComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableSingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/NullableStringDictionaryComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/SingleDimensionalArrayComparer.cs
- src/EFCore.Cosmos/ChangeTracking/Internal/StringDictionaryComparer.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore/ChangeTracking/ArrayStructuralComparer.cs
- src/EFCore/ChangeTracking/GeometryValueComparer.cs
- src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/ValueComparerExtensions.cs
- src/EFCore/ChangeTracking/ValueComparer.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Tests/Storage/ValueComparerTest.cs
* Make Snapshot accept/receive non-nullable (nulls are sanitized externally).
* Make ValueComparer<T>.GetHashCode accept non-nullable object.
Merges #24410 for RC1
> Tweaks to ValueComparer nullability (RC1)

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeDbException.cs
- test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
> Stop wrapping OperationCancellationException with DbUpdateException

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
Added override to do custom task for GroupBy which ended up getting removed in final implementation but method was left behind
Part of #24743
> Query: Remove redundant override of TranslateSubquery

- src/EFCore/Storage/ValueConversion/ValueConverterSelector.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Faction.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Tests/Storage/ValueConverterSelectorTest.cs
Note that after this PR, the SQL gets generated with a useless conversion: `WHERE [b].[Address] = CAST(N'127.0.0.1' AS nvarchar(45))`. We should be able to remove the convert node when its type mapping is identical to its operands, but for this to be correct we need to be able to fully compare type mappings... Leaving this for now (@smitpatel do we have this tracked/discussed somewhere?)
Fixes #21159
> Support value conversion for ReadOnlyIPAddress

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
Resolves #21490
By 5.0 we expanded navigation correctly but failed in translation
in 6.0 we translate correctly too
> Query: Add regression test for #21490

- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Generally we encounter ShapedQueryExpression during translation when translating subqueries
Since ShapedQueryExpression contains QueryExpression which is mutated in-place, we lose the original expression if for any reason translation doesn't work out. Which blocks us from translating it further without recreating original tree again.
We were hitting this during client eval in projection earlier where owned entities are expanded during translation
We recreated tree by expanding owned navigation during the method to retain original expression
With issue #22089 we ran into situation where we try to translate a subquery which is not fully translatable and then we have to visit it through base.
So to avoid the whole issue with reconstruction, now we clone the shaped query during translation so …
> Query: Clone shaped query expression during translation

- test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
> Query: Add regression test for #24133

- src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
- src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/ValueGeneration/Internal/DiscriminatorValueGenerator.cs
- src/EFCore/ValueGeneration/ValueGenerator.cs
- test/EFCore.InMemory.FunctionalTests/GraphUpdates/GraphUpdatesInMemoryTest.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdates/GraphUpdatesSqliteTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Fixes #19856
The fundamental issue here is that the key for owned collections is, by default, formed from shadow properties. This means the values of these properties are lost when the entities in the collection are no longer tracked by a DbContext. When the entities are then later attached there is no way to get these values back. (Contrast this with owned non-collection entities, where the shadow key value can be synthesized from the owner key.) This in turn means that there is no way to identify these entities in the database, and there is therefore no way to update or delete them.
This PR detects this situation and throws an exception with a (hopefully) helpful error message.
The best way to deal with this is to add a CLR property for the key (which can be private) to the owned entity …
> Detect unknown shadow primary key values when attempting to save owned collection

- src/EFCore.Relational/Extensions/Internal/RelationCommandCacheExtensions.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/RelationalCommandCache.cs
- src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Storage/IRelationalCommand.cs
- src/EFCore.Relational/Storage/IRelationalCommandTemplate.cs
- src/EFCore.Relational/Storage/RelationalCommand.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs
- test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
Fixes #25225.
As part of the query performance work in EF Core 6.0, a concurrency state bug was accidentally introduced where the same stateful object (RelationalCommand) may get reused concurrently, leading to issues.
Running the same query concurrently as a split query on SQL Server may fail in unpredictable ways.
**How found**
User report.
Included in this PR.
Yes, as result of a performance optimization introduced in EF Core 6.0.
**Risk**
Very low, the PR simply duplicates the stateful RelationalCommand for the non-primary split query case, a technique already used in other scenarios (e.g. single query).
~~There is also a remaining possible issue that I see: …
> [release/6.0-rc1] Fix #25225 by forcing usage of renting and populating commands when using relational command cache

- src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
Fixes compilation errors starting with .NET SDK 6.0.100-rc.1.21417.19
We won't be able to build the product to ship to them.
**How found**
Updating the SDK.
Compile-time issue.
N/A
**Risk**
Low. Makes the compiler work.
Flagged by @sebastienros because of failures in continuous benchmark runs
> [release/6.0-rc1] Remove unused nullability in typeof

- test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
> Query: Add regression test for #18582

- src/EFCore.Proxies/Proxies/Internal/ProxyChangeTrackingConvention.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/IMemberClassifier.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/MemberClassifier.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Discover inverse navigations when entity becomes non-owned
Don't remove leftover attributes in `ModelCleanupConvention`, instead ignore them in `RuntimeModelConvention`
Fixes #25279
> Discover inverse navigations when entity added after being ignored

- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
> Correctly handle adding optional dependents using table splitting without principal.

- src/EFCore.SqlServer/Diagnostics/Internal/SqlServerLoggingDefinitions.cs
- src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
- src/EFCore.SqlServer/Extensions/Internal/SqlServerLoggerExtensions.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
* Load columns even if they have no type, warn and skip.
* Skip indexes/constraints which reference unknown columns.
Fixes #25729
> Resiliency to columns with missing types in SQL Server scaffolding

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
> Query: Re-enable test for #22896

- azure-pipelines.yml
We are transitioning all servicing build to a new set of pools
```
- Detail 1
- Detail 2
```
> Use new Hosted build pools

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
All Contains calls are converted to Any with predicate (which allows to handle null semantics) so this code never gets but fixing this tiny bug, just in case. We were not setting the cardinality of the contains translation to single result, so the translation would have failed, if it wasn't converted to Any and therefore (correctly) being handled by it's translation code.
Fixes #24671
> Fix to #24671 - Relational: No tests for TranslateContains path

- src/EFCore/Metadata/Conventions/NonNullableNavigationConvention.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Related to https://github.com/dotnet/efcore/pull/25737
Fixes #23588
> Configure requiredness based on NRT even if principal end might be ambiguous.

- test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NorthwindKeylessEntitiesQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindKeylessEntitiesQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsSharedTypeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
Resolves #13560
Resolves #17364
Resolves #17803
Resolves #21078
Resolves #21828
Resolves #23041
> Adding regression tests for some issues fixed earlier

- test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
Also minor test fixes that were found as a result of fixing this.
Fixes #25834
> Fix to #25834 - Query/Test: northwind tests don't have predefined entity asserters

- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategy.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosExecutionStrategyFactory.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SingleQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SplitQueryingEnumerable.cs
- src/EFCore.Relational/Query/RelationalCompiledQueryCacheKeyGenerator.cs
- src/EFCore.Relational/Storage/Internal/RelationalDatabaseFacadeDependencies.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreatorDependencies.cs
- src/EFCore.Relational/Storage/RelationalExecutionStrategyFactory.cs
- src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerDependencies.cs
- src/EFCore/Infrastructure/DatabaseFacade.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Query/CompiledQueryCacheKeyGeneratorDependencies.cs
- src/EFCore/Query/QueryCompilationContext.cs
- src/EFCore/Query/QueryCompilationContextDependencies.cs
- src/EFCore/Query/QueryContext.cs
- src/EFCore/Query/QueryContextDependencies.cs
- src/EFCore/Storage/ExecutionStrategy.cs
- src/EFCore/Storage/IDatabaseFacadeDependencies.cs
- src/EFCore/Storage/IExecutionStrategy.cs
- src/EFCore/Storage/IExecutionStrategyFactory.cs
- src/EFCore/Storage/Internal/DatabaseFacadeDependencies.cs
- src/EFCore/Storage/Internal/ExecutionStrategyFactory.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.Tests/Storage/ExecutionStrategyTest.cs
Don't pass `null` to `ExecutionStrategy.ShouldRetryOn`.
Use the currently executing execution strategy to determine whether buffering is needed.
Fixes #21350
Fixes #23019
Fixes #21463
> Reuse some IExecutionStrategy instances.

- src/EFCore.Cosmos/Query/Internal/StringMethodTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> Fix to #25842 - Cosmos: Translate string.Equals with StringComparison.Ordinal

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
Closes #19702
@maumar can you give this a look? Seems to have been fixed at some point...
> Add test for projected Contains(null)

- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs
- test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
Add a test for deadlocks.
Fixes #15180
Fixes #25228
> Sort inserts to preserve tracking order in more cases.

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> Query: Add regression test for #23784

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore/Design/MethodCallCodeFragment.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
In 6.0 we added a MethodCallCodeFragment constructor when obsoleting the string-based APIs (for type-qualified calls) - this obsoletes it with error, since it's easy to accidentally call the other constructor which accepts `params object[] arguments`. I left it there with error so that anyone converting code would get a build error rather than resolving the wrong constructor.
Fixes #19780
> Remove MethodCallCodeFragment constructor accepting a chained call

- eng/Versions.props
Fixes #25497
Update dependency on external SQLite packages from 2.0.2 to 2.0.4. This version fixes an important bug [System.AccessViolationException at System.Text.UTF8Encoding.GetCharCount(Byte*, Int32, System.Text.DecoderNLS)](https://github.com/ericsink/SQLitePCL.raw/issues/321) which has been hit by many customers. Our 5.0 packages have already depended on this newer version for about a year. We now want to update the 3.1 packages because they are LTS and are the last version of EF Core that runs on .NET Framework.
Fixes an AccessViolationException hit my many customers, and avoids every customer having to manually reference the updated package.
**How found**
Reported by customers.
Sufficient test coverage already exists since this …
> [release/3.1] Update SQLite dependencies to 2.0.4

- src/EFCore/ChangeTracking/PropertyValues.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
> Allow setting original/current values using a typed dictionary

- src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
> Read double as float on SQL Server when precision is less than 25

- src/EFCore.Relational/Metadata/Internal/RelationalIndexExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
> Validate same filters in duplicate indexes

- src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
> Query: Convert SingleResult compared to null to Any

- src/EFCore/ValueGeneration/ValueGeneratorCache.cs
> Remove factory from value generator cache key

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
> Query: Use cancellationToken appropriately

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Fixes #24981
We had decided to make these Debug, but after looking at how these are used I think it makes more sense to make them warnings.
> Change logging level for non-created indexes from Info to Warn

- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitSharedTypeQuerySqliteTest.cs
The issue has been fixed earlier (already works in EF Core 5)
Resolves #24931
> Adding regression test for #24931 - SqlNullValueException on specific combination of outer joins in LINQ

- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/Shared/Multigraph.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.Tests/Utilities/MultigraphTest.cs
This dependency isn't hard, so cycle breaking is introduced.
Make the implementations of `Multigraph` `TopologicalSort` and `BatchingTopologicalSort` more alike and faster
Fixes #14371
> Always sort deletes before inserts for the same table to avoid deadlocks.

- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- src/EFCore/Metadata/IReadOnlyNavigation.cs
- src/EFCore/Metadata/IReadOnlyNavigationBase.cs
- src/EFCore/Metadata/IReadOnlyPropertyBase.cs
- src/EFCore/Metadata/IReadOnlySkipNavigation.cs
- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
- src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
- src/EFCore/Metadata/Internal/Navigation.cs
- src/EFCore/Metadata/Internal/NavigationExtensions.cs
- src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
- src/EFCore/Metadata/Internal/SkipNavigation.cs
- src/EFCore/Metadata/Internal/SkipNavigationExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Make `GetIdentifyingMemberInfo()` return `null` for indexer properties since it doesn't uniquely identifies them
Replaced some usages of `GetIdentifyingMemberInfo()` with more appropriate code.
Fixes #25501
Fixes #25459
> Make sure navigations on property bag entity types don't use CLR properties.

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Fixes #25360
This is a case where an optional relationship is configured with delete orphans behavior. Since the relationship is optional it means that the FK value can be explicitly set to null. (This is not possible for required relationships, which is the usual case for delete orphans.) In this case the navigation fixer was not triggering behavior in the state manager to process deleting orphans.
> Delete optional orphans when foreign key value is set to null

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore/Infrastructure/IndentedStringBuilder.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
> Fix indentation when scaffolding with no namespace

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlSprocQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryTaggingQuerySqlServerTest.cs
> Generate multiple query tags without newlines between them

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
So that when that property is being read outside of entity materialization, we get null value rather than default of non-nullable type
Resolves #25735
> InMemory: Read nullable value for derived properties

- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/Shared/StringBuilderExtensions.cs
> Add a way for providers to filter out non-identity conditions.

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
> Clear all connection pools before attempting to delete SQLite file

- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/ValueGenerationConvention.cs
- test/EFCore.InMemory.FunctionalTests/GraphUpdates/GraphUpdatesInMemoryTest.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerOwnedTest.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdates/GraphUpdatesSqliteTestBase.cs
> Don't hard-code value generation to Never for FKs

- src/EFCore/Metadata/Builders/CollectionCollectionBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
> Throw better exception for many-to-many with same navigation on both ends

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Fixes #25841 - Create period columns as hidden
Fixes #25774 - EFCore.SqlServer - v6.00-preview - SqlServerDatabaseModelFactory doesn't read information about hidden temoral tables' columns
Fixes #25773 - EFCore.SqlServer - v6.00-preview - failed on creating model for WideWorldImporters sample database temporal tables
Multiple problems were causing the issues in the scaffolding code path:
We used to skip over hidden columns when constructing database model. This made sense when temporal tables were not supported, but now we need that column information.
However, if we add period columns to database model, they will in turn produce EF model with period properties, and then code generator will produce property code for them on the entity, rendering them non-shadow.
All period properties must …
> Fixing bugs around hidden period columns

- src/ef/Commands/MigrationsBundleCommand.cs
Fixes #25622, fixes #25483
Manually verified that the files are copied correctly. Really need a way to write automated tests for dotnet tools...
> Bundles: Copy NuGet.Config and global.json files

- src/EFCore/Query/Internal/NullCheckRemovingExpressionVisitor.cs
- src/Microsoft.Data.Sqlite.Core/Extensions/TypeExtensions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
> Query: Avoid incorrect cast when simplifying null check

- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsSharedTypeQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqliteTest.cs
> Query: Add regression test for #21665

- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
Adding a list of columns guaranteed to be null in the given subtree. When processing right side of the || operator, we can convert those to non-nullable columns and therefore improve the generated sql.
Fixes #19883
Fixes #19410
> Fix to #19883 - Query: null semantics should keep track of columns that are guaranteed to be null and remove redundant IS NULL/ IS NOT NULL checks

- global.json
@dotnet/efteam This should restore balance to the universe, and you shouldn't need to run `startvs` anymore if you have VS2022 Preview 4 installed.
> Update to .NET SDK 6.0 RC1

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/OriginalValues.cs
- src/EFCore/ChangeTracking/Internal/SidecarValues.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerExtensions.cs
- src/EFCore/Extensions/PropertyBaseExtensions.cs
- src/EFCore/Metadata/IReadOnlyIndex.cs
- src/EFCore/Metadata/IReadOnlyKey.cs
- src/EFCore/Metadata/IReadOnlyTypeBase.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/ManyToManyModel/ManyToManyData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTManyToManyQuerySqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
Remove null-checking code for `IProperty.GetValueComparer()`
Make `DebugString` terser for Indexes and keys on STETs
Remove extra `UsingEntity` in `ManyToManyQueryFixtureBase`
Fixes #23418
> List shared-identity entries for STETs

- src/EFCore.Relational/Storage/RelationalConnection.cs
- test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
> Allow UseTransaction to replace existing transaction

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Relational/Migrations/Operations/Builders/AlterOperationBuilder.cs
- src/EFCore.Relational/Migrations/Operations/Builders/OperationBuilder.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
Problem was that we perform a null check on old and new annotation, but null is a valid value for annotation. We should allow this and also mark the annotation value as nullable object. Also fixed small issue in code gen where we would not generate code to add annotation with null value (but we were adding it for old annotation).
Fixes #26014
> Fix to #26014 - Migrations/Temporal Tables: null value exception when executing Down migration to convert entity from temporal to normal

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
> Query: Throw better error message when final result contains IGrouping

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
Fixes #26045
Invalid migrations snapshot generated for key Fluent APIs
Generated migrations which contain Fluent API configurations for keys (e.g. clustered) do not compile. Discovered by customer on RC1.
**How found**
User report: #26045 trying RC1
Added as part of this PR
Yes, introduced as part of recent improvements to migration code generation.
**Risk**
Low, the issue is simple, the fix is well-understood, and the area is relatively well-covered.
Also generate Fluent API for IsMemoryOptimized.
@Pilchie @dotnet/efteam - This fixes a bug reported on rc1, and needs to go into rc2.
> [6.0-rc2] Fix Fluent APIs on keys in model snapshot

- src/EFCore.Relational/Query/Internal/QueryExpressionReplacingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Part 2 & 3 of #26046
- Query with GroupBy as final operator throws unfriendly error message
- Query which specifies ToList over grouping element throws translation error or generate incorrect results
Customer will get exception thrown or incorrect results
**How found**
Manual testing done by @ajcvickers 
Added regression tests for scenario and similar cases.
- Query with GroupBy as final operator throwing unfriendly error message is a regression (we used to throw better message)
- Query with ToList over grouping element is a new feature in 6.0
**Risk**
- Low. Code change is minimal and we have many tests going over same code path.
> [6.0-rc2] Query: Translate ToList over grouping element

- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/IEntityType.cs
- src/EFCore/Metadata/IReadOnlyEntityType.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Tests/ApiConsistencyTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
Fixes #24123
- Navigation fixup is erroneously performed using a deleted entity when there is also an added entity with the same key value.
- Navigation fixup is not performed on many-to-many skip navigations when just the join entity is removed
- The first issue causes **data corruption** that can go undetected as expected changes are not persisted to the database.
- The second issue is less severe and just causes the client state to go out-of sync with the database after `SaveChanges`
**How found**
- Customer
- Added regression tests for the scenario.
- No
**Risk**
- Medium. This potentially affects many shared-identity and many-to-many scenarios
> Fixup deleted join entities

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Resolves #26086
Code scaffolded for many-to-many join table is configuring wrong FKs for join table.
An exception is thrown for entities with different key types on either end of the relationship. This is how it was discovered. It could cause silent data corruption for the more common case where entities have the same key type.
**How found**
Added regression tests for the scenario. Also manually tested scaffolding Northwind database where issue was found. We also have #25543 tracking better coverage in general for this area.
No. This is new feature in 6.0
**Risk**
Low. Since the scenario was fully broken, this doesn't have potential to make it worse. Testing on Northwind database also gives us …
> [6.0-rc2] RevEng: Generate correct FK configuration for scaffolding

- test/EFCore.InMemory.FunctionalTests/Query/Ef6GroupByInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/Ef6GroupBySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/Ef6GroupBySqliteTest.cs
As a crude measure of the gap between EF Core and EF6.
Currently:
- 20 tests pass
- 2 tests fail with "Translation of 'Select' which contains grouping parameter without composition is not supported."
- 17 tests fail with general "Could not be translated."
- ~~8 tests fail with different results~~
> Adding grouping tests from EF6

- src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Fixes #26062, replaces #25857.
A change in EF Core 6 to allow for long values in SQL Server identity seed values cause older int values to no longer work.
Some common migrations scaffolded with earlier versions of EF Core cause errors in EF Core 6.0.
**How found**
Customer reports on RC1
Added in this PR
Yes
**Risk**
Low, this simply adds support for the legacy int annotation values in two code sites.
> [6.0-rc2] Fully support int identity seed

- benchmark/EFCore.Benchmarks/UpdatePipeline/SimpleUpdatePipelineTests.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/Shared/Multigraph.cs
- test/EFCore.Tests/Utilities/MultigraphTest.cs
https://github.com/dotnet/efcore/pull/25952 decreased throughput in mixed update scenario by about 20-40%. These changes mostly remove this degradation:
- When sorting update commands add Deleted + Inserted number of edges instead of Deleted * Inserted
- Don't allocate a collection for edges if there's only one edge between given two vertices
- Reuse the `Multigraph` instance
- Change the benchmark to reuse the context instance to simulate pooling behavior
<details>
<summary>Before #25952</summary>
|         Method | Async | Batching |     Mean |   Error |  StdDev |  Op/s |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------- |------ |--------- |--------- |-------- |-------- |------ |---------- |------ |------ |---------- |
| UpdatePipeline | False |    False | 122.4 …
> When sorting update commands add Deleted + Inserted number of edges instead of Deleted * Inserted

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Fixes #23937
#22845 made the join entity type use the same schema as the related entity types, but it didn't persist the schema in the migration snapshot.
A new migration is created even if there are no model changes.
**How found**
Customer report
Added in this PR
No
**Risk**
Low, this only affects the migration snapshot, which can be fixed manually.
> Always store join table schema in the snapshot.

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Project.cs
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/dotnet-ef/Resources/EntityFrameworkCore.targets
- src/dotnet-ef/RootCommand.cs
The new OS-specific TFMs introduced in .NET 6 (net6.0-android, net6.0-ios, etc.) currently aren't compatible with dotnet-ef and the PMC commands. This adds additional checking like the ones we already have for unsupported TFMs (Xamarin.Android, Xamarin.iOS, etc.) and throws a better error message.
Fixes #25938
Note, another issue (#7152) tracks making them actually work when we can.
Without this, customers will continue getting obscure errors about missing .deps.json files.
Yes, kind of. While the OS-specific TFMs are new to .NET 6, the *experience* of working with Android and iOS projects has regressed from .NET 5.
Manually verified the new experience on VS 2022 Preview 4. We have not invested in automated functional testing for dotnet-ef and the PMC commands since this made the build …
> [6.0] Tools: Check for unsupported OS-specific TFMs

- src/EFCore.Relational/Metadata/Conventions/CheckConstraintConvention.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Internal/CheckConstraint.cs
- src/EFCore.Relational/Metadata/Internal/InternalCheckConstraintBuilder.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
Fixes #23399
Currently when an entity type is converted to a shared-type entity type the check constraints are just copied over, without updating the back reference to the entity type.
Without this fix migrations throw an error when performing the diff.
Customer
No.
Low, the modified code only affects STETs with check constraints - a relatively rare scenario.
> Update the entity type on check constraints when it's converted to a STET

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsCollectionsSharedTypeQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsCollectionsSplitSharedTypeQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindGroupByQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindKeylessEntitiesQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindSelectQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindSetOperationsQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Updating the message and resource string name to reflect the changes in behavior after we've improved this scenario.
Fixes #24490
> [6.0] Fix to #24490 - Update exception message when correlated collection cannot be projected

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Metadata/RuntimeEntityType.cs
- src/EFCore/Metadata/RuntimeModel.cs
- src/EFCore/ValueGeneration/DiscriminatorValueGeneratorFactory.cs
- src/EFCore/ValueGeneration/Internal/DiscriminatorValueGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Specification.Tests/CompositeKeyEndToEndTestBase.cs
Optimize the discriminator value in the runtime model
Fixes #18126
> Use the correct value when the discriminator is part of the key.

- src/EFCore/DbContextOptions.cs
- src/EFCore/DbContextOptions`.cs
- test/EFCore.Specification.Tests/LoggingTestBase.cs
- test/EFCore.Tests/ServiceProviderCacheTest.cs
Fixes #26071
The extension services are applied in alphabetic order instead of the order in which they were added.
The fix requires breaking some protected API on `DbContextOptions`, but this class is designed to use composition, not inheritance, so it shouldn't affect any external code.
Extensions that depend on a provider being registered will throw errors if they happen to be sorted before the provider.
Customer
Yes, introduced in rc1 by 4e3ce4e13036eaeac700b2a08faa0d45270beb6e
Low, this reverts the behavior to pre-rc1.
> Preserve extension registration order

- src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs
- src/Microsoft.Data.Sqlite.Core/Utilities/BundleInitializer.cs
We have code for UWP that sets the SQLite data and temp directories so that databases can be created when running inside an app container sandbox. .NET 5 added new bindings for WinRT APIs, and our code no longer ran on .NET 5/6 apps requiring users to manually set the SQLite directories.
Fixes #24213
/cc @Pilchie
Without this, the experience of using SQLite in MSIX-packaged windows apps would continue requiring additional, non-obvious steps.
Not in .NET 6, but the experience was regressed going from UWP to MSIX-packaged .NET 5 apps.
We don't have any automated tests that run inside of a sandboxed app container. Manually verified that databases are now created correctly. (using winsqlite3.dll)
Low. We're just probing for one additional assembly; if it fails, execution continues the same as …
> [6.0] Microsoft.Data.Sqlite: Also try the .NET 5+ ApplicationData API

- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipStringTest.cs
Fixes #23362
Shadow skip navigations are not supported, but currently we don't explicitly validate this.
Without this an obscure `ArgumentException` is thrown when the navigation is used in a query.
Customer
No.
Low, just a better exception message.
> Improve exception message for a shadow skip navigation

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
Fixes #26134
Incorrect migration generated when the HiLo value generation strategy is configured.
Generating migrations with a model-wide HiLo value generation strategy creates an invalid migration.
Customer
Yes
Low, the bug is trivial and the modified code only annotation generation for this particular scenario; coverage is good in this area.
> [6.0] Fix snapshot generation with HiLo

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Fixes #24789
Once `HasNoKey` is called there is no way of override it using Fluent API.
When extending an external model or a model created by scaffolding customers need to use low-level Metadata API to override `HasNoKey`
Customer
No.
Low, the effect of the change is straightforward.
> Allow HasKey to override HasNoKey

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
Fixes #24373
Using a keyless entity type as the principal is invalid, however we didn't have an explicit check for this.
Without this an NRE is thrown when a keyless entity type is used as the principal.
Customer
No.
Low, just a better exception message.
> Throw a better exception for relationships to keyless entity types

- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
Fixes #25388
One more than two properties share a column we fail to mark them as `ValueGenerated.OnUpdateSometimes`
`SaveChanges` with an entity involving a shared column will fail unless the customer calls `ValueGeneratedOnUpdateSometimes` explicitly on every property sharing the column.
Customer
Yes. Regressed in 5.0.0. Previously we didn't validate whether a given property could get its value from a different property sharing the same column.
Low, only affects scenarios with more than two properties sharing any given column.
> Set ValueGenerated.OnUpdateSometimes when more than two properties share the same colum

- src/ef/Commands/DbContextOptimizeCommand.cs
- src/ef/Commands/MigrationsListCommand.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
Fixes #25153
Without this, users will get this lovely error if they try to run `dotnet ef dbcontext optimize` on projects using EF Core 5.0 and 3.1:
> Could not load type 'Microsoft.EntityFrameworkCore.Design.OperationExecutor+OptimizeContext' from assembly 'Microsoft.EntityFrameworkCore.Design, Version=5.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
No--feature is new in 6.0.
Manually verified. We don't have any automated tests mixing EF Core 5.0 projects and 6.0 tools.
Low.
> [6.0] Tools: Warn/error when using new features on old runtimes

- src/EFCore.SqlServer.NTS/Scaffolding/Internal/SqlServerNetTopologySuiteCodeGeneratorPlugin.cs
- test/EFCore.SqlServer.Tests/Scaffolding/SqlServerCodeGeneratorTest.cs
- test/EFCore.Sqlite.Tests/Scaffolding/SqliteCodeGeneratorTest.cs
Fixes #26133
An incorrect type reference prevents scaffolding from working correctly when NetTopologySuite is used.
Customers cannot scaffold databases when using the NetTopologySuite spatial plugin.
Customer
Yes
Very low, the fix is trivial and affects scaffolding only (no runtime impact)
> [6.0] Fix SQL Server NTS scaffolding code generation

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
Fixes #26156
EF Core 6.0 adds support for the new .NET DateOnly/TimeOnly types, but code literal generation support was left out.
Customers cannot scaffold migrations which seed DateOnly/TimeOnly data 
Customer
No, DateOnly/TimeOnly support is new in EF Core 6.0
Very low, the fix is trivial and affects migration scaffolding only (no runtime impact)
> [6.0] Code literal support for DateOnly/TimeOnly

- src/EFCore.Cosmos/Metadata/Conventions/CosmosValueGenerationConvention.cs
- src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Fixes #25167
Cosmos doesn't support value generation, however integer properties were marked as `ValueGenerated.OnAdd`. Only `Guid` properties and the non-persisted `int` ordinals for embedded collections are generated on the client.
Attaching an entity with an integer key will mark it as Updated instead of Added resulting in an error on the next `SaveChanges`
Customer
No
Low, only affects scenarios with value generation, which are not supported in Cosmos.
> Cosmos: Set ValueGenerated.Never for most integer properties

- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
We were not applying mapping to InExpression and it's constituents which could lead to failed translations when these expressions were constructed manually (e.g. as part of UDF translation)
Fixes #26084
> [6.0] Fix to #26084 - Query: SqlExpressionFactory doesn't apply type mapping to InExpression

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- test/EFCore.InMemory.FunctionalTests/Query/OwnedEntityQueryInMemoryTest.cs
We did optimization that required dependent can generate join rather than left join but that is dependent if the owner is nullable or not.
Resolves #26157
> [6.0] InMemory: Expand owned navigation as optional always

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Problem was that for idempotent migration scripts that convert non-temporal table to temporal we need to wrap the period switching statement in exec. Otherwise sql parser(?) complains that the command is invalid because period already exists. This is a false negative - the statement will not actually execute if this migration has already been applied. Exec fixes the problem since the statement inside it can't be parsed. This is how we deal with similar issues in other places in the code.
Fixes #26166
> [6.0] Fix to #26166 - Idempotent migration script generates problematic temporal table alter statement

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
> [6.0] RevEng: Initialize skip collection navigations in ctor

- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
- src/EFCore.Design/Design/Internal/DesignTimeConnectionStringResolver.cs
- src/EFCore.Design/Design/Internal/IDesignTimeConnectionStringResolver.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- src/EFCore.Relational/Storage/Internal/NamedConnectionStringResolver.cs
- src/EFCore.Relational/Storage/Internal/NamedConnectionStringResolverBase.cs
- test/EFCore.Design.Tests/Design/DesignTimeServicesTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs
Fixes #26169
The issue here is that we started TryAdding design time services, which is good since it allows for overrides. However, it meant that for INamedConnectionStringResolver we were not replacing the runtime service, which then null-reffed at design time. Fix is to make them different services so one does not have to override the other.
> [6.0] Separate design time and runtime service for NamedConnectionStringResolver

- src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.Tests/ModelBuilding/ManyToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Fixes #26208
When an explicit join entity type is used we don't discover the foreign key properties that would have match the name for the shadow properties we created.
Users would need to add additional configuration for the foreign keys, diluting the value of the new simpler `UsingEntity` overloads.
Docs writing
No, this mainly impacts the new `UsingEntity` overloads
Low, this mainly impacts the new `UsingEntity` overloads. It is a breaking change from RC2 if the shadow FKs were left unconfigured, though this shouldn't be common.
> Discover join type FK properties using the same naming convention as when creating them

- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindMiscellaneousQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindIncludeNoTrackingQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
Fixes #26227.
This fixes a :facepalm: bug where calling `AsTracking` with `NoTrackingWithIdentityResolution` was not being respecting and the query would be executed with `NoTracking` instead.
> [6.0] Respect AsNoTrackingWithIdentityResolution in AsTracking method

- src/EFCore/DbContext.cs
- src/EFCore/Internal/DbContextLease.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Fixes #26202
When using DbContext pooling, the DbContext disposal logic modifies the state after the context has been returned to the pool, creating a race condition with possible consumers renting the context out of the pool.
When using DbContext pooling, an ObjectDisposedException may occur when using a pooled context. This is the kind of bug that only happens very occasionally but then will cause the application to fail unexpectedly and in a way that is difficult to diagnose. This means lack of customer reports doesn't mean it isn't impacting overall reliability of apps that use EF Core.
No; exists in 5.0 also. We intend to backport there. Does not happen on 3.1.
Low, the fix is quite simple.
We may want to revisit and simplify …
> [6.0] Fix context pooling concurrency issue

- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Cosmos.FunctionalTests/KeysWithConvertersCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/KeysWithConvertersInMemoryTest.cs
- test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs
Fixes #26116
Initial issue was that the converted type also required a comparer. On adding one it revealed that in this case a default comparer was being used for the dependent map in the state manager. Fix is to use the PK comparer in the same was as we use the PK converter.
Added more testing for similar cases including generated shadow FKs.
> [6.0] Use correct value comparer for generated FK properties

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
Part of #26167
An exception is thrown for a certain pattern of raw SQL query that then uses `.Any` in LINQ. Fixing this for 6.0 is considered too risky, but we can detect when we're going to throw the exception, so we are making that exception more helpful. The workaround is to use `.Count` instead, which is pretty easy once it is known.
This is a relatively simple query, so we expect more customers to hit this. Helping them find the workaround will be useful.
Yes, in 6.0.
Tests added to make sure that the new exception is thrown.
Low. The fix just changes the exception thrown.
> [6.0] Query: Throw for FromSql+Any pattern which has been mutated

- azure-pipelines.yml
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
> Switch to 1ES servicing pools on release/3.1

- src/EFCore/DbContext.cs
- src/EFCore/Internal/DbContextLease.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Backports #26226 to 5.0.x, fixes #26202.
When using DbContext pooling, the DbContext disposal logic modifies the state after the context has been returned to the pool, creating a race condition with possible consumers renting the context out of the pool.
When using DbContext pooling, an ObjectDisposedException may occur when using a pooled context. This is the kind of bug that only happens very occasionally but then will cause the application to fail unexpectedly and in a way that is difficult to diagnose. This means lack of customer reports doesn't mean it isn't impacting overall reliability of apps that use EF Core.
Yes, was not present in 3.1.
Low, the fix is quite simple.
> [5.0.x] Fix context pooling concurrency issue

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Relational.Tests/Query/Internal/QuerySqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
And specifically throw for SQL Server.
Fixes #26471
> Identify WITH as generally composable in FromSql

- src/Shared/MethodInfoExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindAggregateOperatorsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
> Query: Identify Contains on IReadOnlySet/IImmutableSet

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
Version 5.0.0 of the dotnet-ef tool introduced the `--no-onconfiguring` option which is great if you plan to configure your DbContext outside of the context itself (which you probably should).
When using this option, the DbContext class is still generated with a default constructor. This default constructor becomes problematic without the `OnConfiguring` method since the context is unusable when created through the default constructor. As soon as you try to use a DbContext created by the default constructor, you get a `System.InvalidOperationException`:
> No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then …
> Do not scaffold a default constructor when OnConfiguring is suppressed

- test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
Correct tests to call correct base class method
- Create_sequence
- Create_sequence_all_settings
- Alter_sequence_all_settings
- Alter_sequence_increment_by
- Drop_sequence
- Rename_sequence
- Move_sequence
Fixes #26571
```
- Detail 1
- Detail 2
```
> Fix MigrationsSqliteTest tests

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
> CREATE SEQUENCE for decimal (sql server)

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Resolves #26496
We had mechanism to generate unique identifiers to assign to skip navigations but the code to find existing identifiers lacked skip navigations. So skip navigation names were not unique-fied throwing error when trying to add skip navigation with same name
An exception is thrown when trying to scaffold model from database where a table has multiple skip navigations to different entity type but same fk properties giving same name to skip navigation.
A database containing such table cannot be scaffolded into model. There are no work-arounds.
**How found**
Customer report on nightly rtm package.
**Regression**
No, feature to scaffold many to many join table is new in 6.0. However, a database that could have been scaffolded previously to a …
> [6.0.1] RevEng: Consider skip navigation names when generating identifier for members of class

- src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
Fixes #26436
An exception is thrown when configuring a foreign key on the principal side of the foreign key configured by data annotations.
There aren't simple workarounds other than removing the attribute, because the exception is thrown during a convention invocation.
Customer report on RC2.
Yes, from 5.0, introduced in https://github.com/dotnet/efcore/pull/25211.
Low; the fix is adding a `null` check that existed previously. Not adding a quirk mode as that would just result in an exception being thrown.
> Avoid NRE in ForeignKeyAttributeConvention

- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Fixes #26429
An exception is thrown when configuring nullable properties with a non-nullable value comparer via pre-convention model configuration.
The only workaround is to avoid using pre-convention model configuration and configure each property explicitly.
Customer report on RC2.
Yes, from RC1 in https://github.com/dotnet/efcore/pull/25969. However, this is a new feature in 6.0
Test for this scenario added in the PR. Tests for value comparers with different nullability are already present, but don't use model building.
Low; the fix is to not throw an exception for a specific case.
> Allow non-nullable value comparer to be applied on nullable properties

- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
- src/EFCore/Design/EntityFrameworkDesignServicesBuilder.cs
- test/EFCore.Cosmos.FunctionalTests/Query/FromSqlQueryCosmosTest.cs
- test/EFCore.Design.Tests/Design/Internal/OperationLoggerTest.cs
- test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
- test/EFCore.Design.Tests/TestUtilities/DesignTestHelpers.cs
- test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- test/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- test/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- test/EFCore.Specification.Tests/TestUtilities/TestOperationReporter.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Fixes #26384
Log messages produced by provider-specific services invoked by the EF CLI tools are no longer displayed.
There isn't a practical workaround as the reporter object is not accessible by the user.
Customer report on RC2.
Yes, from 5.0, introduced in https://github.com/dotnet/efcore/pull/25509
This PR changes tests to use DI to add coverage for this scenario.
Low; the fix only affects design-time logging. Quirk mode not added as there isn't a practical way to access `AppContext` used by CLI tools.
> Register design-time LoggerFactory as Scoped

- src/EFCore.Cosmos/Query/Internal/CosmosValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Resolves #26428
An exception is thrown when running query which has value converters used for predicate.
Query which could work will not work and throw exception.
Customer report on RC2.
Yes, from EF Core 5.0
Test for this scenario added in the PR. Other tests verifies that change is not generating something incorrect.
Low; the fix is to update SelectExpression through Update method correctly.
> [6.0.1] Query: Copy client projections when updating SelectExpression

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
Hooks AppDomain.ProcessExit to clean up native resources.
Fixes #26422
Databases using the write-ahead journal mode (the default for ones created by EF Core) create additional temporary files next to the database file. These files are cleaned up when the native connection is closed.
Previously, Microsoft.Data.Sqlite relied on DbConnection.Close, IDisposable, and finalizers to close the native connection.
A connection pool was added in 6.0 which keeps the native connection open after the DbConnection is closed/disposed/finalized.
Even though we leverage SafeHandle to close native connections, these finalizers are not called when the application is exits. This results in the temporary files not being properly cleaned up.
Yes, the connection pool was added in 6.0. The temporary files were …
> [6.0.1] Microsoft.Data.Sqlite: Clean up on application exit

- azure-pipelines.yml
The build was earlier removed due another issue, re-adding and moving
> [[6.0.1] Move to OSX 11.0 for helix queues

- azure-pipelines.yml
The build was earlier removed due another issue, re-adding and moving
> Move to OSX 11.0 for helix queues

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Scoping causes clash in names.
Resolves #26588
> RevEng: Don't use nameof syntax

- src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
- src/EFCore.Cosmos/Query/Internal/CosmosStringMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
> Query: SqlServer: Add translation for string.IndexOf(string, int)

- build/templates/default-build.yml
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
> Switch to 1ES servicing pools on release/2.1

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- Also unwrap convert node around projection when translating Contains
Resolves #26593
When writing query which has multiple subquery Contains if the inner Contains is on entity type or value type then translation fails.
User query will throw exception with no easy way to figure out work-around
**How found**
Customer reported on RTM package
**Regression**
Yes, the query worked in 5.0 release.
**Testing**
Added test for customer scenario and similar kind of queries.
**Risk**
Low. Recursive visit should be no-op if there is no other relevant parts inside. Also added quirk to go back to earlier behavior.
> [6.0.1] Query: Optimize Contains to Any recursively

- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/MigrationsSqliteTest.cs
> Add test coverage for index recreation

- src/EFCore/ChangeTracking/ValueComparer.cs
Fixes #26672
```
- Detail 1
- Detail 2
```
> Use EqualsExact in DefaultDateTimeOffsetValueComparer

- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
Fixes #26590
When an FK attribute is used with a property on a property bag entity type EF ends up creating a property with a uniquified name instead of using the specified one.
This is made worse in 6.0 because now EF scaffolds this type of configuration for existing databases.
User queries will throw exception since the new property doesn't match a column in the database
**How found**
**Regression**
Yes, this worked in 5.0
**Testing**
**Risk**
Low, only affects property bag entities (`Dictionary<string, object>`). Also added a quirk mode.
> Match indexer properties correctly

- All.sln
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Fixes #26632
When the entity types have store-generated primary keys invalid SQL is produced when a single entity of one type as well as 3 or more (or the amount specified in `MinBatchSize`) are inserted together.
`SaveChanges` produces invalid SQL that results in an exception. The workaround would be to call `SaveChanges` after each batch of specific entity type is added, but this isn't always practical.
**How found**
**Regression**
Yes, this worked in 5.0. Introduced in #25718
**Testing**
**Risk**
Low, the change has very predictable impact. Also added a quirk mode.
> Use a unique identifier for variables during insert

- src/Microsoft.Data.Sqlite.Core/Utilities/ApplicationDataHelper.cs
In 6.0, we enabled our UWP code for detecting the temp and data directory to work on the new `net5.0-windows` (and 6.0) TFMs. For some reason on .NET Core 3.1, this also causes `GetType("Windows.Storage.ApplicationData")` to return non-null now but `GetProperty("LocalFolder")` to return null leading to a NullReferenceException.
Fixes #26574
Because this code runs during static initialization of the ADO.NET connection type it is impossible to work around this issue making it impossible to use the 6.0.0 version of Microsoft.Data.Sqlite on .NET Core 3.1 on Windows.
Yes, from 5.0.
Low. The new handling of `null` results in the same code path that has been used for several releases.
Verification. Manually verified that the library can be used on .NET Core 3.1. Our automated tests only execute …
> [6.0.1] Microsoft.Data.Sqlite: Handle more nulls in ApplicationDataHelper

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
Resubmit of #26658 which was accidentally merged before tactics approval and reverted in #26696. This is identical to #26658 and has already been approved by the team.
As this is being considered for servicing, I went with the least invasive/risky option, and introduced read/write locking. Using a ConcurrentDictionary is definitely possible, but would require other changes - specifically in how pruning is implemented. We can clean this up and improve for 7.0. I couldn't repro this in some quick testing efforts (tricky concurrency issue), if we think it's really worth it I can spend more time on it.
Fixes #26612
Locking is missing when looking up a pool group in a Dictionary in SQLite's pooling implementation.
If code happens to look up a pool group at …
> [6.0.1] Use read-write lock to protect concurrent pool accesses (#26658)

- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupCompositeTest.cs
Fixes #26629
We added code in 6.0 to find the corresponding principal key property of a foreign key property when looking for value comparers. However, we missed the case where the foreign key property is itself the principal key for another overlapping relationship. This can happen when two entity types act as principal and dependents of each other, with one having a composite foreign key containing the principal key of the other. In this case, the code goes into an infinite loop.
Stack overflow when a model of this form is used. This is not a super common model, but is also not extremely rare, so we expect many more people to hit this as the update to 6.0.
**How found**
Customer reported on 6.0.
**Regression**
Yes, from 5.0.
**Testing**
Added this …
> [6.0.1] Avoid infinite loop when finding principal in circular relationships

- src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqlitePropertyBuilderExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteByteArrayMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteCharMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateOnlyMemberTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeMemberTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteGlobMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteHexMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMathTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitorFactory.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteRandomTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteStringLengthTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteStringMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSubstrMethodTranslator.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommandBatchFactory.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
> Evolve null-checking approach in SQLite provider

- src/EFCore/Metadata/Internal/InternalForeignKeyBuilder.cs
- test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
Fixes #26611
When `IsRequired()` is called for a foreign key specified on a shadow property we replace the property to change in to a non-nullable type. This invalidates the current reference held by the builder.
All method calls after `IsRequired()` for a foreign key specified on a shadow property will throw an exception. A workaround would involve separating these calls and repeating some of the setup.
**How found**
**Regression**
Yes, this worked in 5.0
**Testing**
**Risk**
Low, the fix is to update the foreign key reference held by the builder. Also added a quirk mode.
> Update the foreign key builder after IsRequired()

- src/EFCore/Metadata/Internal/PropertiesSnapshot.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Fixes #26659
When `OwnsMany()` is called for a navigation of the same CLR type the second type the target entity type is converted to a shared-type entity type. All existing components, like indexes are then reattached to the new entity type, however the incorrect entity type builder was used for nested owned entity types.
When a nested owned entity type has a configured index the second `OwnsMany()` call throws an exception. A workaround would be to configure the index after the second `OwnsMany()` call.
**How found**
**Regression**
Yes, this worked in 5.0
**Testing**
**Risk**
Low, the fix is to avoid using an entity type that's no longer in the model.
> Use the correct builder when attaching indexes on nested owned entity types

- azure-pipelines.yml
Kept Mac OS in place because it is different version and provides us testing of compiling on windows and testing on non-windows
Kept Ubuntu SqlServer one, hopefully we will get SqlServer running at some day.
> Remove Windows/Ubuntu from helix testing as other pipeline covers it

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
Fixes #26651
We started including the default schema in each `ToTable` call in the model snapshot, even if it was to mark an entity type as not mapped - `ToTable(null, "schema")`, which doesn't work.
If the model has a default schema and unmapped entity types the model snapshot in the generated migration throws an exception when used.
**How found**
**Regression**
Yes, this worked in 5.0
**Testing**
**Risk**
Low, the fix just affects models with unmapped entity types. Also added a quirk mode.
> Return null schema for unmapped entity types.

- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Additional tests for Temporal tables when HasDefaultSchema is configured at the DbContext level .
> Additional tests for Temporal tables

- src/EFCore.Relational/Metadata/Builders/DbFunctionBuilder.cs
- src/EFCore.Relational/Metadata/Builders/IConventionDbFunctionBuilder.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Query/IMethodCallTranslatorPlugin.cs
- src/EFCore.Relational/Query/SqlExpressions/ProjectionExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlParameterExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Metadata/Builders/PropertyBuilder.cs
- src/EFCore/Metadata/Builders/PropertyBuilder`.cs
- src/EFCore/Metadata/IConventionPropertyBase.cs
- src/EFCore/Metadata/IMutablePropertyBase.cs
- src/EFCore/Storage/ValueConversion/ValueConverter.cs
- src/EFCore/Storage/ValueConversion/ValueConverter`.cs
- src/EFCore/ValueGeneration/SequentialGuidValueGenerator.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
Fixes #26667
Fixes #26591
Fixes #26718
Fixes #26443
> Fix some docs issues

- docs/security.md
- Add syntax highlight to C# and SQL code blocks.
- Fix some code mistakes.
> Fix some markdown language syntax highlights

- .github/CONTRIBUTING.md
- test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
Team, I give you SUPERB - the Supreme Ultimate Programmatic Enhancement for Rewriting Baselines.
If the environment variable EF_TEST_REWRITE_BASELINES is set to 1, any SQL assertion failure will cause the baseline to be updated to the new baseline in the original source file. This is implemented by using Roslyn to parse the source and find the AssertSql invocation expression, which is then replaced. I have nothing against reptile-based methods, but this seems more reliable and doesn't require any extra steps.
Just set the env var, make some huge change and see how it ripples by looking at the git diff!
> Test mechanism to automatically rewrite baselines in source code 

- src/EFCore.Relational/Query/Internal/FromSqlQueryRootExpression.cs
- src/EFCore.Relational/Query/Internal/TableValuedFunctionQueryRootExpression.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.CrossStore.FunctionalTests/QueryTest.cs
Query root design
Core exposes QueryRootExpression which is base class for any query root so we can access EntityType out of it. This is needed for nav expansion and any potential future use case.
Since any derived query root would derive from it, core assembly translates it only when type is exact match to QueryRootExpression.
Relational layer also processes QueryRootExpression when they are mapped to default SqlQuery, which also uses exact type match now.
Apart from QueryRootExpression, no other kind of query root which can appear in different providers should be derivable (else they need to use exact type match too).
This rule makes relational ones sealed class. In case any one needs to derive from it, they need to add additional processing anyway.
Provider specific derived query roots …
> Query: Throw error for unhandled derived query root expression

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
> Query: Fix double negation in SQL generation

- src/EFCore.Cosmos/Query/Internal/CosmosMemberTranslatorProvider.cs
- src/EFCore.Cosmos/Query/Internal/CosmosValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/SelectExpression.cs
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
- src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlBinaryExpression.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerFromPartsFunctionTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
> Static analysis: remove trailing commas

- src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
- src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.ShaperExpressionProcessingExpressionVisitor.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/CheckConstraintConvention.cs
- src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
- src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
- src/EFCore.Relational/Metadata/Internal/InternalCheckConstraintBuilder.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Migrations/MigrationBuilder.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Storage/RelationalCommand.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/dotnet-ef/Project.cs
> Static analysis: Use ??=

- src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
- src/EFCore.Design/Scaffolding/Internal/CompiledModelScaffolder.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.Relational/Extensions/RelationalModelExtensions.cs
- src/EFCore.Relational/Metadata/Builders/DbFunctionParameterBuilder.cs
- src/EFCore.Relational/Metadata/Internal/InternalDbFunctionBuilder.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/StoreFunctionParameter.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Storage/RelationalCommand.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMathTranslator.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/ef/Commands/MigrationsBundleCommand.cs
> Static analysis: remove redundant nullable warning suppression

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- src/EFCore.Design/Design/Internal/MigrationsOperations.cs
- src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
- src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpUtilities.cs
- src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
- src/EFCore.Proxies/Proxies/Internal/LazyLoadingInterceptor.cs
- src/EFCore.Proxies/Proxies/Internal/PropertyChangeInterceptorBase.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsIdGenerator.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
- src/EFCore.Relational/Storage/Internal/NamedConnectionStringResolverBase.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/TemporalTableExpression.cs
- src/EFCore/Diagnostics/LoggerCategory.cs
- src/EFCore/Extensions/Internal/TypeExtensions.cs
- src/EFCore/Metadata/Conventions/BackingFieldConvention.cs
- src/EFCore/Metadata/Internal/PropertyParameterBindingFactory.cs
> Static analysis: use range indexer and index from end

- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/IChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/INavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
Fixes #26779
Also cleanup of delay-fixup/suspended detection logic, and tests for #26074.
> Fixup navigations to/from join entity when new many-to-many relationship is created

- src/EFCore/Storage/ExecutionStrategy.cs
- test/EFCore.Specification.Tests/TestUtilities/SingleThreadSynchronizationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Tests/Storage/ExecutionStrategyTest.cs
> Preserve synchronization context in ExecutionStrategy

- src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs
- src/EFCore/Metadata/Conventions/NonNullableReferencePropertyConvention.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs
One possible design question...
* NRT nullability is computed in a convention, but not value type nullability; that's just hard-coded in [Property.DefaultIsNullable](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/Internal/Property.cs#L187).
* We want NRT computation to be in a convention, since there's a [NullabilityInfoContext](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.nullabilityinfocontext?view=net-6.0) which caches stuff for perf.
* We could have a single convention setting IsRequired for both NRTs and value types (NullabilityInfoContext detects for those too), but this could possibly be heavier perf-wise. Also not sure it's worth it, /cc @AndriySvyryd.
Also see #26966 which was discovered as part of this.
Closes #24744
> Replace our nullability decoding with the new BCL API

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
Fixes #26779
When a many-to-many relationship is created and then removed, the state of the join entity that represents this relationship is incorrectly changed to `Deleted`. This results in an attempt to delete a row in the database that does not exist.
Exception thrown when calling SaveChanges after adding and then removing a new many-to-many relationships.
This is a fairly fundamental error. What is not clear is why this was not reported before now, since the behavior existed in 5.0. It's possible people didn't realize it was a bug and having been manually detaching the join entity to make this scenario work.
**How found**
Customer reported on 6.0.
**Regression**
This is not a regression; the same behavior existing in 5.0. However, we believe that it …
> [6.0.2] Detach join entity when removing added relationship

- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Relational/Migrations/HistoryRepository.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/DbContext.cs
- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
- src/EFCore/Infrastructure/Internal/LazyLoader.cs
- src/EFCore/Infrastructure/PooledDbContextFactory.cs
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- src/EFCore/Storage/ExecutionStrategyExtensions.cs
- test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.Tests/SqlServerOptionsExtensionTest.cs
- test/EFCore.Tests/DbSetTest.cs
Fixes #26790, replaces #26793
As part of logging path optimizations in 6.0, an (unawaited) async connection Close method call was accidentally introduced in a synchronous code path. In addition, while investigating this some cases of missing ConfigureAwait(false) were discovered.
In some providers, where pooling isn't used, the unawaited async call causes a race condition with unknown effects, potentially crashing the application. The cases of missing ConfigureAwait(false) could potentially cause EF Core code to run in the user's synchronization context instead of on the thread pool.
**How found**
A customer reported the unawaited async call on 6.0. The other two issues were found as a result of fixing an analyzer issue which suppressed warnings. …
> [6.0.2] Call sync connection close instead of async

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Fixes #26405
If no explicit order is specified we determine the column order partially based on the property declaration order on the CLR types. However for down migrations the snapshot is used and it doesn't have associated CLR types. `Dictionary<string,object>` is used as a stand-in and all properties and navigations are mapped to the indexer. When sorting foreign key properties this causes an exception as the same property info is used as the key multiple times.
An exception is thrown when creating a migration for a table rename with two or more navigations. There isn't a practical workaround.
Customer report on RC2. 7 reports so far.
Yes, from 5.0
This PR adds coverage for this scenario.
Low; the fix only affects column order in migrations produced during design-time. Quirk mode not …
> [6.0.2] Handle duplicate property infos when sorting columns.

- src/Shared/Multigraph.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Fixes #26834
Due to a bug fix EF lost the ability to break table cycles where each table participates in multiple cycles.
An exception is thrown when adding a migration that creates tables linked by multiple foreign key cycles. A workaround would be to add tables without foreign key first, then create another migration for the foreign keys.
Customer report on 6.0.0.
Yes, from 5.0. Regressed by https://github.com/dotnet/efcore/pull/25952
This PR adds coverage for this scenario.
Low; the fix only affects migrations produced during design-time. Quirk mode not added as there isn't a practical way to access the `AppContext` used by CLI tools.
> [6.0.2] Restore the ability to break multiple FK cycles

- src/Shared/Multigraph.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
- test/EFCore.Specification.Tests/UpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
Fixes #26750
Due to a bug fix we now sort Deletes before Inserts for the same table to avoid deadlocks. However in some cases this ordering can create a dependency cycle in the operations.
This fix is the same as in https://github.com/dotnet/efcore/pull/26959, but applied to a different method.
An exception is thrown when adding and removing related self-referencing entities in the same transaction. A workaround would be to remove the entities first then add them in a separate transaction.
Customer report on 6.0.0.
Yes, from 5.0. Regressed by https://github.com/dotnet/efcore/pull/25952
This PR adds coverage for this scenario.
Low; the fix only affects update command ordering. Quirk mode added.
> [6.0.2] Add the ability to break self-ref cycles between added and removed entities

- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/OwnedEntityQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedEntityQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
Issue: Expanding owned navigations in relational falls into 3 categories
- Collection navigation - which always generates a subquery. The predicate is generated in LINQ to allow mutation of outer SelectExpression
- Reference navigation sharing table - which picks column from same table without needing to add additional join. This only mutate the projection list for SelectExpression at subquery level
- Reference navigation mapped to separate table - which generates additional joins. Generating join can cause push down on outer SelectExpression if it has facets (e.g. limit/offset). This pushdown causes owned expansion from category 2 to be outdated and invalid SQL since they get pushed down to subquery. While their relevant entity projection is updated inside SelectExpression we already …
> [6.0.2] Query: Defer inline-ing owned navigation expansion till all joins are generated

- test/EFCore.Specification.Tests/TestUtilities/SingleThreadSynchronizationContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
I can't really see how the failure in #26996 could be possible (and have failed to reproduce it) - but here's a small tweak which should if the test code happens to complete synchronously (which doesn't make much sense to me).
> Tweak SaveChangesAsync_accepts_changes_with_ConfigureAwait_true_22841

- src/Directory.Build.props
Enable the compiler "strict" option. No new errors were generated as a result; I suspect that the recent "warning waves" feature simply integrated all of strict's diagnostics and made it unneeded - but there doesn't seem to be any harm in enabling it. 
@sharwell any comment?
Closes #14502
> Enable strict compilation

- benchmark/Directory.Build.props
- rulesets/EFCore.test.ruleset
- rulesets/FxCop.test.ruleset
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.Relational/Storage/RelationalTransaction.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- src/EFCore/Metadata/Conventions/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- src/EFCore/Storage/ExecutionStrategyExtensions.cs
- test/Directory.Build.props
Also add missing ConfigureAwait(false) and StringComparison.Ordinal, because of a configuration mismatch between FxCop and the built-in diagnostics analyzers.
Fixes #26790
> Call sync connection close instead of async (7.0)

- src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
A simple non-code change.
blog => blog.Posts
Fixes #26983
```
- Detail 1
- Detail 2
```
> WithMany doc: fix the sample expression

- test/EFCore.InMemory.FunctionalTests/Query/Ef6GroupByInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/Ef6GroupBySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/Ef6GroupBySqliteTest.cs
> No test left behind: Ef6GroupByTest

- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
Remove assertions that QueryIterationFailed doesn't appear in the logs, since it may be there because of transient failures from previous retries.
Fixes #27033
> Fix cancellation test flakiness

- src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
- src/EFCore/ChangeTracking/CollectionEntry.cs
- src/EFCore/ChangeTracking/CollectionEntry`.cs
- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/ChangeTracking/EntityEntry`.cs
- src/EFCore/ChangeTracking/NavigationEntry.cs
- src/EFCore/ChangeTracking/ReferenceEntry.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CustomPartitionKeyIdGenerator.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/ValueConvertersEndToEndTestBase.cs
- test/EFCore.Tests/ChangeTracking/EntityEntryTest.cs
- test/EFCore.Tests/ChangeTracking/SkipMemberEntryTest.cs
- test/EFCore.Tests/ChangeTracking/TrackGraphTestBase.cs
Small stuff that I have wanted to do for ages.
Fixes #7390.
> Christmas crackers: Add Property/Reference/etc overloads that take IProperty/INavigation

- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
> Grinding the gears of war

- src/EFCore.Relational/Query/IMethodCallTranslator.cs
Due to EF Core using wrappers to look up methods via reflection (GetRequiredRuntimeMethod), the linker cannot see the dependency on those methods, and trimmed applications fail 
It isn't possible to use EF Core in a trimmed application.
Customer report on 6.0.0.
Yes, from 5.0. Although EF Core 5.0 was never officially trimming-compatible, at least basic scenarios were possible.
Coverage will be added in 7.0, where trimming will be a focus. The fix was verified manually.
Note that EF Core 6.0 still won't be fully trimming-compatible, but this unlocks at least the basic scenarios which customers were asking for.
Very low - the fix only adds an attribute which is meaningful only to the linker.
This uses the [DynamicDependency] attribute to make sure System.Math isn't trimmed when using EF …
> [release/6.0] Add [DynamicDependency] on System.Math for trimming

- src/EFCore.Proxies/Proxies/Internal/ProxyFactory.cs
- test/EFCore.Proxies.Tests/ProxyTests.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseMiscellaneous.cs
Fixes #26602
The C# compiler changed the emit strategy for records in .NET 6 to take advantage of covariant returns. The Clone method now always has a return type that matches the containing type. Castle dynamic proxies throws when attempting to create a proxy for such types. This means EF Core lazy-loading and change-tracking proxies are broken for any record with a base type.
An bug has been filed on Castle proxies (https://github.com/castleproject/Core/issues/601), which is the correct place to ultimately fix this issue. However, since EF Core never needs to override the Clone method for its proxies, the fix here simply excludes the Clone method from the proxies we create.
Proxies for records with base types cannot be used. Reported by multiple …
> [release/6.0] Avoid proxying Clone methods on record types

- src/EFCore.Design/Migrations/Design/MigrationsBundle.cs
- test/EFCore.Design.Tests/Migrations/Design/MigrationsBundleTest.cs
I forgot to set `AllowArgumentSeparator = true` in the bundle's command-line parser. This subverted the remaining code I added to flow additional arguments into application code.
Fixes #26945
Without this, it's impossible to specify application arguments from the migrations bundle. For example, to specify the ASP.NET Core environment to use when applying migrations.
No. Migration bundles are new in EF Core 6.0.
Low. This flag only changes the behavior when specifying `--`. Currently, specifying `--` will result in the following error.
> Unrecognized option '--'
Added a unit test to ensure the flag is set.
Manually verified that arguments can now be flown into the application.
> [release/6.0] Bundles: Allow argument separator (--)

- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
> Don't issue a warning when replacing an optional dependent with non-null values

- src/EFCore.Relational/Metadata/IReadOnlyCheckConstraint.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
Fixes #27059
In 6.0 we started uniquifying check constraint names if there was a conflict in the database, but we also started adding a prefix to all names that didn't have a prefix that we recognized.
This was unexpected and unnecessary, so we decided to revert the prefixing change.
Users get a new migration changing all the check constraint names that don't follow the pattern. The workaround is to manually add overriding configuration for each check constraint.
**How found**
Customer report on 6.0.
**Regression**
Yes, From 5.0
**Testing**
Already present.
**Risk**
Low; only affects migrations. Also added quirk to revert to previous behavior.
> Stop prefixing check constraints.

- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
We copied type from subquery itself which is always Queryable type because of conversion we do. We need to convert it back to enumerable.
Issue happens only when nested level because we use element type so for 1 level queryable is gone. But for nested level we get Queryable<T> as element type on outer which is not assignable from List<T>
The conversion doesn't cause issue with user having Queryable in the result since that throws exception much earlier.
Resolves #27105
When projecting enumerable of enumerable, we didn't assign correct type to expression tree when translating causing it to have incorrect type which later fails when generating compiled code.
Customers with enumerable of enumerable in projection will have query failing.
**How found** …
> [release/6.0] Query: Assign proper type to CollectionResultExpression

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/LikeExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Earlier, we didn't match on exact predicate
Also fix bug in LikeExpression.Equals
Resolves #27102
When projection after group by has an aggregation term which is not aggregate on grouping, incorrect SQL is generated which generates incorrect results or invalid SQL.
Customer queries will either give incorrect result or throw exception with invalid SQL.
**How found**
Customer reported on 6.0.1
**Regression**
Yes, From 5.0
**Testing**
Added test for user scenario which validates non grouping related aggregation.
**Risk**
Very low. Added quirk to revert to previous behavior.
> [release/6.0] Lift GroupByAggregate when correlation predicate matches

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
When replacing columns, we used the outer select expression which had additional joins from previous term whose aliases match tables in current join and it got updated with wrong table.
The fix is to utilize the original tables when replacing columns. These column replacement is to map the columns from initial tables of group by from subquery to outer group by query.
Resolves #27083
This PR is targeting another PR in release/6.0. If the earlier PR is not approved, I will rebase this PR direct on 6.0. The dependency between PR related to group by is to avoid unintentional side-effects between different patch fixes.
When expanding navigation in aggregate operation in projection after GroupBy operator, we lift the joins generated from navigation to main group by query. In …
> [release/6.0] Query: Update column expression correctly when lifting joins from group by aggregate subquery

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindGroupByQuerySqliteTest.cs
Correlate the scalar subquery with parent SelectExpression
Resolves #27094
Certain queries with group by aggregate on multiple level generates stackoverflow exception.
Program crashes with stackoverflow exception.
**How found**
Customer reported on 6.0.1
**Regression**
Yes. Query used to work in 5.0 version.
**Testing**
Added test for customer scenario and similar variations.
**Risk**
Low risk. Also added quirk mode.
> [release/6.0] Query: Avoid stackoverflow in lifting group by aggregate term

- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
This fixes the build failures caused by 021fbcb7f72, and should make the 6.0 build green again.
Sorry for the trouble, should have rebased #26653 before merging.
> [release/6.0] Fix baselines for IS NULL change

- src/EFCore.SqlServer/EFCore.SqlServer.csproj
Due to a [major breaking change](https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.0.md#encrypt-default-value-set-to-true) in SqlClient 4.0, updating to 4.0 breaks all tests that do not use LocalDb.
This PR reverts the update until we can decide how to handle the breaks.
> Reverting SqlClient package upgrade to fix build

- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
Resolves an issue with blob streaming, where a 32-bit PK was always expected - but SQLite stores integers as signed, 64-bit values.
- SqlDataRecord.GetStream changed from using `GetInt32` to `GetInt64`
- Added a new test
Fixes #27138
> fix: #27138, stream with 64-bit PK

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
Earlier we only matched alias and skipped if alias matched. This could happen if the table name starts with same character.
Even if we do deeper match unwinding joins, we cannot match if the join is to subquery (which can be generated when target of navigation has query filter).
Solution:
When applying group by on SelectExpression, remember the original table count. Once Groupby has been applied we cannot add more joins to SelectExpression other than group by aggregate term lifting.
During lifting:
- If aliases of original tables in parent and subquery doesn't match then we assume subquery is non-grouping element rooted and we don't lift.
- If parent have lifted additional joins, one of them being a subquery join, then we abort lifting if the subquery contains a join to lift which is a …
> [release/6.0] Query: Match joined tables properly when lifting for group by aggregate

- src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
We used to skip enumerable parameter because of group join but it is dead code now
Resolves #26964
> Query: Don't skip any parameter in projection

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/EnumHasFlagTranslator.cs
- src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/ExistsExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/InExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/ScalarSubqueryExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- Add an internal state to remember the mutability which is set to false after ApplyProjection is called.
- Add overload of ApplyProjection which ignores shaper to create an immutable select expression to be used as subquery
- Add debug check to verify that all SelectExpression are marked as immutable
~- Clone mapped projection of SqlExpression kind before translating it further to avoid reference sharing with projection which may be applied at later stage~
Resolves #26532 - all those expressions have debug check in ctor
Resolves #26167 - by having more accurate flag for immutability
~Resolves #26104 - by cloning the projection before translating further. This issue may get resolved in other way after pending selector work if we reuse projections from subquery but regardless the change …
> Query: Mark SelectExpression as immutable after projection has been applied

- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerTemporalConvention.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Problem was a discrepancy between RelationalModel build in runtime and the current model (from OnModelCreating) - relational model would set history table schema annotation using the table schema or default schema, however current model wouldn't set those annotations.
Model differ would then pick up on those differences and create migration to set the schema for history table. When building actual migration sql we already compensated for the difference and not generate actual sql code, but the problem persists.
Fix is to improve the temporal convention so that history table schema in current model (more) closely resembles the temporal table schema and therefore is similar to RelationalModel generated in runtime.
Fixes #26676
> Fix to #26676 - EF Core 6 - IsTemporal adds an unnecessary migration when DefaultSchema is configured at the DbContext Level

- azure-pipelines-richnav.yml
- azure-pipelines.yml
- stop building w/ VS2017 in CI
- version of VisualStudio is out of support
- use 1ES machines for official builds
- use Ubuntu 18.04 Helix queue under Ubuntu Docker image
nits:
- move to latest Ubuntu Docker image
> [main] Update build and test machines

- src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
- src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
Add overload to `SqlServerDbContextOptionsBuilder.EnableRetryOnFailure` with `errorNumbersToAdd` without forcing `maxRetryCount` and `maxRetryDelay`
Fixes #27074
Please review
> Add overload to SqlServerDbContextOptionsBuilder.EnableRetryOnFailure with errorNumbersToAdd without forcing maxRetryCount and maxRetryDelay

- azure-pipelines.yml
SqlServer is not starting properly on Ubuntu 1804. Cursory analysis says it needs update to the docker image itself which has very long turn-around time.
> Run Helix SqlServer test on Ubuntu 1604

- src/EFCore/PropertyAccessMode.cs
> Fix typos in PropertyAccessMode

- test/EFCore.InMemory.FunctionalTests/Query/Ef6GroupByInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Fixes #27155
Fixes #27152
Fixes #27278
> Fix non-deterministic tests that fail on postgres

- .github/dependabot.yml
This should enable Dependabot to send PRs once an update is available on nuget.org. From there, we can request that the package be mirrored on the dotnet-public feed. Today, I manually watch for updates on nuget.org. This will automate that part of our workflow.
> Check for updates on nuget.org

- eng/Versions.props
- src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
- src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs
- src/Shared/ReferenceEqualityComparer.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/BuildSource.cs
And suppress CA1814 if multidimensional seed data is present.
Closes #10695
> Add <inheritdoc /> in migrations

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Fixes #27174.
In 6.0, we made a change to fix a "bug" (#25360) where setting the foreign key of an optional relationship to null did not trigger deletion of orphans when the relationship was configured for cascade delete. It turns out that people have been relying on this behavior--i.e. to our users, this was a feature, not a bug.
In addition, the people reporting this a breaking their apps have made a compelling case that orphans should _not_ automatically be deleted for optional relationships with cascade delete enabled. We have discussed this, and have a three-step plan to address this:
1. Revert the change that is breaking apps from updating to 6.0. (This PR.)
2. Stop throwing for optional FKs if delete orphans timing is set to Never. (Setting the timing could have …
> [release/6.0] Revert change to delete dependent when optional FK with cascade delete is set to null

- src/EFCore/Internal/ServiceProviderCache.cs
Fixes #27169
In 6.0 we made a change to `ServiceProviderCache` to use instances of `IDbContextOptions` as keys for the internal `ConcurrentDictionary`.  A key of type `IDbContextOptions` contains, among other things, the extension `CoreOptionsExtension` which has an `ApplicationServiceProvider` reference pointing to the service provider that was used to create the options.
After creation and disposal of the first `DbContext` the `ServiceProviderCache` keeps the `IDbContextOptions` incl. the (disposed) service provider scope, which still references all disposed scoped services, including the `DbContext` itself.
The first service provider scope per each DbContext type used in the application will never be garbage collected.
**How found**
Customer reported …
> [release/6.0] Store ApplicationServiceProvider in a WeakReference

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Scoping causes clash in names.
Resolves #26588
Don't generate `nameof` syntax when generating attributes during scaffolding a database as it can cause clash with types/members.
Customers scaffolding database where this can cause issue will run into code with compilation failure or invalid model created.
**How found**
Customers reported 6.0.
**Regression**
Yes. Use of `nameof` sytanx was new feature in 6.0.
**Testing**
There is existing testing for scenario. Fix here is reverting the feature added in 6.0
**Risk**
Low risk. The fix has been merged to main and this is cherry-pick of it. The generated code is same as what was in 5.0.
> [release/6.0] RevEng: Don't use nameof syntax (#26622)

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/QueryOptimizingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
Resolves #26744
A better fix for #18476
Initial fix for #18476 (in 6.0) assumed that whenever we have single result operation compared to null, it will only be true if the result of single result is default when sequence is empty. This was correct for the query in the issue tracker which had anonymous type projection.
Anonymous type is never null as long as there is data, it can be only null value when default is invoked i.e. empty sequence. Hence we added optimization for that but it didn't restrict to just anonymous type.
For entity type projection when entity is not nullable, the same logic holds true. This helped us translate queries which wouldn't work with entity equality due to composite key from a subquery. But optimization was incorrect for the result which can be null (nullable …
> [release/6.0] Query: Convert single result subquery comparison to null to Any operation

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
Resolves #26756
For property access on optional dependents sharing column with principal, we generate CaseExpression. In order to match them during join key search, we updated our recursive function to match shape of the test in CaseExpression which incorrectly matched similar structure outside of case block causing somewhat wrong join key to be extracted. While join key in itself could work, when generating partitions out of it due to paging operation, it gives incorrect results.
The fix is to match the special structure of CaseExpression. Test separately. Also made the key comparison match more robust by only allowing column or case block to appear in condition. Other structures don't represent part of join key in a comparison.
Null checks for join keys are handled separately so that we …
> [release/6.0] Query: Match correct predicate structure to convert apply to join

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Fix for the optimizer when an entity has a collection property that references itself. An example would be a Json.Net's [JArray](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JArray.cs#L41). It implements IEnumerable&lt;JToken&gt;, which in turn implements IEnumerable&lt;JToken&gt;. This caused an infinite loop and stack overflow exception in [`CSharpRuntimeModelCodeGenerator.AddNamespace`](https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs#L1381)
- Added a check if the sequence type matches the parameter type to break the inifinite loop.
- Added unit test with self-referential collection type. If the unit test doesn't stack overflow, can be considered successful.
Fixes #27301
> Fix for the optimizer when an entity has a collection property that references itself.

- build.cmd
- build.sh
- restore.cmd
- restore.sh
- test.cmd
- test.sh
I can't take it anymore! I'm going back to the way it used to work. No amount of perf gain is worth this pain.
> Unlink of file '.dotnet/dotnet.exe' failed. Should I try again? (y/n)

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Problem was that we were incorrectly using old table schema rather than history table schema when we were creating DropTableOperation for the history table, after versioning has been disabled.
Fix is to use the correct value.
Fixes #27375
--------------------------
Problem was that we were incorrectly using actual table schema rather than history table schema when we were creating DropTableOperation for the history table, after versioning has been disabled.
Customers were unable to use revert temporal table to a regular table if the history table schema was different than the actual table schema.
**How found**
Reported by a customer on 6.0
**Regression**
No. Temporal tables is a new feature in 6.0
**Testing**
Added test for the affected scenario. …
> [release/6.0] Fix to #27375 - EF Core 6.0 temporal tables - migration rollback doesn't work

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionPool.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionFactoryTest.cs
The existing code to reclaim leaked connections inadvertently modifies a collection while enumerating.
Fixes #27168
Because of this defect, calling methods like `SqliteConnection.ClearAllPools()` currently throws when an application fails to dispose connection objects.
Yes. Pooling was added in 6.0 and is enabled by default. There's a new Timer that calls this code on a background thread every 2-4 minutes.
Low. The updated code more closely mirrors the existing code used by the [ODBC](https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/System.Data.Odbc/src/Common/System/Data/ProviderBase/DbConnectionPool.cs#L1073), [OLE DB](https://github.com/dotnet/runtime/blob/v6.0.0/src/libraries/System.Data.OleDb/src/System/Data/ProviderBase/DbConnectionPool.cs#L1610), and …
> [release/6.0] SQLite: Don't modify collection while enumerating inside ReclaimLeakedConnections

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/NorthwindMiscellaneousQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
Improvement on the previous patch fix (#26744). We were not taking into the account scenario where collection projected from FirstOrDefault was compared to null. Collection can only be null if the parent entity is null, so we can safely apply the same optimization we do for anonymous types and required entities.
Fixes #27356
----------------------------------------------
Problem was that we were scaled down the optimization for comparing complex expressions to null, but we scaled it down too much. Scenario involving collection projection could also be optimized (and was being optimized in the too eager version before the previous fix), but now the optimization wouldn't apply causing query compilation error.
Customer executing the query in the scenario …
> [release/6.0] Fix to #27356 - Collection_navigation_equal_to_null_for_subquery fails after merging from release/6.0

- src/EFCore/ModelBuilder.cs
- src/EFCore/PropertyAccessMode.cs
Fixes #27453
/cc @ajcvickers in case the aka.ms link is wrong too
> Fix doc link type

- src/EFCore.Cosmos/Query/Internal/RandomTranslator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Metadata/IMutableCheckConstraint.cs
- src/EFCore.Relational/Metadata/IReadOnlyCheckConstraint.cs
- src/EFCore.Relational/Metadata/ITable.cs
- src/EFCore.Relational/Metadata/Internal/CheckConstraint.cs
- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- src/EFCore.Relational/Metadata/Internal/Table.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/Operations/AddCheckConstraintOperation.cs
- src/EFCore.Relational/Query/Internal/RandomTranslator.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryCollectionMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerMultiLineStringMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerPolygonMemberTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMemberTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerNewGuidTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteRandomTranslator.cs
- src/EFCore/DbContext.cs
- src/EFCore/Metadata/IReadOnlyEntityType.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/RuntimeModel.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
Return null name for constraints on entity types not mapped to a table
Change calls from Array.Empty to Enumerable.Empty
Fixes #24219
> Map check constraints only to the tables for which they are declared

- test/EFCore.Design.Tests/Migrations/Design/MigrationsBundleTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Operations/CreateIndexOperationTest.cs
- test/EFCore.Relational.Tests/Query/Internal/QuerySqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerMigrationsAnnotationProviderTest.cs
- test/EFCore.SqlServer.Tests/SqlServerMigrationBuilderTest.cs
- test/EFCore.Sqlite.Tests/Migrations/SqliteMigrationBuilderTest.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteRelationalConnectionTest.cs
- test/EFCore.Tests/DbSetTest.cs
See https://github.com/dotnet/efcore/pull/16014
> Be consistent about using ConditionalFact and ConditionalTheory

- Directory.Build.props
Remove `DisableImplicitNamespaceImports` config, since .NET 6 RC 1 `ImplicitUsings` is used and disabled by default
> Remove DisableImplicitNamespaceImports config

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
Fixes #27455
We stopped marking properties as store-generated when they are contained in an FK cycle to avoid stack overflows. However, this also affected cycles that contain an optional composite FK that can be used to break the cycle.
For models that contain an FK cycle with an optional composite FK `SaveChanges` will throw an exception when propagating the store-generated value.
**How found**
**Regression**
Yes, in 6.0.0
**Testing**
Added a test for the given scenario.
**Risk**
Low, also added a quirk mode.
> Generate temp values for key properties contained in optional FKs

- src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
Since #27447 is taking a while, this unblocks us from building on newer SDKs (which I already have installed etc.).
> Tiny workaround for analyzer issue

- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
Problem is that when we drop column from the history table we need to disable versioning (and drop columns in both tables separately). However, since we have disabled the period, renaming (and other operations) also needs to happen for both tables now and we don't do it. So the column is only renamed for the temporal table and the name in history table stays the same. When we try to switch versioning back on the exception is thrown.
Fix is to flow the information to ColumnOperations that the column is part of a temporal table and when we process the migrations, if the versioning for the temporal table has been disabled, mirror the necessary operation(s) to the history table also.
Fixes #27423
> Fix to #27423 - Renaming and dropping columns with Temporal Tables generates faulty migration

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
> Fix SQL Server memory-optimized + temporal tables

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
> Fix scaffolding of reference navigations with NRT

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Fixes #27217
Fixes #27218
The 5.0/6.0 behavior here is:
- Orphans are deleted if the relationship is severed by navigation property
- Orphans are not deleted if the relationship is severed by setting the FK to null
This change means orphans are not deleted in either case. The change that causes this to happen is to not set a conceptual null for a nullable FK property. Deletion can still be forced by explicitly forcing a conceptual null or just by setting the dependent state explicitly to Deleted.
> Stop deleting orphans for optional relationships configured for cascade deletes

- src/EFCore.Relational/Diagnostics/DbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbTransactionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs
- src/EFCore/Diagnostics/ISaveChangesInterceptor.cs
- src/EFCore/Diagnostics/SaveChangesInterceptor.cs
Plus some cleanup
Closes #27625
> Add default interface implementations to interceptors

- src/EFCore.Abstractions/PrimaryKeyAttribute.cs
- src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
- src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.InMemory.FunctionalTests/CompositeKeyEndToEndTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
- test/EFCore.Specification.Tests/FieldMappingTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/WithConstructorsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerOwnedTest.cs
- test/EFCore.Tests/Metadata/Conventions/PrimaryKeyAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs
Fixes #11003
This PR introduces a new `[PrimaryKey]` which follows the same pattern as `[Index]` in that it is applied to the entity type class and takes an ordered list of property names. It takes precedence over any `[Key]` attributes on properties, since these may still be needed for OData or other technologies. `PrimaryKey` and `Keyless` cannot be used on the same type.
> Attribute for configuring composite primary keys

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Part of #11597
This change takes the ValueComparer defined for the principal key and uses it for the foreign key, but also accommodating for nulls appropriately. As part of this, we started getting some more complex expressions in value comparers used in the in-memory database. These expressions became part of the query, which then meant they needed to be translated. Therefore, this logic has been changed to call the value comparer as a method when using the in-memory database, and this method is then detected. This incidentally fixes #27495, which was also a case of a value comparer expression that could not be translated, and any other case where a value comparer could not be translated in in-memory queries.
> Ensure FK properties have nullable-appropriate value comparers

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Update/StoreValueGenerationTestBase.cs
- test/EFCore.Relational.Specification.Tests/Update/UpdateSqlGeneratorTestBase.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeSqlGenerator.cs
- test/EFCore.Relational.Tests/Update/UpdateSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/SqlServerUpdateSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationIdentitySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationIdentityTriggerSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationSequenceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationSequenceTriggerSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
- test/EFCore.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/SqliteUpdateSqlGeneratorTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/StoreValueGenerationSqliteTest.cs
> Use RETURNING/OUTPUT clause for UPDATE/DELETE

- src/EFCore.Relational/Update/ModificationCommandBatch.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.Relational/Update/SingularModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatchFactory.cs
- test/EFCore.Relational.Tests/TestUtilities/TestModificationCommandBatch.cs
- test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
- test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
For better perf on SQLite (#27681)
Also moves the handling of MaxBatchSize to ReaderModificationCommandBatch and does some cleanup.
> Reimplement MaxBatchSize as a pre-check

- src/ef/ef.csproj
This is needed otherwise it will try to require ".NET 2.0 Runtime" to be installed, which will cause roll forward to fail to load 6.0.0's System.Runtime when used on devices with newer versions of the .NET SDK and runtimes.
Fixes: https://github.com/dotnet/efcore/issues/27660.
Discovered at: https://github.com/dotnet/efcore/issues/27660#issuecomment-1073184551
```
- Detail 1
- Detail 2
```
> Update tool to roll forward to latest major version of runtime installed.

- src/EFCore.Analyzers/InternalUsageDiagnosticAnalyzer.cs
- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindSelectQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindSelectQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSelectQuerySqlServerTest.cs
This improves the fix made in #27134
In earlier PR we converted `IQueryable<T>` to `IEnumerable<T>` becaused we converted enumerable to queryable during preprocessing phase and types aligned in later phase since we create a list (which does implement `IEnumerable<T>`). Though this implementing behavior doesn't work when returning a single result of enumerable during async which wraps collection type inside Task.
The better fix is to assign `List<T>` as type since we are eventually creating a list.
In case of single result, the single result operator has generic type which will introduce convert node into it automatically which will match types for async tasks.
Resolves #27600
Applying single result operator (First(OrDefault) and family) on queryable of enumerable throws …
> [release/6.0] Query: Assign proper type to collection result expression (part 2)

- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindAggregateOperatorsQueryCosmosTest.cs
> [6.0.x] Ignore a failing Cosmos test to unblock builds

- src/EFCore.Cosmos/ValueGeneration/Internal/CosmosValueGeneratorSelector.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/IColumn.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/ValueGeneration/RelationalValueGeneratorSelector.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/ISqlServerSequenceValueGeneratorFactory.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerSequenceValueGeneratorFactory.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs
- src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/ValueGeneration/Internal/ConvertedValueGenerator.cs
- src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs
- src/EFCore/ValueGeneration/ValueGenerator.cs
- src/EFCore/ValueGeneration/ValueGeneratorSelector.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteValueGenerationScenariosTest.cs
- test/EFCore.Tests/ValueGeneration/TemporaryNumberValueGeneratorFactoryTest.cs
Providers may need to be updated to support this.
Fixes #11597
> Support value generation for converted types

- src/EFCore.Cosmos/Query/Internal/CosmosValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Internal/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/RelationalValueConverterCompensatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/SelectExpressionProjectionApplyingExpressionVisitor.cs
- src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/ShapedQueryExpression.cs
This makes sure that shaper expression has right query expression
> Query: Introduce UpdateQueryExpression on ShapedQueryExpression

- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
> Fix tests in StoreGeneratedTestBase

- .github/workflows/TestCosmos.yaml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- test/EFCore.Tests/Storage/ValueComparerTest.cs
> Fixes to support multi-dimensional arrays

- eng/Versions.props
- src/EFCore.Analyzers/UninitializedDbSetDiagnosticSuppressor.cs
- test/EFCore.Analyzers.Tests/UninitializedDbSetDiagnosticSuppressorTest.cs
> Suppress uninitialized DbSet warnings when a ctor is present

- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore/Metadata/IReadOnlyEntityType.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/ModelExtensions.cs
- src/Shared/Multigraph.cs
- test/EFCore.Relational.Specification.Tests/Update/StoreValueGenerationTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.Relational.Tests/TestUtilities/TestModificationCommandBatch.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationIdentitySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationIdentityTriggerSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationSequenceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoreValueGenerationSequenceTriggerSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/StoreValueGenerationSqliteTest.cs
- test/EFCore.Tests/Utilities/MultigraphTest.cs
This is a draft for allowing batching in more cases by only applying a batch boundary for foreign keys where a principal key property is database-generated. There's still work and failing tests, but it seems like a good point to get feedback on the general approach.
* Multigraph edges now have an additional flag - RequiresBatchBoundary.
* The batching topological sort continuously adds to the same batch, unless it sees an edge with RequiresBatchBoundary=true pointing to a vertex that's in the current batch.
* Since we now mix commands with dependencies in the same batch (as long as the dependency doesn't require a batch boundary), we can no longer do "secondary" sorting within the batch (ModificationCommandComparer). For now that's removed, I'm not sure of the exact importance of this. …
> Reduce SaveChanges roundtrips

- src/EFCore.Relational/Update/SelectingUpdateSqlGenerator.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeSqlGenerator.cs
This introduces a new SelectingUpdateSqlGenerator abstract class, which uses SELECT after the INSERT/UPDATE/DELETE to retrieve database-generated values or to perform concurrency checks. This moves all SELECT logic out of UpdateSqlGenerator, for providers which don't require it. SqlServerUpdateSqlGenerator inherits from SelectingUpdateSqlGenerator and uses the SELECT logic in various cases where triggers are defined (and OUTPUT cannot be used).
The design isn't amazing: SelectingUpdateSqlGenerator extends UpdateSqlGenerator, so that SqlServerUpdateSqlGenerator can call methods from both (it's a combination of both modes, depending on whether there are triggers or not). But it seems reasonable (am open for other ideas).
Note that most of SelectingUpdateSqlGenerator is covered for SQL …
> Refactor UpdateSqlGenerator to separate select logic

- src/EFCore.Relational/Diagnostics/ConnectionCreatedEventData.cs
- src/EFCore.Relational/Diagnostics/ConnectionCreatingEventData.cs
- src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbTransactionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IRelationalConnectionDiagnosticsLogger.cs
- src/EFCore.Relational/Diagnostics/Internal/DbConnectionInterceptorAggregator.cs
- src/EFCore.Relational/Diagnostics/Internal/RelationalConnectionDiagnosticsLogger.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore/Diagnostics/ISaveChangesInterceptor.cs
- test/EFCore.Relational.Specification.Tests/ConnectionInterceptionTestBase.cs
- test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConnectionInterceptionSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/ConnectionInterceptionSqliteTest.cs
> Add creation and disposal to connection interception

- src/EFCore.Relational/Query/IMethodCallTranslator.cs
Due to EF Core using wrappers to look up methods via reflection (GetRequiredRuntimeMethod), the linker cannot see the dependency on those methods, and trimmed applications fail.
It isn't possible to use EF Core's SQLite provider in a trimmed application.
Customer report on 6.0
Yes, from 5.0. Although EF Core 5.0 was never officially trimming-compatible, at least basic scenarios were possible.
Coverage will be added in 7.0, where trimming will be a focus. The fix was verified manually.
Note that EF Core 6.0 still won't be fully trimming-compatible, but this unlocks at least the basic SQLite scenarios which customers were asking for.
Very low - the fix only adds an attribute which is meaningful only to the linker.
This uses the [DynamicDependency] attribute to make sure System.DateOnly and …
> [6.0.x] Add [DynamicDependency] on DateOnly/TimeOnly for trimming

- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
When getting the FK name the code assumed that both entity types are mapped to tables, since it's the only way an FK constraint can be created in the database.
When creating a foreign key between an entity type mapped to a view and an entity type mapped to a table an exception is thrown. No known workaround other than not creating the FK.
**How found**
Customer reported on 6.0.
**Regression**
Yes, From 5.0.
**Testing**
Added tests for this scenario.
**Risk**
Low risk, avoids NRE.
Partial backport of https://github.com/dotnet/efcore/commit/786cb40576d47874549753e6d92fbcf3e65a4f64
Fixes #27854
> [6.0.x] Return null constraint names for keys and FKs on entity types not mapped to a table.

- src/EFCore.Relational/Storage/RelationalDataReader.cs
- test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
As part of the EF Core 6.0 query perf optimization cycle, RelationalDataReader started to get recycled across executions, but the read count value wasn't properly reset.
When tracking how many reader reads were performed via DataReaderDisposingEventData.ReadCount, users got incorrect values since the count wasn't properly reset across usages of RelationalDataReader. No known workaround.
**How found**
Customer reported on 6.0.
**Regression**
Yes, From 5.0.
**Testing**
Added test.
**Risk**
Very low risk, one-line fix.
Backports #27845
Fixes #27652
> [6.0.x] Reset read count on RelationalDataReader

- src/EFCore.Relational/Query/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/ISqlExpressionFactory.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCFiltersInheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCFiltersInheritanceQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCGearsOfWarQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCGearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCInheritanceQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCInheritanceQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCManyToManyNoTrackingQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCManyToManyQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCManyToManyQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCRelationshipsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
> Query: Add support for TPC

- src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
- test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- We use TypeMapping if configured on the DbFunction, or
- We try to get it if store type is specified
- If neither of above work then we do the default type mapping based on return type
Resolves https://github.com/dotnet/efcore/issues/27954
Resolves https://github.com/dotnet/efcore/issues/27524
> Query: Infer type mapping from IDbFunction while translating

- src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
- src/EFCore.Relational/Metadata/ITable.cs
- src/EFCore.Relational/Metadata/Internal/DbFunction.cs
- src/EFCore.Relational/Metadata/RuntimeDbFunction.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Specification.Tests/Query/TPCGearsOfWarQueryRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/TPCInheritanceQueryFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/TPCRelationshipsQueryRelationalFixture.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
Don't configure table name for abstract types in TPC that have a corresponding DbSet property
Make `ToTable(b => {})` map the entity type to the default table
Fixes #3170
Fixes #27608
Fixes #27945
Fixes #27947
> Throw if an entity type in table-sharing uses TPC

- src/EFCore.Relational/Query/Internal/TpcTablesExpression.cs
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryTranslationPostprocessor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCManyToManyQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTInheritanceQuerySqlServerTest.cs
- Add TpcTablesExpression which holds all union all tables so we can prune unused subqueries
- Also allow pruning of unused column inside each subquery
- Assign unique aliases in inner subqueries across whole SelectExpression
- Apply predicate on discriminator column directly to subqueries by removing unnecessary subqueries
Resolves #27967
Resolves #27957
> Query: TPC prune unused concrete tables and columns

- src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCRelationshipsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalTableSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TPTTableSplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs
Resolves #23572
Following rules define if given entity type is a potential candidate for optional dependent in table sharing case
- A keyless entity cannot be in table sharing
- Only root type of hierarchy can be dependent
- The dependent can be TPH/TPT (or no hierarchy) but no TPC
- Principal can be any type except non-leaf type in TPC (this is only applied in model validation, no impact on query)
If above conditions indicate it is optional dependent then we need to find the ITableBase it is mapped to find if it is optional dependent
We find ITableBase for IEntityType (which is also root type)
- For new generated SelectExpression, first table's ITableBase is the mapping table (regardless of type of TableExpressionBase, if no mapping then we use default)
- For other scenario the single …
> Query: Optimize usage of GetViewOrTableMappings

- src/dotnet-ef/dotnet-ef.csproj
- src/ef/ef.csproj
For tools targeting versions below 6.0, the `dotnet tool install` command creates an **x64** shim. When users try to run `dotnet ef`, it errors with *The required library libhostfxr.dylib could not be found.*
For tools targeting 6.0 or higher, it will generate an **arm64** shim. This enables the tool to work as expected.
Fixes #27787, fixes #27827
Without this, users are required to specify `-a arm64` when installing the tool on osx-arm64 before it will work.
Sort of. The `dotnet tool install` behavior changed in 6.0.1 causing our tool to stop working.
Low. EF Core 6.0 already requires .NET 6.0, so users already have it installed, and because we specify RollForward= Major, it's already being used to run dotnet-ef.
> [release/6.0] Tools: Target .NET 6 to improve compatibility with osx-arm64

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.Relational/Query/EnumerableExpression.cs
- src/EFCore.Relational/Query/RelationalGroupByShaperExpression.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/GroupByShaperExpression.cs
> Query: API review changes

- src/EFCore/EFCore.csproj
- src/EFCore/buildTransitive/net6.0/Microsoft.EntityFrameworkCore.props
MAUI's aggressive trimming of NRT-related attributes (https://github.com/dotnet/runtime/issues/55860) doesn't allow users to use NRTs in EF Core models.
EF Core currently cannot be used with NRTs in MAUI. In 6.0, these attributes are silendly discarded (and an incorrect model is built); in EF Core, an exception is thrown (since NullabilityInfoContext is used).
Reported by @eerhardt in #27474
No, MAUI hasn't yet been released.
Manual.
Very low - this simply adds a .props file to the EF Core nuget package.
As suggested by @eerhardt, this adds a .props file to the EF Core main nuget package, which overrides the <NullabilityInfoContextSupport> msbuild property to conserve the nullability attributes.
Fixes #27474
> [release/6.0] Force NullabilityInfoContextSupport=true in user projects

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerMathTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> Query: Assign correct type/typemapping to result of Round on SqlServer

- src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
After the discussion in #1625, it turns out the Npgsql provider didn't implement IndexOf with starting position (see #25396), but this didn't surface because the relevant test was calling the function in the top-most projection, and not in a Where clause (so it was client-evaled).
Changed the IndexOf/Replace tests to use Where - we should avoid testing translations in top-most projections except where we specifically need to test materialization etc.
Also tweaked SQL Server IndexOf translation to be better with constants.
> Improve SQL Server IndexOf translation and change tests to use Where

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Query: Don't add grouping key to projection when Distinct is applied

- All.sln.DotSettings
- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- src/EFCore.Relational/Query/SqlExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/AtTimeZoneExpression.cs
- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerDateTimeMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlExpressionFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
* Adds AtTimeZoneExpression support to relational, along with support in QuerySqlGenerator, SqlNullabilityProcessor.
* Adds SQL Server-specific EF.Functions.AtTimeZone for datetimeoffset -> datetimeoffset and for datetime/datetime2 -> datetimeoffset
Closes #26199
Closes #26971
> Add AtTimeZoneExpression and some relevant translations

- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
> Query: Use accurate generic types in group join flattening

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Query/IAggregateMethodCallTranslator.cs
- src/EFCore.Relational/Query/IAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.Relational/Query/IAggregateMethodCallTranslatorProvider.cs
- src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs
- src/EFCore.Relational/Query/RelationalAggregateMethodCallTranslatorProvider.cs
- src/EFCore.Relational/Query/RelationalAggregateMethodCallTranslatorProviderDependencies.cs
- src/EFCore.Relational/Query/RelationalCompiledQueryCacheKeyGenerator.cs
- src/EFCore.Relational/Query/RelationalEvaluatableExpressionFilter.cs
- src/EFCore.Relational/Query/RelationalMemberTranslatorProvider.cs
- src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitorDependencies.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitorFactory.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerAggregateMethodCallTranslatorProvider.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerLongCountMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteAggregateMethodCallTranslatorProvider.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableAggregateMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/CompiledQueryCacheKeyGenerator.cs
- src/EFCore/Query/EvaluatableExpressionFilter.cs
- src/EFCore/Query/ExpressionEqualityComparer.cs
- src/EFCore/Query/ICompiledQueryCacheKeyGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
Resolves #22957
- Introduce IAggregateMethodCallTranslator and family to translate aggregate methods
- Currently we assume that either method instance or first argument (for static method) will be the one which can be of type enumerable, rest of the arguments if any are scalar.
- Also refactor code in SqlTranslator.VisitMethodCall to avoid visiting grouping element source multiple times
> Query: Add support for custom aggregate operators

- src/EFCore.Proxies/Proxies/Internal/IProxyLazyLoader.cs
- [ + ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ + ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ + ] The code builds and tests pass locally (also verified by our automated build checks)
- [ + ] Commit messages follow this format:
```
- Detail 1
- Detail 2
```
- [ - ] Tests for the changes have been added (for bug fixes / features) I do not know how to test attribute, i am sorry, i am stupid
- [ + ] Code follows the same patterns and style as existing code in this repo
Related issue https://github.com/dotnet/efcore/issues/28083
> add support for System.Text.Json not including LazyLoader

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Infrastructure/ConventionAnnotatable.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/IConventionAnnotatable.cs
- src/EFCore/Metadata/IConventionEntityType.cs
- src/EFCore/Metadata/IMutableEntityType.cs
- src/EFCore/Metadata/IReadOnlyEntityType.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Tests/ApiConsistencyTest.cs
- test/EFCore.Tests/Metadata/Conventions/DiscriminatorConventionTest.cs
- test/EFCore.Tests/Metadata/EntityTypeExtensionsTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
Add model validation when values are not unique
Resolves #28054
> Query: Use GetDiscriminatorValue for TPT and TPC

- src/EFCore.Cosmos/Query/Internal/CosmosContainsTranslator.cs
- src/EFCore.Cosmos/Query/Internal/CosmosEqualsTranslator.cs
- src/EFCore.Cosmos/Query/Internal/CosmosMathTranslator.cs
- src/EFCore.Cosmos/Query/Internal/CosmosMethodCallTranslatorProvider.cs
- src/EFCore.Cosmos/Query/Internal/CosmosRandomTranslator.cs
- src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
- src/EFCore.Cosmos/Query/Internal/RegexMethodTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
Add translator for Regex.IsMatch method to [REGEXMATCH](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-query-regexmatch)
Fixes #28078
Please review
> Cosmos: Add translator for Regex.IsMatch method

- src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
Small fix of the parameter type mapping
Fixes #27213
> Fix parameter type mapping for Sqlite

- src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteDbFunctionsExtensions.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteDbFunctionsMethodCallTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerPointMemberTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
Provides a workaround for returning CircularString, CompoundCurve, and CurvePolygon instances to the client
> MSSQL Spatial: Add EF.Functions.CurveToLine

- .github/dependabot.yml
- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- rulesets/FxCop.ruleset
- rulesets/FxCop.test.ruleset
- src/Directory.Build.props
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.AspNet.Specification.Tests/EFCore.AspNet.Specification.Tests.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
Changes:
- Remove obsolete Microsoft.CodeAnalysis.FxCopAnalyzers package
- Bump SQLitePCLRaw to 2.1.0
- Bump AspNetCore.Identity to 6.0.5
- Bump Grpc to 2.46.0
> Update some NuGet packages

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Query: Improve logic to find column names in TPC

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Resolves #28039
If we need to push current query into a subquery when query has group by operation, we add grouping key to projection so we can refer to them outside but that is incorrect if distinct is applied on the projection since it would change meaning of distinct.
Customers running query which are affected by scenario will get incorrect results.
**How found**
Customer reported on 6.0.5
**Regression**
Yes as reported by customer, it worked on 5.0.13
**Testing**
Added tests for affected scenario.
**Risk**
Low. Also added quirk to revert back to older behavior.
> [release/6.0] Query: Don't add grouping key to projection when Distinct is applied

- src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitorDependencies.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindAggregateOperatorsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
To translate an aggregate operation on top level, provider would get a SelectExpression which would have facets applied and the method call with additional arguments. They should wrap the selector into EnumerableExpression (also add other facets from SelectExpression if needed), wrap into AsQueryable (if queryable method else optional) and the aggregate method over it and use SqlTranslator to translate it.
Also exposed TranslateExpression & TranslateLambdaExpression in QueryableMethodTranslator for relational
Resolves #28097
> Query: Provide a way to translate aggregate methods on top level

- src/EFCore.Cosmos/Query/Internal/CosmosRegexTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
> Fixup to Cosmos regex translation

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerQueryTriggersTest.cs
- test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
HasTrigger with trigger name only, to make the SQL Server SaveChanges work out of the box.
Closes #28185
> "Scaffold" triggers for SQL Server

- src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Query/Internal/FromSqlParameterExpandingExpressionVisitor.cs
- src/EFCore.SqlServer.NTS/Extensions/SqlServerNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerGeometryMethodTranslator.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Extensions/SqliteNetTopologySuiteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
- src/Shared/Check.cs
- test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/SpatialModel/PointEntity.cs
- test/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> Translate spatial aggregates

- src/EFCore.SqlServer/EFCore.SqlServer.csproj
Reverts dotnet/efcore#28278
Fixes #28293.
> Revert "Bump Microsoft.Data.SqlClient from 5.0.0-preview2.22096.2 to 5.0.0-preview3.22168.1"

- src/EFCore.Relational/Diagnostics/DataReaderClosingEventData.cs
- src/EFCore.Relational/Diagnostics/DataReaderEventData.cs
- src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/IRelationalCommandDiagnosticsLogger.cs
- src/EFCore.Relational/Diagnostics/Internal/DbCommandInterceptorAggregator.cs
- src/EFCore.Relational/Diagnostics/Internal/RelationalCommandDiagnosticsLogger.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/RelationalDataReader.cs
- test/EFCore.Relational.Specification.Tests/CommandInterceptionTestBase.cs
- test/EFCore.Relational.Tests/RelationalEventIdTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs
- test/EFCore.Relational.Tests/TestUtilities/FakeRelationalCommandDiagnosticsLogger.cs
- test/EFCore.SqlServer.FunctionalTests/CommandInterceptionSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
Part of #626
Fixes #23535
Also added tests to:
- Show that this can be used to get statistics from a query, as requested in #23535.
- Show that Close and/or Dispose can be suppressed, as requested in #24295.
> Add interception for DbDataReader.Close

- rulesets/StyleCop.noxmldocs.ruleset
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- src/EFCore.Relational/Metadata/Conventions/StoreGenerationConvention.cs
- src/EFCore.Relational/Metadata/ITable.cs
- src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
- src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/Builders/OwnedNavigationBuilder.cs
- src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/Shared/DictionaryExtensions.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryFactoryTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
Add check constraint and trigger annotation support to migration snapshot
Improve owned type FK discovery
Part of #620
> Add entity splitting support to migration snapshot

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Fixes #19274
Also relates to https://github.com/npgsql/efcore.pg/pull/2402
- [X ] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [X ] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
```
- Detail 1
- Detail 2
```
> Add support for CSharpHelper for List literals

- src/EFCore.Relational/Metadata/Conventions/RelationalValueGenerationConvention.cs
- src/EFCore.Relational/Metadata/Internal/ColumnMappingBaseComparer.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Specification.Tests/NonSharedModelTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/EntitySplittingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/EntitySplittingSqliteTest.cs
Don't use identity by default for columns with FKs even when the property is mapped to other columns that should use identity
Update value generation on properties when an entity type is no longer mapped to a table or is mapped again
Part of #620
> Add entity splitting tests for migrations and update pipeline

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/DetectChangesEventArgs.cs
- src/EFCore/ChangeTracking/DetectEntityChangesEventArgs.cs
- src/EFCore/ChangeTracking/DetectedEntityChangesEventArgs.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/IChangeDetector.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
- test/EFCore.Tests/DbContextTest.cs
Fixes #26506
Also disable auto-DetectChanges when in the event to prevent infinite loop of recursive calls.
> Adjust DetectChanges events so they can be used to get a notification when all changes for an entity have been detected

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
> Fix dropping of sequence and dependent column

- src/EFCore.Relational/Storage/Internal/RawRelationalParameter.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Resolves #27427
If a FromSql with DbParameter is reused in multiple parts of query then we need to add the DbParameter only once
If same FromSql with DbParameter is reused in multiple parts of a query then we try to add DbParameter twice which throws an error.
Customers reusing FromSql will see an error. In case of GroupBy aggregate even if customer didn't write query in reusable way, it can still cause an error because we internally create copy.
**How found**
Customer reported on 6.0.2
**Regression**
Partially. In the scenario, where customer is reusing the query it threw error always. In case of groupby aggregate it is regression caused by us when we stopped lifting the aggregate element in all cases.
**Testing**
Added tests for affected scenario. …
> [release/6.0] Query: Don't add DbParameter if already added

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/EntityTypeHierarchyMappingConvention.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPCGearsOfWarQueryRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/TPCInheritanceQueryFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalFixture.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryFixture.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarContext.cs
- test/EFCore.SqlServer.FunctionalTests/EntitySplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerTestModelBuilderExtensions.cs
Use DbSet names for TPC and TPT entity types
Fixes #28193
Fixes #28298
> Store null table name and TPH mapping strategy in the snapshot

- src/EFCore.SqlServer.NTS/Query/Internal/SqlServerNetTopologySuiteAggregateMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodCallTranslatorPlugin.cs
- src/EFCore.Sqlite.NTS/Query/Internal/SqliteNetTopologySuiteAggregateMethodTranslator.cs
- test/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> Implement spatial EnvelopeCombine aggregate translation

- src/EFCore.Relational/Query/Internal/QueryableAggregateMethodTranslator.cs
- src/EFCore.Relational/Query/SqlExpressions/SqlFunctionExpression.cs
- src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerAggregateFunctionExpression.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerAggregateMethodCallTranslatorProvider.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerExpression.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerParameterBasedSqlProcessor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlExpressionFactory.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerStatisticsAggregateMethodTranslator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteAggregateMethodCallTranslatorProvider.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteStringAggregateMethodTranslator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindFunctionsQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindFunctionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerCondition.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
@smitpatel here's some work on custom aggregates:
* string.Join (SQL Server and SQLite)
* string.Concat (SQL Server and SQLite)
* Standard deviation and variance (SQL Server)
I recommend reviewing it commit-by-commit. I went ahead and introduced SqlServerSqlFunctionExpression for SQL Server's ordering (last commit).
Closes https://github.com/dotnet/efcore/issues/2981
Closes https://github.com/dotnet/efcore/issues/28104
> Custom aggregate translations

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/LoadTestBase.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Fixes #27497
This removes the need for DetectChanges in some cases where a reference is changed before a query is executed.
Also tests for already fixed issues:
Fixes #26937
Fixes #26827
> Don't overwrite reference when querying for old principal

- src/EFCore.Relational/Metadata/IRelationalModel.cs
- src/EFCore.Relational/Metadata/ISqlQuery.cs
- src/EFCore.Relational/Metadata/IStoreFunction.cs
- src/EFCore.Relational/Metadata/ITable.cs
- src/EFCore.Relational/Metadata/ITableMapping.cs
- src/EFCore.Relational/Metadata/IView.cs
- src/EFCore/ChangeTracking/ChangeTrackerExtensions.cs
- src/EFCore/Metadata/IReadOnlyEntityType.cs
- src/EFCore/Metadata/IReadOnlyForeignKey.cs
- src/EFCore/Metadata/IReadOnlyModel.cs
- src/EFCore/Metadata/IReadOnlyNavigation.cs
- src/EFCore/Metadata/IReadOnlyProperty.cs
- src/EFCore/Metadata/IReadOnlySkipNavigation.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Internal/QueryDebugView.cs
- src/EFCore/Update/UpdateEntryExtensions.cs
> Make debug views to be resilient to exceptions

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Tests/DbContextTest.cs
> Don't call local DetectChanges in cascade processing if AutoDetectChangesEnabled is false

- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
Test starting failing after upgrading PG version to 15.
> Make Select_nested_collection_with_groupby have deterministic ordering

- src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/EntitySplittingContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/SplitEntityData.cs
- test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/SplitEntityOne.cs
- test/EFCore.SqlServer.FunctionalTests/EntitySplittingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
- test/EFCore.Sqlite.FunctionalTests/Query/EntitySplittingQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/EntitySplittingQuerySqliteTest.cs
> Query: Entity splitting support for regular entities

- docs/getting-and-building-the-code.md
The original link to xunit was broken, it pointed to [Broken XUnit](http://xunit.github.io/) which does not exist. This PR replaces the link with the current link [Xunit](https://xunit.net/)
```
- Detail 1
- Detail 2
```
> Update broken link to xunit.net

- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/DbSet.cs
- src/EFCore/Internal/InternalDbSet.cs
- test/EFCore.Tests/SharedTypeDbSetTest.cs
Fixes #25354
Also added some tests and fixed a couple of other issues with using shared-type entity type instances with tracking, etc.
> Add Entry method to DbSet to get entries for shared-type entity type instances

- src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- test/EFCore.Relational.Specification.Tests/TwoDatabasesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/TwoDatabasesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
- test/EFCore.Sqlite.FunctionalTests/TwoDatabasesSqliteTest.cs
- test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
> Allow null connection string to be passed to UseProvider methods

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Metadata/ISqlQuery.cs
- src/EFCore.Relational/Metadata/ISqlQueryColumn.cs
- src/EFCore.Relational/Metadata/ISqlQueryColumnMapping.cs
- src/EFCore.Relational/Metadata/ISqlQueryMapping.cs
> Update broken links

- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- test/EFCore.Sqlite.FunctionalTests/Migrations/SqliteMigrationsSqlGeneratorTest.cs
- [ x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [ x] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
- [ x] The code builds and tests pass locally (also verified by our automated build checks)
- [ x] Commit messages follow this format:
```
- Detail 1
- Detail 2
```
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Code follows the same patterns and style as existing code in this repo
Fixes #25116
> Fix for issue #25116 - Microsoft.EntityFrameworkCore.Sqlite.NetTopologySuite error during migration

- test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/EntitySplitting/SplitEntityData.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsSharedTypeQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/CompositeKeysQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
- test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/IQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyFieldsQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ManyToManyQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/FunkyDataModel/FunkyDataData.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.Specification.Tests/TestModels/InheritanceModel/InheritanceData.cs
- test/EFCore.Specification.Tests/TestModels/InheritanceRelationshipsModel/InheritanceRelationshipsData.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
- test/EFCore.Specification.Tests/TestModels/NullSemanticsModel/NullSemanticsData.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
~20% improvement in total test run time on my machine
Basically, the changes are to avoid re-creating test data, entity asserters, and entity sorters.
> Some test perf low-hanging fruit

- src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
- src/EFCore/ChangeTracking/EntityEntryGraphNode`.cs
- test/EFCore.Tests/ChangeTracking/TrackGraphTestBase.cs
> Make EntityEntryGraphIterator publicly usable

- src/EFCore.Relational/Extensions/RelationalEntityTypeBuilderExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Builders/OwnedNavigationSplitTableBuilder.cs
- src/EFCore.Relational/Metadata/Builders/OwnedNavigationTableBuilder.cs
- src/EFCore.Relational/Metadata/Builders/SplitTableBuilder.cs
- src/EFCore.Relational/Metadata/Builders/TableBuilder.cs
- src/EFCore.Relational/Metadata/Internal/InternalTriggerBuilder.cs
- src/EFCore.Relational/Metadata/Internal/Trigger.cs
- src/EFCore.Relational/Metadata/RelationalAnnotationNames.cs
- src/EFCore.Relational/Update/IBatchExecutor.cs
- src/EFCore.Relational/Update/ICommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/BatchExecutor.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/ModificationCommandBatch.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.Relational/Update/UpdateAndSelectSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
> Pack of API review changes

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
> Fix grammar typo in XML doc

- azure-pipelines.yml
- eng/helix.proj
Reverted in c54353ce130b3d400a8c6bf0c87cb2e3895eafea, but is still a problem.
> Workaround for Sqlite/InMemory test failures on OSX (again)

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerValueGenerationStrategyConvention.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCFiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTFiltersInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
- test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerValueGenerationStrategyConventionTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs
> Change from sequence-per-model to sequence-per-hierarchy when using sequences for key generation

- src/EFCore.Abstractions/IndexAttribute.cs
- src/EFCore.Proxies/Proxies/Internal/ProxyBindingInterceptor.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/IIdentityResolutionInterceptor.cs
- src/EFCore/Diagnostics/IInstantiationBindingInterceptor.cs
- src/EFCore/Diagnostics/IMaterializationInterceptor.cs
- src/EFCore/Diagnostics/IQueryExpressionInterceptor.cs
- src/EFCore/Diagnostics/IdentityResolutionInterceptionData.cs
- src/EFCore/Diagnostics/IgnoringIdentityResolutionInterceptor.cs
- src/EFCore/Diagnostics/InstantiationBindingInterceptionData.cs
- src/EFCore/Diagnostics/Internal/IdentityResolutionInterceptorAggregator.cs
- src/EFCore/Diagnostics/Internal/MaterializationInterceptorAggregator.cs
- src/EFCore/Diagnostics/Internal/QueryExpressionInterceptorAggregator.cs
- src/EFCore/Diagnostics/UpdatingIdentityResolutionInterceptor.cs
- src/EFCore/Query/Internal/EntityMaterializerSource.cs
- src/EFCore/Query/QueryCompilationContext.cs
- test/EFCore.Specification.Tests/F1MaterializationInterceptor.cs
- test/EFCore.Specification.Tests/MaterializationInterceptionTestBase.cs
- test/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- test/EFCore.Specification.Tests/QueryExpressionInterceptionTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
- test/EFCore.Tests/Metadata/Conventions/IndexAttributeConventionTest.cs
Part of #27588.
- Remove params, Obsolete, and add a new ctor to IndexAttribute
- Use entity instead of instance in IIdentityResolutionInterceptor and IMaterializationInterceptor
- Use parameter objects in IIdentityResolutionInterceptor and IInstantiationBindingInterceptor
- Remove entityInstanceName parameter in IInstantiationBindingInterceptor.ModifyBinding
- Rename SkippingIdentityResolutionInterceptor to IgnoringIdentityResolutionInterceptor
- Remove IQueryExpressionInterceptor.CompilingQuery and CompiledQuery
- Rename IQueryExpressionInterceptor.ProcessingQuery to QueryCompilationStarting
> API review bundle

- src/EFCore.Abstractions/IndexAttribute.cs
- src/EFCore.Abstractions/Properties/AbstractionsStrings.Designer.cs
- src/EFCore.Abstractions/Properties/AbstractionsStrings.resx
- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- src/EFCore.Relational/Metadata/ITableIndex.cs
- src/EFCore.Relational/Migrations/MigrationBuilder.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.Relational/Migrations/Operations/CreateIndexOperation.cs
- src/EFCore/Metadata/Builders/IndexBuilder.cs
- src/EFCore/Metadata/Builders/IndexBuilder`.cs
- src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
- src/EFCore/Metadata/Internal/Index.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.Relational.Tests/Migrations/Operations/CreateIndexOperationTest.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
- test/EFCore.Tests/Metadata/Conventions/IndexAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/IndexTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Improves #27210 by allowing aan empty list parameter to IsDescending, meaning that all index columns should be descending.
Also normalizes explicitly-set all-ascending/all-descending to null/empty array respectively.
(addresses API review, #27588)
> Allow index IsDescending to get empty array for all-descending

- src/EFCore.Relational/Storage/RelationalConnection.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
> Close the DbConnection when returning a context with a DbConnection to the pool

- src/EFCore.Design/Design/DbContextActivator.cs
- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore/EF.cs
- test/EFCore.Design.Tests/Design/DbContextActivatorTest.cs
- test/EFCore.Design.Tests/Design/OperationExecutorTest.cs
> Add a static flag in EF that will be set when code is being executed for design-time discovery

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
- src/EFCore.Sqlite.Core/Diagnostics/Internal/SqliteLoggingDefinitions.cs
- src/EFCore.Sqlite.Core/Diagnostics/SqliteEventId.cs
- src/EFCore.Sqlite.Core/Extensions/Internal/SqliteLoggerExtensions.cs
- src/EFCore.Sqlite.Core/Infrastructure/Internal/SqliteModelValidator.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.resx
- test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Sqlite.FunctionalTests/CompositeKeyEndToEndSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdates/GraphUpdatesSqliteTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OwnedEntityQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs
- test/EFCore.Sqlite.Tests/Infrastructure/SqliteModelValidatorTest.cs
- test/EFCore.Sqlite.Tests/SqliteEventIdTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.PropertyMapping.cs
> Warn for composite generated keys on SQLite

- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorCache.cs
- test/EFCore.Relational.Specification.Tests/Query/TPCInheritanceQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQueryHiLoSqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQueryHiLoSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCInheritanceQuerySqlServerTestBase.cs
> Fix HiLo for TPC

- src/EFCore.Design/Scaffolding/Internal/ModelCodeGeneratorSelector.cs
- src/EFCore.Relational/Design/AnnotationCodeGenerator.cs
- src/EFCore.Relational/Design/IAnnotationCodeGenerator.cs
- src/EFCore.Relational/Diagnostics/DbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbTransactionInterceptor.cs
- src/EFCore.Relational/Metadata/IColumn.cs
- src/EFCore.Relational/Metadata/IColumnBase.cs
- src/EFCore.Relational/Scaffolding/IProviderConfigurationCodeGenerator.cs
- src/EFCore.Relational/Scaffolding/ProviderCodeGenerator.cs
- src/EFCore.Relational/Update/IUpdateSqlGenerator.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore/Diagnostics/SaveChangesInterceptor.cs
- src/EFCore/Internal/DbContextFactory.cs
- test/EFCore.Relational.Tests/RelationalApiConsistencyTest.cs
> Add virtual methods to abstract base classes that implement interfaces using default member implementations

- src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
This PR removes extra duplicate migration existence check in `MigrationsScaffolder`. No breaking changes.
> remove extra duplicate migration existence check

- src/EFCore.Relational/Diagnostics/ConnectionCreatingEventData.cs
- src/EFCore.Relational/Diagnostics/Internal/RelationalConnectionDiagnosticsLogger.cs
- test/EFCore.Relational.Specification.Tests/ConnectionInterceptionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ConnectionInterceptionSqlServerTest.cs
> Expose connection string in ConnectionCreating event data

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/DbContextLoggerTests.cs
> Downgrade the ContextInitialized event from Information to Debug

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Fixes #27496
(cherry picked from commit ec9c6c235a5a04fcc48520c4585a375b2778600d)
When scaffolding an existing database in a project with nullable reference types enabled, dependent navigations are incorrectly scaffolded as non-nullable.
An incorrect model is scaffolded and must be manually fixed up.
**How found**
**Regression**
No, scaffolding NRT code was introduced in 6.0 (#15520)
**Testing**
Added.
**Risk**
Low - affects design-time scaffolding only.
> Fix scaffolding of reference navigations with NRT (#27616)

- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/FiltersInheritanceBulkUpdatesSqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCFiltersInheritanceBulkUpdatesSqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerFixture.cs
Using same database concurrently (from 2 different test classes) was causing time outs when running bulk command due to locking of tables
> Query: Split databases for filter/non-filter cases for bulk updates

- src/EFCore.Relational/Diagnostics/CommandSource.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/NonQueryExpression.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
> BulkUpdates: Add custom CommandSource and exception messages

- src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
- src/EFCore.InMemory/Metadata/Conventions/InMemoryConventionSetBuilder.cs
- src/EFCore.Proxies/Proxies/Internal/ProxiesConventionSetPlugin.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalNavigationJsonPropertyNameAttributeConvention.cs
- src/EFCore.Relational/Migrations/HistoryRepository.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.Sqlite.Core/Metadata/Conventions/SqliteConventionSetBuilder.cs
- src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
- src/EFCore/Metadata/Conventions/ConventionSet.cs
- src/EFCore/Metadata/Conventions/IndexAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/KeyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
- src/EFCore/Metadata/Conventions/NavigationBackingFieldAttributeConvention.cs
- src/EFCore/Metadata/Conventions/RequiredNavigationAttributeConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionSetBuilderTests.cs
> Add sugar methods to ConventionSet

- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Add test for runtime model generation with proxies

- .github/workflows/TestCosmos.yaml
- src/EFCore.Cosmos/Extensions/CosmosDatabaseFacadeExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosDbContextOptionsExtensions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosDbOptionExtension.cs
- src/EFCore.Cosmos/Infrastructure/Internal/CosmosSingletonOptions.cs
- src/EFCore.Cosmos/Infrastructure/Internal/ICosmosSingletonOptions.cs
- src/EFCore.Cosmos/Metadata/Conventions/Internal/CosmosConventionSetBuilder.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.Designer.cs
- src/EFCore.Cosmos/Properties/CosmosStrings.resx
- src/EFCore.Cosmos/Storage/Internal/SingletonCosmosClientWrapper.cs
- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Infrastructure/ProviderConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/NavigationAttributeConventionBase.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/ConnectionSpecificationTest.cs
- test/EFCore.Cosmos.FunctionalTests/EFCore.Cosmos.FunctionalTests.csproj
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
Add a method to get the configured database name
Fixes #26491
Fixes #25063
> Cosmos: Support AAD RBAC via TokenCredential

- src/EFCore.Cosmos/Extensions/CosmosEntityTypeExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosModelExtensions.cs
- src/EFCore.Cosmos/Extensions/CosmosPropertyExtensions.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosInversePropertyAttributeConvention.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalForeignKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Extensions/RelationalKeyExtensions.cs
- src/EFCore.Relational/Extensions/RelationalModelExtensions.cs
- src/EFCore.Relational/Extensions/RelationalNavigationExtensions.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedure.cs
- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerIndexExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerKeyExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqlitePropertyExtensions.cs
- src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
- src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/IConventionNavigationBase.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Cosmos.FunctionalTests/CosmosApiConsistencyTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteApiConsistencyTest.cs
- test/EFCore.Tests/ApiConsistencyTest.cs
Make all IConvention* extension methods that set annotations return the value from the annotation that was set
Part of #22414
> Add IConventionEntityTypeBuilder.GetTargetEntityTypeBuilder

- NuGet.config
- azure-pipelines.yml
- Remove unneeded .NET 6 feeds
- Remove obselete publishing options
- Remove unused variables
- Fix internal build urls.
> Clean up build configuration

- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/Builders/OwnedNavigationTemporalPeriodPropertyBuilder.cs
- src/EFCore.SqlServer/Metadata/Builders/TemporalPeriodPropertyBuilder.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerFixture.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
Added HasPrecision builder methods for temporal period columns and fixed validation so that it can recognize custom precision.
Fixes #27228
> Fix to #27228 - EF Core 6.0 temporal tables - Support specifying precision for PeriodEnd and PeriodStart columns

- test/EFCore.InMemory.FunctionalTests/Query/Ef6GroupByInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
Added custom asserter that checks results within range, rather than adding sql server specific expected query.
For the second test, added proper collection asserter so we can impose the order within nested collection.
Fixes #27155
> Fix to #27155 - Average_Grouped_from_LINQ_101 is non-deterministic

- src/EFCore.Relational/Diagnostics/CommandSource.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Extensions/RelationalQueryableExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalQueryFilterRewritingConvention.cs
- test/EFCore.CrossStore.FunctionalTests/QueryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPCInheritanceQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTInheritanceQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
> Add FromSql/ExecuteSql/ExecuteSqlAsync

- All.sln
- EFCore.Tools.slnf
- src/EFCore.Templates/EFCore.Templates.csproj
- src/EFCore.Templates/templates/ef-templates/.template.config/template.json
Adds a new package that can be installed via `dotnet new`:
dotnet new install Microsoft.EntityFrameworkCore.Templates::7.0.0-*
For now, it just includes a single item template that will add the default T4 templates used by `dotnet ef dbcontext scaffold`.
dotnet new ef-templates
You can then tweak the templates and they'll automatically be used when scaffolding.
dotnet ef dbcontext scaffold Filename=northwind.db Microsoft.EntityFrameworkCore.Sqlite
Resolves #4038
> Add Microsoft.EntityFrameworkCore.Templates

- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/CrossApplyExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/CrossJoinExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/ExceptExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/InnerJoinExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/IntersectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/LeftJoinExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/OuterApplyExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/TableExpressionBase.cs
- src/EFCore.Relational/Query/SqlExpressions/TableValuedFunctionExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/UnionExpression.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQueryableMethodTranslatingExpressionVisitor.cs
Resolves #28120
Only SelectExpression does mutable way, all other expressions will recreate with new annotations.
> Add immutable annotation support to TableExpressionBase

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.Relational/Update/SingularModificationCommandBatch.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
* Append{Update,Delete}Command now accept a higher-level flag for adding a 1 constant to the RETURNING clause.
* Note that AppendReturningClause still accepts a lower-level string; that's actually being used in SQL Server for the synthetic position value we project out (and could be useful elsewhere).
* Accept MaxBatchSize in the ReadModificationCommandBatch constructor
Part of https://github.com/dotnet/efcore/issues/27588
> API review items 

- src/EFCore/Internal/DbContextPool.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
> Allow parameterless constructor in addition to required constructor when using context pooling

- All.sln.DotSettings
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
For the parameter check, we previously added the parameters only when the pending bulk insert commands were applied; this is why they weren't being taken into account for the parameter limit check. The fix here is to move parameter adding to when the bulk insert command is added, just like any normal command; only the SQL addition is deferred.
Note that this won't support fancy bulk strategies, such as a single array parameter for multiple rows in PostgreSQL. But other things have to be done for that anyway, and this seems like an acceptable fix for now.
Fixes #27840
Fixes #28712
> Fix bugs in SQL Server bulk insert management

- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
Regression test for #23281, plus a tiny refactor.
Closes #23281
> Add test for parameter managed across batches

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/BufferedDataReader.cs
- src/EFCore.Relational/Query/Internal/FromSqlQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/SqlQueryRootExpression.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitorDependencies.cs
- src/EFCore.Relational/Query/SqlExpressions/FromSqlExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Storage/IDatabaseFacadeDependencies.cs
- src/EFCore/Storage/Internal/DatabaseFacadeDependencies.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindSqlQueryTestBase.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSqlQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindSqlQuerySqliteTest.cs
> Implement SqlQuery<T>

- tools/ReplaceQueryBaseline.py
Usage: `python .\tools\ReplaceQueryBaseline.py`
(or can invoke inside tools directory too)
> Add python script to replace query baselines

- src/EFCore.Relational/Update/Internal/BatchExecutor.cs
- src/EFCore/AutoTransactionBehavior.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbContext.cs
- src/EFCore/Infrastructure/DatabaseFacade.cs
- src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
- test/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
To avoid a new flag which would be weird with the existing AutoTransactionsEnabled (e.g. AutoTransactionsEnabled=false, newflag=true), I went with the controversial choice of obsoleting AutoTransactionsEnabled and replacing it with an AutoTransactionBehavior enum that has WhenNeeded (default), Never, Always. Before you start hating, remember we almost decided to remove AutoTransactionsEnabled because it's obscure and nobody uses it (or should)...
Closes #27574
> Allow users to always use transactions with SaveChanges

- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationProvider.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
> Generate identity SQL for different seeds in TPC

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitorDependencies.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Resolves #28661
Also source fix for https://github.com/dotnet/efcore/issues/28738
> ExecuteUpdate: Convert to join for query with unsupported operations

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore/Design/ICSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
Fixes https://github.com/dotnet/efcore/issues/19274
[X] I've read the guidelines for [contributing](https://github.com/dotnet/efcore/pull/CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
[X] I've posted a comment on an issue with a detailed description of how I am planning to contribute and got approval from a member of the team
[X] The code builds and tests pass locally (also verified by our automated build checks)
Commit messages follow this format:
- Detail 1
- Detail 2
[X] Tests for the changes have been added (for bug fixes / features)
[X] Code follows the same patterns and style as existing code in this repo
> Add support for CSharpHelper for Dictionary literals

- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerSharedTableConvention.cs
- src/EFCore.Sqlite.Core/Metadata/Conventions/SqliteSharedTableConvention.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
Don't uniquify index constraint names across tables in SQL Server
Fixes #23144
Fixes #27651
> Uniquify FK and Key constraint names across tables

- src/EFCore.Relational/Extensions/RelationalTriggerExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/BlankTriggerAddingConvention.cs
- src/EFCore/Extensions/Internal/DbContextExtensions.cs
- test/EFCore.Relational.Tests/Metadata/Conventions/BlankTriggerAddingConventionTest.cs
- test/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
> Add a custom convention which adds a blank trigger to all tables

- src/EFCore.Relational/Extensions/RelationalTriggerExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Conventions/BlankTriggerAddingConvention.cs
- src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.SqlServer/Infrastructure/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/Builders/TemporalPeriodPropertyBuilder.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore/Extensions/Internal/DbContextExtensions.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/Conventions/BlankTriggerAddingConventionTest.cs
- test/EFCore.Specification.Tests/TestUtilities/TestModelSource.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
- test/EFCore.SqlServer.Tests/Infrastructure/SqlServerModelValidatorTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
- test/EFCore.Sqlite.Tests/Infrastructure/SqliteModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
> Validate that no properties on an entity type are mapped to the same column

- src/EFCore.Design/Design/FluentApiCodeFragment.cs
- src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
> Scaffolding: Address API Review feedback

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- src/EFCore.Relational/Scaffolding/Metadata/DatabaseTable.cs
- src/EFCore.Relational/Scaffolding/Metadata/DatabaseTrigger.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Add scaffolding DatabaseTrigger class

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityBasic.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityBasicForCollection.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityBasicForReference.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Resolves #28808
The entity instance is in resultContext.Values. We were trying to use it before creating resultContext.Values.
Fix is to materialize the includes for JSON after resultContext.Values has been created.
The collection include introduces the resultContext.
> Query: Fix for query fails with JSON columns and Include collection

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
> Fix base parameter index calculation for sprocs

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
> Query: Cleanup exception message about bulk updates

- src/EFCore/Infrastructure/ModelValidator.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
Resolves #26216
Resolves #26900
> Query: Fix issue with required navigation and query filters

- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/ColumnModificationParameters.cs
- src/EFCore.Relational/Update/IColumnModification.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
Currently, whenever we update/add/delete part of aggregate mapped to JSON column, we were replacing the entire structure.
Improvement is to use JSON_MODIFY which can alter just a portion of JSON structure, give a JSON path.
We analyze the entries that are being edited and for each JSON column we find the common denominator that needs to be replaced to accommodate all the requested changes
Note: Whenever we add/remove element from a collection we need to replace the entire collection in order to populate ordinal key values properly.
Also, modifying a single property is not yet supported - the smallest fragment that will be replaced is one that represents an entity.
Fixes #28595
> Fix to #28595 - Use partial updates for JSON

- src/EFCore.Relational/Metadata/Internal/StoredProcedureParameter.cs
- test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
> Suffix original value sproc parameters by default

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
Stop visiting components for queryable methods
Either it is translated using aggregate or subquery not component way
Resolves #28796
> Query: Avoid repeated visitation of subquery in sql translator

- src/EFCore.Relational/Query/Internal/SqlExpressionSimplifyingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindWhereQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindWhereQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindWhereQuerySqlServerTest.cs
> Query: Don't simplify Case block when ElseResult exists

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/StoreStoredProcedureParameter.cs
- src/EFCore.Relational/Metadata/Internal/StoreStoredProcedureReturnValue.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureMapping.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureParameter.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureParameterMapping.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureResultColumn.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureResultColumnMapping.cs
- src/EFCore.Relational/Metadata/RuntimeStoredProcedure.cs
- src/EFCore.Relational/Metadata/RuntimeStoredProcedureParameter.cs
- src/EFCore.Relational/Metadata/RuntimeStoredProcedureResultColumn.cs
- src/EFCore.Relational/Update/ColumnModificationParameters.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
> Fix logic in TPT sproc validation where the root type is abstract

- src/EFCore.Relational/Update/ColumnModificationParameters.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/StoredProcedureUpdateContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TphChild1.cs
- test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/TphChild2.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
This creates column modifications for all parameters of a sproc, regardless if they're mapped to the entity or not. It also changes the design to lay out column modifications for sproc parameters according to their sproc param order; we can then rely on that in SQL generation, parameter generation, etc.
Fixes #28805
> Fix sproc TPH mapping

- azure-pipelines-richnav.yml
- azure-pipelines.yml
> Move to -Svc pool provider in release branches

- src/EFCore.Relational/Update/ColumnModificationParameters.cs
- src/EFCore.Relational/Update/IColumnModification.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityAllTypes.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonOwnedAllTypes.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
Optimization for partial updates - when only one property is modified on the entity we can change it directly, rather than rewriting the JSON element for the entire entity.
To avoid string formatting issues we construct faux JSON element and insert the value that is to be the replacement, and then in the update statement we extract the value using JSON_VALUE.
In case of numeric or bool we need an additional convert statement around the value.
Fixes #28845
> Fix to #28845 - JSON: add support for partial update to update just a single scalar property, rather than entire entities

- src/EFCore.Design/Scaffolding/Internal/TextTemplatingEngineHost.cs
- src/EFCore.Design/Scaffolding/Internal/TextTemplatingModelGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/TextTemplatingModelGeneratorTest.cs
This dramatically improves the performance of the commands.
Part of #27598
> Scaffolding: Avoid recompiling T4 templates

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/MigrationsSqlServerTest.cs
> Allow making a column non-nullable with SQL Server

- src/EFCore.SqlServer/Query/Internal/SqlServerFromPartsFunctionTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindDbFunctionsQuerySqlServerTest.cs
> SqlServer Query: Use correct return type for DATE/TIMEFROMPARTS functions

- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- eng/Versions.props
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteLegacyUpdateSqlGenerator.cs
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteVersionConditionAttribute.cs
- test/EFCore.Sqlite.FunctionalTests/Update/StoreValueGenerationLegacySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/StoreValueGenerationSqliteFixture.cs
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
@bricelam I ended up using SQLitePCL.raw.sqlite3_libversion_number() to find out which Sqlite version we're using, since the UpdateSqlGenerator is set up in a singleton context and it's a bit of a hassle to get a SqliteConnection etc. Are we aware of a situation where different versions of Sqlite could be used based on the connection string (seems unlikely)? If so and you think it's important, I can look into using SqliteConnection.ServerVersion instead.
Test-wise, I've verified manually that the old SQL gets properly generated on Windows (where the version is 3034001, using SQLitePCLRaw.bundle_winsqlite3); there's also a new legacy test suite which I've verified artifically by hard-coding an old version. But since all our tests pass in CI, I'm assuming we always run with the bundled …
> Fall back to non-RETURNING updates with old Sqlite

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
> Microsoft.Data.Sqlite: Use sqlite3_load_extension

- src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPCGearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/TPTGearsOfWarQuerySqliteTest.cs
> SQLite Query: Fix more DateOnly/TimeOnly cases

- src/EFCore.Relational/Extensions/RelationalIndexExtensions.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalRuntimeModelConvention.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
So they can be broken if there's a cycle, since they might not be enforced in the database.
Fixes #28065
> Make filtered unique index update dependencies soft so they can be broken if there's a cycle, since they might not be enforced in the database.

- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Update/IUpdateEntry.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
- test/EFCore.Tests/ExceptionTest.cs
The issue is when saving entities within JSON arrays. When generating column modifications in SaveChanges, we rebuild the entire JSON document in CreateJson; any entities which are contained in a JSON array get their "ordinal key property" recalculated and assigned ([see this line](https://github.com/dotnet/efcore/blob/release/7.0/src/EFCore.Relational/Update/ModificationCommand.cs#L760)); this changes the entity's state to Modified. Since these entities are unrelated to the original change, we don't accept changes on them (not in entriesToSave in StateManager.SaveChanges), and so they remain Modified after SaveChanges completes.
Note that something similar actually happens when we save a regular entity with a computed property: propagating the computed property marks the entry as …
> Stop setting JSON array entities' state to Modified in SaveChanges

- src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs
This causes an issue in Jetbrains IDEs which don't properly resolve partially-qualified ExpressionPrinter
> Fully-qualify ExpressionPrinter in DebuggerDisplay

- src/EFCore/ChangeTracking/Internal/ValueComparerExtensions.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/Metadata/RuntimeProperty.cs
- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Specification.Tests/TestUtilities/DatabaseFacadeExtensions.cs
> Use correct value comparer for FKs in compiled model.

- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/RelationalDataReader.cs
- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/StoredProcedureUpdateContext.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
Fixes to stored procedure update mapping
* Don't attempt to propagate rows affected result columns.
* Warn if an unexpected trailing result set is found.
* Throw an informative message if a result set is missing.
Fixes #28803
> Sproc fixes

- src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
> Take the value converter into account when creating concurrency tokens for table sharing

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/IDbSetCache.cs
- test/EFCore.Specification.Tests/DatabindingTestBase.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Fixes #27056 (`LocalView<TEntity>.Contains` returns true for detached entity)
Fixes #27750 (`DbSet<T>.Local.Count` not updated when calling `ChangeTracker.Clear()`)
> Fix issues with LocalView

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalRuntimeModelConvention.cs
- src/EFCore.Relational/Metadata/IReadOnlySequence.cs
- src/EFCore.Relational/Metadata/Internal/Sequence.cs
- src/EFCore.Relational/Metadata/RuntimeSequence.cs
- src/EFCore/Design/Internal/CSharpRuntimeAnnotationCodeGeneratorParameters.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Sqlite.Tests/SqliteEventIdTest.cs
> Differentiate between a sequence's database schema and model schema

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs
This simple benchmark goes from 5078 ms to 124.
```cs
using Dapper;
using Microsoft.Data.Sqlite;
using var connection = new SqliteConnection(
"Data Source=test.db;Password=Password12!");
connection.Execute(
"CREATE TABLE IF NOT EXISTS Data(Value)");
for (var i = 0; i < 10; i++)
{
connection.Execute(
"INSERT INTO Data VALUES (@Value)",
new { Value = Random.Shared.Next() });
}
```
Fixes #28774
> Microsoft.Data.Sqlite: Avoid re-initialization of pooled connections

- src/EFCore.SqlServer/Metadata/Conventions/SqlServerOnDeleteConvention.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/TPTGearsOfWarQueryRelationalFixture.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTFiltersInheritanceBulkUpdatesSqliteTest.cs
E.g. for TPT.
Fixes #28532 (Cascade delete behavior for FK between PKs in TPT)
Note this is a breaking change--creating a cascade delete for the TPT relationship could cause a cycle with another existing cascade relationship. This is what happened with the GearsOfWar model.
> Don't skip creating cascade delete on SQL Server when types are base-linking across tables

- src/EFCore.Relational/Design/Internal/RelationalCSharpRuntimeAnnotationCodeGenerator.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/InternalStoredProcedureParameterBuilder.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
> Revert breaking change to shadow foreign key targeting generic types.

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Update/ICommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Made MigrationsModelDiffer.GetDataOperations pass through our normal batching logic again, by splitting CommandBatchPreparer.BatchCommands to allow the logic to be called without IUpdateEntries.
On a side note, I was surprised to see we actually have seeding-specific logic for bulk insert... Seeding isn't supposed to be high-perf, and we specifically discourage having a large number of rows (e.g. huge context snapshots), which is where bulk inserting makes the most sense... I'd consider removing it altogether, to simplify the code and avoid bugs (like this one).
Fixes #28876
> Take min/max batch size into account again for seeding

- src/EFCore.Relational/Storage/RelationalDataReader.cs
- test/EFCore.Relational.Tests/Storage/RelationalDataReaderTest.cs
> Clear reference to DbDataReader from RelationalDataReader

- src/EFCore/Query/ExpressionEqualityComparer.cs
- test/EFCore.Tests/Query/ExpressionEqualityComparerTest.cs
> Perform structural equality in ExpressionEqualityComparer

- src/EFCore.InMemory/Storage/Internal/InMemoryStore.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Rodney.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/UpdatesContext.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
> Delete correct shared-key entity with in-memory provider

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitorBase.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
> Cosmos: Stop attempting to include navigations not defined for the concrete type being materialized

- test/EFCore.Relational.Specification.Tests/Query/ToSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ToSqlQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ToSqlQuerySqliteTest.cs
> Test for entity type with navigation mapped to SqlQuery

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/IReadOnlyModificationCommand.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.Relational/Update/ResultSetMapping.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteLegacyUpdateSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/StoredProcedureUpdateContext.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
> Fix bugs with rows affected and value propagation for sprocs

- src/EFCore.Relational/Query/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/JsonQueryExpression.cs
- src/EFCore.Relational/Query/PathSegment.cs
- src/EFCore.Relational/Query/SqlExpressions/JsonScalarExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
Resolves #28838
Resolves #28836
> Query: Change JSONQuery.Path to be list of PathSegment

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Relational.Specification.Tests/TestModels/StoredProcedureUpdateModel/StoredProcedureUpdateContext.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
- test/EFCore.Relational.Tests/ModelBuilding/RelationalModelBuilderTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
- test/EFCore.Sqlite.Tests/Infrastructure/SqliteModelValidatorTest.cs
@AndriySvyryd @ajcvickers one last design thought on this... This PR makes in/out parameters means "always both send and receive", as discussed. If, in the future, we implement optional sproc parameters with sentinel values, it would be a breaking change to change the meaning of in/out to "write only if the user set the property, read only if they didn't" (which is our regular SQL behavior). In other words, in order to allow the user to *sometimes* provide a value and sometimes not (in different commands) - today, without optional params/sentinels - we're making it so that their value is *always* sent and read back (in the same command).
I'm a bit concerned that we're painting ourselves into a corner; ideally, the write-and-read within the same command would be triggered by a separate …
> Support sproc input/output parameters on non-concurrency-token properties

- src/EFCore.Relational/Metadata/Internal/RelationalModel.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
@AndriySvyryd, I think this small code change reproduces a bug in the relational model generation (this PR is based on top of #28908, so ignore the 1st commit).
Basically, when creating the sproc mappings (RelationalModel.CreateStoredProcedureMapping) for a TPH child, we [filter out](https://github.com/dotnet/efcore/blob/release/7.0/src/EFCore.Relational/Metadata/Internal/RelationalModel.cs#L1130)  parameters which aren't mapped to the current child entity type. We'll add these to the StoredStoreProcedure later, but they'll be appended to the ended, meaning that the parameter longer is incorrect.
This is reproduced here by moving Child1Property to the end of the sproc parameter list, after some properties which belong to Child2. Inspecting the final metadata definition shows that in the …
> TPH sibling metadata bug

- src/EFCore.Cosmos/Infrastructure/Internal/CosmosModelValidator.cs
- src/EFCore.Cosmos/Metadata/Conventions/CosmosValueGenerationConvention.cs
- src/EFCore.Cosmos/Metadata/Internal/CosmosPropertyExtensions.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- src/EFCore.Relational/Extensions/Internal/RelationalPropertyInternalExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalValueGenerationConvention.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- Don't undelete dependents if principal key changes
- Re-set ordinal values when the principal is added, not only when it's modified
- Mark the ordinal property as ValueGenerated.OnAddOrUpdate
- Override all JSON values for a replaced dependent
Fixes #27918
Fixes #27272
Fixes #24828
> Don't undelete dependents if principal key changes

- src/EFCore.Cosmos/Metadata/Conventions/CosmosDiscriminatorConvention.cs
- src/EFCore.Cosmos/Metadata/Conventions/StoreKeyConvention.cs
- src/EFCore/Metadata/Conventions/BaseTypeDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/ForeignKeyIndexConvention.cs
- src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.ImmediateConventionScope.cs
- src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/OwnedEntityTypeAttributeConvention.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/ValueGenerationConvention.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Make On*Removed conventions run even if the declaring type was removed previously

- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/IValueGenerationManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
> Generated stable values to not imply that an entity is Added

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore/ChangeTracking/Internal/IValueGenerationManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
- src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/KeysWithConvertersCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/GraphUpdates/GraphUpdatesInMemoryTest.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.Specification.Tests/KeysWithConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerOwnedTest.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/GraphUpdates/GraphUpdatesSqliteTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalClrEntityEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/KeyPropagatorTest.cs
> Allow database default values for FK properties that are part of a composite key

- src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs
- src/EFCore.InMemory/Infrastructure/Internal/InMemorySingletonOptions.cs
- test/EFCore.InMemory.FunctionalTests/GlobalDatabaseTest.cs
> Use different internal service provider when EnableNullChecks is changed

- src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataBuilderExtensionsTest.cs
Fixes #28560
The logic is that if we set something different from a given strategy, then we reset facets for that strategy. This means that when a strategy changes, all facets for other strategies are reset.
> Fix logic for resetting facets in HasValueGenerationStrategy

- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- src/EFCore/Query/QueryTranslationPreprocessor.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindJoinQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/Ef6GroupBySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindJoinQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsSharedTypeQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/Ef6GroupBySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindJoinQuerySqliteTest.cs
> Query: Convert unflattened GroupJoin to correlated subquery

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/Ef6GroupByTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/Ef6GroupBySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs
> Query: Support for GroupBy entity type

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore.Relational/Metadata/Internal/CheckConstraint.cs
- src/EFCore.Relational/Metadata/Internal/EntityTypeMappingFragment.cs
- src/EFCore.Relational/Metadata/Internal/RelationalPropertyOverrides.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureParameter.cs
- src/EFCore.Relational/Metadata/Internal/StoredProcedureResultColumn.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Conventions/KeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/ModelCleanupConvention.cs
- src/EFCore/Metadata/Conventions/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/Index.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/Key.cs
- src/EFCore/Metadata/Internal/Navigation.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/ServiceProperty.cs
- src/EFCore/Metadata/Internal/SkipNavigation.cs
- src/EFCore/Metadata/Internal/Trigger.cs
- test/EFCore.Cosmos.Tests/ModelBuilding/CosmosModelBuilderGenericTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
Propagate value converters to FKs
Check declaring object status in IsInModel
Fixes #27549
> Remove old principal key after a value converter is applied

- src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
- test/EFCore.InMemory.FunctionalTests/LoggingInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.Relational.Specification.Tests/LoggingRelationalTestBase.cs
- test/EFCore.Specification.Tests/LoggingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/LoggingSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/LoggingSqliteTest.cs
Note that this is a breaking change because this bug was preventing exceptions being thrown when they should have been.
Fixes #29069
> Ensure warnings configured to throw really do throw with the SQL Server provider

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindFunctionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
> Ignore case when comparing store types for set operation validation

- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/CosmosConcurrencyTest.cs
> Cosmos: Accept changes for root entities that were not modified but end up being changed due to ETag update

- src/EFCore.Templates/templates/ef-templates/.template.config/template.json
Needed for VB templates. https://github.com/efcore/EFCore.VisualBasic/pull/83? /cc @lorcQc
EF7 allows templates to be used for scaffolding a DbContext and model from an existing database. We implemented C# support and provided extension points for other languages. This change is needed for the in-progress community implementation of VB support.
Allows the community to add VB support for scaffolding templates.
**How found**
Community work implementing VB support.
**Regression**
No. New feature.
**Testing**
The VB implementation will be the primary testing of this.
**Risk**
Low; no impact on C# support.
> Templates: Specify a groupIdentity for ef-templates

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/FieldsOnlyLoadTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseOneToOne.cs
- test/EFCore.Specification.Tests/GraphUpdates/ProxyGraphUpdatesTestBaseOneToOneAk.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/LoadTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
The new nested entity was being fixed up to the deleted double-nested entities.
Fixes #29085
When a nested owned entity that itself has a nested owned entity is replaced and a navigation to the double-nested entity is set to null, then new nested entity is fixed up to the deleted double-nested entity.
The double-nested entity is not deleted when it should be, leading to incorrect data in the database.
**How found**
**Regression**
No; same behavior in 6.0. We will consider porting to 6.0.
**Testing**
Significant testing added around double-nested owned entities.
**Risk**
Low; bug fix for double-nested entities.
> Don't fixup to deleted entities

- global.json
- src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
Fixes #29007
Without this, a lot of unncessary `HasColumnOrder` calls are generated in the scaffolded code.
Yes.
Low. This more closely resembles the code we had in EF Core 6.0.
Automated tests added.
> [release/7.0] Scaffolding: Don't scaffold HasColumnOrder

- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
Test-only fix for 7.0.
Closes #29135
> Sproc test fixes around concurrency tokens

- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
This is the stable version that contains the Wasm libraries for .NET 7.
> [release/7.0-rc2] Update to SQLitePCLRaw 2.1.2

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
> Reduce indentation in SqlTranslator

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SetPropertyCalls.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/FiltersInheritanceBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/EntitySplittingTestBase.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
Fixes #28968
This is a non-breaking tweak to a new API introduced in EF7. It allows a simpler form to be used for `ExecuteUpdate`. Specifcally,
```C#
.SetProperty(p => p.Name, "Shay")
```
can be used instead of
```C#
.SetProperty(p => p.Name, _ => "Shay")
```
There may be many calls to `SetProperty` and setting to a value that does not depend on any other values in the entity is a very common case.
Shorter, more readable code for a frequently used common case.
**How found**
Customer suggestion.
**Regression**
No. New API, and this is non-breaking for existing use of that API in RC1.
**Testing**
New tests added.
**Risk**
Low; non-breaking tweak to new API.
----
@smitpatel as discussed offline. Added various closure tests, funcletizer seems to be humming …
> Allow specify property value without lambda in ExecuteUpdate 

- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/Internal/InternalDbSet.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Fixes #29164
Fix memory leak when using context pooling by not continually registering a listener every time a context is obtained from the pool and a `DbSet.Local` is used.
Fixes memory leak when using context pooling, which is becoming more common.
**How found**
**Regression**
No.
**Testing**
New testing added.
**Risk**
Low; small change.
---
This change treats the LocalView as one of the resettable services and resets it rather than severing when the context is returned to the pool. This fixes a memory leak because the view was previously recreated and re-registered with _the same StateManager_ every time the context was re-used, these registrations were never cleared. But since the StateManager is reused, the local views can also …
> [release/7.0] Reset LocalView when returning context to the pool

- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
When a dependent entity shares a table with its principal but does not have any required properties, then the meaning of all all dependent columns being null is ambiguous. It could mean that the entity does not exist, or it could mean that the entity exists but all its properties have null values. We therefore warn about this kind of mapping and recommend against it. Nevertheless, it is still used by customers, and in EF7 we broke some cases like this. This change reverts those breaks.
Customers using optional owned dependents with table splitting and no required properties will get exceptions.
Updating docs for EF7.
Yes, from 6.0.
Regression tests added.
Low; reverts back to the EF Core 6.0 code.
Resolves #29196
> Query: Generate condition for table splitting when no required properties

- azure-pipelines.yml
- eng/helix.proj
As a part of https://github.com/dotnet/arcade/issues/10123, we are moving all docker containers to the "latest" tagging schema
> Change Docker tags to latest schema

- src/EFCore.Relational/Metadata/Internal/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Query/RelationalEntityShaperExpression.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressionFactory.cs
- test/EFCore.Relational.Specification.Tests/Query/OwnedEntityQueryRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedEntityQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
Resolves #29142
Same area as fix #29207, but this time when using entity equality. 
When a dependent entity shares a table with its principal but does not have any required properties, then the meaning of all all dependent columns being null is ambiguous. It could mean that the entity does not exist, or it could mean that the entity exists but all its properties have null values. We therefore warn about this kind of mapping and recommend against it. Nevertheless, it is still used by customers, and in EF7 we broke cases where this is used with entity equality. This change reverts those breaks.
Customers using optional owned dependents with table splitting and no required properties will get exceptions using entity equality.
Customer reported on EF7 RC1.
Yes, from 6.0.
Regression tests …
> Generate condition for required property in optional dependents

- src/EFCore.SqlServer/Query/Internal/SqlServerStringAggregateMethodTranslator.cs
Fixes #29229
When translating SQL Server aggregate string methods (string.Join, string.Concat), the maximum size for unicode/non-unicode strings is reversed, leading to an incorrect type mapping for the result
Reproducing an observable bug here isn't trivial (and may not be possible), since SqlServerStringTypeMapping has checks and doesn't take the incorrect size into account. However, the fix is trivial and ensures the correctness of the type mapping.
**How found**
**Regression**
No, new feature (aggregate string function translation.
**Testing**
New testing added.
**Risk**
Very low; small self-evident fix in new code introduced for a new 7.0 feature only.
> Fix result mapping string size in SQL Server string aggregate translator

- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalOwnedQuerySqlServerTest.cs
Resolves #29201
Regression in a relatively important case where aggregate functions are used over owned type mapped to the same table as the owner. For example:
```C#
var query = context.Books
.GroupBy(post => post.Author.Id)
.Select(grouping => new
{
Author = grouping.Key,
TotalCost = grouping.Sum(post => post.Detail.Price),
});
```
This was due to a significant change in the design for aggregate functions, enabling a lot of new functionality in EF7. We were missing test cases for this.
Exception in a relatively common query case that worked in EF Core 6.0.
Found writing docs for new features.
Yes. from 6.0.
New testing added; will also investigate additional testing in this area.
Low, since the test removes an incorrect check when looking for errors.
> [release/7.0] Query: Don't fail translation of aggregate when owned navigations

- azure-pipelines.yml
- eng/helix.proj
We decided to remove the '-latest' part of the docker tag
> Remove 'latest' from the docker tag

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionInternal.cs
Fixes #28967
Connection pooling was designed to improve throughput in both high-traffic web scenarios and when using encryption. However, customers reported that when using encryption via SQLCipher, performance had not improved--it was still deriving the encryption key every time a connection was opened. This PR avoids that behavior and ensures the key is only derived once per pooled connection.
No.
Low. This just moves the logic to a place where it will only be executed once per pooled connection instead of every time an ADO.NET connection is opened. The logic will continue to be skipped when not using encryption.
Manually verified the new perf characteristics. This simple benchmark goes from 5078 ms to 124.
```cs
using Dapper;
using Microsoft.Data.Sqlite;
using var connection = new …
```
> [release/6.0] Microsoft.Data.Sqlite: Avoid re-sending PRAGMA key on pooled connections

- src/EFCore.Relational/Storage/RelationalDataReader.cs
- test/EFCore.Relational.Tests/Storage/RelationalDataReaderTest.cs
Fixes #28988
In EF Core 6.0, we started recycling RelationalDataReader instances across RelationalCommand invocations, to optimize the query pipeline and cut down on needless allocations. However, the RelationalDataReader retains its reference to its DbDataReader until a new query is executed; if a BufferedDataReader is used, that can mean needlessly preventing garbage collection of lots of all query data. This is exarcebated by context pooling (where the context is kept around for much longer).
Significantly increased memory usage when a retrying execution is used, context pooling is activated and large results are queries from the database.
**How found**
**Regression**
Yes, in 6.0.
**Testing**
Added a test.
**Risk**
Low.
This …
> [release/6.0] Clear reference to DbDataReader from RelationalDataReader

- src/EFCore.Sqlite.Core/Query/Internal/SqliteDateTimeAddTranslator.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindMiscellaneousQuerySqliteTest.cs
We were using TimeSpan.TicksPerDay rather than TicksPerSecond in the translation. Fixing the typo and correcting the test.
Fixes #29260
> [8.0] Fix to #29260 - Sqlite: AddTicks translation gives incorrect results

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Fixes #29079
When querying optional dependents using table sharing normally EF determines whether they exist by checking all required non-shared columns for NULLs. However, if they are also using entity splitting EF would need to check all table fragments which would be suboptimal from a perf standpoint. Currently EF will only check the properties on the main fragment and the added validation will throw for models that could produce invalid results.
No. Entity splitting is a new feature.
Low. This change is constrained to model validation.
> Validate that the main fragment of optional dependents that use table sharing have at least one required non-shared property

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- test/EFCore.Relational.Specification.Tests/Query/EntitySplittingQueryTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/EntitySplittingQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/EntitySplittingQuerySqliteTest.cs
Fixes #29104
When a split fragment is sharing the table with the main fragment of the principal type and the main fragment of the dependent type shares the table of a split fragment of the principal type then any attempt to insert a row will result in a circular dependency. This change adds model validation to fail early for this type of models.
No. Entity splitting is a new feature.
Low. This change is constrained to model validation.
> Validate that if any fragments use table sharing then the main fragments are mapped to the same table

- src/EFCore.Relational/Query/JsonQueryExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Problem was that in VisitChildren for JsonQueryExpression we were not passing key columns stored in _keyPropertyMap thru the visitor, so the aliases got out of sync. Fix is to process these key columns also and then update the JsonQueryExpression with new map if any of the columns have been modified by the visitor.
Fixes #29279
Exception in a relatively simple GroupBy + paging scenario involving new JSON mapping feature.
Found by a customer testing EF7 bits.
No, this is in the new feature.
New testing added for the reported scenario and additional cases around it.
Low, only affects JSON scenarios (code change is in the new class that only gets created to traverse JSON expressions). It should be safe to pass key columns through the visitor - we already do that for the JSON column. Could be …
> [release/7.0] Fix to #29279 - EF7 - GroupBy on Json column property + First/FirstOrDefault generates incorrect SQL

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Problem was that were not creating navigation bindings for JSON entities in the SelectExpression ctor which takes TableExpressionBase as argument. This would cause error in SharedTypeEntityExpandingExpressionVisitor which depends on those bindings to be present for entities mapped to JSON.
Fix is to use the same logic we use in the "main" SelectExpression ctor.
Fixes #29355
All queries using FromSql on entities that contain owned types mapped to JSON fail with NRE. FromSql is not the mainline scenario for JSON, but it could be used to work-around limitations in our JSON query translation capabilities, which is important given that there are quite a few limitations for JSON in the EF7 release. This issue effectively prevents the customers from using the workaround to …
> [release/7.0] Fix to #29355 - FromSqlRaw throws Exception when querying all objects that contain a certain string property in a json array column

- src/Shared/Multigraph.cs
- test/EFCore.Relational.Specification.Tests/Update/NonSharedModelUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/NonSharedModelUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/NonSharedModelUpdatesSqliteTest.cs
Fixes #29356
In 7.0, we added a perf optimization where our topological sort identifies special graph edges which require a batching boundary (e.g. between adding a principal with a database-generated ID and a dependent). However, in certain cases where there's a cycle in the graph and we perform cycle breaking, the batching boundary wasn't respected, and both commands were sent together in the same batch, causing an error.
Certain update patterns which have worked before now produce an exception.
**How found**
Customer reported on 7.0 RC.
**Regression**
Yes, in 7.0 (unreleased).
**Testing**
Added a test.
**Risk**
Low, minimal simple change.
> [release/7.0] Fix batching boundary with cycle breaking

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> Support value tuples in CSharpHelper

- .config/tsaoptions.json
- azure-pipelines.yml
- add new schedule for a weekly run
- add top-level parameter enabling CodeQL3000 in manual builds
- mix CodeQL3000 tasks into regular build; avoid large duplications
- skip other jobs in CodeQL3000 runs
- set `$(UseSharedCompilation)` to `false` to ease analysis
- tag CodeQL3000 runs
- add a tsaoptions.json file
- cribbed values from our eng/sdl-tsa-vars.config file
nit: Unconditionally disable the auto-injected component governance build step
- job.yml inserts the task where we need (unless overridden)
> Add CodeQL3000 run to efcore-ci-official

- azure-pipelines.yml
- add tag only when CodeQL3000 tasks did useful work
- ignore no-op task executions
- correct tsaoptions.json location
> !fixup! Correct CodeQL3000 setup

- .config/tsaoptions.json
- azure-pipelines.yml
- backport of #29425
- add new schedule for a weekly run
- add top-level parameter enabling CodeQL3000 in manual builds
- mix CodeQL3000 tasks into regular build; avoid large duplications
- skip other jobs in CodeQL3000 runs
- set `$(UseSharedCompilation)` to `false` to ease analysis
- tag CodeQL3000 runs
- add a tsaoptions.json file
- cribbed values from our eng/sdl-tsa-vars.config file
> [release/7.0] Add CodeQL3000 run to efcore-ci-official

- .config/tsaoptions.json
- azure-pipelines.yml
- backport of #29425 via #29438
- add new schedule for a weekly run
- add top-level parameter enabling CodeQL3000 in manual builds
- mix CodeQL3000 tasks into regular build; avoid large duplications
- skip other jobs in CodeQL3000 runs
- set `$(UseSharedCompilation)` to `false` to ease analysis
- tag CodeQL3000 runs
- add a tsaoptions.json file
- cribbed values from our eng/sdl-tsa-vars.config file
> [release/6.0] Add CodeQL3000 run to efcore-ci-official

- src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
- test/EFCore.Relational.Specification.Tests/Query/SimpleQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Resolves #27954
Resolves #27524
Resolves #29204
Custom mappings to database functions are not using the correct type mappings for parameters of the functions. This makes it impossible to map these database functions. These issues have been fixed and tested in EF7, and this change brings the fixes back to LTS EF Core 6.0, since there are no workarounds.
Impossible to map database functions where the type mapping for parameters is important. There is no known workaround.
Multiple customer reports.
No.
These issues have been fixed and tested in EF7.
Low; correct type mappings now used.
> [release/6.0] Query: Use type mapping from IDbFunction while translating (#27995)

- build/dependencies.props
- version.props
I couldn't find any runtime/extensions packages that obviously needed updates, though we could update the aspnetcore.app version from 2.1.27 to 2.1.30
> Update branding to 2.1.39

- .config/tsaoptions.json
- azure-pipelines.yml
- build/templates/default-build.yml
- backport of #29425 via #29438 and #29439
- add new schedule for a weekly run
- add top-level parameter enabling CodeQL3000 in manual builds
- mix CodeQL3000 tasks into regular build; avoid large duplications
- skip other jobs in CodeQL3000 runs
- set `$(UseSharedCompilation)` to `false` to ease analysis
- tag CodeQL3000 runs
- add a tsaoptions.json file
- cribbed values from our eng/sdl-tsa-vars.config file
nit: `s/master/main/`
> [release/2.1] Add CodeQL3000 run to efcore-ci-official

- src/EFCore/Metadata/Builders/ConventionSetBuilder.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Add a generic overload of ConventionSetBuilder.Remove #29476
> Add a generic overload of ConventionSetBuilder.Remove

- src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- Adding ToString() on string columns
- Adding tests for the changes
Fixes #20839
> ToString() on string columns added

- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/FromSqlQuerySqliteTest.cs
> Fix to #29365 - Query/Test: convert FromSql tests to use query infra

- src/EFCore.SqlServer/Query/Internal/SqlServerObjectToStringTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteObjectToStringTranslator.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NorthwindBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
> Add test for ExecuteUpdate with two inner joins

- src/EFCore.SqlServer/Query/Internal/SearchConditionConvertingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Search condition visitor wasn't handling json scalar expressions properly - we should convert them into search conditions/values just like we do with regular columns
Fixes #29572
> [SMALL] Fix to #29572 - Json: predicate on json bool property generates incorrect sql

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/RelationalMethodCallTranslatorProvider.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
> Detect DbFunction returning a nullable value expression

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- test/EFCore.Relational.Specification.Tests/Update/NonSharedModelUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.SqlServer.FunctionalTests/Update/NonSharedModelUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/NonSharedModelUpdatesSqliteTest.cs
> Make DbUpdateException.Entries contain all entries when we can't populate it

- src/EFCore/ValueGeneration/TemporaryNumberValueGeneratorFactory.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
Fixes #29406
The value generator selection was returning a generator for the converted type, when a value for the non-converted type should have been used.
> Fix value generation with converter between different numeric types

- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Fixes #29517
Parameter-reordering works for exception messages, but doesn't work for log messages. Also checked there are no other cases of this.
> Fix passing property and entity type names to ValueGenerated messages

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
…Synapse Serverless SQL Pool SKUs for query only operations
Index query breaks on TDS endpoint, but we can just skip it
sys.views does not exist on TDS endpoint
No temporal, memory optimized or sequences in these engines
Rephrase of FK query due to lack of schema functions on TDS endpoint
Smoke tested against both engines with a CRM schema
fixes #29121
> Reverse engineering of Dynamics CRM TDS endpoint and Synapse Serverless SQL Pool

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
> Fix making column required on SQL Server with idempotent migrations

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
> Use correct parameter in query based on type mapping

- azure-pipelines.yml
- eng/helix.proj
- similar to #29575 but Helix jobs use macOS here
- also align helix.proj (default) Helix queues w/ CI choices
> [release/7.0] Use simpler Docker tags

- src/EFCore.Relational/Query/Internal/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/Shared/ExpressionExtensions.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTInheritanceBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqliteTest.cs
> Support interfaces and entities with owned types in ExecuteUpdate setter property lambda

- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
This moves the application of pending bulk commands to before we snapshot the SQL position, result set count, etc. This way, if the new command goes beyond the parameter limit and causes a rollback, we don't lose the pending bulk commands.
Fixes #29539
> Fix SQL Server bulk insert edge case

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingSourceTest.cs
> SQLite type mapping should not be returned without converter when CLR type does not match

- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteParameterBasedSqlProcessor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteParameterBasedSqlProcessorFactory.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteRegexMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlExpressionFactory.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteSqlNullabilityProcessor.cs
- src/EFCore.Sqlite.Core/Query/SqlExpressions/Internal/GlobExpression.cs
- src/EFCore.Sqlite.Core/Query/SqlExpressions/Internal/RegexpExpression.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindDbFunctionsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindFunctionsQuerySqliteTest.cs
> SQLite: Use infix GLOB and REGEXP operators

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
> Fix bug where a non-sproc command comes before a sproc command

- src/EFCore/ChangeTracking/IPrincipalKeyValueFactory`.cs
- src/EFCore/ChangeTracking/Internal/CompositeDependentKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/CompositePrincipalKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/CompositeValueFactory.cs
- src/EFCore/ChangeTracking/Internal/DependentKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/DependentKeyValueFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/DependentsMap.cs
- src/EFCore/ChangeTracking/Internal/IDependentsMap.cs
- src/EFCore/ChangeTracking/Internal/IIdentityMap.cs
- src/EFCore/ChangeTracking/Internal/IIdentityMap`.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/IdentityMap.cs
- src/EFCore/ChangeTracking/Internal/KeyValueFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/ChangeTracking/ValueComparer.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/IEntityFinder.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/Metadata/IKey.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/FindEntryTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> Thanksgiving project: lookup entities by primary key, alternate key, or foreign key

- src/EFCore.Relational/Metadata/Conventions/TableSharingConcurrencyTokenConvention.cs
- test/EFCore.Relational.Specification.Tests/F1RelationalFixture.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Specification.Tests/F1FixtureBase.cs
- test/EFCore.Specification.Tests/F1MaterializationInterceptor.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/Circuit.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/CircuitTpc.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/CircuitTpt.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/City.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/F1Context.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/Fan.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/FanTpc.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/FanTpt.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/SwagBag.cs
- test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
Fixes #29689
Also add more end-to-end tests for optimistic concurrency, converters, owned types, inheritance, and table sharing.
> Handle row-version columns in owned types with conversions

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/CollectionIndexerToElementAtNormalizingExpressionVisitor.cs
- src/EFCore.Relational/Query/JsonQueryExpression.cs
- src/EFCore.Relational/Query/PathSegment.cs
- src/EFCore.Relational/Query/RelationalQueryTranslationPreprocessor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindCompiledQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerCondition.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerConditionAttribute.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestEnvironment.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/NorthwindCompiledQuerySqliteTest.cs
Converting indexer over list/array into ElementAt, so that nav expansion understands it and can perform pushown and inject MaterializeCollectionNavigation expression where necessary. In translation phase we recognize the pattern that nav expansion creates and if the root is JsonQueryExpression, we apply collection index over it. JsonQueryExpression path segment now consists of two components - string representing JSON property name and SqlExpression representing collection index (it can be constant, parameter or any arbitrary expression that resolves to int)
Deduplication is heavily restricted currently - we only de-duplicate projections whose additional path consists of JSON property accesses only (no collection indexes allowed). All queries projecting entities that need JSON array …
> Fix to #28648 - Json/Query: translate element access of a json array

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/ColumnBase.cs
- src/EFCore.Relational/Update/Internal/ColumnAccessorsFactory.cs
- src/EFCore.Relational/Update/Internal/RowForeignKeyValueFactoryFactory.cs
- src/EFCore.Relational/Update/Internal/SimpleNullablePrincipalRowForeignKeyValueFactory.cs
- src/EFCore.Relational/Update/Internal/SimpleRowKeyValueFactory.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore/ChangeTracking/Internal/CurrentValueComparerFactory.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Address.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/MismatchedKeyTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
Make `IColumn.ProviderClrType` always non-nullable for value types
Fixes #29531
> Allow shared columns with nullable value converters

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/Internal/CompiledQueryBase.cs
- test/EFCore.Tests/Query/CompiledQueryTest.cs
> Throw if CompiledQuery is used with different models

- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/CompositeRowIndexValueFactory.cs
- src/EFCore.Relational/Update/Internal/CompositeRowKeyValueFactory.cs
- src/EFCore.Relational/Update/Internal/CompositeRowValueFactory.cs
- src/EFCore.Relational/Update/Internal/IRowIndexValueFactory.cs
- src/EFCore.Relational/Update/Internal/IRowIndexValueFactory`.cs
- src/EFCore.Relational/Update/Internal/SimpleRowIndexValueFactory.cs
- src/EFCore/Update/EquatableKeyValue.cs
- src/Shared/Multigraph.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
> Make unique index SaveChanges topological dependency optional for null values

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Include table name for overrides in snapshot.

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
> Allow underscores in identifiers again

- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Infrastructure/ExpressionExtensions.cs
- src/EFCore/Query/ExpressionPrinter.cs
- src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NorthwindBulkUpdatesTestBase.cs
- test/EFCore.Specification.Tests/QueryExpressionInterceptionTestBase.cs
- test/EFCore.Tests/Query/ExpressionPrinterTest.cs
And some cleanup
Closes #29851
> Add static Print methods to ExpressionPrinter

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
> Avoid redundant looping in property metadata

- src/EFCore.Abstractions/Infrastructure/ILazyLoader.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LazyLoadingEventData.cs
- src/EFCore/Infrastructure/Internal/LazyLoader.cs
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/IInjectableService.cs
- src/EFCore/Internal/ManyToManyLoader.cs
- src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/IMemberClassifier.cs
- src/EFCore/Metadata/Internal/MemberClassifier.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/Shared/PropertyInfoExtensions.cs
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.Specification.Tests/F1FixtureBase.cs
- test/EFCore.Specification.Tests/FieldsOnlyLoadTestBase.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/LoadTestBase.cs
- test/EFCore.Specification.Tests/ManyToManyFieldsLoadTestBase.cs
- test/EFCore.Specification.Tests/ManyToManyLoadTestBase.cs
- test/EFCore.Specification.Tests/UnidirectionalManyToManyLoadTestBase.cs
- test/EFCore.Specification.Tests/WithConstructorsTestBase.cs
- test/EFCore.Specification.Tests/test/EFCore.Specification.Tests/LazyLoadTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/LazyLoadProxySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
- test/EFCore.Tests/Metadata/Conventions/ServicePropertyDiscoveryConventionTest.cs
Part of #10042
Current limitations are:
- The lazy-loading delegate injection doesn't support tracking of when an navigation is loaded or not; I have an idea for this
- There is no identity resolution when the entities are not tracked, even if the query behavior is NoTrackingWithIdentityResolution
- The model should validated for only a single service property for a given type
I will submit PRs and/or file issues for these things.
> Most of explicit and lazy loading for no-tracking queries

- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Gift.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Lift.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPCTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPTTest.cs
Fixes #29789
Also tests for #29874 and #29875
> Update discriminator columns when PK-to-PK dependent type is changed

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/JsonProjectionInfo.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/ExpressionPrinter.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Reworking shaper to properly track key values for JSON entities that are accessed via array element. Every array access needs to be recorded and incorporated into the key later. Constants can be stored directly by value, non-constants are added to projection, and we keep track of the projection index instead.
- added JsonProjectionInfo in place of a value tuple to store shaping info needed for JSON, so that it's more readable,
- reworked JsonShapingPreProcess to generate and cache key values as well as JsonElement.
- moved dangling (i.e. not coming from include on the owner entity) JSON entity processing after Include processing, so that we guarantee to have all the entities in state manager by the time we get to processing the dangling JSON stuff.
Fixes #29513
> Fix to #29513 - Json: improve projection deduplication for scenarios containing collection indexers

- src/EFCore.Design/Scaffolding/Internal/CSharpRuntimeModelCodeGenerator.cs
- src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
- src/EFCore/Metadata/Conventions/RuntimeModelConvention.cs
- src/EFCore/Metadata/IConventionEntityType.cs
- src/EFCore/Metadata/IMutableEntityType.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalServicePropertyBuilder.cs
- src/EFCore/Metadata/Internal/ServiceProperty.cs
- src/EFCore/Metadata/RuntimeEntityType.cs
- src/EFCore/Metadata/RuntimeServiceProperty.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
- test/EFCore.Specification.Tests/LazyLoadTestBase.cs
- test/EFCore.Specification.Tests/LoadTestBase.cs
Fixes #10042
Service properties have two uses:
1. Allow the entity to use the service directly
2. Allow EF to store state on the entity
This change allows 2 to happen without the entity needing to take a dependency on the service type. This allows the lazy-loader to store loaded state in the entity.
> Allow service properties typed as object

- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Diagnostics/LoggingDefinitions.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/ManyToManyTrackingTestBase.cs
- test/EFCore.Specification.Tests/NonSharedModelTestBase.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryFixtureBase.cs
- test/EFCore.Specification.Tests/ValueConvertersEndToEndTestBase.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
> Warn when entity type, property, or navigation is ignored after being explicitly mapped

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/ManyToManyLoader.cs
- src/EFCore/Metadata/Conventions/ServicePropertyDiscoveryConvention.cs
- src/EFCore/Metadata/IReadOnlyEntityType.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/RuntimeEntityType.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> Dispose service properties when context is disposed or returned to the pool

- src/EFCore.Proxies/Proxies/Internal/ProxiesOptionsExtension.cs
- src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
- src/EFCore.Proxies/ProxiesExtensions.cs
- test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
- test/EFCore.Proxies.Tests/TestUtilities/TestContext.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
Part of #10787
Like the EF6 behavior, but opt-in.
> Allow ignoring non-virtual navigations with lazy-loading proxies

- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/DbContextOptionsBuilder`.cs
- src/EFCore/Extensions/EntityFrameworkServiceCollectionExtensions.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Infrastructure/ICoreSingletonOptions.cs
- src/EFCore/Infrastructure/Internal/CoreSingletonOptions.cs
- src/EFCore/Infrastructure/ServiceProviderAccessor.cs
- test/EFCore.Tests/DbContextServicesTest.cs
Fixes #13540
Scoped and transient internal services can obtain application services using the `DbContext` as a service locator. Singleton services cannot do this since they do not have access to the `DbContext`. This change allows the root application service provider to be registered as an `ISingletonOption` such that singleton internal services can resolve singleton and transient application services.
> Support resolving application services from singleton internal services

- src/EFCore.SqlServer/Storage/Internal/SqlServerLongTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs
> Long and ULong properties marked as rowversion automatically convert to binary on SQL Server

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.Relational/Storage/ValueConversion/RelationalConverterMappingHints.cs
- src/EFCore/Storage/ValueConversion/ConverterMappingHints.cs
- test/EFCore.SqlServer.FunctionalTests/ValueConvertersEndToEndSqlServerTest.cs
> Fix relational mapping hints and add DbType

- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore/ChangeTracking/CaseInsensitiveValueComparer.cs
- src/EFCore/Storage/TypeMappingInfo.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
> Use case-insensitive string comparisons by default on SQL Server

- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs
Fixes #29539, backports #29669
In the SQL Server provider, when there are pending bulk inserts (into the same table) and a new command is added which  causes the batch to go over the parameter limit, we incorrectly rollback the pending commands and not just the new command.
When inserting a large number of rows in SQL Server, SaveChanges throws if the last command causes us to go over the parameter limit.
**How found**
**Regression**
Yes.
**Testing**
**Risk**
Low; the fix is quite trivial, and a quirk was added to revert back to older behavior.
> [release/7.0] Fix SQL Server bulk insert edge case (#29669)

- src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs
- test/EFCore.Relational.Specification.Tests/Update/StoredProcedureUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/StoredProcedureUpdateSqlServerTest.cs
Fixes #29643, #29680
In the new stored procedure mapping support, the logic to count parameters for the purpose of propagating sproc output variables incorrectly assumed all commands in the batch use a sproc. This causes us to propagate the wrong database-generated value into the wrong entity property.
When mixing both stored procedure and non-stored procedure updates in the same SaveChanges batch, database-generated values may cause an exception, or even get assigned to the wrong entity property (bad data).
**How found**
**Regression**
No.
**Testing**
**Risk**
Low; the fix is quite trivial, and a quirk was added to revert back to older behavior.
> [release/7.0] Fix bug where a non-sproc command comes before a sproc command

- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/InheritanceBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/NonSharedModelBulkUpdatesTestBase.cs
- test/EFCore.Relational.Specification.Tests/BulkUpdates/TPTInheritanceBulkUpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/NonSharedModelBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPCInheritanceBulkUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/TPTInheritanceBulkUpdatesSqliteTest.cs
Fixes #28727, backports #29672
The logic for verifying and handling property selectors for ExecuteUpdate does not take into account owned entities.
ExecuteUpdate does not work when the entity being updated has an owned entity (even if the update doesn't affect that owned entity).
**How found**
**Regression**
No.
**Testing**
**Risk**
Low; the fix is quite trivial, and a quirk was added to revert back to older behavior.
> [release/7.0] Support entities with owned types in ExecuteUpdate setter property lambda

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Query/GearsOfWarQueryRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindMiscellaneousQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQueryFiltersQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPCGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TPTGearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalGearsOfWarQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Fixes #29646, backports #29650
When the same parameter is used in a query in contexts which require different type mappings, we sometimes use the incorrect type mapping in the incorrect context.
Since the incorrect SQL representation or parameter may be sent to the server, LINQ queries may return incorrect data. For example, if the same .NET string is compared against both Unicode and non-Unicode database columns in a query, that could yield wrong results.
**How found**
**Regression**
Yes.
**Testing**
**Risk**
Low; the fix is quite trivial, and a quirk was added to revert back to older behavior.
> [release/7.0] Use correct parameter in query based on type mapping

- src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
When scaffolding an EF model from a database schema and using data annotations, incomplete code is generated for foreign key constraints referencing non-primary keys. This fix enables the missing code to be scaffolded.
Fixes #29418
Multiple customers have reported this. The only workaround is to update the scaffolded code once you discover it's incomplete.
The only indication that the code is incomplete is a runtime exception that will occur when querying data using the foreign key:
> SqlException: Invalid column name '{wrong-foreign-key-column}'.
Yes. EF Core 6 generated the correct code.
Added automated scaffolding tests covering several scenarios involving alternate principal keys.
Low. This just causes the same code to be generated whether or not you're using data annotations.
> [release/7.0] Scaffolding: Fix missing HasForeignKey when principal key is an alternate key

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Address.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Person.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
This is a port of #29746
Fixes #29531
The logic for verifying the compatibility of two properties sharing a column does not work when one of them has a value converter to a nullable value type.
Affected models will always throw an exception. There is no workaround that would preserve the functionality of the value converter.
**How found**
**Regression**
Yes.
**Testing**
**Risk**
Low; the fix only affects scenarios with shared columns that involve value converters, and a quirk was added to revert back to older behavior.
> [release/7.0] Allow shared columns with nullable value converters

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Migrations/MigrationsSqlGeneratorTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Migrations/SqlServerMigrationsSqlGeneratorTest.cs
Fixes #29530, backports #29619
Before EF 7.0, making a column non-nullable which contained nulls would fail. EF 7.0 added an UPDATE statement to convert nulls to a default value, but the SQL wasn't properly escaped.
Making a column non-nullable can cause the migration to fail in certain scenarios (when the column is renamed).
**How found**
**Regression**
Partial; this scenario used to work correctly as long as the column contained no nulls. When nulls were present, this already caused a failure (null constraint violation).
**Testing**
**Risk**
Very low; the fix is trivial and affects migrations only (no runtime impact). A quirk was added to revert back to older behavior.
> [release/7.0] Fix making column required on SQL Server with idempotent migrations

- src/EFCore/DbContext.cs
- src/EFCore/Internal/DbContextPoolConfigurationSnapshot.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Port of #29766
Fixes #29733
When using DbContext pooling, a query tracking behavior of NoTracking could be changed to TrackAll after the context has been returned to the pool and retrieved again.
Queries running with the wrong tracking behavior could result in application crashes, incorrect data, and reduced performance. 
**How found**
**Regression**
Yes, from 6.0.
**Testing**
Added a tests around this area where the tracking behavior is specified on the options builder.
**Risk**
Low; simple code change, and a quirk was added to revert back to older behavior.
> [release/7.0] Reset query tracking behavior correctly if set on DbContextOptions

- src/EFCore/Metadata/Internal/Property.cs
This is a port of #29805
Fixes #29642
The logic for reading property metadata is performing more loops than intended resulting in poor model building performance (affects migrations and app startup).
Non-trivial models take up to three times as long to build. There is no workaround.
**How found**
**Regression**
Yes.
**Testing**
Manual verification of the performance.
**Risk**
Low; the fix should not have any behavior impact, and a quirk was added to revert back to older behavior.
> [release/7.0] Avoid redundant looping in property metadata

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
This is a port of #29819
Fixes #29534
The model snapshot generated for a migration that includes types in a TPH hierarchy with table-specific configuration doesn't include the table name for derived classes.
The generated migration will not compile until the customer fixes it manually.
**How found**
Multiple customer reports on 7.0
**Regression**
Yes.
**Testing**
Added tests for the affected scenario
**Risk**
Low; the fix only impacts design-time tooling.
> [release/7.0] Include table name for overrides in snapshot.

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpRuntimeModelCodeGeneratorTest.cs
Port of #29821
Fixes #29450
A change in the validation of identifier names resulted in an unintentional breaking change.
If the generated files would contain underscores the customer needs to add them manually to allow them to compile against existing code.
**How found**
**Regression**
Yes.
**Testing**
Adjusted the tests for the affected scenario
**Risk**
Low; the fix reverts the affected code to the 6.0 version.
> [release/7.0] Allow underscores in identifiers again

- src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
This is a port of #29849
Fixes #29826
When there are already two foreign keys using a property the convention erroneously tries to reconfigure another foreign key to use the same property, fails and repeats.
An app with an affected model will hang in an infinite loop. There is no workaround other than removing this convention.
**How found**
**Regression**
Yes.
**Testing**
Added a test for this scenario
**Risk**
Low; the fix has limited scope and a quirk mode was added.
> [release/7.0] Avoid infinite loop during foreign key discovery

- src/EFCore.Relational/Update/ModificationCommand.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Gift.cs
- test/EFCore.Specification.Tests/TestModels/UpdatesModel/Lift.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPCTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTPTTest.cs
Port of #29876
Fixes #29789
EF generates an update when a dependent entity is deleted and replaced with a new entity that has the same PK. If that new entity is of a different type, then the discriminator column must be updated, but this is not happening in EF7.
Database contains rows that represent the wrong type of object; so potentially data corruption.
**How found**
**Regression**
Yes, from EF Core 6.0.
**Testing**
Added tests for the affected scenario and related.
**Risk**
Low; the fix is simple, and a quirk was added to revert back to older behavior.
> [release/7.0] Update discriminator columns when PK-to-PK dependent type is changed

- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/CompositeRowIndexValueFactory.cs
- src/EFCore.Relational/Update/Internal/CompositeRowKeyValueFactory.cs
- src/EFCore.Relational/Update/Internal/CompositeRowValueFactory.cs
- src/EFCore.Relational/Update/Internal/IRowIndexValueFactory.cs
- src/EFCore.Relational/Update/Internal/IRowIndexValueFactory`.cs
- src/EFCore.Relational/Update/Internal/SimpleRowIndexValueFactory.cs
- src/EFCore/Update/EquatableKeyValue.cs
- test/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTestBase.cs
Port of #29796
Fixes #29647
When SaveChanges performs the topological sort of the update commands it considers duplicate values for unique indexes as invalid and throws an exception. However, in many database providers duplicate `null` values are allowed for unique indexes.
Affected apps throw during SaveChanges for duplicate `null` values. The workaround is to add a filter to every unique index in the model and then manually edit the migration to avoid rebuilding the indexes.
**How found**
Multiple customer reports on 7.0
**Regression**
Yes.
**Testing**
Added tests for the affected scenario.
**Risk**
Medium; the fix considerably changes the implementation, but a quirk was added to revert back to older behavior.
> [release/7.0] Avoid circular dependency for unique indexes with null values

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
Port of #29866
Fixes #29859
The validation of provider CLR type for shared columns became stricter in 7.0 and it affected cases where the model wasn't actually invalid.
Affected models throw an exception during validation. There is no workaround.
**How found**
**Regression**
Yes.
**Testing**
Added tests for the affected scenario.
**Risk**
Low; the fix is to throw in fewer cases, and a quirk was added to revert back to older behavior.
> [release/7.0] Revert shared columns validation breaking change

- docs/DailyBuilds.md
Based on https://github.com/dotnet/efcore/issues/29956#issuecomment-1371386981
> Some tweaks to the daily build docs

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
The scaffolding code currently assumes that all relationships have bidirectional navigation properties. However, this isn't true for foreign keys constraints on keyless tables where only a one-directional relationship is allowed. This fix updates the scaffolding code to handle this case.
Fixes #29516
Multiple customers have reported this. They can work around it by adding custom scaffolding templates to their project and applying the fix locally. Without a fix, scaffolding will fail with a NullReferenceException.
Yes. This worked in EF Core 6.
Added an automated test covering this scenario.
Low. This just adds null handling to the existing code.
> [release/7.0] Scaffolding: Handle FK on keyless entity type

- src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.tt
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Certain patterns of many-to-many join tables that don't follow the EF Core conventions--most notably ones generated by EF6--result in an incomplete model when scaffolding. This fix adds additional handling for these patterns.
Fixes #29544, fixes #29634
Multiple users have reported issues in this area. Some issues can be worked around by applying the fix to custom scaffolding templates. Others require manually updating the code after it's scaffolded. The incorrect models result in runtime exceptions about missing tables and columns.
Yes. Correct models were scaffolded in EF Core 6.
Added automated tests covering more unconventional many-to-many join tables.
Low. Adds back code that I neglected to port as part of the custom templates feature.
> [release/7.0] Scaffolding: Fix code for EF6 many-to-many pattern

- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs
- src/EFCore.Relational/Storage/IRelationalConnection.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteDbContextOptionsBuilderExtensions.cs
- test/EFCore.Relational.Tests/RelationalConnectionTest.cs
- test/EFCore.Relational.Tests/RelationalEventIdTest.cs
- test/EFCore.Relational.Tests/RelationalOptionsExtensionTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConnectionSpecificationTest.cs
- test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
- test/EFCore.Sqlite.Tests/SqliteDbContextOptionsBuilderExtensionsTest.cs
> Allow transfer of ownership of DbConnection from application to DbContext

- test/EFCore.Analyzers.Tests/EFCore.Analyzers.Tests.csproj
This PR does not fix any bugs or add new features and is very small in size, so I think, it doesn't need an issue to be opened first. I just notecied, that for whatever reason analyzer tests have a dependency on a VB package, while the analyzers themselves are for C# only. I verified, that removing this dependency doesn't break test execution locally. If there is some mysterious sense in having this dependency, I won't regret if the PR gets closed. It actually took more time to setup EF repo on my machine than the time taken by the actual change...
> Remove unnecessary dependency on MS.CA.VB package

- src/EFCore/ModelBuilder.cs
> Fix typo in ApplyConfigurationsFromAssembly XML doc

- src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs
> Correct ExpressionPrinter in [DebuggerDisplay]

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- src/EFCore.Relational/Query/SqlNullabilityProcessor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/NorthwindIncludeQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindEFPropertyIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeNoTrackingQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSplitIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindStringIncludeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
> Fix split query over GroupBy over parameter

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.Helper.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsCollectionsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsCollectionsSplitQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/TemporalComplexNavigationsCollectionsSharedTypeQuerySqlServerTest.cs
Fixes #30022, backports #30024
A bug in split query handling results in an incorrect SQL query tree.
Valid LINQ queries involving split queries and GroupBy which worked in EF Core 6.0 throw NullReferenceException in 7.0.
**How found**
Customer report on 7.0.
**Regression**
Yes, from 6.0.
**Testing**
Added tests for the affected scenario.
**Risk**
Very low; the bug is very obvious and the fix is a one-liner.
> [release/7.0] Fix split query over GroupBy over parameter (#30024)

- benchmark/EFCore.Sqlite.Benchmarks/EFCore.Sqlite.Benchmarks.csproj
- src/EFCore.Sqlite/EFCore.Sqlite.csproj
- src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.csproj
- src/Microsoft.Data.Sqlite/Microsoft.Data.Sqlite.csproj
- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.e_sqlcipher.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.sqlite3.Tests.csproj
- test/Microsoft.Data.Sqlite.Tests/Microsoft.Data.Sqlite.winsqlite3.Tests.csproj
This version includes a fix for its projection of the native `sqlite3_load_extension` API.
Fixes #29584
Multiple users have reported issues when trying to load the SQLite spatial extension SpatiaLite. It fails with the following obscure error.
> SqliteException: SQLite Error 1: ''.
Some users have been able to work around the issue by manually loading the native library before calling EF APIs. Another work around, now that SQLitePCLRaw has been fixed, is to manually update the transitive dependency. But EF will remain broken by default for spatial scenarios on SQLite unless we update our dependency.
Yes. This worked on EF Core 6.
We have automated tests covering these scenarios, but because they have proved flakey on Helix, we changed them to fail as a skip warning instead. We didn't …
> [release/7.0] Update to SQLitePCLRaw 2.1.4

- src/EFCore.Relational/Metadata/Internal/ForeignKeyConstraintComparer.cs
- test/EFCore.Relational.Tests/Metadata/RelationalModelTest.cs
Fixes #29741
A foreign key constraint is lost when the model contains two tables with the same name, but in different schemas with FKs referencing the same table. This causes exceptions during SaveChanges and invalid migrations. There are no known workarounds.
No.
Low. This change is constrained to FK comparison and a quirk mode was added.
> [release/7.0] Take schema into account when comparing FK constraints.

- src/EFCore.Design/Extensions/ScaffoldingModelExtensions.cs
- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
The code generation tests use a model builder which produces a slightly different model than the scaffolding model factory. This compensates for some of those differences to make the test assertions closer to what the end-to-end scaffolding pipeline generates.
> Scaffolding: Clean up code generation tests

- src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
- test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
Also when non-virtual navigations are allowed.
Fixes https://github.com/dotnet/efcore/issues/10787#issuecomment-1385422910
> Allow field navigations in proxies when lazy-loading is disabled for the navigation

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
> Remove regex from SqlServerMigrationsSqlGenerator

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
Problem was that when we were translating join, combining two SelectExpressions together, we were not remapping JSON column indexes stored in the inner select. This later result in shaper trying to read JSON column data from the wrong index and throwing the exception.
We already had a test that would have caught that, but it didn't return any data so the mismatch was never detected - fixed the data issue and added few more tests for good measure.
Fixes #30073
> [SMALL] Fix to #30073 - JSON query regression in EF8

- test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalQueryAsserter.cs
Our tests sometimes create a DbCommand (e.g. by calling CreateDbcommand on a queryable, see ExecuteOurDbCommand in RelationalQueryAsserter), and then execute it, assuming the connection is open. This currently works because the test store happens to do UseSqlServer with an open connection. But with some integration of DbDataSource in Npgsql, the connection isn't open at that point; this makes the test open it if necessary.
> Open connection in tests if needed

- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
> Remove unchecks in SQL Server type mappings

- src/EFCore/Infrastructure/ModelValidator.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/UnmappedCustomer.cs
> Throw for ad-hoc type with property that looks like collection navigation

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseMiscellaneous.cs
- test/EFCore.Specification.Tests/GraphUpdates/GraphUpdatesTestBaseOneToOne.cs
- test/EFCore.SqlServer.FunctionalTests/GraphUpdates/GraphUpdatesSqlServerOwnedTest.cs
Fixes #28961
In the issue, an alternate key was added over the the foreign key to make it effectively an identifying relationship. That is, changing the relationship changes the identity of the dependent. This resulted in the special handling for identifying relationships to kick in, which didn't respect the configured DeleteBehavior. This change fixes that.
> Stop allowing identifying relationships from overriding cascade behavior

- src/Microsoft.Data.Sqlite.Core/SqliteConnectionFactory.cs
This is a port of #30080
Fixes #29952
The field `_idlePoolGroups` was being used outside the lock.
`ArgumentOutOfRangeException` exceptions when using Microsoft.Data.Sqlite, even without connection pooling.
**How found**
Multiple customer reports on 7.0.
**Regression**
No.
**Testing**
**Risk**
Low; simple move of the lock area, and a quirk was added to revert back to older behavior.
> [release/7.0] Move taking of lock earlier to avoid race in PruneCallback

- src/EFCore.Relational/Query/QuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- test/EFCore.Cosmos.FunctionalTests/Query/NorthwindKeylessEntitiesQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/NorthwindKeylessEntitiesQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindKeylessEntitiesQuerySqlServerTest.cs
Ported from https://github.com/dotnet/efcore/pull/30134
Fixes #29667
Query using keyless entities that also uses Take and Count throws SqlException.
Query using keyless entities that also uses Take and Count throws SqlException. Scenario is not common, but it is a regression and there is no good workaround for it. Only options are to not use keyless entities or perform Count on the client (which can be a significant perf hit)
**How found**
Customer report on 7.0.
**Regression**
Yes. 
**Testing**
Added regression tests.
**Risk**
Low; Fix is very isolated, only affecting empty projection by adding an alias for it. Empty projection by definition can't be referenced in other parts of the query, so there is no risk of name clashes due to new alias. Also …
> [release/7.0] Fix to #29667 - Count after Take throws "No column name was specified for column 1 of 't'."

- src/EFCore.Relational/Metadata/Conventions/TableNameFromDbSetConvention.cs
- test/EFCore.Cosmos.FunctionalTests/Query/InheritanceQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/InheritanceQueryFixtureBase.cs
- test/EFCore.Specification.Tests/TestModels/InheritanceModel/DrinkType.cs
- test/EFCore.Specification.Tests/TestModels/InheritanceModel/InheritanceContext.cs
- test/EFCore.SqlServer.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncompleteMappingInheritanceQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/BulkUpdates/InheritanceBulkUpdatesSqliteTest.cs
> Don't set table names from DbSet properties when Discriminator property is conflicted with the default but is then configured explicitly

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/ColumnBase.cs
- src/EFCore.Relational/Update/Internal/ColumnAccessorsFactory.cs
- src/EFCore.Relational/Update/Internal/RowForeignKeyValueFactoryFactory.cs
- src/EFCore.Relational/Update/Internal/SimpleNullablePrincipalRowForeignKeyValueFactory.cs
- src/EFCore.Relational/Update/Internal/SimpleRowKeyValueFactory.cs
- src/EFCore/ChangeTracking/Internal/CurrentValueComparerFactory.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/ValueComparer`.cs
- src/EFCore/Metadata/Internal/Property.cs
- test/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Specification.Tests/UpdatesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Update/MismatchedKeyTypesSqlServerTest.cs
- test/ef.Tests/ef.Tests.csproj
Port of #29746
Fixes #29985
In EF7, processing seed data in the model snapshot could result in an incorrect provider type when the property has a converter. This change ports a fix already in EF8 to ensure provider types are used correctly.
Many customers reporting that models with seed data will continually update this data on every migration, even though the data never changes. This means every generated migration contains Up and Down steps, even when the migration should be empty. No reasonable workaround.
**How found**
Multiple customer reports on 7.0.
**Regression**
Yes.
**Testing**
New tests added for this kind of seed data in the model snapshot.
**Risk**
Medium. Significant code changes, but these changes have been in the 8.0 code for several …
> [release/7.0] Use correct provider type for nullable value type with converter

- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Port of #30214
Fixes #29899
With TPC mapping, it is common for to have derived types that are mapped to tables while the base type is not mapped to a table. In these cases, the default schema was not being picked up for the derived types.
Customer reported in relatively common scenario. There is a workaround to manually specify the schema on all tables, but this can get tricky, especially when the schema is obtained from the tenant in multi-tenant scenarios.
**How found**
Customer reported on 7.0.
**Regression**
No; new feature in 7.0.
**Testing**
Default schema set for more existing tests to give better coverage.
**Risk**
Low; trivial code change to get the default schema in cases like this, and quirked.
> [release/7.0] Use default schema for TPC tables (#30214)

- azure-pipelines-richnav.yml
- azure-pipelines.yml
- import the variable template
- use the two variables it provides wherever we name the pool
- future release branches will now automatically switch to the -Svc pools
> Use Arcade's pool-providers.yml

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs
Problem was that we when accessing inner property on a JsonElement we used GetProperty. If property is not present (which should be allowed if we try to access optional navigation) KeyNotFound is thrown.
Fix is to use TryGetProperty instead to gracefully handle this scenario.
Fixes #30028
> Fix to #30028 - Added nullable property to Json mapped model resulting in errors instead of mapping non existing json property to null

- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore.Sqlite.Core/Extensions/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Metadata/Internal/SqliteAnnotationProvider.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQuerySqlGenerator.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteJsonTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommand.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteModificationCommandFactory.cs
- src/EFCore.Sqlite.Core/Update/Internal/SqliteUpdateSqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonEntityConverters.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonOwnedConverters.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/JsonQuery/JsonQueryData.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateFixtureBase.cs
- test/EFCore.Relational.Specification.Tests/Update/JsonUpdateTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/JsonQueryAdHocSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/JsonQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/JsonQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Update/JsonUpdateSqliteTest.cs
Adding support for Sqlite.
Limitation:
When accessing element of a JSON array we can only use constant values. Unlike Sql Server which supports parameters, columns or even arbitrary expressions.
Also since JSON aggregates are mapped to own types, in case of collections users need to ignore SqliteEventId.CompositeKeyWithValueGeneration
Fixes #28816
> Fix to #28816 - Json: add support for Sqlite provider

- test/EFCore.Relational.Specification.Tests/Query/OperatorsProceduralQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/OperatorsQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityBase.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityBool.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityDateTimeOffset.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityInt.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityLong.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityNullableBool.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityNullableInt.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorEntityString.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorsContext.cs
- test/EFCore.Relational.Specification.Tests/TestModels/Operators/OperatorsData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OperatorsProceduralSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OperatorsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OperatorsProceduralSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OperatorsQuerySqliteTest.cs
Testing up to 6 sources (3 pairs for predicate, 2 trios for projection). Entities have 3-4 max rows so even if all 6 are used the result set is not too large. Unused sources are pruned so usually we end up using 3-4 sources.
> Adding procedural test generation to test interactions between various operators.

- test/EFCore.Relational.Specification.Tests/Query/SharedTypeQueryRelationalTestBase.cs
> Use NormalizeDelimitersInRawString in Ad_hoc_query_for_shared_type_entity_type_works

- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Update/JsonUpdateSqlServerTest.cs
when producing update statement, when deciding whether we need CAST around the result of JSON_VALUE, we need to look if the property has converter, rather than just look at it's clr type. If the clr type is string, but it gets converted to int/bool etc we still need a CAST.
Fixes #30330
> [SMALL] Fix to #30330 - Json: updating property with conversion from string to other type fails on sql server

- test/EFCore.Relational.Specification.Tests/Query/SqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SqlQuerySqlServerTest.cs
> Some fixes to SqlQueryTestBase

- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
Who's the idiot who embedded SqlServer in an inherited relational test...
> Make test provider-agnostic

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
> Handle entity paths with no tables in model differ

- .editorconfig
- All.sln.DotSettings
- test/EFCore.InMemory.FunctionalTests/ModelBuilding101InMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/ModelBuilding101TestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding101ManyToManyTestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding101OneToManyNrtTestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding101OneToManyTestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding101OneToOneNrtTestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding101OneToOneTestBase.cs
- test/EFCore.Specification.Tests/ModelBuilding101TestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ModelBuilding101SqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/ModelBuilding101SqliteTest.cs
These are the cases I used when writing the relationship docs. Since I ran into several issues, it seemed worthwhile to bring them over as regression tests. They should also help ensure that basic functional cases continue working the same when we change the implementation of conventions by adding layering.
> Port simple relationship scenarios from docs samples

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- test/EFCore.Relational.Tests/Infrastructure/RelationalModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
> Don't warn in model validation when bool property with default value has nullable backing field

- All.sln.DotSettings
- src/Microsoft.Data.Sqlite.Core/Extensions/TypeExtensions.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
Following a discussion on generic methods, this optimizes SqliteDataReader.GetFieldValue to take advantage of JIT elision when doing value-type checks. The mechanism (with produced assembly code) can be seen [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4aNYgGYGZBgGEGAbxoMdypcRQMAsgAoAlNt1bqu2wwDiMDADFxMADYATAGrZ3QmAAecTEAPhM6M1kbXQBfSx0EhgBtAClxDEcRGChxMBMMAE8OGAgAMxMQjDMzNAZ0zJhs3PyikvKTMvcIbGra+oysnLyC4tKKqoB+GrqGoZbR9orickizAF0kxQYqhydXDx8/AMCAFXDd6E8QvwsYnWs7XXEyhkXxk1OzBgBeH4Y2h8qjUkrZHk87MQAOwMcjRCEMeL3Oyg56vd4dL6/f6AjpdHp9VEPImQmGkeEQpEIkkvN64ipYv4AsYdKYg5Fgkm2aEMOBwklUiE09H0z7fJmilZrEnghE6HmrClPJEknkATg1SsRNFiQA).
Note that we can optimize nullable value types in the same way (`int?`) if we want. While looking at …
> Optimize SqliteDataReader.GetFieldValue

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Port of #30347
Fixes #30321
With TPC mapping (new feature in EF7), abstract types are not mapped to any table. This case was not being handled correctly in the model differ.
"Sequence contains no elements" exception when attempting to generate a migration for simple changes in abstract types. No workaround.
Customer reported on 7.0.
No; bug in new feature.
Tests updated.
> [release/7.0] Handle entity paths with no tables in model differ

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.tt
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
Port of #30311
Fixes https://github.com/dotnet/efcore/issues/30286
The generated code when reverse engineering (scaffolding) from an existing database was changed to drop the setter from collection navigation properties. The setter is not needed for EF use cases, so this made the generated code cleaner. However, it turns out that:
- Like to use the setter to set an entirely new collection, even though it isn't really designed to be used that way
- Some serializers, notably System.Text.Json, ignore properties without setters, even though the property is pre-initialized and so is never null or needs setting.
Multiple customers prefer the previously generated code, and, more importantly, System.Text.Json no longer serializes entities correctly. There is a …
> [release/7.0] Add back setter for scaffolded collection navigations

- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/JsonQueryAdHocTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryAdHocSqlServerTest.cs
Ported from #30101
Fixes #30028
Projecting or accessing into JSON object that has an optional subdocument that is missing (rather than being null) throws during query.
Customers are unable to query JSON objects when they are missing part of the document (which should be allowed when mapped using optional navigation). There is no good workaround, customers need to edit JSON and add the missing element(s). Also, we already patched similar issue, when the "leaf" property was missing rather than navigation - see https://github.com/dotnet/efcore/issues/29219
**How found**
Multiple customer reports on 7.0.
**Regression**
No. JSON support has been introduced in 7.0.
**Testing**
Added regression tests.
**Risk**
Low-Mid; Fix is relatively small and involves …
> [release/7.0] Fix to #30028 - Added nullable property to Json mapped model resulting in errors instead of mapping non existing json property to null

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/ExpressionEqualityComparer.cs
> Better exception when same parameter instance is reused in multiple lambdas

- global.json
From https://github.com/dotnet/aspnetcore-internal/issues/4250
> If your rotation falls on a Monday, update the SDK version in both [aspnetcore](https://github.com/dotnet/aspnetcore/blob/main/global.json) and [efcore](https://github.com/dotnet/efcore/blob/main/global.json) to the [latest available nightly](https://github.com/dotnet/installer)
> Update SDK to 8.0.100-preview.3.23156.3

- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.Specification.Tests/Query/NorthwindSetOperationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindSetOperationsQuerySqlServerTest.cs
Problem was that during SelectExpression pruning for set operations we would try to prune both sources independently. However, if a source is Distinct we can't prune (that could affect the result). So the problematic case is where we prune one source but can't prune the second due to Distinct, and we end up with both sources having not matching projections. Fix is to check if either source has Distinct before attempting to prune them.
Fixed #30273
> [SMALL] Fix to #30273 - EF7 generating incorrect SQL for the Concat/Union All, The same code was working fine for EF6.4.4

- test/EFCore.Relational.Specification.Tests/Query/OperatorsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OperatorsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OperatorsQuerySqliteTest.cs
Just adding regression test, bug already fixed by roji in the parentheses work.
Resolves #30181
> Regression test for #30181 - Missing parentheses when using Expression.Or over bool (instead of OrElse)

- src/EFCore/DbContext.cs
- test/EFCore.Specification.Tests/SaveChangesInterceptionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SaveChangesInterceptionSqlServerTest.cs
> Don't log both `SaveChangesFailed` and `OptimisticConcurrencyException` for same event
