src/EntityFramework.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/EntityFramework.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EntityFramework.Relational/Query/Expressions/AliasExpression.cs, src/EntityFramework.Relational/Query/Expressions/SelectExpression.cs, src/EntityFramework.Relational/Query/RelationalQueryModelVisitor.cs, src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, test/EntityFramework.Core.FunctionalTests/IncludeTestBase.cs, test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/QuerySqlServerTest.cs
When lifting OrderBys on Include subqueries we were always clearing the OrderBy on the subquery. However, if the subquery has a limit or offset specified, then we need to leave the OrderBy intact.
=> Fix #3732 - Include and Take generate incorrect SQL without Skip

src/EntityFramework.Commands/Migrations/Design/CSharpSnapshotGenerator.cs, test/EntityFramework.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs
@bricelam - Minor typo.
It was generating empty entity type declaration for derived type even if the relationship is defined in the base type only. e.g.
````
modelBuilder.Entity("TestApp.ApiDescriptionBase", b =>
{
b.HasOne("TestApp.ApiDescriptionBase")
.WithMany()
.HasForeignKey("ParentId");
});
modelBuilder.Entity("TestApp.ApiGroupDescription", b =>
{
});
````
=> [Tiny] :bug: Generate entity types with relationship declared on them

src/EntityFramework.MicrosoftSqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, src/EntityFramework.Relational/Extensions/ExpressionExtensions.cs, src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, test/EntityFramework.Core.FunctionalTests/AsyncQueryTestBase.cs, test/EntityFramework.Core.FunctionalTests/GearsOfWarQueryTestBase.cs, test/EntityFramework.Core.FunctionalTests/QueryTestBase.cs, test/EntityFramework.Core.FunctionalTests/TestModels/GearsOfWarModel/GearsOfWarModelInitializer.cs, test/EntityFramework.Core.FunctionalTests/TestModels/GearsOfWarModel/Weapon.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/GearsOfWarFromSqlQuerySqlServerTest.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EntityFramework.Relational.FunctionalTests/GearsOfWarFromSqlQueryTestBase.cs
resolves #3703 
Issue: SQL does not allow not operation on Boolean type directly. They must be compared with true or false. Fix is to convert unary operations on Boolean type to comparison operation.
resolves  #3618 
Issue: SQL does not allow comparison operation into projection. They must be wrapped in `Case When Then` block.
Fix: Whenever there is comparison operation into projection, convert it to conditional expression.
If comparison operation is inside conditional expression already then do no convert.
Issue: Comparison follows null semantics.
Implementation: While processing `SelectExpression` process the projection accordingly.
resolves #649 for projections
=> Boolean in select

src/EntityFramework.Commands/Scaffolding/Internal/EntityTypeWriter.cs, src/EntityFramework.Relational.Design/EntityFramework.Relational.Design.csproj, src/EntityFramework.Relational.Design/Metadata/Internal/ScaffoldingAnnotationNames.cs, src/EntityFramework.Relational.Design/Metadata/ScaffoldingMetadataExtensions.cs, src/EntityFramework.Relational.Design/Metadata/ScaffoldingPropertyAnnotations.cs, src/EntityFramework.Relational.Design/RelationalScaffoldingModelFactory.cs, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/AllDataTypes.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/OneToManyDependent.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/OneToOneFKToUniqueKeyDependent.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/OneToOneFKToUniqueKeyPrincipal.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/OneToOneSeparateFKDependent.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/PropertyConfiguration.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/SelfReferencing.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_AllFluentApi/Test_Spaces_Keywords_Table.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/AllDataTypes.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/OneToManyDependent.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/OneToOneFKToUniqueKeyDependent.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/OneToOneFKToUniqueKeyPrincipal.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/OneToOneSeparateFKDependent.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/PropertyConfiguration.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/SelfReferencing.expected, test/EntityFramework.MicrosoftSqlServer.Design.FunctionalTests/ReverseEngineering/ExpectedResults/E2E_UseAttributesInsteadOfFluentApi/Test_Spaces_Keywords_Table.expected, test/EntityFramework.Relational.Design.Tests/EntityFramework.Relational.Design.Tests.csproj, test/EntityFramework.Relational.Design.Tests/RelationalScaffoldingModelFactoryTest.cs, test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/FkToAltKey/Comment.expected, test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/ManyToMany/Users_Groups.expected, test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/OneToMany/OneToManyDependent.expected, test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/UseAttributesInsteadOfFluentApi/FkToAltKey/Comment.expected, test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/UseAttributesInsteadOfFluentApi/ManyToMany/Users_Groups.expected, test/EntityFramework.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/UseAttributesInsteadOfFluentApi/OneToMany/OneToManyDependent.expected
Fixes #4062. 
Note: this uses a Scaffolding-only ColumnOrdinal annotation for now. If we decide to add column ordering in a more general way to the model as a whole (see discussion in #2272) then we should change this code to use that instead.
=> RevEng: Generate Properties in same order as columns in DB

src/EntityFramework.Commands/build/netcore50/EntityFramework.Commands.props, src/EntityFramework.Core/build/netcore50/EntityFramework.Core.targets, src/EntityFramework.Core/project.json
We stripped out automatic inference in #4197. UWP projects *will fail* without generating runtime directives. We can help users catch this early with msbuild
(If this idea get's approved, I will replace the URL in the error message to a fwlink)
cc @bricelam
=> [uwp] Add build error if runtime directives are not present

src/EntityFramework.MicrosoftSqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, src/EntityFramework.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, test/EntityFramework.Core.FunctionalTests/GearsOfWarQueryTestBase.cs, test/EntityFramework.Core.FunctionalTests/TestModels/ComplexNavigationsModel/ComplexNavigationsModelInitializer.cs, test/EntityFramework.Core.FunctionalTests/TestModels/GearsOfWarModel/GearsOfWarModelInitializer.cs, test/EntityFramework.Core.FunctionalTests/TestModels/InheritanceRelationships/InheritanceRelationshipsModelInitializer.cs, test/EntityFramework.Core.FunctionalTests/TestModels/NullSemanticsModel/NullSemanticsModelInitializer.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EntityFramework.Sqlite.FunctionalTests/NullSemanticsQuerySqliteFixture.cs
resolves #2450 
Removed all `context.Database.EnsureCreated/Deleted` from `Seed` method. All fixtures call Seed method after dropping/creating database.
=> Allow complex boolean expressions in projection

src/EntityFramework.Core/project.json, src/EntityFramework.Relational/project.json, src/EntityFramework.Sqlite/project.json
Add netcore50 TFM to libraries required to run SQLite provider on UWP.
TODO: support commands project on UWP.
Partial fix for #4320 
cc @bricelam
=> Re-add netcore50

src/EntityFramework.Core/EntityFrameworkServiceCollectionExtensions.cs, src/EntityFramework.Core/Infrastructure/IModelCacheKeyFactory.cs, src/EntityFramework.Core/Infrastructure/IModelCustomizer.cs, src/EntityFramework.Core/Infrastructure/ModelCacheKey.cs, src/EntityFramework.Core/Infrastructure/ModelCacheKeyFactory.cs, src/EntityFramework.Core/Infrastructure/ModelCustomizer.cs, src/EntityFramework.Core/Infrastructure/ModelSource.cs, src/EntityFramework.InMemory/Infrastructure/Internal/InMemoryModelSource.cs, src/EntityFramework.MicrosoftSqlServer/Infrastructure/Internal/SqlServerModelSource.cs, src/EntityFramework.Sqlite/Infrastructure/Internal/SqliteModelSource.cs, test/EntityFramework.Core.FunctionalTests/ModelSourceTest.cs, test/EntityFramework.Core.FunctionalTests/TestModelSource.cs, test/EntityFramework.Core.Tests/DbContextTest.cs, test/EntityFramework.Core.Tests/ModelSourceTest.cs, test/EntityFramework.InMemory.FunctionalTests/TestInMemoryModelSource.cs, test/EntityFramework.MicrosoftSqlServer.FunctionalTests/Utilities/TestSqlServerModelSource.cs, test/EntityFramework.Sqlite.FunctionalTests/TestSqliteModelSource.cs
Provides a possible implementation for a way to alter modelbuilder from outside dbcontext.
Resolves: #2992 and #2805
=> Adds and implements ModelCustomizer

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/InheritanceRelationshipsQueryFixtureBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/InheritanceRelationshipsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/InheritanceRelationshipsContext.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/InheritanceRelationshipsModelInitializer.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/NonEntityBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/PrincipalEntity.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/ReferencedEntity.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs
=> Use correct entityType for chained navigations

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/ConditionalRemovingExpressionVisitorFactory.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/ChangeTrackingInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
- Add missing virual
- Disable failing InMemory Tests
- Disable asserting SQL in tests where statements are generated in different order for different runtime
With this changes `build.cmd` finishes fully.
=> Fix build failures on core clr

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/FixupTest.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/Microsoft.EntityFrameworkCore.FunctionalTests.xproj, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.xproj, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Initial testing shows about 65% perf improvement for Add/AddRange.
The change is to handle the case where there is a dependent being tracked before a principal and the dependent has a reference to the principal, but the principal does not have a reference to the dependent. In this case when we later start tracking the principal and it potentially gets its PK value, we need to go back and propagate that value to the FK. But finding the dependent entity at that time requires an expensive scan, so instead we keep a dictionary to look at later.
=> Improve perf of initial fixup for Add

src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapper.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteFixture.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
See Issue #4399
The issue was that the update pipeline was always asking the type mapper for the type to use even if a type had been explicitly set for the property. Fixed this and added tests for inserting all mapped types as both single inserts and multiple inserts both with and without Identity columns.
=> Use type mapper correctly in SQL Server batch updates

src/Microsoft.EntityFrameworkCore.Relational/RelationalPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Metadata/Builders/SqlitePropertyBuilderExtensions.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerInternalMetadataBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Metadata/Builders/SqliteBuilderExtensionsTest.cs
resolves #4328 
If user has set ValueGenerated for property explicitly HasDefaultValueSql will not modify it.
=> HasDefaultValueSql should update ValueGeneratedOnAdd if not set explicitly

test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/project.json, test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/project.json
The issue: When we build our design functional tests we copy .expected files to bin & .testpublish folders. On the subsequent runs it copies files from those folders too. Hence recursively creating more and more folders inside bin & .testpublish. All this works fine till the path becomes too long at which point build-tests phase fails.
Fix: We are restricting our scope to ReverseEngineering folder where we have created files. Exclude syntax in project.json is not able to work correctly somehow. I am trying to create a standalone repro to file bug on dotnet cli.
=> Avoid recursively copied content

test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/Properties/AssemblyInfo.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/project.json, test/Microsoft.EntityFrameworkCore.Microbenchmarks/project.json
Because we now consume artifacts from the central CI build (rather than
cloning and building on the perf agent), we need to copy config files so
that they are part of the artifacts from the build.
Also removing redundant TestFramework attribute from EF6 tests.
=> [TINY] Fixes for benchmark CI

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
Resolves #4313 
If a relationship
- Has dependent to principal navigation of reference type
- Has principal to dependent navigation set as null
- Has matching property(-ies) on principal side
- Has no matching property(-ies) on dependent side
Then conventions will try to invert and make one-to-one relationship using the single navigation
Conventions will not match "Id" as a matching property since it is ambiguous.
If "Id" is PK for dependent entity then conventions will use PK property for FK as per existing rules
=> Allow conventions to create one-to-one relationship with single reference navigation

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/ConventionSet.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ConventionDispatcher.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/IPrincipalEndConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/KeyPropagatorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
resolves #4451 
Conditions
- One-to-One relationship (non-self-PK-referencing)
- No matching properties on either side
Either of following two
- Principal Key is set with source higher than convention, or
- Principal End & Uniqueness set with source higher than convention
Issue 1: For one-to-one relationship configured conventionally, we don't match compatible PK since principal end is ambiguous. If on such relationship, `HasPrincipalKey` is used then principal end is specified by user and we should try matching PK. But if the `HasPrincipalKey` calls the same principal key as the current one then conventions are not run.
Issue 2: Using `HasOne` API sets principal end explicitly. So we may use half-configured relationship to determine side and assign FK properties even though when …
=> Match compatible PK as FK properly

EntityFramework.sln, src/Microsoft.EntityFrameworkCore.Commands/Design/DatabaseOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/DbContextOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/StartupInvoker.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/OperationExecutor.cs, src/dotnet-ef/ConsoleCommandLogger.cs, src/dotnet-ef/DatabaseCommand.cs, src/dotnet-ef/DatabaseUpdateCommand.cs, src/dotnet-ef/DbContextCommand.cs, src/dotnet-ef/DbContextListCommand.cs, src/dotnet-ef/DbContextScaffoldCommand.cs, src/dotnet-ef/Extensions/CommandLineApplicationExtensions.cs, src/dotnet-ef/MigrationsAddCommand.cs, src/dotnet-ef/MigrationsCommand.cs, src/dotnet-ef/MigrationsListCommand.cs, src/dotnet-ef/MigrationsRemoveCommand.cs, src/dotnet-ef/MigrationsScriptCommand.cs, src/dotnet-ef/OperationsFactory.cs, src/dotnet-ef/Program.cs, src/dotnet-ef/Properties/AssemblyInfo.cs, src/dotnet-ef/Properties/InternalsVisibleTo.cs, src/dotnet-ef/dotnet-ef.xproj, src/dotnet-ef/project.json, test/Microsoft.EntityFrameworkCore.Commands.Tests/Design/Internal/StartupInvokerTest.cs, test/dotnet-ef.Tests/ApiConsistencyTest.cs, test/dotnet-ef.Tests/dotnet-ef.Tests.xproj, test/dotnet-ef.Tests/project.json
Part of #3925 
This commit puts a stake in the ground. I'm still getting assembly resolution errors locally that may or may not be related to CoreCLR/CLI issues. Most negative cases aren't handled very well. Etc. I'll continue to test and iterate on this, but I think it's at a good point to merge.
For reference, here's [ye olde DNX Program.cs](https://github.com/aspnet/EntityFramework/blob/16dc2107105930e4a8b3bea4ac0679269d22d888/src/EntityFramework.Commands/Commands/Program.cs).
=> Add (non-working) .NET Core CLI commands

test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkTestCaseRunner.cs
We used to rely of conditional compilation to report Full .NET vs DNX,
but as part of moving to .NET CLI this was removed in
a80fd5277892dd1e9eee5c451df0b494ee98a9ff. We also no longer recompile
for each test run (we use central artifacts from CI build) - so
conditional compilation doesn't work anyway. Changing to just report CLR
vs CoreCLR and we can always report additional details via build
configuration parameters if needed.
=> [SMALL] Fix framework reporting in benchmarks

src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryByteValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryCharValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryDecimalValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryDoubleValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryFloatValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryIntValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryLongValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryNumberValueGeneratorFactory.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporarySByteValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryShortValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryUIntValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryULongValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/Internal/TemporaryUShortValueGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ValueGeneration/TemporaryNumberValueGeneratorFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ValueGeneration/TemporaryNumberValueGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ValueGeneration/ValueGeneratorSelectorTest.cs
See Issue #4488
This requires different start values and increment/decrement behavior for different types due to size limitations.
=> Change numeric temp value generators to use values that are even less likely to be used as real keys

src/Microsoft.EntityFrameworkCore.Relational/project.json, src/Microsoft.EntityFrameworkCore/project.json, test/Microsoft.EntityFrameworkCore.FunctionalTests/project.json, test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/project.json, test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/project.json
...again.
Note, dotnet/cli#1012 didn't help us much here because `Remotion.Linq`, `System.Diagnostics.DiagnosticSource`, `xunit.abstractions`, `xunit.assert`, and `xunit.extensibility.core` fall outside of its rules.
@victorhurdugaci
=> Re-enable installation on net451

src/Microsoft.EntityFrameworkCore/Extensions/EntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceNavigationBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceNavigationBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
Make InternalRelationshipBuilder.DependentEntityType() and InternalRelationshipBuilder.PrincipalEntityType() not try to invert the relationship
Add InternalRelationshipBuilder.RelatedEntityTypes() that handles inversion, as well as lifting of dependent or principal ends
This avoids ambiguity between lifting and inverting relationships between types in the same hierarchy
Make ForeignKeyPropertyDiscoveryConvention match shadow properties that weren't added by convention
=> Handle lifting of relationships between entity types in the same hierarchy

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/ISelectExpressionFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpressionFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/ComplexNavigationsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/GearsOfWarQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/IncludeTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/ComplexNavigationsQuerySqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
resolves #3826 
Presently it is code change only. If approaches looks right then I will update SQL generated for tests and add more test to verify this scenario.
=> Generate Unique alias for table names

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
There are further tests being affected by #4458 breaking the build.
Converted Assert.Equal to Assert.Contains to verify SQL ignoring the ordering of statements
=> Fix build break

src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs
=> Failing test and fix for: Subquery.Where(Expression<Func<Entity, bool>>) throws exception

src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSqlGenerationHelper.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Corrects issue where generated SQL for `decimal` types did not always include digits following the decimal (invalid cast from boxed `int` to `decimal` and incorrect use of integer math on server-side computations).
CC: @bricelam @natemcmaster @anpete
=> Fix #4308 - InvalidCastException for decimal without significant digits

src/Microsoft.EntityFrameworkCore.Commands/Design/AssemblyLoader.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/DatabaseOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/DbContextOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/DesignTimeServicesBuilder.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/OperationExecutor.cs, src/Microsoft.EntityFrameworkCore.Commands/tools/EntityFramework.psm1, src/Microsoft.EntityFrameworkCore.Relational.Design/TableSelectionSet.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/DesignTimeProviderServicesAttribute.cs, src/dotnet-ef/DatabaseUpdateCommand.cs, src/dotnet-ef/DbContextListCommand.cs, src/dotnet-ef/DbContextScaffoldCommand.cs, src/dotnet-ef/MigrationsAddCommand.cs, src/dotnet-ef/MigrationsListCommand.cs, src/dotnet-ef/MigrationsRemoveCommand.cs, src/dotnet-ef/MigrationsScriptCommand.cs, src/dotnet-ef/OperationExecutor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Design.Tests/SqlServerTableSelectionSetExtensionsTests.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.Tests/SqliteTableSelectionSetExtensionsTests.cs
Resolves #3925
**Provider writers beware**, this splits `DesignTimeProviderServicesAttribute.FullyQualifiedTypeName` into `TypeName` and `AssemblyName`. (cc @rowanmiller)
This should also fix #3862
=> CLI Commands: Fix design-time assembly resolution

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
resolves #4682 
Issue: When we encountered multiple relationship candidates, we were falling out of the loop if find ambiguous candidate. Therefore rest of candidates were not being process to build relationships. The issue did not surfaced so far because such missing relationships are found by the relationship discovery convention running on the other side. Which fails for self-ref relationship.
=> :bug: Process all relationship candidates

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs, src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/SqliteModelValidatorTest.cs
Resolves #4251 
If the properties which are being added to single table has same name and different type mapping then throw exception.
=> Validate properties mapped to same column has same type mapping.

src/Microsoft.EntityFrameworkCore.InMemory/Storage/Internal/IInMemoryStore.cs, src/Microsoft.EntityFrameworkCore.InMemory/Storage/Internal/InMemoryDatabase.cs, src/Microsoft.EntityFrameworkCore.InMemory/Storage/Internal/InMemoryStore.cs, src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs, test/Microsoft.EntityFrameworkCore.Tests/EntityFrameworkServiceCollectionExtensionsTest.cs
This clears the way for a logger or logger provider to be set at the context level, either through the constructor or some other sugar mechanism. This may be needed for proposed changes in the way we use D.I. but even if it isn't it will be useful for logging sugar.
=> Tiny: Only resolve ILogger<> and ISensitiveDataLogger<> from scoped services

src/dotnet-ef/OperationExecutor.cs
This fixes some assembly/native library resolution errors.
Part of #3925
=> CLI Commands: Specify RIDs when building project context

makefile.shade
Extend test-compile target to publish .NET Core test apps for SQL Server testing
cc @divega will better enable testing .NET Core => Sql Azure. cref #2898
=> More x-plat testing

src/Microsoft.EntityFrameworkCore/Extensions/Internal/ExpressionExtensions.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, src/Microsoft.EntityFrameworkCore/Query/ResultOperators/Internal/IncludeExpressionNode.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/IncludeTestBase.cs
resolves #4058 
Exception messages will be like this for `Include` & `ThenInclude` both
````
System.ArgumentException : The expression 'o => new <>f__AnonymousType103`2(Customer = o.Customer, OrderDetails = o.OrderDetails)' is not a valid property expression. The expression should represent a property access: 't => t.MyProperty'.
````
=> Update exception message for invalid property expression in Include & ThenInclude

src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/AsyncQueryTestBase.cs
This ensures partial results are never returned, as was found to be the case in #4317.
Close #4317
cc @anpete
=> Add high-level cancellation token check to async queries

src/Microsoft.EntityFrameworkCore.Relational/RelationalDatabaseFacadeExtensions.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/Internal/ConcurrencyDetector.cs, src/Microsoft.EntityFrameworkCore/Internal/IConcurrencyDetector.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/LinqOperatorProvider.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.FunctionalTests/SqlExecutorTestBase.cs
1) Fixed race-condition in EnterCriticalSection.
2) Switched to Disposable pattern to streamline usage.
3) Use InvalidOperationException instead of NotSupportedException. see #4730
cc @mikary
=> Fixes/improvements to ConcurrencyDetector:

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs
Throw a better exception when a property of interface type was not discovered
Resolves #4484, #4627
=> Throw a better exception when a property was not discovered, but could be a primitive property

src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/ExpressionTransformingQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/ComplexNavigationsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Issue was that we were applying our standard navigation expansion logic to SelectMany queries (e.g. customers.SelectMany(c => c.Orders)
This resulted in queries like:
SELECT * FROM Orders as o
which is correct for the basic case, however gives invalid SQL for slightly complex scenarios, e.g. with filter:
customers.Where(c => c.CustomerPK == 1).SelectMany(c => c.Orders)
SELECT * FROM Orders as o
WHERE o.CustomerPK = 1
Fix is to always translate the navigations inside SelectMany into inner joins instead.
This will produce queries like:
SELECT * FROM Customers as c
JOIN Orders as o ON c.Id = o.CustomerFK
WHERE c.CustomerPK = 1
This will have to be modified when Many-Many relationships are introduces, as some of the navigations will have to be translated into CROSS JOINs
Also added template …
=> Fix to #3889 - Query: [Nav Prop Translation] SelectMany generates wrong SQL

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs
...when we would get null argument exception when trying to translate coalesce expression whose arguments were not translatable to sql (i.e. needed to be client eval-ed)
=> [TINY] Fixing small issue in SqlTranslatingExpressionVisitor 

src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/MigrationsScaffolder.cs, src/Microsoft.EntityFrameworkCore.Commands/Scaffolding/Internal/FileSystemFileService.cs
=> Explicitly set UTF8 encoding on migration files output

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
resolves #4715 
Convention used to discover relationships to derived type based on the navigation targeting to base type. Due to this if there is relationship with base type and base type relationships are not built yet then derived types will try to use the same pairs and the inverse navigation becomes null for one of them throwing exception.
Fixes:
- Discover relationship by convention to exact type match only.
- Add extra check if we cannot find relationship builder then return null.
Tests:
Issue surfaces in existing tests after changing model so it is already covered.
=> :bug: Conventions should only discover relationships targeting exact type

src/Microsoft.EntityFrameworkCore.Commands/tools/EntityFramework.psm1, src/dotnet-ef/DbContextListCommand.cs, src/dotnet-ef/Extensions/CommandLineApplicationExtensions.cs, src/dotnet-ef/MigrationsAddCommand.cs
The powershell commands invoke dotnet-ef when executing on an xproj. It will throw errors if dotnet-ef is not installed in the tools section of the targeted project.
Fixes #978 
cc @bricelam
=> Add PMC cmdlet support for xproj

test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/project.json
An item with the same key has already been added. Key: System.Threading
Unspecified exception.
=> Workaround for CLI issue where restore fails with

src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/AccessorExtensions.cs, src/Microsoft.EntityFrameworkCore/Internal/DatabaseProviderSelector.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests/EndToEndTest.cs, test/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests/ProviderSpecificServicesTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalConnectionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
The common case here is a context that does not have OnConfiguring and does not pass in a DbContextOptions to its constructor, or the DbContextOptions passed does has not had any providers configured on it.
It is also possible to get no EF services at all, but this now requires making a call to UseInternalServiceProvider with a service provider that does not have EF services in it.
Also fixes #4665.
@rowanmiller for exception message wording
=> Throw helpful exceptions when services or provider are not configured

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/ShaperCommandContext.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/IQuerySqlGenerator.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
May need to revisit the `CommandCacheKey` comparison after  #4575 is merged
@anpete
=> Fix #4605 - Do not cache commands with Contains on Enumerable parameter.

src/Microsoft.EntityFrameworkCore.Commands/Design/Internal/DesignTimeServicesBuilder.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/MigrationsScaffolder.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsAssembly.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalCompiledQueryCacheKeyGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContextFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerCompiledQueryCacheKeyGenerator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryCompilationContextFactory.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Metadata/Conventions/SqliteConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/ChangeTrackerFactory.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore/Internal/CurrentDbContext.cs, src/Microsoft.EntityFrameworkCore/Internal/DbContextServices.cs, src/Microsoft.EntityFrameworkCore/Internal/ICurrentDbContext.cs, src/Microsoft.EntityFrameworkCore/Internal/IDbContextServices.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/CompiledQueryCacheKeyGenerator.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompilationContextFactory.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs, test/Microsoft.EntityFrameworkCore.Commands.Tests/Migrations/Design/MigrationScaffolderTest.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/ThrowingMonsterStateManager.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsAssemblyTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/TestConventionalSetBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs, test/Microsoft.EntityFrameworkCore.Tests/EntityFrameworkServiceCollectionExtensionsTest.cs
Because when people use the same service provider for both the application and our internal services and don't create a derived DbContext class, then the two registrations can often collide. See #4750.
The fix is to use the type ICurrentDbContext internally which wraps the context for the current scope.
=> Stop registering DbContext as an internal service

src/Microsoft.EntityFrameworkCore/Internal/DbContextServices.cs, src/Microsoft.EntityFrameworkCore/Internal/InterceptingLogger.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
We intercept ILogger creation to ensure EF uses the correct logger when the UseLoggerProvider method has been used. However, this meant that when sharing a service provider we would sometimes fail to provider a logger if the context had not yet been initialized. This change fixes that by falling back to regular service provider resolution.
=> Allow ILoggers to be resolved before context has been created

src/Microsoft.EntityFrameworkCore.Commands/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Commands/Design/OperationExecutor.cs, src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/MigrationsScaffolder.cs, src/Microsoft.EntityFrameworkCore.Commands/Properties/CommandsStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Commands/Properties/CommandsStrings.resx, src/Microsoft.EntityFrameworkCore.Commands/tools/EntityFramework.psm1, src/dotnet-ef/MigrationsRemoveCommand.cs, src/dotnet-ef/OperationExecutor.cs
cc @bricelam 
Fix https://github.com/aspnet/EntityFramework/issues/4812.
Allows user to force remove the last migration, skipping over database check.
=> Remove-Migration -Force

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs
=> [TINY] Reorder parameters in exceptions thrown from PropertyMappingValidationConvention

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ShadowFkFixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
This means that graph Attach calls behave as expected no matter which entity is attached first or which mechanism is used, and work correctly with shadow FKs.
It also means that re-parenting an attached dependent cannot be done by setting a new principal to point to it, and then attaching that principal. But attaching the principal and then setting the navigation property will work.
/cc @divega @rowanmiller
=> Make Attach never have side effect of setting dependent entities as Modified

src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalLoggerExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalDiagnosticSourceAfterMessage.cs, src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalDiagnosticSourceBeforeMessage.cs, src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalDiagnostics.cs, src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj, src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalCommand.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalCommandTest.cs
This brings DiagnosticSource usage inline with what we have been doing elsewhere. 
- **Timing**: usage has been converted from using a new instance of `StopWatch` to using `Stopwatch.GetTimestamp()`. This has been well [documented](https://github.com/aspnet/Hosting/pull/543) to have better performance than other alternatives. 
- **TimeStamp**: `timestamp` has ben added to the begin/end payloads so that all consumers of logging and DiagnosticSource will be showing the same times when using EF based events
- **Correlation**: `InstanceId` has ben added to the payload so that consumers can correlate begin and end messages together in a deterministic way without haven't to maintain state across events
- Note: Strictly speaking other areas where we are using this, the Id is "global" to the …
=> Adds Timestamps, InstanceId and Duration to Diagnostic Source events

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
resolves #4094
The issue: When we added complex projection to the Sql, we removed the scalar projections from it. They get re-added while binding but this changes the order in which projections appear. In the case of #4094, we had to do filter on client eval, due to re-ordering the filter condition still used old index which was wrong. Based on the type of the projection at that index, it threw InvalidCastException or gave incorrect results.
Fix:When we visit the SelectClause we record the present projection count. These projections are already present and required by WhereClause. Then we visit the Selector and if we lift the query we remove additional projections added while visiting the selector using previously recorded count.
=> Avoid re-ordering of projections in case of complex projections

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalShadowEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateData.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ChangeTrackerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/StateDataTest.cs
Shadow properties get this state when entities are first attached. These properties are then not considered modified even if the entire entity is marked as modified and so the values for these properties are not saved. The properties are only considered as modified or not when an actual value is set.
See #4474
=> Introduce an Unknown state for property values

src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/CSharpSnapshotGenerator.cs, src/Microsoft.EntityFrameworkCore.Commands/Scaffolding/Internal/Configuration/ModelConfiguration.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/IRelationalPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalFullAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/Microsoft.EntityFrameworkCore.Relational/RelationalPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/SqlServerScaffoldingModelFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Internal/SqlServerPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Metadata/Builders/SqlitePropertyBuilderExtensions.cs, test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/RelationalScaffoldingModelFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/SqliteScaffoldingModelFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Metadata/Builders/SqliteBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Metadata/SqliteMetadataExtensionsTest.cs
Because not all provider support both concepts we were storing these things as a single string and then letting other metadata determine how to use the value. However, for cases like that in issue #4501 Migrations assumes a computed column because it doesn't know that the value specified is actually a default and not computed expression. The fix is to stop combining the metadata.
=> Split storage of default value SQL and computed value SQL

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/Extensions/EntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/ModelExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutableModelExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ICanFindEntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalModelBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Model.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, test/Microsoft.EntityFrameworkCore.FunctionalTests/InheritanceRelationshipsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/DerivedCollectionOnBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/InheritanceRelationships/InheritanceRelationshipsModelInitializer.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #4817
The problem was that query was passing in the base type to the state manager since the actual type varies by row. It would likely be possible to flow the actual type through from the materializer but this would require significant changes and would not be used in a lot of cases. Instead the state manager now looks up the entity type if it is not the base type, with some optimizations to that lookup made in metadata.
=> Ensure entities from query are tracked as correct type

test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkTestCaseBase.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkTestCaseRunner.cs, test/Microsoft.EntityFrameworkCore.Relational.Design.FunctionalTests/TestUtilities/BuildReference.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
Use ifdefs to prevent R# from removing unused stuff on code cleanup
=> Refix fixes to build break so they won't break again

test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerConnectionTest.cs
Since it seems SQLClient on Linux is now verifying these
Issue #4915
=> Remove Integrated Security/Trusted_Connection from dummy strings

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/ShaperCommandContext.cs, src/Microsoft.EntityFrameworkCore/Internal/NonCapturingLazyInitializer.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Key.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Navigation.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
See issue #4789
This requires a new initializer class since the BCL LazyInitializer doesn't support passing parameters to the creation delegate.
=> Use non-capturing lambdas for lazy initialization

src/Microsoft.EntityFrameworkCore/EF.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/TestModels/Northwind/NorthwindData.cs
Implementing the solution proposed in #4975. Also includes minor change to `ParameterExtractingExpressionVisitor` because the attribute was not being checked due to a performance optimization.
@anpete @maumar
=> Fix #4975 - EF.Property<T> property name shoud not be parameterized

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/RelationshipsSnapshot.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrICollectionAccessor.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/IClrCollectionAccessor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryBuffer.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs
Issue #4853
The issue here is when the second TestClass was loaded the relationship snapshot on the inverse was not updated, which in turn caused DetectChanges to misbehave. Rather than attempt to do any kind of diff at the end of query the fix is to update the relationship snapshot at the same time that query is setting or populating the actual navigation property.
=> Ensure relationship snapshot is kept up-to-date when query loads navigations

src/Microsoft.EntityFrameworkCore/Query/Internal/ExpressionEqualityComparer.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs
Adds hash code generation for expression type that was not covered by the existing implementation.
@anpete @divega
=> Fix #4998 - NotImplementedException thrown on Where TypeIs cache key generation

src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/DbContextOptions.cs, src/Microsoft.EntityFrameworkCore/DbContextOptions`.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Probably root cause of issue #4994.
If there are multiple context types registered in D.I. and each depends on non-generic DbContextOptions, then only one of them will get the correct instance. This fix checks that a context is getting its correct options and throws if not with the guidance to use generic DbContextOptions parameters in the context constructors.
=> Throw when using multiple context types with non-generic DbContextOptions

src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/InheritanceInMemoryTest.cs
Linq adds an extra Convert to object for boxing when EF.Property<T> is called in a method without generic constraints on the entity type.
Adding a step to query compilation to update the Expression before the QueryModel is generated but after caching.
cc @anpete @maumar
=> Fix #4875 - EF.Property<T> throws in certain generic usages

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
Bug is now fixed and pushed to releases/service packs. See #266.
=> Re-enabling test that was disabled due to SQL Server bug

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs
See #3625. Passing in null or the empty string indicates that all properties are changing/changed. We now honor this, except for properties marked as read-only. We ignore these since we don't track original values for full notification entities and hence have no way of knowing if they are really changed or not, and we cannot mark them as modified. So we assume that since they are read only they have not been changed.
=> Handle null/empty in property name in notification events

src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx
Emphasizes that generic DbContextOptions should be used.
See #5076
=> Update exception message seen for parameterless context constructor

TestAssets/TestProjects/PortableAppWithTools/TestContext.cs, TestAssets/TestProjects/PortableAppWithTools/project.json.ignore, src/dotnet-ef/project.json
This is to unblock other teams.
Temporary workaround for https://github.com/dotnet/cli/issues/2514. 
We may need to change dotnet-ef's execution strategy to permanently fix version issues with using `AssemblyLoadContext` from a tool. Until that lands, we can fix most issues by just pulling higher version of Newtonsoft.Json.
=> Temporary workaround for Newtonsoft.Json issues with AssemblyLoadContext

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/CompositePredicateExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/PredicateReductionExpressionOptimizer.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
OData adds null guards in form of:
expression -> a == null ? (expression_type?)null : (expression_type?)(expression)
nullable_boolean_expression -> nullable_boolean_expression == (bool?)true
The first one we optimize in SqlTranslatingExpressionVisitor as it's not necessary for relational queries, the second one is redundant in general so we remove it for all queries.
=> fix to 5060 - Query :: nullability-related errors during query compilation for some queries generated with OData

test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/BenchmarkConfig.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/Models/AdventureWorks/TestHelpers/AdventureWorksDatabaseRequiredAttribute.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/Models/AdventureWorks/TestHelpers/AdventureWorksFixtureBase.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.Core/SqlServerRequiredAttribute.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/Models/Orders/OrdersFixture.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/config.json, test/Microsoft.EntityFrameworkCore.Microbenchmarks/Models/Orders/OrdersFixture.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks/Query/Profile.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks/config.json
We used to just allow configuring the database instance name, and
assumed integrated security etc. Updating to allow the full connection
string to be specified, then we just append the database. This is
required because we are moving the benchmark CI to use a separate
database server.
=> Improve configurability of benchmark database 

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Issue is Order By requires value type for ordering. Having condition in order by expression is incorrect sql.
Fix is convert comparison or logical expressions in case blocks when they appear in order by expression
Fixes #5095
=> Query: Convert order by condition to case blocks

src/Microsoft.EntityFrameworkCore.Relational/Update/ColumnModification.cs, src/Microsoft.EntityFrameworkCore.Relational/Update/ModificationCommand.cs, src/Microsoft.EntityFrameworkCore.Relational/Update/ReaderModificationCommandBatch.cs, src/Microsoft.EntityFrameworkCore.Relational/Update/UpdateSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/OriginalValues.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyAccessorsFactory.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/ColumnModificationTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ChangeTrackerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalShadowEntityEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/PropertyEntryTest.cs, tools/Resources.tt
Issue #4375.
For entities that implement INotifyPropertyChanging, the original value is not needed by changing tracking and hence we do not store it or allocate space to store it. Previously if you asked for the original value in such cases we would give you back the current value. We now throw saying that the value is not available and directing you to the flag that will make it available. It's a pretty blunt flag right now, but we can make it more fine-grained if enough people want this behavior.
In fixing this, it turns out that the update pipeline was using the original value for primary key where clauses. This started to throw because the original value was not available. This has been changed to use the current value instead. This was complicated because the logic for choosing …
=> Throw when attempting to access original value when it is not being tracked.

src/Microsoft.EntityFrameworkCore.Commands/Migrations/Design/CSharpSnapshotGenerator.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Navigation.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Commands.FunctionalTests/Migrations/ModelSnapshotTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericStringTest.cs
=> Metadata: Allow creating shadow navigation on shadow entity types

src/Microsoft.EntityFrameworkCore.Relational/Query/AsyncQueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs
Replaced most commonly used IX-Async operators with async methods (await), which are more efficient.
In one async query microbenchmark we see allocations go from 1,893,939,770 bytes/34,771,015 objects to 312,770,445 bytes/5,421,289 objects.
=> Query: Async: Reduce allocations during async query.

src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/DbContextOptions.cs, src/Microsoft.EntityFrameworkCore/DbContextOptions`.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Add #5017 to RC2. 
Fixes https://github.com/aspnet/EntityFramework/issues/4994
cc @ajcvickers @divega
=> [rc2] Throw when using multiple context types with non-generic DbContextOptions

src/Microsoft.EntityFrameworkCore.Tools.Core/Design/DbContextOperations.cs, src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Fix https://github.com/aspnet/EntityFramework/issues/5156
~~This brings https://github.com/aspnet/EntityFramework/pull/5017 into release branch~~ 
cc @divega @ajcvickers
=> Switch AddDbContext to use .Add instead of .TryAdd when adding DbContextOptions

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/CompositePrincipalKeyValueFactory.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #4854
Switch to using Equals(x, y) instead of x.Equals(y).
=> Fix for NullRef when adding graph with shadow keys

src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/AsyncQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/AsyncQuerySqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
fixes #5035 
Funcletize method calls in query.
`Guid.NextGuid()` & `Random().Next()` are not funcletized
=> Query: Funcletize method calls

src/Microsoft.EntityFrameworkCore.Specification.Tests/StoreGeneratedTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StoreGeneratedValues.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
Issue #448
Store-generated values are discarded, but the identity maps from key value to entry were not being updated. The fix is to send a changed notification for any property that had been assigned a store generated value.
=> Update identity map after SaveChanges fails

test/Microsoft.EntityFrameworkCore.Microbenchmarks.EF6/ChangeTracker/FixupTests.cs, test/Microsoft.EntityFrameworkCore.Microbenchmarks/ChangeTracker/FixupTests.cs
We recently updated the other fixup tests to work on 5,000 customers &
10,000 orders. Upping the tests that fixup with a query to work on the
same entity counts.
=> [TINY] Increase work in fixup query tests

src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrAccessorFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrPropertyGetterFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrPropertySetterFactory.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs
Some changes were added in 3b693c7ee789f117c3e1a7f5f2cde8aeb298393c and c35ce4d3632331d14ff8a3ab8ac59c54a660a535 for .NET Native that are no longer necessary.
Fix #3477
=> Cleanup .NET Native workarounds

src/Microsoft.EntityFrameworkCore.Tools.Core/Design/Internal/StartupInvoker.cs
Fixes #5236
This array is used in a loop that stops on the first method it finds.  It should try the more specific methods before the less specific methods.
=> Switches the order of Configure*Services methods.

src/Microsoft.EntityFrameworkCore.Tools.Cli/ExecuteCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Migrations/Design/MigrationsScaffolder.cs, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFramework.psm1, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/DotNetEfFixture.cs, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/EndToEndTests.cs, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/AspNetHostingPortableApp/project.json.ignore, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/DesktopAppWithTools/project.json.ignore, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/LibraryUsingSqlite/project.json.ignore, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/PortableAppWithTools/project.json.ignore, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/TestProjects/StandaloneAppWithTools/project.json.ignore, test/Microsoft.EntityFrameworkCore.Tools.Cli.FunctionalTests/clean-assets.cmd
This PR is a collection of 3 minor tweaks for CLI commands and testing.
Fix #5187 - use `--output-dir` when specified for the directory where migrations are written to
Fix #5260 - improve compatibility of PMC cmdlets with dotnet-ef
Fix #5227 - one line change so "dotnet ef" is used in help text, not "Microsoft.EfCore.Tools.Cli"
cc @divega
=> [rc2] Fix minor issues in commands

src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
In #5209 I changed the namespaces of a lot of files to add `.Internal`. But I missed the couple of references (by reflection) in the `DesignTimeProviderServices` attributes.
=> [TINY] Correct references to an Internal namespace

src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/IsNullOrEmptyTranslator.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/RelationalCompositeMethodCallTranslator.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerCompositeMethodCallTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringIsNullOrWhiteSpaceTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimEndTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimStartTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Microsoft.EntityFrameworkCore.Sqlite.csproj, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteCompositeMethodCallTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteStringIsNullOrWhiteSpaceTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteStringTrimEndTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteStringTrimStartTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteStringTrimTranslator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
Resolves #5199 
@anpete @divega - Are there anymore translators which we should have?
Currently we have following translators for string
Contains, EndsWith, Equals, StartsWith, Compare, Concat (in relational)
Length, Replace, Substring, ToLower, ToUpper (in sql server)
Adding IsNullOrEmpty in this PR.
=> Query: Add translators for string functions

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IInternalEntityEntrySubscriber.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntrySubscriber.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntryEntrySubscriberTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #1378
This change ensures that entities are unsubscribed from notification events when they stop being tracked or the context is disposed.
=> Unsubscribe from notification events

src/Microsoft.EntityFrameworkCore.Tools.Cli/ExecuteCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsAddCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/OperationExecutor.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json, src/Microsoft.EntityFrameworkCore.Tools.Core/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Migrations/Design/MigrationsScaffolder.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Properties/ToolsCoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Properties/ToolsCoreStrings.resx, src/Microsoft.EntityFrameworkCore.Tools/Design/OperationExecutor.cs, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFramework.psm1, test/Microsoft.EntityFrameworkCore.Tools.FunctionalTests/Design/OperationExecutorTest.cs
Fixup migrations -outputdir to better handle subnamespace computation normalizing path, and error handling. 
Fix #5274
Fix #5277 
Fix https://github.com/aspnet/EntityFramework/issues/5271
=> Add-Migrations: better handling of outputDir

src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerCompositeMemberTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateTimeDateComponentTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateTimeDatePartComponentTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Expressions/Internal/DatePartExpression.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Sql/ISqlServerExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
This PR adds sql server translation support for the following DateTime properties in LINQ (See also: https://github.com/aspnet/EntityFramework/issues/4582):
- DateTime.Date
- DateTime.Year
- DateTime.Month
- DateTime.Day
- DateTime.DayOfYear
- DateTime.Day
- DateTime.Hour
- DateTime.Minute
- DateTime.Second
- DateTime.Millisecond
This is SQL server only atm, but I would also be willing to add support for sqlite. 
However, I thought I would gather some feedback on this part first.
Looking forward to your feedback :)
=> SQL Server datepart translation support (fixes #4582)

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalParameterBuilder.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalTypeMapper.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/ISqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalParameterBuilder.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalCommandBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapper.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapperExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalCommandBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/TestRelationalTypeMapper.cs
In looking at #4425 and #4134 in became quickly apparent that the support for inferring Unicode was too specific to Unicode. What is really needed is that if the type mapping to be used can be inferred in some way, then this type mapping should be used for all relevant facets, not just Unicode. Only in cases where no inference is possible should the default mapping for the CLR type be used.
=> Generalize type mapping support for Unicode

test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
Issue #3376
Added tests for both the customer model (1:*) and the model Smit added (1:1). Both work with the current bits.
=> Regression tests for overlapping FK/PK

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was that navigation expansion logic was only applied for MemberExpressions, but never for MethodCallExpression. Fix is to abstract that logic to work for both MemberExpressions and MethodCallExpression that happen to be EF.Property.
Also did some minor bugfixes and optimizations found along the way:
- compensating for nullability differences in SqlTranslatingExpressionVisitor, when processing comparison,
- preventing EntityEqualityRewritingVisitor to short-circuit on non-equality operations in case of nested binary expressions.
=> Fix to #5043 - Query: Navigations: Using EF.Property with reference nav omits null compensation

src/Microsoft.EntityFrameworkCore.Tools.Cli/DbContextScaffoldCommand.cs
Fix for #5267. Example had the old provider package name. Updated to the new one.
=> [TINY] Correcting bad example provider name.

src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Extensions/MethodInfoExtensions.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs
Problem was that for include we were using relinq's EntityAccessorFindingVisitor, to extract a accessor lambda to a given query source in the selector (for InMemory scenario). Problem was that EntityAccessorFindingVisitor was not meant to work for some cases that we were using it (e.g. Coalesce, Conditional).
Fix is to refactor InMemory include mechanisms so that we no longer need the accessor lambda. Now Include method is applied either around appropriate elements of the outer-most selector, or in case no Select method has been generated - around EntityQuery/OfType directly.
=> Fix to #3101 - .Include() with Self-Join / Coalesce

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs
To allow provider-specific model validators to access them.
=> Make RelationalModelValidator's fields protected

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
=> Add tests for #3804 - Select Navigation following Skip or Take

src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs
=> Look at all derived types when creating a column during migration.

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
Problem was that we were not applying navigation expansion to some queries (when the navigation was based of a subquery, rather than query source reference), e.g.
ctx.Customers.Select(c => ctx.Orders.FirstOrDefault().Customer)
This would cause incorrect results - Customer navigation would always be null.
Fix is to push those navigations before the FirstOrDefault call, like so:
ctx.Customers.Select(c => ctx.Orders.Select(o => o.Customer).FirstOrDefault())
=> Fix to #5191 - Query :: invalid results returned for queries with complex projection involving FirstOrDefault and navigation property

src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/IncludeSqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/Utilities/SqliteVersionConditionAttribute.cs
Disable IncludeSqliteTest which fails for Sqlite version below 3.8.8
Skips failing test in SQLite on Linux.
=> Test: Add SqliteVersionConditionAttribute

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFramework.psm1
Fix #5383.
Possibly also fixes https://github.com/aspnet/EntityFramework/issues/5293
> The Item method throws a ArgumentException exception if the specified value cannot be found in the collection.
https://msdn.microsoft.com/en-us/library/envdte.properties.item(v=vs.120).aspx
e.g. UWP class libraries don't define "ProjectN.UseDotNetNativeToolchain" at all but UWP app projects do.
cc @bricelam
=> PS commands: add catch around GetProperty for non-existent properties

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/IRelationalPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalAnnotationsBuilder.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalFullAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx, src/Microsoft.EntityFrameworkCore.Relational/RelationalMetadataExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/RelationalPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerScaffoldingModelFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Internal/SqlServerPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Migrations/Design/CSharpSnapshotGenerator.cs, src/Microsoft.EntityFrameworkCore.Tools.Core/Scaffolding/Configuration/Internal/ModelConfiguration.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalMetadataBuilder.cs, test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/RelationalScaffoldingModelFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/ModelSnapshotTest.cs
Detect conflicting DefaultValue, DefaultValueSql, ComputedColumnSql and SqlServerValueGenerationStrategy
Rename ComputedValueSql extension method to ComputedColumnSql to be consistent with fluent API
Fixes #5384
=> Add some guards to relational property metadata builders

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psd1, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1, src/Microsoft.EntityFrameworkCore.Tools/tools/about_EntityFramework.help.txt, src/Microsoft.EntityFrameworkCore.Tools/tools/init.ps1, src/Microsoft.EntityFrameworkCore.Tools/tools/install.ps1
Fix #5145
Related: documenation update https://github.com/aspnet/EntityFramework.Docs/pull/170
~~Btw, we still have "Apply-Migrations" and "Enable-Migrations" in this module. Can we remove these now? Or do we still want them there to throw "obsolete" errors?~~ nevermind. Just realized Brice opened an issue a few hours before me to track this exact question.
cc @rowanmiller @bricelam @divega
=> Rename PowerShell cmdlets module to EntityFrameworkCore

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs
when there is no ORDER BY Clause or ORDER BY is on principal key properties
resolves #4903
=> Use WHERE EXISTS instead of INNER JOIN for collection navigation Include

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
There are several issues around the area:
- in some cases we were forcing client evaluation too aggressively when trying to translate SubQueryExpression. Fix is to relax those criteria, so that more queries that we can translate to SQL will actually be translated.
- in other cases we were not translating expressions that could have been translated because we were not looking into queries processed by parent EntityQueryExpressionVisitor during binding,
- in general, if we were unable to translate the item expression of the contains, we were not applying client-side result operator, which would produce incorrect results when client evaluation was really needed,
- we were handling Contains in two places separately: RelationalResultOperatorHandler and SqlTranslatingExpressionVisitor -> …
=> Fix to 4355 - Contains on Sub query with entity type generates invalid SQL

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TestSqlLoggerFactory.cs
Marked the `SqlLoggerData` with the `SerializableAttribute` but I have not seen the CI failures reproduce locally.
@natemcmaster
=> Fix #5184 - Make SqlLoggerData Serializable to identify underlying test errors

src/Microsoft.EntityFrameworkCore.Tools/DispatchCommand.cs, src/Microsoft.EntityFrameworkCore.Tools/Properties/ToolsStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Tools/Properties/ToolsStrings.resx, src/Microsoft.EntityFrameworkCore.Tools/project.json, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.PowerShell2.psd1, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.PowerShell2.psm1, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1, src/Microsoft.EntityFrameworkCore.Tools/tools/about_EntityFrameworkCore.help.txt, src/Microsoft.EntityFrameworkCore.Tools/tools/init.ps1, src/Microsoft.EntityFrameworkCore.Tools/tools/install.ps1
Fix #5418 - net451 commands on Linux are not supported
Fix #5272 - add fwlink when PMC command fails on .NET Core projects
Fix #5292 - write error when installing tools on PowerShell 2.0
cc @bricelam @rowanmiller
=> Add more contextual error messages to EF commands

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TestSqlLoggerFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapper.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerMaxLengthMapping.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
Issues:
#4608 Use column/property facets for parameter types in Query Pipeline
#4134 Use column/property facets for parameter types in Update Pipeline
If a property length is specified, then this is used to infer the length to use for parameters relating to that property, unless the length of the data is too long, in which case unbounded length is used. Because query has code that can infer the length to use for a parameter this still means that fragmentation will not happen without always using the 4000/8000 value.
=> Use length facet for parameter size

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs
Issue #5397
The problem was that before attaching the new entity we were not recording that it had a navigation pointing to it, so then in initial fixup this was not being used to populate the FK.
=> Fix detecting reference to untracked entity

src/Microsoft.EntityFrameworkCore/Metadata/Builders/CollectionNavigationBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceNavigationBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ManyToOneTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
Throw when configuring a bidirectional relationship that conflicts with a previously configured biderectional relationship on one of the navigations.
Fixes #5344
=> Throw on multiple relationships using one navigation instead of letting the last one win

src/Microsoft.EntityFrameworkCore.Tools.Cli/ConsoleCommandLogger.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/DatabaseDropCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/DatabaseUpdateCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/DbContextCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/DbContextListCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/DbContextScaffoldCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/ExecuteCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/Extensions/AnsiColorExtensions.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/Extensions/CommandLineApplicationExtensions.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsAddCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsListCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsRemoveCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsScriptCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/Program.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/project.json, src/Microsoft.EntityFrameworkCore.Tools/DispatchCommand.cs, src/Microsoft.EntityFrameworkCore.Tools/Microsoft.EntityFrameworkCore.Tools.csproj, src/Microsoft.EntityFrameworkCore.Tools/project.json, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1
Replace use of their console reporter with our own
Copy over a few of the command line helpers
Remove use of stderr for normal execution output from dotnet-ef
Fix #5012 
Incidentally fixes #5483 by removing dependency on Microsoft.Extensions.PlatformAbstractions
cc @bricelam
=> Remove dependency on Microsoft.DotNet.Cli.Utils

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/KeyPropagator.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #4831
The problem was in the code that propagates FK values from principal values when adding dependents. It was doing expensive scanning with a TODO: Perf comment. :-) The fix is to reuse the look-aside indexes already created for fixup. For large graphs the perf is now orders of magnitude faster.
=> Perf improvement for adding graphs

src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs
This reverts commit 242d53cfc49dd40932ff3b5cdc0639893d729ad6.
Adding in the missing "Microsoft." that caused the build to break. Not really sure why this only started failing recently since the code has been like this for a while.
=> [TINY] Revert "Fixing build break"

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.PowerShell2.psm1, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1, src/Microsoft.EntityFrameworkCore.Tools/tools/init.ps1
cc @rowanmiller @bricelam 
When executing any command that also exist in EF6 powershell commands AND the EF6 commands are installed, users will see a warning.
Fix #5145
=> Issue warning when EF6 commands are also installed in solution

test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/Migrations/SqliteMigrationSqlGeneratorTest.cs
Issues:
1. Missing Table property values in `AddColumnOperation`
2. No `StringTypeMapper` in test code.
3. Use property to get type when property is not null and maxlength is absent or same as max length annotation.
=> Fix build break introduced PR #5555

src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
While setting basetype by convention, if derived type has objects defined using DataAnnotation as ConfigurationSource then it blocks setting base type. Even though it is coming from same property. Therefore while removing object use Max(CS.DataAnnotation, configurationSource) so that objects added with DataAnnotation can be removed and added back. And base type won't be set if there are objects which are set using Explicit configuration source.
Fixes #5547
=> Allow removing metadata objects defined using DataAnnotation while setting base type by convention

src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ManyToOneTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
Fix #5406 
Set principal end correctly for explicit
For relationships which has collection navigation, don't check for matching property on principal side.
=> One-to-many relationships are not ambiguous

src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ManyToOneTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
Fixes issue #5573 
Run conventions on removed FKs after Key is removed fully
=> Metadata: RemoveKey should run all conventions after key is removed

src/Microsoft.EntityFrameworkCore.Tools.Cli/ConsoleCommandLogger.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/DbContextListCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/Extensions/CommandLineApplicationExtensions.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsAddCommand.cs, src/Microsoft.EntityFrameworkCore.Tools.Cli/MigrationsListCommand.cs, src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1
After further review, it appears anyone scripting dotnet-ef with json output always needs to parse out other stdout output anyways. When we trigger a dotnet-build or when we add a migration, there is now other output on stdout. We might as well always log "//BEGIN" and "//END" for json output.
cc @bricelam
=> CLI commands: always wrap JSON output with begin/end markers

src/Microsoft.EntityFrameworkCore.Specification.Tests/F1FixtureBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/OptimisticConcurrencyTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/ConcurrencyModel/Chassis.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/ConcurrencyModel/Driver.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/ConcurrencyModel/Sponsor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/ConcurrencyModel/Team.cs
This allows other providers to use different concurrency tokens in the model
=> Change optimistic concurrency tests to use a shadow property

src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
This decouples statement termination from `SqlCommand` creation, and enables us to implement #3928 later.
=> Migrations: Make MigrationsSqlGenerator.EndStatement batching-friendly

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/NullSemanticsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs
Problem was that during null semantics rewrite we were only looking at constant and column expressions, never taking parameter expressions into account. Those can be optimized out in some cases as we know the value of the parameter during sql generation. Added another pass of PredicateReductionExpressionOptimizer after null semantics is applied to get rid of redundant true/false constants that may now be produced.
=> [SMALL] Fix to #5499 - Local variable null check incorrectly translates to SQL

src/Microsoft.EntityFrameworkCore/Internal/InterceptingLogger.cs
Cache logger name for the type to avoid calling DisplayName each time a logger instance is created.
Issue #5059
=> Reduce allocations in construction of InterceptingLogger

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1
cc @lajones @bricelam 
This also fixes out we treat verbose output and stderr.
Escapes all parameters passed to dotnet-ef with single quotes.
=> Fix #5376 - escape parameters passed to dotnet-ef from PMC

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs
Issue #5623
The index created to go alongside the relationship was not getting its uniqueness from the relationship, and hence the database created by Migrations did not have a unique index for the FK column. The fix is to propagate uniqueness from the relationship metadata to the index.
=> Enforce uniqueness of foreign keys in the database

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Fixes #5571
Problem was in the way that we were doing PushDownSubquery during complex includes. We were incorrectly overriding aliases of the projection elements from the outer query in some cases. Basically, we were looking at the aliased column name to determine whether it needs to be aliased again. Instead we should look at the alias first, and only if that is not set or it would be a duplicate, we should re-alias the column.
=> Fix to #5571 - RC2 Upgrade Eager Loading throw an exception

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/AsyncFromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/QueryingEnumerable.cs
Resolves #5628 
Close the connection only if it was opened by `QueryingEnumerable`
=> Close connection only if opened by QueryingEnumerables

src/Microsoft.EntityFrameworkCore.Relational/RelationalQueryableExtensions.cs, src/Shared/CodeAnnotations.cs
Add R# StringFormatMethod to FromSql
Will help users avoid parameter referencing and formatting issues in SQL queries passed to FromSql.
A good example is a user having curly braces somewhere in the SQL query, that will make `string.Format` bomb internally.
=> Add R# StringFormatMethod to FromSql

src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Fixes #4739 and #5641
Thanks to @sepplK for pointing out where the bug is.
Problem was that during query rewrite for RowNumberPaging, when copying projection elements from the inner query, we were not preserving aliases. Instead were using ColumnExpression (so it would be the projected element in the outer query) even in the alias was explicitly set in the inner SelectExpression. Fix is to try use alias first and only if alias is not set fall-back to using the column name.
=> Fix to #4739 - UseRowNumberPaging causes NRE in complex queries

test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
=> Update conditional skip to exclude sequence test only on Linux/OSX

src/Microsoft.EntityFrameworkCore.Tools/tools/EntityFrameworkCore.psm1
Helps future-proof PMC commands against rename of *.xproj -> *.csproj
cc @bricelam
=> Add fallback check to determine if projects are .NET Core

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/StateManagerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Microsoft.EntityFrameworkCore.Tests.csproj
Issue #5674
The state manager was assuming the query would take care of fixup for all single queries. However, this is only true when the relationships are explicitly included in the query. For some cases such as self references and multiple relationships between entity types, fixup is needed that will not be performed by query. Therefore we will now drop out of single query mode for any query with self refs and any time multiple entities are returned. This will have a perf impact, but super simple queries will still run in single query mode. Post RTM we will try to do something better.
=> Do state manager fixup for for more single queries

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
resolves #5652 
Issue: In Sql bool values and conditions are different concept and implicit conversion is not done. Therefore we need to append `= 1` to where predicate for certain expression. So far we had a list of expression which needed it. `Coalesce` was not part of the list hence incorrect SQL generated.
Solution: Instead of adding another special case for `Coalesce` here we generalized kind of expression which are valid to be used as search condition and generated `= 1` for all the rest. The CFG was taken from T-SQL which covers all cases. (supposedly)
@anpete @maumar @divega
=> Query: Convert boolean value to search condition in sql predicates

src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
Issue #5715
SQL Server was mapping "datetime" to DbType.DataTime2 parameters. This breaks SQL Server 2005 and also the always encrypted feature of later versions where the automatic conversions from datetime2 don't work.
=> Correctly map SQL Server datetime columns

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ShadowFkFixupTest.cs
Issue #5734
When we encounter an untracked entity in a navigation we save it for later fixup, but we were not adding these entities to the snapshot for the navigation. This later caused change detection to be confused, which resulted in the entities being removed from the navigation.
=> Update relationship snapshot when recording dangling entities

makefile.shade
Temporary workaround to use a build of nightly NuGet.exe to repack packages with `serviceable` attribute.
=> Use KOREBUILD_NUGET_EXE if available

src/Microsoft.EntityFrameworkCore.InMemory/Microsoft.EntityFrameworkCore.InMemory.csproj, src/Microsoft.EntityFrameworkCore.InMemory/Storage/Internal/InMemoryTransaction.cs, src/Microsoft.EntityFrameworkCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Expressions/Internal/DatePartExpression.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Expressions/Internal/RowNumberExpression.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Sql/Internal/ISqlServerExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Infrastructure/SqliteServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Microsoft.EntityFrameworkCore.Sqlite.csproj, src/Microsoft.EntityFrameworkCore.Sqlite/Query/Sql/Internal/SqliteQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/Sql/Internal/SqliteQuerySqlGeneratorFactory.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteDatabaseProviderServices.cs, test/Microsoft.EntityFrameworkCore.InMemory.Tests/InMemoryTransactionManagerTest.cs
Move the following classes to .Internal.
- InMemoryTransaction
- InMemoryTransactionManager
- SqliteDatabaseProviderServices
- SqliteQuerySqlGenerator
- SqliteQuerySqlGeneratorFactory
- ISqlServerExpressionVisitor
Fix #5761
cc @rowanmiller @anpete
=> Move API into .Internal namespaces.

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/GearsOfWarModel/Gear.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarModelInitializer.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Fixes #5454 
Problem was for happening for queries with optional navigations like so:
context.Orders.Where(o => o.Customer.IsVip)
In this case Customer can be nullable, so IsVip can also be nullable. We compensate for this by introducing the following:
context.Orders.Where(o => o.Customer != null ? (bool?)o.Customer.IsVip : (bool?)null)
However, we didn't convert it back to the original type (users had to introduce those casts themselves). Without the cast, those queries were throwing compile-time exceptions that were not very informative.
Fix is to cast back to the original type requested by user:
context.Orders.Where(o => (bool)(o.Customer != null ? (bool?)o.Customer.IsVip : (bool?)null))
This still may cause runtime errors if o.Customer is actually null, but those are much more …
=> Fix to #5454 - Error when using Where with reference

src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/InMemoryQueryContext.cs, src/Microsoft.EntityFrameworkCore.InMemory/Query/Internal/InMemoryQueryContextFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/UnbufferedEntityShaper.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalQueryContextFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryContext.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsNoTrackingTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/NorthwindQueryFixtureBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ChangeTracker.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/ChangeTrackerFactory.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryBuffer.cs, src/Microsoft.EntityFrameworkCore/Query/QueryContext.cs, src/Microsoft.EntityFrameworkCore/Query/QueryContextFactory.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/NorthwindQueryInMemoryFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NorthwindQuerySqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NorthwindSprocQuerySqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/NorthwindQuerySqliteFixture.cs
Lazily resolve services related to tracking from query such that they will not be loaded when only no-tracking queries are used.
=> Making tracking more pay-per-play in query

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrCollectionAccessorFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrICollectionAccessor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs
=> Allow navigation properties to be typed as IEnumerable so long as backed by ICollection

src/Microsoft.EntityFrameworkCore.Specification.Tests/FindTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/Microsoft.EntityFrameworkCore.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/CompositePrincipalKeyValueFactory.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IIdentityMap.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IPrincipalKeyValueFactory.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IdentityMap.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/SimplePrincipalKeyValueFactory.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/DbSet`.cs, src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/FindInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FindSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/FindSqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #797
Semantics are essentially the same as EF6:
- If entity with given key is being tracked, then return it without a database query
- Otherwise, query the database and track and return entity if found
- Otherwise, return null
=> Implement DbSet.Find

src/Microsoft.EntityFrameworkCore.Design.Core/Utilities/Internal/JsonUtility.cs, test/Microsoft.EntityFrameworkCore.Tools.Core.Tests/Utilities/JsonUtilityTest.cs
- If the entity framework is used in some culture that use another kind of decimal separator the JsonUtility test fail
- Forced invariant culture when doing serialization and add specific test forcing another culture
Fixes #5821 
```
- Detail 1
- Detail 2
```
=> Culture resistence in JsonUtility

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IEntityStateListener.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IInternalEntityEntryNotifier.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/INavigationFixer.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IQueryTrackingListener.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntryNotifier.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/TrackingQueryMode.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/Internal/EntityTrackingInfo.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/StateManagerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #5688
Query code will take care of fixing up entities within the query when Include is used. This means that the state manager does not need to do fixup for these relationships in cases where there are no entities tracked other than those that have come from query. This change allows query to communicate this to the state manager so that it can avoid unneeded work. The change also preserves the very simple case of a single query for a single entity type with no self-refs, in which case the state manager does not need to do work at all.
=> Query tells state manager which relationships have been fixed up

src/Microsoft.EntityFrameworkCore.Design.Core/Design/MigrationsOperations.cs, src/Microsoft.EntityFrameworkCore.Design.Core/Migrations/Design/CSharpHelper.cs, src/Microsoft.EntityFrameworkCore.Design.Core/Properties/DesignCoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Design.Core/Properties/DesignCoreStrings.resx, src/Microsoft.EntityFrameworkCore.Design.Core/Scaffolding/Configuration/Internal/ModelConfiguration.cs, src/Microsoft.EntityFrameworkCore.Design.Core/Utilities/Internal/JsonUtility.cs, src/Microsoft.EntityFrameworkCore.InMemory/ValueGeneration/Internal/InMemoryIntegerValueGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalLoggerExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsIdGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/IsNullExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/PropertyParameterExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ResultOperators/Internal/FromSqlResultOperator.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/ParameterNameGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalSqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerDatabaseModelFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerScaffoldingModelFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteDatabaseModelFactory.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteSqlGenerationHelper.cs, src/Microsoft.EntityFrameworkCore/Internal/TypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ForeignKey.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/IncludeSpecification.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/HiLoValueGeneratorState.cs
=> Fix globalization issues

src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapper.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyExtensions.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Microsoft.EntityFrameworkCore.Relational.Tests.csproj, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/TestRelationalTypeMapper.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
So that if the type mapping for a primary key is changed, then the type mapping for referencing foreign keys will also change.
Issue #2455
=> Propagate type mapping from principal property to dependent property

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalTypeMapper.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/BuiltInDataTypesFixtureBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/BuiltInDataTypesTestBase.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutablePropertyExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/PropertyExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/PropertyBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/PropertyBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/CoreAnnotationNames.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/BuiltInDataTypesInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalTypeMapperTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/TestRelationalTypeMapper.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerTypeMapperTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalPropertyBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs, test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/ModelSnapshotTest.cs
Issue #3420
I think everything in the runtime and migrations areas is implemented. The ScaffoldingTypeMapper already supports unicode, but scaffolding will not make use of this until updated as described in issue #5410.
/cc @rowanmiller Can you look at the public API and doc comments?
=> Implement IsUnicode API

.gitignore, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/TaskBlockingExpressionVisitor.cs
Fix #5640 - Only block composed async queries at the top level.
=> Fix #5640 - Only block composed async queries at the top level.

src/Microsoft.EntityFrameworkCore.Design.Core/Migrations/Design/CSharpSnapshotGenerator.cs, test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/ModelSnapshotTest.cs
Instead of just using the raw annotation syntax.
=> Use fluent API in snapshot for HasMaxLength and IsUnicode

src/Microsoft.EntityFrameworkCore.Design.Core/Migrations/Design/CSharpSnapshotGenerator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/ValueGeneration/Internal/SqlServerValueGeneratorSelector.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutablePropertyExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/PropertyExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/PropertyBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/PropertyBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/CoreAnnotationNames.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, src/Microsoft.EntityFrameworkCore/ValueGeneration/ValueGeneratorSelector.cs, test/Microsoft.EntityFrameworkCore.FunctionalTests/CustomValueGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.InMemory.Tests/InMemoryValueGeneratorSelectorTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalPropertyBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ValueGeneration/ValueGeneratorSelectorTest.cs, test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/ModelSnapshotTest.cs
Issue #5537. Also see #5303.
This change added fluent API set set a custom value generator for use on a property. The value generator will be used regardless of provider and does not do anything special to ensure Migrations or the update pipeline are in sync with what is happening, but is useful to make a change to a value generator when these things do not matter or are already setup correctly.
=> Make it easy to set a custom value generator

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationFixtureBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyAttributeConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/PropertyAttributeConvention.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/DataAnnotationInMemoryFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/DataAnnotationSqliteFixture.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyAttributeConventionTest.cs
When entities are discovered through relationships the conventions run in a different order. This can cause the KeyAttributeConvention to run on derived types before the base. Move the check to validation to avoid the false positive.
Fixes #5898
=> [1.0.1] Fix KeyAttribute on derived types

src/Microsoft.EntityFrameworkCore.Specification.Tests/F1FixtureBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/OptimisticConcurrencyTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/F1SqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs
The optimistic concurrency test base classes contained some SqlServer-specific code, i.e. the setup of a byte[] rowversion as the concurrency column. Moved that out to the SqlServer tests.
@AndriySvyryd, this is a continuation of the discussion in #5367 (thanks for fixing those the tests in #5608.
Also just to let you guys know (@rowanmiller, @divega, @ajcvickers), I've added first-class optimistic concurrency support to the Npgsql provider, using PostgreSQL's xmin column. This is a special system column that all tables have, and which contains the id of the last transaction that touched the row ([see the docs](https://www.postgresql.org/docs/current/static/ddl-system-columns.html)). Challenges included uint support, and also making Npgsql's ModelDiffer totally ignore system columns and …
=> Separate SqlServer code in optimistic concurrency tests

src/Microsoft.EntityFrameworkCore.SqlServer/ValueGeneration/Internal/SqlServerSequenceHiLoValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IKeyPropagator.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IValueGenerationManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/KeyPropagator.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/ValueGenerationManager.cs, src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/DbSet`.cs, src/Microsoft.EntityFrameworkCore/Internal/AsyncLock.cs, src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/ValueGeneration/HiLoValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/HiLoValueGeneratorState.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/ValueGenerator.cs, src/Microsoft.EntityFrameworkCore/ValueGeneration/ValueGenerator`.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbSetTest.cs
But only AddAsync and not everything else that was virally async by association. This allows a path by which an application can ensure that database calls are all async even when using value generators that make calls to the database.
Issue #2291, #5254
=> Bring back AddAsync

src/Microsoft.EntityFrameworkCore.Specification.Tests/InheritanceRelationshipsQueryFixtureBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/OneToOneQueryFixtureBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder`.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ShadowFkFixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Microsoft.EntityFrameworkCore.Tests.csproj, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericRelationshipTypeStringTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericUnqualifiedStringTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
Issue #5377
Added back generic overloads so that in the common case of a shadow property in CLR entity types the generic method can be used instead of using typeof().
Also, only for these APIs, the short name of the type can be passed as a string since the resolution space is very small--it just checks the name at either end of the relationship.
=> Sugar for HasForeignKey/HasPrincipalKey

src/Microsoft.EntityFrameworkCore.Relational/Query/AsyncQueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/ResultTransformingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/IQueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/ShaperCommandContext.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/QueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryCompilationContext.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/AsyncQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fix is to allow more queries to be translated to SQL, specifically subqueries that are correlated with outer query, e.g.
customers.Select(c => c.Orders.FirstOrDefault())
would be translated to:
customers.Select(c => orders.Where(o => o.CustomerId == c.Id).FirstOrDefault())
This would previously produce outer query to fetch all the customers and for each customer another query, fetching ALL the orders each time filtering out the orders for each customer and returning only the first one on the client (because we didn't know how to handle o.CustomerId in this case)
With this change we will convert o.CustomerId into a SQL parameter, whose value is set for each iteration of the outer query - this can be easily translated to SQL and produce much more efficient queries:
SELECT [t].[CustomerID] …
=> [1.0.1] Fix to #5738 - Query Perf: Selecting entire table for navigation properties in projections

src/Microsoft.EntityFrameworkCore.Specification.Tests/FindTestBase.cs, src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore/Internal/EntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/EntityFinderSource.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinderSource.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder`.cs, src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/FindInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FindSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/FindSqliteTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #5998
Moved Find code into its own service and re-factored so it could also be used in a non-generic way.
=> Add non-generic Find to DbContext

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Test for #5369 
we already have support for string.Compare. For the particular query it failed because the argument was property of other object. In current code, that is converted to parameter hence correctly translating to SQL.
=> Query: Add test for string.Compare where argument is not constant

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryAnnotationExtractor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
- Separated requires client eval from composability for FromSql queries in order that FromSql queries can be lifted.
- Fixed a broken assumption in QueryAnnotationExtractor: Extraction should do a deep search of query model expressions.
=> Fix #5773 - FromSql in subqueries

src/Microsoft.EntityFrameworkCore/Metadata/Builders/CollectionNavigationBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/CollectionNavigationBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/EntityTypeBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceCollectionBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceCollectionBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceNavigationBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceNavigationBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Builders/ReferenceReferenceBuilder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderGenericRelationshipStringTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericStringTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/TestModel.cs
This bug would prevent the user from configuring a relationship on the derived type if a convention created a relationship on the base that used any of the same members.
=> Pull down the relationship to the derived type for any order it can be configured.

src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/DesignTimeProviderServicesTest.cs, src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Design.Tests/Microsoft.EntityFrameworkCore.SqlServer.Design.Tests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.Design.Tests/SqlServerDesignTimeProviderServicesTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.Tests/Microsoft.EntityFrameworkCore.Sqlite.Design.Tests.csproj, test/Microsoft.EntityFrameworkCore.Sqlite.Design.Tests/SqliteDesignTimeProviderServicesTest.cs
Code scaffolding is broken in the hotfix branch because the assembly version has changed to "1.0.1.0".
I will also apply this same fix to the dev branch.
cc @Eilon @lajones
=> Fix code scaffolding in hotfix-branch

src/Microsoft.EntityFrameworkCore/ChangeTracking/CollectionEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/CollectionEntry`.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry`.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/MemberEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/NavigationEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/PropertyEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ReferenceEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ReferenceEntry`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Navigation.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyAccessorsFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBaseExtensions.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/CollectionEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/EntityEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/MemberEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/NavigationEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ReferenceEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Microsoft.EntityFrameworkCore.Tests.csproj
Fills out the skeleton of the EntityEntry API adding methods for navigation properties. Patterned closely on the EF6 API.
Also implemented #5114.
=> Add Reference/Collection access methods

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs
Issue #6067
The issue was that we were not checking that the inverse had not already been fixed up before changing it. Added a check to stop this. Also found related issue that if shared PK/FK of Added entity was set manually, then it shouldn't be overwritten with same value by fixup since this will stop it being processed correctly later by DetectChanges.
=> Ensure fixup doesn't get confused when already done manually

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
Problem was that we tried to lift queries that we shouldn't have - i.e. GroupJoin whose ShapedQuery elements were wrapped in Select. Fix is to check the shape of the expression before performing the lifting - we do similar thing for SelectMany already.
=> Fix to #4749 - Query :: error during groupjoin flattening for complex query with multiple joins subquery and LOJ

src/Microsoft.EntityFrameworkCore.Specification.Tests/LoadTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/Microsoft.EntityFrameworkCore.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore/ChangeTracking/CollectionEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/CollectionEntry`.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry`.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/NavigationEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ReferenceEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ReferenceEntry`.cs, src/Microsoft.EntityFrameworkCore/Internal/EntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder`.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/CollectionTypeFactory.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/LoadInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/LoadSqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/EntityEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ObservableHashSetTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/CollectionTypeFactoryTest.cs
Modeled closely on the EF6 APIs
Issue #625
@rowanmiller Can you look at the API and doc comments?
=> Implement explicit loading APIs for navigation properties

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
Use ReferenceEqualityComparer in StateManager
Fixes #6055 
I think this fix should go into 1.0.1
=> [1.0.1] Fix GetReferencingForeignKeys for derived types

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IdentityMap.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityMaterializerSource.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/IEntityMaterializerSource.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/FromSqlQuerySqliteTest.cs
Surround generated ValueBuffer reads with a Try/Catch so we can throw a better exception. Explicit detection of common cases: Null ref and invalid cast.
Fix: #6039, #4289
No perf degradation observed when running tests locally. I will monitor perf runs after this goes in.
=> Query: Better error messages when encountering invalid data.

src/Microsoft.EntityFrameworkCore.Relational/Query/AsyncQueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/GroupJoinInclude.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/QueryMethodProvider.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs
Resolves #5456 
Issue:  `GroupJoinInclude`  in compiled query has querycontext as field which is initialized while iterating query. If the same query is ran from different thread and uses the cached entry then the querycontext in  `GroupJoinInclude`  gets changed. Which means only 1 query will have correct context, rest of them will be using incorrect data hence causing exception.
Solution: Make  `GroupJoinInclude`  immutable and use different data structure which is context based for each query.
Same applies to async case.
=> Query: Make GroupJoinInclude in compiled query thread safe

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
Issue #6109
Fix is to clear any conceptual null if any part of the composite key is nullable, and to instead make sure that that part is null.
Also added more coverage for update scenarios with composite keys and improved perf of GraphUpdatesTest.
=> Fix handling of conceptual nulls for composite keys in change tracker

src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj, src/Microsoft.EntityFrameworkCore.Relational/Query/AsyncQueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncGroupJoinInclude.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/GroupJoinInclude.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/GroupJoinIncludeBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/QueryMethodProvider.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryNavigationsTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/Microsoft.EntityFrameworkCore.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/AsyncQueryNavigationsSqlServerTests.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
Problem was that our include logic for groupjoin was expecting outer and inner elements (on which the include was being performed) to be entities. However sometimes those elements would be TransparentIdentifiers (e.g. when the element comes from a result of SelectMany).
Fix is to also store (when necessary) the accessor from the outer/inner element to the entity that we want to include, extract the actual entity in runtime and apply include operations on that entity instead of the actual outer/inner element.
=> Fix to #5672 - Query :: Include with multiple navigations (including optional navigation) fails

src/Microsoft.EntityFrameworkCore.Relational/Internal/RelationalModelValidator.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Relational/Properties/RelationalStrings.resx, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Tests/SqliteModelValidatorTest.cs
Validate that matching foreign keys and indexes are compatible
Fixes #5769
=> Avoid creating foreign keys with the same relational name

src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/AsyncQuerySqlServerTest.cs
Problem: Our async Select operator was too lazy. The projector delegate was only run when the Current property was accessed, but the code in LoadAsync spins the enumerator without accessing the Current property.
Solution: Change our async Select operator to invoke the projector delegate on MoveNext. This is preferred over accessing Current during LoadAsync because it matches L2O behavior and will prevent future instances of this bug.
=> Fix #6122 - LoadAsync does not work

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/LoadTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/CollectionEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/CollectionEntry`.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateData.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/NavigationEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ReferenceEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ReferenceEntry`.cs, src/Microsoft.EntityFrameworkCore/Internal/EntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder`.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, src/Microsoft.EntityFrameworkCore/Query/Internal/EntityTrackingInfo.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryBuffer.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/LoadInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/StateDataTest.cs
Set when an entity is loaded with Include or one Load, regardless of whether or not there are any related entities or not. Always true for reference navigation properties on tracked entities when the reference is non-null.
Issue #625
Issue #1201
=> Implement IsLoaded flag

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/ChangeTracker.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IStateManager.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/StateManager.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #1198
StateManager keeps count of entities that need processing by SaveChanges and hence can report this without scanning.
=> Implement HasChanges flag

src/Microsoft.EntityFrameworkCore/ChangeTracking/ChangeTracker.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrAccessorFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrCollectionAccessorFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrPropertyGetterFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrPropertySetterFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/CoreAnnotationNames.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityMaterializerSource.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/FieldMatcher.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/IMemberMapper.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/MemberMapper.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ModelExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/MutableModelExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, src/Shared/SharedTypeExtensions.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/FixupTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ContextConfigurationTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs, test/Microsoft.EntityFrameworkCore.Tests/EntityFrameworkServiceCollectionExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/ClrCollectionAccessorFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityMaterializerSourceTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/MemberMapperTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/ModelTest.cs
Add change tracker support for read-only properties with backing fields
Issue #4461
Previously the materializer would use the backing field, but then when a value needed to be set for fixup, etc, things would fall down. Now we generate delegates everywhere that can use the backing field.
Note that query still prefers the backing field, while fixup prefers the property.
MemberMapper was made a service of the model. Only the minimal done here--we can allow it to be set by convention or fluent API if the need to customize it is requested.
Also fixed #758 - When mapping to backing fields handle cases where field is on base type
=> Add change tracker support for read-only properties with backing fields

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fixes #5930 
Difference between logical and bitwise operators is, logical operators can short-circuit. In order to prevent short-circuiting and also producing a valid query, converted the Boolean conditions to values.
=> Query: Handle | and & operator for boolean values properly

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalEntityTypeBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/ValueGeneration/RelationalValueGeneratorSelector.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, test/Microsoft.EntityFrameworkCore.CrossStore.FunctionalTests/DiscriminatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/KeyConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs, test/Microsoft.EntityFrameworkCore.Tools.Core.FunctionalTests/Migrations/ModelSnapshotTest.cs
Change the default of RequiresValueGenerator to simplify KeyConvention
Fixes #5776
=> Explicitly set the DiscriminatorValueGenerator on the discriminator property

src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/EntityQueryableExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/ProjectionExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/LinqOperatorProvider.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/AsyncQuerySqlServerTest.cs
- Corrects handling of nested IQueryables in projections.
- Fixes a small bug in member binding to do with our new parameter injector.
@maumar
=> Fix: 6198 - NotImplementedException for GroupJoin

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs
Issue #6171
The fix is to to make sure that any existing dependent that points to the same principal has its FK and nav props nulled out.
=> Make fixup consistent for 1:1 relationships changed in store

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/EqualityPredicateInExpressionOptimizer.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/PredicateReductionExpressionOptimizer.cs
Resolves #6254 
Issue: We visit children and try to optimize but if we cannot then we fall back to base visitor which re-visit the children hence doubling the execution time for every node.
Fix: When we fail to optimize, create return expression using the visited children.
=> Perf: Query: Avoid revisiting children in visitor

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves #4581 
Issue: For SqlServer, we are able to translate date.month using DatePart which is not available in SQLite at present. When we are able to translate the key successfully, we add order by clause for streaming group by result operator. But we were using the same operator even when key is not translated. Hence the requirement for our streaming group by that records appear in order of their key is broken making more groups than what is expected.
Solution: If we are not able to translate the key to Sql, we should use linq's default group by operator.
=> Query: Use streaming group by operator only if the query has ordering by key

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
=> [TINY] SQL Server Migrations: Avoid redundant WHERE..NOT NULL on unique indices

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
=> [TINY] SQL Server Migrations: Ignore default value of added identity columns

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/WarningsTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/WarningsSqlServerTest.cs
=> Query: Do not show client eval warning for top level Single()

src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/MigrationsScaffolder.cs
We don't need to show the stack trace for these three errors, so we should throw OperationException instead.
cc @bricelam
=> [tiny] Hide stack trace for common migrations operation failures

src/Microsoft.EntityFrameworkCore.Specification.Tests/StoreGeneratedFixupTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/StoreGeneratedTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/PropertyEntry.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/StoreGeneratedFixupInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/StoreGeneratedFixupSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/StoreGeneratedFixupSqliteTest.cs
=> Add IsTemporary API on PropertyEntry

src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder.cs, src/Microsoft.EntityFrameworkCore/DbContextOptionsBuilder`.cs, src/Microsoft.EntityFrameworkCore/Internal/CoreOptionsExtension.cs, src/Microsoft.EntityFrameworkCore/Internal/ServiceProviderCache.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalConnectionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ServiceProviderCacheTest.cs
Issue #6306
Adds a ReplaceService method to DbContextOptionsBuilder that is used like this:
```C#
protected internal override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
=> optionsBuilder
.ReplaceService<IModelCustomizer, CustomModelCustomizer>()
.UseInMemoryDatabase();
```
The replacement service automatically gets the scoping of the original registration.
An exception is thrown if this method is used in combination with UseInternalServiceProvider.
\cc @rowanmiller for API, documentation, and exception message
=> Make it easier to replace internal EF services

src/Microsoft.EntityFrameworkCore/Internal/ModelValidator.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/Infrastructure/ModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/KeyConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderNonGenericStringTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToManyTestBase.cs
Reorder the validation rules so this exception is thrown less frequently.
Fixes #6260
=> [1.0.1] Throw a better exception when shadow keys are detected

src/Tools.DotNet/Internal/EfConsoleCommandResolver.cs, test/Tools.DotNet.FunctionalTests/EndToEndTests.cs, test/Tools.DotNet.FunctionalTests/TestProjects/DesktopStartupApp/Startup.cs, test/Tools.DotNet.FunctionalTests/TestProjects/DesktopStartupApp/project.json.ignore, test/Tools.DotNet.FunctionalTests/Utilities/DotnetEf.cs, test/Tools.DotNet.FunctionalTests/clean-assets.cmd, test/Tools.DotNet.FunctionalTests/clean-assets.sh, test/Tools.DotNet.FunctionalTests/copy-tools.cmd, test/Tools.DotNet.FunctionalTests/copy-tools.sh
dotnet-ef currently assumes AppContext.BaseDirectory is in the extracted nupkg when really it is inside the special .tools folder in the nuget cache.
```
Expected: <nupkg>/packages/Ms.EfCore.Tools.DotNet/<version>/lib/netcoreapp1.0
Actual  : <nupkg>/packages/.tools/Ms.EfCore.Tools.DotNet/<version>/lib/netcoreapp1.0
```
This updates dotnet-ef to use Assembly.Location instead of AppContext.BaseDirectory to find the location of installed nupkg.
cc @JunTaoLuo @bricelam
=> CLI commands: fix search path for locating ef.dll/ef.exe

src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Fixes #6193 
Note, you may want to review [ignoring whitespace changes](https://github.com/aspnet/EntityFramework/pull/6362/files?w=1).
=> [TINY] Migrations: Unwrap enum types before synthesizing a default value

src/Microsoft.EntityFrameworkCore.Specification.Tests/StoreGeneratedFixupTestBase.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/StoreGeneratedFixupInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/StoreGeneratedFixupSqliteTest.cs
We decided that issue #6292 is just a limitation of SQLite and we are therefore not going to do anything in EF about it. Therefore, the SQLite version of the composite key store generated tests will continue to not use store generated values and comments in the code indicating that this should change have been removed.
=> Remove references to issue #6292

src/Microsoft.EntityFrameworkCore.Specification.Tests/Microsoft.EntityFrameworkCore.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore.Specification.Tests/OptimisticConcurrencyTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/ArrayPropertyValues.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/CurrentPropertyValues.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EntryPropertyValues.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/OriginalPropertyValues.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/OriginalValues.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/PropertyEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/PropertyValues.cs, src/Microsoft.EntityFrameworkCore/Internal/EntityFinder.cs, src/Microsoft.EntityFrameworkCore/Internal/IEntityFinder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityMaterializerSource.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/PropertyValuesInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/PropertyValuesSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/PropertyValuesSqliteTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
Issue #1200
Pretty much the same design as EF6. Exposed full property metadata instead of names since we now have nice metadata. Tests were ported from EF6. Not fully functional, especially on SqLite, until #6337 is fixed.
=> Implement CurrentValues, OriginalValues, and GetDatabaseValues

src/Microsoft.EntityFrameworkCore.Design/Design/DbContextOperations.cs, src/Tools.Console/Commands/DatabaseDropCommand.cs, src/Tools.Console/Internal/OperationExecutorBase.cs, src/Tools.Console/Internal/OperationExecutorFactory.cs, src/Tools.Console/Program.cs, src/Tools.Console/Properties/ToolsStrings.Designer.cs, src/Tools.Console/Properties/ToolsStrings.resx, src/Tools.Console/Tools.Console.csproj, src/Tools.DotNet/Internal/DispatchOperationExecutor.cs
A collection of minor tweaks to polish ef.exe.
Change color output of drop database command so it displays better against default blue PowerShell background
Fix #6371 - always create new instance of DbContext for each design-time operation
cc @bricelam
=> [small] polish error handling in ef.exe

src/Microsoft.EntityFrameworkCore/ChangeTracking/EntityEntry.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/EntityEntryTest.cs
Likewise for members, navigations, references, collections.
Issues #2295 and #2245
The issue here is that it is quite common to want to do something for all property entries for a given entity. In the question asked by the customer this was to get the modified state. This was always possible but required two steps:
- Use metadata APIs to find all the Properties
- Loop/query over this metadata getting entries
So Rowan's code looked liked this:
```C#
var entry = context.Entry(myEntity);
var propertyNames = entry.Metadata.GetProperties().Select(p => p.Name);
var modifiedEntries = propertyNames.Select(p => entry.Property(p)).Where(e => e.IsModified);
```
With these new APIs the metadata and entry steps are combined for you so you would now write this:
```C#
var modifiedEntries = …
```
=> Add API to get PropertyEntry objects for all properties of an entity

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/NotMappedMemberAttributeConvention.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalPropertyAttributeConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/PropertyAttributeConventionTest.cs
=> Add support for data annotations on fields

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/OptimisticConcurrencySqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/PropertyValuesSqliteTest.cs
Issue #6337
The expression tree has converts in it to box the returned values. But this means we always ask for object from the reader. Therefore, use the value inside the convert when asking for the value from the data reader.
=> Project correct value types into array

src/Microsoft.EntityFrameworkCore.Design.Core/Properties/DesignCoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.Design.Core/Properties/DesignCoreStrings.resx
This was introduced in 0bae43dd1e5f46271cba354f002d62f42f1b6dff when fixing #5765
@Eilon @divega
=> [1.0.1] Remove trailing whitespace from a resource name

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Expressions/Internal/NullConditionalExpression.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/ExpressionPrinter.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Problem was that we were providing null protection in case of optional navigation access, but that did not include further calling methods on top of them.
If the navigation was null, the member access would return null and we would try to call a method on it, which results in NRE.
Fix is to introduce a new reducible expression that represents conditional access to a method or a member. In memory this gets rewritten to a Block expression that recursively evaluates it's caller, assigns it to a variable and depending on the value, either returns null or performs the required access operation. This is superior to using Conditional expression that we did before, because the caller only gets evaluated once, rather than N times.
Also fixes related issue #6261 - DateTime converted to …
=> Fix to #5613 - Query :: optional navigations null-ref protection logic doesn't work for some cases involving multiple optional navs and method calls

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves #5736 
For logical binary expressions, we try to evaluate each child and if it converts to true/false then based on the node type we prune the trees.
=> Query: Use short-circuiting in predicates based on parameter values

src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Problem was that when we do SelectMany, we should later re-map all subsequent references to the original query source, to point to the new query source (added during SelectMany nav rewrite). However we were not doing that for query sources inside a subquery. This caused incorrect query sources to be embedded in the query, which could not be translated and hence the 'must be reducible node' exception was thrown.
Fix is to also replace query sources inside a subquery.
=> [SMALL] Fix to #5812 - 'must be reducible node' when aggregating over a join

src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalLoggerExtensions.cs
I noticed that the logged times for the executed commands are way off what they should be and found a small bug in the source code.
The problem is that TimeSpan ticks does not always equate to Stopwatch ticks so a conversion based on the Stopwatch.Frequency is necessary.
On my macbook running osx the reported times are 100 times slower and on my windows 10 desktop they are 3 times slower.
This is by no means a serious bug but its definitely annoying.
=> Fix incorrect timestamp conversion to milliseconds in logging

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/RelationalTestStore.cs, src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TransactionFixtureBase.cs, src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TransactionTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/BatchExecutor.cs, src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/DatabaseFacade.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/BatchExecutorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/TransactionSqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/SqliteTestStore.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/TransactionSqliteFixture.cs
Issue #6339
```C#
context.Database.AutoTransactionsEnabled = false;
```
Doesn't affect anything done with UseTransaction or BeginTransaction--only prevents EF from creating a transaction automatically.
Also some perf improvements for running the transaction tests--previously when running on my machine they would take about 70 seconds. Now they take about 3. But note that most of this is masked when running many tests in parallel.
=> Support opting out of wrapping database operations in a transaction during SaveChanges()

src/Microsoft.EntityFrameworkCore.Relational/RelationalDatabaseFacadeExtensions.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs
=> Add DbContext.Database.GetMigrations() etc. methods

src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/Operations/SqlServerCreateDatabaseOperation.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerConnection.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerDatabaseCreationTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerConditionAttribute.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerConnectionTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
There isn't any handling for custom filenames within sql connection strings ('AttachDBFilename'), which leads to obscure error messages. Thus, we just add proper handling of filenames.
* AttachDBFilename gets a reset while building master connection strings
* Exists checks accept error 1832 **and 5120** too as a hint for a non existing database
* SqlServerCreateDatabaseOperation gets an additional FileName property
*NOTE:* I don't get the difference between "CreationTests" and "CreatorTests", so I just added my tests to the former ones (the other ones seem to test less related stuff).
~~*NOTE:* The changes broke a unit test, which I just changed accordingly. I'm not sure, if that's ok.~~
Fixes #2810
=> Add support for AttachDBFilename

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBaseExtensions.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs
Issue #6570
This issue is caused by incorrectly calculating the indexes for navigations. Navigations started counting at the end of the properties, but I'm not sure why that was since all uses appear to be independent. This lack of overlap was then "corrected for" when using the index for the IsLoaded flag, but this correction was done incorrectly when derived types were involved. The fix is to just make navigation indexes count independently from property indexes. Note, however, that relationship indexes are still combined.
=> Correct navigation index calculation

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fix #6478 
Issue: In certain queries where there is a subquery being used in multiple parts, the same subquerymodel is shared among all. If there is member access on subquery then our optimizer in `SubqueryMemberPushDownExpressionVisitor` modifies the selector for subquerymodel. Due to this, other places where subquerymodel is used now has invalid querymodel.
Fix: Since the subquerymodel could be shared, before modifying it, clone it to make a new copy in order to keep the original model intact.
=> Query: Bug 6478: Do not mutate original subquery model in SubqueryMemberPushDownExpressionVisitor

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/AsyncFromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/QueryingEnumerable.cs
Resolves #6581 
Issue: When MARS is disabled, we buffer all the data. Which was setting datareader to null. Our dispose method was based on assumption that if datareader is non-null then only we opened connection & we should try to close it.
Fix: We should close the connection once we are done buffering all the data.
=> [1.0.2] Query: Close the connection properly while loading related data

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs
Fixes #6530 
Issue: During Include with skip/take, first query select only fixed amount of rows. Second query should join related data with only those rows. But using `WHERE EXISTS` will give matching rows for all related data. With use of Skip, if there are not sufficient matching rows then where exists can return false. With Take it will return true for any matching rows. This would give incorrect result (reported in #5901 & fixed in #6002) or fetch whole table (#6530)
Solution is to disable `Where Exists` while using skip/take.
=> [1.0.2] Query: Generate Inner Join for collection include while Skip/Take

src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ExpressionTransformingQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Problem was that for some groupjoin queries, e.g.:
```c#
var query = context.LevelOne
.GroupJoin(
context.LevelOne.Select(l1 => l1.OneToOne_Required_FK),
l1 => l1.Id,
l2 => EF.Property<int?>(l2, "Level1_Optional_Id"),
(l1, l2s) => new { l1, l2s })
.Select(r => r.l1)
```
In this case inner collection selector can potentially return null and therefore when translating inner key selector we should apply null protection logic. We were not doing that however, because those two operations were done in separate places, by two different instances of NavigationRewritingExpressionVisitor. Fix is to introduce additional state to the visitor, when visiting inner key selector, and then using that information when processing inner key selector.
Moreover now we are reusing the …
=> Fix to #6429 - NRE protection is not applied to manually created GroupJoin when trying to extract keys from collections potentially containing nulls

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Problem was during join flattening - we can't flatten joins whose input elements are not directly ShapedQueries (e.g. when shaped query is wrapped in select). For those cases we should delegate to client eval.
We already do that for GroupJoin, but it can also happen for regular joins.
=> [SMALL] Fix to #6597 - "Operation is not valid due to the current state of the object" in some queries with navigation and paging

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves #6598 
We have `ProjectionComparisonTransformingVisitor` class in Sql-Server specific code.
https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs#L153
Which somewhat does the same thing as `SearchConditionTranslatingVisitor`. In combination, both tried to make a case block hence we got into state of incorrect nested case blocks.
Sql-Server specific code should be removed and relational one should be used. The most of the changes needed in `SearchConditionTranslatingVisitor` are already done in 1.1.0 codebase.
=> [1.0.2] Query: Remove Sql-Server specific projection modifier for search conditions

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Shared/SharedTypeExtensions.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was with Tracking queries involving GroupBy and OrderBy/Skip/Take/Distinct. When tracking results of group by we were trying to extract Grouping element from the result however we always assumed that the Grouping result operator would be on the main QueryModel. When Orderby/Take/Skip etc are used in conjunction with GroupBy, the GroupBy result operator is actually in the subquery. Fix is to properly extract Group Element information from the subquery when needed.
=> [1.0.2] Fix to #6620 - GroupBy multiple keys throws exception in 1.0.1

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
We used to try server-evaluate calls to First() in a subquery, however we are unable to properly mimic the exception that could potentially be thrown from First() method. Fix is to always force client evaluation when First() is used in a subquery.
If one wants to avoid client evaluation, FirstOrDefault() should be used.
=> [SMALL] Fix to #5544 - Query :: force client evaluation on First() inside a query

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EmptyShadowValuesFactoryFactory.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalShadowEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/ShadowValuesFactoryFactory.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutableNavigationExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutablePropertyBaseExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutablePropertyExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/IProperty.cs, src/Microsoft.EntityFrameworkCore/Metadata/IPropertyBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBaseExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/TypeBase.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj
These are changes that have been made on the ComplexTypes branch for things that I found following the change to the metadata types hierarchy and the move of some members to IPropertyBase. Making these changes to dev since they aren't strictly related to complex type support and it is better to change them sooner rather than later.
=> Metadata cleanup following hierarchy/base class changes

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
Fixes #6270 
Issue: There are multiple issues here
1. In projection, we have function to update column references while from is subquery but if the inner projection is aliased then it does not use alias. And in the case of specific SQL function, it tries to use it on a column which is not projected in the subquery. Fix is to use the alias if the inner projection has alias, else update column reference.
2. In where clause, when we select whole querysourcerefence, we were trying to use the subquery selector. That works only if the single column is being projected out of the subquery. But in the case if the inner subquery projection is aliased due to Sql function then it will have Sql function with references which may not be projected in subquery. Fix is to use the alias expression if …
=> Query: Properly modify column references while from clause is subquery

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fixes #6145 , #6580 
Converted OrderBy with Constant/Parameter to `(SELECT 1)`
Converted dummy `@@rowcount` to `(SELECT 1)`
=> Query: Convert Order By constant & @@rowcount to (SELECT 1)

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/ColumnExpression.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/IncludeTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
Fixes #6591 
Issue here was, when we were lifting order by in collection include, we only made alias for `SelectExpression` so for a case block, we updated column expression to add it to outer query order by. Which generated incorrect SQL because the column is not project from inner subquery and the table reference is incorrect.
Fix is to make alias for any expression in inner subquery order by which is not column expression or aliased column expression.
Another minor fix - if ColumnExpression does not have underlying property then `Equals` should match names too.
=> Query: Convert complex expression to alias while lifting order by in collection include

src/Microsoft.EntityFrameworkCore/Extensions/EntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Extensions/MutableEntityTypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ComplexTypeUsage.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/ComplexTypeUsageTest.cs
Makes EntityType.GetComplexTypeUsages return all usages in the hierarchy and adds methods to get only declared usages. This matches the semantics for properties. Methods on complex types themselves don't change since we don't support mapped hierarchies in complex types.
/cc @AndriySvyryd (but anyone can review)
=> Add GetDeclaredComplexTypeUsages and match semantics

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalExpressionPrinter.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Expressions/Internal/NullConditionalExpression.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/ExpressionPrinter.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/IQueryModelPrinter.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryModelExtensions.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryModelPrinter.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
Example of the output:
```
from Customer c in [EntityQueryable<Customer>]
where ([c].City == "London")
orderby [c].CustomerID asc
select
from Order o1 in [EntityQueryable<Order>]
where (([o1].CustomerID == [c].CustomerID) AndAlso (Convert([o1].OrderDate).Year == 1997))
orderby [o1].OrderID asc
select
from Order o2 in [EntityQueryable<Order>]
where ([o1].CustomerID == [c].CustomerID)
orderby [o2].OrderID asc
select [o1].OrderID
```
- Made ExpressionPrinter to work from Visit() method rather than from Print() entry method.
- Fixed minor issue with NullConditionalExpression.ToString()
=> Adding printer class for QueryModel for easier debugging.

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionTranslators/RelationalCompositeExpressionFragmentTranslator.cs
This is a fix to https://github.com/aspnet/EntityFramework/issues/6691
We did similar change for the MethodCallTranslators.
=> [TINY] Fix to #6691 - Provider specific ExpressionFragmentTranslators should override default ones

src/Microsoft.EntityFrameworkCore.Relational/Update/UpdateSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/StoreGeneratedFixupTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Update/Internal/SqliteUpdateSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/UpdateSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/UpdateSqlGeneratorTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs
For inserts inner join the INSERTED table instead of reading values directly from it.
For updates use the relational implementation that doesn't use INSERTED table.
Fixes #6044
Fixes #6474
=> Add support for triggers that modify values in the inserted/updated row to SQL Server

src/Microsoft.EntityFrameworkCore.Design/Design/Internal/StartupInvoker.cs, src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/ReverseEngineering/E2ETestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerDesignTimeServices.cs, src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteDesignTimeServices.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/IDesignTimeServices.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, test/Microsoft.EntityFrameworkCore.Design.Tests/Design/Internal/StartupInvokerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/SqliteDatabaseModelFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.Design.FunctionalTests/SqliteScaffoldingModelFactoryTest.cs
`IDesignTimeServices` can be implemented in the startup assembly to override the default design-time services like `MigrationsCodeGenerator` or `EntityTypeWriter`.
Also stops looking for `ConfigureServices` on `App` and `Program` (use `IDbContextFactory` instead).
Providers beware: This has a minor breaking changes in `Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests`
Resolves #5617, fixes #5677
=> Add IDesignTimeServices

src/Microsoft.EntityFrameworkCore.Relational/Infrastructure/RelationalServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalDatabaseCreator.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalDatabaseProviderServices.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerDatabaseProviderServices.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteDatabaseProviderServices.cs, src/Microsoft.EntityFrameworkCore/Infrastructure/EntityFrameworkServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore/Internal/IServiceInjectionSite.cs, src/Microsoft.EntityFrameworkCore/Internal/ServiceProviderExtensions.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/QueryContextFactory.cs
Issue #6622
The approach we discussed didn't pan out exactly because IRelationalDatabaseCreator can also be obtained as the non-relational service IDatabaseCreator. The delegate for this is defined in the core package and so cannot directly reference relational types. Therefore, I created an abstract interface that any provider service can implement which then allows the service itself to request the additional services it needs.
Tested by making SQLite and SQL Server providers use the obsolete constructor and running all tests.
RelationalQueryContextFactory was not changed--see issue #6713.
We should review other constructors for changes--see issue #6714
=> Fix breaking change to RelationalDatabaseCreator constructor

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
Issue here:
We need to filter on qsre not null. But since it is not being materialized the value comes from the valuebuffer. `ValueBuffer` is tricky object here. When we use a composite shaper, the value buffer has values but we don't know corresponding value of particular qsre to compare it to null. And when it is valuebuffer for particular qsre only then `_values` becomes null instead of null value inside value buffer.
For SqlServer, which flattens query, we use composite shaper, we can translate such filters to Sql via entity equality rewriting.
For SQLite & InMemory where we generate different queries we need to guard against, `_values` in value buffer being null instead of actual value.
built on top of #6706 
Resolves #6636
=> Query: Convert Entity comparison with null to comparison on key properties

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
Resolves #6207 
Issues here:
Additional unification in `DefaultIfEmpty` result operator processing which causes alias references to break.
Another side-effect, Since DefaultIfEmpty operator is in query model without group join, it doesn't materialize and keeps valuebuffer which doesn't work well when valuebuffer is being compared to null.
=> Query: Generate proper aliases for DefaultIfEmpty result operator

src/Microsoft.EntityFrameworkCore/Metadata/IEntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/IProperty.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs
Issue #6709
This should fix binary compat issues where 1.0 providers are bound to these members on the derived types.
=> Add back members to metadata interfaces

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IsNullExpressionBuildingVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/PredicateReductionExpressionOptimizer.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/ColumnExpression.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/ComplexNavigationsQuerySqliteTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/GearsOfWarQuerySqliteTest.cs
Problem was that we were not adding null semantics compensation for some cases that were enabled after LOJ translation to SQL.
Specifically, when we decide whether to apply null semantics we look at the expression nullability, and for Column/Alias expression we also look at the IProperty to see if it's nullable (e.g. in case of a non-nullable string).
LOJ translation enabled scenarios where the IProperty is non-nullable, but the actual value can be null, because it comes from an optional navigation - we should be applying null semantics for those cases.
Fix is to add extra metadata to ColumnExpression telling us when the column can be null, even if the IProperty says otherwise. The field is being set during ConditionalAccessExpression translation.
Also fixed minor bugs found along the …
=> Fix to 6702 - Query: Null semantics issue after improved nav. translation

src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalCommandExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj, src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationCommand.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/QueryingEnumerable.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalCommand.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RelationalCommandBuilderFactory.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalCommandTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
Make RelationalCommandBuilderFactory use a public type for the ISensitiveDataLogger category
Fixes #6700
=> Remove parameters with default values from IRelationalCommand

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/Internal/SqlServerValueGenerationStrategyConvention.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Internal/SqlServerPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/DataAnnotationInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
=> Make the DatabaseGeneratedOption annotation configure ValueGenerationStrategy for SqlServer

src/Microsoft.EntityFrameworkCore/Metadata/INavigation.cs, src/Microsoft.EntityFrameworkCore/Metadata/IProperty.cs, src/Microsoft.EntityFrameworkCore/Metadata/IPropertyBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs
Issue #6768
/cc @divega @rowanmiller
=> Add back IPropertyBase.DeclaringEntityType for binary compat with 1.0 providers

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
DefaultQuerySqlGenerator's GenerateOrderBy is a single block that's difficult to extend. Moved the generation of the individual ordering clauses into a separate function to allow appending to them.
This is necessary to support PostgreSQL ORDER BY ... NULLS FIRST.
I hope this can make it into 1.1, it's really very trivial.
=> Trivial refactor to make ORDER BY more extensible

src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs
When deciding which value generation to use, the SQL Server provider falls back to the model annotation. However, it did not properly check that the property's CLR type is compatible with the model-determined strategy. As a result, defining a ValueGeneratedOnAdd decimal on a model with strategy HiLo triggered a failure.
=> Fix SQL Server value generation from model issue

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
Issue #6720
The fix is to stop marking the value as permanent as soon as the store generated value is generated, but instead weight until AcceptChanges when it is pushed into the entity. Also, when DiscardStoreGeneratedValues is used, a temporary value is ensured to stay temporary.
=> Preserve temporary flag for store generated values until AcceptChanges

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
Resolves #6785 
Set table for project star wherever we generate subquery which needs project star.
~~Slight change in API for `SetTableForProjectStar` since we don't have query source perfectly matched with table alias.~~
Nuked the function to set project star. Direct setter on the property since we need to store string alias only.
=> Query: Set table alias for star projection properly for all cases

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fore `Any()` or `All()` we created new `SelectExpression` for inner subquery but we should clone it so that we preserve all limit, offset & orderby from it.
Fixes #6710 
Should this go to 1.2.0 or dev?
=> Query: Skip/Take with Any/All should preserve skip/take

src/Microsoft.EntityFrameworkCore.Specification.Tests/GraphUpdatesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, src/Microsoft.EntityFrameworkCore/EntityFrameworkServiceCollectionExtensions.cs
Because this either throws because the PK property cannot be set to null, or marks the property as conceptually null which then causes issues later.
There were also two issues in the tests:
- Equals method of one of the entities was wrong
- Tests wouldn't run on SQLite because composite keys with store generated ints are not supported
Issue #6840
=> Don't attempt to null out PK parts of composite FK during fixup

src/Microsoft.EntityFrameworkCore/Query/Internal/AsyncLinqOperatorProvider.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs
- Removed an allocation from the query execution code path. 
- Reverted hack introduced in fixing #4317 because it looks like the IX-Async issue has been resolved.
=> Query: Minor perf optimizations

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/DerivedTypeDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InheritanceDiscoveryConventionBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/DerivedTypeDiscoveryConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
Properly discover base types when they are added to the model after the derived types.
Improve the exception message for conflicting properties in the new base type.
Don't duplicate unused inherited properties that are being removed when setting a new base type. They will be discovered by conventions if they should be on the entity type.
Fixes #6814
=> Lift properties from the derived types in addition to the current type when setting base type.

src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs, src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs, src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/IndexConfiguration.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Metadata/IndexModel.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/RelationalScaffoldingModelFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/IRelationalIndexAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalFullAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalIndexBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalIndexAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationBuilder.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/Operations/CreateIndexOperation.cs, src/Microsoft.EntityFrameworkCore.Relational/RelationalIndexBuilderExtensions.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerDatabaseModelFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Internal/SqlServerIndexBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/FilteredIndex.expected, test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/FilteredIndexContext.expected, test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Migrations/SqlServerMigrationSqlGeneratorTest.cs
```
Implement ability to add filter to index
- Extension for index builder
- Index creation operation
- Corresponding SQL generator for migration
- Corresponding SQL reverse engeniering code for scaffolding
- Corresponding C# reverse engeniering code for scaffolding
Fixes #5817
```
Fixed #5817
=> feat(Migrations): SQL Server Filterable indexes.

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/Internal/SqlServerQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
Resolves #6736 
Issue for the specific case of #6736 is, when we do RowNumberPaging, we remove `OrderBy` clause. For a simple query, results are returned correctly but when we have include, we add ordering on PK property, which changes the order causing incorrect results.
For more general case, it can arise whenever we push down a subquery since outer query will not have any order by and Include can introduce one.
Fix would be to copy over the order by so that data is always in fixed order and will not be change. Also clear order by from a subquery level if there is not limit/offset.
=> Query: Copy OrderBy in PushDownSubquery

src/Microsoft.EntityFrameworkCore.Specification.Tests/FieldMappingTestBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/BackingFieldConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/ClrCollectionAccessorFactory.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs
Issue #6893
This lets backing fields of, for example, `List<T>` be found and used for navigation properties of `IEnumerable<T>` while still allowing fields of `int?` to be found and used for properties of `int`.
=> Allow navigation backing fields to be assign-compatible

src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityTypeExtensions.cs
Issue #6914
Method is not an extension method and is obsolete but should allow code already bound it to continue working.
=> Add back EntityTypeExtensions.DisplayName to fix binary break

src/Microsoft.EntityFrameworkCore/Internal/TypeExtensions.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityType.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/InternalPropertyBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/Property.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/PropertyBase.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/EntityTypeTest.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/InheritanceTestBase.cs
Make InternalEntityTypeBuilder.HasKey more resilient by removing conflicting fks of lower source
Reset FieldInfo when lifting properties if the field doesn't exist on the new type
Improve the exception message for removing a property that is still being referenced
Fixes #6867
=> Add a safeguard for fks updated in recursive calls to ForeignKeyPropertyDiscoveryConvention

src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Problem was that during nav rewrite we sometimes can simplify navigation like: order.Customer.Id into order.CustomerId.
This however is problematic for some complex queries like so:
var query = context.LevelThree
.Select(l3 => l3.OneToOne_Required_FK_Inverse)
.OrderBy(l3 => l3.Id)
.Take(10)
.Select(l2 => l2.OneToOne_Required_FK_Inverse.Name);
In this case we try to lift the orderby to the outer query. If the orderby gets simplified the query becomes invalid, because now we try to order by Level3.FK_ID, but what we project out from the subquery is Level2.
Fix is to not perform this optimization for orderby inside a subquery if we project the entity on which property we try to order.
=> Fix to #6896 - Query: Rewrite Principal key access to FK access only if FK entity is not projected out

src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/IndexConfiguration.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/FilteredIndexContext.expected
Expressions in index filters may contain backslashes, double-quotes, etc.
Scaffold these expressions as verbatim strings and escape double-quotes. Especially important for PostgreSQL where identifiers are surrounded by double-quotes.
cc @laskoviymishka
=> Use verbatim strings for scaffolded index filters

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/WarningsTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
Resolves #6929 
Issue: we always set ClientEval as false even though it was required. Added proper handling.
Rules:
Last with order by can always be translated to Sql. Do not log warning.
LastOrDefault with order by gets translated but we still do client eval for the exception (just like FirstOrDefault), Do not log warning.
Warn when LastOrDefault is used inside subquery.
Warn when Last is used without order by because we need to evaluate on client to find the last record.
=> Query: Issue propert client eval warning for Last & LastOrDefault

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/ExistsExpression.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/CompiledQueryCacheKeyGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
@anpete @maumar 
Some of the tests which relied on Supporting offset are made ConditionalFact
For, rownumberpaging we did not modify select expression if it was wrapped inside Exists. Causing invalid queries for SqlServer2008.
=> Build fixes for SqlServer 2008

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/TransactionTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/BatchExecutor.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/BatchExecutorTest.cs
Resolves #6968 
Issue here was, we were closing the connection while saving changes even if we did not open it.
Question: Where should I add tests?
=> Maintain connection state in BatchExecutor

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/CompiledQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/Microsoft.EntityFrameworkCore.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, src/Microsoft.EntityFrameworkCore/EF.CompileAsyncQuery.cs, src/Microsoft.EntityFrameworkCore/EF.CompileQuery.cs, src/Microsoft.EntityFrameworkCore/EF.cs, src/Microsoft.EntityFrameworkCore/Internal/NonCapturingLazyInitializer.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/AsyncEnumerable.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/CompiledAsyncEnumerableQuery.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/CompiledAsyncTaskQuery.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/CompiledQuery.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/CompiledQueryBase.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/IQueryCompiler.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/CompiledQueryInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests/Microsoft.EntityFrameworkCore.InMemory.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/CompiledQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/CompiledQueryInMemoryTest.cs, test/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests/Microsoft.EntityFrameworkCore.Sqlite.FunctionalTests.csproj
- Adds EF.CompileQuery and EF.CompileAsyncQuery which allow for the creation of user managed
compiled query delegates. Such queries are more efficient to execute because they bypass the
CompiledQueryCache (avoiding query hashing and parameterization). Typical gains are around 3-5%
=> Query: Perf: Adds explicit compiled queries.

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EntityGraphAttacher.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/AggregatesTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/CollectionEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/EntityEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ReferenceEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #6990
Makes Attach/Update more useful by properly using the value-generation semantics built into the model.
Note that we haven't decided to do this yet, but I did the work to validate the approach. I will not merge until we decide to do it.
=> Stop special-casing the root entity on Attach

src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Query/QueryCompilationContext.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was that for GroupJoin we need to mark both inputs for materialization, so we have all the elements necessary to produce joining calls.
However, if one side is a subquery, we just mark that outer query source for materialization, without digging deep into the subquery itself. This results in the actual table (which is inside) not being materialized, and that in turn produces SQL which doesn't have necessary elements to produce the correct joins.
Fix is to check if the groupjoin element in a subquery, and if so recursively mark it's elements for materialization.
=> [SMALL] Fix to #7003 - Wrong SQL generated for query with group join on a subquery that is not present in the final projection

src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/EntityMaterializerSource.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
Adding bad data error handling logic to materialization introduced the possibility
of hitting a known expression compiler limitation (as described here: https://github.com/dotnet/corefx/pull/13126).
This change works around the limitation by moving the read-value try-catch to a helper method, thus we no
longer insert a try-catch directly into the output ET.
=> Fix: #7048 - EF Core 1.1 .ToString() translation causes exception

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/PredicateReductionExpressionOptimizer.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/GearsOfWarQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Problem was that when we were fixing search conditions on a query, we did not take into account differences in nullability that could be created by those transformations.
e.g.:
myEntity.MyNullableBool (result type is bool?)
would get converted to:
myEntity.MyNullableBool == (bool?)true (result type bool)
If that in turn was a part of a bigger expression, e.g. AndAlso with another bool? expression, that did not have to be converted, then we would produce a type discrepancy which was resulting in an error.
Fix is to adjust types of the Left and Right expressions that we process before reconstructing a binary expression node.
=> Fix to #7061 - the binary operator Equal is not defined for the types 'System.Nullable`1[System.Boolean]' and 'System.Boolean'

src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
=> Allow ForeignKeyPropertyDiscoveryConvention to use the primary key if the name matches even if the principal end hasn't been configured.

src/Microsoft.EntityFrameworkCore.SqlServer/Extensions/SqlServerIndexBuilderExtensions.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
As filtered index expressions are very likely to be provider-specific.
Closes #7087
Not sure if that's all that needed to add a provider-specific setting? Hope I didn't miss anything...
=> Add ForSqlServerHasFilter

src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/TestUtilities/BuildReference.cs, src/Microsoft.EntityFrameworkCore.Relational.Design.Specification.Tests/project.json
This ensures references from the netstandard1.7 TFM are resolved by Microsoft.EntityFrameworkCore.Design.FunctionalTests.
=> Update test specification to netstandard1.7

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/NavigationFixer.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/CollectionEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/PropertyEntryTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ReferenceEntryTest.cs
Issue #7227
Ensures that the entity is attached with the property set to modified and that fixup does not inappropriately do more than it should (i.e. marking FK is modified).
=> Fix handling of setting property to modified on detached Entity (Note: 1.1.1 fix)

src/Microsoft.EntityFrameworkCore/EntityFrameworkQueryableExtensions.cs, src/Microsoft.EntityFrameworkCore/Query/ResultOperators/Internal/ThenIncludeExpressionNode.cs
Issue #7116
Method is obsolete and not an extension method since it only needs to be there for binary compat.
=> Add back ThenInclude for ICollection to fix binary compat break (Note: 1.1.1 fix)

src/Microsoft.EntityFrameworkCore.Relational/Update/Internal/CommandBatchPreparer.cs, src/Microsoft.EntityFrameworkCore.Relational/Update/ModificationCommand.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/KeyPropagator.cs, src/Microsoft.EntityFrameworkCore/Metadata/Internal/MutableEntityTypeExtensions.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/CommandBatchPreparerTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Update/ModificationCommandTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/KeyPropagatorTest.cs
=> Propagate the temporality of values.

src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/Xunit/SkipReasonTestCase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/Xunit/SkipXunitTheoryTestCase.cs
by adding parameterless constructor
fixes #7320
=> Enable TestCases to run from Visual Studio Test Explorer

src/Microsoft.EntityFrameworkCore.Relational/Metadata/Internal/RelationalPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/Internal/SqlServerPropertyBuilderAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerInternalMetadataBuilderExtensionsTest.cs
=> Don't throw when SqlServer ValueGenerationStrategy is configured on an incompatible property by a convention

src/Microsoft.EntityFrameworkCore.Specification.Tests/DataAnnotationTestBase.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
=> [1.1.1] Only consider navigations to be ambiguous if there's more than one with InversePropertyAttribute.

src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs, test/Microsoft.EntityFrameworkCore.Tests/DbSetTest.cs
Note that set creation has to happen before the model is created because model creation is lazy. So the fix here is to check when the set is lazily initialized that the type hasn't been ignored.
Issue #7094
=> Throw better exception if DbSet is used with ignored entity

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs
Corrected a bad assumption in RelationalQueryModelVisitor.SnapshotQuerySourceMappings.
=> Fix #7293 - Queries fail after upgrading to EF Core 1.1

src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimEndTranslator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimStartTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteStringTrimEndTranslator.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Query/ExpressionTranslators/Internal/SqliteStringTrimStartTranslator.cs
It was relying on only one method with that name being declated (i.e. no overloads), which will break once additional overloads are added.
Fix is to make method selection deterministic.
=> Changing a way we extract MethodInfo to be used for TrimStart and TrimEnd translators

src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EntryPropertyValues.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/InternalEntityEntry.cs
=> Fix OriginalValues.Clone to really use original values (1.1.1 fix)

src/Microsoft.EntityFrameworkCore/DbContext.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #7298
This is a lower-risk fix replacing #7430. The fix is to call the non-async methods. There is an extremely low probability that any real-world code is making database calls in the async methods combined with an even lower probability that making those calls synchronously would cause issues, so this fix is low-risk and does not have binary-compat issues.
=> Make AddAsync and AddRangeAsync include related entities (1.1.1 fix)

src/Microsoft.EntityFrameworkCore/IEntityTypeConfiguration`.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/ModelBuilder.cs, test/Microsoft.EntityFrameworkCore.Tests/ApiConsistencyTestBase.cs, test/Microsoft.EntityFrameworkCore.Tests/Microsoft.EntityFrameworkCore.Tests.csproj, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/IEntityTypeConfigurationTest.cs
=> Add EntityTypeConfiguration<TEntity>

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EntityGraphAttacher.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IEntityEntryGraphIterator.cs, src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/IEntityGraphAttacher.cs, src/Microsoft.EntityFrameworkCore/DbContext.cs, test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
=> Make AddAsync and AddRangeAsync really async

src/Microsoft.EntityFrameworkCore/DbContext.cs, src/Microsoft.EntityFrameworkCore/Internal/DbContextPool.cs, src/Microsoft.EntityFrameworkCore/Internal/IDbContextPoolable.cs, src/Microsoft.EntityFrameworkCore/Internal/InternalDbSet.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- Fixed race condition between pool return and context state reset.
- Added missing dispose checks to DbContext. These are helpful for uncovering pooling issues because pooled instances are treated as disposed when not in use.
=> Fix #7251 - Possible race condition affecting DbContext pooling.

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/SqlExecutorTestBase.cs, src/Microsoft.EntityFrameworkCore.Relational/RelationalDatabaseFacadeExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/IRawSqlCommandBuilder.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/Internal/RawSqlCommandBuilder.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Microsoft.EntityFrameworkCore.Relational.Tests.csproj, test/Microsoft.EntityFrameworkCore.Relational.Tests/Storage/RelationalDatabaseFacadeExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
Issue #7100
Allow:
- Async without explicit cancellation token
- Strongly typed arrays/lists
- Not accidentally passing cancellation token as parameter
There is no overload taking `IEnumerable<TParam>` because this results in a single string parameter being passed as `IEnumerbale<char>`. A similar situation still exists for parameters that implement IList of something, but this seems much less likely. Another option would be to add an explicit overload that takes string and revert to IEnumerable, but this would only cover the string case and not any other parameter type that implements IEnumerable.
=> Change signatures of ExecuteSqlCommand/Async to be more natural to use

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryBugsTest.cs
Resolves #7359 
Whenever we make comparison of discriminator using `EF.Property` the property expression is generated to be null-able type. If the value is non-nullable type (like int) then it throws exception due to strong typing of `Expression.Equal`. Fix is to create the constant for value of type of the property expression to avoid mis-match.
It surfaces in materializer for shadow properties. For CLR property the `is` operator in predicate would throw exception.
=> Query: Use discriminator type to create the discriminator constant values

src/Microsoft.EntityFrameworkCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs, test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs
Issue #7119
The fundamental problem here is that Answer.AuthorId is being used as the FK for two different relationships. The navigation properties for the relationships effectively pointed to different objects during fixup, which caused the FK to change value, resulting in an inconsistent graph. This kind of overlapping FKs will only work if great care is taken with the entities assigned and FK values given, which was not the case in the repro code.
All that being said, the framework should be resilient to modification of navigations while attaching, so defensive copy code has been added to ensure this.
=> Defensively copy navigation properties during graph attach

src/Microsoft.EntityFrameworkCore.Relational/Storage/IRelationalConnection.cs, src/Microsoft.EntityFrameworkCore.Relational/Storage/RelationalConnection.cs, src/Microsoft.EntityFrameworkCore.Sqlite/Storage/Internal/SqliteRelationalConnection.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalConnectionTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/Utilities/TestSqlServerConnection.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
Issue #7527
Removes the reference counting logic from SqliteRelationalConnection and instead uses information from the base implementation to determine if a connection was actually opened and therefore whether or not the pragma to enable FKs needs to be sent.
=> Update IRelationalConnection to return status of Open/Close calls

src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
Resolves #7512 
Issue: `Distinct()` in linq is not guarantee the ordering of results. Therefore `Take` after `Distinct` can give different set of rows depending on ordering conservation by providers.
filed #7525 for variations after `Distinct()`
=> Test: Update a test which was giving non-deterministic results

test/Microsoft.EntityFrameworkCore.Tests/DbContextTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/OneToOneTestBase.cs
=> Test: Use named in-memory database for the test which requires clean database

src/Microsoft.EntityFrameworkCore/DbSet`.cs
Simple change to fix pluralisation issues on the XML comments of 2 `*Range` methods
=> Fix some pluralisation issues in method comments

src/Microsoft.EntityFrameworkCore/Infrastructure/CoreModelValidator.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyDiscoveryConvention.cs, test/Microsoft.EntityFrameworkCore.Tests/Metadata/Conventions/Internal/KeyDiscoveryConventionTest.cs, test/Microsoft.EntityFrameworkCore.Tests/ModelBuilderTest/NonRelationshipTestBase.cs
Rediscover primary key if the matched property is ignored.
Fixes #7377
=> Don't throw on referenced shadow primary key.

src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves issue #7271
part of #7520
=> Query: Refactor SearchConditionTranslatingVisitor

src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalForeignKeyAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational/Metadata/RelationalIndexAnnotations.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Microsoft.EntityFrameworkCore.SqlServer.Tests.csproj, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/TestSqlServerAnnotationProvider.cs
This will still result in a validation error if the conflicting name is configured by convention as in this case the uniquification would be dependent on the convention order.
Fixes #7082
=> [1.1.1] Uniquify FK and index names if there's another FK or index with the same name configured explicitly.

src/Microsoft.EntityFrameworkCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs, test/Microsoft.EntityFrameworkCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
- Adding a test for filter generation on the CreateIndexOperation
- Fixing code in CSharpMigrationOperationGenerator to wrap filter in ""
=> Fix filter generation in CSharpMigrationOperationGenerator

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/exceptions.net45.json, src/Microsoft.EntityFrameworkCore.Relational/exceptions.netcore.json, src/Microsoft.EntityFrameworkCore/Extensions/Internal/AsyncQueryProviderExtensions.cs, src/Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.csproj, src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryOptimizer.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves #7451 
For OfType operators of entity type remove the operator by changing the type of entityqueryable.
Move TypeIs to query model level optimization
=> Query: Optimize OfType operator to only query for required columns

test/Microsoft.EntityFrameworkCore.Relational.Tests/RelationalConnectionTest.cs
`DbConnection.Dispose()` calls `Close()` on .NET Standard 1.2 causing `CloseCount` to be `2` afterwards.
=> Make Lazy_connection_is_recreated_if_used_again_after_being_disposed more robust

src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Configuration/Internal/ModelConfiguration.cs, src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Internal/DbContextWriter.cs, src/Microsoft.EntityFrameworkCore.Design/Scaffolding/Internal/ScaffoldingServiceCollectionExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Infrastructure/IPluralizer.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Internal/NullPluralizer.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Metadata/Internal/ScaffoldingAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Metadata/Internal/ScaffoldingFullAnnotationNames.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Metadata/ScaffoldingEntityTypeAnnotations.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/Metadata/ScaffoldingMetadataExtensions.cs, src/Microsoft.EntityFrameworkCore.Relational.Design/RelationalScaffoldingModelFactory.cs, src/Microsoft.EntityFrameworkCore.SqlServer.Design/Internal/SqlServerScaffoldingModelFactory.cs, src/Microsoft.EntityFrameworkCore.Sqlite.Design/Internal/SqliteScaffoldingModelFactory.cs, test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/NullPluralizerTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/RelationalScaffoldingModelFactoryTest.cs, test/Microsoft.EntityFrameworkCore.Relational.Design.Tests/ScaffoldingMetadataExtenstionsTest.cs
Introduces a new IPluralizer service that is used to singularize entity type names and pluralize DbSet names. The default implementation is a no-op, so this is just a hook where folks can easily plug in their own pluralizer.
I left this separate from the existing CandidateNamingService, which is responsible for cleaning up the table name into a C# friendly identifier.
Here is what it looks like for a developer to hook in their own pluralizer (this example uses Inflector). Our code generation coverage is lacking, so I tested this against Northwind and verified by round tripping data.
```c#
public class MyDesignTimeServices : IDesignTimeServices
{
public void ConfigureDesignTimeServices(IServiceCollection services)
{
services.AddSingleton<IPluralizer, MyPluralizer>();
}
}
public class …
```
=> Add Pluralization Hook to Reverse Engineer

src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/ExistsExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/InExpression.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
- Introduce CompositeExpression to explicitly represent a set of various expressions
-----
More changes being split out of #7543. The immediate benefits are that further optimizations are applied to subqueries within `InExpression` and `ExistExpression`, and instead of using various odd means of representing a small collection of `Expression`s (such as `IReadOnlyCollection<Expression>` and `ConstantExpression` with an `Expression[]` value) we have an explicit expression type to represent that concept. 
In the longer term, `CompositeExpression` will gain a `Flatten` method which allows for more opportunities like complex/nested grouping keys and easier processing of complex/nested projections.
=> Implement VisitChildren for InExpression and ExistsExpression

src/Microsoft.EntityFrameworkCore.InMemory/Microsoft.EntityFrameworkCore.InMemory.csproj, src/Microsoft.EntityFrameworkCore.Relational.Design/Microsoft.EntityFrameworkCore.Relational.Design.csproj, src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/Microsoft.EntityFrameworkCore.Relational.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore.Relational/Microsoft.EntityFrameworkCore.Relational.csproj, src/Microsoft.EntityFrameworkCore.Specification.Tests/Microsoft.EntityFrameworkCore.Specification.Tests.csproj, src/Microsoft.EntityFrameworkCore.SqlServer/Microsoft.EntityFrameworkCore.SqlServer.csproj, src/Microsoft.EntityFrameworkCore.Sqlite/Microsoft.EntityFrameworkCore.Sqlite.csproj
Maybe caused by `dotnet migrate`, might be worth checking for a bug there.
=> Fix extra brackets in csproj

src/Microsoft.EntityFrameworkCore.SqlServer/Infrastructure/SqlServerEventId.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Infrastructure/SqlServerModelValidator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.Designer.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Properties/SqlServerStrings.resx, src/Microsoft.EntityFrameworkCore/Metadata/Conventions/Internal/KeyConvention.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/NorthwindQuerySqlServerFixture.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
Issue #7161
Byte properties are set to not be store-generated by convention, but if store-generation is configured, then SQL Server will use an identity column and a warning is issued in model validation.
Also a small fix to the warning for decimal properties to ensure that nullable decimals also get the warning if they have no explicit mapping.
=> Allow SQL Server identity columns for byte properties, but warn

src/Microsoft.EntityFrameworkCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
#7220 is working in current dev. Adding test.
Now it causes a subquery to be formed and `ProjectStarAlias` picks up table correctly.
Close #7220
=> Query: Add test for #7220

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs
Fix is to now produce SELECT [alias].* FROM ... for subqueries generated due to discriminator column being present in LOJ query, instead of listing all the columns individually.
=> Fix to #7689 - Query : improve SQL for queries with left join that generate subqueries due to discriminator predicate

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/Internal/IncludeExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Expressions/SelectExpression.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryNavigationsTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
- Use ProjectStarTable as default table when SelectExpression is unable to find table for querysource
- Change ProjectStarAlias to ProjectStarTable
- Don't bind with subquery when subquery has client side projection (fixes #7220)
- Set ProjectStarTable more correctly
The main issue here was:
We were trying to bind to subquery which had client side projection. We cannot bind directly to select expression in such case because client method can generate different result then what is returned by the query.
When similar client methods applied for Where/OrderBy, it should be able to bind but the issue arose was unable to find the correct table since we fell back to last table in subquery. The correct table would be table set by ProjectStarAlias which is set when we encounter QSRE in …
=> Query: Improve logic to find the correct table in the select expression

src/Microsoft.EntityFrameworkCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/AsyncQueryTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fixes #3792 
Aggregate over subquery generates invalid sql. For Max/Min/Average/Sum if the inner projection is a subquery (aka selectexpresion) then we force client eval.
=> Query: Translate aggregate functions to server only if not on subquery

src/Microsoft.EntityFrameworkCore.Relational/Query/RelationalQueryModelVisitor.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
Fixes minor issue in sub-query lifting.
=> Query: Relational: Allows subqueries with OrderBy and Offset to be lifted

src/Microsoft.EntityFrameworkCore/Extensions/Internal/AsyncQueryProviderExtensions.cs, src/Microsoft.EntityFrameworkCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/EntityQueryable`.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/NullAsyncQueryProvider.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryOptimizer.cs
Pull NullAsyncQueryProvider out into an internal singleton.
=> Query: Small refactoring to make it easier to create QueryModels.

src/Microsoft.EntityFrameworkCore.Specification.Tests/LoadTestBase.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/PropertyValuesTestBase.cs, src/Microsoft.EntityFrameworkCore/Internal/EntityFinder.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.Designer.cs, src/Microsoft.EntityFrameworkCore/Properties/CoreStrings.resx, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
Issue #7388
Throwing for Query method as well because it would lead to the same issues as using Load directly--that is, fixup would not happen. If we implement explicit loading for un-tracked entities in the future, then it is conceivable that we would make Query work using the same mechanism.
Also checked other places where operations might behave differently based on entity state and added some more tests for Reload.
=> Throw for attempt to load navigation property on un-tracked entity

src/Microsoft.EntityFrameworkCore/ChangeTracking/PropertyValues.cs
- Fixed typo on ToObject intellisense prompt. Changed "insatcne" to "instance"
=> Fixed typo on intellisense prompt for ToObject. corrected "instance"

src/Microsoft.EntityFrameworkCore.Design/Design/Internal/MigrationsOperations.cs
=> [1.0.4] Design: Only check for migrations assembly mismatch when modifying files

src/Microsoft.EntityFrameworkCore.Relational.Specification.Tests/MigrationsFixtureBase.cs, src/Microsoft.EntityFrameworkCore.Relational/Migrations/MigrationsSqlGenerator.cs, src/Microsoft.EntityFrameworkCore.SqlServer/Migrations/Internal/SqlServerMigrationsSqlGenerator.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
Resolves #6747
I found a few issues with this (it's more permissive than it should be with things after the statement), but it's more-or-less the same implementation as EF6, and nobody has reported them yet...
**Providers**: This PR is 99% SQL Server, but it also updates `MigrationsSqlGenerator` to stop tacking on a statement terminator (`;`) to the user's `.Sql()` calls. This will only have a functional impact if you've gone above and beyond the base implementation to add batching to Migrations.
@ErikEJ: You may want to support this in SQL CE too.
=> SQL Server Migrations: Handle GO and (Backslash) utilities statements

src/Microsoft.EntityFrameworkCore/Query/EntityQueryModelVisitor.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/ExpressionEqualityComparer.cs, src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs, test/Microsoft.EntityFrameworkCore.Relational.Tests/Microsoft.EntityFrameworkCore.Relational.Tests.csproj
=> More reflection reference equality comparison fixes

test/EFCore.Benchmarks/BenchmarkTestCase.cs, test/EFCore.Benchmarks/BenchmarkTestCaseBase.cs, test/EFCore.Benchmarks/NonCollectingBenchmarkTestCase.cs
The test case had a separate reference to the metric collector in
addition to the instance being added to the test method parameters. This
works fine until you serialize the test cases, as you end up with
separate references - one which the results are recorded in, and the
other that they are read from. The end result is reporting of zero
results. Serialization happens by default in the new MSBuild/csproj
project system (i.e. when you use the VS Test Runner or dotnet test).
There were two issues here. Test cases were creating a new metric
collector everytime they were created (i.e. they weren't
serialized/deserialized). Just fixing that wouldn't solve the problem
though, as serializing the refernce on the test case would have still
ended up with two separate instance on the test case and …
=> [SMALL] Fix metric collection when test runner serializes test case

appveyor.yml
EF is hogging the AppVeyor queue. It's builds take so long, and devs are not generally cancelling builds when they push new commits to a PR.
This will make running on AppVeyor opt-in. Add the word 'appveyor' to the commit message to run on AppVeyor.
=> Make appveyor builds opt-in

src/EFCore.Relational.Design/RelationalScaffoldingModelFactory.cs, test/EFCore.Relational.Design.Tests/RelationalScaffoldingModelFactoryTest.cs
Tested manually as there isn't really test coverage for any of this
As pointed out by @jwooley in https://github.com/aspnet/EntityFramework/pull/7634, I missed pluralizing collection navigation in the initial PR.
=> Reverse Engineer: Pluralize collection navigations

src/EFCore.Specification.Tests/QueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was in the in-memory portion of the test. We would execute 830 subqueries and that took the vast majority of the time. Fix is to introduce additional predicate, cutting the number of subqueries down to 4.
=> [TINY] Fix to #7864 - OrderBy_correlated_subquery_lol2 seems to be a very slow test

src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/ExpressionVisitorBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs, src/EFCore/Query/Internal/QueryModelExtensions.cs, src/EFCore/Query/QueryCompilationContext.cs
DRY up VisitSubQuery method
Use TransformingQueryModelExpressionVisitor instead of RecursiveQueryModelExpressionVisitor
=> Query: Improve ExpressionVisitorBase by making it recursive.

src/EFCore.Relational/Query/ExpressionVisitors/Internal/CompositeShaper.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/ProjectionShaper.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/Shaper.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
If we are projecting a simple QSRE then we can avoid introducing a ProjectionShaper.
=> Query: Small improvement to projection-shaper optimization

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was that in the fix for #7033 we force client evaluation on queries that try to bind to parents, when the parent has a client projection.
However, for the case when single element is returned (e.g. cusotmers.Select(c => new DTO { Count = c.Orders.Count() })) we don't need to do client evaluation.
We actually try to merge the subquery into the parent query, but this causes a problem because earlier in the pipeline we assumed that client eval is needed (since parent QM has client projection)
Fix is to be consistent and never try to lift subquery if the parent QM has a client projection. This causes more scenarios to produce N+1 queries, but the proper fix would require a breaking change:
we need additional information passed to the SqlTranslatingExpressionVisitor to know that the …
=> [1.1.2] Fix to #7714 - Invalid query produced when projecting DTO containing subquery that returns a single element

src/EFCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/LeftOuterJoinExpression.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/Expressions/TableExpressionBase.cs, src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/QueryNavigationsTestBase.cs, src/EFCore/Metadata/Internal/EntityMaterializerSource.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, src/EFCore/Query/Internal/QuerySourceExtensions.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was that for GroupJoin we would always force materialization on participating query sources.
We were doing this because we are not always able to correctly divide outer elements of the GroupJoin into correct groups.
However, if the GroupJoin clause is wrapped around SelectMany clause then groups don't matter because they are getting flattened by SelectMany anyway.
Fix is to recognize those scenarios and only force materialization when the correct grouping actually matters.
We can avoid materialization if the GroupJoin is followed by SelectMany clause (that references the grouping) and that the grouping itself is not present anywhere else in the query.
This addresses optional navigations, which is the 80% case. Manually created GroupJoins that are not modeling LeftOuterJoins still …
=> Fix to #6647 - Left Join (GroupJoin) always materializes elements resulting in unnecessary data pulling

src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs, test/EFCore.SqlServer.FunctionalTests/Properties/TestAssemblyConditions.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationsTest.cs, test/EFCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs, test/EFCore.SqlServer.FunctionalTests/config.json, test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs
* Remove the transient failure retry count limit in SqlServerDatabaseCreator.Exists so it's only limited by time (1 minute by default)
* Increase timeout used for creating SqlServer test databases to account for the increased delay when running in parallel.
* Speed up SqlServerDatabaseCreatorTest by decreasing the timeouts used
* Make SqlServer.FunctionalTests run in parallel
* Turn off SqlClient connection resiliency in tests
Fixes #7411
=> Fix SQL Server test timeouts

build/dependencies.props, src/EFCore.Design/EFCore.Design.csproj, src/EFCore.Relational.Design.Specification.Tests/EFCore.Relational.Design.Specification.Tests.csproj, src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj, src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj, src/EFCore.Sqlite/EFCore.Sqlite.csproj, src/EFCore/EFCore.csproj, src/dotnet-ef/dotnet-ef.csproj, test/EFCore.Benchmarks.EF6/EFCore.Benchmarks.EF6.csproj, test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj, test/EFCore.Benchmarks/EFCore.Benchmarks.csproj, test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj, test/EFCore.Design.Tests/EFCore.Design.Tests.csproj, test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj, test/EFCore.InMemory.Tests/EFCore.InMemory.Tests.csproj, test/EFCore.Relational.Design.Tests/EFCore.Relational.Design.Tests.csproj, test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj, test/EFCore.SqlServer.Design.FunctionalTests/EFCore.SqlServer.Design.FunctionalTests.csproj, test/EFCore.SqlServer.Design.Tests/EFCore.SqlServer.Design.Tests.csproj, test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj, test/EFCore.SqlServer.Tests/EFCore.SqlServer.Tests.csproj, test/EFCore.Sqlite.Design.FunctionalTests/EFCore.Sqlite.Design.FunctionalTests.csproj, test/EFCore.Sqlite.Design.Tests/EFCore.Sqlite.Design.Tests.csproj, test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj, test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj, test/EFCore.Tests/EFCore.Tests.csproj, test/dotnet-ef.Tests/dotnet-ef.Tests.csproj, test/ef.Tests/ef.Tests.csproj
Puts all dependency versions into one file. We're doing this to help ensure we are consistent in the package versions we use, and to make it easier for automation to update.
Also, removes Microsoft.DotNet.InternalAbstractions from the spec test projects. This package shouldn't be used anymore.
FYI - this is still using Roslyn 1.3.0. Latest RTM is 2.0.0. I left the dependency version as 1.3.0 in this PR.
=> Unify dependency versions to one file

appveyor.yml, build/repo.targets
This PR enables only SqlServer Functional Tests on AppVeyor. It takes about ~23 minutes for 1 run to finish.
Since we already had made groups of testsin #7842 this PR just run the group which travis cannot run.
Also had to change to SqlServer 2016 because for some reason SqlServer 2014 is not starting up in AppVeyor.
=> AppVeyor: Run only SqlServer FunctionalTests

tools/CleanMSSQLLocalDB.cmd, tools/ShrinkLocalDBModel.cmd
All research and testing done by @divega
`CleanMSSQLLocalDB.cmd` drops all databases and deletes the default instance. This is useful to quickly get to a clean state, it doesn't have any perf benefits.
`ShrinkLocalDBModel.cmd` runs `DBCC ShrinkDatabase (model)` several times as this was empirically proven to yield the smallest `model` file resulting in faster database creation.
Then it changes the growth amount for the `model` database to 10%, this is the default for non-system dbs.
To use this you need to have sqlcmd and SQLClient ODBC drivers installed:
* https://www.microsoft.com/en-us/download/details.aspx?id=53591
* https://www.microsoft.com/en-us/download/details.aspx?id=53339
On my machine it sped up the SQLServer FTs on .NET Core from 4 min to 2.5 min
=> Add scripts to clean and speedup the default LocalDB instance

src/EFCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore/Metadata/Internal/EntityMaterializerSource.cs, src/EFCore/Metadata/Internal/IEntityMaterializerSource.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
This enables better error messages in more cases when we hit a bad data exception.
=> Flow property metadata more often during query binding.

src/EFCore/EntityFrameworkQueryableExtensions.cs, test/EFCore.Tests/Extensions/QueryableExtensionsTest.cs
Resolves #7937 
Also verified that all other methods are coming from Queryable only so shouldn't need a check.
=> Query: Make AsTracking/AsNoTracking no-op for non-EF queries

test/EFCore.Benchmarks.EF6/EFCore.Benchmarks.EF6.csproj, test/EFCore.Benchmarks.EF6/InitializationTests.cs, test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj, test/EFCore.Benchmarks.EFCore/InitializationTests.cs, test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj, test/EFCore.Relational.Design.Tests/EFCore.Relational.Design.Tests.csproj, test/EFCore.SqlServer.Design.Tests/EFCore.SqlServer.Design.Tests.csproj, test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj, test/EFCore.Sqlite.Design.Tests/EFCore.Sqlite.Design.Tests.csproj, test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj, test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj
Disable failing tests in Benchmarks.EF6 cold variation.
@jbagga 
I will update issue #7998 with more details on skipped tests.
=> Add binding redirects to test projects after net46 upgrade

src/EFCore.Relational.Specification.Tests/RelationalQueryTestBase.cs, src/EFCore.Relational/Properties/RelationalStrings.Designer.cs, src/EFCore.Relational/Properties/RelationalStrings.resx, src/EFCore.Relational/Query/ExpressionTranslators/Internal/LikeTranslator.cs, src/EFCore.Relational/Query/ExpressionTranslators/RelationalCompositeMethodCallTranslator.cs, src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/LikeExpression.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Relational/RelationalDbFunctionsExtensions.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerCompositeMethodCallTranslator.cs, src/EFCore/DbFunctions.cs, src/EFCore/EF.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
To allow relational and providers to start defining extension methods on it, for #2850.
Hope this is more or less what you guys were thinking of, let me know of any nitpicks in terms of class/file naming etc.
Note that no actual methods (e.g. Like) are defined, that can come later in a separate PR.
=> Add EF.Functions and SQL Like

src/EFCore.Relational/Internal/RelationalDiagnostics.cs
Looks like a copy/paste oops here - the diagnostic name was incorrect.
I was trying to write an adapter per #7939 and wondered why this wasn't working. Turns out I wasn't the crazy one, *this time*...
Fixes item 1 in #8001.
=> Fix diagnostic name for RelationalDiagnostics.ConnectionError

src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj, src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj, test/EFCore.Benchmarks.EF6/InitializationTests.cs, test/EFCore.Benchmarks.EFCore/InitializationTests.cs, test/EFCore.Benchmarks/ColdStartSandbox.cs
Add net46 as tfm in test project for test driven
resolves #7998 
Also avoids exception while using testdriven to run tests.
Still cannot get dotnet-ef.Tests to be no-op in testdriven.
=> Re-enable disabled benchmark tests.

src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was that we were adding unnecessary condition when pruning EF.Property from the QuerySourceTracingExpressionVisitor.
Fix is to remove the check so that all the EF.Property calls will correctly be pruned.
=> [TINY] Fix to #8053 - Query: QuerySourceTracingExpressionVisitor doesn't always prune EF.Property expressions

src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringReplaceTranslator.cs
Resolves #8021 
Reference to correct overload: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/String.Manipulation.cs#L1146
There are 4 overloads for string.Replace now.
`string Replace(string oldValue, string newValue, bool ignoreCase, CultureInfo culture)`
`string Replace(string oldValue, string newValue, StringComparison comparisonType)`
`String Replace(char oldChar, char newChar)`
`String Replace(String oldValue, String newValue)`
=> Query: Update the resolution of string.Replace overload

src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore/Query/Internal/QueryOptimizer.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Problem was that during initial parsing of query model, Include, AsTracking, AsNoTracking force subqueries to be created (since they are result operators). Those operators are then removed, but the subqueries persist, making it much harder to translate queries efficiently. We try to prune "empty" subqueries, but sometimes it is safe to lift subqueries that contain body clauses.
Fix is to recognize those patterns and perform the lift during query model optimizations. We do it for cases when the subquery is coming from the MainFromClause, it doesn't contain any result operators and is projecting it's MainFromClause only in the selector.
The optimization is the most prominent for queries with Include but will help other cases also.
=> [SMALL] Fix to #6611 - Hundred of queries being ran. When calling OrderBy, then Include then Where to a one to many relationship

src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs, src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs, test/EFCore.Sqlite.FunctionalTests/BadDataSqliteTest.cs
Issue #6924
This makes services singletons based on:
- ILogger is now singleton
- There is only one database provider per container
=> Make more services singletons

src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
This scenario is now working. Added additional constraint to make the test faster (since it's client eval) and fixed baseline, which had a typo.
=> [TINY] fix to #6997 - enabling previously disabled test

src/EFCore/ChangeTracking/ChangeTracker.cs, src/EFCore/ChangeTracking/Internal/ChangeDetector.cs, src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs, src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs, src/EFCore/ChangeTracking/Internal/IStateManager.cs, src/EFCore/ChangeTracking/Internal/IValueGenerationManager.cs, src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/EFCore/ChangeTracking/Internal/NavigationFixer.cs, src/EFCore/ChangeTracking/Internal/StateManager.cs, src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs, src/EFCore/ChangeTracking/NavigationEntry.cs, src/EFCore/ChangeTracking/ReferenceEntry.cs, src/EFCore/ChangeTracking/ReferenceEntry`.cs, src/EFCore/DbContext.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs, test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs, test/EFCore.Tests/ChangeTracking/Internal/ShadowFkFixupTest.cs, test/EFCore.Tests/ChangeTracking/ReferenceEntryTest.cs, test/EFCore.Tests/DbContextTest.cs
Add ReferenceEntry.TargetEntry as a way to get entries for the delegated identity entities
If the navigation to owned entity is set to null the owned entity will be deleted
Changes in the inverse navigation from an owned type will be ignored as its meaning is ambiguous
=> Add change tracking support for delegated identity entity types

src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, src/EFCore/Query/Internal/EvaluatableExpressionFilter.cs, src/EFCore/Query/Internal/QueryCompiler.cs
Making ctor public, de-nesting class and making methods virtual.
=> Fixing extensibility blockers in QueryCompiler/ParameterExtractingExpressionVisitor

src/EFCore/Infrastructure/DatabaseFacade.cs
While working on a project on VS, I noticed that the comments had a slight typo.
- Added missing **_d_**
- Added comma, to break sentence up
=> Fix minor grammatical error

src/EFCore.Relational/Query/ExpressionVisitors/Internal/CompositePredicateExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/PredicateNegationExpressionOptimizer.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/RelationalNullsExpandingVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/RelationalNullsExpressionVisitorBase.cs, src/EFCore.Relational/Query/Expressions/NullCompensatedExpression.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/FunkyDataQueryTestBase.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerEndsWithOptimizedTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStartsWithOptimizedTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteEndsWithOptimizedTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStartsWithOptimizedTranslator.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Fix is to use more permanent translation:
property.StartsWith(pattern) => property LIKE pattern + '%' AND LEFT(property, LEN(pattern)) = pattern
Also fixed minor issue with null semantics where we would apply C# null semantics for comparisons to null-valued parameters
=> Fix to #7429 - StartsWith() filter slow with use of SQL CHARINDEX()

src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/Expressions/Internal/NullConditionalExpression.cs, src/EFCore/Query/Internal/ExpressionEqualityComparer.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTree.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs
Move from a list of include paths to a tree representation in preparation for making the compiler fully recursive.
=> Query: Include: Refactor to use tree data structure inside IncludeCompiler.

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/QueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves #8092 
The issue here was, the condition `_parameter == "code"` has parameter value as null, thus `NullComparisonTransformingVisitor` converted the condition to `false`. This condition was part of conditional expression in the order by clause, which produced incorrect SQL as 0.
The fix is to convert constantExpression in `BooleanExpressionTranslatingVisitor` to appropriate expression based on search condition. Since this change will convert `true` to `true == true` for search condition, which we don't want to print specifically for Where clause, moved that processing to `GeneratePredicate` (we need it for join conditions where join conditions are also search conditions.
Also kept the `Translate` method in visitor so we can easily pass the flag and reuse the same visitor.
=> Query: Process ConstantExpression in BooleanExpressionTranslatingVisitor

src/EFCore.InMemory/Query/ExpressionVisitors/Internal/InMemoryEntityQueryableExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore/Extensions/NavigationExtensions.cs, src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/EntityResultFindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/Query/QueryCompilationContext.cs, src/EFCore/Query/ResultOperatorHandler.cs, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs, src/EFCore/Query/ResultOperators/Internal/StringIncludeExpressionNode.cs, test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs, test/EFCore.Tests/ModelBuilderTest/ModelBuilderGenericTest.cs, test/EFCore.Tests/ModelBuilderTest/ModelBuilderNonGenericTest.cs, test/EFCore.Tests/ModelBuilderTest/ModelBuilderTestBase.cs, test/EFCore.Tests/ModelBuilderTest/OwnedTypesTestBase.cs
* Add QueryCompilationContext.QuerySourceEntityTypeMapping to keep track of the mapping from IQuerySource to IEntityType
* Change EntityQueryModelVisitor.IterateCompositePropertyExpression to propagate the IEntityType through navigations and rename it to MemberAccessBindingExpressionVisitor.GetPropertyPath
=> Add query support for delegated identity entity types

src/EFCore.Relational.Specification.Tests/TestUtilities/RelationalTestHelpers.cs, test/EFCore.Relational.Tests/TestUtilities/RelationalTestHelpers.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj, test/EFCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
Make AssertSql assert the ordering
Add AssertContainsSql which disregard ordering (due to .NET Core)
Add output to VS output window again
=> QueryTest: Update to AssertSql

src/EFCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs, test/EFCore.Sqlite.FunctionalTests/QuerySqliteTest.cs
Handle StarProjection expression better in PushDownSubquery
SelectExpression.BindSubqueryProjectionIndexToSelectExpression method which binds AnonymousObject index with correct projected expression
resolves #8131
=> Query: Remove unnecessary ExplodeStarProjection

src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs
Only Includes on GJ QSREs still use the old code path.
=> Query: IncludeCompiler: Enable full recursion in compiler!

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/InheritanceTestBase.cs, src/EFCore/Extensions/Internal/ExpressionExtensions.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs, src/EFCore/Query/ResultOperatorHandler.cs, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs
Resolves #7280
There were mainly 2 issues here
1. When marking source2 in set operation for materialization, we had exact type match. Which is not correct because `Concat<T>` can take parameter of derived type of `T`.
2. Since our shaped queries are transparent to cast result operator which are directly assignable, while forming `Concat<T>` we need to find the right type to use for `T` since we had swallowed it earlier.
=> Query: Allow set operations to work after casting

src/EFCore.Tools/tools/EntityFrameworkCore.psd1, src/EFCore.Tools/tools/EntityFrameworkCore.psm1
This is the PowerShell version of #7948
Fixes #7889
=> [tools/1.0.1] PMC Tools: Use project's runtime framework version

src/EFCore.Relational/Query/ExpressionTranslators/ParameterlessInstanceMethodCallTranslator.cs, src/EFCore.Relational/Query/ExpressionTranslators/SingleOverloadStaticMethodCallTranslator.cs, src/EFCore.Specification.Tests/QueryTestBase.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateAddTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerMathTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringReplaceTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringSubstringTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimEndTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimStartTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringTrimEndTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringTrimStartTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringTrimTranslator.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Problem was that the way we extract MethodInfos for translators was always deterministic and could lead to errors if the new overloads of those methods were to be added.
Fix is to use pattern in which we fully specify the name and types of all arguments to the method - this is guaranteed to be unique.
=> Fix to #8060 - Query: Make our reflection info selection logic deterministic

src/EFCore.Specification.Tests/FieldMappingTestBase.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationSubqueryInjector.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Problem was that when translating collection navigation outside projection we assumed it's always going to be wrapped in a subquery.
This is the case for the most part because in order to be useful inside a query, collection needs to have it's cardinality reduced to single element using a result operator (Count, Any, FirstOrDefault etc), which forces subquery on the collection.
However it is also possible to use client method, which takes collection and returns single element. For this case, subquery won't be generated and we were unable to translate such query.
Fix is to inject subqueries where needed, using same mechanism we use in case of projection. Client method forces materialization on the collection, so it's safe to use.
=> Fix to #6383 - The wrong type is being selected when an extension method is used in a subquery

src/EFCore.Specification.Tests/TestModels/ComplexNavigationsModel/ComplexNavigationsModelInitializer.cs
Before we were executing 2 queries when preparing the model, which made it tedious for debugging.
=> [TINY] Improving test model initializer for ComplexNavigations, so that it doesn't execute any queries.

src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore.Specification.Tests/QueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
DTO which are projected out, (from any level) are materialized correctly with typed projection shaper
Store member bindings for MemberInitExpression to allow binding after DTO projection
Resolves #7234
=> Query: Allow translations through DTO objects

src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Problem was in the optimization that compared navigation to null, specifically:
o.Customer == null => c.CustomerId == null
If we detected that this optimization could be performed, we assumed that the navigation [o.Customer] is no longer needed, and it was being removed from the navigation joins list.
However, if that navigation was also used for another nav access, then it should not have been removed.
Fix is to add counter to the NavigationJoins list, and only remove given navigation join from the list, if it's not referenced anywhere else in the query.
Also removed some dead code and fixed an issue where we would not apply:
c == o.Customer => c.Id == o.CustomerId
if CustomerId was optional (i.e. clr type was different than the PK on the other side)
=> Fix to #7207 - Query: compilation error for queries with navigations that also compare same navigation to null

src/EFCore.Specification.Tests/QueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Resolves #6353 
This is probably fixed by #7950  in which we removed a lot of restrictions on translation of expression. So we can actually build is null for subquery perhaps.
=> Add test for subquery null comparison translated correctly

src/EFCore.Specification.Tests/QueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
Add test for set operation followed group by not translating correctly Issue #6658
**This PR does not fix the issue**
We were checking for type matching when marking set operations for materialization. That should not be required as compiler would make sure that types are compatible.
=> Query: Update materialization marking for set operations

src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Specification.Tests/QueryTestBase.cs, src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
Distinct clears ordering and in the presence of limit it can create incorrect results.
Add counter in RowNumberPagingExpressionVisitor because for a multi level nested subquery, inner subquery can provide column with RowNumber while we are adding it on outer level which causes name clash for a subquery
Counter make sure to unique-fy them for given select expression.
Moved the visitor to constructor
Resolves #7525
=> Pushdown subquery when applying distinct in presence of limit

src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/InheritanceRelationshipsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
Unique-fy the code to create uniquely aliased projection for subquery. (which was being used in AddToProjection & PushDownSubquery). This removes CreateUniqueProjectionAlias and introduces method CreateUniqueProjection which makes the projection alias unique (and replaces it in projection & order by)
Side effect of above is, for pushdownsubquery, we don't use ColumnAliasPrefix for new name. Instead we will unique-fy current column name.
=> DRY code to unique-fy the projection expression

src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs, test/EFCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
Log any Includes left over at end of compilation.
=> Query: Include: Log ignored Include warnings properly in new compiler.

src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs
Resolves #8204 
This introduces aliases when they are not needed therefore, other parts of SelectExpression should use alias only and inner expression of alias should only be visited during projection.
Changes to baseline are submitted in separate in commit for read-ability.  (and coming soon)
=> Query: Use member name for alias for anonymous/DTO projection

src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/TestUtilities/ExpectedInclude.cs, src/EFCore.Specification.Tests/TestUtilities/IExpectedInclude.cs, src/EFCore.Specification.Tests/TestUtilities/QueryResultAsserter.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
- added verification for include queries that does deep comparison, while taking into account specified expected includes,
- added verification for single result queries.
=> Improving verification for ComplexNavigationTests so that it no longer relies on running product code to create expected results

src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs, src/EFCore/Storage/ExecutionStrategy.cs, test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs, test/EFCore.SqlServer.FunctionalTests/Utilities/TestSqlServerConnection.cs, test/EFCore.SqlServer.FunctionalTests/Utilities/TestSqlServerRetryingExecutionStrategy.cs, test/EFCore.SqlServer.Tests/Storage/SqlServerRetryingExecutionStrategyTests.cs, test/EFCore.Tests/Storage/ExecutionStrategyTests.cs
=> Increase max retry count default value to 6 so that we cover 1 full minute

src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs, test/EFCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
Problem was that when we tried to extract navigation paths specified in the Include we would throw if the Include was on non-entity type.
Fix is to log a warning for this case, just like we do for cases where included entity is not reachable in the final result.
We will still throw exception if user specifies incorrect navigation on existing entity.
=> [SMALL] Fix to #7516 - Query: Compiler crash for invalid Include path

src/EFCore/Infrastructure/CoreModelValidator.cs, test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
Allow shadow PKs created by convention (which will happen only for DIET)
Throw for shadow alternate key created by convention which is principal end of relationship
Resolves #7238
=> Allow shadow keys created explicitly

src/EFCore.Specification.Tests/IncludeTestBase.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryLoggingSqlServerTest.cs
Instead of ignoring includes that are not specified directly on entity type we throw NotSupportedException
=> [TINY] Modification to fix for #7516 - Query: Compiler crash for invalid Include path

build/repo.props, test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj, test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj, test/EFCore.Design.Tests/EFCore.Design.Tests.csproj, test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj, test/EFCore.InMemory.Tests/EFCore.InMemory.Tests.csproj, test/EFCore.Relational.Design.Tests/EFCore.Relational.Design.Tests.csproj, test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj, test/EFCore.SqlServer.Design.FunctionalTests/EFCore.SqlServer.Design.FunctionalTests.csproj, test/EFCore.SqlServer.Design.Tests/EFCore.SqlServer.Design.Tests.csproj, test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj, test/EFCore.SqlServer.Tests/EFCore.SqlServer.Tests.csproj, test/EFCore.Sqlite.Design.FunctionalTests/EFCore.Sqlite.Design.FunctionalTests.csproj, test/EFCore.Sqlite.Design.Tests/EFCore.Sqlite.Design.Tests.csproj, test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj, test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj, test/EFCore.Tests/EFCore.Tests.csproj, test/ef.Tests/ef.Tests.csproj
fixes #8337 
`build.cmd /p:CoreOnly=True` <10 mins run time on my machine 😀
=> CoreOnly build

src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/EntityResultFindingExpressionVisitor.cs, test/EFCore.InMemory.FunctionalTests/QueryBugsInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryBugsTest.cs
- Don't track entities which are being passed in constructor to DTO
- Stop storing sql expression for member info which cannot be bound later
`new Entity(args)` produces `NewExpression` with members null and args as arguments. 
`new Entity(args) { Prop = value }` creates `MemberInitExpression` with member bindings for properties assigned and `NewExpression` for ctor initialization.
`new { Prop = value }` creates `NewExpression` with members being constructed from property assignments. For memberExpression, memberInfo will be added by implicit reference.
Changes:
- Do not store MemberInfo->SqlExpression when members == null which (nominal type with ctor) since you cannot bind with the nominal type. (even if member info matches in which case it can be incorrect too based on what is ctor …
=> Don't track entities which are being passed in constructor to DTO

src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore/Query/Internal/QueryModelPrinter.cs, src/EFCore/Query/Internal/QueryOptimizer.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Problem was that during optimization, when we flatten subqueries we didn't account for Cast result operator properly. This would fail when trying to access a property on a derived type, when derived type was coming from a subquery with Cast result operator.
Fix is to wrap qsres to that (former) subquery with Convert(s) the subquery was casted into.
Also fixed another issue around this area:
We tried to lift Distinct in some cases, which could lead to incorrect results. E.g
from outer in (ctx.Customers.Distinct())
select outer.Name
would get translated to:
(from outer in ctx.Customers
select outer.Name).Distinct()
=> [SMALL] Fix to #3736 - Query :: some queries with Queryable.Cast<T> don't work

src/EFCore.Relational.Specification.Tests/WarningsTestBase.cs, src/EFCore.Relational/Query/ExpressionTranslators/Internal/EqualsTranslator.cs, src/EFCore.Specification.Tests/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/QueryTestBase.cs, src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs, src/EFCore/Infrastructure/CoreEventId.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsOwnedQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/WarningsSqlServerTest.cs
Also fixes (smaller in scope) #5825 - Query: Comparing collection navigation to NULL throws Null Exception
Problem was that we were not taking into account queries where collection navigation was being compared to null and/or each other. This would cause various exceptions during query compilation.
Some of the common cases can be simplified, making them much easier for the query compiler (i.e. navigation rewrite) to process.
When it comes to null comparison, we assume that collection navigation is only null if its parent entity is null, so we can actually just compare the parent entity to null instead
e.g.: customer.Orders == null ---> customer == null ---> customer.Id == null
However, it's possible that user wanted to check whether collection has any elements - we will issue a warning …
=> Fix to #8364 - Query: comparing collection navigations to null or to each other doesn't work

src/EFCore.Specification.Tests/IncludeAsyncTestBase.cs
I was able to get hang process like appVeyor in SqlServer.FunctionalTests inside a VM. Debugging into VM this is the test which seems to cause the hang. Disabling it to verify if there are more reasons.
=> [AppVeyor] Skip test causing hang

test/EFCore.SqlServer.FunctionalTests/MemoryOptimizedTablesTest.cs, test/EFCore.SqlServer.FunctionalTests/Utilities/SqlServerTestStore.cs
`context.Database.EnsureDeleted()` fails in the test because we pass opened connection from SqlServerTestStore. & connection uses SQL Auth so when we try to connect to master for delete, it does not contain password and log in failure is caused.
=> Fix test issue on SqlServer2016 with SqlServer Authentication

src/EFCore.Specification.Tests/QueryTestBase.cs
It works now because we use SDK 2.0 & Specification.Tests target netcoreapp2.0
Resolves #6803
=> Re-Enable testing Convert.ToString on netcoreapp2.0

appveyor.yml, build/repo.props
~~It hangs most times
Our appveyor build has been unreliable recently because net46 hangs while running sqlserver.functionaltests. Since it is not appveyor we are not able to find the root cause of hang (perhaps in MSBuild or test runner, I may have repro in a VM which got stuck at similar point).~~
~~While the underlying issue is resolved out we should disable testing offending assembly.
Testing if netcoreapp2.0 is working fine (by skipping net46 with new CoreOnly switch). If possible I may add specific project disabling.~~
The issue for hang #8384  which was disabled in #8383 So we no longer have hangs.
PR #8382 Fixed issue with test which used SQL Auth on SqlServer 2016. This enable SqlServer 2016 specific tests.
PR #8377  Removed appdomains for net46 testing which cut down build time …
=> Enable full build on AppVeyor with SQL Server 2016 settings

src/EFCore.Sqlite/EFCore.Sqlite.csproj, src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.csproj, src/EFCore.Tools/EFCore.Tools.csproj
Suppress producing \*.symbols.nupkg files for packages that don't include build output.
=> Suppress symbols nupkgs for metapackages

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Initial problem was that when translating anonymous type we change the expression type from the anonymous type to Expression[].
In case of conditional expression, if the second result is null constant, it's type stays the same, and when we try to update ConditionalExpression, type mismatch is thrown.
However, even if the types are compensated for, we can't translate NewExpression to SQL, apart from it being used in comparison (e.g. in composite key join scenarios)
Fix is to recognize the pattern and force client eval.
Also fixes small bug around alias generation.
=> Fix to #8315 - Argument types don't match for queries projecting conditional expression with anonymous type result

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs
Resolves #8304 
The issue is marked with 1.1.3
Should I create new branch?
=> Query: Add parenthesis when expanding InExpression with null values

src/EFCore.Relational/Query/Expressions/ColumnExpression.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsOwnedQuerySqlServerTest.cs
=> Query: Adds simple redundant SelectExpression join elimination.

src/EFCore.Relational/Diagnostics/CommandData.cs, src/EFCore.Relational/Diagnostics/CommandEndData.cs, src/EFCore.Relational/Diagnostics/CommandErrorData.cs, src/EFCore.Relational/Diagnostics/CommandExecutedData.cs, src/EFCore.Relational/Diagnostics/ConnectionData.cs, src/EFCore.Relational/Diagnostics/ConnectionEndData.cs, src/EFCore.Relational/Diagnostics/ConnectionErrorData.cs, src/EFCore.Relational/Diagnostics/DataReaderDisposingData.cs, src/EFCore.Relational/Diagnostics/TransactionData.cs, src/EFCore.Relational/Diagnostics/TransactionEndData.cs, src/EFCore.Relational/Diagnostics/TransactionErrorData.cs, src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs, src/EFCore.Relational/Storage/Internal/RelationalCommand.cs, src/EFCore.Relational/Storage/RelationalConnection.cs, src/EFCore.Relational/Storage/RelationalDataReader.cs, src/EFCore.Relational/Storage/RelationalTransaction.cs
Start capturing event start time (DateTimeOffset.UtcNow) and switch duration to TimeSpan.
- Aligns with AppInsights APIs and is generally just easier to use and more useful.
=> Diagnostics - Reworks timing infrastructure

src/EFCore.Relational.Specification.Tests/FromSqlQueryTestBase.cs, src/EFCore.Relational/Query/ResultOperators/Internal/FromSqlExpressionNode.cs, src/EFCore.Relational/RelationalQueryableExtensions.cs, src/EFCore.Relational/breakingchanges.netcore.json, src/EFCore.Relational/breakingchanges.netframework.json, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs
Interpolated variables are parameterized and queries are cached in the usual way.
=> Query: FromSql: Adds support for interpolated strings!

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/QueryNavigationsTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, src/EFCore/Query/Expressions/Internal/NullConditionalEqualExpression.cs, src/EFCore/Query/Internal/ExpressionEqualityComparer.cs, src/EFCore/Query/Internal/ExpressionPrinter.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
Problem was happening for InMemory queries with optional navigation and collection navigation, e.g.:
from e in entities
where e.Optional.Collection.Where(predicate)
select e
those would get rewritten into:
from e in entities
join o in optionals on e.Id equals o.EntityId into grouping
from o in grouping.DefaultIfEmpty()
where o.Collection.Where(predicate)
select e
and then:
from e in entities
join o in optionals on e.Id equals o.EntityId into grouping
from o in grouping.DefaultIfEmpty()
join c in collections
where o.Id == c.OptionalId && predicate
select e
Problem was that o could be null (because of the optional navigation), which would result in NRE for InMemory.
We could add null compensation on the o.Id, but then null semantics would kick in for relational producing the following …
=> Fix to #7787 - Query: NullConditional is not added to some complex queries with optional navigation and collection with subquery

src/EFCore.Specification.Tests/QueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/DefaultQueryExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/Expressions/Internal/NullConditionalExpression.cs, src/EFCore/Query/Internal/ExpressionPrinter.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs
We don't need Caller and NullableCaller, removing one of them.
=> [SMALL] Remove unnecessary argument (nullable caller) to the NullConditionalExpression

build/dependencies.props, src/EFCore.Relational.Design.Specification.Tests/EFCore.Relational.Design.Specification.Tests.csproj, src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj, src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj, test/EFCore.ApplicationInsights.Tests/EFCore.ApplicationInsights.Tests.csproj, test/EFCore.Benchmarks.EF6/EFCore.Benchmarks.EF6.csproj, test/EFCore.Benchmarks.EFCore/EFCore.Benchmarks.EFCore.csproj, test/EFCore.Benchmarks/EFCore.Benchmarks.csproj, test/EFCore.CrossStore.FunctionalTests/EFCore.CrossStore.FunctionalTests.csproj, test/EFCore.Design.Tests/EFCore.Design.Tests.csproj, test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj, test/EFCore.InMemory.Tests/EFCore.InMemory.Tests.csproj, test/EFCore.Relational.Design.Tests/EFCore.Relational.Design.Tests.csproj, test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj, test/EFCore.SqlServer.Design.FunctionalTests/EFCore.SqlServer.Design.FunctionalTests.csproj, test/EFCore.SqlServer.Design.Tests/EFCore.SqlServer.Design.Tests.csproj, test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj, test/EFCore.SqlServer.Tests/EFCore.SqlServer.Tests.csproj, test/EFCore.Sqlite.Design.FunctionalTests/EFCore.Sqlite.Design.FunctionalTests.csproj, test/EFCore.Sqlite.Design.Tests/EFCore.Sqlite.Design.Tests.csproj, test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj, test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj, test/EFCore.Tests/EFCore.Tests.csproj, test/dotnet-ef.Tests/dotnet-ef.Tests.csproj, test/ef.Tests/ef.Tests.csproj
Part of https://github.com/aspnet/Coherence-Signed/issues/497
Upgrade xunit.runner.visualstudio to 2.3.0 and Microsoft.NET.Test.Sdk to 15.3.0.
Unlike the rest of aspnet repos, I have not updated the xunit runtime version which remains at 2.2.0. Xunit 2.3.0 includes xunit.analyzers which threw thousands of errors for EF. We can't move foward to to xunit 2.3.0 until https://github.com/dotnet/sdk/issues/1212 is resolved (can't exclude analyzers from PackageRef's), or until the test code is updated to satisfy the analyzer.
=> Upgrade xunit.runner.visualstudio and vstest.console version

src/EFCore.Relational/Query/AsyncQueryMethodProvider.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/IdentityShaper.cs, src/EFCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/EFCore.Relational/Query/Internal/IValueBufferCursor.cs, src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs, src/EFCore.Relational/Query/QueryMethodProvider.cs, src/EFCore.Specification.Tests/AsyncQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/FilterApplyingExpressionVisitor.cs, src/EFCore/Query/Internal/AsyncLinqOperatorProvider.cs, src/EFCore/Query/Internal/IParameterValues.cs, src/EFCore/Query/QueryContext.cs, test/EFCore.SqlServer.FunctionalTests/AsyncQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
- Fixes a race in async ShapedQuery execution.
- Optimizes ShapedQuery by pushing down shaper to inner enumerable.
- Removes IValueBufferCursor.Current - no longer used.
=> Query: Testing out a fix for #8393

src/EFCore.Specification.Tests/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs
Problem was that navigation inside inner key selector of a JoinClause was always being rewritten to subquery (needed for #3103). However, we should only be doing this for "naked" navs - if the nav itself is inside a subquery it can be safely rewritten into a join.
Fix is to "reset" the state indicating whether we are inside join inner key selector every time we visit SubQuery.
=> [TINY] Fix to #8216 - Query: navigation rewrite fails for queries with navigation inside a subquery inside join inner key selector

src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs, src/EFCore.Design/Design/Internal/DbContextOperations.cs, test/EFCore.Design.Tests/Design/Internal/AppServiceProviderFactoryTest.cs, test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs, test/EFCore.Design.Tests/TestUtilities/TestAppServiceProviderFactory.cs, test/EFCore.Design.Tests/TestUtilities/TestDbContextOperations.cs, test/EFCore.Design.Tests/TestUtilities/TestWebHost.cs
=> Design: Use Program.BuildWebHost to discover DbContext types

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore/Extensions/Internal/ExpressionExtensions.cs, src/EFCore/Query/ExpressionVisitors/Internal/ConditionalOptimizingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/EFCore/Query/Internal/QueryOptimizer.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Moving some of the null conditional check optimization to QueryOptimizer.
QM expressions containing patterns like:
entity != null ? entity.Property : null
get converted to:
entity?.Property
Optimization on Query Model level is limited to member access, EF.Property and TypeAs
Optimization during SQL translation additionally handles all method calls and binary expressions (except equality)
This allows us to optimize more cases (e.g. composite keys) and overall simplifies query models.
Also improved null protection translation:
- we were incorrectly simplifying equality binary operations - those are not safe to translate because of null semantics
Also fixed small bug in binding where we would not protect from unexpectedly accessing null value from ValueBuffer in NullConditionals with Convert …
=> Fix to #8385 - Query: inefficient translation of null protection logic for InMemory and some cases of relational

src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs, src/EFCore/ChangeTracking/ChangeTracker.cs, src/EFCore/ChangeTracking/EntityEntry.cs, src/EFCore/ChangeTracking/NavigationEntry.cs, src/EFCore/DbContext.cs, src/EFCore/Extensions/Internal/DbContextDependenciesExtensions.cs, src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs, src/EFCore/Internal/DbContextDependencies.cs, src/EFCore/Internal/EntityFinder.cs, src/EFCore/Internal/IDbContextDependencies.cs, src/EFCore/Internal/InternalDbSet.cs, src/EFCore/Query/QueryContextDependencies.cs, test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs, test/EFCore.Tests/DbContextTest.cs
Issue #8440
Reverts an unintentional breaking change created by adding another implementation of Infrastructure. The fix is to make DbContext explicitly implement IDbContextDependencies. The exposed services are still "hidden" and all documented as internal.
=> Allow context.GetInfrastructure() with generic inference to work again

src/EFCore.Design/Design/Internal/DatabaseOperations.cs, src/EFCore.Design/Scaffolding/Configuration/Internal/CustomConfiguration.cs, src/EFCore.Design/Scaffolding/Configuration/Internal/EntityConfiguration.cs, src/EFCore.Design/Scaffolding/Configuration/Internal/PropertyConfiguration.cs, src/EFCore.Design/Scaffolding/Internal/ConfigurationFactory.cs, src/EFCore.Design/Scaffolding/Internal/DbContextWriter.cs, src/EFCore.Design/Scaffolding/Internal/EntityTypeWriter.cs, src/EFCore.Design/Scaffolding/Internal/ReverseEngineeringConfiguration.cs, src/EFCore.Design/Scaffolding/Internal/ReverseEngineeringGenerator.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteAllFluentApiE2ETest.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteAttributesInsteadOfFluentApiE2ETest.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
=> Negate UseFluentApiOnly and make parameter UseDataAnnotations

src/EFCore.InMemory/Extensions/InMemoryDatabaseFacadeExtensions.cs, src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs, src/EFCore.SqlServer/Extensions/SqlServerDatabaseFacadeExtensions.cs, src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsExtensions.cs, src/EFCore.Sqlite.Core/SqliteDatabaseFacadeExtensions.cs, src/EFCore.Sqlite.Core/SqliteDbContextOptionsBuilderExtensions.cs, src/EFCore/Infrastructure/DatabaseFacade.cs, test/EFCore.InMemory.Tests/InMemoryDatabaseFacadeTest.cs, test/EFCore.SqlServer.Tests/SqlServerDatabaseFacadeTest.cs, test/EFCore.Sqlite.Tests/SqliteDatabaseFacadeTest.cs
Part of #7166
Main scenario here is conditional behavior in OnModelCreating now that we build a different model per provider.
=> Add sugar for determining the database provider in use

src/EFCore.Design/Design/Internal/DbContextOperations.cs, src/EFCore.Relational.Design.Specification.Tests/DesignTimeProviderServicesTest.cs, src/EFCore.SqlServer.Design/Internal/SqlServerDesignTimeServices.cs, src/EFCore.SqlServer/Properties/AssemblyInfo.cs, src/EFCore.Sqlite.Core/Properties/AssemblyInfo.cs, src/EFCore.Sqlite.Design/Internal/SqliteDesignTimeServices.cs, src/EFCore/Design/DesignTimeProviderServicesAttribute.cs, src/EFCore/Design/IDesignTimeDbContextFactory.cs, src/EFCore/Design/IDesignTimeServices.cs, src/EFCore/Infrastructure/DbContextFactoryOptions.cs, src/EFCore/breakingchanges.netcore.json, src/EFCore/breakingchanges.netframework.json
This namespace (in Microsoft.EntityFrameworkCore.dll) includes the following hooks that applications and providers can use to influence the design-time experience.
* `[DesignTimeProviderServices]`--assembly-level attribute providers use to point to their design-time services
* `IDesignTimeDbContextFactory`--implemented by applications to instantiate their DbContext at design time (resolves #8499)
* `IDesignTimeServices`--implemented by providers and applications to add or replace design-time services
Fixes #8553
=> Introduce Microsoft.EntityFrameworkCore.Design namespace into the runtime

build/dependencies.props, src/EFCore.Design/EFCore.Design.csproj, src/EFCore.Relational/EFCore.Relational.csproj, src/EFCore.SqlServer/EFCore.SqlServer.csproj
These packages won't be shipping in the 2.0 wave, but are still required when targeting 1.x.
=> Downgrade to valid package versions

src/EFCore.Specification.Tests/NorthwindQueryFixtureBase.cs, src/EFCore/Infrastructure/CoreOptionsExtension.cs, src/EFCore/Internal/DiagnosticsLogger.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.InMemory.FunctionalTests/WarningsTest.cs, test/EFCore.SqlServer.FunctionalTests/NorthwindQuerySqlServerFixture.cs
Issue #8398
The warning is now configured to throw by default. Some of our tests intentionally create queries that have includes that will be ignored, so we switch back to Log for those tests.
=> Throw error on ignored includes

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, src/EFCore.SqlServer/breakingchanges.netcore.json, src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs, src/EFCore.Sqlite.Core/breakingchanges.netcore.json
Because they need to be inherited from in order to implement custom operations.
=> API review: Move provider-specific SQL generator classes back to public

src/EFCore.Specification.Tests/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/SubQueryMemberPushDownExpressionVisitor.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs
Problem was that we were performing subquery member pushdown incorrectly in some cases, e.g. when subquery had Distinct result operator:
from Level1 l1 in DbSet<Level1>
select
(from Level3 l3 in DbSet<Level3>
select [l3])
.Distinct()
.FirstOrDefault().Name
previously we were translating this into:
from Level1 l1 in DbSet<Level1>
select
(from Level3 l3 in DbSet<Level3>
select [l3].Name)
.Distinct()
.FirstOrDefault()
Fix is to introduce a subquery, if Distinct result operator is present in a subquery:
from Level1 l1 in DbSet<Level1>
select
(from subquery in (from Level3 l3 in DbSet<Level3>
select [l3])
.Distinct()
select [subquery].Name)
.FirstOrDefault()
Also added tests for a number of issues discovered when fixing this one
=> Fix to #8505 - Query: SubQueryMemberPushDown optimization is too aggressive, which may lead to invalid sql or data corruption

src/EFCore.Relational/Storage/RelationalTypeMapping.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerConvertTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerDateTimeDateComponentTranslator.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
Changed to use SqlFragmentExpression so we can directly specify the argument to SQL Server CONVERT.
Also, discussed with @divega and @smotpatel and changed the types for decimal and string from decimal and nvarchar to decimal(18, 2) and nvarchar(max) respectively. Note decimal(18, 2) is not perfect, but nothing is.
Issue #8609
=> Remove RelationalTypeMapping.GenerateLiteral(DbType)

src/EFCore.Relational/Storage/IRelationalCommand.cs, src/EFCore.Relational/Storage/Internal/RelationalCommand.cs, src/EFCore.Relational/breakingchanges.netcore.json, src/EFCore/EntityFrameworkQueryableExtensions.cs, src/EFCore/Metadata/INavigation.cs, src/EFCore/Metadata/IProperty.cs, src/EFCore/Metadata/IPropertyBase.cs, src/EFCore/Metadata/Internal/PropertyBase.cs, src/EFCore/breakingchanges.netcore.json, test/EFCore.SqlServer.FunctionalTests/Utilities/TestRelationalCommandBuilderFactory.cs, test/EFCore.SqlServer.Tests/SqlServerDatabaseCreatorTest.cs, test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs
These things were made obsolete for binary compat in 1.1 releases. They can now be removed.
Issue #8490
=> Removing obsolete members

src/EFCore.Relational/breakingchanges.netcore.json, src/EFCore/Infrastructure/AccessorExtensions.cs, test/EFCore.Tests/DbContextTest.cs
Issue #7185
This makes it easier for applications that are using AddDbContext to get access to services registered on the container that was used for AddDbContext.
=> Make context.GetService<> fallback to the app service provider

src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs, test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs, test/EFCore.Relational.Tests/Utilities/RelationalLoggerExtensionsTest.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/CompiledQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/FiltersSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/FromSqlQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/FromSqlSprocQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/InheritanceSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryBugsTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/RowNumberPagingTest.cs, test/EFCore.SqlServer.FunctionalTests/SqlExecutorSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs, test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
Issue #8456
We previously used a different format for parameter logging in our tests when compared to product code logging. Now we use the same format everywhere. This change updates the product format back to what it was, and updates the test baselines to reflect this.
=> Revert back to parameter logging format from v1 and update test baselines

src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs, src/EFCore.Relational/Storage/Internal/INamedConnectionStringResolver.cs, src/EFCore.Relational/Storage/Internal/NamedConnectionStringResolver.cs, src/EFCore.Relational/Storage/RelationalConnection.cs, src/EFCore.Relational/Storage/RelationalConnectionDependencies.cs, test/EFCore.Relational.Tests/Storage/NamedConnectionStringResolverTest.cs, test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs, test/EFCore.SqlServer.FunctionalTests/ConnectionSpecificationTest.cs, test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs
Issue #7185
This change allows code like this:
```C#
.AddDbContext<MyContect>(
b => b.UseSqlServer("name=ConnectionStrings:DefaultConnection"))
```
Assuming the IConfiguration is found in the same service provider as AddDbContext is used on, then this will find "ConnectionStrings:DefaultConnection" and use it as the connection string.
Should work for all relational providers.
=> Support named connection strings when IConfiguration is in the app service provider

src/EFCore.ApplicationInsights/DiagnosticEventForwarder.cs, src/EFCore.Design/Scaffolding/Internal/ScaffoldingServiceCollectionExtensions.cs, src/EFCore/DbLoggerCategory.cs, src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs, test/EFCore.Tests/Infrastructure/DiagnosticsLoggerTest.cs
To better align with other category Name properties.
=> Rename DbLoggerCategory.Root to DbLoggerCategory.Name

src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
=> Throw if the FK properties set by the convention are ambiguous in the hierarchy.

src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
=> Throw when a property is made optional if it's contained in a key created explicitly.

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs, src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs
Adding to the exclusion list since they cannot be serialized.
=> Ignore TypeMapping annotations when generating model snapshot

src/EFCore/Metadata/Internal/ForeignKey.cs, src/EFCore/Metadata/Internal/Property.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs, test/EFCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs, test/EFCore.Tests/Metadata/Internal/PropertyTest.cs
=> Don't throw when defining an FK in a derived type on a property contained in a key if the property is not value generated

src/EFCore/Extensions/MutableEntityTypeExtensions.cs
I believe that @ajcvickers made these remarks obsolete/nonsensical when he removed the "shadow" parameter in https://github.com/aspnet/EntityFramework/commit/847a2668125beba73878cef683922be6b2e81cad, but that he missed these remarks in his adjustment of the docs.
=> Remove obsolete remarks about forcing shadowness

src/EFCore.Specification.Tests/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/QueryNavigationsTestBase.cs, src/EFCore/Metadata/Internal/ClrICollectionAccessor.cs, src/EFCore/Metadata/Internal/IClrCollectionAccessor.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationIncludeExpressionRewriter.cs, src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationSubqueryInjector.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/QueryCompilationContext.cs, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs, test/EFCore.SqlServer.FunctionalTests/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/QueryNavigationsSqlServerTest.cs
Currently when projecting collection navigation we produce N+1 queries. This change leverages include pipeline which produces 2 queries instead and joins the result on the client.
We only do this for collection navigation that are not composed on - otherwise, the query that happens after collection navigation would be performed on the client, so it's not clear that would be preferable to N+1.
Also as a side effect, we always materialize root entity (or all intermediate entities in case of multi-level navigation). This is a side effect of reusing Include pipeline, which always expects (and depends on) root element being materialized.
We leverage the include pipeline by performing a simple QM rewrite:
```
from [e] in entities
select new { [e].Id, [e].Reference.Collection }
```
will be …
=> Fix to #8584 - Query: reuse include pipeline for queries projecting uncomposed collection navigations

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs, src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs, src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs, src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs, src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/EFCore/ChangeTracking/Internal/NavigationFixer.cs, src/EFCore/Metadata/Conventions/Internal/CascadeDeleteConvention.cs, src/EFCore/Metadata/DeleteBehavior.cs, src/EFCore/Metadata/Internal/ForeignKey.cs, src/EFCore/breakingchanges.netcore.json, test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SqlServerReverseEngineerTestE2EContext.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/AttributesContext.cs, test/EFCore.SqlServer.FunctionalTests/GraphUpdatesWithIdentitySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GraphUpdatesWithRestrictSqlServerTest.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/FkToAltKey/FkToAltKeyContext.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/OneToOne/OneToOneFluentApiContext.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/FkToAltKey/FkToAltKeyContext.cs, test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/OneToOne/OneToOneAttributesContext.cs, test/EFCore.Tests/Metadata/Conventions/Internal/CascadeDeleteConventionTest.cs, test/EFCore.Tests/Metadata/Internal/ForeignKeyTest.cs, test/EFCore.Tests/Metadata/Internal/InternalRelationshipBuilderTest.cs, test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
Issues #8654, #8632, #8633
The new behavior is called 'ClientSetNull'.
'Restrict' now throws on SaveChanges if EF would have set null. This is the same behavior that has always been there for required relationships, so this is only a break for optional relationships explicitly configured with Restrict, which should be relatively rare since this was the default anyway. The default is now 'ClientSetNull', which matches the old behavior of 'Restrict', so apps that were not setting anything explicitly will not get a breaking change.
=> Add a hybrid OnDelete behavior that does SetNull in the StateManager and Restrict in the database

src/EFCore.Design/Internal/DesignLoggerExtensions.cs, src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs, src/EFCore.Specification.Tests/TestHelpers.cs, src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs, src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.resx, src/EFCore.Sqlite.Core/Internal/SqliteLoggerExtensions.cs
This means if the message is in "Scaffolding", then it is tested to not generate DiagnosticSource events.
All other events are tested to be doing DiagnosticSource messages using nominal types.
Issue #7939
=> Stop generating DiagnosticSource events for purely design-time messages

src/EFCore.Relational/Diagnostics/DataReaderDisposingEventData.cs, src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs, src/EFCore.Relational/Migrations/HistoryRepository.cs, src/EFCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs, src/EFCore.Relational/Storage/RelationalDataReader.cs, src/EFCore.Relational/Update/AffectedCountModificationCommandBatch.cs, src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs, src/EFCore.Relational/breakingchanges.netcore.json, test/EFCore.Sqlite.FunctionalTests/BadDataSqliteTest.cs
- Track DbDataReader.Read/Async invocation count via new delegating methods on RelationalDataReader.
=> Fix #8197 - Diagnostics: Report number of rows returned by server on reader dispose

build/common.props
- Property is automatically set by Internal.AspNetCore.Sdk
=> Remove TreatWarningsAsErrors from common.props

src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs, test/EFCore.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs
=> Don't use a temporary table for batching inserts.

src/EFCore.Specification.Tests/ComplexNavigationsOwnedQueryTestBase.cs
=> Ignore Entity_equality_empty for owned ETs, as it's not supported

build/repo.targets
Usage: build.cmd /p:TestFilter=InMemory would run only tests whose folder names contain InMemory
Resolves #8679 
`build.cmd /p:TestFilter=Functional`
=> Add `TestFilter` property on build.cmd to allow selective test runs

src/EFCore/ChangeTracking/LocalView.cs, src/EFCore/DbContext.cs, src/EFCore/Internal/DbContextDependencies.cs, src/EFCore/Internal/DbSetInitializer.cs, src/EFCore/Internal/EntityFinder.cs, src/EFCore/Internal/IDbContextDependencies.cs, src/EFCore/Internal/IDbSetCache.cs, test/EFCore.Tests/DbSetTest.cs, test/EFCore.Tests/Infrastructure/EntityFrameworkServicesBuilderTest.cs
Issue #8144
I don't think that there is any issue not un-registering the listeners, since LocalView objects always have the same lifetime as the underlying context. I added checks so that the LocalView will throw if it is being used with a disposed context.
=> Cache DbSet objects to prevent memory leaks when DbSets cache local views

src/EFCore.Relational/ValueGeneration/RelationalValueGeneratorSelector.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs, test/EFCore.SqlServer.Tests/SqlServerValueGeneratorSelectorTest.cs
Otherwise we just send the generated key to the database.
Issue #8239
=> Generate temp values for string, Guid, and binary key properties if column has default SQL

src/EFCore/Query/Internal/QueryBuffer.cs
Unable to repro so far, but it looks like there are some cases where {_includedCollections.Keys} != {0.._includedCollections.Count - 1}
This change just removes that assumption during Dispose.
=> Issue #8817 - "Given key was not present in the dictionary" after migration to 2.0

src/EFCore.SqlServer/Infrastructure/Internal/SqlServerOptionsExtension.cs, src/EFCore/Infrastructure/CoreOptionsExtension.cs, test/EFCore.SqlServer.Tests/SqlServerOptionsExtensionTest.cs
=> Changing RowNumberPaging should cause new internal service provider to be built

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.ResultOperators.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.Select.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.ResultOperators.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.Select.cs
Problem was for queries with value types being projected in a select expression when also using convert. The problem was that getValue is typed as object which then was converted to an expected type. However if the value returned by SQL was not exactly the same type, exception would get thrown due to boxing/unboxing.
Fix is to detect when we apply convert on a top level projection, and in this case use explicit cast, so that type returned by SQL was exactly the same as the type that was expected after unboxing.
Also added support for translating Negate expression, which was previously evaluated on the client.
=> Fix to #8652 - InvalidCastException when casting from one value type to another in a simple select statement

src/EFCore.Design/Design/DbContextActivator.cs, src/EFCore.Design/Design/IOperationReportHandler.cs, src/EFCore.Design/Design/Internal/OperationReporter.cs, test/EFCore.Design.Tests/Design/DbContextActivatorTest.cs
Resolves #7050 
cc @prafullbhosale
=> Design: Enable instantiating DbContext types at design time

src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/Query/OneToOneQueryFixtureBase.cs, src/EFCore.Specification.Tests/Query/OwnedQueryFixtureBase.cs, src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs, src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/EFCore/Metadata/Conventions/Internal/NavigationEagerLoadingConvention.cs, src/EFCore/Metadata/IMutableNavigation.cs, src/EFCore/Metadata/INavigation.cs, src/EFCore/Metadata/Internal/ForeignKey.cs, src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/EFCore/Metadata/Internal/Navigation.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/breakingchanges.netcore.json, test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryFixture.cs, test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/PropertyEntrySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerFixture.cs, test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/AutoincrementTest.cs, test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteFixture.cs, test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs
- Adds INavigation.IsEager - navs can now be marked as eager by-default (core metadata only).
- Adds a core convention that sets IsEager=true for principal-to-dependent navs when FK.IsOwnership=true.
- Updates the query compiler to auto-synthesize Include trees for owned navs on result QSREs.
- Adds a new query test suite for testing queries involving ownership.
=> Fix #8843 - Automatic eager loading of owned types.

src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs, src/EFCore.Relational/Metadata/Conventions/Internal/RelationalConventionSetBuilder.cs, src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs, src/EFCore.Relational/Metadata/Internal/RelationalPropertyBuilderAnnotations.cs, src/EFCore.Specification.Tests/TestHelpers.cs, src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs, test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs, test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs, test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipStringTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeStringTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericUnqualifiedStringTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs, test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Use the provider model validator in the ModelBuilding tests
Fix and refactor RelationalModelValidator.ValidateSharedTableCompatibility
Fixes #7240
=> Uniquify column names for types sharing a table

src/EFCore.Specification.Tests/Query/CompiledQueryTestBase.cs, src/EFCore/EF.CompileQuery.cs, test/EFCore.SqlServer.FunctionalTests/Query/CompiledQuerySqlServerTest.cs
- Added overloads of CompileQuery that resolve for queries returning IIncludableQueryable.
=> Fix #8884 - CompileQuery throws if query ends in Include

.travis.yml
#8642 happens a lot on osx to decrease the value of travis to us. We can re-enable it once we fix the issue.
=> Disable travis testing on Mac OS

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Relational/Storage/IRelationalParameter.cs, src/EFCore.Relational/Storage/IRelationalParameterBuilder.cs, src/EFCore.Relational/Storage/Internal/DynamicRelationalParameter.cs, src/EFCore.Relational/Storage/Internal/RawRelationalParameter.cs, src/EFCore.Relational/Storage/Internal/RelationalCommand.cs, src/EFCore.Relational/Storage/Internal/RelationalParameterBase.cs, src/EFCore.Relational/Storage/Internal/RelationalParameterBuilder.cs, src/EFCore.Relational/Storage/Internal/TypeMappedRelationalParameter.cs, src/EFCore.Relational/Storage/RelationalCommandBuilderExtensions.cs, src/EFCore.Relational/breakingchanges.netcore.json, test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Resolves #8721 
TODO:
@anpete - Creating PR to get initial feedback on the approach.
=> Query: Allow FromSql to accept parameter of type DbParameter in subquery

src/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs, src/EFCore.Relational/Storage/Internal/RawSqlCommandBuilder.cs, test/EFCore.SqlServer.FunctionalTests/Query/SqlExecutorSqlServerTest.cs
=> Query: Allow more patterns of parameters on ExecuteSqlCommand

src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs, src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs, src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/E2E.sql, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SqlServerReverseEngineerTestE2EContext.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/AttributesContext.cs, test/EFCore.SqlServer.Design.FunctionalTests/SqlServerDatabaseModelFactoryTest.cs
Resolves #8687 
Rules followed 
- If PK is marked as "CLUSTERED" don't do anything. That is default behavior for SqlServer.
- If some other index/unique constraint is marked as clustered then output `ForSqlServerIsClustered()` for index. PK will be non clustered by default.
- If PK is marked as "NONCLUSTERED" and there is no other Clustered index then we explicitly output `ForSqlServerIsClustered(false)` on PK.
=> RevEng: Scaffold ForSqlServerIsClustered correctly for PK/Index

src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/QueryCompilationContext.cs, src/EFCore/breakingchanges.netcore.json
- Simplified the whole thing. QueryAnnotations is IReadOnlyCollection and AddAnnotations method remains.
=> Fix #8944 - Change QueryCompilationContext.QueryAnnotations to ICollection

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs, test/EFCore.Tests/ChangeTracking/Internal/NavigationFixerTest.cs
Issue #8101
Happens when entities are inconsistently fixed up and do shenanigans in setters. (May also happen in other scenarios, but I was able to repro it this way.) Fix is to do defensive copy.
=> Prevent Collection was modified; enumeration operation may not execute.

src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/Query/Internal/QueryModelExtensions.cs, test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs
When GroupBy is in play we need to ensure we use ElementSelector and not SelectClause.Selector as the output expression.
=> Query: Fix bug in IncludeCompiler where we would resolve an incorrect QSRE for grouped results.

src/EFCore.Relational/Extensions/RelationalExecutionStrategyExtensions.cs, src/EFCore/DbContext.cs, src/EFCore/Extensions/ExecutionStrategyExtensions.cs, src/EFCore/Storage/ExecutionStrategy.cs, src/EFCore/Storage/IExecutionStrategy.cs
Issue #7012
Text is copied from the documentation for the exception types.
Also checked that there are no other custom exception types used at runtime that do not have similar documentation. All other exceptions indicate a program/logic error, not a recoverable state, and use built-in exception types.
=> Add exception documentation for SaveChanges

src/EFCore.Specification.Tests/Query/QueryTestBase.Functions.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimEndTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimStartTranslator.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerStringTrimTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringTrimEndTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringTrimStartTranslator.cs, src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringTrimTranslator.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.Functions.cs, test/EFCore.Sqlite.FunctionalTests/Query/QuerySqliteTest.cs
=> Query: Translate new overloads of Trim/TrimStart/TrimEnd in netcoreapp2.0

src/EFCore.Specification.Tests/Query/QueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
Tweaked parameterizer to detect and handle this particular case of queryable composition.
=> Fix #7783 - Calling IQueryable-producing methods inside expression tree throws exception when outer is enumerated

src/EFCore.Relational/Query/Internal/ShaperCommandContext.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.cs
- Found an edge case where we can extract different parameters during parameterization but end up with a single query in query cache.
=> Fix #7863 - Somehow a mismatch in the ShapedCommandContext entries resulting in KeyNotFoundException

src/EFCore.Relational/Diagnostics/RelationalEventId.cs, src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs, src/EFCore.Relational/Properties/RelationalStrings.Designer.cs, src/EFCore.Relational/Properties/RelationalStrings.resx, src/EFCore.Relational/Query/AsyncQueryMethodProvider.cs, src/EFCore.Relational/Query/ExpressionVisitors/Internal/ResultTransformingExpressionVisitor.cs, src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Relational/Query/QueryMethodProvider.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.ResultOperators.cs, src/EFCore/Diagnostics/ExpressionEventData.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.ResultOperators.cs
Max, Min and Average should throw "Sequence contains no elements" when there was no data returned and the result type is non-nullable. Updated relational result operator handling to do that.
- Added a warning for the subquery throwing case.
=> Fix #7901 - Max(), Min(), etc. do not differentiate between no results and zero

src/EFCore/ChangeTracking/LocalView.cs, src/EFCore/Query/Internal/EntityQueryable`.cs, test/EFCore.Tests/DbSetTest.cs
=> Implement IListSource on LocalView and EntityQueryable to further direct data binding

src/EFCore/EntityFrameworkServiceCollectionExtensions.cs, test/EFCore.Tests/DbContextTest.cs
Issue #8797
After going back and forth on this I settled on:
* Register DbContextOptions as scoped by default
* This allows scoped services to be used in AddDbContext
* This allows scoped services to be resolved from context.GetService
* It will still work fine if scoped services are not needed
* Add another parameter to AddDbContext to allow the options to be registered as Singleton if needed
* This can be used for apps that are doing some heavy lifting in AddDbContext
=> Allow scoped application services to be accessed from the context

src/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs, src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs, src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs, src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/EFCore.Relational/Metadata/RelationalPropertyExtensions.cs, src/EFCore.Relational/Properties/RelationalStrings.Designer.cs, src/EFCore.Relational/Properties/RelationalStrings.resx, src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs, src/EFCore.Relational/Update/Internal/ModificationCommandIdentityMap.cs, src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/CombustionEngine.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/Engine.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/FuelTank.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/LicensedOperator.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/Operator.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/PoweredVehicle.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs, src/EFCore.Specification.Tests/TestModels/TransportationModel/Vehicle.cs, src/EFCore/Metadata/Internal/KeyExtensions.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs, test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/TableSplittingSqlServerTest.cs, test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/TableSplittingSqliteTest.cs
Make the columns nullable for dependent types involved in table splitting.
When uniquifying column names use the declaring entity type name as prefix.
Fixes #8907
=> Fix table splitting for derived types in the update pipeline.

src/EFCore.InMemory/Infrastructure/Internal/InMemoryOptionsExtension.cs, src/EFCore.Relational.Specification.Tests/LoggingRelationalTest.cs, src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs, src/EFCore.Specification.Tests/LoggingTestBase.cs, src/EFCore.Specification.Tests/TestUtilities/ListLogger.cs, src/EFCore.Specification.Tests/TestUtilities/ListLoggerFactory.cs, src/EFCore.SqlServer/Infrastructure/Internal/SqlServerOptionsExtension.cs, src/EFCore.Sqlite.Core/Infrastructure/Internal/SqliteOptionsExtension.cs, src/EFCore/DbContext.cs, src/EFCore/Diagnostics/ContextInitializedEventData.cs, src/EFCore/Diagnostics/CoreEventId.cs, src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs, src/EFCore/Infrastructure/CoreOptionsExtension.cs, src/EFCore/Infrastructure/IDbContextOptionsExtension.cs, src/EFCore/Internal/DbContextDependencies.cs, src/EFCore/Internal/IDbContextDependencies.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, src/EFCore/breakingchanges.netcore.json, test/EFCore.InMemory.FunctionalTests/LoggingInMemoryTest.cs, test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs, test/EFCore.Relational.Tests/Storage/RelationalTransactionExtensionsTest.cs, test/EFCore.SqlServer.FunctionalTests/LoggingSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/LoggingSqliteTest.cs, test/EFCore.Tests/DbContextOptionsTest.cs, test/EFCore.Tests/DbContextTest.cs, test/EFCore.Tests/Infrastructure/CoreEventIdTest.cs, test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs, test/EFCore.Tests/ServiceProviderCacheTest.cs
Issue #8893
Message is logged on context initialization and looks something like:
Entity Framework Core 2.0.0-preview3 initialized 'LoggingContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: NoTracking
Only options that are both non-default and simple to log are included. Providers get to participate.
=> Log a message with EF version information

src/EFCore/ChangeTracking/Internal/NavigationFixer.cs, src/EFCore/ChangeTracking/PropertyEntry`.cs, test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
If the FK was non-identifying make sure the properties are set to null instead of the dependent being removed.
Fixes #8137
=> Make sure the old dependent is removed when the new one is reference stealing using navigations and/or FK properties

build/dependencies.props, src/EFCore/EFCore.csproj
This is a reaction to our Mirror build soon picking up a new version of DiagnosticSource.
=> DiagnosticSource to 4.4.1

src/EFCore.Specification.Tests/FindTestBase.cs, src/EFCore/Internal/EntityFinder.cs, test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs
Issue #8189
The problem was with overly aggressive validation of arguments.
=> Make DbSet.Find() work for nullable value types

src/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
Issue #9039
Navigation properties do not have defined order, so test should not rely on it.
=> Fix test ordering issue

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs, src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs, test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
For operations (`CREATE INDEX`, `ALTER COLUMN`, etc.) on memory-optimized tables, the backing model is now used to determine if it's for a memory-optimized table. This prevents unnecessary differences on non-table artifacts. For memory-optimized tables created out of band (i.e. without a backing entity type), you can manually add the `SqlServer:MemoryOptimized` annotation to get the appropriate behavior.
Fixes #6887
=> SqlServer Migrations: Clean up memory-optimized table mechanics

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Relational/Storage/DoubleTypeMapping.cs, src/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.Functions.cs, test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteFixture.cs, test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
Resolve #8259 Self-contained type mappings so no more binding errors since we have mapping for every clr type.
Resolves https://github.com/aspnet/EntityFramework/issues/8270
After much discussion with @bricelam we ended up with
float -> Use `ToString("R")` which is roundtrip-able. 
double -> R faces issue on x64 so docs suggest using "G17"
Removed "E0" suffix for relational provider.
Resolves https://github.com/aspnet/EntityFramework/issues/8905
float in SqlServer -> Always cast to real while generating literal
double in SqlServer -> if the literal does not have E then append E0 (to make it double literal)
Since Long literals are used in migrations too we cannot cast them always. It has to be done based on functions in query.
=> Improve literal generation for various types

src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs, src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
Issue #8319
Behavior for EF Core is that navs on deleted entities are not cleared/nulled out. This avoid graph shredding when deleting partial graphs.
=> Stop removing entities from collection nav props when entity is deleted

src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqliteTest.cs
Problem was that for queries with owned types that were using GroupJoin-SelectMany-DefaultIfEmpty pattern we were not able to find the owned entity type behind the groupjoin subquery qsre.
Usually (i.e. in case of navigations) we look for the entity type in the lookup on QueryCompilationContext, but if the groupjoin is created manually then this lookup was not populated with entry for the groupjoin subquery.
Fix is to populate the lookup with entry for groupjoin subquery qsre. We do it in nav rewrite, which also populates other entries for owned types.
=> Fix to #8492 - Query: incorrect sql generated for query with owned entities, left join and predicate using inner qsre

src/EFCore.Relational/Query/ExpressionTranslators/SingleOverloadStaticMethodCallTranslator.cs
The class `SingleOverloadStaticMethodTranslator` is supposed to find matching method which does not have any other overload but it was never meant to be parameter less. This regression was introduced in 11dd5f60028a70329946dfe07409bbb4094c95a3
=> Query: SingleOverloadStaticMethod can have parameters

src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs, src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs, src/EFCore.Design/Migrations/Design/MigrationsScaffolderDependencies.cs, src/EFCore.Design/Migrations/Internal/ISnapshotModelProcessor.cs, src/EFCore.Design/Migrations/Internal/SnapshotModelProcessor.cs, src/EFCore.Design/Properties/DesignStrings.Designer.cs, src/EFCore.Design/Properties/DesignStrings.resx, test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs, test/EFCore.Design.Tests/Migrations/Design/SnapshotModelProcessorTest.cs
Issue #8925
Currently relies on the model elements from the snapshot being mutable, but API could return a new IModel instead if this ever becomes not true.
=> Post-process the snapshot model to remove/combine legacy provider-specific annotations

src/dotnet-ef/Project.cs
=> [TINY] CLI Tools: Ensure MSBuildProjectExtensionsPath exists

src/EFCore.Design/Design/Internal/ContextInfo.cs, src/EFCore.Design/Design/Internal/DbContextOperations.cs, src/EFCore.Design/Design/OperationExecutor.cs, src/EFCore.Tools/tools/EntityFrameworkCore.PowerShell2.psd1, src/EFCore.Tools/tools/EntityFrameworkCore.PowerShell2.psm1, src/EFCore.Tools/tools/EntityFrameworkCore.psd1, src/EFCore.Tools/tools/EntityFrameworkCore.psm1, src/EFCore.Tools/tools/about_EntityFrameworkCore.help.txt, src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs, src/EFCore/Extensions/Internal/DbContextOptionsExtensions.cs, src/ef/Commands/DbContextInfoCommand.cs, src/ef/Properties/Resources.Designer.cs, src/ef/Properties/Resources.resx, test/ef.Tests/SimpleProjectTest.cs
Enhances `dotnet ef dbcontext info` command and adds Get-DbContext.
The following information is available:
- Provider name
- Database server (was already on CLI)
- Database name (was already on CLI)
- DbContextOptions (reuses the Logging format)
Resolves #9052
Example PMC usage:
```
PM> Get-DbContext | Format-List
providerName : Microsoft.EntityFrameworkCore.Sqlite
databaseName : main
dataSource   : ConsoleApp1.db
options      : SuppressForeignKeyEnforcement NoTracking
```
@ajcvickers @divega Should we take this in 2.0.0 or wait?
=> Tools: More DbContext info

src/EFCore.Design/Design/OperationExecutor.cs, src/EFCore.Design/baseline.netcore.json, src/EFCore.Design/baseline.netframework.json, src/ef/IOperationExecutor.cs, src/ef/OperationExecutorBase.cs, test/ef.Tests/SimpleProjectTest.cs
@vijayrkn Publish just calls `dotnet ef`, right? You don't use this?
=> [2.0.0] Design: Remove OperationExecutor.GetContextType

build/dependencies.props, src/EFCore/EFCore.csproj
* `System.Collections.Immutable` version `1.4.0` will ship with .NET Core 2.0 RTM
=> Update ImmutableCollectionsVersion to 1.4.0-*

src/EFCore/EntityFrameworkServiceCollectionExtensions.cs
Because we now redirect ILoggerFactory in a slightly different way it means that this is not needed when not using an ASP.NET application. When using an ASP.NET application you will get whatever filtering, etc, was setup for ASP.NET. This is different from 1.1 and may be confusing, but doesn't seem unreasonable.
Issue #9192
=> Revert setting default log level

src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that when processing include collection we clone the query model, which changes references of the individual query sources inside. In case of owned types we rely on the references to determine which entity type corresponds with a given query source (using a dictionary).
However, after cloning we were not populating the dictionary with the additional entries, so the owned types corresponding to those clones query sources could not be found.
Fix is to populate the QuerySourceEntityTypeMapping with entries for the cloned query sources - like we do in other places.
=> [2.0.0] Fix to #9202 - Query: Exception when using Include on collection navigation for models also containing owned types

test/EFCore.CrossStore.FunctionalTests/EndToEndTest.cs, test/EFCore.CrossStore.FunctionalTests/TestModels/CrossStoreContext.cs, test/EFCore.InMemory.FunctionalTests/ShadowStateUpdateTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/MappingQuerySqliteFixture.cs
Mostly removes model builder workarounds that have since been fixed.
Also removes some tests no longer necessary since we have per-provider models.
=> Migrations Tests: Cleanup

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Problem was that try to optimize conditionals with logical iftrue/iffalse but the logic around but the logic was not robust enough. We can return null from Invert(...) method which throws the exception seen here, and then that null result is used to construct the Expression, which throws the error.
Fix is to also apply Invert for null comparison (which is a separate node, and not only comparison expressions), as well as only try to apply the optimization if the Invert returns a valid result (i.e. not null)
=> [SMALL] Fix to #9223 - Query: ArgumentNullException when using ternary operator with null comparison in the test expression

src/EFCore.Specification.Tests/Query/AsyncQueryNavigationsTestBase.cs, src/EFCore.Specification.Tests/Query/AsyncQueryTestBase.cs, src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs, src/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.JoinGroupJoin.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs, src/EFCore.Specification.Tests/TestHelpers.cs, src/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.Objects.cs, src/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs, src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs, src/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs, test/EFCore.InMemory.FunctionalTests/Query/AsyncSimpleQueryInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs, test/EFCore.Sqlite.FunctionalTests/Query/AsyncSimpleQuerySqliteTest.cs
- creating AsyncQueryTestBase with all the async helper methods,
- adapting ResultAsserter to support async calls,
- removing static NorthwindData, since it's no longer used
=> Converting async query tests to use AssertQuery verification infrastructure

src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
SqlServerRetryingExecutionStrategy allows parameter errorsNumbersToAdd to be null which the method EnableRetryOnFailure in SqlServerDbContextOptionsBuilder do not.
=> Allow errorNumbersToAdd to be null

benchmarks/EFCore.Benchmarks.EF6/ChangeTracker/DbSetOperationTests.cs, benchmarks/EFCore.Benchmarks.EF6/ChangeTracker/FixupTests.cs, benchmarks/EFCore.Benchmarks.EF6/InitializationTests.cs, benchmarks/EFCore.Benchmarks.EF6/Program.cs, benchmarks/EFCore.Benchmarks.EF6/Properties/AssemblyInfo.cs, benchmarks/EFCore.Benchmarks.EF6/Query/FuncletizationTests.cs, benchmarks/EFCore.Benchmarks.EF6/Query/NavigationsQueryTests.cs, benchmarks/EFCore.Benchmarks.EF6/Query/QueryCompilationTests.cs, benchmarks/EFCore.Benchmarks.EF6/Query/RawSqlQueryTests.cs, benchmarks/EFCore.Benchmarks.EF6/Query/SimpleQueryTests.cs, benchmarks/EFCore.Benchmarks.EF6/SingleRunBenchmarkJobAttribute.cs, benchmarks/EFCore.Benchmarks.EF6/UpdatePipeline/SimpleUpdatePipelineTests.cs, benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/DbSetOperationTests.cs, benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/FixupTests.cs, benchmarks/EFCore.Benchmarks.EFCore1/Program.cs, benchmarks/EFCore.Benchmarks.EFCore1/UpdatePipeline/SimpleUpdatePipelineTests.cs, benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/DbSetOperationTests.cs, benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/FixupTests.cs, benchmarks/EFCore.Benchmarks.EFCore2/Program.cs, benchmarks/EFCore.Benchmarks.EFCore2/UpdatePipeline/SimpleUpdatePipelineTests.cs, benchmarks/EFCore.Benchmarks/ColdStartSandbox.cs, test/EFCore.Benchmarks.EFCore/ChangeTracker/DbSetOperationTests.cs, test/EFCore.Benchmarks.EFCore/ChangeTracker/FixupTests.cs, test/EFCore.Benchmarks.EFCore/Program.cs, test/EFCore.Benchmarks.EFCore/UpdatePipeline/SimpleUpdatePipelineTests.cs
AutoDetectChanges=true is super slow on EF6. Running those 8 mins tests for multiple iterations causes timeouts.
Resolves #9304
=> Benchmarks: Limit no. of runs for slow running benchmarks on EF6

src/EFCore.Relational/Storage/Internal/RelationalCommand.cs, src/EFCore.Relational/Storage/RelationalDataReader.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Resolves #9277 
Issue: For #6249 which allows query with FromSql be called twice, we start clearing out `DbCommand.Parameters` collection so same DbParameters can be used in another command. Though we cleared out Parameters after creating the reader assuming we wouldn't need parameters after command is executed. But for out parameters value is not set until DbReader is disposed. 
Solution: We should clear out Parameters right before disposing the Command. That makes sure that reader is not open/undisposed and still can reuse the parameter with another command.
This blocks reusing the same parameter till first command is disposed. But behavior of that with out parameter would be weird.
=> Clear DbCommand.Parameters only after reader is disposed

benchmarks/EFCore.Benchmarks.EF6/ChangeTracker/FixupTests.cs, benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/FixupTests.cs, benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/FixupTests.cs, benchmarks/EFCore.Benchmarks/BenchmarkSummaryProcessor.cs, test/EFCore.Benchmarks.EFCore/ChangeTracker/FixupTests.cs
Find the type running benchmark correctly when benchmark method is on base type
Escape output in teamcity
=> Benchmarks: Update FixUpTests to create new data every iteration

src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.csproj, src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.nuspec, src/EFCore.Tools/EFCore.Tools.csproj, src/EFCore.Tools/EFCore.Tools.nuspec
The aspnet/Universe repo-to-repo build graph tool doesn't correctly identify usages of EF's tools packages because NuGet reports their package ID incorrectly. This moves the package id in the csproj so the graph analyzer can detect any downstream usages of these packages.
=> Add PackageId to tools csproj 

src/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs, src/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs, test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs, test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs, test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs, test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/FromSqlSprocQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/IncludeOneToOneSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/MappingQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/WarningsSqlServerTest.cs, test/EFCore.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs, test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/MappingQuerySqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs, test/EFCore.Tests/Utilities/IndentedStringBuilderTest.cs
Uses `ignoreLineEndingDifferences` on `Equal` and `Environment.NewLine` with `StartsWith`, `Contains` & `EndsWith`.
Fixes #9147
=> Test: Update EOL pattern

src/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs, src/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs, src/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs, src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/Internal/AsyncLinqOperatorProvider.cs, src/EFCore/Query/Internal/LinqOperatorProvider.cs, src/EFCore/Query/ResultOperatorHandler.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
Issue: Single result async queries create the inner enumerator before the outer enumerator is created. If the outer enumerator isn't created and disposed (e.g. due to an exception) the inner enumerator isn't disposed
Fix: Don't create the inner enumerator until the outer enumerator is created
Fixes #9074
=> Reliably close readers when running single result async queries

src/Microsoft.EntityFrameworkCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/Microsoft.EntityFrameworkCore.Specification.Tests/QueryTestBase.cs, test/Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests/QuerySqlServerTest.cs
When we try to bind to parent query model we keep track of the current model output data info. However when recursive binding is required (i.e. binding to grandparent) we were not storing the output data of the parent, but still using the output data info of the child. This caused problems when the parent output data info doesn't allow for the binding to its parent - we would still try to perform the binding because we took the incorrect output data info into account.
Fix is to store the correct output data info in the variable before recursively trying to call TryBindParentExpression.
=> [1.1.3] Fix to #8862 - The multi-part identifier "ts.Id" could not be bound

.gitignore, src/EFCore.Specification.Tests/Query/AsyncQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/TaskBlockingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/ProjectionExpressionVisitor.cs, test/EFCore.InMemory.FunctionalTests/Query/AsyncQueryInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncQuerySqlServerTest.cs
Removes blocking by making async projections fully async even when nested queries are using sync operators.
=> Fix #9128: Projection with nested projection hangs/does not complete in 2.0 Preview 2

src/EFCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs, src/EFCore.Relational/Storage/RelationalDataReader.cs, src/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs, src/EFCore/Query/Internal/AsyncLinqOperatorProvider.cs, src/EFCore/Query/Internal/LinqOperatorProvider.cs, test/EFCore.SqlServer.FunctionalTests/ConcurrencyDetectorSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs, test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs, test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
Leaks
- If Query fails while enumerating we leak data reader
- If DataReader disposing logger fails we leak data reader
- Dispose reader before logging message
- If sync query throws due to concurrency check we leak data reader
- Make enumerator creation more lazy by moving it inside concurrency detector check
- If query is not run due to concurrency then no data readers will be created
Extend fix for #9074 to sync pipeline - sync queries do not create inner enumerator until needed
Fix issue #9404
QueryBugsTest need MARS=true because of running queries in parallel (using different contexts)
Introduce random MARS settings
=> Query: Fix leaking data readers when query throws exception

src/EFCore.Design/Scaffolding/Internal/CSharpUniqueNamer.cs, test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Windows file system consider file names case insensitive so entity types with same name different casing would end up overwriting other in same file
Resolves #9257
=> RevEng: Generate names of entity types case insensitive

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Types which requires length specified returns needs default length of 8000 specified
Resolves #9188 
The issue,
We don't read metadata when type has length equal to default max length. For all types that would be the length set if not specified but for `(varying) (n)char/binary` no length means size of 1 instead of default max. So we were not getting data from scaffolding and generating a type which would throw in model validation.
Fix:
- Updated list of disallowed mappings in SqlServerTypeMapper. It was missing `char varying`
- All such types have default max length of 8000. Scaffolding would set max length for them if it is default max. (it would be null for all other types)
Also uncovered another bug #9473
=> RevEng: Fix scaffolding for nvarchar(4000)

src/EFCore.Relational/Storage/RelationalDataReader.cs, test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
Connection was required to be null except for some unit test scenarios, so fixed those and added NotNull.
Issue #9456
=> Fix DataReaderDisposing null connection inconsistency

src/EFCore/EntityFrameworkServiceCollectionExtensions.cs, src/EFCore/Internal/DbContextPool.cs, test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- Adds missing DbContextOptions generic parameter.
=> Fix #9433 - Using pooling for multiple DbContexts causes exception

src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
=> Query: Tuples are not translatable to Sql. Client Eval them

src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that for the fixup for _IncludeAsync method would sometimes return default(Task) (i.e. null) if there was nothing to include. This breaks the async pattern, which is expecting a Task. Fix is to return Task.CompletedTask instead.
=> [2.0.1/TINY] Fix to #9038 - NullReferenceException when using TPH Inheritance

src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Adding element sorters to the failing tests
=> Fix to #9341 - SimpleQueryTestBase.Projection_when_arithmetic tests throw

src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
Error was due to null ref in the client eval, added null protection logic to the expected queries
=> [TEST/TINY] Fix to #9340 - ComplexNavigationsQueryTestBase.GroupJoin tests throw in verification

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs, src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs, src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs, src/EFCore.Relational/Internal/RelationalPropertyExtensions.cs, src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
=> [2.0.1] Don't use IProperty.Relational().ColumnType when we want only explicitly configured values

src/EFCore.InMemory/Diagnostics/InMemoryEventId.cs, src/EFCore.Relational/Diagnostics/RelationalEventId.cs, src/EFCore.Specification.Tests/TestHelpers.cs, src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs, src/EFCore.Sqlite.Core/Diagnostics/SqliteEventId.cs, src/EFCore/Diagnostics/CoreEventId.cs, src/EFCore/Diagnostics/Internal/EventIdFactory.cs, src/EFCore/breakingchanges.netcore.json, test/EFCore.SqlServer.Tests/SqlServerEventIdTest.cs
Issue #9437
All values now fit in a 16-bit unsigned int. There is a Quirks mode to switch back to the 2.0.0 RTM values.
=> Patch: Make Event ID values smaller so they will work with Windows EventLog

benchmarks/EFCore.Benchmarks.EFCore1/EFCore.Benchmarks.EFCore1.csproj, build/repo.props
Pretty soon, we will stop installing .NET Core 1.1 and 1.0 by default in the dev branch of KoreBuild. EFCore1 benchmarks still uses netcoreapp1.1. This specifies the required dependency on .NET Core 1.1.2 so it can be installed by KoreBuild.
Usage: to ensure all runtimes are installed, execute `build.sh /t:InstallDotnet`.
cref https://github.com/aspnet/BuildTools/issues/347
=> Ensure .NET Core 1.1.2 is installed for the benchmarks project

src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.GroupBy.cs, test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncIncludeSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.GroupBy.cs
Also lift GroupBy subquery when possible
This allows us to access the SelectExpression corresponding to GroupBy Result operator in ParentQMV
Resolves #9581
=> Query: GroupBy after Skip/Take should push down subquery

src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, src/EFCore/Query/Internal/IncludeCompiler.cs
Instead of modifying the Task that we return from the problematic query, we are checking if the resulting fixup Task is null and only await on it if it's not.
=> Improving fix for #9038 - NullReferenceException when using TPH Inheritance

src/EFCore.Design/Design/Internal/DatabaseOperations.cs, src/EFCore.Design/Scaffolding/Internal/IReverseEngineerScaffolder.cs, src/EFCore.Design/Scaffolding/Internal/IScaffoldingModelFactory.cs, src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs, src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs, src/EFCore.Design/Scaffolding/Internal/ScaffoldingServiceCollectionExtensions.cs, src/EFCore.Design/Scaffolding/Internal/ScaffoldingTypeMapper.cs, test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs
Changes:
- Rename ModelScaffolder to ReverseEngineeringScaffolder
- Decouple RelationalScaffoldingModelFactory from IDatabaseModelFactory
- Remove IRelationalTypeMapper dependency in RelationalScaffoldingModelFactory
- Remove protected dependency properties on internal services
Part of #8853
=> RevEng: More internal refactoring

src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Issue: Since OrderBy comes after Projection, for smaller sql, we refer to ordering as alias when it is present in projection. When we pushdown a subquery, we generate unique alias for each projection. This can cause change of alias for existing alias expression which may be referred by ordering. So even though ordering expression is correct one but since we only print out alias it may cause change of the expression actually used.
Fix: When pushing down subquery, we need to account for already aliased expression being in orderby. Hence we would store a map so that we can track change of expression and update orderby accordingly
Test: Due to #9742 added test in QueryBugsTest
Resolves #9735
=> Query: When we PushDownSubquery update aliases of ordering expressions

samples/OracleProvider/NuGet.config
This should solve the failure on Universe. The problem was that while the top level `NuGet.config` was getting edited to include the artifacts folder this one was not. The two appeared to be the same.
=> Remove sample NuGet.config

src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
Don't assert results since they are non-deterministic
Resolves #8664
=> Test: Improve OrderBy_coalesce_skip_take_distinct_take test

src/EFCore.Relational/Storage/Internal/RelationalCommand.cs, src/EFCore.Relational/Storage/RelationalDataReader.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
=> [2.0.1] Clear DbCommand.Parameters only after reader is disposed

EFCore.Runtime.sln.DotSettings, src/EFCore/Query/Internal/IQueryBuffer.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, src/EFCore/Query/Internal/QueryBuffer.cs
- Avoids the use of IIncludeKeyComparer and ValueBuffers when neither of the entity types involved have any shadow key properties.
- Introduces breaking changes in IQueryBuffer
TBD: Update breaking changes log.
=> Query: Include: Adds an optimized collection include client join predicate code path.

src/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsOwnedQueryRelationalFixtureBase.cs, src/EFCore.Relational/Metadata/Internal/PropertyExtensions.cs, src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/EFCore.Relational/Metadata/RelationalPropertyExtensions.cs, src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs, src/EFCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.resx, src/EFCore/Internal/EnumerableExtensions.cs, test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs, test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs, test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
Default to the principal value generation strategy for the primary key columns for entity types sharing the same table.
Validate that properties sharing the same column have the same value generation strategy.
Fixes #9652
=> Fix Identity for shared columns

src/EFCore.Specification.Tests/Query/AsyncQueryTestBase.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.Select.cs, src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationSetOperatorSubqueryInjector.cs, src/EFCore/Query/ExpressionVisitors/ProjectionExpressionVisitor.cs
Two issues:
1) CollectionNavigationSetOperatorSubqueryInjector would incorrectly introduce MaterializeCollectionNavigation calls around
subqueries. Fix is to reset the ShouldInject flag when visiting subqueries.
2) After fixing 1, we would deadlock due to blocking on the subquery call. Extended task lifting to deal with this case.
=> [2.0.1] - Fix #9570 - Exception in Client vs. Server Evaluation with async/await in EF Core 2.0.0

build/common.props, src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.csproj, src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.nuspec, src/EFCore.Tools/EFCore.Tools.csproj, src/EFCore.Tools/EFCore.Tools.nuspec, version.props
Backports https://github.com/aspnet/EntityFrameworkCore/pull/9381 so repo-to-repo graph analysis works.
Set VersionSuffix on the packages produced from this branch to 2.0.1-rtm-$(BuildNumber)
=> [2.0.1] Update version.props to include suffix and set PackageId in csproj

src/EFCore/ChangeTracking/Internal/IdentityMap.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
=> Throw better exception when replacing an owned entity

version.xml
This was accidentally deleted when merging from feature/2.0.1 into dev.
7a92224a8bd37a56c505937fc96aeb623de974bb
cc @AndriySvyryd
=> Append build number to the version suffix

src/EFCore.Specification.Tests/Query/QueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QuerySqlServerTest.cs
**Take 3**
Issue:
We adopted short-circuiting logic in logical expression due to possible exceptions (which compiler would never throw in memory). This works correctly for general cases because the expression tree would have current value of closure variable hence evaluating to correct thing.
When it comes to QueryFilter, the filter has closure member access on context instance which was used during OnModelCreating which may have stale value of context closure variables. We parametrize such closure variables and insert their values through parameters when running query. But if such closure variable is used in complex expression which can short-circuit then we would be using wrong value for short-circuit (by this point we haven't inserted correct value from current context instance) hence …
=> [2.0.1] Query: Fix for Access to context bound variable can be optimized out

src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/TaskBlockingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/TaskLiftingExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs
And corresponding changes to task lifting and Include compiler.
=> Restore GetAwaiter behavior of TaskBlockingExpressionVisitor.

src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
When there are multiple collections being included then we have single fixup task with AwaitMany function which would wait each of the include task. If one of the collection include is after optional reference navigation then only that task in AwaitMany would be null and not whole fixup task.
=> [2.0.1] Update the fix for #9038 to make it more robust against multi-collection includes

src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs, src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs, src/EFCore.Relational/Query/Internal/AsyncQueryingEnumerable.cs, src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs, src/EFCore.Relational/Storage/IRelationalTransactionFactory.cs, src/EFCore.Relational/Storage/RelationalConnection.cs, src/EFCore.Relational/Storage/RelationalConnectionDependencies.cs, src/EFCore.Relational/Storage/RelationalTransactionFactory.cs, src/EFCore.Relational/Storage/RelationalTransactionFactoryDependencies.cs, src/EFCore.Relational/breakingchanges.netcore.json, test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalConnection.cs, test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs, test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalCommandBuilderFactory.cs, test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs, test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerConnection.cs, test/EFCore.SqlServer.Tests/SqlServerConnectionTest.cs
Issue #9524
The issue here was the reference count was not kept correctly if the connection was closed externally when it was not expected to be. The fix is to keep the count correct in this case.
=> Recover connection state counting after external close

src/EFCore/Query/ExpressionVisitors/ExpressionVisitorBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/DefaultQueryExpressionVisitor.cs, test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
Tweak ExpressionVisitorBase to not visit parameters during VisitLambda.
=> Fix #9849 - Using Include with InMemory and empty database throws

EFCore.Benchmarks.sln, EFCore.Runtime.sln, EFCore.sln, samples/OracleProvider/OracleProvider.sln
Cross repo effort to set the minimum VS version to 15.3.0, primarily for outside contributors. 
Part of https://github.com/aspnet/BuildTools/issues/403
=> Update Minimum Version of Visual Studio to 15.3.0

src/EFCore/DbContext.cs, src/EFCore/Internal/DbContextPool.cs, test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
Problem: Pooling was not resilient to multiple DbContext.Dispose calls, which meant that a context instance could incorrectly be returned to the pool twice.
Solution: Adds a DbContext async local to track which "context" (e.g. request scope) owns the context and use it to ensure a single return to the pool.
=> Fix #9741 - AddDbContextPool in asp.net core System.InvalidOperationException

src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/Query/IncludeTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceTracingExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTree.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs
- Modify QuerySourceTracingExpressionVisitor so that it can return the "deepest" GroupBy QueryModel if one exists.
- Update the Include compiler to target the correct QueryModel when GroupBy is in play.
=> [2.0.1] - Fix #9551 - Expression of type 'System.Object' cannot be used for parameter of type 'Microsoft.EntityFrameworkCore.Metadata.IEntityType'

src/EFCore.Specification.Tests/Query/CompiledQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
Issue: In CompiledQuery, since closure variables are not modified after compilation we capture the values of closure variables as constants rather than parameters. Though the logic to create constant expression was faulty when the value is null.
Resolves #9844
=> Query: Fix for CompiledQuery with closure variable evaluating to null throws

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Issue: When generating conditional expression we generated typed literal for true/false but that was not happening for nullable bools inside converts. Hence whole expression was getting upcasted to int type causing InvalidCastException
Resolves #9818
=> Query: Fix for projecting out bool values with ternary expression throws

src/EFCore.InMemory/EFCore.InMemory.csproj, src/EFCore.Relational/EFCore.Relational.csproj, src/EFCore.SqlServer/EFCore.SqlServer.csproj, src/EFCore.Sqlite.Core/EFCore.Sqlite.Core.csproj, src/EFCore.Sqlite/EFCore.Sqlite.csproj, src/EFCore.Tools/EFCore.Tools.nuspec, src/EFCore/EFCore.csproj
Changes:
- Set min client version to 3.6 (fixes #9668)
- Block metapackage on incompatible frameworks (fixes #9654)
See also aspnet/Microsoft.Data.Sqlite#434
=> NuGet: Friendlier .NET Standard 2.0 packages

samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleTypeMapper.cs, src/EFCore.Relational/Storage/RelationalTypeMapper.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMapper.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs, test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs, test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalTypeMapper.cs, test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMapper.cs, test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs, test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
=> Only use the store type name for finding a type mapping if it has been explicitly set

Directory.Build.targets, NuGet.config, build/dependencies.props, build/sources.props, src/EFCore.Relational.Design.Specification.Tests/EFCore.Relational.Design.Specification.Tests.csproj
Changes
- Use MSBuild to set NuGet feeds instead of NuGet.config. This allows us to configure feeds conditionally using MSBuild properties which is not possible with NuGet.config
- Upgrade Microsoft.Extensions.DependencyModel to the latest 2.0.x build
FYI - CI is expected to fail until we mirror Microsoft.Extensions.DependencyModel 2.0.2-servicing-25728-02 to our feed
=> [2.0.1] Use MSBuild to set NuGet feeds instead of NuGet.config

src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.SqlServer/Query/ExpressionTranslators/Internal/SqlServerObjectToStringTranslator.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Since server would store underlying type of enum hence server eval causes incorrect result
Resolves #9894
=> [2.0.1] Query: Always evalaute Enum.ToString on client

src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs, src/EFCore/Query/Internal/ExpressionEqualityComparer.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue:
When the query is projecting out a collection object in non-navigation case, we cause N+1 queries.
To support streaming behaviour, we inject QueryableAdapter (or async version) which would be evaluated on when enumerated.
When we are chaining on the navigation after such query, the QueryableAdapter is captured in ConstantExpression.
In our ExpressionEqualityComparer, during GetHashCode, we add such value if ConstantExpression is of type IQueryable. (so that we can fall back to Comparison)
During comparing such ConstantExpressions, we assumed if they are of type IQueryable then they are same. Which is true for IQueryable from DbSet.
But for QueryableAdapter which are also IQueryable, it could still evaluate to different results.
Another thing is, in …
=> Query: Fix for incorrect QueryCache hit when chaining a streaming N+1 query

src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj, src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
Slight changes in xunit.core 2.3.0-rc3 would cause these packages not to produce a nupkg. See https://github.com/xunit/xunit/issues/1487
cref https://github.com/aspnet/Universe/pull/578
=> Workaround xunit/xunit#1487

src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/AllFluentApi/SqlServerReverseEngineerTestE2EContext.cs, test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/Attributes/AllDataTypes.cs, test/EFCore.SqlServer.Design.FunctionalTests/SqlServerDatabaseModelFactoryTest.cs
Types which requires length specified returns needs default length of 8000 specified
Resolves #9963
=> [2.0.1] RevEng: Fix scaffolding for nvarchar(4000)

samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleTypeMapper.cs, samples/OracleProvider/test/OracleProvider.FunctionalTests/BuiltInDataTypesOracleTest.cs, samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/SimpleQueryOracleTest.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/Sql/Internal/FromSqlNonComposedQuerySqlGenerator.cs
Issue #242
Note that this PR doesn't fix all the issues with Oracle type mapping; it just gets the tests passing with the types changed to unsigned.
=> Update Oracle sample for type mapping changes

samples/OracleProvider/src/OracleProvider/Query/Sql/Internal/OracleQuerySqlGenerator.cs, samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleSqlGenerationHelper.cs, samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
Fixes #9560
I reviewed all places we generate SQL for schema and table name to ensure they were consistent.
You may want to review [ignoring whitespace changes](https://github.com/aspnet/EntityFrameworkCore/pull/9903/files?w=1) since the R# settings have diverged from Visual Studio's default formatting.
=> Query: Use correct overload of DelimitIdentifier() in DefaultQuerySqlGenerator

src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Resolves #6859
Array access is BinaryExpression with node type of ArrayIndex. Since we always used base method for BinaryExpression except logical expression, we would end up evaluating array separately from access hence always caused client evaluation.
Fix is to process array access as whole instead of visiting left & right subtree.
=> Query: Funcletize accessing array element

src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- Special case Sum for nullable types: result should be (T?)default(T)
=> Fix #800 - Query: Sum should return zero for empty collections regardless of the type.

src/EFCore/DbContext.cs, src/EFCore/EntityFrameworkServiceCollectionExtensions.cs, src/EFCore/Internal/DbContextPool.cs, src/EFCore/Internal/IDbContextPoolable.cs
Introduces a "lease" object, which is a scoped object that manages ownership of a pooled context instance. In particular, the lease object is responsible for returning instances to the pool at the end of the scope. This removes the complexity/race condition from DbContext.Dispose and greatly simplifies pooling in general.
=> Fix #9923 - Perf Regression: AddDbContextPool in asp.net core System.InvalidOperationException

src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
=> Use ReferenceEquals for navigation value comparison in SetProperty

src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Storage/TypeMaterializationInfo.cs, src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs, src/EFCore.Relational/Storage/UntypedRelationalValueBufferFactoryFactory.cs, src/EFCore/Metadata/Internal/EntityMaterializerSource.cs, src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/EFCore/Storage/TypeConverter`.cs, src/EFCore/Storage/ValueConverter.cs, test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs, test/EFCore.Tests/Storage/TypeConverterTest.cs
This moves converting a store value to happen immediately after the value is read from the data reader. This means that it only needs to happen in one place, which will make it cleaner when implementing more complex conversions; such as those needed for Oracle.
Value converters are now registered as expressions, and the expression is compiled directly into the materializer code with no lambda or method invocation, which should be optimal for perf.
=> Compile value converter expressions directly into ValueBuffer factory

src/EFCore.Relational/Storage/UntypedRelationalValueBufferFactoryFactory.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, src/EFCore/Storage/CoreTypeMapping.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/MappingQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs, test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
Part of #242 and #6480
These are the default conversions:
* sbyte -> smallint
* ushort -> int
* uint -> bigint
* ulong -> decimal(20, 0)
* char -> nchar(1)
These can be used by changing the store type:
* sbyte -> byte (not order preserving)
* ushort -> short (not order preserving)
* uint -> int (not order preserving)
* ulong -> long (not order preserving)
* char -> other string types of any size: char, nchar, varchar, nvarchar, text
* char -> int
Also cleaned up the SQL Server type mapping tests to make them easier to understand.
=> Update SQL Server type mappings

src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.SqlServer/Query/Expressions/Internal/RowNumberExpression.cs, src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
…tions
Resolves #10035
Issue here was, our method to calculated projection types was not entirely accurate. It was not robust enough to handle a case where there is project star & projection both at the same time (Sql Generation handles that pretty well).
Due to the bug in the method, when we encouter project star with projection list, we returned based on projection only ignoring the star table. At present this kind of structure only arises with RowNumberPaging which ads RowNumber Expression on projection with star.
Hence we got incorrect type in first slot causing InvalidCastException.
Also changed type for RowNumberExpression since, RowNumber is of type bigint in SqlServer.
This PR brings projection & materialization on same page w.r.t. CLR types.
All tests passed when using …
=> Query: Make GetMappedProjectionTypes to return based on actual projections

src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs, src/EFCore.Relational/Infrastructure/RelationalOptionsExtension.cs, src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/EFCore.Relational/Properties/RelationalStrings.Designer.cs, src/EFCore.Relational/Properties/RelationalStrings.resx, src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs, src/EFCore.Relational/Update/Internal/CommandBatchPreparerDependencies.cs, test/EFCore.Relational.Tests/TestUtilities/RelationalTestHelpers.cs, test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs, test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
=> Add MinBatchSize option

src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Specification.Tests/Query/IncludeTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
Issue: When visiting Selector with _Include method we could not translate it and ended up setting RequiresClientProjection=true which caused Distinct to not get lifted
Fix: _Include should not cause client eval since it would get removed. This allows us to translate Distinct to server.
As a side effect of this in Collection Include case, our distinct order removal logic needs to pattern match more.
Resolves #9912
=> Query: Translate Distinct after Include to server

src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs, src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.resx, src/EFCore.SqlServer/Scaffolding/Internal/SqlDataReaderExtension.cs, src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs, test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Resolves #6196, #9473, #9526, #9568, #10034
Issue#6196 Sequences are only scaffolded if the schema is in selection list
Issue#9473 Type aliases are storing fully-specified underlying type
Issue#9526 Decimal/Numeric always scaffold precision, scale
Issue#9568 Execute separate query to fetch metadata which are parametrized on table & schema
Issue#10034 At present we don't have a way to scaffold custom type for Sequence, we always get typemapping based on CLR type. So when alias is used for Sequence, we will send underlying system type for scaffolding
=> RevEng: Rewrite SqlServerDatabaseModelFactory for improved scripts

src/EFCore.Relational/Storage/RelationalTypeMapper.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs, test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs, test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
Part of issue #1100
This change allows properties of type SqlGeography, SqlGeometry, and HierarchyId to be included in entity classes and mapped by convention to corresponding database columns.
WARNING: This is by no-means full spatial support for EF Core. These are the important limitations:
* It only works when running on .NET Framework. It will not work on .NET Core, since SqlClient for .NET Core does not support these types.
* Query support is limited:
* LINQ queries that don't use the semantics of the SQL types should work.
* Queries that need to use the type semantics (e.g. using STDistance) can be done with FromSql queries, but not LINQ
* See issue #10108 for some test code and issue #10109 for some ideas to make LINQ work better
* The SQL Server spatial types do not provide a good …
=> Allow mapping to SqlGeography, SqlGeometry, and HierarchyId columns on .NET Framework

src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore/Extensions/Internal/ExpressionExtensions.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Issue:
We have optimization to convert `a ? b : c` where a, b, c are all comparison expression to `a && b || c && d`.
For this case, while b seemed like comparison expression but it was in such pattern due to being nullable bool. (b == true)
A true comparison expression is of type bool since it gives true/false answer. If it is not then its value type expression.
In user case, since we tried incorrect optimization, we ended up with mismatched types in AndAlso expression.
Fix is to improve logic of IsComparisonExpression to only identify boolean expression
Resolves #9468
=> Query: Apply conditional collapse to comparisons only for truly comparison Expressions

src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs, src/EFCore.Design/EFCore.Design.csproj, test/EFCore.Design.Tests/TestUtilities/TestAppServiceProviderFactory.cs, test/EFCore.Tests/TestUtilities/MockAssembly.cs
Uses the new shared sources package we created to abstract the aspnet templates host initialization logic. It finds either
IWebHostBuilder CreateWebHostBuilder(string[] args) or
IWebHost BuildWebHost(string[] args)
and provides a factory method that can be used to produce an IWebHost instance
=> Update AppServiceProviderFactory to use WebHostFactoryResolver

src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/EFCore/Internal/EnumerableExtensions.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
=> Migrations: Use reflection order for columns in CreateTable

src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs, src/EFCore.InMemory/Properties/InMemoryStrings.resx, src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs, src/EFCore.InMemory/Storage/Internal/InMemoryTableFactory.cs, src/EFCore.Relational.Specification.Tests/UpdatesRelationalTestBase.cs, src/EFCore.Specification.Tests/TestModels/UpdatesModel/Product.cs, src/EFCore.Specification.Tests/UpdatesTestBase.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryFixtureBase.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithSensitiveDataLoggingFixture.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithSensitiveDataLoggingTest.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithoutSensitiveDataLoggingFixture.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithoutSensitiveDataLoggingTest.cs, test/EFCore.Tests/DbContextServicesTest.cs
```
- Detail 1
- Detail 2
Fixes #10157
```
=> Concurrency token checks in Update and Delete methods of InMemoryTable

src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs, test/EFCore.Relational.Tests/Utilities/DbParameterCollectionExtensionsTest.cs
- Fixes log outputs so times are sent as total milliseconds, instead of just the millisesond part
- Renamed wrongly named RelationLoggerExtensionsTests
Fixes #10223
=> Fix log time output

src/ef/ReflectionOperationExecutor.cs
This enables using a separate migrations assembly when the startup project contains the DbContext.
(Found while writing [docs about it](https://github.com/bricelam/EntityFramework.Docs/blob/migrate/entity-framework/core/managing-schemas/migrations/projects.md).)
Verification: Manually tested
=> Tools: Hook AssemblyResolve on .NET Core

src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Resolves #10112
Issue here was, we set ProjectStarTable for QSRE only in subquery. But in this case even though it is top level, it later gets pushed down due to Take-Count sequence causing it to be subquery without projection & projectStarTable set.
Whenever we are projecting QSRE, we can set ProjectStarTable regardless of level. It is just a mapping for us between QSRE returned by queryModel & ProjectStarTable returned by SelectExpression.
=> Set ProjectStarTable whenever QSRE is being projected out

EFCore.sln.DotSettings, src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.cs, src/EFCore/Query/ResultOperators/Internal/IncludeResultOperator.cs, test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs
- Added flag to IncludeResultOperator that tracks whether the Include was implicit. I.e. Added because of IsEagerLoad in model.
=> Fix #10222 - Using .Any() on table with owned entities causes IncludeIgnoredWarning

.editorconfig, EFCore.Runtime.sln, EFCore.sln
This introduce .editorConfig file for common options & specifically our naming style.
.editorConfig is supported by R# & VS both. It overrides user-defined settings.
part of #9911
=> Add .editorConfig file

src/EFCore.Relational/Query/Expressions/SelectExpression.cs, test/Directory.Build.props, test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
We used to rely on null check rather than properly checking for expression. This improves our logic when to add ordering expression to projection when lifting it from subquery
We started hitting this when we added Debug check in `LiftExpressionFromSubquery`
=> Query: Process expression to lift properly in LiftOrderBy

src/EFCore.InMemory/Infrastructure/InMemoryDbContextOptionsBuilder.cs, src/EFCore.Relational/Infrastructure/RelationalDbContextOptionsBuilder.cs, src/EFCore.Relational/Metadata/Builders/DbFunctionBuilder.cs, src/EFCore.Relational/Metadata/Builders/DiscriminatorBuilder.cs, src/EFCore.Relational/Metadata/SequenceBuilder.cs, src/EFCore.Relational/Migrations/MigrationBuilder.cs, src/EFCore.Relational/Migrations/Operations/Builders/ColumnsBuilder.cs, src/EFCore.Relational/Migrations/Operations/Builders/OperationBuilder.cs, src/EFCore/ChangeTracking/ChangeTracker.cs, src/EFCore/ChangeTracking/EntityEntry.cs, src/EFCore/ChangeTracking/MemberEntry.cs, src/EFCore/ChangeTracking/PropertyValues.cs, src/EFCore/DbContext.cs, src/EFCore/DbContextOptionsBuilder.cs, src/EFCore/DbFunctions.cs, src/EFCore/DbSet`.cs, src/EFCore/Infrastructure/DatabaseFacade.cs, src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs, src/EFCore/Metadata/Builders/EntityTypeBuilder.cs, src/EFCore/Metadata/Builders/IndexBuilder.cs, src/EFCore/Metadata/Builders/KeyBuilder.cs, src/EFCore/Metadata/Builders/PropertyBuilder.cs, src/EFCore/Metadata/Builders/ReferenceCollectionBuilder.cs, src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs, src/EFCore/Metadata/Builders/ReferenceReferenceBuilderBase.cs, src/EFCore/ModelBuilder.cs, test/EFCore.Tests/DbContextTest.cs
Includes:
- `DbContext` and its facades
- `DbSet`
- `EntityEntry` and friends
- `DbContxtOptionsBuilder` and its chain types
- `ModelBuilder` and its chain types
- `MigrationBuilder` and its chain types
- `EF`'s chain types
Resolves #1367 
ℹ️ Looks like you can't hide `GetType()` in modern tooling.
=> Hide System.Object methods on fluent APIs

src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Without an ORDER BY clause the database results come in an undefined order, and the assertion against LINQ to Objects fails (happens in PostgreSQL).
=> Add orderby in DefaultIfEmpty_in_subquery_nested

src/EFCore.SqlServer/Properties/SqlServerStrings.resx
Fixed a minor typo in SqlServerStrings.resx - 'accomadate' to 'accommodate'
=> Typo in SqlServerStrings.resx

test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
AppContext.BaseDirectory points to TestHost which at times may be un-writable
For net461 in `dotnet test` its inside dotnet SDK folder
For VS its inside VS installation folder
CurrentDirectory points to bin output of the source hence will always be writable
This applies to database files which we explicitly create. By default LocalDb will use its default location.
Resolves #4553 
Relates to #8902
=> Test: Use CurrentDirectory instead of AppContext.BaseDirectory

src/EFCore.Relational/Metadata/Internal/DbFunction.cs, src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
=> Query: Add support for instance based SqlFunction

src/EFCore.Relational/Query/ExpressionVisitors/Internal/PredicateNegationExpressionOptimizer.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Issue:
When the InExpression.Values is empty list, expression is always false. We used to expand values from parameters at time of generating SQL.
When OrderBy contains, the InExpression gets expanded to conditional for value type statement and later we find out that InExpression evaluates to false. But by then we have written incorrect SQL already.
Fix:
Pre-process and condense InExpression based on parameter values using a visitor. So that ORDER BY is away of final condensed form before writing SQL.
Also added small optimization
!(true) -> false & vice-versa.
Combined logic to generate InExpression into SQL in single method.
P.S. all Generate* method should be void.
First Part of #9951
=> Query: Expand value list in InExpression before writing SQL

src/EFCore.Specification.Tests/Query/DbFunctionsTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Issue was fixed in #10370
VisitChildren method was incorrect
This adds test for the scenario
Resolves #10421
=> Query: Preserve Schema in SqlFunctionExpression while visiting children

src/EFCore.Relational/Query/Expressions/AliasExpression.cs, src/EFCore.Relational/Query/Expressions/ColumnExpression.cs, src/EFCore.Relational/Query/Expressions/ColumnReferenceExpression.cs, src/EFCore.Relational/Query/Expressions/DiscriminatorPredicateExpression.cs, src/EFCore.Relational/Query/Expressions/ExplicitCastExpression.cs, src/EFCore.Relational/Query/Expressions/InExpression.cs, src/EFCore.Relational/Query/Expressions/IsNullExpression.cs, src/EFCore.Specification.Tests/Query/IncludeTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
When there is InExpression in order by and used with collection include query, we threw NRE when trying to lift the order by in SelectExpression
Resolves #9951
=> Query: Make InExpression.Equals null safe

test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs
Resolves #8050
We depend on xunit 2.3.0 which has fix for the issue forcing us to write attributes in derived classes.
=> Remove redundant FactAttribute from tests

src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs
Implemented a null/dbnull value check before assigning an UDT typename (string) to a DbParameter. 
Fixes: #10214
```
- Detail 1
- Detail 2
```
=> Adding a null check to prevent SqlCommand exception for UDT

src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs, src/EFCore.Relational/Properties/RelationalStrings.Designer.cs, src/EFCore.Relational/Properties/RelationalStrings.resx, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.cs, src/EFCore/EntityFrameworkQueryableExtensions.cs, src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs, src/EFCore/Internal/InternalDbSet.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/EntityQueryModelVisitorDependencies.cs, src/EFCore/Query/ExpressionVisitors/Internal/FilterApplyingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, src/EFCore/Query/Internal/IQueryModelGenerator.cs, src/EFCore/Query/Internal/IQueryProcessor.cs, src/EFCore/Query/Internal/QueryCompiler.cs, src/EFCore/Query/Internal/QueryModelGenerator.cs, src/EFCore/Query/Internal/QueryOptimizer.cs, src/EFCore/Query/Internal/QueryProcessor.cs, src/EFCore/breakingchanges.netcore.json, test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- Adjust parameterizer to correctly handle DbSet eval when parameterizing filters.
- Introduce IQueryProcessor so we can parse queries inside the query compiler itself.
=>  Query: Filters: Fix 10463 - Error when referencing DbSet in filter

src/EFCore.Specification.Tests/TestUtilities/TestServiceFactory.cs, test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs, test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ScaffoldingTypeMapperSqlServerTest.cs, test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs, test/EFCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs, test/EFCore.Relational.Tests/Migrations/MigrationCommandListBuilderTest.cs, test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs, test/EFCore.Relational.Tests/Storage/RawSqlCommandBuilderTest.cs, test/EFCore.Relational.Tests/Storage/RelationalCommandBuilderTest.cs, test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs, test/EFCore.Relational.Tests/Storage/RelationalParameterBuilderTest.cs, test/EFCore.Relational.Tests/Storage/RelationalTypeMapperTest.cs, test/EFCore.Relational.Tests/TestUtilities/TestRelationalConventionSetBuilder.cs, test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs, test/EFCore.Relational.Tests/Update/UpdateSqlGeneratorTest.cs, test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs, test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs, test/EFCore.SqlServer.Tests/SqlServerSequenceValueGeneratorTest.cs, test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs, test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs, test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchFactoryTest.cs, test/EFCore.SqlServer.Tests/Update/SqlServerModificationCommandBatchTest.cs, test/EFCore.SqlServer.Tests/Update/SqlServerUpdateSqlGeneratorTest.cs, test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs, test/EFCore.Sqlite.Tests/SqliteModelValidatorTest.cs, test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs, test/EFCore.Sqlite.Tests/Update/SqliteUpdateSqlGeneratorTest.cs
For some types that have a lot of unit tests there is a lot of code just to call the default constructors for a service, its dependency objects, and its dependencies. This change adds a simple helper that uses the D.I. system to create factories for this code. This greatly reduces the amount of test code that needs to change when a new dependency is added. This change uses the factory for type mappers. Use for other types can be added as needed.
=> Add a test helper for creating default service instances

src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs, src/EFCore.Design/Properties/DesignStrings.Designer.cs, src/EFCore.Design/Properties/DesignStrings.resx, src/EFCore/Design/DesignTimeServicesReferenceAttribute.cs
Note, referenced services can override default and provider services, but the user can override referenced services.
Resolves #10154
@tonysneed This was the easy part. 😄 The harder part is going to be authoring NuGet packages to automatically add this attribute to the user's project. See [my comment](https://github.com/aspnet/EntityFrameworkCore/issues/10154#issuecomment-340047623) on the issue for my thoughts on doing this. I'm going to start working on a few design-time extensions. I'll CC you when I work out the specifics to how to do this.
=> Design: Allow referencing additional design-time services

src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs, test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
=> Query: inline deterministic fields

src/ef/Commands/CommandBase.cs
- Enable response files at command line
Manual tests include:
`dotnet ./dotnet-ef.dll migrations add initial @BloggingContext.ef.config`
(BloggingContext.ef.config contents)
```
-p
C:\playground\AppToBuilder\AppToBuilder.csproj
-s
C:\playground\AppToBuilder\AppToBuilder.csproj
```
`dotnet ./dotnet-ef.dll @BloggingContext.ef.config`
(BloggingContext.ef.config contents)
```
migrations
add
initial
-p
C:\playground\AppToBuilder\AppToBuilder.csproj
-s
C:\playground\AppToBuilder\AppToBuilder.csproj
```
Relative path:
`dotnet ./dotnet-ef.dll migrations add initial @D:/BloggingContext.ef.config` 
Error condition (no migration name):
`dotnet ./dotnet-ef.dll migrations add @D:/BloggingContext.ef.config`
Fixes #10409
=> Add support for using response files from EF commands

src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs, src/EFCore/EntityFrameworkQueryableExtensions.cs, src/EFCore/Extensions/Internal/ExpressionExtensions.cs, src/EFCore/Query/ResultOperators/Internal/IncludeExpressionNode.cs, src/EFCore/Query/ResultOperators/Internal/ThenIncludeExpressionNode.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
There is a bug in the compiler that would cause it to not pick the correct overload for the ThenInclude method for collection navigations.
Fix is to remove the additional overloads and re-purpose the current ones, so that users can specify derived includes using them.
Previous declaration was:
customers.Include(SpecialCustomer sc => sc.SpecialOrders).ThenInclude(SpecialOrder so => so.SpecialOrderDetails)
New declaration is:
customers.Include(c => ((SpecialCustomer)c).SpecialOrders).ThenInclude(o => ((SpecialOrder)o).SpecialOrderDetails)
alternatively, using "as" operator:
customers.Include(c => (c as SpecialCustomer).SpecialOrders).ThenInclude(o => (o as SpecialOrder).SpecialOrderDetails)
=> Fix to #10441 - Query: Derived include types not inferred for collections

samples/OracleProvider/src/OracleProvider/Extensions/OracleServiceCollectionExtensions.cs, src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs, src/EFCore.InMemory/Query/ExpressionVisitors/Internal/InMemoryEntityQueryableExpressionVisitor.cs, src/EFCore.InMemory/Query/ExpressionVisitors/Internal/InMemoryEntityQueryableExpressionVisitorFactory.cs, src/EFCore.InMemory/Query/Internal/IInMemoryMaterializerFactory.cs, src/EFCore.InMemory/Query/Internal/InMemoryMaterializerFactory.cs, src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs, src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs, src/EFCore.Relational/Migrations/MigrationsSqlGeneratorDependencies.cs, src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs, src/EFCore.Relational/Update/IUpdateSqlGenerator.cs, src/EFCore.Relational/Update/Internal/ISingletonUpdateSqlGenerator.cs, src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs, src/EFCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs, src/EFCore/Infrastructure/AccessorExtensions.cs, src/EFCore/Internal/InternalAccessorExtensions.cs, src/EFCore/Metadata/Internal/EntityMaterializerSource.cs, src/EFCore/Metadata/Internal/IEntityMaterializerSource.cs, src/EFCore/Metadata/Internal/ServiceMethodParameterBinding.cs, src/EFCore/Metadata/Internal/ServiceParameterBinding.cs, test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs, test/EFCore.SqlServer.FunctionalTests/ConvertToStoreTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
Addresses #10545 plus some more newer breaks
* Added a workaround for IUpdateSqlGenerator scope change to singleton
* Added back internal method on IEntityMaterializerSource that in-memory provider is calling directly and renamed classes to avoid future confusion (I have some other changes coming to help mitigate this in the future.)
* Made constructor injection of services behave better if context is not injected (only a problem for in-memory, due to above internal call issue)
* Disabled some tests that can only work with a provider that supports type conversions
=> Fix some compat issues running 2.1 EF with 2.0 provider

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs, src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs, src/EFCore/Storage/Converters/ConverterMappingHints.cs, test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
Issue #10638
Change to serialize an actual, but non-functional, ValueConverter so that the type mapper works the same on the snapshot model as it does on the original model.
=> Change to handling value conversion annotations in code generation and more tests

src/EFCore.Relational/Storage/RelationalTypeMapper.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerSqlVariantTypeMapping.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs, src/EFCore/Metadata/Conventions/Internal/PropertyDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs, src/EFCore/Storage/CoreTypeMapper.cs, src/EFCore/Storage/ITypeMapper.cs, src/EFCore/breakingchanges.netcore.json, src/Shared/PropertyInfoExtensions.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
Issue #7043
The type mapper will now map properties to sql_variant columns if:
* The property is type object
* The store type name is specified as sql_variant
Also #10633 - set min batch size to 1 for type mapping tests so that batching and non-batching are tested.
=> Allow mapping sql_variant on SQL Server

src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs, src/EFCore/Extensions/Internal/ExpressionExtensions.cs, src/EFCore/Infrastructure/CoreOptionsExtension.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationIncludeExpressionRewriter.cs, src/EFCore/Query/ExpressionVisitors/Internal/CollectionNavigationSubqueryInjector.cs, src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionFindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceReferenceFindingExpressionTreeVisitor.cs, src/EFCore/Query/Internal/CorrelatedSubqueryMetadata.cs, src/EFCore/Query/Internal/ExpressionPrinter.cs, src/EFCore/Query/Internal/IQueryBuffer.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, src/EFCore/Query/Internal/MaterializedAnonymousObject.cs, src/EFCore/Query/Internal/QueryBuffer.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
This feature optimizes a number of queries that project correlated collections. Previously those would produce N+1 queries. Now, we rewrite queries similarly to how Include pipeline does it, producing only two queries and correlating them on the client.
To enable the feature the inner subquery needs to be wrapped around ToList() or ToArray() call.
Current limitations:
- only works for sync queries,
- doesn't work if the parent query results in a CROSS JOIN,
- doesn't work with result operators (i.e. Skip/Take/Distinct)
- doesn't work if outer query needs client evaluation anywhere outside projection (e.g. order by or filter by NonMapped property)
- doesn't work if inner query is correlated with query two (or more) levels up, (e.g. customers.Select(c => c.Orders.Select(o => …
=> Fix to #9282 - Query: optimize queries projecting correlated collections, so that they don't result in N+1 database queries

src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
Problem was that when comparing sql functions (to look for duplicate orderby's) we were not taking into account situation when instance for the function was null.
=> [TINY] Fix to #10743 - Query: order by property's length twice throws NRE exception during query compilation

src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Problem was that when rewriting QM for Include (or correlated collection optimization) we always assumed that orderbys on the parent collection would be a simple member access. However, in some cases it can be more complicated - if property is declared on interface or base class, there will be a Convert in the tree.
Also, orderbys can be specified using EF.Property, which was also not supported.
=> [SMALL] Fix to #10635 - Query: ArgumentOutOfRangeException when using Include and OrderBy by with casting

NuGetPackageVerifier.json, src/EFCore.Design/EFCore.Design.csproj, src/EFCore.Design/build/net461/Microsoft.EntityFrameworkCore.Design.props, src/EFCore.Design/build/netcoreapp2.0/Microsoft.EntityFrameworkCore.Design.props, src/EFCore.Tools/EFCore.Tools.nuspec, src/EFCore.Tools/tools/EntityFrameworkCore.psm1, src/dotnet-ef/Project.cs
Changes our existing workaround to use an MSBuild file in EFCore.Design; adds a workaround for .NET Framework
Fixes #10639
=> Tools: Work around more class library limitations

src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
Fixes #10740 
* Solve apostrophe problem in database name
New SQL output:
```sql
IF SERVERPROPERTY('EngineEdition') <> 5
BEGIN
ALTER DATABASE [Migrations'Test] SET READ_COMMITTED_SNAPSHOT ON;
END;
```
=> Fix #10740: Repair the database name with apostrophe

src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
Oracle returns results in different order than InMemory - test was working "by accident" on SqlServer - adding client side orderby to the results so that they are deterministic on all providers.
=> fixing test verification issue that leads to failing oracle test

src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/AsyncQueryTestBase.cs, src/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs, src/EFCore/Query/Internal/IQueryBuffer.cs, src/EFCore/Query/Internal/QueryBuffer.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs
Adding support for async, porting GearsOfWars correlated collection tests to async for coverage.
=> Fix to #10723 - Query: add correlated collection optimization support for async queries

src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs, src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs, test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs
Establishes a pattern for reverse engineering code scaffolding tests. The code is generated, compiled, and loaded. Both the C# and loaded model are asserted.
This test should help us catch the usual regressions until we can add more.
Part of #9111
=> Add a CSharpModelGenerator test

src/EFCore.Relational.Specification.Tests/Query/WarningsTestBase.cs, src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
No need to generate a warning unless we are in a subquery.
=> Fix #9726 - Max causes QueryClientEvaluationWarning

src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Removing calls to ToList() on correlated collections if the collections are being optimized using CorrelateSubquery.
=> Fix to #10762 - Query: remove redundant ToList calls on top of correlated collections that get optimized

src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs, src/EFCore/Metadata/Conventions/Internal/ConventionNode.cs, src/EFCore/Metadata/Conventions/Internal/ConventionVisitor.cs, src/EFCore/Metadata/Internal/EntityType.cs
Reuse last `ConventionNode` when empty
Make read-only check debug-only
=> Small conventions optimization

src/EFCore.Specification.Tests/CustomConvertersTestBase.cs, src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs, src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/EFCore/Storage/Internal/FallbackCoreTypeMapper.cs, test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
Issue #10765
Because until the call to HasConversion is made we can't know whether or not the property can be mapped.
=> Allow properties to be defined/configured before their final types are known

src/EFCore/Query/Expressions/Internal/IPrintable.cs, src/EFCore/Query/Expressions/Internal/NullConditionalEqualExpression.cs, src/EFCore/Query/Expressions/Internal/NullConditionalExpression.cs, src/EFCore/Query/Internal/ExpressionPrinter.cs, src/EFCore/Query/Internal/QueryModelPrinter.cs
Added IPrintable interface to our custom expression nodes that takes ExpressionPrinter argument and knows how to properly print a given node.
Also improved printing of GroupResultOperator - we now properly print it's arguments, rather than just using ToString()
=> Fix to #10202 - Query: ExpressionPrinter is not flexible

src/ef/Commands/DatabaseDropCommand.cs
Fix #10636 so that `ConfigurationServices` will not be called second time when the drop command is executed with _--force_ option.
=>  ContextInfo will not be called second time in a forced drop command.

src/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.QueryTypes.cs
Query type test fails on PostgreSQL because of undelimited table name - get the provider's ISqlGenerationHelper and delimit (hope I did this the right way).
An alternative would be for providers to extend NorthwindRelationalContext and specify their own SQL but that becomes more complicated.
=> Delimit table name in query type test

src/EFCore.Design/Design/DbContextActivator.cs, src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs, src/EFCore.Design/Design/Internal/DatabaseOperations.cs, src/EFCore.Design/Design/Internal/DbContextOperations.cs, src/EFCore.Design/Design/Internal/DesignTimeConnectionStringResolver.cs, src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs, src/EFCore.Design/Design/Internal/MigrationsOperations.cs, src/EFCore.Design/Design/OperationExecutor.cs, src/EFCore.Design/Scaffolding/IModelCodeGenerator.cs, src/EFCore.Design/Scaffolding/IReverseEngineerScaffolder.cs, src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs, src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs, src/EFCore.Design/Scaffolding/Internal/ICSharpDbContextGenerator.cs, src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs, src/EFCore.Design/Scaffolding/ModelCodeGenerationOptions.cs, src/EFCore.Design/Scaffolding/ModelCodeGenerator.cs, src/EFCore.Design/Scaffolding/ModelReverseEngineerOptions.cs, src/EFCore.Relational/Storage/Internal/NamedConnectionStringResolverBase.cs, test/EFCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs, test/EFCore.Design.Tests/TestUtilities/TestDbContextOperations.cs
This extends support for the "name=" connection string format to the Scaffold-DbContext and `ef dbcontext scaffold` commands. Obviously, the tools will need to be able to access your application services at design time (via Program.BuildWebHost, etc.) and get the IConfiguration service.
Resolves #2464
=> RevEng: Support named connection strings

src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryFixtureBase.cs, src/EFCore/Metadata/Builders/EntityTypeBuilder.cs, src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs, src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs, src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder.cs, src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/EntityEqualityRewritingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs
Record the EntityType when visiting the MainFromClause.
Allow to use the ModelBuilder API to configure weak entity types added using the Model API.
=> Fix some optimizations not being applied to weak entities

src/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs, src/EFCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/Query/InheritanceSqliteTest.cs
Force query composition if target entity is part of an inheritance hierarchy.
=> Fix #10501 - Inconsistent SQL queries in inheritance + FromSql scenarios

src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerCoreTypeMapper.cs, test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs, test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs
Also updates the tests to catch more missing design-time services.
=> SQL Server: Use SqlServerCoreTypeMapper at design-time

src/EFCore.Relational/Metadata/Conventions/Internal/DiscriminatorConvention.cs, src/EFCore/Infrastructure/ModelValidator.cs, src/EFCore/Metadata/Conventions/ConventionSet.cs, src/EFCore/Metadata/Conventions/Internal/BaseTypeDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/ConventionDispatcher.cs, src/EFCore/Metadata/Conventions/Internal/ConventionNode.cs, src/EFCore/Metadata/Conventions/Internal/ConventionVisitor.cs, src/EFCore/Metadata/Conventions/Internal/DerivedTypeDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/IEntityTypeRemovedConvention.cs, src/EFCore/Metadata/Internal/EntityTypeExtensions.cs, src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/EFCore/Metadata/Internal/Model.cs, test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs, test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs, test/EFCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs, test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs, test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs, test/EFCore.Tests/ModelBuilding/TestModel.cs
Validate owned type inheritance
Allow to disconnect mapped base type
Fixes #10200
Fixes #10715
=> Don't discover base or derived types for owned types

src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
Problem was that when rewriting collection query for case with group result operator, we add order by key element, but we were not adding it as first orderby term. This would cause outer elements arrive in different order than inner, so include would not associate them together. Fix is to apply order by always as first element.
=> [TINY] Fix to #10828 - Query: include doesn't work for queries with order byand group by

samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/GroupByQueryOracleTest.cs, src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Ordering was not determinstic, passing in SQL Server but failing in PostgreSQL.
=> Specify ordering in OrderBy_Skip_GroupBy

src/EFCore.Relational/DbFunctionAttribute.cs, src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Tweak SQL gen to delimit function calls that have a schema.
=> Fix #9558 - Relational: UDF calls are generated unquoted

src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs, src/EFCore.Specification.Tests/LoadTestBase.cs, src/EFCore/Internal/LazyLoader.cs
Part of #10042, #10509, #3797
It would be good to make this work in a future release, but this involves running a no-tracking query with fixup where the root entity is already materialized. For now, this will throw so we can make it work later without it being a breaking change.
Lazy-loading behaviors for non-tracked entities:
* Proxies:
* No-op if entity was explicitly detached
* Throw if it was queried as no-tracking
* Lazy-loading entities with loader service property:
* No-op if entity was explicitly detached
* Throw if it was queried as no-tracking
* Lazy-loading entities without service property:
* Throw even if entity was explicitly detached, but entity can set loader to null, or a service property can be defined
* Throw if it was queried as no-tracking
=> Throw when attempting to lazy-load after no-tracking query

src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that correlated collection optimization rewrite wasn't properly handling result operators that could be part of the parent query model. Parent QM is cloned, rewritten and then used as part of the inner collection query.
Fix is to properly compensate for result operators that change the cardinality of the result (specifically First/Single/Last), similarly to what we do in the include pipeline.
=> Fix to #10813 - Query: correlated collection optimization is broken for queries containing top level First/FirstOrDefault/Single/SingleOrDefault

src/EFCore/DbContext.cs, src/EFCore/Diagnostics/CoreEventId.cs, src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs, src/EFCore/Internal/InternalDbQuery.cs, src/EFCore/Internal/InternalDbSet.cs, src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs, src/EFCore/Metadata/Conventions/Internal/KeyDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs, src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs, src/EFCore/Metadata/Internal/EntityType.cs, src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/EFCore/Metadata/Internal/InternalModelBuilder.cs, src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, src/Shared/Check.cs, src/Shared/SharedTypeExtensions.cs, test/EFCore.Tests/DbContextTest.cs, test/EFCore.Tests/DbSetTest.cs, test/EFCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs, test/EFCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs, test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs, test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs, test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs, test/EFCore.Tests/ModelBuilding/TestModel.cs, test/EFCore.Tests/Utilities/CheckTest.cs
Throw better exception for `.Set<WeakType>()`
Log warnings for `InversePropertyAttribute` not working for owned types
Fixes #9265
Fixes #9626
=> Ignore collection navigations to owned types

src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs, src/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs, src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs, src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs, src/EFCore.Specification.Tests/Query/InheritanceTestBase.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs, src/EFCore.SqlServer/Properties/SqlServerStrings.resx, src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/EFCore/ChangeTracking/Internal/NavigationFixer.cs, src/EFCore/ChangeTracking/Internal/StateManager.cs, src/EFCore/Internal/Multigraph.cs, src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, src/EFCore/Update/Internal/UpdateEntryExtensions.cs, test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs, test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithSensitiveDataLoggingTest.cs, test/EFCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs, test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs, test/EFCore.Tests/ChangeTracking/Internal/InternalClrEntityEntryTest.cs, test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs, test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs, test/EFCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs, test/EFCore.Tests/Metadata/MetadataBuilderTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
Add key values to SaveChanges circular dependency message
Update transient error message to not reference SqlAzureExecutionStrategy
Add key values to the conceptual null exception
Don't validate mapping for shadow properties created by convention
Add incompatible principal entity during fixup exception
Don't reference 'Property' in property is already a navigation exception
Fixes #8363
Fixes #8365
Fixes #9696
Fixes #9817
Fixes #10135
Fixes #10856
=> Improve exception messages

src/EFCore.Relational/Query/ExpressionVisitors/Internal/IsNullExpressionBuildingVisitor.cs, src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryFixtureBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs, src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that we would not apply null semantics properly to ColumnReference expressions - we were not detecting that the column behind it is actually nullable and IS NULL term needs to be generated for it.
Also as part of this change improved test infrastructure for cases when some of the results are null.
=> Fix to #10785 - Model Query Filter generates incorrect SQL

src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Problem was that we were too aggressive in applying null compensation during navigation rewrite. This could lead to type change of an argument to a function - if the argument was a non-nullable property accessed via optional navigation). This in turn causes issues during compilation, because new method arguments must match method signature.
Fix is to unwrap null compensation for arguments of the function.
=> [TINY] Fix to #10284 - EF Core does not cast from Nullable to underlying type

src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
Contains on top-level cannot be translated (since we don't have it inside lambda and don't have expression tree for Item)
This caused to throw exception because we did not mark the QSRE for materialization.
Fix is to mark the naked QSRE for materialization if in top level Contains
Resolves #10868
=> Query: Materialize entity if used in top level Contains

src/EFCore.Specification.Tests/WithConstructorsTestBase.cs, src/EFCore/ChangeTracking/NavigationEntry.cs, src/EFCore/ILazyLoader.cs, src/EFCore/Internal/LazyLoader.cs, src/EFCore/Metadata/Internal/LazyLoaderParameterBindingFactory.cs
Part of #10509, #3797
Adds ILazyLoader.LoadAsync and allows binding to delegate for it.
=> Add async infrastructure for lazy-loading

src/EFCore.SqlServer/Metadata/Conventions/Internal/SqlServerIndexConvention.cs, src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs, test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
SqlServerIndexConvention sets filter on unique index based on column null-ability.
When changing base type, the column null-ability in derived type changes so we need to update the filter.
Fix is to trigger convention for BaseTypeChanged
Resolves #10659
=> Metadata: Run SqlServerIndexConvention when changing base type

src/EFCore.Relational/Migrations/MigrationBuilder.cs, src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs, test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs, test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
This was happening in two places:
- An overload of MigrationBuilder.UpdateData() (fixes #10115)
- When generating SQL for SQL Server memory-optimized indexes (fixes #10402)
=> Migrations: Fix missing schema values

src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs, src/EFCore.Relational/Query/ExpressionTranslators/Internal/EqualsTranslator.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs, test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
Improving equals translator to handle static Equals
=> Fix to #10807 - Query: Translate string.Equals(a, b)

samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleTypeMapper.cs, src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs, src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs, src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs, src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Relational/Storage/RelationalTypeMapping.cs, src/EFCore.Relational/Storage/TypeMaterializationInfo.cs, src/EFCore.Relational/Storage/UntypedRelationalValueBufferFactoryFactory.cs, test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs, test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs, test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs, test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
Issues #10748, #3620
These are now handled by type converters in type mapping, and for providers that can natively handle enums they will not be converted at all.
Also, change the way properties with conversions are stored in the snapshot such that:
- Only "store types" are used
- A dummy value converter is created to preserve any mapping hints, etc.
Note that if the database maps the enum directly, then this means that it is a "store type" and will be used in the snapshot and migrations and these may break if the type is later removed or changed.
=> Remove ad-hoc enum conversions

src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs, src/EFCore.SqlServer/Design/Internal/SqlServerDesignTimeServices.cs, src/EFCore.SqlServer/Storage/Internal/SqlServerCoreTypeMapper.cs, test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineerScaffolderTest.cs, test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs, test/EFCore.Design.Tests/TestUtilities/FakeScaffoldingModelFactory.cs
(Cherry-picked from changes already in `dev`.)
Fixes #10931
=> [2.1.0-preview1] SQL Server: Use SqlServerCoreTypeMapper at design-time

src/EFCore/ChangeTracking/ChangeTracker.cs, src/EFCore/ChangeTracking/EntityEntryEventArgs.cs, src/EFCore/ChangeTracking/EntityStateEventArgs.cs, src/EFCore/ChangeTracking/EntityTrackedEventArgs.cs, src/EFCore/ChangeTracking/Internal/IStateManager.cs, src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/EFCore/ChangeTracking/Internal/StateManager.cs, test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs, test/EFCore.Tests/TestUtilities/FakeStateManager.cs
=> Add events for entity state changes

src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
Issue #10942
No new tests because behavior is the same when using our providers.
=> Stop using old type mapper in MigrationsSqlGenerator

src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs, src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/EFCore/ChangeTracking/Internal/NavigationFixer.cs, src/EFCore/ChangeTracking/Internal/StateManager.cs, test/EFCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs
Issue #9703
Restrict now means that EF will never either set an FK to null or perform a cascade delete if an entity is deleted. This is the same as before, although the exception type may change--it's a negative case and we triaged this break as okay. However, if a navigation property is explicitly changed, then the FK associated with that navigation property will still be set to null. This is the change from the previous behavior. This changes some negative cases into positive cases, which was also triaged as okay.
=> Update DeleteBehavior.Restrict to not apply when navigations are changed

test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
@bricelam, found this while copy-pasting tests, not sure if SQL Server is actually parsing this without the semicolons?
=> Add missing semicolons in scaffolding test SQL

src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/MemberAccessBindingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was in the binding logic for NullConditionalExpression - as part of the binding we are rewriting TryReadValue method if it originally was created for non-nullable type. Without the rewrite it can sometimes throw because null would be materialized where non-nullable value was expected.
However, we only perform the rewrite if the Caller of the NCE was modified during the same visit (e.g. from qsre to t.Inner).
If the NCE is accessed from within result operator subquery, we hit a problem. During ReplaceClauseReferences in the EntityQueryableExpressionVisitor we can translate NCE caller (qsre), but we fail to translate AccessOperation (member access) because there are not QueriesBySource available in the QMV that is processing the result operator supbquery (the correct entry is stored …
=> Fix to #10627 - Query: compilation error for queries accessing null-protected property inside subquery produced by All/Any result operator

src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs, src/EFCore/Query/Internal/QueryOptimizer.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Problem was that as part of fixing #8652 we were removing explicit casts when processing result operators. This is fine for most aggregate operators, but is not correct for Min/Max. This is because the final result type is the same as the argument - original type of the argument must be preserved or we risk type mismatches in the final result.
Additionally improved the fix for #1251 - we should be stripping order by clauses for Min/Max operators as well. Previously we exempt all ChoiceResultOperatorBase, instead of correct First/Single/Last.
=> Fix to #10537 - `Specified cast not valid` when using min or max after decimal to float cast

src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, src/EFCore/Query/Internal/QueryOptimizer.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that in QueryOptimizer, if we flattened redundant subquery (Include result operator was the only element on that subquery and we strip those out) we did not update PathFromQuerySource on the IncludeResultOperator annotations with the new Qsre.
Also, in nav rewrite we were trying to match PathFromQuerySource with regular comparison, rather than using ExpressionComparer.
=> Fix to #10101 - Query: Select.Include.OrderBy ignores the include

samples/OracleProvider/test/OracleProvider.FunctionalTests/BuiltInDataTypesOracleTest.cs, samples/OracleProvider/test/OracleProvider.FunctionalTests/DataAnnotationOracleTest.cs, src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs, test/EFCore.Relational.Tests/Storage/RelationalCommandTest.cs, test/EFCore.Relational.Tests/Utilities/DbParameterCollectionExtensionsTest.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs, test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
And show AnsiString when we know it is.
Issue #10634
=> Change parameter log formatting to not show DbType = String when it isn't

src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
Note, mainline scenarios won't hit this since code is typically only generated for valid models.
Everywhere else in Migrations we already support having no primary key since it's valid for OOB tables.
Fixes #10571
=> [TINY] Migrations: Add missing primary key null check

src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs, src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs, src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/EFCore/Properties/CoreStrings.Designer.cs, src/EFCore/Properties/CoreStrings.resx, test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs, test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
Normalize warning event id names
Fixes #10918
=> Don't log convention info for temporary keys

src/EFCore.Relational/Diagnostics/MigrationTypeEventData.cs, src/EFCore.Relational/Diagnostics/RelationalEventId.cs, src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs, src/EFCore.Relational/Migrations/Internal/MigrationsAssembly.cs, src/EFCore.Relational/Properties/RelationalStrings.Designer.cs, src/EFCore.Relational/Properties/RelationalStrings.resx, test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsAssemblyTest.cs, test/EFCore.Relational.Tests/RelationalEventIdTest.cs
This can be useful when manually creating migrations.
Fixes #9920
=> Migrations: Warn when missing [Migration] attribute

src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarContext.cs, src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs, src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/LocustCommander.cs, src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/LocustHighCommand.cs, src/EFCore/Metadata/Internal/EntityTypeExtensions.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that when determining whether given navigation should be represented by INNER JOIN we were looking if it was required and its direction (dependent to principal). However if navigation is defined on derived type in TPH, it can be required and dependent to principal, and should still be represented as LEFT JOIN, because base types don't have the relationship defined for them.
Fix is to check whether navigation is not defined on derived type on top of previous checks.
=> Fix to #10988 - Query: accessing property on a required navigation defined on a derived type produces INNER JOIN

src/EFCore.Relational/Query/ExpressionVisitors/Internal/CompositePredicateExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Some optimizations that are applied to predicates in SelectExpression can be safely applied to join predicates as well. Fix modifies CompositePredicateExpressionVisitor to also look into JoinExpression predicates and not only SelectExpression predicates.
Also changes the way we build join predicates themselves, when inheritance is concerned - now the discriminator predicate will be extracted out of the comparison, so that the comparisons are sargable.
Before:
((a is Derived) ? a.DerivedFK : null) == b.PK - which translated to CASE block (not sargable)
After:
a is Derived && a.DerivedFK == b.PK
=> Fix to #9395 - Query: Apply CompositePredicateExpressionVisitor to join predicates

samples/OracleProvider/test/OracleProvider.FunctionalTests/BuiltInDataTypesOracleTest.cs, samples/OracleProvider/test/OracleProvider.FunctionalTests/ConvertToStoreTypesOracleTest.cs, samples/OracleProvider/test/OracleProvider.FunctionalTests/CustomConvertersOracleTest.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs, test/EFCore.InMemory.FunctionalTests/BuiltInDataTypesInMemoryTest.cs, test/EFCore.InMemory.FunctionalTests/ConvertToStoreTypesInMemoryTest.cs, test/EFCore.InMemory.FunctionalTests/CustomConvertersInMemoryTest.cs, test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/ConvertToStoreTypesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/GraphUpdatesSqlServerTest.cs, test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/ConvertToStoreTypesSqliteTest.cs, test/EFCore.Sqlite.FunctionalTests/CustomConvertersSqliteTest.cs
Part of #3620
Also, changed test pattern for BuiltInDataTypes tests to have configuration in the fixture which is used by tests that always run by default. This is consistent with what we do elsewhere and prevents subclasses from forgetting to add a new test method to call the base.ls.
=> Pass enum literals to type mapper for value conversion

src/EFCore/ChangeTracking/ChangeTracker.cs, src/EFCore/ChangeTracking/IEntityEntryGraphIterator.cs, src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs, src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs, src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs, test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
Issues #10540 #8226
The overload required a new argument somewhere to avoid a breaking change, so I took the opportunity to add a state parameter to the API to allow state to be passed in without capturing.
=> Make IEntityEntryGraphIterator public and add overload for TrackGraph

src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs, test/EFCore.Tests/QueryProviderTest.cs
Issue: A linq query starting from DbSet always has EntityQueryable. But for a manually created query incorrectly passes Constant(IQueryable) rather than IQueryable.Expression then we try to parametrize it and cause multiple running queries.
The fix is to not funcletize it. The Constant(DbSet) gets converted to EntityQueryable during ReLinq query parsing.
This is a negative case. The query is malformed. We would leak context instance in this case. Since it is hot path, we are not going to add overhead for all other cases.
Resolves #11043
=> Query: Don't funcletize DbSet/InternalDbSet

src/EFCore/Extensions/MutableEntityTypeExtensions.cs, src/EFCore/Extensions/MutableModelExtensions.cs, test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
Issue #9087
I remembered why ChangeTrackingStrategy is not exposed on the interfaces--we decided it wasn't part of the core model definition, and hence should be accessed through extension methods. The Get methods were already there, but the Set methods were missing.
=> Add SetChangeTrackingStrategy methods

src/EFCore.Specification.Tests/Query/InheritanceRelationshipsQueryTestBase.cs, src/EFCore.Specification.Tests/TestModels/InheritanceRelationships/BaseInheritanceRelationshipEntity.cs, src/EFCore.Specification.Tests/TestModels/InheritanceRelationships/InheritanceRelationshipsContext.cs, test/EFCore.SqlServer.FunctionalTests/Query/InheritanceRelationshipsQuerySqlServerTest.cs
Removing tests that are covered by GearsOfWar test suite:
DerivedReferenceOnBase: LocustCommander -> CommandingFaction
DerivedCollectionOnBase: LocustHighCommand -> Commanders
BaseCollectionOnDerived: LocustHorde -> Leaders
Also, enabling some additional tests that are no longer broken.
=> Fix to #10805 - Investigate skipped tests: InheritanceRelationshipsQuerySqlServerTest

src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryTestBase.cs, src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs, src/EFCore/Query/ExpressionVisitors/Internal/NavigationRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
Problem was that we were not properly updating PathFromQuerySource and QuerySource properties on IncludeResultOperator when processing SelectMany in nav rewrite. This issue is similar to #10101
=> [SMALL] Fix to #11053 - Query: include over SelectMany with reference navigation projection doesn't work

src/EFCore.Specification.Tests/DataAnnotationTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs, src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs, src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/KeyAttributeConvention.cs, src/EFCore/Metadata/Internal/EntityType.cs, src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs, test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
Run ForeignKeyPropertyDiscoveryConvention when the PK is changed.
Fixes #9180
Fixes #11019
=> Don't remove FKs when the referenced key is removed.

src/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
From_sql_queryable_simple_projection_composed compares a boolean column to 1, which is non-portable (PostgreSQL requires TRUE or FALSE literals). Went through the type mapping to properly generate a bool literal.
Originally flagged in #3548
=> Make FromSql test portable

EFCore.sln, build/dependencies.props, src/EFCore.Analyzers/EFCore.Analyzers.csproj, src/EFCore.Analyzers/Extensions.cs, src/EFCore.Analyzers/SqlInjectionDiagnosticAnalyzer.cs, test/EFCore.Analyzers.Tests/EFCore.Analyzers.Test.csproj, test/EFCore.Analyzers.Tests/SqlInjectionDiagnosticAnalyzerTest.cs, test/EFCore.Analyzers.Tests/TestUtilities/DiagnosticAnalyzerTestBase.cs
A new EF Core Analyzer that detects some common potential SQL injection patterns. Currently looks at ```FromSql```, ```ExecuteSqlCommand/Async``` and ```DbCommand.CommandText``` APIs.
Works by inspecting the SQL argument expression (either passed directly, or by walking up any local variable chain), and pattern matching the expression for:
- Calls to String.Format, Concat, '+', Insert, Replace, Join involving any local variable or parameter data.
- Uses of interpolated strings that use local variable or parameter data in places that don't end up resolving to an overload that accepts ```FormattableString```.
See unit tests for examples of patterns.
TBD: Figure out packaging of this.
cc @blowdart
=> Analyzers: Part of #10080 - Adds potential SQL injection analysis.

src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs, src/EFCore/Infrastructure/ModelValidator.cs, test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs, test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs, test/EFCore.SqlServer.Tests/Scaffolding/SqlServerCodeGeneratorTest.cs, test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs, test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs, test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
Don't generated implicitly-typed array for seed data in the snapshot
Fixes #11083
Fixes #11097
=> Don't throw on missing discriminator in seed data

src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/AsyncQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/QueryTestBase.cs, src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs, src/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs, src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs
Problem was that for async include on derived entity we produce the following fixup task and await it:
fixup: (QueryContext queryContext | Gear entity | object[] included | CancellationToken ct) =>
{
return (entity is Officer) ? Task queryContext.QueryBuffer.IncludeCollectionAsync(...) : default(Task)
}
this results in null-value task in case the entity is not of the derived type, and we try to await on it. Fix is to check that the fixup is not null before awaiting.
Also added a lot of include tests for async - ported AssertIncludeQuery test helper and most of the gears of war include tests.
=> Fix to #10440 - Query: Include on derived throws in async

src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs, src/EFCore/Query/QueryCompilationContext.cs, test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
=> QueryBuffer is required when derived types of querying types are having shadow props

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
ConditionalExpression requires test to be bool type. When an optional navigation is projected out with other conditions, it coerce everything to nullable bool. When trying to convert to conditional block it fails because test becomes of type nullable bool. The fix is to apply cast before creating ConditionalExpression
Resolves #9275
=> Query: Apply appropriate cast before converting to conditional block in projection

src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that when processing Join/GroupJoin/SelectMany, we replace the existing Expression with a new methodcall expression representing updated Join/GroupJoin/SelectMany. However, if the clause that's being processed required outer parameter injection (e.g. as part of the Join/GroupJoin key), that information would be lost.
Fix is to only replace/update the correct fragment of the Expression, rather than its entirety. We also need to add compensation for GroupJoinDefaultIfEmpty processing, which was not able to handle case where InjectParameters was wrapping the GroupJoin method.
=> Fix to #10122 - No value provided for required parameter '_outer_Id'

src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/AsyncGearsOfWarQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Problem was that in RequiresMaterializationExpressionVisitor tried to access a dictionary based on querySource that could in some cases be null. Fix is to check that the value we are about to use as key is not null.
=> [TINY] Fix to #11007 - ArgumentNullException with Concat

src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs, test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
Adding cast to int? so that it doesn't throw for in memory. If we wanted to compensate for the case we would have to rewrite the OrderBy to accept int?
=> [TINY] Fix to #10060 - Test: OrderBy OptionalNav.Property fails for InMemory

src/Shared/SharedTypeExtensions.cs, test/EFCore.Tests/Metadata/Internal/EntityTypeTest.cs
=> Allow discovery of PropertyInfo/FieldInfo in base type when using AddProperty with a string

src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/Query/AsyncGearsOfWarQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs, test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Convert Not(...) on top level projection to conditional block in SQL
Issue: Our logic to identity search condition was missing Not nodetype. So when we encountered it on top level projection, we did not modify it assuming it is a value but that causes invalid SQL
Resolves #9944
=> Friday eve bugs burndown

src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs, src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs, src/EFCore/ChangeTracking/MemberEntry.cs, src/EFCore/ChangeTracking/PropertyEntry`.cs, test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
Fixes #9856
The fix is to add a ValueComparer for this mapping so that it does deep comparison. Testing revealed a couple of bugs in ValueCompaer--they were not being used when explicitly setting CurrentValue or OriginalValue.
Providers: This is only done for SQL Server, since this is a SQL Server-specific mechanism, but it is possible other providers have similar issues.
=> Don't mark rowversion as modified if the token hasn't changed

src/EFCore.Relational/Query/ExpressionVisitors/Internal/ResultTransformingExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs, src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs, src/EFCore.Relational/Query/Expressions/SelectExpression.cs, src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs, src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs, src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs, src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs, src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs, src/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.Objects.cs, src/EFCore.SqlServer/Query/ExpressionVisitors/Internal/SqlServerSqlTranslatingExpressionVisitorFactory.cs, src/EFCore.Sqlite.Core/Query/ExpressionVisitors/Internal/SqliteSqlTranslatingExpressionVisitorFactory.cs, src/EFCore/Query/EntityQueryModelVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionOptimizingVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/QuerySourceReferenceFindingExpressionVisitor.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, src/EFCore/Query/Internal/IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs, test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
Query: Improvements to Relational GroupBy translation for composition
- Add support for translating OrderBy after GroupBy operator
- Add support for `HAVING` clause in SQL which would be generated when translating predicate after GroupByAggregate Resolves #10870
- Make sure client eval warning is not issued when translating GroupByAggregate Resolves #11157
- GroupBy Aggregate works when element/result selector is DTO instead of anonymous type Resolves #11176 (KeySelector has to be client evaluated)
- Make sure that SQL added to GROUP BY clause is not aliased Resolves #11218
- Translate GroupBy Constant/Parameter with aggregates Resolves #9969
Part of #10012 
Part of #2341
=> Query: Improvements to Relational GroupBy translation for composition

src/EFCore.Specification.Tests/DataAnnotationTestBase.cs, src/EFCore/Metadata/Conventions/Internal/BaseTypeDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs, src/EFCore/Metadata/Conventions/Internal/OwnedEntityTypeAttributeConvention.cs, src/EFCore/Metadata/Internal/EntityType.cs, src/EFCore/Metadata/Internal/EntityTypeExtensions.cs, src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs, src/EFCore/Metadata/Internal/InternalModelBuilder.cs, src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs, src/Shared/PropertyInfoExtensions.cs, test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs, test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs, test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs, test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs, test/EFCore.Tests/ModelBuilding/TestModel.cs
Handle OwnedAttribute correctly
Convert types to owned in a more robust way
Fixes #11074
Fixes #11152
=> Don't discover collection of string as navigation

src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs, src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs, src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs, test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
=> Query: Client eval when doing joins after GroupByAggregate

src/EFCore.Design/EFCore.Design.csproj, src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj, src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj, test/Directory.Build.props
Right now VS for Mac cannot work with multiple tfms and picks first one only.
It also cannot use dotnet SDK from path and uses the pre-installed one (which is not dogfood SDK)
This will still keep net461 as first tfm in tests for windows so that TestDriven.net still works
=> VS 4 Mac: make sure netcoreapp2.0 is first tfm in all projects
