dotnet/efcore

- test/EFCore.Tests/DbContextTest.cs
Issue #8264, which was already fixed in 2.0 by the changes Attach/TrackGraph handling.
> Add test for key generation when setting Added state after Unchanged state

- build/dependencies.props
React to https://github.com/aspnet/Microsoft.Data.Sqlite/pull/378
See also https://github.com/aspnet/BuildTools/pull/285
> Upgrade SQLitePCLRaw to 1.1.7

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
- src/EFCore.Design/Design/Internal/OperationLoggerProvider.cs
- src/EFCore.Design/Scaffolding/Internal/ScaffoldingServiceCollectionExtensions.cs
- src/EFCore.Relational.Design.Specification.Tests/ReverseEngineering/E2ETestBase.cs
- test/EFCore.Design.Tests/Design/Internal/OperationLoggerTest.cs
- test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
- test/EFCore.Sqlite.Design.FunctionalTests/ReverseEngineering/SqliteE2ETestBase.cs
- test/EFCore.Sqlite.Design.FunctionalTests/SqliteDatabaseModelFactoryTest.cs
- test/EFCore.Sqlite.Design.FunctionalTests/SqliteScaffoldingModelFactoryTest.cs
> RevEng: Show verbose provider messages

- src/EFCore.Relational.Specification.Tests/TestSqlLoggerFactory.cs
- src/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
Confirmed that #8378 is already fixed.
> Adds a regression test for #8378

- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Utilities/SqlServerConditionAttribute.cs
- test/EFCore.SqlServer.FunctionalTests/Utilities/TestEnvironment.cs
Refactor SqlServerDatabaseCreatorTest
Part of #8615
> Disable SqlServerDatabaseCreatorTest on CI

- src/EFCore.Relational/Storage/Internal/RelationalCommand.cs
> Don't dispose DbCommand before logging

- test/EFCore.Design.Tests/Design/OperationExecutorTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
- test/EFCore.Sqlite.Tests/Migrations/SqliteHistoryRepositoryTest.cs
I got overwhelmed trying to remove all the usages, but I felt obligated to remove mine.
Part of #7627
> Remove some usages of Moq

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Tests/ChangeTracking/EntityEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/StateManagerTest.cs
> Stop returning detached entries from the ChangeTracker

- src/EFCore.Relational.Specification.Tests/ConcurrencyDetectorRelationalTest.cs
- src/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.InMemory.FunctionalTests/ConcurrencyDetectorInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/DatabaseErrorLogStateTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConcurrencyDetectorSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/ConcurrencyDetectorSqliteTest.cs
Issue #8305
Also, updated text for recursive call to OnConfiguring since in my investigation this was often the first error seen in invalid multi-threading scenarios.
> More tests for ConcurrencyDetector

- src/EFCore/EntityFrameworkServiceCollectionExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
> Reenable DbContext pooling test

- src/EFCore.Relational/Storage/Internal/RelationalCommand.cs
I scanned all product code and these were the only two places I found doing it.
Fixes #9041
> Don't use disposed objects

- src/EFCore.Design/Design/Internal/AppServiceProviderFactory.cs
- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- test/EFCore.Design.Tests/Design/Internal/AppServiceProviderFactoryTest.cs
- test/EFCore.Design.Tests/TestUtilities/TestAppServiceProviderFactory.cs
> Design: Continue on BuildWebHost errors

- build/common.props
> Add NETStandard.Library.NETFramework for older versions of Visual Studio

- src/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NorthwindQuerySqlServerFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteFixture.cs
> Revert warning-as-error default for ignored includes

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
This was removed some time ago in the CLI tools
> PMC Tools: Remove -Environment

- src/EFCore.Relational.Specification.Tests/Query/ComplexNavigationsOwnedQueryRelationalFixtureBase.cs
- src/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryFixtureBase.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqliteFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/OwnedQuerySqliteTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Add validation for principal owned types, non-owner navigations to owned types and table splitting with a derived type.

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalEntityEntryTestBase.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalMixedEntityEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalShadowEntityEntryTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
Fix shadow owned types.
Fixes #9086
> Properly track dependent entities when queried.

- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
> [SMALL] SqlServer: Throw better during EnsureDelete when no database name

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/breakingchanges.netcore.json
- src/EFCore.Design/breakingchanges.netframework.json
- src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
> Fix migration snapshot for owned types

- src/EFCore.Relational.Design.Specification.Tests/Migrations/ModelSnapshotTest.cs
- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
> Fix .HasIndex generic type argument for owned types

- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Improve parametrization of variables from nested closure

- src/dotnet-ef/Project.cs
This reverts commit 3d7ecc984b72bbd9b693a1cefe97fc48ffde6f5a.
Reverts #8963
> Revert "Remove GetTempFileName"

- src/EFCore.Design/Design/ICSharpHelper.cs
- src/EFCore.Design/Design/Internal/CSharpHelper.cs
'Tis a silly unused overload...
> [2.0.0] Design: Remove a nonsensical overload of ICSharpHelper.Lambda()

- src/EFCore/DbFunctionsExtensions.cs
> Update docs for Like

- .travis.yml
- appveyor.yml
@bricelam - I believe you would like this too. 😄
> Build feature branches on remote CI

- build/dependencies.props
> Update to Roslyn RTM

- build/dependencies.props
> Update DependencyModelVersion to 2.0.0-*

- build/dependencies.props
> Update DependencyModelVersion to 2.0.0-* (#9162)

- build/common.props
- build/dependencies.props
> Rename variable to NETStandardLibraryNETFrameworkVersion

- src/dotnet-ef/ProjectOptions.cs
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/dotnet-ef/RootCommand.cs
> [2.0.0] CLI Tools: Add --no-build

- EFCore.Benchmarks.sln
- benchmarks/EFCore.Benchmarks.EFCore1/CalibrationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/DbSetOperationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/FixupTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/EFCore.Benchmarks.EFCore1.csproj
- benchmarks/EFCore.Benchmarks.EFCore1/Extensions.cs
- benchmarks/EFCore.Benchmarks.EFCore1/InitializationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/AdventureWorks/AdventureWorksContext.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/AdventureWorks/AdventureWorksFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/Orders/OrdersContext.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/Orders/OrdersFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Program.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Properties/AssemblyInfo.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/FuncletizationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/NavigationsQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/QueryCompilationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/RawSqlQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/SimpleQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/UpdatePipeline/SimpleUpdatePipelineTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/config.json
- benchmarks/EFCore.Benchmarks/BenchmarkSummaryProcessor.cs
- benchmarks/EFCore.Benchmarks/EFCore.Benchmarks.csproj
- build/dependencies.props
> Benchmarks: Create new project to benchmark EF Core 1.1.2

- EFCore.Benchmarks.sln
- benchmarks/EFCore.Benchmarks.EFCore2/CalibrationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/DbSetOperationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/FixupTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/EFCore.Benchmarks.EFCore2.csproj
- benchmarks/EFCore.Benchmarks.EFCore2/Extensions.cs
- benchmarks/EFCore.Benchmarks.EFCore2/InitializationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/AdventureWorks/AdventureWorksContext.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/AdventureWorks/AdventureWorksFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/Orders/OrdersContext.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/Orders/OrdersFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Program.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Properties/AssemblyInfo.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/FuncletizationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/NavigationsQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/QueryCompilationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/RawSqlQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/SimpleQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/UpdatePipeline/SimpleUpdatePipelineTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/config.json
- benchmarks/EFCore.Benchmarks/BenchmarkSummaryProcessor.cs
- benchmarks/EFCore.Benchmarks/EFCore.Benchmarks.csproj
- build/dependencies.props
> Benchmarks: Create new project to benchmark EF Core 2.0.0

- build/dependencies.props
- src/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
* Change xunit version in specs to 2.2.0
* Disable unreliable tests
> Change xunit version in specs to 2.2.0 (#9250)

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/IncludeQueryResultAsserter.cs
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore.Specification.Tests/TestHelpers.cs
- src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- src/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarModelInitializer.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- src/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
Making gears of war verification more comprehensive, also removing a lot of code (about 1000 lines)
> Converting GearsOfWar tests to use AssertQuery verification infrastructure

- EFCore.Benchmarks.sln
- benchmarks/EFCore.Benchmarks.EFCore2/CalibrationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/DbSetOperationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/ChangeTracker/FixupTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/EFCore.Benchmarks.EFCore2.csproj
- benchmarks/EFCore.Benchmarks.EFCore2/Extensions.cs
- benchmarks/EFCore.Benchmarks.EFCore2/InitializationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/AdventureWorks/AdventureWorksContext.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/AdventureWorks/AdventureWorksFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/Orders/OrdersContext.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Models/Orders/OrdersFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Program.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Properties/AssemblyInfo.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/FuncletizationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/NavigationsQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/QueryCompilationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/RawSqlQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/Query/SimpleQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/UpdatePipeline/SimpleUpdatePipelineTests.cs
- benchmarks/EFCore.Benchmarks.EFCore2/config.json
- benchmarks/EFCore.Benchmarks/EFCore.Benchmarks.csproj
- build/dependencies.props
- build/repo.props
Use 2.0 released packages for common library
Update to 2.0 final release once available on NuGet.
> Benchmarks: Project for EF Core 2.0.0 Preview 2

- EFCore.Benchmarks.sln
- benchmarks/EFCore.Benchmarks.EFCore1/CalibrationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/DbSetOperationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/ChangeTracker/FixupTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/EFCore.Benchmarks.EFCore1.csproj
- benchmarks/EFCore.Benchmarks.EFCore1/Extensions.cs
- benchmarks/EFCore.Benchmarks.EFCore1/InitializationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/AdventureWorks/AdventureWorksContext.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/AdventureWorks/AdventureWorksFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/Orders/OrdersContext.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Models/Orders/OrdersFixture.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Program.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Properties/AssemblyInfo.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/FuncletizationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/NavigationsQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/QueryCompilationTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/RawSqlQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/Query/SimpleQueryTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/UpdatePipeline/SimpleUpdatePipelineTests.cs
- benchmarks/EFCore.Benchmarks.EFCore1/config.json
- benchmarks/EFCore.Benchmarks/EFCore.Benchmarks.csproj
- build/dependencies.props
> Benchmarks: Add project for EF Core version 1.1.2

- build/dependencies.props
- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsOwnedQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsOwnedQuerySqliteTest.cs
> Query: Upgrade version of Remotion.Linq

- src/EFCore.Relational/Query/ExpressionVisitors/Internal/CompositeShaper.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
> Don't use reflection on the compiled materializer lambda

- src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Set metadata appropriately
Resolves #9323 
resolves #9333 
resolves #9334
> RevEng: Remove redundant warnings & checks

- test/EFCore.Design.Tests/EFCore.Design.Tests.csproj
> Add Missing DependencyModel reference

- EFCore.sln.DotSettings
- build/dependencies.props
- src/EFCore.Relational.Specification.Tests/RelationalServiceCollectionExtensionsTest.cs
- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryTestBase.cs
- test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj
- test/EFCore.Relational.Tests/EFCore.Relational.Tests.csproj
- test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
- test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/EFCore.SqlServer.Tests.csproj
- test/EFCore.SqlServer.Tests/Storage/SqlServerSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
- test/EFCore.Sqlite.FunctionalTests/EFCore.Sqlite.FunctionalTests.csproj
- test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
- test/EFCore.Sqlite.Tests/EFCore.Sqlite.Tests.csproj
- test/EFCore.Sqlite.Tests/SqliteModelValidatorTest.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
- test/ef.Tests/AppDomainOperationExecutorTest.cs
- test/ef.Tests/SimpleProjectTest.cs
> Upgrade xUnit version

- src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
- src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
> RevEng: Remove unused resources

- src/EFCore/Properties/Microsoft.EntityFrameworkCore.rd.xml
> Improve change tracking perf on .NET Native

- src/Microsoft.EntityFrameworkCore.Design/Design/Internal/DbContextOperations.cs
- test/Microsoft.EntityFrameworkCore.Design.Tests/Design/Internal/DbContextOperationsTest.cs
- test/Microsoft.EntityFrameworkCore.Design.Tests/Microsoft.EntityFrameworkCore.Design.Tests.csproj
> [1.1.3] Design: Get DbContext from application services if possible

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/ef/Commands/DbContextInfoCommand.cs
- src/ef/Commands/DbContextScaffoldCommand.cs
- src/ef/Commands/MigrationsAddCommand.cs
- src/ef/Commands/MigrationsRemoveCommand.cs
- src/ef/Json.cs
- test/ef.Tests/JsonTest.cs
> [2.0.1] Tools: Handle null in "ef migrations remove --json"

- src/EFCore.Specification.Tests/TestModels/ConcurrencyModel/F1Context.cs
- src/EFCore.Specification.Tests/TestModels/ConcurrencyModel/Team.cs
> Replace references to Sir Richard

- src/EFCore/DbContext.cs
- Update the `DbContext.OnConfiguring` docs, to state that the base implementation does nothing.
> Updated that the base method is a noop.

- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
> Throw if both sides of a one-to-one relationship can use the PK properties

- src/EFCore.Specification.Tests/Query/IncludeAsyncTestBase.cs
> Reenable deadlocking test

- src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
> [2.0.1] Prevent stack overflow for self-referencing PK-to-PK relationships

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
These tests were added in 1.1.3 patch to fix a regression. The code has been reworked so the fix doesn't have to be ported but the tests still provide value.
> adding some complex query binding tests

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
To fix AppVeyor
Will merge if AppVeyor passes.
> Test: Update deadlocking test in QueryBugsTest

- src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore/Properties/AssemblyInfo.cs
- test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs
> Fixes version dependent tests and properties for 1.1.3

- src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore/Properties/AssemblyInfo.cs
- test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs
> Fixes version dependent tests for 1.0.5

- src/EFCore.Relational/Internal/RelationalPropertyExtensions.cs
> Quirk RelationalPropertyExtensions.GetConfiguredColumnType()

- src/EFCore.Specification.Tests/Query/ComplexNavigationsOwnedQueryFixtureBase.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Throw on configuring an entity type as an owned entity type

- .travis.yml
- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
> Test: At times we need to wait :)

- .travis.yml
- appveyor.yml
Since feature branch configuration was not specified in feature branch it was not being built.
> Update Travis/AppVeyor files to include feature branches

- src/EFCore.Design/Metadata/Internal/ScaffoldingAnnotationNames.cs
> [TINY] RevEng: Remove unused Scaffolding annotations

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
> [2.0.1] Don't try to detach the same relationship twice.

- src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
- test/EFCore.Relational.Tests/Utilities/RelationalLoggerExtensionsTest.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
> Improve logging of datetime DbParameter values

- src/EFCore.InMemory/Diagnostics/InMemoryEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Internal/RelationalPropertyExtensions.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/TestHelpers.cs
- src/EFCore.SqlServer/Diagnostics/SqlServerEventId.cs
- src/EFCore.Sqlite.Core/Diagnostics/SqliteEventId.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Query/Internal/IncludeCompiler.cs
> Update existing 2.0.1 quirks to use issue number

- Directory.Build.props
> Remove reference to NETStandard.Library.NETFramework

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/Expected/NonNullBoolWithDefault.cs
- test/EFCore.SqlServer.Design.FunctionalTests/ReverseEngineering/SqlServerE2ETests.cs
> [2.0.1] RevEng: Don't generate nullable bool if default value is false

- src/EFCore/Infrastructure/IModelCustomizer.cs
- test/EFCore.InMemory.FunctionalTests/DatabaseInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/ModelSourceTest.cs
- test/EFCore.Tests/DbContextOptionsTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
- test/EFCore.Tests/ModelSourceTest.cs
> Improve IModelCustomizer doc comment

- src/EFCore.Relational/Storage/RelationalDataReader.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Merge feature/2.0.1

- Directory.Build.props
- src/EFCore.Tools.DotNet/EFCore.Tools.DotNet.nuspec
- src/EFCore.Tools/EFCore.Tools.nuspec
> Improve NuGet tags

- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Conventions/Internal/ChangeTrackingStrategyConvention.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
> Move change tracking flag setting to ModelBuiltConvention

- .gitignore
- Directory.Build.targets
- NuGet.config
- build/dependencies.targets
- Adding the patch feed
- Adding the generated list of packages that should be changed from AspNetCoreVersion
> [2.0.1] Update references to other 2.0.1 patch packages

- src/EFCore.Relational/Infrastructure/EntityFrameworkRelationalServicesBuilder.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparerDependencies.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerDependencies.cs
- src/EFCore/EntityFrameworkServiceCollectionExtensions.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.Relational.Tests/TestUtilities/RelationalTestHelpers.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
These will allow to create `CommandBatchPreparer` and `StateManager` instances on demand.
> Add CommandBatchPreparerDependencies and StateManagerDependencies

- src/EFCore.Sqlite.Core/Migrations/SqliteMigrationsSqlGenerator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
> SQLite Migrations: Rebuild renamed indices

- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/PropertyEntrySqliteTest.cs
aspnet/Microsoft.Data.Sqlite#420 started inferring `SqliteParameter.Size` from the value.
> React to aspnet/Microsoft.Data.Sqlite#420

- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
> RevEng: Do not sanitize directory names while generating namespace

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/ChangeTracking/Internal/IInternalEntityEntryFactory.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/ShadowValuesFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/SnapshotFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/PropertyAccessorsFactory.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> Use EntityMaterializerSource to create entities from property bags

- src/EFCore/Properties/CoreStrings.resx
Fixed spelling mistake in CoreStrings.resx. Changed "sharin" to "sharing".
> Fixed spelling mistake

- samples/OracleProvider/Directory.Build.props
- samples/OracleProvider/Directory.Build.targets
- samples/OracleProvider/README.md
- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleProvider.FunctionalTests.csproj
Steps to build
```
.\build /t:Pin
cd samples\OracleProvider
dotnet restore
.\OracleProvider.sln
```
> Build: Make sure OracleProvider.sln works

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
> Resolves #9820 use-database-names for Scaffolding DBContext columns

- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
> Convert UdfDbFunctionSqlServerTests to use AssertSql pattern

- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder.cs
- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
> Add data seeding support for owned types

- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleProvider.FunctionalTests.csproj
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/AsyncGroupByQueryOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/GroupByQueryOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/SimpleQueryOracleTest.cs
> Update GroupBy tests for Oracle

- test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
> Linux test

- src/Microsoft.EntityFrameworkCore.SqlServer.Design/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.SqlServer/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.Sqlite.Design/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore.Sqlite/Properties/AssemblyInfo.cs
- src/Microsoft.EntityFrameworkCore/Properties/AssemblyInfo.cs
- test/Microsoft.EntityFrameworkCore.Tests/ModelSourceTest.cs
Similar to previous updates we made to fix tests in 1.x.
> Version updates

- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Update parameter prefix for query filter

- Directory.Build.props
react to https://github.com/aspnet/BuildTools/pull/419
This is needed to build in VS.
@natemcmaster
> Set RepositoryRoot

- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/FiltersOracleTest.cs
- src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Change prefix for Query Filter parameters

- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleEndToEndTest.cs
@anpete  Can_save_changes test correction!
Solved, and @AndriySvyryd had already caught my attention before, I had switched to testing due to locality.
> Can_save_changes test correction

- samples/OracleProvider/src/OracleProvider/Diagnostics/OracleEventId.cs
This is a small name fix, From SQL Server for Oracle.
> Correction of name

- src/EFCore.Relational/Storage/RelationalDataReader.cs
Issue #10147
* MySQL provider sometimes has null Parameters collection
* MySQL provider sometimes throws when asking for records affected
Fix is to be defensive in our code and we will file issues on MySQL provider
> By defensive with command and reader access due to issues with MySQL provider

- samples/CompiledQueries/CompiledQueries.csproj
- samples/CompiledQueries/Model/AdventureWorksContext.cs
- samples/CompiledQueries/Model/Customer.cs
- samples/CompiledQueries/Program.cs
- samples/CompiledQueries/README.md
- samples/DbContextPooling/DbContextPooling.csproj
- samples/DbContextPooling/Program.cs
- samples/DbContextPooling/README.md
- samples/Samples.sln
- samples/Samples.sln.DotSettings
Adds Explicit Compiled Queries and DbContext Pooling samples.
> Adds Explicit Compiled Queries and DbContext Pooling samples.

- src/EFCore/Internal/TypeExtensions.cs
- test/EFCore.Tests/Utilities/TypeNameHelperTest.cs
> Improve perf of TypeNameHelper

- src/EFCore.Relational/Storage/RelationalDataReader.cs
> Remove defensive code

- src/EFCore.Design/EFCore.Design.csproj
- src/EFCore.Relational/EFCore.Relational.csproj
- test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
> Remove unused references

- test/EFCore.SqlServer.FunctionalTests/EFCore.SqlServer.FunctionalTests.csproj
> Test: Run SqlServer.FunctionalTests in own group

- .appveyor.yml
- test/EFCore.SqlServer.FunctionalTests/config.json
> Upgrade SqlServer LocalDb version to 2016

- src/EFCore/Infrastructure/ModelValidator.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
> Detect temporary values in data seeds during validation.

- src/EFCore.SqlServer/SqlServerRetryingExecutionStrategy.cs
Small change to simplify code.
> Simplify code

- src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Storage/IRelationalDatabaseCreator.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreatorDependencies.cs
- src/EFCore.Relational/breakingchanges.netcore.json
- test/EFCore.Relational.Tests/TestUtilities/FakeProvider/FakeRelationalDatabaseCreator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
fixes #2943
- also fixes a test localization bug causing test failure on non US systems.
> Add GenerateCreateScript extension method on DatabaseFacade

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
(also broke long lines)
Resolves #9530
Manually verified.
> RevEng: Scaffold annotations for key found by convention/annotation

- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
Previously, when we encountered this type of expression we would produce LEFT JOIN in the SelectExpression but at the same time rewrite the query model, pruning the GJ and DIE clauses, replacing it with regular join clause.
This is problematic, because QM no longer adequately represents the query that is being generated - if the new QM were visited again, we would produce INNER JOIN.
Fix is to not modify the QM, but instead keep track of additional from clauses that were flattened (and not visit them in the VisitAdditionalFromClause), as well as properly remap query/shapers to point to additional from clause, rather than the join.
> Improving logic around visiting and flattening GroupJoin-SelectMany-DefaultIfEmpty queries.

- src/EFCore.Tools/tools/EntityFrameworkCore.psd1
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Project.cs
- version.props
Fixes #10298 
Verification: Manually tested
> [2.0.2] Tools: Force runtime configuration file generation

- test/ef.Tests/TestUtilities/TempDirectory.cs
> Tests: Make TempDirectory more robust

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
> Add seed data batching

- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
> Disable flaky tests on Ubuntu

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
> [2.0.2] PMC Tools: Handle unicode in project.assets.json

- EFCore.Runtime.sln
- src/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- src/EFCore.Relational/Diagnostics/BatchEventData.cs
- src/EFCore.Relational/Diagnostics/MinBatchSizeEventData.cs
- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/TransactionEnlistedEventData.cs
- src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.Relational/Update/Internal/BatchExecutor.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/CommandBatchPreparerDependencies.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore/DbLoggerCategory.cs
- test/EFCore.Relational.Tests/RelationalEventIdTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTransactionExtensionsTest.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
- test/EFCore.Tests/Infrastructure/DiagnosticsLoggerTest.cs
- tools/Resources.tt
> Add more logging to the update pipeline.

- EFCore.sln
- build/repo.props
- samples/OracleProvider/OracleProvider.sln
- samples/OracleProvider/src/OracleProvider/Query/ExpressionTranslators/Internal/OracleStringSubstringTranslator.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleProvider.FunctionalTests.csproj
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/SimpleQueryOracleTest.cs
- src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- src/EFCore.Specification.Tests/TestUtilities/Xunit/FrameworkSkipConditionAttribute.cs
Add Oracle.FunctionalTests into Core.sln
> Fix Oracle build break

- EFCore.Runtime.sln
- EFCore.sln
- samples/OracleProvider/OracleProvider.sln
- src/EFCore.Attributes/EFCore.Attributes.csproj
- src/EFCore.Attributes/OwnedAttribute.cs
- src/EFCore.Attributes/baseline.netcore.json
- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore/EFCore.csproj
- src/EFCore/Metadata/Builders/OwnedEntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/OwnedEntityTypeBuilder`.cs
- src/EFCore/Metadata/Conventions/Internal/OwnedEntityTypeAttributeConvention.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/ModelBuilder.cs
- test/EFCore.Tests/ApiConsistencyTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipTypeTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericUnqualifiedStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/ef.Tests/AppDomainOperationExecutorTest.cs
- test/ef.Tests/SimpleProjectTest.cs
Change owned entity type configuration API.
Part of #9487
> Add Microsoft.EntityFrameworkCore.Attributes assembly

- src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
> Test: Cross compile Specification.Tests with netcoreapp2.1

- src/EFCore.InMemory/Diagnostics/InMemoryEventId.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
- src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- src/EFCore.Relational/Scaffolding/Internal/TableSelectionSet.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.Relational/Update/Internal/BatchExecutor.cs
- src/EFCore.Specification.Tests/UpdatesTestBase.cs
- src/EFCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs
- src/EFCore/Extensions/TransactionsDatabaseFacadeExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/IDbContextTransactionManager.cs
- src/EFCore/Storage/ITransactionEnlistmentManager.cs
- src/EFCore/breakingchanges.netcore.json
- test/EFCore.InMemory.FunctionalTests/EFCore.InMemory.FunctionalTests.csproj
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
> Revert TableSelectionSet and IDbContextTransactionManager breaking changes.

- EFCore.sln.DotSettings
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Diagnostics/ExecutionStrategyEventData.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Storage/ExecutionStrategy.cs
- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlExceptionFactory.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestRelationalTransaction.cs
- test/EFCore.Tests/Infrastructure/CoreEventIdTest.cs
- tools/Resources.tt
> Add logging to ExecutionStrategy

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
Fixes #10338
Manually verified:
> PMC Tools: Redirect standard error

- test/EFCore.Tests/DbContextServicesTest.cs
Use both a public constructor for the typed options and a protected constructor for the un-typed options on a DbContext type that is intended to be both instantiated and inherited from in the same service provider.
> Test for pattern suggested by @greggbjensen in #7533

- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Infrastructure/ModelValidatorDependencies.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/breakingchanges.netcore.json
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
- test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
- test/EFCore.Sqlite.Tests/SqliteModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/CoreEventIdTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
> Add more logging to the model builder

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Migrations: Test owned types, table splitting, and inheritance more

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
Pairs model objects earlier to enable better diffing of subsequent objects.
Yes, the author date is correct, this has been sitting in a branch for over a year. 😉
> Migrations: Enhance DiffContext in MigrationsModelDiffer

- src/EFCore.Relational/Storage/RelationalTypeMapper.cs
The internals of RelationalTypeMapper have changed significantly to support type conversions. While this was done in a way that should not break 2.0 providers, it turns out that some 2.0 providers take an interesting approach involving throwing exceptions on methods that were not previously called but now can be. To workaround this, if the provider has not been updated--detected by still calling the obsolete constructor--then the RelationalTypeMapper falls back to working in a similar way to how it did before, which should be much less likely to cause issues. This means type conversions is a feature that needs a new provider, but in general that was already the case.
See also #10654
> Allow RelationalTypeMapper to run in a legacy mode for 2.0 providers

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
Issue #10638
Also adds tests so that new annotations without any handling are detected.
For value conversions, only the store type is serialized since it is not possible to serialize an arbitrary ValueConveter. This is an area that will need more testing.
> Handle value conversion annotations in code generation.

- samples/OracleProvider/src/OracleProvider/Internal/OracleLoggerExtensions.cs
- src/EFCore.InMemory/Extensions/Internal/InMemoryLoggerExtensions.cs
- src/EFCore.Relational/Internal/RelationalLoggerExtensions.cs
- src/EFCore.Specification.Tests/TestUtilities/ListLogger.cs
- src/EFCore.SqlServer/Internal/SqlServerLoggerExtensions.cs
- src/EFCore.Sqlite.Core/Internal/SqliteLoggerExtensions.cs
- src/EFCore/Diagnostics/EventDefinition.cs
- src/EFCore/Diagnostics/EventDefinitionBase.cs
- src/EFCore/Diagnostics/EventDefinition`.cs
- src/EFCore/Diagnostics/EventDefinition``.cs
- src/EFCore/Diagnostics/EventDefinition```.cs
- src/EFCore/Diagnostics/EventDefinition````.cs
- src/EFCore/Diagnostics/EventDefinition`````.cs
- src/EFCore/Diagnostics/EventDefinition``````.cs
- src/EFCore/Diagnostics/FallbackEventDefinition.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.Tests/DbContextServicesTest.cs
- test/EFCore.Tests/Infrastructure/DiagnosticsLoggerTest.cs
> Consistently do a short-circuit check in logging extensions

- src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- test/EFCore.Sqlite.FunctionalTests/TransactionSqliteFixture.cs
Fixes aspnet/Microsoft.Data.Sqlite#476
> [2.0.2] React to aspnet/Microsoft.Data.Sqlite#475

- src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyBuilderAnnotations.cs
- src/EFCore.Relational/RelationalReferenceCollectionBuilderExtensions.cs
- src/EFCore.Relational/RelationalReferenceOwnershipBuilderExtensions.cs
- src/EFCore.Relational/RelationalReferenceReferenceBuilderExtensions.cs
- test/EFCore.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerInternalMetadataBuilderExtensionsTest.cs
- test/EFCore.Sqlite.Tests/Metadata/Internal/SqliteInternalMetadataBuilderExtensionsTest.cs
> Undo a breaking change on Internal API

- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNodeBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Modified IncludeCompiler to bring in eager loaded navigations when building the include load tree.
> Fix: #9210: Owned type is not being included on a query that includes its owner type as a navigation property.

- samples/OracleProvider/src/OracleProvider/Metadata/OraclePropertyAnnotations.cs
- samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs
- samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs
Resolves #10380
✔️Create Column
✔️Create Index
✔️Rename Table
✔️Rename Column
✔️Rename Index
✔️Drop Index
✔️Drop Column
✔️Drop Table
```sql
DECLARE
v_Count INTEGER;
BEGIN
SELECT COUNT(*) INTO v_Count FROM all_tables t WHERE t.table_name = N'__EFMigrationsHistory'
IF v_Count = 0 THEN
EXECUTE IMMEDIATE
'
CREATE TABLE "__EFMigrationsHistory" (
"MigrationId" NVARCHAR2(150) NOT NULL,
"ProductVersion" NVARCHAR2(32) NOT NULL,
CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)
';
END IF;
END;
GO
CREATE TABLE "Product" (
"Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
"Description" NVARCHAR2(450) DEFAULT ('BOOK') NULL,
"Quanty" NUMBER(10) NOT NULL,
"Price" NUMBER(29,4) NOT NULL,
"Date" TIMESTAMP NOT NULL,
"Logo" BLOB NULL,
CONSTRAINT "PK_Product" PRIMARY KEY ("Id")
)
GO …
```
> Migration Fix for Oracle

- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Changes:
* Stronger matching by table, column, and property names
* Match by root entity types before others (fixes #10099)
> Migrations: Better matching

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
Issue has already been fixed as side-effect of another change.
> [TINY] Adding test for #10711 - Support ArrayIndex expressions in where clause

- samples/OracleProvider/test/OracleProvider.FunctionalTests/SequenceEndToEndTest.cs
- test/EFCore.SqlServer.FunctionalTests/DbContextPoolingTest.cs
- test/EFCore.SqlServer.FunctionalTests/SequenceEndToEndTest.cs
> Test: Re-enable flaky tests on Ubuntu

- src/EFCore/ChangeTracking/LocalView.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/InternalDbQuery.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/Internal/LazyLoader.cs
- test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/DbSetTest.cs
> Remove DbContext.IsDisposed

- src/EFCore.Design/Scaffolding/IReverseEngineerScaffolder.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/ef/Commands/DbContextScaffoldCommand.Configure.cs
- src/ef/Commands/DbContextScaffoldCommand.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
- test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs
(Per our design meeting.)
cc @tonysneed
> Tools: Rename --output-dbcontext-dir to --context-dir

- src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs
> Fix uniquification error in ConstraintNamer

- src/EFCore.Design/Design/Internal/MigrationsOperations.cs
- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Design/Migrations/Design/IMigrationsScaffolder.cs
- src/EFCore.Design/Migrations/Design/MigrationsScaffolder.cs
- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
- src/ef/Commands/MigrationsRemoveCommand.Configure.cs
- src/ef/Commands/MigrationsRemoveCommand.cs
- src/ef/IOperationExecutor.cs
- src/ef/OperationExecutorBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
> Tools: Merge -Force and -Revert parameters on Remove-Migration

- src/EFCore.Specification.Tests/TestUtilities/ListLoggerProvider.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- test/EFCore.Sqlite.FunctionalTests/Scaffolding/SqliteDatabaseModelFactoryTest.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteDatabaseCleaner.cs
> SQLite RevEng: Ignore DEFAULT constraints for CLR defaults

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> SQL Server RevEng: Ignore DEFAULT constraints for CLR defaults

- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
> Tests: Remove [FrameworkSkipCondition]

- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
> Reattach foreign keys referencing derived types when base type is removed.

- samples/OracleProvider/src/OracleProvider/Extensions/OracleServiceCollectionExtensions.cs
- samples/OracleProvider/src/OracleProvider/Metadata/Conventions/OracleConventionSetBuilder.cs
- src/EFCore.Relational/Migrations/HistoryRepository.cs
- src/EFCore.Relational/Migrations/HistoryRepositoryDependencies.cs
- src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.Sqlite.Core/Metadata/Conventions/SqliteConventionSetBuilder.cs
- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Internal/DbContextServices.cs
- src/EFCore/Metadata/Conventions/ConventionSet.cs
- src/EFCore/Metadata/Conventions/Internal/CompositeConventionSetBuilder.cs
- test/EFCore.Relational.Tests/Migrations/HistoryRepositoryDependenciesTest.cs
> Implement SqlServerConventionSetBuilder.Build() by using the IServiceProvider

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs
- src/EFCore.Relational/Metadata/Internal/PropertyExtensions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
Throw on identifying relationship cycle
Fixes #10077
> Throw on multiple shared table roots

- src/EFCore.Relational/Metadata/Internal/ConstraintNamer.cs
- src/EFCore.Relational/Metadata/RelationalPropertyAnnotations.cs
- test/EFCore.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
> Flow facets for shared primary key

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore/Metadata/Internal/EntityTypeSnapshot.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalIndexBuilder.cs
- src/EFCore/Metadata/Internal/InternalKeyBuilder.cs
- src/EFCore/Metadata/Internal/InternalMetadataBuilder.cs
- src/EFCore/Metadata/Internal/InternalNavigationBuilder.cs
- src/EFCore/Metadata/Internal/InternalPropertyBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Navigation.cs
- src/EFCore/Metadata/Internal/PropertiesSnapshot.cs
- test/EFCore.Relational.Tests/ModelBuilding/RelationalTestModelBuilderExtensions.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericTest.cs
> Preserve annotations when detaching entity types and navigations.

- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
Resolves #10716
Also add test for #10974
> Query: Add test for GroupBy ToList over grouping

- src/EFCore/Metadata/Builders/ReferenceReferenceBuilder.cs
- src/EFCore/Metadata/Builders/ReferenceReferenceBuilder`.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
> Don't validate properties that haven't been set explicitly.

- src/EFCore/Metadata/Conventions/Internal/ConstructorBindingConvention.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ConstructorBindingConventionTest.cs
Issue #10852
Now we pick the constructors with the most number of services, followed by the constructor with the least number of regular properties.
> Small change to constructor binding convention

- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
Like #9581 but for async
/cc @smitpatel
> Another test OrderBy fix

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
> Update "More than twenty 'IServiceProvider'..." message to be more helpful

- samples/OracleProvider/src/OracleProvider/Properties/OracleStrings.Designer.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/DataAnnotationOracleTest.cs
- src/EFCore.InMemory/Properties/InMemoryStrings.Designer.cs
- src/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/WarningsTestBase.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.Sqlite.Core/Properties/SqliteStrings.Designer.cs
- src/EFCore/Diagnostics/EventDefinition.cs
- src/EFCore/Diagnostics/EventDefinitionBase.cs
- src/EFCore/Diagnostics/EventDefinition`.cs
- src/EFCore/Diagnostics/EventDefinition``.cs
- src/EFCore/Diagnostics/EventDefinition```.cs
- src/EFCore/Diagnostics/EventDefinition````.cs
- src/EFCore/Diagnostics/EventDefinition`````.cs
- src/EFCore/Diagnostics/EventDefinition``````.cs
- src/EFCore/Diagnostics/FallbackEventDefinition.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.InMemory.FunctionalTests/Query/WarningsTest.cs
- test/EFCore.InMemory.Tests/InMemoryTransactionManagerTest.cs
- test/EFCore.Proxies.Tests/LazyLoadingProxyTests.cs
- test/EFCore.SqlServer.FunctionalTests/DataAnnotationSqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
- tools/Resources.tt
> Make warning as error exception more helpful

- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore.Specification.Tests/PropertyValuesTestBase.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder`.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericRelationshipStringTest.cs
> Add generic HasOne/HasMany overloads that take strings

- src/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs
- src/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandComparerTest.cs
> Make ModificationCommandComparer handle shared table.

- src/EFCore.Specification.Tests/ConvertToStoreTypesTestBase.cs
- src/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToStoreTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
For issue #10944, which is already fixed in dev.
> Adding tests for specifying facets with value conversions

- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder.cs
- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs
- src/EFCore/Metadata/Builders/ReferenceReferenceBuilderBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Keep the underlying Builder in ReferenceOwnershipBuilder up-to-date

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
> Throw better exception when supplying a non-unique value for a unique index

- src/EFCore.Specification.Tests/Query/QueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- src/EFCore.SqlServer/Extensions/SqlServerServiceCollectionExtensions.cs
- src/EFCore.SqlServer/Query/ExpressionVisitors/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/ExpressionVisitors/Internal/SqlServerSqlTranslatingExpressionVisitorFactory.cs
- src/EFCore.Sqlite.Core/Infrastructure/SqliteServiceCollectionExtensions.cs
- src/EFCore.Sqlite.Core/Query/ExpressionVisitors/Internal/SqliteSqlTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/ExpressionVisitors/Internal/SqliteSqlTranslatingExpressionVisitorFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
> Query: Client Eval DateTime arithmetic operation for Sqlite/SqlServer

- src/EFCore.InMemory/Query/Internal/IInMemoryMaterializerFactory.cs
- src/EFCore.InMemory/Query/Internal/InMemoryMaterializerFactory.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryModelVisitor.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/BufferedEntityShaper`.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/BufferedOffsetEntityShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/EntityShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/IMaterializerFactory.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/UnbufferedEntityShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/UnbufferedOffsetEntityShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/RelationalEntityQueryableExpressionVisitor.cs
- src/EFCore/ChangeTracking/Internal/ArrayPropertyValues.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Metadata/Internal/ContextParameterBinding.cs
- src/EFCore/Metadata/Internal/DefaultServiceParameterBinding.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/EntityTypeParameterBinding.cs
- src/EFCore/Metadata/Internal/IEntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/ParameterBindingInfo.cs
- src/EFCore/Metadata/Internal/PropertyParameterBinding.cs
- src/EFCore/Metadata/Internal/ServiceMethodParameterBinding.cs
- src/EFCore/Metadata/Internal/ServiceParameterBinding.cs
- src/EFCore/Query/EntityLoadInfo.cs
- src/EFCore/Storage/MaterializationContext.cs
- test/EFCore.Tests/Metadata/Internal/EntityMaterializerSourceTest.cs
Fixes #10641
Allows new dependencies to be added with less chance of breaking change and less churn throughout the stack.
> Add MaterializationContext parameter object

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Internal/EntityMaterializerSourceTest.cs
> Fix build issue and add "simple" to property access string

- src/EFCore.Specification.Tests/FindTestBase.cs
- src/EFCore/DbContext.cs
- src/EFCore/DbSet`.cs
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/IEntityFinder.cs
- src/EFCore/Internal/IEntityFinder`.cs
> Make Find return null for null key

- build/dependencies.props
- samples/OracleProvider/src/OracleProvider/Infrastructure/OracleDbContextOptionsBuilder.cs
- samples/OracleProvider/src/OracleProvider/OracleProvider.csproj
- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleProvider.FunctionalTests.csproj
* Update Oracle Data Provider for .Net Core 2.12.0-beta2
**Ref:**  #11024
**NuGet Ref:** [https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/)
------ Test started: Assembly: Microsoft.EntityFrameworkCore.Oracle.FunctionalTests.dll ------
6137 passed, 0 failed, 51 skipped (see 'Error List / Messages'), took 355,60 seconds (xUnit.net 2.3.1 build 3858).
> Update ODP.NET for ODP.NET Core

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Storage/Internal/RelationalCommand.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
> Use the converted values for seed data and default values in migrations

- src/EFCore/Infrastructure/ModelSource.cs
- test/EFCore.Tests/ModelSourceTest.cs
> Ensure that OnModelCreating is not run concurrently

- samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs
- src/EFCore.Relational/Migrations/HistoryRepository.cs
- src/EFCore.Relational/Migrations/HistoryRepositoryDependencies.cs
- src/EFCore.Relational/Storage/ISqlGenerationHelper.cs
- src/EFCore.Relational/Storage/RelationalSqlGenerationHelper.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerHistoryRepository.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/EFCore.Sqlite.Core/Migrations/Internal/SqliteHistoryRepository.cs
- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerHistoryRepositoryTest.cs
> Migrations: Clean up SQL generation

- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> 'Cause we love one liners

- src/Shared/PropertyInfoExtensions.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/PropertyDiscoveryConventionTest.cs
> Discover properties with private setters on unmapped base type

- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericUnqualifiedStringTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Throw when foreign key principal end becomes ambiguous after the pk is configured.

- src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
- src/EFCore.Specification.Tests/F1FixtureBase.cs
- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore.Specification.Tests/Query/NorthwindQueryFixtureBase.cs
- test/EFCore.SqlServer.FunctionalTests/ExecutionStrategyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
> Enable DbContext Pooling for functional tests

- src/EFCore/IEntityTypeConfiguration`.cs
- src/EFCore/IQueryTypeConfiguration`.cs
- src/EFCore/ModelBuilder.cs
- test/EFCore.Tests/ModelBuilding/IQueryTypeConfigurationTest.cs
```
- Detail 1
- Detail 2
```
Fixes #11257
This is my first PR for EF, so please be patient with me 😃
> Add IQueryTypeConfiguration<TEntity>

- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- src/EFCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Sqlite.FunctionalTests/DataAnnotationSqliteTest.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/KeyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/RelationshipDiscoveryConventionTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
> Update log levels for new events

- src/EFCore.Design/Scaffolding/Internal/CandidateNamingService.cs
- src/EFCore.Design/Scaffolding/Internal/ICandidateNamingService.cs
- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CandidateNamingServiceTest.cs
> Make ICandidateNamingService more useful

- src/EFCore.Relational/Query/Internal/ShaperCommandContext.cs
- src/EFCore/Query/Internal/EntityQueryable`.cs
> Perf: Query: Removes two allocs from query execution

- src/EFCore.Tools/EFCore.Tools.csproj
- src/EFCore.Tools/EFCore.Tools.nuspec
This reverts commit c532dc6baf7d64d2e3197e65d9d34e2983533668.
> Revert "Remove nuspec. Use csproj instead"

- src/EFCore.Analyzers/CommandTextInjectionDiagnosticAnalyzer.cs
- test/EFCore.Analyzers.Tests/TestUtilities/DiagnosticAnalyzerTestBase.cs
This is the quick fix to get Universe passing again. Filed #11371 to decide on a plan forward.
> Analyzers: Disable EF1001 by default

- build/dependencies.props
- korebuild-lock.txt
- src/EFCore.Tools/EFCore.Tools.csproj
- src/EFCore.Tools/EFCore.Tools.nuspec
See https://github.com/aspnet/Coherence-Signed/issues/789
React to aspnet/BuildTools#617
> Update EFCore.Tools package copyright and other metadata

- src/EFCore.Tools/EFCore.Tools.nuspec
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/RootCommand.cs
- src/dotnet-ef/dotnet-ef.csproj
- src/ef/ef.csproj
We need to do this since dotnet-ef is bundled with the SDK.
> Tools: Rearrange package layout

- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
> Clean up outdated messages about BuildWebHost

- src/EFCore.Tools/tools/EntityFrameworkCore.PowerShell2.psd1
- src/EFCore.Tools/tools/EntityFrameworkCore.psd1
- src/EFCore.Tools/tools/init.ps1
> PMC Tools: Don't load if newer tools are already loaded

- src/EFCore/Metadata/Builders/CollectionNavigationBuilder.cs
- src/EFCore/Metadata/Builders/CollectionNavigationBuilder`.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Builders/QueryTypeBuilder.cs
- src/EFCore/Metadata/Builders/QueryTypeBuilder`.cs
- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder.cs
- src/EFCore/Metadata/Builders/ReferenceNavigationBuilder`.cs
- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder.cs
- src/EFCore/Metadata/Builders/ReferenceOwnershipBuilder`.cs
> Update Has.../With... API docs to be clear on meaning of not specifying a navigation property

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
> Add back base implementation of RelationalTypeMapping.Clone

- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleByteArrayTypeMapping.cs
- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleDecimalTypeMapping.cs
- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleDoubleTypeMapping.cs
- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleStringTypeMapping.cs
- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleTypeMappingSource.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/BuiltInDataTypesOracleTest.cs
- src/EFCore.Relational/Storage/ByteArrayTypeMapping.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingExtensions.cs
- src/EFCore.Relational/Storage/StringTypeMapping.cs
- src/EFCore.Relational/breakingchanges.netcore.json
- src/EFCore.SqlServer/Storage/Internal/SqlServerByteArrayTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs
- src/EFCore/Storage/CoreTypeMapping.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
- test/EFCore.SqlServer.Tests/SqlServerTypeMapperTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
> Make store type name facet postfix configurable in the type mapping

- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore/Internal/SemanticVersionComparer.cs
- src/ef/AppDomainOperationExecutor.cs
- src/ef/ReflectionOperationExecutor.cs
- src/ef/ef.csproj
> Tools: Warn when using with a newer runtime

- src/EFCore.Relational/Update/Internal/CommandBatchPreparer.cs
- src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs
- src/EFCore.Relational/Update/ModificationCommand.cs
- src/EFCore.Relational/Update/ReaderModificationCommandBatch.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerModificationCommandBatch.cs
- src/EFCore.SqlServer/Update/Internal/SqlServerUpdateSqlGenerator.cs
- src/EFCore/ChangeTracking/Internal/LocalViewListener.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.SqlServer.FunctionalTests/SequentialGuidEndToEndTest.cs
> Improve update pipeline performance

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Query: Properly materialize streaming correlated collection with FirstOrDefault

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
> PMC Tools: Warn when multiple startup projects

- src/EFCore.Relational/Storage/Internal/FallbackRelationalTypeMappingSource.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSource.cs
- src/EFCore/Storage/ITypeMappingSource.cs
- src/EFCore/Storage/TypeMappingInfo.cs
- src/EFCore/Storage/TypeMappingSource.cs
- src/EFCore/Storage/TypeMappingSourceBase.cs
- src/EFCore/Storage/TypeMappingSourceDependencies.cs
Fixes #11424
There is still some code duplication that could be refactored, but hopefully the shape is right.
> Perf: make TypeMappingInfo a struct

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
> Tweak model building log messages

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
> PMC Tools: Handle empty strings written to stdout

- src/EFCore.Analyzers/EFCore.Analyzers.csproj
Resolves #11507
Tested local package on scaffolding repo. And it removes the error.
> Analyzer: Lower tfm to netstandard1.3

- src/EFCore.Relational/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/ChangeTracking/Internal/ArrayPropertyValues.cs
- src/EFCore/ChangeTracking/Internal/EntityEntryGraphIterator.cs
- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/EntryPropertyValues.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalMixedEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/InternalShadowEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/OriginalValues.cs
- src/EFCore/ChangeTracking/Internal/RelationshipsSnapshot.cs
- src/EFCore/ChangeTracking/Internal/Snapshot.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/ValueGenerationManager.cs
- src/EFCore/Extensions/EntityTypeExtensions.cs
- src/EFCore/Extensions/ModelExtensions.cs
- src/EFCore/Extensions/TypeBaseExtensions.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetter.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Metadata/Internal/IClrPropertyGetter.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- test/EFCore.Tests/ApiConsistencyTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/InternalClrEntityEntryTest.cs
- test/EFCore.Tests/Metadata/Internal/ClrPropertyGetterFactoryTest.cs
> Improve ChangeTracking performance

- src/EFCore.Tools/EFCore.Tools.csproj
- src/dotnet-ef/dotnet-ef.csproj
fixes #9439
-verified by building and inspecting generated packages with Nuget Package Explorer
> Update Tools Nuget package descriptions

- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- src/EFCore.Specification.Tests/WithConstructorsTestBase.cs
- src/EFCore/Update/Internal/UpdateEntryExtensions.cs
Fixes #11471 
Also makes all tests run on non-US system
> Issue 11471

- samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs
- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleDateTimeOffsetTypeMapping.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/CustomConvertersOracleTest.cs
- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.Relational/Migrations/Operations/DeleteDataOperation.cs
- src/EFCore.Relational/Migrations/Operations/InsertDataOperation.cs
- src/EFCore.Relational/Migrations/Operations/UpdateDataOperation.cs
- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs
- src/EFCore.Relational/Update/ColumnModification.cs
- src/EFCore.Relational/Update/UpdateSqlGenerator.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- src/Shared/DictionaryExtensions.cs
Use the model mapping for values in migrations data operations.
> Fix BuiltInDataTypesOracleTest

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/Shared/SharedTypeExtensions.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Migrations: Test value converters

- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/IEntityEntryGraphIterator.cs
- src/EFCore/Infrastructure/ServiceCollectionMap.cs
- src/EFCore/Metadata/Builders/QueryTypeBuilder.cs
- src/EFCore/Metadata/Builders/QueryTypeBuilder`.cs
Corrects spelling of some comments
> Corrects spelling of some comments

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Migrations: Diff DeleteBehavior.ClientSetNull and Restrict as equal

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Relational/Metadata/Conventions/Internal/RelationalDbFunctionConvention.cs
- src/EFCore.Relational/Metadata/Internal/RelationalAnnotationsBuilder.cs
- src/EFCore.Relational/Metadata/RelationalAnnotations.cs
- src/EFCore.Relational/Metadata/RelationalEntityTypeAnnotations.cs
- src/EFCore.Specification.Tests/TestUtilities/AnnotationComparer.cs
- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/Conventions/Internal/SqlServerValueGenerationStrategyConvention.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
- src/EFCore/Infrastructure/Annotatable.cs
- src/EFCore/Infrastructure/Annotation.cs
- src/EFCore/Metadata/IMutableAnnotatable.cs
- src/EFCore/Metadata/Internal/ConventionalAnnotatable.cs
- src/EFCore/Metadata/Internal/ConventionalAnnotation.cs
- src/EFCore/Metadata/Internal/InternalMetadataBuilder.cs
- src/EFCore/breakingchanges.netcore.json
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerValueGenerationStrategyConventionTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
- test/EFCore.SqlServer.Tests/SqlServerValueGeneratorCacheTest.cs
- test/EFCore.Tests/Infrastructure/AnnotationTest.cs
> Allow annotations with null values

- src/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
- src/EFCore/Query/Internal/QueryBuffer.cs
> Set IsLoaded when Included navigation is null/empty

- src/EFCore/ChangeTracking/EntityEntryGraphNode.cs
- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/DbContext.cs
- src/EFCore/Infrastructure/AccessorExtensions.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
> Don't propagate state to shadow PK dependent if principal is unchanged.

- test/EFCore.Tests/ChangeTracking/Internal/ChangeDetectorTest.cs
> Add tests for inserting with array ValueComparer

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
> RevEng: Scaffold constructors for DbContext

- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilderDependencies.cs
- src/EFCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Internal/InversePropertyAttributeConvention.cs
- src/EFCore/Metadata/Conventions/Internal/NavigationAttributeEntityTypeConvention.cs
- src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
- src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/IMemberClassifier.cs
- src/EFCore/Metadata/Internal/MemberClassifier.cs
- src/Shared/PropertyInfoExtensions.cs
- test/EFCore.Relational.Tests/Metadata/Conventions/Internal/RelationalPropertyMappingValidationConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/NavigationAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/PropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/PropertyMappingValidationConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/RelationshipDiscoveryConventionTest.cs
> Extract member classification into a service

- src/EFCore/ChangeTracking/NavigationEntry.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Tests/ChangeTracking/CollectionEntryTest.cs
Fixes #10450
Tests for #10448 (which was already fixed) and #10603 (which I don't think is a bug.)
> Various Andriy's game issues

- src/EFCore.Analyzers/EFCore.Analyzers.csproj
- test/EFCore.Analyzers.Tests/EFCore.Analyzers.Test.csproj
> Analyzer: Pack better

- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
No Process at the other end of pipe
Resolves #9031
> Test: Disable SqlServer Database Creation tests on CI

- src/EFCore.Analyzers/EFCore.Analyzers.csproj
- src/EFCore.Analyzers/EFCore.Analyzers.nuspec
- src/EFCore.Tools/EFCore.Tools.csproj
- src/EFCore.Tools/EFCore.Tools.nuspec
- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
> Generate symbol nupkg for EFCore.Tools, EFCore.Analyzers and dotnet-ef

- NuGetPackageVerifier.json
- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
- test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
Arbitrary constraints must be satisfied.
> Update dotnet-ef to netcoreapp2.1

- NuGetPackageVerifier.json
- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
- test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
Fixes #11809
See also aspnet/Coherence-Signed#850
@jbagga may need to react (again) when merged into `release/2.1`
> [2.1] Update dotnet-ef to netcoreapp2.1

- src/EFCore.Proxies/Proxies/Internal/ProxyBindingRewriter.cs
- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
> [2.1] Create proxies for base type and derived types in any order

- src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
> Add missing file header

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> SqlServer RevEng: Use concat operators instead of function

- samples/OracleProvider/test/OracleProvider.FunctionalTests/LoggingOracleTest.cs
> Remove: Namespace not used

- Directory.Build.targets
- NuGetPackageVerifier.json
- build/dependencies.props
- build/repo.props
- src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- src/EFCore.Specification.Tests/TestUtilities/Xunit/FrameworkSkipConditionAttribute.cs
- src/dotnet-ef/dotnet-ef.csproj
- test/Directory.Build.props
- test/EFCore.Analyzers.Tests/EFCore.Analyzers.Test.csproj
- test/EFCore.Design.Tests/Design/Internal/ForwardingProxyTest.cs
- test/EFCore.Design.Tests/TestUtilities/BuildReference.cs
- test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlExceptionFactory.cs
- test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
- test/ef.Tests/AppDomainOperationExecutorTest.cs
- test/ef.Tests/SimpleProjectTest.cs
netcoreapp2.1 -> netcoreapp2.2
Also moved around tfm ordering since VS for Mac supports custom SDKs.
> Upgrade Tfm to netcoreapp2.2

- NuGet.config
Attempt to fix https://github.com/aspnet/EntityFrameworkCore/issues/11988 by working around Microsoft/msbuild#2914
> Add tools feed to nuget.config

- src/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- src/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- src/EFCore.Relational.Specification.Tests/TestModels/Northwind/NorthwindRelationalContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarFromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.QueryTypes.cs
Fixes #12099
@ralmsdeveloper FYI
> Fix Oracle FromSql tests

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerByteArrayTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTimeSpanTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteCharTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeOffsetTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDateTimeTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDecimalTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteGuidTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteULongTypeMapping.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.Relational.Tests/TestUtilities/TestRelationalTypeMappingSource.cs
> Remove redundant overrides from provider type mappings

- src/EFCore.Relational.Specification.Tests/TransactionTestBase.cs
> Avoid using failed transactions in tests.

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.QueryTypes.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/ModelBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Internal/InternalModelBuilderTest.cs
- test/EFCore.Tests/Metadata/Internal/ModelTest.cs
And improve exception message
Fixes #12119
> [2.1.1] Allow overriding query types found by convention.

- korebuild-lock.txt
- src/EFCore.Tools/EFCore.Tools.nuspec
Workaround for NuGet/Home#3337 and also update build tools.
> Fix bugs in packing the .Tools package on Linux/macOS

- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/NullSemanticsQueryOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/QueryNoClientEvalOracleTest.cs
> Oracle: Code cleanup

- src/EFCore/EntityFrameworkQueryableExtensions.cs
Fixes https://github.com/aspnet/EntityFramework.ApiDocs/pull/17/.
> Fix for incorrect XML comment on AsTracking

- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/KeyPropagator.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/baseline.netcore.json
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> fix Referrers typo

- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/Shared/SharedTypeExtensions.cs
- test/EFCore.Tests/Infrastructure/CoreModelValidatorTest.cs
Simple improve seeding error message. Fixes #12399
Please review
> Improve seeding error message when CLR default is used. 

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> [2.1.3] Avoid creating a duplicate property in nested owned type in model snapshot.

- src/EFCore.InMemory/Storage/Internal/InMemoryTable.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
> [2.1.3] Add quirks for in-memory concurrency patch fix

- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlEntityQueryableExpressionVisitor.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlEntityQueryableExpressionVisitorFactory.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlGenerator.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/DocumentQueryExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/EntityProjectionExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/KeyAccessExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/QueryShaperExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/RootReferenceExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/SelectExpression.cs
- src/EFCore.Cosmos.Sql/Query/Internal/CosmosSqlEntityQueryModelVisitorFactory.cs
- src/EFCore.Cosmos.Sql/Query/Internal/CosmosSqlQueryContextFactory.cs
- src/EFCore.Cosmos.Sql/Query/Internal/CosmosSqlQueryModelVisitor.cs
- src/EFCore.Cosmos.Sql/Query/Internal/EntityShaper.cs
- src/EFCore.Cosmos.Sql/Query/Internal/IShaper.cs
- src/EFCore.Cosmos.Sql/Query/Internal/ValueBufferFactoryFactory.cs
- src/EFCore.Cosmos.Sql/Storage/Internal/CosmosClient.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/SimpleQueryCosmosSqlTest.cs
- test/EFCore.Cosmos.Sql.Tests/Metadata/Conventions/Internal/DiscriminatorConventionTest.cs
- test/EFCore.Cosmos.Sql.Tests/TestUtilities/CosmosSqlTestHelpers.cs
> CosmosDb: Implement basic query functionality

- .vsts-pipelines/builds/ci-internal.yml
- .vsts-pipelines/builds/ci-public.yml
- build/repo.props
- korebuild.json
Preparing the release/2.2 branch for use.
part of https://github.com/aspnet/Home/issues/3278
> Update CI and build tools for to use 2.2 versions

- version.props
Part of https://github.com/aspnet/Home/issues/3278
> Upgrade branding to 3.0.0-alpha1

- src/EFCore.Relational.Specification.Tests/Query/WarningsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/WarningsSqlServerTest.cs
> [TINY] adding async test to warn when Skip is used without OrderBy

- Directory.Build.targets
- NuGetPackageVerifier.json
- build/dependencies.props
- build/repo.props
- src/EFCore.Relational.Specification.Tests/EFCore.Relational.Specification.Tests.csproj
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- src/EFCore.Specification.Tests/TestUtilities/Xunit/FrameworkSkipConditionAttribute.cs
- src/dotnet-ef/dotnet-ef.csproj
- test/Directory.Build.props
- test/EFCore.Design.Tests/Design/Internal/ForwardingProxyTest.cs
- test/EFCore.Design.Tests/TestUtilities/BuildReference.cs
- test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlExceptionFactory.cs
- test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
- test/ef.Tests/AppDomainOperationExecutorTest.cs
- test/ef.Tests/SimpleProjectTest.cs
We need this to fix templating since it relies on dotnet-ef.
> netcore2.2->netcore3.0

- .editorconfig
> Update .editorconfig for Type_parameter & namespace naming

- .editorconfig
- src/EFCore.Cosmos.Sql/Extensions/CosmosSqlLoggerExtensions.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlEntityQueryableExpressionVisitor.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlGenerator.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/DocumentQueryExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/QueryShaperExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/SelectExpression.cs
- src/EFCore.Cosmos.Sql/Query/Internal/CosmosSqlQueryModelVisitor.cs
- src/EFCore.Cosmos.Sql/Storage/Internal/CosmosClient.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/NorthwindQueryCosmosSqlFixture.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/SimpleQueryCosmosSqlTest.Where.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/TestUtilities/CosmosSqlTestStoreFactory.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/TestUtilities/TestSqlLoggerFactory.cs
> CosmosDb: Introduction of SqlTranslator for Predicate translation

- src/EFCore.Cosmos.Sql/Extensions/CosmosSqlLoggerExtensions.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlGenerator.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/SqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/DocumentQueryExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/SelectExpression.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/EFCore.Cosmos.Sql.FunctionalTests.csproj
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/SimpleQueryCosmosSqlTest.Where.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/SimpleQueryCosmosSqlTest.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/TestUtilities/TestSqlLoggerFactory.cs
> CosmosSql: Support various unary/binary/ternary SQL operators

- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
Disable GroupBy_Composite_Select_Dto_Sum_Min_Key_flattened_Max_Avg, flakiness seems external to EF
Fixes #12664
> Remove the test for the quirk mode for #12227

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Handle simple value conversions for key properties in seed data.

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Add migrations snapshot support for TimeSpan ticks, Linux-style new lines and flags enums

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
Don't generate invalid .ToTable() calls
Fixes #12191
Fixes #11655
> Don't use .DisplayName() in model snapshot

- test/Directory.Build.props
Close #12706 
Will be merging once all CIs are happy.
> Remove netcoreapp2.0 as test tfm from master branch 

- build/dependencies.props
- src/EFCore.Design/EFCore.Design.csproj
@natemcmaster 
Depends on/reacts to https://github.com/aspnet/Hosting/pull/1502
> React to WebHostBuilderFactory rename

- build/dependencies.props
- test/Directory.Build.props
> Re-enable SqlServer tests on netcoreapp2.0 tfm

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Also added scaffolding test for unique constraints.
Fixes #12821
> PK name taken into account when scaffolding

- src/EFCore/Metadata/Internal/Model.cs
> [2.1.4] Use a ConcurrentDictionary to store DisplayName values as they could be added after the model is built.

- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
> Query: Re-enable tests

- src/EFCore/EntityFrameworkServiceCollectionExtensions.cs
> Minor typo

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- src/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.QueryTypes.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.QueryTypes.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Tests are disabled for now, should be enabled as the bugs are getting fixed
> adding tests for recenlty found query issues

- src/EFCore.Specification.Tests/TestModels/QueryFilterFuncletizationContext.cs
- src/EFCore.Specification.Tests/WithConstructorsTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
> Make tests run for SQL CE also

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
> Test: Add ordering for collection before comparing

- src/EFCore.Relational/Metadata/Builders/DiscriminatorBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/BaseTypeDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/DerivedTypeDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/Internal/OwnedTypesConvention.cs
- src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
- src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/ModelExtensions.cs
- src/EFCore/Metadata/Internal/TypeBase.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
This is part of a larger change
> Make sure weak entity types are reattached as weak entity types unless only one instance is left

- src/EFCore/Update/IUpdateEntry.cs
> Comment clarification IUpdateEntry.cs

- src/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
Same as #12909 for another test.
> Add another ordering to tests before comparing

- src/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
Like #12177 but for the async version of the test.
/cc @smitpatel
> Test: Update test which was throwing off reference counting

- src/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
> Add some defense against slow file system on slow C.I.

- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/AsyncSimpleQueryOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/GearsOfWarQueryOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/QueryLoggingOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/Query/SimpleQueryOracleTest.cs
- samples/OracleProvider/test/OracleProvider.FunctionalTests/UpdatesOracleTest.cs
Filed #13029 to investigate skipped failues
> Oracle: Fix some tests

- src/EFCore.InMemory/Extensions/InMemoryServiceCollectionExtensions.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMapping.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMappingSource.cs
Breaking this out of #12988 to unblock some other PRs.
> InMemory: Stop using FallbackTypeMappingSource

- build/dependencies.props
- samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleComplianceTest.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMapping.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTypeMappingSource.cs
- src/EFCore.Specification.Tests/EFCore.Specification.Tests.csproj
- src/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.Specification.Tests/SpatialFixtureBase.cs
- src/EFCore.Specification.Tests/SpatialTestBase.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/LineStringEntity.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/MultiLineStringEntity.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/PointEntity.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/PolygonEntity.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialContext.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialData.cs
- src/EFCore.Specification.Tests/TestUtilities/GeometryComparer.cs
- src/EFCore.Specification.Tests/TestUtilities/WKTComparer.cs
- src/EFCore/ChangeTracking/GeometryValueComparer.cs
- test/EFCore.InMemory.FunctionalTests/Query/SpatialQueryInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/Query/SpatialQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/SpatialInMemoryFixture.cs
- test/EFCore.InMemory.FunctionalTests/SpatialInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
Part of #1100 
Depends on aspnet/Universe#1319 (Merged)
> InMemory: Support spatial data via NTS

- src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs
Resolves #12682 
This uses lock to make sure that we are not mutating service once we start calling Create method on it.
It includes all the changes on related objects to clean up. Some may be kept as is due to this being a patch fix.
> [2.1.5] Query: Make `MethodInfoBasedNodeTypeRegistryFactory` best possible singleton service

- version.props
When this PR merges, the release/2.2 branches will be open for preview3 changes.
> Update branding to 2.2.0-preview3

- src/EFCore.Cosmos.Sql/Metadata/Conventions/Internal/StoreKeyConvention.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlEntityQueryableExpressionVisitor.cs
- src/EFCore.Cosmos.Sql/Query/ExpressionVisitors/Internal/CosmosSqlMemberAccessBindingExpressionVisitor.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/DocumentQueryExpression.cs
- src/EFCore.Cosmos.Sql/Query/Expressions/Internal/QueryShaperExpression.cs
- src/EFCore.Cosmos.Sql/Query/Internal/CosmosSqlQueryModelVisitor.cs
- src/EFCore.Cosmos.Sql/Storage/Internal/CosmosClient.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
- src/EFCore/Query/ExpressionVisitors/Internal/TaskLiftingExpressionVisitor.cs
- src/EFCore/Query/ExpressionVisitors/ProjectionExpressionVisitor.cs
- src/EFCore/Query/Internal/AsyncLinqOperatorProvider.cs
- src/EFCore/Query/ResultOperatorHandler.cs
- test/EFCore.Cosmos.Sql.FunctionalTests/Query/SimpleQueryCosmosSqlTest.JoinGroupJoin.cs
Handle Take, Skip, Last pushdown for SelectAsync
Remove async-to-sync subquery conversion when async is expected
> Enable async queries on Cosmos SQL

- src/EFCore/Diagnostics/WarningsConfiguration.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- test/EFCore.Tests/ServiceProviderCacheTest.cs
> Make provider cache more resilient to collisions

- src/EFCore.Relational/Migrations/Internal/Migrator.cs
Issue: When reverting/unapplying migration (or generating script for the same), we use unapply chain to figure out model from previous migration except for the last migration to revert where we passed null. Hence when reverting the very last migration, we don't have model information. Which causes us to generate incorrect script based on only Down method.
Fix: While populating migrations, if we are reverting some migrations then also populate the actual target migration which we can pass into Down script generation to correctly identify target model and generate script correctly.
Testing: Manual testing
Resolves #13217
> Tools: Get correct model from previous migration while reverting

- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- src/EFCore.Relational/Scaffolding/Metadata/DatabaseColumnExtensions.cs
- src/EFCore.Relational/Scaffolding/Metadata/Internal/ScaffoldingAnnotationNames.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
Resolves #12633
Filed #13292 for cleanup of infra as breaking change
> RevEng: Swap out type alias with actual store type in DatabaseModelFactory

- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
Ignore the DateKind in literal generation
Resolves #12211
> Produce correct Sql Literal for datetime

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeOffsetTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDecimalTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerDoubleTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
> Update base RelationalTypeMapping to not set DbParameter Size

- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
> Fixup navigations to deleted entity even for DeleteBehavior.Restrict

- src/EFCore.Specification.Tests/F1FixtureBase.cs
- src/EFCore/DbContext.cs
- src/EFCore/Internal/InternalDbSet.cs
> Reset DbSet.Locals when context is returned to the pool

- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore.Specification.Tests/LoadTestBase.cs
- src/EFCore/Internal/LazyLoader.cs
> Stop calling DetectChanges when lazy-loading

- src/EFCore.InMemory/Extensions/InMemoryDbContextOptionsExtensions.cs
> Fix links to point to non-obsolete methods

- build/dependencies.props
- src/EFCore.SqlServer.NTS/NetTopologySuite.IO/SqlServerSpatialReader.cs
Resolves #13223 
See also aspnet/Universe#1409
> Update NetTopologySuite.Core to 1.15.1

- src/dotnet-ef/RootCommand.cs
and vice-versa
Resolves #11330
cc: @bricelam - how to test this works?
> CLI tools: Use target project when we cannot find startup project

- src/EFCore.Specification.Tests/Query/QueryTaggingTestBase.cs
- src/EFCore/EntityFrameworkQueryableExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryTaggingSqlServerTest.cs
> Query: Allow WithTag API on IQueryable of primitive types

- src/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
Fixes #12810
I realized that technically a call to DetectChanges is needed between the FK change and the call to `Remove`. However, doing a local check seems pretty reasonable and makes it work without DetectChanges.
> Don't null out FK after delete of principal if FK was changed to point to a new principal

- src/EFCore.Relational/Metadata/Builders/DiscriminatorBuilder.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/Model.cs
- test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
> Metadata: HasValue<TDerived> registers QueryTypes appropriately

- src/EFCore/ChangeTracking/Internal/StateManager.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
> Clear StateManager event handlers when context returned to pool

- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMemberTranslator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Sql/Internal/SqliteQuerySqlGenerator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteGeometryMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteGeometryMethodTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> Spatial: Translate InteriorPoint, Union (unary), and IsWithinDistance

- Directory.Build.targets
- build/dependencies.props
- korebuild-lock.txt
- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
Required a change to packaging to workaround a bug in generating tool shims. 
cref https://github.com/dotnet/sdk/pull/2561
> Upgrade the build to 2.2 Preview 2 SDK

- samples/OracleProvider/src/OracleProvider/Storage/Internal/OracleTransientExceptionDetector.cs
* Change Comment SQL Server to Oracle ✔️
> Small change

- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
Regression test for #11936
It is already working in latest package
> RevEng: Scaffold FK targetting UniqueConstraint

- src/EFCore.Relational/Update/Internal/ModificationCommandComparer.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandComparerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
> Use StructuralComparisons when sorting modification commands with byte array as PK

- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
> Don't assume that Index has Includes in migration SQL generation

- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
> Don't warn when bool property store default value is false

- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore.Specification.Tests/FieldMappingTestBase.cs
- src/EFCore.Specification.Tests/TestUtilities/MetadataExtensions.cs
- src/EFCore/Query/Internal/IncludeCompiler.IncludeLoadTreeNode.cs
- test/EFCore.Sqlite.FunctionalTests/FieldMappingSqliteTest.cs
> Allow fast materializer to write values of non-exact type

- src/EFCore/DbContextOptionsBuilder.cs
- test/EFCore.Tests/DbContextOptionsTest.cs
As opposed to any extension
Fixes #13228
> Fix IsConfigured to return true only when a provider is configured

- samples/OracleProvider/test/OracleProvider.FunctionalTests/BuiltInDataTypesOracleTest.cs
Not sure what changed but all tests passed.
> :volcano: Fix oracle test failures :volcano:

- src/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
> Reset IsLoaded when FK is changed under null navigation

- src/EFCore.Sqlite.Core/Query/ExpressionTranslators/Internal/SqliteStringLengthTranslator.cs
* Code Refactoring
cc/ @bricelam
> Use nameof

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerUdtTypeMapping.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
> Literal generation for UDTs

- src/EFCore.Relational/Storage/RelationalTypeMappingInfo.cs
- src/EFCore.Relational/Storage/RelationalTypeMappingSourceExtensions.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
> Allow empty store type names because SQLite

- src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs
- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- src/EFCore/Metadata/Conventions/Internal/BackingFieldConvention.cs
- src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/ModelExtensions.cs
- src/EFCore/Metadata/Internal/TypeBase.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryBugsInMemoryTest.cs
> ModelBuilding: Compare metadata string using StringComparer.Ordinal

- src/EFCore.Relational/Query/ExpressionVisitors/Internal/IsNullExpressionBuildingVisitor.cs
Small optimization for IsNullExpressionBuildingVisitor::VisitBinary
> Small optimization for IsNullExpressionBuildingVisitor::VisitBinary method

- src/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- src/EFCore/Metadata/Conventions/Internal/KeyDiscoveryConvention.cs
- src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Don't configure PK on collection owned types

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
Resolves #13678
Now we sort PK properties first.
Inside PK properties, we sort by CLR hierarchy, then by reflection order, then by CLR vs shadow property
Resolves #13069
Issue: User specified facets were stored on property from owner which is part of PK. This property is shared with owned types PK.
Since column ordering expanded owned type into navigation and PK property appeared after navigation in reflection order, we sorted owned PK property before owner PK property.
While doing distinct, we selected owned PK property which did not have facets copied over from owner PK which caused migration to lose user configuration.
Fix: Sorting PK properties first in migration solves issue that owned property is used for table definition
> Column Ordering: Sort PK properties first

- src/EFCore/Metadata/Conventions/Internal/RelationshipDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/MemberClassifier.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/UnmappedTypesSqlServerTest.cs
- test/EFCore.Tests/ModelBuilding/UnmappedTypesTest.cs
> Don't discover multi-dimensional arrays as entity types

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
> Change nullability of explicitly configured shadow FKs to match the requiredness.

- src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs
> Correct spelling mistake in comment

- src/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
- src/EFCore/Query/Internal/CompiledAsyncEnumerableQuery.cs
- src/EFCore/Query/Internal/CompiledAsyncTaskQuery.cs
- src/EFCore/Query/Internal/CompiledQueryCache.cs
- src/EFCore/Query/Internal/EntityQueryProvider.cs
- src/EFCore/Query/Internal/EntityQueryable`.cs
- src/EFCore/Query/Internal/IAsyncQueryProvider.cs
- src/EFCore/Query/Internal/ICompiledQueryCache.cs
- src/EFCore/Query/Internal/IQueryCompiler.cs
- src/EFCore/Query/Internal/NullAsyncQueryProvider.cs
- src/EFCore/Query/Internal/QueryCompiler.cs
- test/EFCore.Tests/Extensions/QueryableExtensionsTest.cs
> Query: Remove ReLinq dependency from EntityQueryable

- src/EFCore/Metadata/IMutableProperty.cs
> API docs copy/paste error fix

- src/EFCore.Analyzers/SqlInjectionDiagnosticAnalyzerBase.cs
> Protect bugs in the analyzer from leaking into VS

- src/EFCore.Relational.Specification.Tests/Query/SpatialQueryRelationalFixture.cs
- src/EFCore.Relational/Query/Expressions/SelectExpression.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialData.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteCurveMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteGeometryMemberTranslator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteGeometryMethodTranslator.cs
- src/EFCore.Sqlite.NTS/Query/ExpressionTranslators/Internal/SqliteMultiCurveMemberTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
Also adds SQL Server coverage for constants with non-default SRIDs
> Spatial: Test NULL more

- src/EFCore.Specification.Tests/SpatialTestBase.cs
> Spatial: Test translators with static members

- src/EFCore.Relational/Storage/RelationalGeometryTypeMapping.cs
- src/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.Specification.Tests/SpatialFixtureBase.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/GeoPoint.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/GeoPointEntity.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialContext.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialData.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.SqlServer.FunctionalTests/SpatialSqlServerFixture.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> Fix parameter generation when with additional conversion on IGeometry

- src/EFCore.Specification.Tests/Query/SimpleQueryTestBase.QueryTypes.cs
- src/EFCore/DbContext.cs
- src/EFCore/Diagnostics/CoreEventId.cs
- src/EFCore/Extensions/Internal/CoreLoggerExtensions.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.QueryTypes.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Metadata/Internal/EntityTypeBaseTypeTest.cs
- test/EFCore.Tests/Metadata/Internal/NavigationTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/QueryTypesTestBase.cs
Part of #13252
Fixes #12470
Fixes #12163
Fixes #11790
Fixes #9543
> Improve exception messages

- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Expressions/CaseExpression.cs
- src/EFCore.Relational/Query/Expressions/SqlFunctionExpression.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.SqlServer.NTS/Query/ExpressionTranslators/Internal/SqlServerGeometryMethodTranslator.cs
- test/EFCore.Relational.Tests/Query/Expressions/CaseExpressionTest.cs
- test/EFCore.Relational.Tests/Query/Expressions/SqlFunctionExpressionTest.cs
> Relational: Address API review feedback

- src/EFCore.Specification.Tests/Query/SpatialQueryFixtureBase.cs
- src/EFCore.Specification.Tests/Query/SpatialQueryTestBase.cs
- src/EFCore.Specification.Tests/SpatialFixtureBase.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/GeoExtensions.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/GeoPointConverter.cs
- src/EFCore.Specification.Tests/TestModels/SpatialModel/SpatialData.cs
- src/EFCore.SqlServer.NTS/Storage/Internal/SqlServerGeometryTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SpatialQuerySqliteTest.cs
> Add tests for converted type spatial function tests

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Design/Internal/DesignTimeServicesBuilder.cs
- src/EFCore.Design/Design/Internal/MigrationsOperations.cs
- src/EFCore.Design/Design/OperationExecutor.cs
> Design: Scan target project for [DesignTimeServicesReference]

- src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
- test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
- test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
Adds UseSqlServer overload with SqlConnectionStringBuilder.
Fixes #1238
> Add UseSqlServer overload that takes SqlConnectionStringBuilder action.

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/dotnet-ef/Properties/Resources.Designer.cs
- src/dotnet-ef/Properties/Resources.resx
> Tools: Link to .NET Standard docs

- src/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- src/EFCore/Metadata/Conventions/Internal/CoreConventionSetBuilder.cs
- src/EFCore/Metadata/Conventions/Internal/ForeignKeyAttributeConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
> Detect conflicting ForeignKeyAttributes specified on navigations or properties.

- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.SqlServer/Metadata/SqlServerKeyAnnotations.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs
- src/EFCore.SqlServer/Properties/SqlServerStrings.resx
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
- test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
Validate IsClustered configuration on shared keys.
Fixes #13774
> Propagate IsClustered configuration to the owned type key.

- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
> Design: Lead less people to IDesignTimeDbContextFactory

- src/EFCore.Design/Design/Internal/DatabaseOperations.cs
- src/EFCore.Design/Scaffolding/IModelCodeGenerator.cs
- src/EFCore.Design/Scaffolding/IReverseEngineerScaffolder.cs
- src/EFCore.Design/Scaffolding/Internal/CSharpModelGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/ReverseEngineerScaffolder.cs
- src/EFCore.Design/Scaffolding/ModelCodeGenerator.cs
- src/EFCore.Design/breakingchanges.netcore.json
- src/EFCore.Design/breakingchanges.netframework.json
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpModelGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ReverseEngineeringConfigurationTests.cs
Also pass rootnamespace for VB code generation
Resolves #13904
> RevEng: Pass in context namespace based on context dir option

- src/EFCore.Design/Design/OperationExecutor.cs
- test/EFCore.Design.Tests/Design/OperationExecutorTest.cs
> Design: Make OperationBase.Execute() protected

- src/EFCore.SqlServer/Design/Internal/SqlServerAnnotationCodeGenerator.cs
- test/EFCore.SqlServer.Tests/Design/Internal/SqlServerAnnotationCodeGeneratorTest.cs
Seems this was missed in #12266...
> Generate fluent API for index includes

- src/EFCore.Relational/Migrations/Internal/MigrationsAssembly.cs
- src/EFCore.Relational/Migrations/Internal/Migrator.cs
> Fix migration order

- src/EFCore.Relational/Migrations/MigrationBuilder.cs
> Update RenameTable docs

- src/EFCore.Cosmos/Query/Internal/EntityShaper.cs
- src/EFCore.Cosmos/Update/Internal/DocumentSource.cs
- test/EFCore.Cosmos.FunctionalTests/NestedDocumentsTest.cs
> Cosmos: don't assume all nested entities are tracked.

- samples/StreamingSample/Program.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
- src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteBlobTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> Microsoft.Data.Sqlite: Address BLOB I/O API review feedback

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- test/EFCore.Design.Tests/Design/Internal/CSharpHelperTest.cs
> Correct static method call generation in CSharpHelper

- src/EFCore.Specification.Tests/TestUtilities/TestHelpers.cs
- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTestBase.cs
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
- test/EFCore.Relational.Tests/TestUtilities/RelationalTestHelpers.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestHelpers.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestHelpers.cs
- test/EFCore.Sqlite.Tests/SqliteModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderAssemblyScanTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderNonGenericStringTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/ShadowEntityTypeTest.cs
Refactor unit test model validation infrastructure
> Separate shadow entity type tests

- src/EFCore.Relational/Migrations/MigrationBuilder.cs
> Fixed mistakes in description of table param of DeleteData method.

- test/ef.Tests/AppDomainOperationExecutorTest.cs
- test/ef.Tests/SimpleProjectTest.cs
- test/ef.Tests/TestUtilities/WrappedXunitException.cs
> Test: Error better when WrappedException is thrown

- azure-pipelines.yml
cc @natemcmaster @ryanbrandenburg
> Use the maximum timeout on the internal build

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
> Microsoft.Data.Sqlite: Report only missing parameter

- src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs
- src/Microsoft.Data.Sqlite.Core/Extensions/SqliteConnectionExtensions.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteExceptionTest.cs
Resolves #13828, part of #13826
> Microsoft.Data.Sqlite: Add Password, Foreign Keys, and Recursive Triggers connection string keywords

- src/EFCore/Extensions/ModelExtensions.cs
- src/EFCore/Extensions/PropertyBaseExtensions.cs
- src/EFCore/Metadata/Internal/NavigationExtensions.cs
- src/EFCore/Metadata/Internal/PropertyBaseExtensions.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/PropertyAccessMode.cs
- test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
> Write to fields by default

- src/EFCore/Metadata/Internal/CoreAnnotationNames.cs
> Move `Relational:` from TypeMapping annotation name

- version.props
> Update Branding for 2.1.8 Patch

- version.props
> Update branding to 2.2.2

- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
> [2.2.x] Don't propagate implicit requiredness when recreating an FK

- src/EFCore/Infrastructure/ModelValidator.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTest.cs
> [2.2.x] Don't throw on missing store generated values in data seeds.

- src/EFCore.Cosmos/Metadata/Conventions/Internal/StoreKeyConvention.cs
- src/EFCore.Cosmos/ValueGeneration/Internal/IdValueGenerator.cs
- test/EFCore.Cosmos.Tests/ValueGenerator/Internal/IdValueGeneratorTest.cs
> Calculate the value for the id property from PK values

- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
> Removed unnecessary word from method summary

- src/EFCore/Metadata/Internal/ContextParameterBinding.cs
- src/EFCore/Metadata/Internal/DefaultServiceParameterBinding.cs
- src/EFCore/Metadata/Internal/EntityTypeParameterBinding.cs
- src/EFCore/Metadata/Internal/ServiceMethodParameterBinding.cs
- src/EFCore/Metadata/Internal/ServiceParameterBinding.cs
While going over some code I came across this, seems to be unused.
> Remove unused param in ParameterBinding

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
While we are breaking things for v3.0, might as well get this in here.
- Removed ArgumentIsEmpty and CollectionArgumentIsEmpty
Fixes #11307
> Removed ArgumentIsEmpty and CollectionArgumentIsEmpty

- EFCore.Cosmos.sln
- EFCore.Runtime.sln
- EFCore.sln
- Microsoft.Data.Sqlite.sln
- src/EFCore/Metadata/Conventions/Internal/BackingFieldConvention.cs
- src/EFCore/Metadata/Internal/TypeBase.cs
- src/Shared/DictionaryExtensions.cs
- startvs.cmd
> Make GetRuntimeProperties() and GetRuntimeFields() thread-safe

- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
> Refactor table creation into separate methods

- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeBuilderExtensions.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.Tests/Metadata/MetadataBuilderTest.cs
> Make HasIndex generic

- src/EFCore.SqlServer/Extensions/SqlServerEntityTypeBuilderExtensions.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/ModelBuilder.cs
- test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDbFunctionMetadataTests.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
- test/EFCore.Tests/Metadata/Conventions/Internal/ConventionDispatcherTest.cs
- test/EFCore.Tests/Metadata/MetadataBuilderTest.cs
> Rename Model.Validate to Finalize

- version.props
> Update branding to 2.2.3

- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
> Remove quirk for relational nulls fix

- azure-pipelines.yml
It's OK if `SqlLocalDB stop MSSQLLocalDB` fails
> CI: Tweak database cleanup task

- eng/Version.Details.xml
- eng/Versions.props
Generated using this script https://github.com/aspnet/AspNetCore-Internal/pull/1830
> Update to latest, coherent dependencies

- src/EFCore.Relational/Migrations/MigrationCommand.cs
- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore/DbContext.cs
Originally done by @SimonCropp in #14575
> Remove some unneeded awaits

- eng/Signing.props
- eng/Versions.props
- src/EFCore.Cosmos/EFCore.Cosmos.csproj
- src/dotnet-ef/RootCommand.cs
- src/dotnet-ef/dotnet-ef.csproj
- test/EFCore.Tests/EFCore.Tests.csproj
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/TestModel.cs
- test/dotnet-ef.Tests/dotnet-ef.Tests.csproj
Remove Newtonsoft.Json dependency from dotnet-ef and replaces it with System.Text.JSon. (#14571)
> Replace Newtonsoft.Json with System.Text.Json.

- eng/Versions.props
> Update package branding to 3.0.0-preview4

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
> Microsoft.Data.Sqlite: Persist CreateCollation, CreateAggregate, CreateFunction & EnableExtensions between close and re-open

- test/EFCore.Tests/DbContextServicesTest.cs
This works because ILoggerFactory is a singleton service. Scoped services cannot be obtained correctly when options are registered as singleton, or pooling is used (which implies the same thing.) This is a limitation with pooling/singleton options which we always had and can keep--the fix is to not use pooling/singleton options.
> Add test for using ILoggerFactory with pool

- src/EFCore/Metadata/Conventions/Internal/BackingFieldConvention.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/Metadata/Conventions/Internal/BackingFieldConventionTest.cs
> Throw if multiple backing fields match by convention

- src/EFCore.Relational/Storage/RelationalTypeMapping.cs
- src/EFCore.Relational/Storage/TypedRelationalValueBufferFactoryFactory.cs
- src/EFCore.Sqlite.NTS/Storage/Internal/SqliteGeometryTypeMapping.cs
Fixes build-break on consuming new corefx.
> Be robust about looking up System.Data methods by reflection

- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionStringBuilderTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
> Microsoft.Data.Sqlite: Differentiate between "Foreign Keys=False" and the default

- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
Issue #12592
See also the discussion in the issue.
> Only return a principal entity if it matches the type required by the FK

- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
> Update semi-specified FK property types correctly for required FKs

- src/EFCore/Metadata/Internal/Model.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/ModelCodeGeneratorTestBase.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/InheritanceTestBase.cs
- test/EFCore.Tests/ModelBuilding/ManyToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderGenericTest.cs
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/NonRelationshipTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
- test/EFCore.Tests/ModelBuilding/QueryTypesTestBase.cs
> Make the model read-only after Finalize

- src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
- test/EFCore.Tests/ModelBuilding/OneToOneTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Detect ambiguous self-referencing FKs

- src/EFCore.Cosmos/Query/Internal/EntityShaper.cs
- src/EFCore.Relational/Query/ExpressionVisitors/Internal/MaterializerFactory.cs
- src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs
- src/EFCore/Metadata/Internal/EntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/IEntityMaterializerSource.cs
- src/EFCore/Metadata/Internal/PropertyParameterBinding.cs
- src/EFCore/Query/EntityQueryModelVisitor.cs
> Remove unused property passed to EntityMaterializerSource.CreateReadValueExpression

- src/Microsoft.Data.Sqlite.Core/Extensions/SQLitePCLExtensions.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.Designer.cs
- src/Microsoft.Data.Sqlite.Core/Properties/Resources.resx
- src/Microsoft.Data.Sqlite.Core/SqliteBlob.cs
- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs
- src/Microsoft.Data.Sqlite.Core/SqliteConnectionStringBuilder.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- src/Microsoft.Data.Sqlite.Core/SqliteException.cs
- src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs
- src/Microsoft.Data.Sqlite.Core/SqliteParameterBinder.cs
- src/Microsoft.Data.Sqlite.Core/SqliteParameterReader.cs
- src/Microsoft.Data.Sqlite.Core/SqliteResultBinder.cs
- src/Microsoft.Data.Sqlite.Core/SqliteTransaction.cs
- src/Microsoft.Data.Sqlite.Core/SqliteType.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueReader.cs
- test/Microsoft.Data.Sqlite.Tests/Extensions/SqliteConnectionExtensions.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteBlobTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteConnectionTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteExceptionTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
Part of #13833, fixes #14682, fixes #14947
> Clean up Microsoft.Data.Sqlite

- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
- src/EFCore.SqlServer/Query/Sql/Internal/SqlServerQuerySqlGenerator.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerBoolTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- src/EFCore.Sqlite.Core/Query/Sql/Internal/SqliteQuerySqlGenerator.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/TestSqlLoggerFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersInheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/InheritanceSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryFilterFuncletizationSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryNavigationsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/RowNumberPagingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Where.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeometryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
This also removes hacky code to generate cast in projection.
Resolves #14956
> SqlServer: Generate Bool literal correctly

- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/NavigationFixer.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
> Delete/detach nested owned entities when replaced by new instances.

- benchmark/Shared.EFCore/Query/RawSqlQueryTests.cs
- src/EFCore.Relational/Query/ResultOperators/Internal/FromSqlExpressionNode.cs
- src/EFCore.Relational/RawSqlString.cs
- src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/RelationalQueryableExtensions.cs
- test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlSprocQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/GearsOfWarFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Relational.Specification.Tests/TestUtilities/RelationalTestStore.cs
- test/EFCore.Relational.Tests/Storage/RelationalDatabaseFacadeExtensionsTest.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerQueryTriggersTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
Resolves #10996
New methods:
FromRawSql/ExecuteRawSql(Async) - works with string, parameters
FromInterpolatedSql/ExecuteInterpolatedSql(Async) - works with FormattableString
Deprecated old methods & RawSqlString
> Separate FromSql methods into 2 methods

- src/EFCore.Design/Design/ICSharpHelper.cs
- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs
> Collapse optional parameter overloads

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteTransactionTest.cs
> Microsoft.Data.Sqlite: Make CommandTimeout of 0 mean no timeout

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteGuidTypeMapping.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteTypeMappingSource.cs
- src/Microsoft.Data.Sqlite.Core/SqliteValueBinder.cs
- test/EFCore.Sqlite.Tests/Storage/SqliteTypeMappingTest.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteParameterTest.cs
> SQLite: Store Guid as TEXT

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteTestStore.cs
> SQLite: Create new databases with WAL journal mode

- src/EFCore.Design/EFCore.Design.csproj
> Design: Mark package as a development dependency

- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
- src/EFCore.Sqlite.Core/Scaffolding/Internal/SqliteDatabaseModelFactory.cs
- src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs
- test/EFCore.Sqlite.FunctionalTests/TestUtilities/SqliteDatabaseCleaner.cs
> SQLite: Revert breaking changes to SpatialiteLoader

- src/EFCore.Relational/Diagnostics/RelationalEventId.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggingDefinitions.cs
- src/EFCore.Relational/Properties/RelationalStrings.Designer.cs
- src/EFCore.Relational/Properties/RelationalStrings.resx
- src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs
- test/EFCore.Relational.Specification.Tests/Query/NorthwindQueryRelationalFixture.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
> Postfix LogQueryPossibleExceptionWithAggregateOperator with Warning

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- src/EFCore.Relational/Infrastructure/RelationalModelValidator.cs
- src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs
- src/EFCore.Relational/Metadata/IRelationalForeignKeyAnnotations.cs
- src/EFCore.Relational/Metadata/Internal/ForeignKeyExtensions.cs
- src/EFCore.Relational/Metadata/Internal/RelationalForeignKeyBuilderAnnotations.cs
- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- src/EFCore.Relational/Metadata/RelationalForeignKeyAnnotations.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Tests/Metadata/InternalRelationalMetadataBuilderExtensionsTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalBuilderExtensionsTest.cs
- test/EFCore.Relational.Tests/Metadata/RelationalMetadataExtensionsTest.cs
- test/EFCore.Relational.Tests/RelationalModelValidatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerInternalMetadataBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
- test/EFCore.SqlServer.Tests/SqlServerModelValidatorTest.cs
- test/EFCore.Sqlite.FunctionalTests/UpdatesSqliteTest.cs
- test/EFCore.Sqlite.Tests/Metadata/Builders/SqliteBuilderExtensionsTest.cs
- test/EFCore.Sqlite.Tests/Metadata/Internal/SqliteInternalMetadataBuilderExtensionsTest.cs
- test/EFCore.Sqlite.Tests/Metadata/SqliteMetadataExtensionsTest.cs
Issue #10730
And related method name changes
> Rename RelationalForeignKeyAnnotations.HasName to HasConstraintName

- src/EFCore.Relational/Metadata/Conventions/Internal/SharedTableConvention.cs
- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
> Map inherited CLR properties to the same column

- build/templates/default-build.yml
> Do not specify `name` of the default (hosted) pools

- benchmark/Shared.EFCore/Query/RawSqlQueryTests.cs
- src/EFCore.Relational/RawSqlString.cs
- src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/RelationalQueryableExtensions.cs
- test/EFCore.Relational.Specification.Tests/ConcurrencyDetectorRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlSprocQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/GearsOfWarFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/InheritanceRelationalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Relational.Tests/Storage/RelationalDatabaseFacadeExtensionsTest.cs
- test/EFCore.SqlServer.FunctionalTests/BatchingTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerQueryTriggersTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerTriggersTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerValueGenerationScenariosTest.cs
- test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
> Rename FromRawSql to FromSqlRaw and related

- eng/Version.Details.xml
- eng/Versions.props
- update to dotnet/CoreFx packages with version '4.6.0-preview4.19201.9'
- update to dotnet/core-setup packages with version '3.0.0-preview4-27602-01'
- update to aspnet/Extensions packages with version '3.0.0-preview4.19202.2' from build '20190402.2'
> Update dependencies to latest

- eng/Versions.props
- src/EFCore/DbContext.cs
- src/EFCore/DbSet.cs
- src/EFCore/EFCore.csproj
- src/EFCore/Internal/EntityFinder.cs
- src/EFCore/Internal/IEntityFinder.cs
- src/EFCore/Internal/IEntityFinder`.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/ValueGeneration/HiLoValueGenerator.cs
- src/EFCore/ValueGeneration/HiLoValueGeneratorState.cs
- src/EFCore/ValueGeneration/ValueGenerator.cs
- src/EFCore/ValueGeneration/ValueGenerator`.cs
- test/EFCore.InMemory.FunctionalTests/FindInMemoryTest.cs
- test/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs
- test/EFCore.Specification.Tests/FindTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/FindSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/AsyncSimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/FindSqliteTest.cs
- test/EFCore.Tests/DbContextTest.cs
- test/EFCore.Tests/DbContextTrackingTest.cs
- test/EFCore.Tests/DbSetTest.cs
- test/ef.Tests/AppDomainOperationExecutorTest.cs
- test/ef.Tests/SimpleProjectTest.cs
This covers FindAsync(), AddAsync() and the value generators (3 different commits).
Part of #15184
> Change some main APIs to return ValueTask instead of Task

- src/EFCore.Relational/Migrations/Operations/Builders/ColumnsBuilder.cs
> Fix xml comment in ColumnsBuilder.cs

- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.Specification.Tests/ComplianceTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
> Compliance tests now fail on non-public test classes

- build/templates/default-build.yml
Addresses aspnet/AspNetCore-Internal#2282.
> Do not overwrite TEMP

- src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
- src/EFCore.SqlServer/Metadata/ISqlServerPropertyAnnotations.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerPropertyBuilderAnnotations.cs
- src/EFCore.SqlServer/Metadata/SqlServerModelAnnotations.cs
- src/EFCore.SqlServer/Metadata/SqlServerPropertyAnnotations.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerBuilderExtensionsTest.cs
- Added optional parameters to UseSqlServerIdentityColumn to specify seed and increment
- Added SqlServerAnnotationNames for seed and identity
Fixes #11924
> Identity property configuration

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
Use compatibility_level for feature detection
Unblock scaffolding on Azure SQL DW 
Maybe it is better to prevent scaffolding with SQL DW? 
https://docs.microsoft.com/en-us/azure/sql-data-warehouse/sql-data-warehouse-tables-overview#unsupported-table-features 
fixes #14566
fixes #5553
> SQL Server scaffolding fixes

- src/EFCore.Design/Design/Internal/DbContextOperations.cs
- src/EFCore.Design/Design/OperationExecutor.cs
- src/EFCore.Tools/EntityFrameworkCore.PowerShell2.psd1.in
- src/EFCore.Tools/EntityFrameworkCore.psd1.in
- src/EFCore.Tools/tools/EntityFrameworkCore.PowerShell2.psm1
- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
- src/EFCore.Tools/tools/about_EntityFrameworkCore.help.txt
- src/ef/Commands/DbContextScriptCommand.Configure.cs
- src/ef/Commands/DbContextScriptCommand.cs
- src/ef/IOperationExecutor.cs
- src/ef/OperationExecutorBase.cs
- src/ef/Properties/Resources.Designer.cs
- src/ef/Properties/Resources.resx
- test/ef.Tests/SimpleProjectTest.cs
> Implements "ef dbcontext script" and PS: Script-DbContext

- test/EFCore.Tests/Utilities/TypeNameHelperTest.cs
> Stop using partially open generics in theory data

- src/EFCore.Design/Design/OperationExecutor.cs
@bricelam Looks like this could have been a merge issue between Erik's any my comments.
@dougbu @natemcmaster @JunTaoLuo This will need to go into preview5.
> Fix merge break

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
> Enable reverse engineering of an exsiting Azure SQL Data Warehouse database

- src/EFCore.Relational/Query/PipeLine/EqualsTranslator.cs
- src/EFCore.Relational/Query/PipeLine/IsNullOrEmptyTranslator.cs
- src/EFCore.Relational/Query/PipeLine/RelationalMethodCallTranslatorProvider.cs
- src/EFCore.Relational/Query/PipeLine/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore/Query/PipeLine/QueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosSqlTest.Functions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
- Add string.Concat translator
- Add explicit cast for convert to object nodes
- Ignore ToOrderedQueryable method call
> Query: Bugfixes

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Reverse engineer SQL Server views

- korebuild-lock.txt
Addresses https://github.com/aspnet/AspNetCore-Internal/issues/2279
> Update SDK 2.2

- build/templates/default-build.yml
- aspnet/AspNetCore-Internal#2436
- aspnet/AspNetCore#9767
> Switch to non `-Int` pools and clear NuGet caches

- src/EFCore.Design/Properties/DesignStrings.Designer.cs
- src/EFCore.Design/Properties/DesignStrings.resx
- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
> Scaffold entities with no keys

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
> Stop scaffolding productversion

- src/EFCore.Design/Scaffolding/Internal/CSharpDbContextGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
> Add partial method to the scaffolded DbContext

- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore/Diagnostics/CoreLoggerExtensions.cs
- src/EFCore/Storage/DatabaseProvider.cs
- src/EFCore/ValueGeneration/HiLoValueGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
These were made public but the docs had not been updated.
> Update docs for now-public logger extensions

- src/EFCore.Relational/Query/Pipeline/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SubSelectExpression.cs
- src/EFCore/Query/Pipeline/EnumerableToQueryableReMappingExpressionVisitor.cs
- Fix bug in EnumerableToQueryableMapping
- Make ctor for SelectExpression private and use method to generate new SelectExpression
> [Query] Bug fixes

- src/EFCore/Query/Internal/ExpressionPrinter.cs
adding separate list for parameters without defined name, so we can uniquely identify them based on their index in the list.
> [TINY] minor printer fix - adding support for parameters without name

- src/EFCore/ChangeTracking/CollectionEntry.cs
- src/EFCore/ChangeTracking/CollectionEntry`.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/Internal/StateManagerDependencies.cs
- src/EFCore/DbContextOptionsBuilder.cs
- src/EFCore/Extensions/ConventionModelExtensions.cs
- src/EFCore/Infrastructure/CoreOptionsExtension.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Builders/IConventionEntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/IConventionModelBuilder.cs
- src/EFCore/Metadata/IConventionModel.cs
- src/EFCore/Metadata/IConventionTypeBase.cs
- src/EFCore/Metadata/IMutableModel.cs
- src/EFCore/Metadata/IMutableTypeBase.cs
- test/EFCore.Tests/ChangeTracking/CollectionEntryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/OwnedFixupTest.cs
> Address API Review feedback

- src/EFCore.Relational/Query/Pipeline/SqlExpressions/CaseExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/InExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/OrderingExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SqlConstantExpression.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
Also fixing minor bugs that the tests have exposed
> Enable GearsOfWar query test suite

- src/EFCore/Query/NavigationExpansion/LinqMethodHelpers.cs
No actual changes, just some minor code cleanup.
> Cleanup of LinqMethodsHelpers

- src/Microsoft.Data.Sqlite.Core/SqliteDataRecord.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteDataReaderTest.cs
> Microsoft.Data.Sqlite: Don't call sqlite3_step() after SQLITE_DONE

- src/EFCore/Storage/CoreTypeMapping.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/StoreGeneratedTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/StoreGeneratedSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/StoreGeneratedSqliteTest.cs
- test/EFCore.Tests/ChangeTracking/PropertyEntryTest.cs
PR #15820 will be closed since Andriy suggested a potentially better way to add the feature.
However, I wanted to get the additional test coverage checked in now, with the three tests that explicitly test the new functionality skipped for now.
> Porting tests from #15820

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- ComplexNavigations
- GearsOfWar
> Updating query sql baselines - part 1

- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.InMemory.Tests/InMemoryDatabaseTest.cs
- test/EFCore.InMemory.Tests/InMemoryValueGeneratorSelectorTest.cs
- test/EFCore.Relational.Tests/RelationalEventIdTest.cs
- test/EFCore.Relational.Tests/Update/CommandBatchPreparerTest.cs
- test/EFCore.Relational.Tests/Update/ModificationCommandTest.cs
- test/EFCore.Relational.Tests/Update/ReaderModificationCommandBatchTest.cs
- test/EFCore.SqlServer.Tests/SqlServerEventIdTest.cs
- test/EFCore.Sqlite.Tests/SqliteEventIdTest.cs
> Finalize the model in tests

- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Disable SimpleQuerySqlServerTest.Cache_key_contexts_are_detached

- src/EFCore/DbContext.cs
- src/EFCore/Query/Pipeline/ShapedQueryExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.QueryTypes.cs
- test/EFCore.Specification.Tests/WithConstructorsTestBase.cs
> Query: Make DbQuery API also call AsNoTracking

- Directory.Build.targets
- eng/Version.Details.xml
- eng/Versions.props
- global.json
Part of aspnet/AspNetCore#9720, similar to https://github.com/aspnet/Extensions/pull/1828.
> React to Microsoft.NETCore.App changes

- azure-pipelines.yml
- src/EFCore/Metadata/Builders/EntityTypeBuilder.cs
- src/EFCore/Metadata/Builders/EntityTypeBuilder`.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Cosmos.Tests/Metadata/CosmosBuilderExtensionsTest.cs
- test/EFCore.Tests/Metadata/Conventions/BackingFieldConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/BaseTypeDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/CascadeDeleteConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ConstructorBindingConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ConventionDispatcherTest.cs
- test/EFCore.Tests/Metadata/Conventions/DerivedTypeDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/DiscriminatorConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/EntityTypeAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ForeignKeyIndexConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ForeignKeyPropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/KeyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ModelCleanupConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/NavigationAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/NonNullableReferencePropertyConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/PropertyAttributeConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/PropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/PropertyMappingValidationConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/RelationshipDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ServicePropertyDiscoveryConventionTest.cs
- test/EFCore.Tests/Metadata/Conventions/ValueGeneratorConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/InternalEntityTypeBuilderTest.cs
> Allow removing the discriminator for entity types that are not part of a hierarchy.

- test/EFCore.Relational.Specification.Tests/Query/AsyncFromSqlQueryTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/FromSqlQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
Issue has already been fixed in earlier commit
> enable tests for #15991

- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/OriginalValues.cs
- src/EFCore/ChangeTracking/Internal/OriginalValuesFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/RelationshipSnapshotFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/SidecarValues.cs
- src/EFCore/ChangeTracking/Internal/SidecarValuesFactoryFactory.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/EFCore/Metadata/Internal/IndexedPropertyGetterFactory.cs
- test/EFCore.Tests/Infrastructure/ModelValidatorTestBase.cs
- test/EFCore.Tests/Metadata/Conventions/PropertyMappingValidationConventionTest.cs
- test/EFCore.Tests/Metadata/Internal/PropertyBaseTest.cs
All Cosmos tests fail without this.
> Undo some GetTypeMapping changes to fix non-persisted properties.

- src/EFCore.Relational/Diagnostics/CompositeDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/DbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbCommandInterceptor.cs
- src/EFCore.Relational/Diagnostics/RelationalInterceptors.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Storage/RelationalCommand.cs
- test/EFCore.Relational.Specification.Tests/InterceptionTestBase.cs
Plus some of the refactorings from the abandoned Database.Log PR
Fixes #16199
> Add errors to IDbCommandInterceptor

- src/EFCore.SqlServer/Extensions/SqlServerDbContextOptionsBuilderExtensions.cs
- test/EFCore.Design.Tests/TestUtilities/BuildSource.cs
- test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
This reverts commit cf72e2e2c287fa77de8b6d1e76f73b45ef66685b.
Part of #15642
> Remove UseSqlServer overloads that take SqlConnectionStringBuilder

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
> Simplify concurrent access guard exception 

- src/EFCore.Relational/Query/Pipeline/IncludeCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalCollectionShaperExpression.cs
- src/EFCore.Relational/Query/Pipeline/RelationalProjectionBindingRemovingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryOptimizingExpressionVisitors.cs
- src/EFCore.Relational/Query/Pipeline/ShaperExpressionDedupingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/Pipeline/ShapedQueryExpressionVisitor.cs
- test/EFCore.Specification.Tests/GraphUpdatesFixtureBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeAsyncSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Implement logic to include multiple collections on same level

- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- test/EFCore.Relational.Specification.Tests/TransactionInterceptionTestBase.cs
Fixes #16336 to unblock ASP.NET https://github.com/aspnet/AspNetCore/pull/11626
> Return transaction even if no interceptor registered

- src/EFCore.Cosmos/Infrastructure/CosmosModelValidator.cs
- src/EFCore.Cosmos/Query/Pipeline/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Pipeline/CosmosSqlTranslatingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Pipeline/EntityProjectionExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/KeyAccessExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/ObjectAccessExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/ProjectionExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Cosmos/Query/Pipeline/SelectExpression.cs
- src/EFCore.Cosmos/Query/Pipeline/SqlExpressionVisitor.cs
- src/EFCore/Query/Pipeline/ShapedQueryExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
> Add support for nested navigations in filters

- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
Fixes #16262
@smitpatel also fixed what seems like a bug in the Equals behavior for _projectionMapping.
> Add Equals/Hash/Print support for set operations to SelectExpression

- test/EFCore.Tests/Metadata/Conventions/NonNullableNavigationConventionTest.cs
> Revert incorrect test changes made in infra update

- test/EFCore.Relational.Specification.Tests/TableSplittingTestBase.cs
- test/EFCore.Specification.Tests/FieldMappingTestBase.cs
- test/EFCore.Specification.Tests/GraphUpdatesTestBase.cs
- test/EFCore.Specification.Tests/TestModels/ConcurrencyModel/F1Context.cs
- test/EFCore.Specification.Tests/TestModels/TransportationModel/TransportationContext.cs
- test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/OptimisticConcurrencySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ProxyGraphUpdatesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerEndToEndTest.cs
- test/EFCore.Sqlite.FunctionalTests/LoadSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/ProxyGraphUpdatesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteComplianceTest.cs
- test/EFCore.Tests/ChangeTracking/ChangeTrackerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs
Part of #15318 (Still open for in-memory tests)
See also #16359 and #16360
> Re-enable more non-query tests

- src/EFCore.Cosmos/Query/Pipeline/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Cosmos/Query/Pipeline/CosmosShapedQueryCompilingExpressionVisitorFactory.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryShapedQueryExpressionVisitor.cs
- src/EFCore.InMemory/Query/Pipeline/InMemoryShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Pipeline/QuerySqlGenerator.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/Pipeline/RelationalShapedQueryExpressionVisitorFactory.cs
- src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpansionExpression.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpansionExpressionState.cs
- src/EFCore/Query/NavigationExpansion/NavigationExpansionHelpers.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs
- src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpansionReducingVisitor.cs
- src/EFCore/Query/Pipeline/QueryCompilationContext.cs
- src/EFCore/Query/Pipeline/QueryMetadataExtractingExpressionVisitor.cs
- src/EFCore/Query/Pipeline/QueryOptimizingExpressionVisitor.cs
- src/EFCore/Query/Pipeline/ShapedQueryExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryTaggingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerComplianceTest.cs
> Query: Add support for TagWith in relational layer

- src/EFCore.Relational/Diagnostics/DbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/IDbConnectionInterceptor.cs
- src/EFCore.Relational/Diagnostics/Internal/DbConnectionInterceptorResolver.cs
- src/EFCore.Relational/Diagnostics/RelationalLoggerExtensions.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Migrations/Internal/MigrationCommandExecutor.cs
- src/EFCore.Relational/Storage/IRelationalConnection.cs
- src/EFCore.Relational/Storage/RelationalCommand.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore.Relational/Storage/RelationalTransaction.cs
- src/EFCore.Relational/Update/Internal/BatchExecutor.cs
- test/EFCore.Relational.Specification.Tests/ConnectionInterceptionTestBase.cs
- test/EFCore.Relational.Tests/RelationalEventIdTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
- test/EFCore.Tests/ApiConsistencyTestBase.cs
> Preview7: Remove cancellation token from Close APIs

- test/EFCore.Specification.Tests/ProxyGraphUpdatesTestBase.cs
> Re-enable Save_required_one_to_one_changed_by_reference

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
See https://github.com/aspnet/EntityFrameworkCore/pull/16484
> Use `Literal` instead of `UnknownLiteral` for column type

- src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs
- test/EFCore.Specification.Tests/FieldMappingTestBase.cs
> Take backing field into account when deciding what kind of collection to create

- test/EFCore.Tests/ChangeTracking/Internal/FixupTest.cs
Issue #16483 which is already fixed in 3.0
Issue #16546 which I thought might be fixed, but isn't
> Tests for two recently filed issues

- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.Specification.Tests/ConferencePlannerTestBase.cs
- test/EFCore.Specification.Tests/ConferencePlannerTestBaseData.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ApplicationDbContext.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/Attendee.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/Attendee.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/AttendeeResponse.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/SearchResult.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/SearchResultType.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/SearchTerm.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/Session.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/SessionResponse.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/Speaker.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/SpeakerResponse.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/ConferenceDTO/Track.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/EntityExtensions.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/Session.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/SessionAttendee.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/SessionSpeaker.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/Speaker.cs
- test/EFCore.Specification.Tests/TestModels/ConferencePlanner/Track.cs
- test/EFCore.SqlServer.FunctionalTests/ConferencePlannerSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/ConferencePlannerSqliteTest.cs
Based on code in 3.0 branch of https://github.com/dotnet-presentations/aspnetcore-app-workshop
> Tests for Conference Planner model and queries

- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Ignore convert nodes from nullable to non-nullable

- src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Reverts aspnet/EntityFrameworkCore#16655
Merging this if validation passes to unblock broken build
> Revert "Ignore convert nodes from nullable to non-nullable"

- test/EFCore.SqlServer.FunctionalTests/MigrationsSqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/MigrationsSqliteTest.cs
Based on work here: https://github.com/aspnet/AspNetCore/pull/12258
> Updating Identity model snapshots to real 3.0 versions

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
when DataAnnotations have been requested.
fixes #15677
> Always scaffold [Key] attribute on all involved properties

- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs
> Exclude any indexes with hidden columns from being included in DatabaseModel

- src/EFCore/DbContext.cs
- src/EFCore/Internal/InternalDbSet.cs
- src/EFCore/Query/Internal/CompiledAsyncTaskQuery.cs
- src/EFCore/Query/Internal/QueryCompiler.cs
- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/CompiledQueryInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/CompiledQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/CompiledQueryInMemoryTest.cs
> Compiled query for 3.0

- src/EFCore.Cosmos/Storage/Internal/CosmosTransactionManager.cs
- src/EFCore.InMemory/Storage/Internal/InMemoryTransactionManager.cs
- src/EFCore.Relational/Storage/RelationalConnection.cs
- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/DbContext.cs
- src/EFCore/Infrastructure/IResettableService.cs
- src/EFCore/Internal/IDbContextPoolable.cs
- src/EFCore/Internal/InternalDbSet.cs
- test/EFCore.Relational.Tests/RelationalDatabaseFacadeExtensionsTest.cs
- test/EFCore.Relational.Tests/RelationalEventIdTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/BadDataSqliteTest.cs
- test/EFCore.Tests/DatabaseFacadeTest.cs
- test/EFCore.Tests/Infrastructure/EntityFrameworkServicesBuilderTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> Change IResettableService.ResetStateAsync() to return Task

- src/EFCore.SqlServer/Storage/Internal/SqlServerDateTimeTypeMapping.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
> Tests and small tweeks for DateTime literal generation

- src/EFCore.Design/Design/DesignTimeServiceCollectionExtensions.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/CSharpSnapshotGeneratorDependencies.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGeneratorDependencies.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationsGeneratorTest.cs
- test/EFCore.Design.Tests/Migrations/Design/MigrationScaffolderTest.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Relational.Specification.Tests/MigrationsTestBase.cs
Fixes #16737
Also manually tested add/remove migration.
> Stop assuming model snapshot and model-behind will have generated type mappings

- test/EFCore.Relational.Specification.Tests/MigrationSqlGeneratorTestBase.cs
- test/EFCore.Relational.Tests/Migrations/MigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteMigrationSqlGeneratorTest.cs
Every now and then you just gotta do one of these...
> Clean up migration test SQL assertions

- eng/Versions.props
- src/EFCore.Cosmos/Storage/Internal/CosmosClientWrapper.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
> Update Cosmos SDK to RTM

- eng/Versions.props
This is blocked until we branch for preview8
> Update branding to 5.0.0-alpha1

- eng/Versions.props
https://github.com/aspnet/AspNetCore-Internal/issues/2876
> Update branding to preview 9

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- test/EFCore.InMemory.FunctionalTests/FindInMemoryTest.cs
> Check for no results in ResultEnumerator

- src/EFCore.Design/Design/Internal/CSharpHelper.cs
- src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs
- src/EFCore/Metadata/Internal/IndexExtensions.cs
- src/EFCore/Metadata/Internal/KeyExtensions.cs
This method is new to .NET Standard in version 2.1
> Use StringBuilder.AppendJoin()

- src/EFCore.Tools/EFCore.Tools.csproj
- src/EFCore.Tools/EFCore.Tools.nuspec
> Build: Tweak GeneratedContent code

- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Fixed by new nav rewrite
Resolves #16622
> Query: Re-enable tests for issue#16622

- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
Close #16076
Fixed in new nav expansion
The exception went away and hitting the different bug now.
> Verify Issue#16076 is fixed

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Query: Throw exception for cycle in include path when no tracking query

- src/EFCore.SqlServer/Storage/Internal/SqlServerByteArrayTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs
- src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMappingSource.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpDbContextGeneratorTest.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/RelationalScaffoldingModelFactoryTest.cs
- test/EFCore.Relational.Tests/Storage/RelationalTypeMappingTest.cs
- test/EFCore.Specification.Tests/CustomConvertersTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.Tests/Storage/SqlServerTypeMappingTest.cs
> Fix type mappings for "text", "ntext", and "image"

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
> RevEng: Don't generate nameof that won't compile

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Fix nullability in entity equality

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs
- src/EFCore/Query/QueryableMethodProvider.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
> Return null from Min/Max/Average when nullable type and no rows

- src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryExpressionVisitor.cs
- src/EFCore.Relational/Extensions/RelationalDatabaseFacadeExtensions.cs
- src/EFCore.Relational/Query/AsyncQueryingEnumerable.cs
- src/EFCore.Relational/Query/Internal/QueryingEnumerable.cs
- src/EFCore/Internal/ConcurrencyDetector.cs
- src/EFCore/Internal/IConcurrencyDetector.cs
- test/EFCore.Cosmos.FunctionalTests/ConcurrencyDetectorCosmosTest.cs
- test/EFCore.InMemory.FunctionalTests/ConcurrencyDetectorInMemoryTest.cs
- test/EFCore.Relational.Specification.Tests/Query/SqlExecutorTestBase.cs
- test/EFCore.Specification.Tests/ConcurrencyDetectorTestBase.cs
- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/ConcurrencyDetectorSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Sqlite.FunctionalTests/ConcurrencyDetectorSqliteTest.cs
> Query: Reimplement concurrency detector

- src/EFCore.Relational/Metadata/Conventions/SharedTableConvention.cs
- test/EFCore.SqlServer.FunctionalTests/UpdatesSqlServerTest.cs
> Uniquify index names across all tables

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/QueryableMethodProvider.cs
Resolves #16326
Filed #17036 for clean up
> Query: Treat FromSql as query root in nav expansion

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/CollectionEntry.cs
- src/EFCore/ChangeTracking/EntityEntry.cs
- src/EFCore/ChangeTracking/Internal/IStateManager.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/StateManager.cs
- src/EFCore/ChangeTracking/ReferenceEntry.cs
- src/EFCore/Update/IUpdateAdapter.cs
- src/EFCore/Update/Internal/UpdateAdapter.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
- test/EFCore.Tests/TestUtilities/FakeStateManager.cs
> Delete and insert seed data for dependents when principal is deleted and the FK is set to cascade

- eng/Versions.props
See the [release notes](https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.19221.1-Preview.md).
> Update Microsoft.Data.SqlClient to 1.0.19221.1-Preview

- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- test/EFCore.Relational.Tests/Migrations/Internal/MigrationsModelDifferTest.cs
> Make check constraints work when creating a table

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
> Add a test for #8864

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/GraphUpdatesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/MusicStoreInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/NotificationEntitiesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/PropertyValuesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/ProxyGraphUpdatesInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/AsNoTrackingInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/AsTrackingInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/IncludeAsyncInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/NullKeysInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryNavigationsInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/QueryTaggingInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithSensitiveDataLoggingTest.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryWithoutSensitiveDataLoggingTest.cs
Plus re-enabling many in-memory tests
Part of #16963
> Async collection include for in-memory database

- src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs
- test/EFCore.Tests/ModelBuilding/OneToManyTestBase.cs
> Update the reference when changing type for a shadow property.

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceRelationshipsQueryInMemoryTest.cs
> Basic support for inheritance in in-memory provider

- src/EFCore.InMemory/Query/Internal/InMemoryShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalShapedQueryCompilingExpressionVisitor.CustomShaperCompilingExpressionVisitor.cs
- src/EFCore/Extensions/NavigationExtensions.cs
- src/EFCore/Metadata/Internal/InternalRelationshipBuilder.cs
- src/EFCore/Metadata/MemberIdentity.cs
- src/EFCore/Query/QueryContext.cs
* Made creation of MemberIdentity from INavigation an extension method
* Renamed QueryContext.SetIsLoaded to SetNavigationIsLoaded
> Reacting to API review PR comments

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Design/Migrations/Design/MigrationsCodeGenerator.cs
- src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyExtensions.cs
- src/EFCore.SqlServer/Internal/SqlServerModelValidator.cs
- src/EFCore.Sqlite.Core/Migrations/Internal/SqliteMigrationsAnnotationProvider.cs
- src/EFCore/ChangeTracking/Internal/ChangeDetector.cs
- src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs
- src/EFCore/ChangeTracking/Internal/OriginalValues.cs
- src/EFCore/ChangeTracking/Internal/OriginalValuesFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/RelationshipSnapshotFactoryFactory.cs
- src/EFCore/ChangeTracking/Internal/SidecarValues.cs
- src/EFCore/ChangeTracking/Internal/SidecarValuesFactoryFactory.cs
- src/EFCore/Extensions/PropertyExtensions.cs
- src/EFCore/Infrastructure/ModelValidator.cs
- src/EFCore/Metadata/Internal/ClrPropertyGetterFactory.cs
- src/EFCore/Storage/TypeMappingSource.cs
> Add GetTypeMappingConfigurationSource

- src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- src/EFCore/Query/QueryCompilationContext.cs
> Remove Type parameter from QCC.RegisterTypeParameter

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Extensions/RelationalEntityTypeExtensions.cs
- src/EFCore.Relational/Metadata/Internal/TableMapping.cs
- src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs
- src/EFCore.Relational/Migrations/MigrationsSqlGenerator.cs
- src/EFCore.Relational/TypeForwards.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
> Address more API Review feedback

- test/EFCore.Specification.Tests/DataAnnotationTestBase.cs
> [preview9] Add a test for #14618

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/InheritanceTestBase.cs
> Support OfType/is in in-memory database

- src/EFCore.Cosmos/Query/Internal/CosmosQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteQueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.Relational.Specification.Tests/Query/QueryNoClientEvalTestBase.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.Specification.Tests/Query/FiltersTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeAsyncTestBase.cs
- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.Sqlite.FunctionalTests/BuiltInDataTypesSqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
> Query: Throw better exception message for client eval

- eng/Versions.props
Thanks, @airbreather!
Part of #17355
> [release/3.0] Update NetTopologySuite packages

- eng/Versions.props
> [release/3.0] Update Microsoft.Data.SqlClient

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryLinqOperatorProvider.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
> InMemory: Some refactorings

- eng/Versions.props
- src/EFCore/EFCore.csproj
> Remove System.Threading.Tasks.Extensions

- src/EFCore.Relational/Metadata/Conventions/Infrastructure/RelationalConventionSetBuilder.cs
- src/EFCore.Relational/Metadata/Conventions/RelationalValueGenerationConvention.cs
- src/EFCore.Relational/Metadata/Internal/RelationalPropertyExtensions.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- test/EFCore.SqlServer.Tests/ModelBuilding/SqlServerModelBuilderGenericTest.cs
> Reset ValueGenerated on owned types mapped to a different table.

- src/EFCore/Metadata/Internal/InternalModelBuilder.cs
- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- test/EFCore.Tests/ModelBuilding/ModelBuilderTestBase.cs
- test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs
> Throw when deriving from an owned type.

- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/InheritanceInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/SpatialInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/UpdatesInMemoryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryLoggingSqlServerTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs
Filed #17498 to add logging
Resolves #17245
> Update query logging tests

- src/EFCore.InMemory/Query/Internal/EntityProjectionExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryProjectionBindingExpressionVisitor.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- src/EFCore.InMemory/Query/Internal/InMemoryQueryableMethodTranslatingExpressionVisitor.cs
- src/EFCore/Query/QueryableMethodTranslatingExpressionVisitor.cs
- test/EFCore.InMemory.FunctionalTests/InMemoryComplianceTest.cs
- test/EFCore.InMemory.FunctionalTests/LazyLoadProxyInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/MonsterFixupSnapshotInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/OwnedQueryInMemoryTest.cs
- test/EFCore.Tests/ChangeTracking/Internal/QueryFixupTest.cs
> InMemory: Support for Weak/Owned entityTypes

- src/EFCore.InMemory/Query/Internal/InMemoryQueryExpression.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/ComplexNavigationsWeakQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/GearsOfWarQueryInMemoryTest.cs
- test/EFCore.InMemory.FunctionalTests/Query/SimpleQueryInMemoryTest.cs
> InMemory: Last cleanup

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Add regression test for issue#5008

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#6864

- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindContext.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#7222

- src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs
- src/EFCore/Query/Internal/CompiledQueryCache.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
Part of #12905
[Ask mode template is in email]
> [3.0] Set a default query cache size limit.

- src/EFCore/Infrastructure/ModelSource.cs
- src/EFCore/Infrastructure/ModelSourceDependencies.cs
- test/EFCore.Tests/ModelSourceTest.cs
Fixes #17602
[Ask Mode template is in email]
> [3.0] Use IMemoryCache for model caching.

- test/EFCore.Specification.Tests/Query/IncludeTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeSqlServerTest.cs
> Add regression test for issue#7658

- src/EFCore/Query/ReplacingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Earlier it threw NullReferenceException
Resolves #17437
> Query: Throw translation failed exception when unable to bind a member

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Query: Preserve the return type of FirstOrDefault etc.

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
> Add regression test for issue#17555

- src/EFCore/Extensions/Internal/ExpressionExtensions.cs
- src/EFCore/Infrastructure/ExpressionExtensions.cs
- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- test/EFCore.Specification.Tests/TestModels/Northwind/NorthwindData.cs
> Obsolete RemoveConvert API as it should not be used

- eng/Versions.props
> [release/3.0] Update Microsoft.Data.SqlClient to 1.0.19249.1

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.JoinGroupJoin.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.JoinGroupJoin.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.JoinGroupJoin.cs
> Add regression test for Issue#7906

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
> Add regression test for issue#8999

- src/EFCore.Relational/Query/EntityProjectionExpression.cs
- src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
Also make identifiers nullable when applying defaultIfEmpty
> Add regression test for issue#7973

- src/EFCore.SqlServer/Extensions/SqlServerDbFunctionsExtensions.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerDateDiffFunctionsTranslator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs
Replaces #17226 to target release/3.1
Merging when build passes.
> SqlServer: Implement DateDiffWeek

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#9582

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#10447

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#11023

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
> Add regression test for issue#11453

- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.SqlServer.FunctionalTests/Properties/TestAssemblyConditions.cs
- test/EFCore.SqlServer.FunctionalTests/TransactionSqlServerTest.cs
Clean up TransactionSqlServerTest
> Add a test for #17733

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.KeylessEntities.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestSqlLoggerFactory.cs
- test/EFCore.InMemory.FunctionalTests/Query/AsyncSimpleQueryInMemoryTest.cs
- test/EFCore.Specification.Tests/Query/AsyncSimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsWeakQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/FiltersTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Functions.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.JoinGroupJoin.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.KeylessEntities.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Where.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryTestGeneration/ProceduralQueryExpressionGenerator.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsWeakQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FiltersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/IncludeAsyncSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Functions.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.KeylessEntities.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
Covers EFCore.Specs.Tests Query folder
Resolves #8366
Resolves #8582
Resolves #8722
Resolves #9007
Resolves #9254
Resolves #12574
Resolves #12579
Resolves #12598
Resolves #12786
Resolves #12787
Resolves #12794
Resolves #12806
Resolves #12827
Resolves #12873
Resolves #14900
Resolves #15862
Resolves #16157
Resolves #17240
Close #12889
Close #17243
> Scrub tests

- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
> Cosmos: Make EnsureCreatedAsync behave the same as EnsureCreated

- src/EFCore/Query/Internal/ParameterExtractingExpressionVisitor.cs
- test/Directory.Build.props
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#12456

- src/EFCore/Infrastructure/ModelSource.cs
This approach seems to avoid deadlock in Identity tests
> Use single lock for model caching

- src/EFCore.Relational/Storage/RelationalDatabaseCreator.cs
- src/EFCore/ChangeTracking/NavigationEntry.cs
> Replaces inconsistent Task.FromResult usage with Task.CompletedTask

- build.cmd
- restore.cmd
- test.cmd
> build.cmd: Avoid confusing the cmd argument parser with too many quotes

- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
Enables result verification and adds async versions of the tests.
Resolves #16923
> Fix to #16923 - Test: Improve result verification in OwnedQueryTests

- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.Specification.Tests/ConvertToProviderTypesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
> Add regression test for issue#12556

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
> Add regression test for issue#12942

- src/EFCore.SqlServer/Metadata/Conventions/SqlServerConventionSetBuilder.cs
- src/EFCore.SqlServer/Metadata/Conventions/SqlServerEnumConvention.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Specification.Tests/TestModels/MonsterModel.cs
- test/EFCore.SqlServer.Tests/Metadata/Conventions/SqlServerEnumConventionTests.cs
https://github.com/aspnet/AspNetCore/wiki/Engineering-guidelines
Fixes #15411
> Added CHECK enum columns

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryNavigationsTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/SimpleQuerySqliteTest.cs
> Add regression test for issue#13250

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Add regression test for issue#13590

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserter.cs
- test/EFCore.Specification.Tests/TestUtilities/QueryAsserterBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
> Add regression test for issue#13885

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.ResultOperators.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.ResultOperators.cs
> Add a regression test for issue#14408

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Add a regression test for issue#14040

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.Select.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.Select.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.Select.cs
> Add a regression test for #14186

- test/EFCore.Specification.Tests/Query/FunkyDataQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/FunkyDataModel/FunkyDataContext.cs
- test/EFCore.Specification.Tests/TestModels/FunkyDataModel/FunkyDataData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs
- adding result verification,
- adding SQL verification,
- adding async versions of tests
> Convert FunkyDataTests into AssertQuery

- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
> Add regression test for issue#15097

- test/EFCore.SqlServer.FunctionalTests/LoadSqlServerTest.cs
> Re-enable Sql baseline for loading tests

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test for issue#15137

- src/EFCore.Design/Migrations/Design/CSharpMigrationOperationGenerator.cs
- test/EFCore.Design.Tests/Migrations/Design/CSharpMigrationOperationGeneratorTest.cs
> Modify create table operation comment.

- test/EFCore.Cosmos.FunctionalTests/BuiltInDataTypesCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/CustomConvertersCosmosTest.cs
- test/EFCore.Specification.Tests/BuiltInDataTypesTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/BuiltInDataTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/ConvertToProviderTypesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/CustomConvertersSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsBytesSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/EverythingIsStringsSqlServerTest.cs
> Add regression test for issue#15200

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/Query/QueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Add regression test for issue#15340

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Add regression test for #16107

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> This one is last!

- src/EFCore/Query/Internal/ExpressionEqualityComparer.cs
Related to #17959
Please review,
> Error message for not supported binding

- src/Microsoft.Data.Sqlite.Core/SqliteCommand.cs
- test/Microsoft.Data.Sqlite.Tests/SqliteCommandTest.cs
> Add an intended local variable to SqliteCommand.ExecuteReader()

- src/EFCore/Properties/CoreStrings.Designer.cs
- src/EFCore/Properties/CoreStrings.resx
- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.cs
> Improve exception message for memory leak warning

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
> Add regression test for issue#14772

- All.sln
- azure-pipelines.yml
- src/EFCore.Cosmos/Storage/Internal/CosmosDatabaseCreator.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/EmbeddedDocumentsTest.cs
- test/EFCore.Cosmos.FunctionalTests/EndToEndCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbConfiguredConditionAttribute.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestEnvironment.cs
Clean Cosmos collections instead of deleting them
Reuse Cosmos databases instead of recreating them
Don't uniquify database names when using the emulator
Use a separate account for PRs
Fixes #17925
> Reduce Cosmos flakiness

- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
> Add regression test

- test/EFCore.Relational.Specification.Tests/Query/FromSqlSprocQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/FromSqlSprocQuerySqlServerTest.cs
Assert that exceptions are DbException rather than anything. Also switch to using declarations while we're at it.
Closes #18134
> Tighten FromSqlSprocQueryTest

- src/EFCore.Relational/Query/SqlExpressions/SqlFragmentExpression.cs
- test/EFCore.Relational.Specification.Tests/Query/UdfDbFunctionTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/UdfDbFunctionSqlServerTests.cs
Closes #17918
With more issues like this I can rack up my closed issue count in no time!
> Make SqlFragmentExpression constructor public

- src/EFCore.Design/Design/Internal/OperationLogger.cs
- test/EFCore.Design.Tests/Design/Internal/OperationLoggerTest.cs
> Tools: Dampen SQL logging to verbose again

- src/EFCore.Design/Scaffolding/Internal/CSharpEntityTypeGenerator.cs
- test/EFCore.Design.Tests/Scaffolding/Internal/CSharpEntityTypeGeneratorTest.cs
> RevEng: Fix more invalid nameof code in InverseProperty

- src/EFCore.SqlServer/Extensions/SqlServerModelBuilderExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerModelExtensions.cs
- src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs
- src/EFCore.SqlServer/Metadata/Internal/SqlServerAnnotationNames.cs
- src/EFCore.SqlServer/Migrations/Internal/SqlServerMigrationsAnnotationProvider.cs
- src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs
- test/EFCore.Cosmos.FunctionalTests/ConfigPatternsCosmosTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
- test/EFCore.Specification.Tests/TestUtilities/TestStore.cs
- test/EFCore.SqlServer.FunctionalTests/MemoryOptimizedTablesTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/DbFunctionsSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlAzure/Model/AdventureWorksContext.cs
- test/EFCore.SqlServer.FunctionalTests/SqlAzure/SqlAzureDatabaseCreationTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerDatabaseCreatorTest.cs
- test/EFCore.SqlServer.FunctionalTests/SqlServerMigrationSqlGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerTestStore.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataBuilderExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Metadata/SqlServerMetadataExtensionsTest.cs
- test/EFCore.SqlServer.Tests/Migrations/SqlServerModelDifferTest.cs
Fixes #2969
Fixes #15004
This is pre-approved for 3.1
> Add support for SQL Azure database edition options

- src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
> Query: Preserve Includes when creating entity reference snapshot

- src/EFCore.Sqlite.Core/Infrastructure/SpatialiteLoader.cs
> SQLite: Fix issue with SpatialiteLoader when no fallback RIDs

- test/EFCore.Specification.Tests/Query/GearsOfWarQueryFixtureBase.cs
- test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/Gear.cs
- test/EFCore.Specification.Tests/TestModels/GearsOfWarModel/GearsOfWarData.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs
CityOrBirthName -> CityOfBirthName
> [SMALL] Fixing typo in GearsOfWar model

- src/EFCore.Design/Migrations/Design/CSharpSnapshotGenerator.cs
- src/EFCore.Relational/Migrations/Migration.cs
- test/EFCore.Design.Tests/Migrations/ModelSnapshotSqlServerTest.cs
> Migrations: Handle properties without column type in snapshot

- src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs
- test/EFCore.Cosmos.FunctionalTests/Query/OwnedQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/OwnedQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/OwnedQuerySqlServerTest.cs
> Correctly identify owned entity materialization without owner

- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
> Fix to #17339 - Test: Re-enable Union_over_different_projection_types

- src/EFCore.Tools/tools/EntityFrameworkCore.psm1
Fixes #18304
(Manually verified)
> PMC Tools: Show details for single type when Get-DbContext -Context is $null

- src/EFCore/ChangeTracking/Internal/EntityGraphAttacher.cs
- test/EFCore.Specification.Tests/LazyLoadProxyTestBase.cs
- test/EFCore.Specification.Tests/LoadTestBase.cs
> Set reference navigation properties as loaded when attaching

- eng/Versions.props
> Update Microsoft.Azure.Cosmos to 3.3.2

- src/EFCore/ChangeTracking/Internal/EntityReferenceMap.cs
> Tiny: use null coalescing assignment in EntityReferenceMap

- src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs
- src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs
- src/EFCore.SqlServer/Query/Internal/SqlServerSqlTranslatingExpressionVisitor.cs
- test/EFCore.Specification.Tests/Query/GroupByQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GroupByQuerySqliteTest.cs
> Query: Relational: Throw exception when translating Count with predicate on Grouping

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.SetOperations.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs
> Regression test for constant projection after set operation

- azure-pipelines.yml
- test/EFCore.Cosmos.FunctionalTests/Internal/CosmosDatabaseCreatorTest.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosDbContextOptionsBuilderExtensions.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/CosmosTestStore.cs
- test/EFCore.Cosmos.FunctionalTests/TestUtilities/TestSqlServerRetryingExecutionStrategy.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerDbContextOptionsBuilderExtensions.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/TestSqlServerRetryingExecutionStrategy.cs
Increase retry count
Spread execution between two accounts
> Disable Cosmos tests on PRs

- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
> CLI Tool: Remove dependency group from package

- src/EFCore.Design/build/net461/Microsoft.EntityFrameworkCore.Design.props
> [master] Design: Remove net461 build artifacts

- src/EFCore.Sqlite.Core/Storage/Internal/SqliteDatabaseCreator.cs
- test/EFCore.Sqlite.FunctionalTests/SqliteDatabaseCreatorTest.cs
> SQLite: Assume in-memory databases always exist

- eng/Version.Details.xml
> Pin NETStandard.Library.Ref

- eng/Versions.props
> Update Microsoft.Azure.Cosmos to version 3.3.3

- src/EFCore.SqlServer/Infrastructure/SqlServerDbContextOptionsBuilder.cs
- test/EFCore.SqlServer.FunctionalTests/LoggingSqlServerTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/CompiledQueryCacheKeyGeneratorTest.cs
- test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs
- test/EFCore.SqlServer.FunctionalTests/TestUtilities/SqlServerDbContextOptionsBuilderExtensions.cs
- test/EFCore.SqlServer.Tests/SqlServerDbContextOptionsExtensionsTest.cs
- test/EFCore.SqlServer.Tests/SqlServerOptionsExtensionTest.cs
> Obsolete UseRowNumberForPaging

- eng/Versions.props
> Update to SQLitePCL.raw version 2.0.2

- src/dotnet-ef/dotnet-ef.nuspec
> CLI Tool: Fix bad merge in nuspec

- test/EFCore.Specification.Tests/Query/ComplexNavigationsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs
> [TINY] enable test for #16093

- test/EFCore.Relational.Specification.Tests/Query/NullSemanticsQueryTestBase.cs
- test/EFCore.SqlServer.FunctionalTests/Query/NullSemanticsQuerySqlServerTest.cs
> add regression test for #16955

- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.KeylessEntities.cs
- test/EFCore.Cosmos.FunctionalTests/Query/SimpleQueryCosmosTest.cs
- test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.KeylessEntities.cs
- test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.KeylessEntities.cs
Actual issue has been fixed earlier.
Resolves #17635
> Add regression test for #17635 - GroupBy wants to execute on client when performed on DbQuery (View)

- azure-pipelines.yml
- problem should be specific to our 'master' branch
> Temporarily disable signing validation

- eng/Versions.props
CC @mmitche @dougbu
I'll merge this once we got the all-clear for 3.1-preview3
> Stabilize packages for 3.1

- eng/Versions.props
> Update branding to 3.0.2

- eng/Versions.props
> Update to Microsoft.Azure.Cosmos version 3.4.1

- eng/Versions.props
> Update Microsoft.Data.SqlClient to 1.1.0

- NuGet.config
CC @aspnet/build
Don't merge until we open for 3.0.2
> Cleanup nuget feeds

- azure-pipelines.yml
- eng/Versions.props
Update branding & add trigger for internal release/3 branches
@JunTaoLuo @mmitche PTAL
> Update branding to 3.1.1

- .github/CONTRIBUTING.md
- README.md
- docs/getting-and-building-the-code.md
- docs/security.md
Resolves #16771
Just initial draft for move. Some of the files seems not so relevant now so we can probably drop them. Once this is merged we can improve particular page if we want to.
> Move wiki pages to .md in repo

- src/dotnet-ef/dotnet-ef.csproj
- src/dotnet-ef/dotnet-ef.nuspec
> [release/3.0] Revert dotnet-ef package changes

- src/EFCore.Cosmos/Diagnostics/Internal/CosmosLoggerExtensions.cs
- src/EFCore.Relational/Storage/Internal/DbParameterCollectionExtensions.cs
- src/EFCore/ChangeTracking/ChangeTracker.cs
- src/EFCore/ChangeTracking/Internal/StateManagerDebugStringOptions.cs
- src/EFCore/ChangeTracking/Internal/StateManagerExtensions.cs
- src/EFCore/Internal/DebugView.cs
- src/EFCore/Metadata/Internal/EntityType.cs
- src/EFCore/Metadata/Internal/EntityTypeExtensions.cs
- src/EFCore/Metadata/Internal/ForeignKey.cs
- src/EFCore/Metadata/Internal/ForeignKeyExtensions.cs
- src/EFCore/Metadata/Internal/Index.cs
- src/EFCore/Metadata/Internal/Key.cs
- src/EFCore/Metadata/Internal/KeyExtensions.cs
- src/EFCore/Metadata/Internal/MetadataDebugStringOptions.cs
- src/EFCore/Metadata/Internal/Model.cs
- src/EFCore/Metadata/Internal/ModelExtensions.cs
- src/EFCore/Metadata/Internal/Navigation.cs
- src/EFCore/Metadata/Internal/NavigationExtensions.cs
- src/EFCore/Metadata/Internal/Property.cs
- src/EFCore/Metadata/Internal/PropertyExtensions.cs
- src/EFCore/Metadata/Internal/ServiceProperty.cs
- src/EFCore/Metadata/Internal/ServicePropertyExtensions.cs
- src/Shared/StringBuilderExtensions.cs
To make it easy to view which entities are being tracked together their states and relationships.
Fixes #19109
Example short view:
```
RequiredAk1 {Id: 1} Unchanged AK {AlternateId: ed1c54e9-6e3d-47be-aa0c-3807a69d1342} AK {Id: 1, AlternateId: ed1c54e9-6e3d-47be-aa0c-3807a69d1342} FK {ParentId: a2de1382-93fc-4944-a0ab-d8ce3230c0f4}
RequiredAk1 {Id: 2} Unchanged AK {AlternateId: 665e179f-e4a9-4cd7-b746-ec275f411e83} AK {Id: 2, AlternateId: 665e179f-e4a9-4cd7-b746-ec275f411e83} FK {ParentId: a2de1382-93fc-4944-a0ab-d8ce3230c0f4}
RequiredAk2 {Id: 1} Unchanged FK {ParentId: ed1c54e9-6e3d-47be-aa0c-3807a69d1342}
RequiredAk2 {Id: 2} Unchanged FK {ParentId: ed1c54e9-6e3d-47be-aa0c-3807a69d1342}
RequiredAk2 {Id: 3} Unchanged FK {ParentId: 665e179f-e4a9-4cd7-b746-ec275f411e83}
RequiredAk2 {Id: 4} …
```
> Debug view for the state manager

- test/EFCore.Tests/SimpleLoggerTests.cs
Length of date string changed from November 30 to December 1.
> Fix test break

- src/EFCore.Sqlite.Core/Query/Internal/SqliteByteArrayMethodTranslator.cs
- src/EFCore.Sqlite.Core/Query/Internal/SqliteMethodCallTranslatorProvider.cs
- test/EFCore.Sqlite.FunctionalTests/Query/GearsOfWarQuerySqliteTest.cs
Completes #4601
See https://github.com/aspnet/EntityFrameworkCore/pull/19071#discussion_r350574075
> Support Contains on byte arrays on Sqlite

- eng/Version.Details.xml
> [release/3.1] Sort pinned dependency to bottom (#19277)

- eng/Versions.props
Reverts aspnet/EntityFrameworkCore#19242
Revert and checking into the internal to avoid breaking PRs
> Revert "[release/3.0] Stabilize package versions"
